### ISSUE TITLE
The delete button is scary, because I don't know what it'll do

### ISSUE THREAD

**Issue by Pomax** [mozilla/thimble.mozilla.org#1001]
Creating a project creates a new thimble project, editing files autosaves my project, publishing a project takes what I've written and puts it on the web.

However, deleting does not seem to be this granular, so I'm afraid to press the delete button. Is it going to delete my project _and_ my web-published data? Will I be asked which of the two, or both, I want deleted?

The delete button is scary...

**Comment by gideonthomas** [comment]
This is a great question! How do we indicate to users that once they delete a project, the published version also vanishes?

cc @flukeout

**Comment by flukeout** [comment]
You're scary, @Pomax 

We could indicate it in the javascript confirm for now. "Are you sure? The published version will be deleted also." ... or something to that effect. Down the road I think we want something nicer UI and UX so we can revisit it.

**Comment by comoss** [comment]
Is anyone working on this? I'd be willing to take a stab at it.

**Comment by humphd** [comment]
<img width="980" alt="screen shot 2017-01-24 at 1 16 27 pm" src="https://cloud.githubusercontent.com/assets/427398/22260475/5bf21216-e237-11e6-9095-a89bba51b42e.png">

The string for this text is here: https://github.com/mozilla/thimble.mozilla.org/blob/fa3dde088dc016a562520e62a9df1f5558ba8f70/locales/en-US/messages.properties#L139

**Comment by badrmodoukh** [comment]
I would like to work on this 
Is @flukeout still assigned to this? Can I start working on it?

**Comment by humphd** [comment]
@badrmodoukh it's yours, go for it!

**Comment by flukeout** [comment]
Let's go with this copy...

``Are you sure? The published version of this project will also be deleted."

**Comment by flukeout** [comment]
@badrmodoukh For extra points, we can also display a different message depending on if the project has actually been published.

* If not published - ``Are you sure you want to delete this project?``
* If published - ``Are you sure? This will also delete the published version of this project.``

**Comment by badrmodoukh** [comment]
Is there code available to check whether a project has been published or not?
Or would I need to implement this?

**Comment by Pomax** [comment]
You should be able to tell whether a project is published based on whether or not it has a `project.publish_url` property set.
