### ISSUE TITLE
Suggestion for the website: put "Remix this project" as the main CTA

### ISSUE THREAD

**Issue by LauraReynal** [mozilla/thimble.mozilla.org#1049]
Today, we had about 10 learners using Thimble. We loaded the Website, and the first thing you see is start from scratch. Then everyone is blocked and wondering what to do on the blank page. 
You actually need to scroll down to Remix a project, which means that some kids did not see it was possible. 

We would suggest to reverse this order to have the main CTA to be "Remix" instead of start from scratch.

**Comment by hannahkane** [comment]
Thanks for this suggestion. I think at some point we'll want to do a user research study on Thimble users, to understand what the common pathways are and how we can differentiate/serve both the "remixers" and the "start-from-scratchers". Know anyone who could help with that? :) :) :)

Also, wanted to reference the "galleries" line item of the Thimble roadmap (http://bit.ly/1Q9yokU). Right now, we are not providing a lot of remix pathways—just the three projects we've chosen to highlight on the homepage. Once we build gallery features (as well as search/browse functionality), I think that will add a rich new experience for remixers.

**Comment by humphd** [comment]
cc @flukeout
