### ISSUE TITLE
Make authentication pluggable

### ISSUE THREAD

**Issue by gideonthomas** [mozilla/thimble.mozilla.org#1069]
Having the thimble and publish servers dependent on `id.webmaker.org` which in turn depends on `login.webmaker.org` makes the UX and DevX pretty bad. Instead, we should probably do the following:
- For local dev, we should probably allow you to turn off auth completely or provide mock credentials.
- For prod/staging, we should use something like `passport.js` and allow authentication from common oauth2 servers like github, facebook, twitter, etc., in addition to `id.webmaker.org`

**Comment by gideonthomas** [comment]
@xmatthewx do you have any suggestions for this (or if we should even do this)?

**Comment by xmatthewx** [comment]
cc'ing @ashleygwilliams for input

**Comment by humphd** [comment]
From https://remysharp.com/2015/09/16/jsbin-toxic-part-3

<blockquote>In the end the only way to register with JS Bin now is via GitHub. I don't like this, but it does lean on GitHub's verification process. It doesn't kill the issue 100%, but it reduced our sign-up rate significantly and we only have the odd one arsehat come through (which I also then report back to GitHub).</blockquote>

His whole series on the perils of running jsbin are interesting, too.

**Comment by gideonthomas** [comment]
Closing this until we figure out what our org strategy for auth is
