### ISSUE TITLE
Research integration of COPPA guidelines into Thimble workflows

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.mozilla.org#1114]
Started here
https://docs.google.com/document/d/1qnt9Pr7SDrW5lbg7Io10iQ-iJ1PmmB9kfSQc_2g5qkQ/edit

cc @hannahkane

**Comment by hannahkane** [comment]
Added some comments.

**Comment by humphd** [comment]
https://twitter.com/gideonwilliams/status/646331659881680896 + https://twitter.com/gideonwilliams/status/646331332805677056

**Comment by jgmac1106** [comment]
I added the relevant TOS under the examples of how others have solved the
problem. Something happened and the strikethrough went on the Edmodo TOS.
Figure you may eventually need for legal.

**Comment by khanh2003** [comment]
Note: If the teacher has to create a class and accounts for students, it'll be more difficult to use.
Let the students do it.
