### ISSUE TITLE
Alternative to right-click in file pane

### ISSUE THREAD

**Issue by my2iu** [mozilla/thimble.mozilla.org#1135]
Can you make an alternative to right-clicking in the file pane? When giving instructions to kids, right-clicks are always problematic because there's no right-click on Macs (plus, there's always someone who swapped their mouse buttons or who brought a tablet or something). So then you have to give an extended explanation about what to do if you can't right-click.

Maybe you could have a button to the right of the filenames (you could make it so that the button only appears on a hover or when the file is selected or something so that the UI doesn't get too busy). The button could then be used to trigger a "right-click" context menu.

That way, I only need to create a single set of instructions for how to do file operations.

**Comment by flukeout** [comment]
Thanks for the feedback @my2iu, our original designs had something similar to what you're describing...

![image](https://cloud.githubusercontent.com/assets/25212/10025266/4a1191c4-6110-11e5-8988-11cf6d608810.png)

However, to implement this requires a fairly serious re-write of the Brackets file-tree (or implementing our own) so we opted to leave it as is. We've recently contemplated tackling this so your feedback is very helpful.

**Comment by flukeout** [comment]
I wonder if we could just add a little icon and use the existing right-click menu feature when someone clicks it. That might be an easier change. I'll look into it.

**Comment by Pomax** [comment]
What about a "click when already selected"? The first click opens the file in brackets, and then a subsequent click pulls up the little menu?

**Comment by flukeout** [comment]
That could work too. Do you know where in the code we fire up the dialog?

**Comment by humphd** [comment]
The way that these menus work is that you register a command (see `src/command/Commands.js`) or a menu item, see https://github.com/mozilla/brackets/blob/master/src/command/DefaultMenus.js#L239.

**Comment by flukeout** [comment]
Just to follow up, @Pomax was hacking on this yesterday and we realized that a 'two-click' is already used for renaming the file. I'm still OK with something like was mocked up here...

<img width="244" alt="image" src="https://cloud.githubusercontent.com/assets/25212/23075073/f99f6020-f4ef-11e6-9e9c-59dbe9414418.png">

Maybe not with that icon since it won't really be a dropdown menu, but something similar. We could just show it for the item that is currently selected in the filetree.

Thoughts?

**Comment by Pomax** [comment]
I think that could work, with the icon only showing on mouse hover/tap-and-hold?

**Comment by Pomax** [comment]
closing this in favour of "when people really need this, they'll let us know"

**Comment by flukeout** [comment]
This request came from an educator, saying kids don't know how to right-click. Honestly using someone else's laptop with a trackpad, sometimes I don't either.

**Comment by Rajat-dhyani** [comment]
i think i can work on this if that's okay?
Just to sum up all the discussion above this is what needs to be done here : 
* add a drop down icon just next to file names in the tree.
* show the drop down icon on mouse hover.
* add all the right click option to the drop down menu.

**Comment by flukeout** [comment]
Sure thing @Rajat-dhyani - just to clarify..

* We already have a menu that opens when you right-click
* We want to also allow showing the same menu by clicking on an icon next to the filename

**Comment by my2iu** [comment]
Doing anything on a mouse hover isn't a great fix. The kids today are from the iPad generation. They're using their touchscreen Chromebooks to do their stuff and will never see mouse hover prompts. That fix exhibits the same underlying problem as the original right-click issue.

**Comment by flukeout** [comment]
Hey @my2iu - thanks for jumping in! We aren't planning to make any of the behaviour dependent on a hover state. Each file, when selected, will have a small icon, as pictured here (roughly)...

<img width="220" alt="image" src="https://user-images.githubusercontent.com/25212/26885962-f23c239e-4b58-11e7-89cd-ef4120b3b688.png">

When the icon is clicked, or tapped, the menu will open. We'll be re-using the same menu that we currently show when someone right-clicks, but just giving an additional click, or touch-based, way to get to it. Does that clear things up?

**Comment by Rajat-dhyani** [comment]
okay got it.....thanks will now work on this and get back to you on it. 👍  @flukeout

**Comment by Rajat-dhyani** [comment]
Sorry it took me some time, I was afk last weak. I have added a fix to this. 
Please review it. @flukeout @Pomax 
Thank you 😄

**Comment by flukeout** [comment]
This is addressed in https://github.com/mozilla/brackets/pull/838
