### ISSUE TITLE
Handling a broken FS / IndexDB in Firefox

### ISSUE THREAD

**Issue by Pomax** [mozilla/thimble.mozilla.org#1136]
I tried opening thimble.mozilla.org today in a regular firefox session, but got

```
[Bramble] browser filesystem inaccessible (needs to be re-formatted, or permission denied due to private browsing mode. bramble.js:4:3478
[Bramble Error] Object { name: "EFILESYSTEMERROR", code: "EFILESYSTEMERROR", errno: 1001, message: "unknown error", stack: "e@https://mozillathimblelivepreview…" } main.js:4:27317
[Bramble] browser filesystem inaccessible (needs to be re-formatted, or permission denied due to private browsing mode. bramble.js:4:3478
[Bramble] browser filesystem inaccessible (needs to be re-formatted, or permission denied due to private browsing mode. bramble.js:4:3478
[Bramble] browser filesystem inaccessible (needs to be re-formatted, or permission denied due to private browsing mode.
```

@humphd suggested trying a `Bramble.formatFileSystem()`, which yielded:

```
<< Bramble.formatFileSystem()
>> undefined
>> Filer error:  Object { name: "EINVAL", code: "EINVAL", errno: 18, message: "IndexedDB cannot be accessed. If pr…", stack: "e@https://mozillathimblelivepreview…" }
```

So it looks like, for _some_ reason, my IndexDB for thimble.mozilla.org got damaged, and getting back to a working site is far more work than we can expect regular users to perform.

**Comment by humphd** [comment]
For whatever reason, Firefox IndexedDB databases can become "wedged" and refuse to open.  There are a few bugs filed on this in Bugzilla, for example https://bugzilla.mozilla.org/show_bug.cgi?id=944918.  How to fix it...somehow one has to wipe their site-specific data and let the db get recreated.  The only data-loss that's going to happen is anything that was done while not authenticated, since we don't send these files to the server.

**Comment by humphd** [comment]
I notice a bunch of bugs that look like they are related to this in https://bugzilla.mozilla.org/buglist.cgi?component=DOM%3A%20IndexedDB&product=Core&bug_status=__open__

**Comment by humphd** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1143003#c21 might offer a workaround to unwedge it

**Comment by Pomax** [comment]
in a bizar twist, if I run FF dev edition on a new profile, things work. If I run plain FF on that same profile, I keep getting the indexdb errors
