### ISSUE TITLE
Design focus group to present, discuss and learn from educators about Thimble in the Classroom features.

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.mozilla.org#1148]
We need to..
- [ ] Finalize the wireframes in #1147
- [ ] Make a list of people we'd like to invite and invite 'em
- [ ] Figure out a good format
  - Google presentation?
- [ ] Come up with a list of discussion questions
  - [ ] What about a form to fill out
- What else...

cc @hannahkane

**Comment by flukeout** [comment]
I started a doc here https://docs.google.com/document/d/1VA3xM4dBpaVPFgVXUjdxfjiTCk2rak-uwC72VJmIOT0/edit

**Comment by hannahkane** [comment]
Nice, @flukeout. Added some comments.

**Comment by hannahkane** [comment]
@flukeout - should we close this ticket here, and potentially open a new one in the Teach repo at some point?
