### ISSUE TITLE
Discuss ways for teachers to view the code of unpublished projects created by their students.

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.mozilla.org#1149]
Here's a user story...
- "As a teacher, I want to see the code that my students are working on in projects they haven't published yet."

We'd like to explore the concept of granting teachers special powers to be able to view their students' in-progress projects via the editor, but without being able to make changes. This would allow them to check in and see what a student is up to and what they are struggling with.

In a hypothetical scenario, a student could paste the URL to their in-progress project `ie. https://thimble.mozilla.org/user/flukeout/14978` into some special interface which would grant a teacher the ability to view it.

Can we get an estimate of how much work this would be to implement? What other considerations are there and what sorts of additional specifications do we need to provide to help estimate this?

cc @humphd @gideonthomas

**Comment by gideonthomas** [comment]
We did some brainstorming here: https://docs.google.com/document/d/14KRnhDUmfVl9SmoYJKJ0GIsB0_thx30FKbIs60fKMeg/edit
