### ISSUE TITLE
Track how many times a project was remixed.

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.mozilla.org#1172]
It would be handy to see how many times a project was remixed.

**Comment by flukeout** [comment]
Some more thoughts
* Let's put this information in the ``projects`` table, where the records are more permanent (instead of ``publishedProjects``
* Going further, it might make sense to keep remix information in a ``remixes`` table, then we can track the date of each individual remix action, or maybe just keep track of remixes per day
  * This would allow us to have a better idea of what projects are 'trending' instead of keeping just an absolute count
  * In the past, when we've tracked absolutes, the same few projects kept being at the top of the list (for likes, and remixes) and it stopped being interesting & meaningful

**Comment by Pomax** [comment]
keep in mind that it'll end up being a recursive check, though, so it's going to be a fairly expensive query

**Comment by flukeout** [comment]
@Pomax This issue in particular is just about keeping track of when a thing was remixed, and not about tracking a chain of remixes, which is where your consideration would come into play. I'm not sure if that remix attribution ticket is filed anywhere yet.

**Comment by hannahkane** [comment]
+1 to getting trending data vs. just absolutes. Same principle would apply to views and likes and any other interaction data we're tracking in the future.

**Comment by gideonthomas** [comment]
Discussion moved to https://github.com/mozilla/thimble.mozilla.org/issues/1546
