### ISSUE TITLE
[STAGING] Styles set in a LESS file aren't immediately reflected in the preview.

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.mozilla.org#1174]
**Steps to reproduce**
- Create a project with a linked LESS file 
  - On staging you can remix this one http://bramble-staging.s3-website-us-east-1.amazonaws.com/flukeout/32/
- Make a change to the LESS file
- It won't appear in the preview until you click the index.html file in the file tree

![less3](https://cloud.githubusercontent.com/assets/25212/10402482/85d0741a-6e7a-11e5-9a3e-642c3a08b6ba.gif)

cc @humphd

**Comment by humphd** [comment]
I'll see if I can fix this in the next milestone.

**Comment by humphd** [comment]
This seems to also happen with markdown and html files, where changes to the generated html are not automatically caught and applied (it should be updating the preview when the file changes on disk).
