### ISSUE TITLE
Explore ways to track anonymous usage

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.mozilla.org#1201]
Currently we're only tracking projects created by authenticated users in our database. This gives us an incomplete view of Thimble use - as many projects are created anonymously.

What if we saved all projects that are created anonymously in the database under one special user. We could keep track of all of the same kinds of information. 

cc @humphd @gideonthomas

**Comment by gideonthomas** [comment]
What kind of information do you want to track for anonymous users?

**Comment by Pomax** [comment]
Alternatively, we could create a dedicated GA event for anonymous creation, and query google analytics for that information

**Comment by humphd** [comment]
Yes, I'd vote for a custom GA event here.  Will that work for your needs, @flukeout?
