### ISSUE TITLE
Add "camera" icon to Add File Menu to highlight selfie feature

### ISSUE THREAD

**Issue by humphd** [mozilla/thimble.mozilla.org#1215]
In the dashboard, I see very few people taking selfies.  I wonder if they don't know it exists?  What if we put a camera icon beside the green `+`, and broke it out of the `Upload...` dialog (or left it there, but _also_ but it in the top level)?  I wonder if it would spark people to try it more?

I think this icon is well known at this point.  From Twitter:

![screenshot 2015-11-03 21 36 09](https://cloud.githubusercontent.com/assets/427398/10928044/28a3c492-8273-11e5-97d8-f9908cbc6b9e.png)

cc @cassiemc, @hannahkane, @flukeout

**Comment by hannahkane** [comment]
Next to the + sign doesn't seem exactly right to me, since it's not a critical feature that people will be looking for often. But what if we added it to the + menu, so it said HTML, CSS, JavaScript, Take a Selfie, and then Upload?

**Comment by jgmac1106** [comment]
We also have no projects that model the use of the selfie tool.

We need one simple project that uses this tool.

**Comment by jgmac1106** [comment]
I have been watching my students use the selfie tool a bit and it is problematic as you can do nothing post-production to the image. Without a basic ability to crop the photo or choose portrait or landscape you end up with stretched images.

You almost have to plan your design around the limitations of the selfie tool. I see my students either: using stretched out images or b: uploading different images after they can format them.

**Comment by humphd** [comment]
@jgmac1106, we might want to split your comments off into a new bug, since it expands the scope of this bug.  Question though: how is this different than any image on the web?  If I upload an image and set both a width and height, I'll always get stretched images (i.e., improper aspect ratio).  There are JS libraries we could add to the Image Viewer in Brackets that let you crop or otherwise manipulate images (e.g., https://fengyuanchen.github.io/cropper/).  Should we?  I'm not sure, and I'd be interested to hear from others on this (@Pomax, @hannahkane, @flukeout).

**Comment by humphd** [comment]
Let's add "Take a Selfie..." to the `+` icon menu.

**Comment by waseem18** [comment]
Hello @humphd ,

I would like to work on this. 

Thank You.

**Comment by flukeout** [comment]
Hello @waseem18 - that's great, let us know if you want any assistance or guidance.

**Comment by humphd** [comment]
We're going to close this for now.
