### ISSUE TITLE
Redirect thimbleprojects.org/user/<id>/remix to thimble.mozilla.org/<id>/remix

### ISSUE THREAD

**Issue by Pomax** [mozilla/thimble.mozilla.org#1221]
JSbin gives users the option to see "the page" or "the editor with that page", which a feature I find is rather missing for thimble projects. You can't just add `/remix` to a thimble published URL and get to the editor, you actually need to substitute the cloudfront part with "thimble.mozilla.org", which is more than we can expect users to do. While there is a remix button, simply "getting the link" to drop in a facebook message or stackoverflow question is not possible without jumping through hoops

**Comment by humphd** [comment]
We need some redirects like this.

**Comment by gideonthomas** [comment]
@humphd i feel like these are two different issues. The redirect itself needs to happen on S3, so I'm removing the good first bug label on this. The other issue about redirecting urls, can we file separately and discuss there?

**Comment by Pomax** [comment]
We could update the S3 404.html so that it does a redirect to the correct domain if it sees it's loading for a `/remix` page
