### ISSUE TITLE
Fix or change tutorial styling so that images don't extend over the edge of the tutorial.

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.mozilla.org#1229]
This is what happens right now, on an image that isn't particularly wide...

![image](https://cloud.githubusercontent.com/assets/25212/11020705/81f057e0-861f-11e5-9f3c-0cfed0c65a8f.png)

Let's have it do something nicer.

**Comment by flukeout** [comment]
I'll verify if this is still a thing.

**Comment by flukeout** [comment]
Confirming that this is still happening and requires a fix.

**Comment by edyedy123** [comment]
Id like to work on this

**Comment by flukeout** [comment]
Sounds good @edyedy123 - we'll need to set some kind of ``max-width`` property for these images.

**Comment by itaditya** [comment]
Hey @edyedy123 , if you aren't working on this issue now , can I fix it ?

**Comment by edyedy123** [comment]
Sorry @itaditya IL be working on this bug today.

**Comment by gideonthomas** [comment]
@itaditya maybe you might find a bug that you are interested in fixing from [this list](https://github.com/mozilla/thimble.mozilla.org/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20label%3A%22good%20first%20bug%22%20-label%3A%22assigned%20to%20contributor%22)

**Comment by edyedy123** [comment]
Hey, i cant seem to be able to find where this bug is. When I create a new project on thimble, and add any images they don't go out of frame like in your picture. Could you direct me to where on thimble this is happening?

**Comment by edyedy123** [comment]
never mind, I see the problem, the css has a class border that has a max width that I was using, but nothing for images in general, I will add it.

**Comment by gideonthomas** [comment]
Fixed with #1701
