### ISSUE TITLE
UX for moving files into folder makes you move your mouse too much.

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.mozilla.org#1231]
The click area for the folder I want (left) and the OK action (right) is too far apart and is annoying.

A few suggestions
- We can make this popup narrower
- We can make it so the clickable area for the folder extends all the way across the box
- We can auto-select the next folder in the list after root (if moving from root)

![image](https://cloud.githubusercontent.com/assets/25212/11020721/1af47cf0-8620-11e5-84c5-cc5358daf528.png)

**Comment by gideonthomas** [comment]
Moved to #1352
