### ISSUE TITLE
Provide option to disable auto-enclosing tags

### ISSUE THREAD

**Issue by hannahkane** [mozilla/thimble.mozilla.org#1262]
From a tweet: https://twitter.com/agentrockstar11/status/666887017356095488

**Comment by jgmac1106** [comment]
I too would like this. As a novice I often write my content first and then
go back and tag.
I find myself constantly cutting and pasting closing tags.

**Comment by humphd** [comment]
This is really easy to do.  The question is, what we want in the way of UI, @flukeout?  Should I add another slider to the gear menu?

**Comment by humphd** [comment]
Let's start by doing this as an extension for this.

**Comment by cgsingh** [comment]
I might be interested in attempting to add this feature, depending on the scope of it.

Are you looking for something like this:
![autoenclosetags](https://cloud.githubusercontent.com/assets/14262279/23076545/ead893d0-f50e-11e6-885b-828ba34e70ad.png)

And can anyone tell me where the code for the auto-enclosing tag is?

**Comment by Pomax** [comment]
That sounds great @cgsingh! I think @flukeout has all the details on where to make your change for this

**Comment by humphd** [comment]
It's controlled in Brackets by a preference on CodeMirror:

https://github.com/adobe/brackets/blob/40f96c3c348101181e2557c2c6aec71490c14618/src/editor/Editor.js#L144-L166

And we are setting it here:

https://github.com/mozilla/brackets/blob/master/src/extensions/default/bramble/main.js#L103-L104

**Comment by cgsingh** [comment]
I have the UI built and some functionality:
`//Auto-enclose tags toggle
	$("#auto-tags-toggle").click(function() {
	  var $autoTagsToggle = $("#auto-tags-toggle");
	  
	  if (!$autoTagsToggle.hasClass("switch-enabled"))
	  {
		$autoTagsToggle.addClass("switch-enabled");
	    // - call function here
	  }
	  else
	  {
		$autoTagsToggle.removeClass("switch-enabled");
		// - call function here
	  }
	  
      return false;
    });`

Can anyone tell me where I can write the function to do this:
`PreferencesManager.set("closingTags", false);`
Because that line will solve the problem.

**Comment by gideonthomas** [comment]
@cgsingh you would similarly call `bramble.setAutoCloseTags(true or false)` in your code above. Now, obviously, the `setAutoCloseTags` function does not exist yet, so, you would need to add it to bramble. That change is something you will need to make in the Brackets repository. If you follow [this patch](https://github.com/mozilla/brackets/pull/378/files) as a guide, it's very similar to what you want to do, except it was for `wordWrap`. You will need to customize it for `closeTags`. Once you make those changes in the Brackets, run `npm run build` in Brackets and `npm start`. Then, `bramble.setAutoCloseTags` will now be a function that is available for Thimble to use and your code above will work.

Let us know if you need any more information.

**Comment by cgsingh** [comment]
@gideonthomas Okay, so just copy what was done in that patch but base it around what I want (autocloseTags).

**Comment by cgsingh** [comment]
@gideonthomas In that patch, can you tell me what function in it "can" be called in Thimble? It's very confusing. I've replicated that for my autoCloseTags version but I don't know what to call. :/

**Comment by humphd** [comment]
It's confusing, and we don't have good docs on it.  I'll try to explain it:

* Thimble uses an API for Bramble defined in the mozilla/brackets repo in `src/bramble/client/main.js`, which gets built and loaded at run time from `dist/bramble.js` on the Brackets server.  This file is what creates and controls the editor iframe, and lets Thimble (the hosting app) talk to Brackets.
* Communication between Thimble and Brackets happens using something called a `MessageChannel`, which is like a socket between two windows.  Each side can pass (i.e., `postMessage()`) and receive (i.e., `on('message')` events) data to each other.
* If you want a function to get called in Bramble from Thimble, you start by creating a new function in the Bramble API, like this: https://github.com/mozilla/brackets/pull/378/files#diff-878090be7f48acda4fa38b7440388092R610.  You have to pass a unique message type (string) so that Brackets knows what you want it to do.
* On the Brackets side you receive this message here: https://github.com/mozilla/brackets/pull/378/files#diff-ff6f9f7c4c8b8efa6a41925f0fbe77d3L59, and you have to write a `switch` case for your message string.
* At that point, you can call Brackets code to do whatever you want.

**Comment by cgsingh** [comment]
@humphd Okay, so only create the function in main.js and add the switch case in Remotecommandhandler.js? I'm browsing this from my phone because I'm away right now, and can't view the links you gave thoroughly, sorry if I missed something.

**Comment by cgsingh** [comment]
@humphd @gideonthomas Can you tell me how I can return a value? wordWrap uses `bramble.getWordWrap();` and this seems to be defined in `brackets/src/editor.Editor.js`. `Editor.getWordWrap = function (fullPath) {
        return PreferencesManager.get(WORD_WRAP, _buildPreferencesContext(fullPath));
    };`
I attempted to make one myself, but it's not being detected.

**Comment by humphd** [comment]
You don't need to return anything, you're just enabling/disabling it (i.e., calling the method implies the result when the callback fires).

**Comment by cgsingh** [comment]
@humphd I have the enabling and disabling working for the close tags, however, I'm pretty sure I'm supposed to remember what state the close tags is in for when I refresh the editor so that the toggle is switched off or on accordingly

**Comment by cgsingh** [comment]
@humphd Also, the editor/bramble, is not remembering the state when I refresh the browser unlike the other toggles...

**Comment by humphd** [comment]
Please go back and re-read this patch more closely: https://github.com/mozilla/brackets/pull/378/files  In it you'll see that we add state management to `src/bramble/client/StateManager.js` and then use it in `src/bramble/client/main.js`, see all instances of `_state.wordWrap`.  You basically need to follow this pattern, and store the state that way, then pass it to Brackets on startup to initialize it.

**Comment by gideonthomas** [comment]
@cgsingh I would also suggest that you open up a [WIP] (work in progress) pr(s) with whatever you have already done even if it doesn't work completely, since it might be easier for us to help you out if we see code.
