### ISSUE TITLE
Tutorial tab is still visible even if the tutorial.html file has been deleted.

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.mozilla.org#1279]
See here, a project with a tutorial that I just deleted...
![image](https://cloud.githubusercontent.com/assets/25212/11484621/df3a6e4a-9763-11e5-88bc-7fb07f14bffa.png)

Refreshing returns things to normal.

**Comment by errietta** [comment]
Can i take a look? alsocan you tell me what the event is that is called when a file is deleted :smile:

**Comment by humphd** [comment]
The code for this in Thimble lives here:

https://github.com/mozilla/thimble.mozilla.org/search?utf8=%E2%9C%93&q=tutorialRemoved

This `tutorialRemoved` event comes from Bramble, here:

* https://github.com/mozilla/brackets/blob/master/src/extensions/default/bramble/lib/Tutorial.js
* https://github.com/mozilla/brackets/blob/master/src/bramble/BrambleEvents.js#L61
* and see both calls to `genericFileEventFn("tutorialRemoved", ...)` in https://github.com/mozilla/brackets/blob/master/src/bramble/client/main.js#L677 and L696

**Comment by bkim49** [comment]
I would like to work on this bug!

**Comment by Shank09** [comment]
I'll try to tackle this bug. If no one is working on it. :)

**Comment by flukeout** [comment]
Go for it @Shank09

**Comment by humphd** [comment]
NOTE: @MargarytaChepiga has a PR coming soon that fixes #1596, which might be related to this.

**Comment by Shank09** [comment]
I think @MargarytaChepiga solved this issue by solving #1596. However the pull request was accidentally opened in Adobe's brackets instead on Mozilla's brackets.  

https://github.com/adobe/brackets/pull/13121

**Comment by humphd** [comment]
@MargarytaChepiga what ever happened with this bug and your fix?  Did you eventually get it done against Mozilla's Brackets?  If so, can we close this?  If not, can you please do that?

**Comment by humphd** [comment]
Merged in Brackets https://github.com/mozilla/brackets/pull/693
