### ISSUE TITLE
Brainstorm solutions for offline needs

### ISSUE THREAD

**Issue by hannahkane** [mozilla/thimble.mozilla.org#1283]
Spoke with Melissa from #glccodeday, who loves Thimble, but would like to see a local version to solve problem of sometimes having no or spotty internet connections at events. In her use case, she doesn't need ability to publish without internet, but would like for learners to be able to edit and save locally (with expectation that they'd publish later, when they have internet access).

Let's brainstorm some possible solutions in the comments.

/cc @humphd @flukeout

**Comment by gideonthomas** [comment]
Discussion should probably continue here instead: https://github.com/mozilla/thimble.mozilla.org/issues/1459
