### ISSUE TITLE
UX Improvements for My Projects List

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.mozilla.org#1289]
We've had a lot of discussion about some of the features and improvements we'd like to see:

**Important**
- Indicate if a project is published, and if it is...
  - Show the link so you can copy & paste it or click it to open the project
  - Have a way to Remix the project directly
- Show a thumbnail of the project
  - For the dashboard, this is possible for published projects only, since they have a public URL and can be rendered into an iframe. 
- Ability to open multiple projects from this view into new tabs (via right-click menu or command+click) - we can't do this now
- Reduce the fear of the Delete button!
  - I'm always scared when pruning my project list because I feel like I'll make a mistake I can't recover from. I think there are a few reasons
    - The delete button is far away from the project name, so I feel like I have to triple-check I'm deleting the right thing.
    - There is no undo feature

**Other Enhancements**
- Add folders or some organization structure to this list?
- Search / Sort
- Ability to Rename a project
- Expose some possible remixable projects from this view (like the projects on the homepage)
  - How will we pick these?
  - Maybe this could be dismissable or a little carousel, so you're not always seeing the same stuff. 

cc @hannahkane @humphd Ping so that you know I've moved this over here.

**Comment by hannahkane** [comment]
Awesome list. I like the idea of a dismissable set of remixable projects, near the "Start a new project" button.

Would add that we may need to accommodate the "old" thimble projects that will be migrated, as per #509. Will we group them separately, or otherwise indicate to the user that they were made with "old" Thimble? Perhaps not necessary if they work 100% as expected—could be a seamless experience for users—but if they behave any differently than new Thimble projects, we may want to provide a visual cue.

Also, do we have a pagination solution for extra-long lists of projects?

**Comment by flukeout** [comment]
@hannahkane For now, the page just scrolls if you've got a lot of stuff. I'm going to dig up some of the old UX designs I had. In our next stand we should go through this list of features and changes with the rest of the team so we can get an idea of how much effort each would take.

**Comment by flukeout** [comment]
@hannahkane Are we planning to auto-import all old Thimble stuff? In that case I think it would be nice to have some kind of notice at least the first time that users see their Projects list. Let's figure out how much effort it would be to do that from a technical standpoint.

We could also just add a dismissable message along the top of that view for users that suddenly have new projects. Something like..

``You ma notice some new projects in your list. That's because we've imported them from the Old Thimble. You can edit them in the new Thimble now. [Ok, Got it]``

That might be easiest.

**Comment by hannahkane** [comment]
A one-time message could be the perfect solution. My assumption is that we're auto-importing old Thimble projects, but you know what they say about assumptions. Maybe @jbuck or @cadecairos could verify?

**Comment by gideonthomas** [comment]
https://github.com/mozilla/thimble.webmaker.org/issues/1145

**Comment by hannahkane** [comment]
From a community member regarding the My Projects page: "I wind up creating lots of extra versions of the same thing and then can’t tell which is the original. I would be great if there was a thumbnail, the ability to go to the published or remix site and finally an option to delete multiple project at once."

**Comment by flukeout** [comment]
Via @jgmac1106 

>I agree with @khan2003 you the My Projects page needs some serious love. I
have so many projects now I can spend too much time looking for one I want.
Plus you can't right click to open in a new tab so your navigation path has
to go project>my projects>a project>my project>open another project.

**Comment by flukeout** [comment]
Lots of good starter bugs here, so I'll break this out into smaller chunks.

**Comment by flukeout** [comment]
I'm going to close this as I've filed a bunch of "good first bugs" that address these points. There's also an existing issue already about the Delete Button being scary.
