### ISSUE TITLE
Re-think the positioning & placement of Remix button on published projects.

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.mozilla.org#1296]
One of our goals in redesigning the new curriculum template was to publish it as a remixable project that anyone could use. Well, here it is...

https://d157rqmxrxj6ey.cloudfront.net/flukeout/17698/#step-2

Obviously there is a big problem here, the design we're using conflicts with our autmatically-added Remix button (and z-index issues)...

![image](https://cloud.githubusercontent.com/assets/25212/11578988/e9e17ffa-99de-11e5-8e7f-49402a1ad195.png)

We can't simply remove the Remix button from the project, since that defeats the purpose of this template.

**So - how can we solve this?**
- Design the curriculum template so that there is nothing in the top right corner
  - This is easier for desktop, but harder for our mobile design, which has a navigation fixed bar across the top of the page.
- Allow the user to change the position of the remix button?
- Change the Remix UI / UX so that it's even less obtrusive
  - Maybe make it really small? 
  - Make it dismissable?
  - Fade it out as soon as the page is touched / moved?
  - Only show it for the first few X seconds?
- Place it in a different part of the page?
  - Opens up the door to other conflicts though?
- Revert to old style 'bar above content'?
  - Ugly but at least will be conflict free?

cc @hannahkane @chadsansing @humphd

**Comment by flukeout** [comment]
We could also indicate inside of the preview in Thimble that there is a reserved area at the top-right of the page.

**Comment by flukeout** [comment]
Here's the mobile version, which uses the entire top of the screen for a persistent navigation. It's not unreasonable to think that most mobile sites will have critical features & navigation in that area.

![image](https://cloud.githubusercontent.com/assets/25212/11579331/077d8e34-99e2-11e5-8662-6284e5473323.png)

**Comment by chadsansing** [comment]
Two other ideas, neither great:

1. Return the top bar, but keep it empty except for the remix button in the top right.
2. Append the button after the first block element as a kind of sub-header.

Otherwise, it would be interesting to think about how to make this a smart feature.

**Comment by flukeout** [comment]
Chiming in for @humph, who suggested we might look at the bottom-right corner as a better location. It seems to be a bit of a pattern lately that we could lean on.

**Comment by hannahkane** [comment]
I agree bottom-right could be better placement (fixed, so that it's visible even on long pages), but am also intrigued by @flukeout's ideas for making it less obtrusive. Do we have data on when the Remix button is typically clicked? e.g. is it most often within 5 seconds of loading a page?

**Comment by flukeout** [comment]
Will re-file as a new issue.
