### ISSUE TITLE
Consider adding blog posts tagged #thimble to thimble homepage

### ISSUE THREAD

**Issue by hannahkane** [mozilla/thimble.mozilla.org#1298]
People new to Thimble might not be aware of the Webmaker blog, but perhaps we could pull in relevant blog posts.

**Comment by hannahkane** [comment]
Or maybe just a link.

**Comment by flukeout** [comment]
I think having links to the last few articles would be great. On a broader note, we should probably have a different blog name now? A teach blog? I'll file another issue for ideas on how to communicate new features within the tool itself.

**Comment by gideonthomas** [comment]
Closing considering recent changes that make this not useful anymore.
