### ISSUE TITLE
Explore UX / UI of highlighting new features within Thimble.

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.mozilla.org#1299]
We're just about to land the inspector, but have no good way of calling attention to it or explaining how to use it within the tool. What are some options...
- When we land a new feature, we can launch the editor with a popup/overlay explaining it.
  - Users can dismiss it and it will only be shown once per user
- We can use the default starting content in the Blank New Project to call attention to the new feature
- We can have some kind of overlay or top bar callout along the top of the editor that calls out the feature and links to a post or resource about it.
- A special highlight or treatment aroudn the UI for a new feature with a [?] icon that people can click on for more info?
  - We can keep this on for a week or first few uses per user.
- ...others?

Mockups for the above incoming.

**Comment by humphd** [comment]
This hasn't moved, closing until we decide to do something.
