### ISSUE TITLE
Getting saving failed, retrying errors...

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.mozilla.org#1311]
![image](https://cloud.githubusercontent.com/assets/25212/11885123/b15e3146-a4d3-11e5-841d-826acce114d1.png)

Just started noticing this now - 3:35 PM PST - December 17

**Comment by flukeout** [comment]
Seems like other projects are saving fine - but this one isnt.

``https://thimble.mozilla.org/user/flukeout/69635``

**Comment by flukeout** [comment]
While this was happening, I uploaded some image files - and they seem to be persisting in the project, even though the UI is reporting a Saving Error...

![image](https://cloud.githubusercontent.com/assets/25212/11885651/48c80e92-a4d6-11e5-9315-751a65e57b5b.png)

**Comment by flukeout** [comment]
In this state, I'm unable to update the published version. It's stuck on "Publishing..."

![image](https://cloud.githubusercontent.com/assets/25212/11885660/5d9926da-a4d6-11e5-8ae4-9dd24145fa7c.png)

**Comment by flukeout** [comment]
cc @gideonthomas When you get a chance, let's try to troubleshoot?

**Comment by flukeout** [comment]
Clearing the IndexedDB files table resolved this - but we should put in place something that prevents this from happening to other users.

Seemed like moving files into folders is what started this chain of events. I'll try to reproduce it.

**Comment by flukeout** [comment]
Just updating because it happened again - resolved by clearing Indexed DB, files table.

**Comment by gideonthomas** [comment]
Moving out of Jan 29th Heartbeat until we can figure out a good solution for https://github.com/mozilla/thimble.webmaker.org/issues/1330

**Comment by humphd** [comment]
I hit this today in Firefox.  I don't have very good data to add to what we already know, but here's what happened.  I have been off on holidays, so came back to the site with a very old browser cache.  I remixed the Keep Calm project on the homepage, and made no changes, before clicking Publish.  This caused it to start trying to save to the server, and that failed over and over, forever.  I then opened the console (note: it was closed at first, so maybe this is stale cache?), and could see 400s and errors from cloudfront (no idea if that's related, but the responses included them).  I reloaded the page, and it made no difference.  I closed the tab, and 15 mins tried again with console open.  This time it worked.

It worked without issue doing the same thing in Chrome.

**Comment by preetidulloo** [comment]
Can someone fix this on priority

**Comment by humphd** [comment]
@preetidulloo I'd love to, but we can't reliably reproduce this (yet).  If you hit it, can you give me details?  Which browser?  Which OS?  What happened?  Thanks.

**Comment by gideonthomas** [comment]
Also, if you are able to open the console (instructions for [Firefox](https://developer.mozilla.org/en/docs/Tools/Browser_Console#Opening_the_Browser_Console) and [Chrome](https://developer.chrome.com/devtools/docs/console#basic-operation)) and copy/paste everything you see there, that might be helpful.

**Comment by preetidulloo** [comment]
I am using Chrome. I have experienced this bug from long, and it's really annoying me now. Sorry for that but it is. I have experienced this issue usually when I make a new file within a folder, or make a folder, or move a file from one folder to another, meaning something happening with folder. And believe me...once I start seeing this message, then I need to export all the files, create a new project and upload the whole project again. It's so irritating. Also uploading the whole project using the export zip will create a parent folder 'project' under which it will keep all the files and makes all other folders. This way the path settings also change.

**Comment by Pomax** [comment]
@preetidulloo I tried making a new project, and a variety of creating foldes, files inside folders, moving files into and out of folders, but nothing seems to trigger this behaviour for me right now, so if you know of a sure fire number of steps that we can follow that are guaranteed to lead to this problem, that information would be very valuable.

I understand that it's frustrating to constantly hit this bug, but if there is no way to reliably reproduce it, we can't actually analyse the code to see what is actually happening when it goes wrong, all we see is what's happening when it's already gone wrong, which is not enough information to fix this bug unfortunately.

**Comment by preetidulloo** [comment]
[Thimble.txt](https://github.com/mozilla/thimble.mozilla.org/files/162236/Thimble.txt)

**Comment by preetidulloo** [comment]
This file is holding Javascript console entries

**Comment by humphd** [comment]
@preetidulloo, also, don't worry about saying bugs are annoying--we agree!  Even the info you put above is very helpful, since it challenges some things I thought were true, but aren't in your case.  As @Pomax says, try to get us as much data as possible.

**Comment by humphd** [comment]
Ok, nothing in that log that affects this bug.  Thanks for adding it.  If you add `?logging=1` to your URL, it will turn on some extra debug logging for the remote saving.  That might help here.

**Comment by preetidulloo** [comment]
OS -  Windows 10

**Comment by preetidulloo** [comment]
When I opened the same project in IE, no such message. It's saving perfectly fine.

**Comment by preetidulloo** [comment]
[Thimble - saving failed, retrying.txt](https://github.com/mozilla/thimble.mozilla.org/files/162253/Thimble.-.saving.failed.retrying.txt)

**Comment by preetidulloo** [comment]
with ?logging=1

**Comment by Pomax** [comment]
After a lot of making folders and files, moving them into/out of folders, renaming, and generally doing all kinds of constant FS operations, I can get it in a "saving failed" state, although there does not appear to be a console error when that happens, nor a network error. With logging turned on, the `e` from @preetidulloo's logfile is:
```
[Thimble LOG (module=SyncManager)] error syncing file, requeuing operation e {
  name: "ENOENT",
  code: "ENOENT",
  errno: 34,
  message: "O_CREATE is not set and the named file does not exist",
  path: "/365/projects/145347/candies2"
}

stack: "Error: O_CREATE is not set and the named file does not exist↵    at new e (https://mozillathimblelivepreview.net/bramble/production/dist/bramble.js:2:16370)↵    at s (https://mozillathimblelivepreview.net/bramble/production/dist/bramble.js:2:20550)↵    at IDBRequest.r.onsuccess (https://mozillathimblelivepreview.net/bramble/production/dist/bramble.js:3:11351)"__proto__: e
```

**Comment by Pomax** [comment]
So far based on completely unreproducible testing, one thing I did run into with logging turned on is that when things go wrong and I'm renaming/deleting/moving files around, I've seen the following notice preceding the failure cascade:

```
Deleted /365/projects/145380/test2.js Document still has 2 references. Did someone addRef() without listening for 'deleted'?
```

**Comment by humphd** [comment]
OK, this is useful.  We're seeing a filesystem error at least, where it's trying to read a file that doesn't exist, `/365/projects/145347/candies2`.  Was this the file you moved?

**Comment by preetidulloo** [comment]
I haven't made a file named candies

**Comment by preetidulloo** [comment]
candies2

**Comment by humphd** [comment]
@preetidulloo I was referring to @Pomax's log above.  For you it's this:

```
[Thimble LOG (module=SyncManager)] starting sync /16125/projects/145136/advanced html-css/audio-video update
[Thimble LOG (module=SyncManager)] error syncing file, requeuing operation e {name: "ENOENT", code: "ENOENT", errno: 34, message: "O_CREATE is not set and the named file does not exist", path: "/16125/projects/145136/advanced html-css/audio-video"Ö}
[Thimble LOG (module=project)] queueFileUpdate /16125/projects/145136/advanced html-css/audio-video
[Thimble LOG (module=SyncManager)] progress event - pending paths to sync: 1
[Thimble LOG (module=SyncManager)] finished current operation (failed), will run next in 12573ms. 1 operation(s) remain.
```

**Comment by humphd** [comment]
If I had to guess (which I do, in this case), I'd say that there's a save operation pending on a file that's been moved or renamed.  Does that seem possible?

**Comment by gideonthomas** [comment]
Ok yeah I can reproduce this consistently when I rename a **folder**. Not sure about moving files yet!

**Comment by preetidulloo** [comment]
I created a folder, then I created a file in that folder. Then I renamed the file, and then the folder. As soon as I renamed the folder, saving failed retrying... starts flashing

**Comment by Pomax** [comment]
@humphd that was a folder, and I either moved or deleted it - I did a *lot* of things.. sounds like @gideonthomas has STR for folders at least now

**Comment by gideonthomas** [comment]
Ok this is going to be a bit hard to fix! I need to make changes in publish, brackets and thimble to special case folders.

**Comment by humphd** [comment]
Before you do that, can we discuss what this bug actually is?  I'm unclear why we care about folder renames on the server side, given that we only deal in file paths.  Maybe we can catch the specific case that is causing this in the sync code, and not have it fail the whole process, thus blocking the sync completion on the pending rename.

**Comment by gideonthomas** [comment]
@humphd the issue is https://github.com/mozilla/thimble.mozilla.org/blob/master/public/editor/scripts/editor/js/fc/filesystem-sync.js#L76 is being triggered for a folder rename. When it reaches: https://github.com/mozilla/thimble.mozilla.org/blob/master/public/editor/scripts/editor/js/fc/sync-manager.js#L161 it fails because of an `EISDIR` error. We do care about folder renames on the server because of the way it affects the publish step. References to the new folder in code will fail in the published version of the project with a 404.

**Comment by humphd** [comment]
Does a folder rename not kick off recursive UPDATE (new filename) and DELETE (old filename) requests to the server?  This is probably worth discussing on a call later this week so we can hash out a plan.

**Comment by gideonthomas** [comment]
Ok sounds good! I'll ping you tomorrow and find out!

**Comment by gideonthomas** [comment]
Ok I think we have come up with a plan to fix this. We will add a new route in `publish.wm.org` to handle the special case of renames that will rename the file path and accordingly remove the old path from the published version when it is re-published. In brackets, we need to trigger a new event for folder renames that will trigger renames for every file under that folder. In thimble, we listen for the renames and instead of queueing up create/delete operations, we hit the new rename route on `publish.wm.org`.

Unfortunately, this is going to be a complex change with an estimated completion time of about a week to a week and a half. We will get to it hopefully by the end of the week or next week due to being swamped with other work in the current cycle. Until then, since renaming folders (or even creating folders) is not a core feature of thimble and hence for the time being, we discourage renaming them.

**Comment by Dhanesh95** [comment]
Facing this issue since yesterday. I've been trying to design a simple website and every time I upload an image which is my header image, the projects fails to save. It also happens when an image is uploaded and it is renamed.

**Comment by gideonthomas** [comment]
@Dhanesh95 what was the size of the image you were trying to upload? Would you also be able to provide the project id you were working with (it's the last bit in the url - `thimble.mozilla.org/user/myusername/<project id>`)? 
We were experiencing some memory issues yesterday so maybe it was during that time you weren't able to upload the image.

**Comment by Dhanesh95** [comment]
@gideonthomas The size of the image I'm trying to upload is 2.0MB (.png image). The project is here: https://thimbleprojects.org/zealfirefoxclub/124763/

**Comment by gideonthomas** [comment]
@Dhanesh95 is that the ID you see when you go to the published project link? i.e. `thimbleprojects.org/<username>/124763` or is it what you see with the editor page i.e. `thimble.mozilla.org/user/<username>/124763`?

**Comment by Dhanesh95** [comment]
@gideonthomas That is the ID I see on the published project link. 
> **https://thimbleprojects.org/zealfirefoxclub/124763/**

Sorry for providing the incorrect ID. The ID you are looking for is: **575670**

The name of my project is: **Mozilla Club Zeal website**.

**Comment by gideonthomas** [comment]
@Dhanesh95 np! I'm not entirely sure what happened when you tried to upload that image since I don't see any red flags in the database nor in our server logs. I suspect that something might have gone wrong with the state of the project on the client side. What would be helpful is if it is still happening, would you be able to copy/paste what you see in the developer console of your browser? Here's how you can do that for [Firefox](https://developer.mozilla.org/docs/Tools/Web_Console/Opening_the_Web_Console) and [Chrome](https://developers.google.com/web/tools/chrome-devtools/console/?utm_source=dcc&utm_medium=redirect&utm_campaign=2016q3)

Until then, one thing I can do for you is to upload the image myself into a remix of your project that I create and then give you the link to remix that project with the image in it. For that you would need to provide me with the image though so let me know if you would like to do that.

**Comment by Dhanesh95** [comment]
@gideonthomas So I reluctantly tested this on Chrome and turns out it works on Chrome. No issues faced. It is still happening in Firefox though and I think we can safely say that this is a Firefox issue. :( 

I've copied the log and you can find it [here](http://pastebin.com/HCUGNEK6).

**Comment by gideonthomas** [comment]
@Dhanesh95 sorry to hear that :( we're going to try to investigate what happened. Until then, if you need anything else from us to recover your project contents or add something to your project, feel free to let us know.

@humphd If you look at the log posted above, on line 212 you can see a localstorage error Any idea why that might happen on drag and drop?

**Comment by Dhanesh95** [comment]
@gideonthomas Thanks a lot for your help.  I'll definitely let you guys know if there is anything I'll need.  Thanks again.
