### ISSUE TITLE
No obvious user friendly way to download images use in a project

### ISSUE THREAD

**Issue by ScottDowne** [mozilla/thimble.mozilla.org#1313]
Example, I want to download the images used in this project.

![download](https://cloud.githubusercontent.com/assets/197334/11962987/d4e7b59c-a8b1-11e5-947b-5700e1d1f813.png)

First thing I tried was right click, but that didn't work, second thing I tried is looked for a download icon in the image preview.

For what it's worth, right click is something I know to do as a developer, I think the download icon would probably be more user friendly, but that's just my initial reaction. I ended up ripping it from the source, which worked for me.

**Comment by ScottDowne** [comment]
Maybe also a way to download the whole folder in one go.

**Comment by humphd** [comment]
If you are logged in, you can export the project as a zip, see https://github.com/mozilla/thimble.webmaker.org/wiki/Using-Thimble#export-a-project

On Dec 22, 2015 1:46 PM, ScottDowne <notifications@github.com> wrote:

Maybe also a way to download the whole folder in one go.

**Comment by Pomax** [comment]
does right-click in the preview work, though?

**Comment by ScottDowne** [comment]
I could only right click on the actual finished project view, not the right preview panel.

**Comment by Pomax** [comment]
@humphd is the right click intercepted for the preview pane? does the source mapping on click kick in without looking at which button was pressed maybe?

**Comment by simon66** [comment]
This is something that I was actually trying to do the other day.
I wanted to download just the image and not the whole project.

![capture](https://cloud.githubusercontent.com/assets/1103528/23032835/e2237de8-f443-11e6-8e40-ef59ad8ccaf0.PNG)

Maybe an option like this would be nice. This way I can download any single file (Or maybe a folder if I want to).
What do you think @flukeout?

**Comment by flukeout** [comment]
Sounds good to me! I think @humphd and @gideonthomas are in the process getting us over on the latest version of brackets. Might make sense to wait until that is finished before tackling this.

https://github.com/mozilla/brackets/pull/588

**Comment by humphd** [comment]
@simon66 you can file that as a separate bug in mozilla/brackets.  When you do, give some consideration to the case of a file vs. a folder, and what you'd do in the folder case.

**Comment by gideonthomas** [comment]
This is done
