### ISSUE TITLE
Can't add a Tutorial immediately after deleting Tutorial

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.mozilla.org#1321]
**Steps to reproduce**
- Add a tutorial
- Delete it
- Try to add another tutorial
- The option isn't there

A refresh solves this problem.

![tutorial-bug](https://cloud.githubusercontent.com/assets/25212/12127629/2a3789ae-b3ad-11e5-8f5a-c489f8f8adf5.gif)

**Comment by humphd** [comment]
This is where that stuff gets handled (we listen for events on the `/tutorial.html` file being added or removed):

https://github.com/mozilla/thimble.webmaker.org/blob/bramble/public/editor/scripts/editor/js/fc/bramble-ui-bridge.js#L170-L177

There must be something broken in there?

**Comment by humphd** [comment]
Closing this in favour of #1596, where it's being worked on right now.
