### ISSUE TITLE
Documentation for new contributors

### ISSUE THREAD

**Issue by gideonthomas** [mozilla/thimble.mozilla.org#1324]
The thimble project is a pretty complex one. It depends on a bunch of other projects (brackets, publish.wm.org...) and the relationships between them are pretty convoluted (I myself am lost a lot). In order to engage contributors, we need to make the on-boarding process as smooth as possible. One major improvement to this process can be thorough documentation.

Things that the documentation needs to cover are:
- The overall architecture of the project and why certain design decisions were made
- How the different dependencies are related to Thimble and each other
- Why each dependency exists and what it's function is wrt the whole product
- How to navigate through the codebase easily (which is especially an issue with brackets)
  - Where would you look to add new features
  - Which parts of the codebase to avoid modifying
  - ...
- The different processes that begin with Thimble and how they are carried out by interfacing with the different dependencies
- Other stuff that I can't think of right now

As far as how we're going to approach this documentation, there are a bunch of ways but we need to discuss. I don't think having one long CONTRIBUTING.md file is very appealing. We can decide from any/some/all of great strategies such as sequence diagrams, ERDs, wikis, etc.

One thing that I do think is important wrt the discussion about how we should document is that it's probably a good idea to make some of our decisions based on research from other mozilla/non-mozilla projects and pick and choose some good strategies from different projects.

cc @hannahkane, @simonwex, @davidascher, @flukeout, @humphd, @Pomax

**Comment by flukeout** [comment]
Thanks for starting this work @gideonthomas - it sure is a bunch of moving parts. I can take on writing a guide that explains how to add a feature in the Thimble UI that talks to the brackets editor (like the full screen preview, for example).

**Comment by gideonthomas** [comment]
@flukeout that's a great idea, let's break this down into smaller bugs that each of us can take on and document. We should probably outline the different parts of documentation that need to be done first and we can figure out what kind of strategy would be appropriate for each piece.

**Comment by humphd** [comment]
Can we do this in the Github Wiki?  If you fill out a TOC and the basic pages you want, I'm happy to contribute docs on the parts I know well

**Comment by ryanwarsaw** [comment]
I think moving this up to critical status is appropriate, especially since we're going to have an influx of new contributors. It's also important that we do a better job at letting people know about processes such as creating a localization change (Pontoon).

**Comment by humphd** [comment]
I think this has gotten significantly better.  What still needs to happen?  Can we close this now?

**Comment by flukeout** [comment]
Sounds good - let's file more concrete issues if we want to change things.

**Comment by flukeout** [comment]
Closing until we have more action items related to this.
