### ISSUE TITLE
Adding a new folder to the tray adds it in the wrong place.

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.mozilla.org#1325]
Right-clicking below the last folder in the gif and selecting "new folder" adds it to that folder, instead of to the root, as would be expected...

![folder-bug](https://cloud.githubusercontent.com/assets/25212/12250506/4da104d2-b87c-11e5-903c-61d9337136a0.gif)

**Comment by gideonthomas** [comment]
Yeah I'm pretty sure this is a react issue in brackets. Before creating the new folder, if you click on one of the files first (give it focus in the file tree) and then create the new folder (the same way you do above), it will work as expected.

**Comment by gideonthomas** [comment]
Moving discussion to #1352
