### ISSUE TITLE
Remove jQuery dependency from injected remix button code

### ISSUE THREAD

**Issue by flaki** [mozilla/thimble.mozilla.org#1327]
It would be nice if we could remove the jQuery-dependency of the [injected remix button code](https://thimble.mozilla.org/resources/remix/index.js) from published code, as it interferes non-trivially with jQuery loading (from user code).

We don't use any jQ plugins and that source is not so vast that and complicated taht this should be an issue. Also we would win on performance, reduce page load time and size, and favoring the use of vanilla js would be in line with general Mozilla principles, so it's a win on multiple grounds.

If this is deemed okay, I would like to have a stab at this at [`vanilla`](https://github.com/flaki/thimble.webmaker.org/tree/vanilla) branch.

**Comment by humphd** [comment]
This sounds fine to me. As long as we  can do it well without breaking current browser support, go for it.

cc @flukeout

On Jan 13, 2016 1:57 AM, István Szmozsánszky <notifications@github.com> wrote:

It would be nice if we could remove the jQuery-dependency of the injected remix button code<https://thimble.mozilla.org/resources/remix/index.js> from published code, as it interferes non-trivially with jQuery loading (from user code).

We don't use any jQ plugins and that source is not so vast that and complicated taht this should be an issue. Also we would win on performance, reduce page load time and size, and favoring the use of vanilla js would be in line with general Mozilla principles, so it's a win on multiple grounds.

If this is deemed okay, I would like to have a stab at this at vanilla<https://github.com/flaki/thimble.webmaker.org/tree/vanilla> branch.

**Comment by flukeout** [comment]
Sounds great to me!

**Comment by flukeout** [comment]
@flaki - I started doing some of this work in the past, but didn't finish, so let me know if you have any questions!

**Comment by humphd** [comment]
We inject a script into published HTML files that uses jQuery, see https://github.com/mozilla/thimble.mozilla.org/blob/fa3dde088dc016a562520e62a9df1f5558ba8f70/public/resources/remix/index.js#L119.  Fixing this would require replacing the jQuery calls in that file with vanilla JS and DOM calls.

**Comment by ryanwarsaw** [comment]
GH-1602 (#1602) also uses jQuery in order to function properly.

**Comment by humphd** [comment]
We don't need to get rid of jQuery in general, it's just in the remixed project where we inject that script.

**Comment by aayushsanghavi** [comment]
@flukeout I would like to work on this. How should I proceed with it?

**Comment by humphd** [comment]
@aayushsanghavi whatever you end up working on, can I ask that you please just do one bug at a time?  We have a lot of new contributors who are looking for bugs, and we'd like to try and accommodate as many of them as possible. Thanks a lot for getting involved, and for helping us grow our community.

**Comment by aayushsanghavi** [comment]
@flukeout sure! I just got a little excited when I was able to finally set up Thimble.
Yes definitely, I'll keep that in mind.

**Comment by aayushsanghavi** [comment]
@humphd could you please tell me which components are dependent on jQuery and require changes?

**Comment by humphd** [comment]
See my discussion above in https://github.com/mozilla/thimble.mozilla.org/issues/1327#issuecomment-274892908
