### ISSUE TITLE
Dismiss the "Publish" dialog when link to publish project is linked.

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.mozilla.org#1333]
**Scenario**
When publishing a project, or updating the published version, the next step for the user is generally to leave the editor and go see how the project looks in another tab.

When they return to the editor, the Publish dialog is still visible and is obscuring the project preview, as seen here...

![image](https://cloud.githubusercontent.com/assets/25212/12362588/f74a0156-bb78-11e5-84fc-952f87c027d0.png)

Since the project was just published and looked at, there isn't really any good reason for this dialog to be open.

**Proposal**
When a user clicks the link to a published project...

![image](https://cloud.githubusercontent.com/assets/25212/12362622/3b0f1c78-bb79-11e5-863e-b6794aa90aba.png)

...let's close the Publish dialog.

**Comment by wildaces215** [comment]
Is this bug still open?

**Comment by gideonthomas** [comment]
yes @wildaces215, would you like to take this on?

**Comment by wildaces215** [comment]
Yes I would like to take this issue on!

**Comment by wildaces215** [comment]
Though I might need help with it

**Comment by gideonthomas** [comment]
sure thing @wildaces215 

You should start by forking and cloning our repo and its dependencies (instructions are [here](https://github.com/mozilla/thimble.mozilla.org#setup))
If you have any issues, let us know in this bug and we'll be happy to help you through the process.

Once you have everything set up and running, I believe the relevant code should go [here](https://github.com/mozilla/thimble.mozilla.org/blob/master/public/editor/scripts/editor/js/fc/bramble-ui-bridge.js#L335) (explore the code a couple of lines below/above to give you an idea of what you need to do). You probably need to add an `id` to [this element](https://github.com/mozilla/thimble.mozilla.org/blob/master/views/editor/publish.html#L15) and handle the click in the section I linked above based on this `id`.

Let us know if you run into any problems or if the above description isn't clear enough.

**Comment by wildaces215** [comment]
Ok so I am trying to install thimble yet when I run the command 
'npm run localize' does not work

**Comment by gideonthomas** [comment]
@wildaces215 what error do you see?

**Comment by wildaces215** [comment]
Sorry can't do the bug anymore

**Comment by cgsingh** [comment]
I'd like to solve this issue (I have a pull request ready).

**Comment by Pomax** [comment]
@cgsingh nice! This looks good to me, I'll let @flukeout decide whether it matches the flow he had in mind (pretty sure it does)

**Comment by cgsingh** [comment]
@flukeout Yeah, I forgot to do that on the initial commit and when I tried to edit the message, I guess it didn't work.
