### ISSUE TITLE
Update Remix Rollout styling, doesn't look great on white projects.

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.mozilla.org#1334]
The remix "fly-out" (which appears when hovering over the Remix button on published projects) doesn't look great on white backgrounds -the top edge bleeds into the project itself, as seen here...

![image](https://cloud.githubusercontent.com/assets/25212/12362883/8dd620ae-bb7a-11e5-8e4b-68e4250deece.png)

**Proposed solution**
Let's change some of the styling of this element to make it stand out better against white backgrounds. Ideas include...
- Change the drop shadow so that some of it is visible along the top edge
- Add a faint border to the entire "fly-out"

**Comment by yash14123** [comment]
Would like to work on this. Please assign me this.

**Comment by humphd** [comment]
Fixing this requires making changes to the CSS in this LESS file:

https://github.com/mozilla/thimble.mozilla.org/blob/master/public/resources/remix/style.less

**Comment by JohnEJames** [comment]
I would like to try to resolve this bug @humphd

**Comment by humphd** [comment]
Sounds good, it's yours @JohnEJames.

**Comment by flukeout** [comment]
Closed via https://github.com/mozilla/thimble.mozilla.org/pull/1712
