### ISSUE TITLE
Docker for Thimble?

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.mozilla.org#1337]
Is there a possibility for using something like Docker to get a Thimble dev environment up and running? Currently it requires 6 different services to be running at once in perfect glorious harmony, and that might be hard and or annoying for contributors.

cc @cadecairos @gideonthomas

**Comment by cadecairos** [comment]
https://github.com/cadecairos/webmaker-docker currently spins up all services Thimble require, save Thimble itself.

**Comment by gideonthomas** [comment]
I think it's possible esp. since you've got the other services running already. We just need to change some of the env stuff to match the docker config you've set up (e.g. ports).

@humphd you did some work with this right? Any suggestions?

**Comment by cadecairos** [comment]
I dont think it's worth adding in thimble though, if the goal is to speed development on thimble, we'd want to leave that in the hands of the developer. My main goal with webmaker-docker was to eliminate the need for the developer to configure and run all the dependent services.

**Comment by davidascher** [comment]
It would be good to get someone (who doesn't know how to build these
systems) to try to use this (& whatever instructions there are) and file
feedback/bugs on whether it's effective or there are still rough edges.

**Comment by gideonthomas** [comment]
Oh I totally thought that you posted the bug @cadecairos lol. Yeah that sounds sane!
+1 to @davidascher's suggestion

**Comment by cadecairos** [comment]
Yeah it could definitely benefit from more eyes. 

It's been somewhat well tested on Linux and Mac (thanks to @gvn) (although as is with Docker, it's easier on Linux). It should theoretically work on Windows.... but, I've never been able to test that.

**Comment by humphd** [comment]
This is now done, using Vagrant.  Closing.
