### ISSUE TITLE
Benchmark how other open source projects do community

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.mozilla.org#1338]
I've started some preliminary work in the [Open Source Community Benchmarks](https://docs.google.com/a/mozilla.com/document/d/17geDLdYd-qFmUsSvo9Pz7rgyf8Yc--0WMUFKoBJH-l4/edit?usp=sharing) doc.

I'd like to see what similarities projects with successful communities have so that we can emulate some of it for Thimble. Ideally, the projects will have some similarity to Thimble (in size, age & topic).

**Some projects**
- [x] [Rust](https://www.rust-lang.org/)
- [x] [Brackets](http://brackets.io/)
- [x] [SageMath](http://www.sagemath.org/development.html)
- [ ] [Project Jupyter](http://jupyter.org/)
- [ ] [OpenRefine](https://github.com/OpenRefine/OpenRefine)
- [ ] [Gimp](https://www.gimp.org/)

...need a bunch more here!

**Comment by gideonthomas** [comment]
[Open Refine](https://github.com/OpenRefine/OpenRefine) is also another project to consider. I like their idea of a "Credits" section - it tends to attract contributors with the allure of putting their name on the project.

**Comment by chadsansing** [comment]
[Scratch](http://scratch.mit.edu)?

**Comment by flukeout** [comment]
@chadsansing does Scratch have a developer community? I couldn't really find anything on their site.

**Comment by chadsansing** [comment]
Mebbe something like this, @flukeout: https://scratch.mit.edu/discuss/topic/175099/?page=1.
