### ISSUE TITLE
Explore Thimble digest blog post format & write a post!

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.mozilla.org#1339]
We agreed that a monthly blog post would be a great way to surface and celebrate the work and community behind Thimble. I'll take a look at some benchmarks and draft up a proposal.

**Potential content**
- Interesting projects built by our users
- Usage stats
- New or featured curriculum
- New features
- Tips & tricks (or feature highlights)
- Issues for the community to work on
- Upcoming features & work

It would be good if this format also worked as an email.

**Benchmarks**
- Olde Appmaker release notes & progress doc
- Codepen News Email

cc - @chadsansing Thoughts about this from a curriculum perspective?

**Comment by chadsansing** [comment]
@flukeout, I would love to contribute here with copy and curation from the dashboard/Twittersphere.

**Comment by humphd** [comment]
This hasn't happened, closing.  I'd love to see it actually happen, though.

**Comment by flukeout** [comment]
Yeah, related to the community piece you started in another issue. I agree, this would be cool - it's a cool way to engage with community without needing to be always-on like with Twitter etc.
