### ISSUE TITLE
Understand future and direction of Brackets

### ISSUE THREAD

**Issue by simonwex** [mozilla/thimble.mozilla.org#1348]

**Comment by humphd** [comment]
My sense is that things are either on hold, or they're done with it.  Take a look at the commit graph:

https://github.com/adobe/brackets/graphs/contributors

You'll note that Adobe's devs mostly stopped working on it in July.  This is roughly the last time we rebased on them (we're at ~1.3 and Brackets is currently at 1.6, with recent releases being mostly about bug fixes in parts of the code we don't use).

At the same time, it looks like Brackets is being used to modernize Dreamweaver:

http://blogs.adobe.com/dreamweaver/2015/10/next-generation-of-dreamweaver.html

This will likely mean there will be updates in Brackets at some point that we might want to pick up, but I suspect most of the work will be done outside of the core (extensions) and/or in Dreamweaver itself.

All of this is speculation, and I don't have any inside knowledge.

**Comment by simonwex** [comment]
Super helpful talking points, thanks David. I've sent an email to my peeps over at Adobe. Will report back.

**Comment by humphd** [comment]
Can we close this now?  I'd suggest that we evaluate merging new work from upstream when it's clear that we need it.  This hasn't been necessary for 6 months+, and I don't think it will be in the near future.
