### ISSUE TITLE
Improve UX for adding/deleting/moving folders

### ISSUE THREAD

**Issue by hannahkane** [mozilla/thimble.mozilla.org#1352]
A user pointed out that it's not intuitive to right-click the file tree in order to see the add'l actions.

Apologies if this is already a ticket, or we triaged it out of the list. Feels like a big usability flaw right now, though.

**Comment by gideonthomas** [comment]
@hannahkane I believe we had this discussion before as well and I'm not sure why we shut it down. I marked this as a P2 for now but feel free to escalate that to a P1.

cc @flukeout

**Comment by gideonthomas** [comment]
Related issue: https://github.com/mozilla/thimble.mozilla.org/issues/1325

**Comment by gideonthomas** [comment]
Closing since we've done this with the context toolbar and top + nav bar.
