### ISSUE TITLE
Create diagram explaining flow of text for translation

### ISSUE THREAD

**Issue by simonwex** [mozilla/thimble.mozilla.org#1355]
The components that should be mapped here include:
 * Pontoon
 * Brackets
 * Extensions
 * thimble.webmaker.org

Actions to consider:
 * Creating a translation for each of the components from Pontoon
 * Merging updates to translations and new keys from Brackets, including effect on Pontoon users
 * Sending new translated locales upstream to Brackets

WIP:

![image](https://cloud.githubusercontent.com/assets/25260/12623691/2c36bab0-c4e0-11e5-9651-ca7a0e076a90.png)

**Comment by gideonthomas** [comment]
First pass:
https://drive.google.com/open?id=0BwCd-6qteGa8bDhmT2RJUE1ydkE

**Comment by humphd** [comment]
Do you need another bug for a plain text version of this?  I know I need it in order to get started on localizing strings across Thimble/Brackets.

**Comment by gideonthomas** [comment]
@humphd sure, can you file? I'll fix today

**Comment by gideonthomas** [comment]
@simonwex The plan is to add this to the wiki. How does this look:

![thimble l10n](https://cloud.githubusercontent.com/assets/5816130/13685163/21a8ac4c-e6dd-11e5-8748-4971ec0edc93.png)

**Comment by gideonthomas** [comment]
This has been added to the wiki
