### ISSUE TITLE
Enable l10n in Bramble Core using Pontoon

### ISSUE THREAD

**Issue by simonwex** [mozilla/thimble.mozilla.org#1356]
L10n is already enabled for Bramble core (Brackets) but we don't have a mechanism for customizing translations, translating [additional keys](https://github.com/mozilla/thimble.webmaker.org/blob/bramble/public/editor/scripts/editor/js/fc/publisher.js#L8-L12) we've added and for translating to locales that the existing Brackets community hasn't yet.

Related: #1355

**Comment by simonwex** [comment]
Articulating a plan and getting started is fine for this HB.  We can move over to follow-on HB if we need to.

**Comment by gideonthomas** [comment]
I think any upstream string changes that we want to incorporate, we should do manually. 

As far as "adding" anything is concerned, I believe that 4119b0c04009599ac713faaf560ad1a57e0fa721 addresses that. All we do is add new strings to the `.properties` files, and the script will handle the rest...it will amalgamate what's in our `.properties` files with what's in the corresponding brackets' community written string files with a preference for our strings. 

The only caveat is that every time a new string is added, the script needs to be run manually for local development (which will need to be documented).

The last thing that needs to be done is to figure out how to integrate pontoon into this i.e. do we need to have brackets as a separate app on pontoon or will adding the pontoon script work in the editor iframe on thimble?

**Comment by gideonthomas** [comment]
Fixed in https://github.com/mozilla/brackets/commit/cef04c0e96fbe6c08ee473cc71659195eae64b0f and https://github.com/mozilla/thimble.mozilla.org/commit/3afe6b4c4cd2924b626a2ec88f1a3cb5300cee6d
