### ISSUE TITLE
Use localized version of WebPlatformDocs

### ISSUE THREAD

**Issue by simonwex** [mozilla/thimble.mozilla.org#1360]
We need to remove any use of this as it's not localized and we're using MDN docs instead.

https://github.com/humphd/brackets/tree/bramble/src/extensions/default/WebPlatformDocs

**Comment by simonwex** [comment]
@gideonthomas is this necessary? Does our use of MDN replace this?

**Comment by gideonthomas** [comment]
See https://github.com/mozilla/thimble.mozilla.org/issues/1364#issuecomment-187862557

**Comment by gideonthomas** [comment]
See https://github.com/mozilla/thimble.mozilla.org/issues/1364#issuecomment-189371348
Getting the localized version of WebPlatformDocs is actually quite hard (seems to be even harder than MDNDocs) so I think we should go with the easier option for now and iterate.

**Comment by gideonthomas** [comment]
For now, I'm closing this issue and we can re-open again if we decide to come back to WebPlatformDocs
