### ISSUE TITLE
Localize Bramble

### ISSUE THREAD

**Issue by simonwex** [mozilla/thimble.mozilla.org#1362]
* Tooltips in UI (https://github.com/humphd/brackets/blob/bramble/src/extensions/default/bramble/lib/UI.js)
 * `tutorial.html` (https://github.com/humphd/brackets/blob/bramble/src/extensions/default/bramble/lib/Tutorial.js#L43)

**Comment by simonwex** [comment]
TODO: Add additional strings that need extracting

**Comment by gideonthomas** [comment]
Closing since none of the strings in `bramble` are visible to the user in Thimble
