### ISSUE TITLE
preserve scrollTo position when content is updated

### ISSUE THREAD

**Issue by Pomax** [mozilla/thimble.mozilla.org#1370]
Working on a project that is more than 2 paragraphs means that if you edit far down enough, a content update reloads the preview, and scrolls back to top, preventing you from seeing the changes you are making.

This is a quite  a UX barrier

**Comment by simonwex** [comment]
Hey @flukeout, could you add some words describing how we should fix this?

**Comment by humphd** [comment]
I can't reproduce this. Can you give me more info?  If I remix the Comic Strip project on the homepage, scroll down to the bottom, and edit, it stays in place.

**Comment by Pomax** [comment]
interesting, looks like this got landed since filing, but wasn't flagged as fixed.
