### ISSUE TITLE
Show error/warning if cookies are disabled

### ISSUE THREAD

**Issue by gideonthomas** [mozilla/thimble.mozilla.org#1384]
From a tweet: https://twitter.com/Cleo_Qc/status/695687805528367104

`localStorage` is not accessible because cookies are disabled and the user gets stuck at the "Loading" screen without any indication about what's happening. 

We should surface a warning or error message (kind like we do for private browsing mode) if cookies are disabled and let users know that they need to turn on cookies to get thimble to work!

cc @flukeout

**Comment by CleoQc** [comment]
To be more specific, normal cookies were accepted, but not third parties cookies.

**Comment by SaptakS** [comment]
I would like to work on this issue.

**Comment by gideonthomas** [comment]
sure thing @SaptakS, let's get some UI guidance and we can direct you in the right direction. Until then, feel free to start setting up the project on your computer (https://github.com/mozilla/thimble.mozilla.org#setup); I suspect it might take a while. If you run into issues, feel free to ask for help in this issue.

@flukeout how should we show this error? Should it be a banner at the top or a popup message or an alert or we could show the same UI we show for the "Unsupported Browser" error? As far as the text for this is concerned, it should probably include something along the lines of "please enable cookies", "or add exceptions for [*.]mozilla.org, https://id.webmaker.org and https://mozillathimblelivepreview.net"

**Comment by flukeout** [comment]
@gideonthomas What happens now? I don't think the editor even loads, right?

**Comment by SaptakS** [comment]
Ok cool. Thanks.

**Comment by gideonthomas** [comment]
@flukeout yeah it just gets stuck on "Loading". I think we should error out on the homepage as well as the editor page.

**Comment by gideonthomas** [comment]
Closing since this is done
