### ISSUE TITLE
Localize the remix script

### ISSUE THREAD

**Issue by gideonthomas** [mozilla/thimble.mozilla.org#1388]
The remix script that is injected into published projects needs to be localized!

This is going to be tricky since all we can rely on is the locale info given to us by the browser. Accordingly, we need to make sure we send the right correctly localized file to the user-agent.

I think simple server-side rendering of the localized content into the js file should be good enough to accomplish this. But, we need to make sure that the routes to access this remix script go through the node-webmaker-i18n middleware first. We also need to make sure that it does not go through the i18n-force-locale-in-url middleware.

A suggestion is to create a custom dynamic route that will render the file using nunjucks.

**Comment by humphd** [comment]
I don't think we should localize the JS file.  Rather, let's extract https://github.com/mozilla/thimble.mozilla.org/blob/master/public/resources/remix/index.js#L83-L100 into a templated HTML file with its own localized route, and XHR that content at runtime before we inject it into the page.

**Comment by gideonthomas** [comment]
Yeah that makes sense!

We should send all the project metadata to this route and generate the html accordingly (so that we don't have to localize the metadata on the client) and send it in the response which we can then use to plug into the DOM.
