### ISSUE TITLE
Plan to engage our community of localizers

### ISSUE THREAD

**Issue by gideonthomas** [mozilla/thimble.mozilla.org#1399]
Currently to start, we have chosen the following languages to localize Thimble in:
de, hi, fr, es-MX, pt-BR
@alicoding would you like to comment on why we chose these languages?

It would be nice to inform/back this decision based on metrics (most used languages in ye olde Thimble for e.g.).
cc @simonwex, @adamlofting

**Comment by alicoding** [comment]
Based on our old metrics/market that we were focusing on for other products that we worked on Localization in general. It's also the language that most active in the localization community which will help drive this project to a fully localized state.

**Comment by adamlofting** [comment]
Here's a very quick list of the most popular (non-en) browser languages for traffic to all the old webmaker tools combined.

<img width="377" alt="screenshot 2016-02-12 09 25 08" src="https://cloud.githubusercontent.com/assets/1901816/13002975/9d398dd2-d16a-11e5-9571-bb6d70ae9f53.png">

**Comment by humphd** [comment]
Other than being an interesting data point, is there any actual work to be done here?  As @alicoding points out, given that we're relying on the l10n community to help us here vs. doing it ourselves, I'm not sure we can really affect which locales get done first.

That said, it might be worth doing some blogging, tweeting, mailing-listing, etc. to ask for help and encourage people.  Another thought would be to provide some kind of thank-you reward system for people who really dig in.  In the past I know we sent T-Shirts to active localizers.

**Comment by chrislarry33** [comment]
Hi all

We did a version of what @humphd is talking about including incentives for our curriculum localization efforts in the fall. Tagging @ldecoursy @chadsansing @soapdog and @KGorr to share more detail. I wonder if this could be an exstension/remix of what we did there?

**Comment by ldecoursy** [comment]
The translations recently went live - if you click on each of the 6 activities in the Web Lit Basics I module: https://teach.mozilla.org/activities/web-lit-basics/ you'll see the pull-down on the top right for languages that are available. We did blog posts, Tweets and lots of targeted outreach (via Clubs, Remos, etc.) and efforts resulted in translations in the following 10 anguages (over 4 months):
* Bengali  /   বাংলা
* Dutch    /   Nederlands
* Filipino   /    Pilipino
* German   /   Deutsch
* Gujarati   /   ગુજરાતી
* Hindi   /   हिन्दी
* Indonesian   /  Bahasa Indonesia
* Portuguese   /   Português
* Spanish  /   Español
* Swedish     /     Svenska

We did offer T-shirts to the first 20 people that submitted translated activities.

**Comment by gideonthomas** [comment]
@humphd yeah this issue should have been closed earlier. We decided to start with a couple of languages based on the list @adamlofting provided and keep it completely open-ended for contributors to add new languages (the goal was to push to production soon with a set of most commonly used languages). 

cc @simonwex and @hannahkane re: the incentives part.

**Comment by gideonthomas** [comment]
Moving out of the Feb 26th heartbeat as this is a bit out of scope for it.

**Comment by gideonthomas** [comment]
We're going to track this work in the https://github.com/mozilla/learning.mozilla.org repo.
