### ISSUE TITLE
Thimble Postcard project not working

### ISSUE THREAD

**Issue by msblizzard** [mozilla/thimble.mozilla.org#1400]
When my students are trying to remix the postcard, the front and the back of the card are identical images.  The code allowing the project to flip sides is missing.

**Comment by jgmac1106** [comment]
@msblizzard  I just tested it out and could not reproduce your error: https://d157rqmxrxj6ey.cloudfront.net/jgmac1106/32457/

Can you send me one of your projects and I can take a closer look?

**Comment by msblizzard** [comment]
https://d157rqmxrxj6ey.cloudfront.net/2242890/32461/

**Comment by msblizzard** [comment]
We solved our problem! It was the browser's problem!  Thank you!

**Comment by jgmac1106** [comment]
You didn't have quotes around the image in line 138. I actually downloaded
the image you wanted to link to and uploaded  it in this project:
https://d157rqmxrxj6ey.cloudfront.net/jgmac1106/32466/

I am going to close this ticket. Feel free to hit me up on Discourse or
Twitter if you need more help.

**Comment by jgmac1106** [comment]
@msblizzard Never mind. I can't close the issue. If your problem is resolved please do so.

A little tip: For  tips and tricks help you might find Twitter (using #teachtheweb hashtag) or discourse.webmaker.org better for community requests.
