### ISSUE TITLE
Rename this repo to thimble.mozilla.org

### ISSUE THREAD

**Issue by simonwex** [mozilla/thimble.mozilla.org#1402]
Pretty simple ^

**Comment by simonwex** [comment]
Hey @gideonthomas, what effects would doing this rename have on things like how we build and deploy this?

**Comment by gideonthomas** [comment]
Should be fairly simple. Changes that I know need to be made:
* Update `.travis.yml`
* Update `bower.json` and `package.json`
* Update `README.md`

I don't know if anything on heroku needs to be updated - cc @cadecairos

**Comment by gideonthomas** [comment]
Fixed in c46c3fe46e374b22ac802b978f65146b97538b34, 108acfbf11883d75ae4112c6dedf7758d0010989 and 3a0c59c7943f41a0e66acf48bf91ec97c7cdd8d7
