### ISSUE TITLE
Trying to install Thimble receiving "SyntaxError: Unexpected strict mode reserved word" on sudo npm run localize

### ISSUE THREAD

**Issue by dcforeman** [mozilla/thimble.mozilla.org#1406]
Hi

I'm using a fresh Ubuntu server (14.04 LTS) and am attempting to install Thimble. These are the commands I've used so far.

Thimble setup commands

Install NodeJS

cd ~
sudo curl -sL https://deb.nodesource.com/setup_0.12 | sudo bash -
sudo apt-get install -y nodejs
sudo npm install -g grunt
sudo npm install -g grunt-cli 

Install Brambles

cd ~
sudo git clone https://github.com/dcforeman/brackets --branch bramble --recursive
cd brackets
sudo npm install
sudo npm build-browser
npm start

Install Thimble --issues

cd ~
sudo git clone http://github.com/dcforeman/thimble.webmaker.org --recursive
cd thimble.webmaker.org
sudo npm install
sudo cp env.dist .env
sudo npm run localize

upon run localize it fails with the following:

/root/thimble.webmaker.org/scripts/common.js:3
let fs = require("q-io/fs");
^^^
SyntaxError: Unexpected strict mode reserved word
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/root/thimble.webmaker.org/scripts/properties2json.js:11:22)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)

npm ERR! Linux 3.13.0-71-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "localize"
npm ERR! node v0.12.10
npm ERR! npm  v2.14.9
npm ERR! code ELIFECYCLE
npm ERR! thimble@2.0.0 localize: `node scripts/properties2json.js && npm run localize-client`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the thimble@2.0.0 localize script 'node scripts/properties2json.js && npm run localize-client'.
npm ERR! This is most likely a problem with the thimble package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/properties2json.js && npm run localize-client
npm ERR! You can get their info via:
npm ERR!     npm owner ls thimble
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/thimble.webmaker.org/npm-debug.log

**Comment by gideonthomas** [comment]
hi @dcforeman the issue is that thimble only works on node v4 and above. So instead of: 
`sudo curl -sL https://deb.nodesource.com/setup_0.12 | sudo bash -`
try
`sudo curl -sL  https://deb.nodesource.com/setup_4.x | sudo bash -`

**Comment by dcforeman** [comment]
Thank you @gideonthomas, that has solved my present issues.
