### ISSUE TITLE
License file

### ISSUE THREAD

**Issue by dcforeman** [mozilla/thimble.mozilla.org#1410]
Hi

Most github projects have a license file! I can't find one here? Is that a mistake?

Basically I'm working with a small education company, we're looking to deploy thimble on our own servers. We need a consistant experience for our students without any changes so we'd like to take this version, deploy it and give them a link to our server.

Is this allowed in the usage terms.

Are we allowed to modify the software with our own unique examples, change colors, that kind of thing?

To keep me out of hot water with the boss is there a simple license file I can review!?!

Thanks :)

**Comment by gideonthomas** [comment]
cc @hannahkane

**Comment by Pomax** [comment]
MPL-2

**Comment by davidascher** [comment]
We forgot to add the MPLv2 license file.  Your usage is fine with us, and
we'd love to learn more about what you're thinking of doing.  Expect a
LICENSE file to show up soon.

**Comment by dcforeman** [comment]
Thank you very much.

**Comment by gideonthomas** [comment]
@dcforeman the license has been added to the repo. Thanks for catching that!

**Comment by dcforeman** [comment]
Thanks for providing it!
