### ISSUE TITLE
Unable to install id.webmaker.org

### ISSUE THREAD

**Issue by dcforeman** [mozilla/thimble.mozilla.org#1414]
Hi I'm unable to install and run id.webmaker.org

The instructions I have are based on my understanding of the rough install procedures listed on the repo.

I am using Ubuntu 14.04, the following code shows the commands I used to get to the id.webmaker.org stage in the procedure. 

```
Install NodeJS

cd ~
sudo curl -sL https://deb.nodesource.com/setup_4.x | sudo bash -
sudo apt-get install -y nodejs
sudo npm install -g grunt
sudo npm install -g grunt-cli
nodejs --version 
should return v4.3.0
grunt --version
should return v0.1.13
sudo apt-get install -y git

Install Brambles

cd ~
sudo git clone https://github.com/dcforeman/brackets --branch bramble --recursive
cd brackets
sudo npm install
sudo npm build-browser
npm start
sudo forever start

Install Thimble

cd ~
sudo git clone http://github.com/dcforeman/thimble.webmaker.org --recursive
cd thimble.webmaker.org
sudo npm install
sudo cp env.dist .env
sudo npm run localize
sudo npm start

Install id.webmaker.org

```

From this point onwards I atttempt to install id.webmaker.org

```
cd ~
sudo git clone https://github.com/dcforeman/id.webmaker.org --recursive
cd id.webmaker.org
sudo cp sample.env .env
```

But then these steps fail

```
sudo npm install -- fails
sudo npm start -- fails
```

With the following error messages:

```
root@Thimble:~/id.webmaker.org# sudo npm install
npm WARN deprecated react-tools@0.13.3: react-tools is deprecated. For more information, visit https://fb.me/react-tools-deprecated
npm WARN deprecated npmconf@0.0.24: this package has been reintegrated into npm and is now out of date with respect to npm
npm WARN peerDependencies The peer dependency babel-core@^5.0.0 included from babel-loader will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm WARN deprecated graceful-fs@2.0.3: graceful-fs version 3 and before will fail on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possible.
|

phantomjs@1.9.7-14 install /root/id.webmaker.org/node_modules/phantomjs
node install.js
root@Thimble:~/id.webmaker.org# sudo npm start

id.webmaker.org@1.0.0 start /root/id.webmaker.org
npm-run-all --parallel server watch:css watch:js
sh: 1: npm-run-all: not found

npm ERR! Linux 3.13.0-71-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
npm ERR! node v4.3.0
npm ERR! npm v2.14.12
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! id.webmaker.org@1.0.0 start: npm-run-all --parallel server watch:css watch:js
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the id.webmaker.org@1.0.0 start script 'npm-run-all --parallel server watch:css watch:js '.
npm ERR! This is most likely a problem with the id.webmaker.org package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR! npm-run-all --parallel server watch:css watch:js
npm ERR! You can get their info via:
npm ERR! npm owner ls id.webmaker.org
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR! /root/id.webmaker.org/npm-debug.log
root@Thimble:~/id.webmaker.org#
```

Thank you for taking the time to read my issue.

**Comment by gideonthomas** [comment]
cc @cadecairos

**Comment by cadecairos** [comment]
@dcforeman Try running "npm install -g npm-run-all"

**Comment by gideonthomas** [comment]
@cadecairos is the use of `npm-run-all` new to `id.webmaker.org`?

Either way, we should probably document that since thimble also uses `npm-run-all`

**Comment by cadecairos** [comment]
It's not new, this repo is missing lots of documentation. There are probably already issued filled for that.

**Comment by Pomax** [comment]
note that any utility that is only used in npm scripts does not need the `-g` flag. npm scripts run with an extended environment that includes all node_modules entries

**Comment by Pomax** [comment]
There's a lot of SUDO going on here, which shouldn't be necessary - the git clones don't do any installs into the system, and NPM should be able to run "for you" if you tell it which prefix to use (see https://docs.npmjs.com/getting-started/fixing-npm-permissions)

**Comment by dcforeman** [comment]
@cadecairos I've reset my server to a clean install, then I included _sudo npm install -g npm-run-all_ in the initial instructions set:

```
cd ~
sudo curl -sL https://deb.nodesource.com/setup_4.x | sudo bash -
sudo apt-get install -y nodejs
sudo npm install -g grunt
sudo npm install -g grunt-cli
sudo npm install -g npm-run-all
nodejs --version 
grunt --version
sudo apt-get install -y git
```

I had an error stating it couldn't find autoless so I ran the command _sudo npm install -g autoless_

The server still isn't starting however, the debug log is as follows:

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs', '/usr/bin/npm', 'start' ]
2 info using npm@2.14.12
3 info using node@v4.3.1
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info prestart id.webmaker.org@1.0.0
6 info start id.webmaker.org@1.0.0
7 verbose unsafe-perm in lifecycle true
8 info id.webmaker.org@1.0.0 Failed to exec start script
9 verbose stack Error: id.webmaker.org@1.0.0 start: `npm-run-all --parallel server watch:css watch:js `
9 verbose stack Exit status 1
9 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/lib/utils/lifecycle.js:214:16)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at EventEmitter.emit (events.js:172:7)
9 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:24:14)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at ChildProcess.emit (events.js:172:7)
9 verbose stack     at maybeClose (internal/child_process.js:821:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
10 verbose pkgid id.webmaker.org@1.0.0
11 verbose cwd /root/id.webmaker.org
12 error Linux 3.13.0-77-generic
13 error argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
14 error node v4.3.1
15 error npm  v2.14.12
16 error code ELIFECYCLE
17 error id.webmaker.org@1.0.0 start: `npm-run-all --parallel server watch:css watch:js `
17 error Exit status 1
18 error Failed at the id.webmaker.org@1.0.0 start script 'npm-run-all --parallel server watch:css watch:js '.
18 error This is most likely a problem with the id.webmaker.org package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     npm-run-all --parallel server watch:css watch:js
18 error You can get their info via:
18 error     npm owner ls id.webmaker.org
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]


```

The command line reported the following:

```
root@Thimble:~/id.webmaker.org# npm start

> id.webmaker.org@1.0.0 start /root/id.webmaker.org
> npm-run-all --parallel server watch:css watch:js


> id.webmaker.org@1.0.0 watch:js /root/id.webmaker.org
> npm run build:js -- --watch


> id.webmaker.org@1.0.0 server /root/id.webmaker.org
> node web/index.js


> id.webmaker.org@1.0.0 watch:css /root/id.webmaker.org
> autoless --source-map templates/less public

module.js:327
    throw err;
    ^

Error: Cannot find module 'json-stringify-safe'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/root/id.webmaker.org/node_modules/newrelic/lib/util/safe-json.js:3:21)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)

npm ERR! Linux 3.13.0-77-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run-script" "server"
npm ERR! node v4.3.1
npm ERR! npm  v2.14.12
npm ERR! code ELIFECYCLE
npm ERR! id.webmaker.org@1.0.0 server: `node web/index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the id.webmaker.org@1.0.0 server script 'node web/index.js'.
npm ERR! This is most likely a problem with the id.webmaker.org package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node web/index.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls id.webmaker.org
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/id.webmaker.org/npm-debug.log
ERROR: server: None-Zero Exit(1);

npm ERR! Linux 3.13.0-77-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
npm ERR! node v4.3.1
npm ERR! npm  v2.14.12
npm ERR! code ELIFECYCLE
npm ERR! id.webmaker.org@1.0.0 start: `npm-run-all --parallel server watch:css watch:js `
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the id.webmaker.org@1.0.0 start script 'npm-run-all --parallel server watch:css watch:js '.
npm ERR! This is most likely a problem with the id.webmaker.org package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm-run-all --parallel server watch:css watch:js
npm ERR! You can get their info via:
npm ERR!     npm owner ls id.webmaker.org
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/id.webmaker.org/npm-debug.log
root@Thimble:~/id.webmaker.org#

```

**Comment by Pomax** [comment]
You should not need to use sudo with NPM (in fact, it really should never ever be given superuser install permissions). Instead, tell npm to use a dir with your user's permissions by setting its `prefix` to a dir you control. See https://docs.npmjs.com/getting-started/fixing-npm-permissions

**Comment by cadecairos** [comment]
@dcforeman Yes, please try configuring npm to work without superuser permissions. Not only is it best practice, but it might solve some of your troubles.

**Comment by dcforeman** [comment]
I don't need to use sudo, it's simply there out of habbit, the result is the same with or without it.

**Comment by Pomax** [comment]
looking at https://github.com/mozilla/id.webmaker.org#up-and-running it seems you forgot some steps? The error you're getting is inside the newrelic package, but if you're running a dev instance newrelic should not be called in the slightest, suggesting you don't have a dev `.env` file set up.

**Comment by dcforeman** [comment]
Thank you I will check these instructions in the morning. This is the first time I've seen these as I've been running from the main instruction set on the thimble.webmaker.org archive. Thanks for your help so far.

**Comment by dcforeman** [comment]
Hi, I've been through the instructions.

Node and NPM installed, check. Using version 4.x.
Postgres 9.3 installed, check

Forked and cloned id.webmaker.org, check
Navigated into id.webmaker.org check
npm install command run, check
Set configuration variables, aka cp sample.env .env... check
npm start run, this is the failure point. Error messages generated:
```

root@ubuntu-512mb-nyc3-01:~/id.webmaker.org# npm start

> id.webmaker.org@1.0.0 start /root/id.webmaker.org
> npm-run-all --parallel server watch:css watch:js


> id.webmaker.org@1.0.0 server /root/id.webmaker.org
> node web/index.js


> id.webmaker.org@1.0.0 watch:css /root/id.webmaker.org
> autoless --source-map templates/less public


> id.webmaker.org@1.0.0 watch:js /root/id.webmaker.org
> npm run build:js -- --watch

sh: 1: autoless: not found

npm ERR! Linux 3.13.0-77-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run-script" "watch:css"
npm ERR! node v4.3.1
npm ERR! npm  v2.14.12
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! id.webmaker.org@1.0.0 watch:css: `autoless --source-map templates/less public`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the id.webmaker.org@1.0.0 watch:css script 'autoless --source-map templates/less public'.
npm ERR! This is most likely a problem with the id.webmaker.org package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     autoless --source-map templates/less public
npm ERR! You can get their info via:
npm ERR!     npm owner ls id.webmaker.org
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/id.webmaker.org/npm-debug.log
ERROR: watch:css: None-Zero Exit(1);

npm ERR! Linux 3.13.0-77-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
npm ERR! node v4.3.1
npm ERR! npm  v2.14.12
npm ERR! code ELIFECYCLE
npm ERR! id.webmaker.org@1.0.0 start: `npm-run-all --parallel server watch:css watch:js `
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the id.webmaker.org@1.0.0 start script 'npm-run-all --parallel server watch:css watch:js '.
npm ERR! This is most likely a problem with the id.webmaker.org package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm-run-all --parallel server watch:css watch:js
npm ERR! You can get their info via:
npm ERR!     npm owner ls id.webmaker.org
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/id.webmaker.org/npm-debug.log
```

**Comment by cadecairos** [comment]
What happens when we cut npm-run-all out of the equation? 

Try 'npm run build && npm run server'

**Comment by dcforeman** [comment]
I get the following errors

root@ubuntu-512mb-nyc3-01:~/id.webmaker.org# npm run build && npm run server
```

> id.webmaker.org@1.0.0 build /root/id.webmaker.org
> npm run build:css && npm run build:js


> id.webmaker.org@1.0.0 build:css /root/id.webmaker.org
> npm run watch:css -- --no-watch


> id.webmaker.org@1.0.0 watch:css /root/id.webmaker.org
> autoless --source-map templates/less public "--no-watch"

sh: 1: autoless: not found

npm ERR! Linux 3.13.0-77-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "watch:css" "--" "--no-watch"
npm ERR! node v4.3.1
npm ERR! npm  v2.14.12
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! id.webmaker.org@1.0.0 watch:css: `autoless --source-map templates/less public "--no-watch"`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the id.webmaker.org@1.0.0 watch:css script 'autoless --source-map templates/less public "--no-watch"'.
npm ERR! This is most likely a problem with the id.webmaker.org package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     autoless --source-map templates/less public "--no-watch"
npm ERR! You can get their info via:
npm ERR!     npm owner ls id.webmaker.org
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/id.webmaker.org/npm-debug.log

npm ERR! Linux 3.13.0-77-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "build:css"
npm ERR! node v4.3.1
npm ERR! npm  v2.14.12
npm ERR! code ELIFECYCLE
npm ERR! id.webmaker.org@1.0.0 build:css: `npm run watch:css -- --no-watch`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the id.webmaker.org@1.0.0 build:css script 'npm run watch:css -- --no-watch'.
npm ERR! This is most likely a problem with the id.webmaker.org package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run watch:css -- --no-watch
npm ERR! You can get their info via:
npm ERR!     npm owner ls id.webmaker.org
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/id.webmaker.org/npm-debug.log

npm ERR! Linux 3.13.0-77-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "build"
npm ERR! node v4.3.1
npm ERR! npm  v2.14.12
npm ERR! code ELIFECYCLE
npm ERR! id.webmaker.org@1.0.0 build: `npm run build:css && npm run build:js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the id.webmaker.org@1.0.0 build script 'npm run build:css && npm run build:js'.
npm ERR! This is most likely a problem with the id.webmaker.org package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run build:css && npm run build:js
npm ERR! You can get their info via:
npm ERR!     npm owner ls id.webmaker.org
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/id.webmaker.org/npm-debug.log
```

**Comment by cadecairos** [comment]
The error log tells me that autoless isn't installed or wasn't installed properly by npm.

Is autoless present in '$ID_WM_ORG_DIR/node_modules/.bin'?

**Comment by dcforeman** [comment]
Hi

Yes it is present, I've tried fixing these errors with npm install -g autoless, which does fix that error. But then it complains it can't find other modules, I've repeated that process several times but it consistently isn't able to find modules that are in that folder. For example it's asked for webpack, and webpack is present as well.

**Comment by Pomax** [comment]
could I ask this be moved over to the [`id.webmaker.org` repository](https://github.com/mozilla/id.webmaker.org/issues) instead, so we can address this issue in the right place, since this isn't technically a problem with thimble?

**Comment by Pomax** [comment]
filed as https://github.com/mozilla/id.webmaker.org/pull/414, which also has a PR with the solution to how to fix this.

**Comment by dcforeman** [comment]
@pomax I'm happy for that to happen, however I did post there 24 hours before I posted here. It's had zero responses in that time, the id project side seems pretty dead.

**Comment by Pomax** [comment]
interesting, I wonder it fell out of someone's inbox. I've noticed github not giving me all notifications I should be getting recently. (PRs that people tweet they filed, but github never notified me of, etc)

**Comment by dcforeman** [comment]
I've seen the post you made in the id.webmaker.org project, however it appears to be ignored without confirmation or indication that anyone is even alive over there to confirm the issue.

At present this makes the whole thimble concept un-deployable. I guess this is the problem with breaking projects like this up into different project sections, some of them just die out bringing down the whole system.

**Comment by gideonthomas** [comment]
@dcforeman we're sorry about the issues you are facing when trying to install Thimble. One of our main goals in the very near future is to make the installation process simple and unfortunately, it seems like there is a bunch of work to do there. 

As far are `id.webmaker.org` is concerned, it does seem like the discussion is happening here so I think for now let's just keep it here. I am happy to try to help you set this up (although `id.webmaker.org` is not my project of expertise) over IRC or a call if the discussion here is blocking you. Until then, I will draw the attention of someone who knows more about the project and will be able to provide more information about how you might be able to resolve some of the issues you are facing.

**Comment by cadecairos** [comment]
Don't worry @dcforeman, the project is not dead.

I landed some fixes to dependencies two days ago. Can you remove your node_modules directory and try installing dependencies using the latest develop branch?

**Comment by dcforeman** [comment]
Thanks for updates to the latest development branch. I'm deep into writing our groups new web development course at the moment, I'll check it out on the weekend and let you know if it works.

**Comment by dcforeman** [comment]
I've attempted to install using my old instruction, I don't get as far as the ID now, because the thimble.webmaker.org section won't run anymore.

root@ubuntu-512mb-nyc3-01:~/thimble.webmaker.org# npm start

> thimble.mozilla.org@2.0.0 prestart /root/thimble.webmaker.org
> npm run localize


> thimble.mozilla.org@2.0.0 localize /root/thimble.webmaker.org
> node scripts/properties2json.js

Skipping  hi-IN  due to missing strings
Skipping  uk  due to missing strings
Done writing: /root/thimble.webmaker.org/dist/locales/cs/messages.json
Done writing: /root/thimble.webmaker.org/dist/locales/de/messages.json
Done writing: /root/thimble.webmaker.org/dist/locales/dsb/messages.json
Done writing: /root/thimble.webmaker.org/dist/locales/en_US/messages.json
Done writing: /root/thimble.webmaker.org/dist/locales/es/messages.json
Done writing: /root/thimble.webmaker.org/dist/locales/es_CL/messages.json
Done writing: /root/thimble.webmaker.org/dist/locales/fr/messages.json
Done writing: /root/thimble.webmaker.org/dist/locales/hsb/messages.json
Done writing: /root/thimble.webmaker.org/dist/locales/hu/messages.json
Done writing: /root/thimble.webmaker.org/dist/locales/nl/messages.json
Done writing: /root/thimble.webmaker.org/dist/locales/pt_BR/messages.json
Done writing: /root/thimble.webmaker.org/dist/locales/pt_PT/messages.json
Done writing: /root/thimble.webmaker.org/dist/locales/ru/messages.json

> thimble.mozilla.org@2.0.0 start /root/thimble.webmaker.org
> node scripts/start.js

module.js:327
    throw err;
    ^

Error: Cannot find module 'babel-runtime/helpers/toConsumableArray'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/root/thimble.webmaker.org/node_modules/npm-run-all/lib/npm-run-all.js:8:27)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)

npm ERR! Linux 3.13.0-79-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
npm ERR! node v4.3.2
npm ERR! npm  v2.14.12
npm ERR! code ELIFECYCLE
npm ERR! thimble.mozilla.org@2.0.0 start: `node scripts/start.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the thimble.mozilla.org@2.0.0 start script 'node scripts/start.js'.
npm ERR! This is most likely a problem with the thimble.mozilla.org package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/start.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls thimble.mozilla.org
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/thimble.webmaker.org/npm-debug.log
root@ubuntu-512mb-nyc3-01:~/thimble.webmaker.org# sudo npm start
path.js:424
    var path = (i >= 0) ? arguments[i] : process.cwd();
                                                 ^

Error: ENOENT: no such file or directory, uv_cwd
    at Error (native)
    at Object.posix.resolve (path.js:424:50)
    at Function.Module._resolveLookupPaths (module.js:249:17)
    at Function.Module._resolveFilename (module.js:316:31)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at /usr/lib/node_modules/npm/bin/npm-cli.js:23:11
    at Object.<anonymous> (/usr/lib/node_modules/npm/bin/npm-cli.js:75:3)
    at Module._compile (module.js:409:26)
root@ubuntu-512mb-nyc3-01:~/thimble.webmaker.org#

**Comment by dcforeman** [comment]
Thanks for your support and efforts, since this ticket was opened 18 days ago our project timeline has moved on. I'm afraid I have to abandon Thimble now for something viable if we intend to hit our course deadline. Perhaps we'll revisit this project in a year or two.

It's a real shame, the system would have been a huge boon to our students. Thanks again for your efforts. I was hoping to at least provide a complete installation tutorial in return and help out with the support documentation. Best of luck with the development it will be a fantastic resource when it's deployable..

**Comment by gideonthomas** [comment]
@dcforeman I'm sorry to hear that you having so many issues installing thimble and have decided to continue with other products. I do hope that you consider trying it out again whenever time permits with the completely fair expectation that Thimble will provide a much better experience in terms of usage as well as setup.

This however is a good learning experience for us as this brings to light a bunch of issues that we should address soon. One of them is clearly the sheer complexity of setup. Perhaps we should prioritize working on a Docker solution to make this process easier. Either way we should figure out a good solution for this soon.

@dcforeman do you have any suggestions about how we might make setup easier?
cc @simonwex, @cadecairos, @humphd, @Pomax

**Comment by dcforeman** [comment]
Thank you for writing back, I will re-try the project upon our project refresh cycle, courses are generally written in year one, and then rewritten and updated year after year. As we have about 5000 students awaiting this first generation course I must progress. Meaning I'll come back and look at this in about a year.

I'm glad it was a good learning experience. I did feel I was complaining too much! Which I was trying to avoid so I hope I wasn't too much of a pain. Thanks for your patience.

My only suggestions lay in simplicity and project unity. From what I understand different parts of the project require different dependencies. This is natural of course, but when two or more parts require two different versions of the same dependency it becomes a big issue. Do I reduce or increase the version of one, so that the other might work and then risk breaking the other? In terms of installation if I do this I must first install one dependency, and then install, then reinstall that dependency with another version number then install, then hope both run.

I presume everyone has it working here effectively because you're all developers who can make these kinds of decisions pretty easily, Or simply understand the issues far greater than I do. I'm from a network deployment background and often setup CMS, linux servers, and various bespoke software, or other github project software generally with success. But that doesn't put me in the class of the developers here by a long shot. But I've never felt the need to begin threads like these either to get packages installed.

To be honest, I'd absolutely love to know the exact commands being used here by developers to set this project up on a Linux server because I'm unable to work out where I'm going wrong. And if there's any specific linux server setup for ubuntu 14.04.3 LTS I'm missing in order to let this work. Or even if another distribution of Linux is more effective than Ubuntu such as CentOS, Debian, or even OpenSUSE. Perhaps a Windows server would have solved the issues I was having? I'm at a loss at present either way.

Thanks again for your efforts! I will definitely be returning to try again next year.

**Comment by humphd** [comment]
Now that we've moved to using a Vagrant VM as our recommended setup method, this bug is likely not needed any more.  @gideonthomas can you confirm and close if so?

**Comment by gideonthomas** [comment]
Yeah I think we can close this since we're working on https://github.com/mozilla/thimble.mozilla.org/issues/1700
