### ISSUE TITLE
Installing Thimble, getting "TypeError: Cannot read property 'locale_src' of undefined" on npm install

### ISSUE THREAD

**Issue by asherdale** [mozilla/thimble.mozilla.org#1416]
Hello,

I'm running OSX Yosemite 10.10.4 and I'm trying to install Thimble. I've already successfully installed Bramble, but after cloning Thimble, I am having trouble running 'npm install'.

When I run 'npm install' (in the proper directory of thimble.mozilla.org), I get this error:

/root/thimble.mozilla.org/scripts/properties2json.js:14
var localeSrc = path.join(process.cwd(), l10nConfig.locale_src || "locales");
                                                   ^

TypeError: Cannot read property 'locale_src' of undefined
    at Object.<anonymous> (/root/thimble.mozilla.org/scripts/properties2json.js:14:52)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:140:18)
    at node.js:1001:3

npm ERR! Darwin 14.4.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "localize"
npm ERR! node v5.6.0
npm ERR! npm  v3.7.3
npm ERR! code ELIFECYCLE
npm ERR! thimble.mozilla.org@2.0.0 localize: `node scripts/properties2json.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the thimble.mozilla.org@2.0.0 localize script 'node scripts/properties2json.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the thimble.mozilla.org package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/properties2json.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs thimble.mozilla.org
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls thimble.mozilla.org
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/thimble.mozilla.org/npm-debug.log

Thanks for the help in advance, and hopefully I can start contributing soon!

**Comment by gideonthomas** [comment]
Hi @asherdale you will need to do the following:
`cp env.dist .env`

**Comment by gideonthomas** [comment]
I see that the order in the README is wrong, I'll fix that!

**Comment by asherdale** [comment]
Thanks @gideonthomas! Just successfully installed and ran Thimble.
