### ISSUE TITLE
add a way to turn off auto-previewing

### ISSUE THREAD

**Issue by Pomax** [mozilla/thimble.mozilla.org#1417]
If you have a large document, the auto-preview reloading actually starts to interfere with your typing in files, contantly interrupting the input stream, leading to far more typing errors than is otherwise the case, as well as contant unnecessary preview reset.

A feature similar to JSbin's "autorun with JS: [x]" checkbox would be very much appreciated.

**Comment by humphd** [comment]
What if you try turning off the Autorun JS feature in the gear menu?

**Comment by Pomax** [comment]
my intuitive thoughts there were "that icon clearly has nothing to do with preview settings, because it's in the editor pane"

**Comment by flaki** [comment]
This is a repeated ask at workshops.

@humphd where is that feature located that you are referring to? My "gear" menu only contains the following items: Text size, Color theme, Wrap long lines, Allow JavaScript and allow JavaScript turns off JavaScript completely in the resulting preview window (not the updating behavior).

For JS errors interfering with typing this solves the problem but then one needs to open dropdown, navigate the menu, click button every time on & off, which gets to be a hassle...

**Comment by humphd** [comment]
cc @flukeout 

OK, so it sounds like what is wanted here is a way to toggle the automatic refresh of the preview pane all the time.  We can do that.  It needs some UX, but the backend part isn't hard.  If get some help with the UI, I'll do the rest.

**Comment by Pomax** [comment]
As a quick "throwing out an idea" it might be nice to have this option as a toggle in/on the preview pane, but have the preview "know" there is new content, so that if you've been editing your files, and the auto-preview-refresh is turned off, you see a little question box in the upper right or something going "there were updates, refresh?" so that you get fine-control over when you refresh the view without turning auto-refresh back on (a bit like github's "this PR has updates, click here to refresh" notice)

**Comment by flukeout** [comment]
I'll get started on some UI / UX for this feature.

Definitely sounds like a feature we need given this feedback. Even though it's probably an issue only for a minority of users, we can't have things become unusable.

@flaki The feedback you're hearing, is it because of the same problems (large document that makes editing slow) that @Pomax is describing?

**Comment by flukeout** [comment]
Got a couple of ideas here... 

**Idea 1**
![image](https://cloud.githubusercontent.com/assets/25212/14256756/5365253c-fa4f-11e5-920a-4d9940de621e.png)

We _could_ add some indication of when there are changes that haven't been shown yet as a bonus. We could light up the "reload" button to the right side maybe. That could be a nice add-on.

**Idea 2**
We can add a gear menu to the preview pane, and divide the items and move the Javascript item to the new menu, where it makes more sense anyway.

![image](https://cloud.githubusercontent.com/assets/25212/14256808/8af70da8-fa4f-11e5-81fb-68eba6303436.png)

I think I like the first option more. For the second option I think the gear icon should be next to the PREVIEW label, even if that makes it inconsistent with where the other gear is. Otherwise it feels very cluttered over on the right.

Curious about your thoughts @flaki @Pomax and @humphd

**Comment by humphd** [comment]
I think I lean toward Idea 1 with the checkbox vs. adding another gear menu.

One thought I have about the case where the preview is "dirty" and needs a manual update--we could do some kind of overlay (darker gray or green?) over the entire preview pane, which visually indicates that it's intentionally not updating any more?

**Comment by flukeout** [comment]
@humphd seems a bit heavy handed - in the process of making edits to a CSS sheet for example, you might want to look at what's going on the page color-wise when picking a value, so modifying it with an overlay might become annoying. We could add a subtle animation to the reload button though, that would attract attention while also not distorting the preview.

Open to try either way though.

**Comment by Pomax** [comment]
I'd go with 1 as well.

As for "dirty" notification, just because there is new content doesn't mean the current content should become visually inaccessible. Highlighting the reload button feels like it might be too subtile, so perhaps a compromise: a small overlay that gets added similar to the remix dialog for published projects, so if you mouseover it expands to a readable text form "There is a new preview avalable, [update]()?"

**Comment by flaki** [comment]
@flukeout not as much as "large" documents per-se, but more like "we're coding and this thing preview on the right flickers constantly, jumps in-and-out-of-working" while bashing in a ton of code. I've used thimble with wide-ranging groups, from starting front-end folks writing their first HTML5/CSS endeavor, to Angular trainings and it worked great for most purposes, but this was a constant ask to have.

PS: if a checkbox, I'd put it right next/around the "reload" button above the preview plane and make it easily accessible (definitely wouldn't hide it i a cog-menu, as that would decrease visibility a lot and people wouldn't go into toggling it just leave it off most of the time, I'd imagine).

**Comment by flukeout** [comment]
@flaki Thanks for the feedback, I'm wary of putting the checkmark in the right side there with all that other UI, but we could also re-order things like this...

![image](https://cloud.githubusercontent.com/assets/25212/14359210/489f43dc-fca5-11e5-85a4-689325820acb.png)

I think this might be better. Of course, I would design it nicely, consider that a wireframe. We could also create a hybrid reload + checkmark thing, like...

![image](https://cloud.githubusercontent.com/assets/25212/14359406/1aad8604-fca6-11e5-9523-6394d1b1313e.png)

@gideonthomas @humphd How should we proceed, I can contribute to a branch once that basic markup and functionality is added if that works.  Cheers.

**Comment by xmatthewx** [comment]
I like the visual connection between the reload and checkbox @flukeout. 

Another approach might be a play/pause button that straddles the divide between code and preview. It could sit below the toolbar. It might not match our mental model, but could be more intuitive for new learners.

**Comment by flaki** [comment]
I'm loving all this! <3
Just a nit: I'd leave a bit more space between the checkbox & reload button (for touchscreen users, like me) - of course properly tagging the label as a <label>in the frontend build would ease that too).

**Comment by flukeout** [comment]
Just a bit of a progress update while I work away...

![image](https://cloud.githubusercontent.com/assets/25212/14470915/dfe606d2-00a0-11e6-845c-36100d52fa87.png)

**Comment by flukeout** [comment]
@flaki @Pomax We've pushed this update to staging https://bramble.mofostaging.net/en-US/

If you have a sec to try it out please do and report back if you have any feedback and comments! Cheers!

**Comment by flukeout** [comment]
I'm going to close this issue, as it has basically landed. We can make new issues for adjustments or fixes as needed.

**Comment by Pomax** [comment]
\o/

**Comment by flukeout** [comment]
This issue feels incomplete without a screengrab of the finished product, so here it is...

![auto-preview](https://cloud.githubusercontent.com/assets/25212/14515074/34c3db9c-01ab-11e6-940d-fe5919bc78dc.gif)

...aaah, closure.
