### ISSUE TITLE
Installing login.webmaker.org, getting "fetch failed with status code 404"

### ISSUE THREAD

**Issue by asherdale** [mozilla/thimble.mozilla.org#1418]
Hello,

I'm running OSX Yosemite 10.10.4 and I'm trying to install login.webmaker.org. I've already successfully installed Bramble, Thimble, and id.webmaker.org, but after cloning login.webmaker.org, I am having trouble running 'npm install'.

When I run 'npm install' I get this error:

npm ERR! fetch failed https://github.com/Pomax/less.js-middleware/archive/master.tar.gz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 404
npm WARN deprecated sequelize@1.7.10: security/injection issue with limit/offset fixed in 3.17.0
npm WARN deprecated MD5@1.0.3: deprecated, use lowercase 'md5@2.x' from now on
npm ERR! fetch failed https://github.com/Pomax/less.js-middleware/archive/master.tar.gz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 404
npm ERR! fetch failed https://github.com/Pomax/less.js-middleware/archive/master.tar.gz
npm ERR! Darwin 14.4.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v5.6.0
npm ERR! npm  v3.7.3

npm ERR! fetch failed with status code 404
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /root/login.webmaker.org/npm-debug.log

I further investigated the 404 error and found that the URL https://github.com/Pomax/less.js-middleware/archive/master.tar.gz is missing on a normal browser, and I get a 404 error when trying to access the page on Google Chrome. Is this repository missing? Was it recently removed? If so, how should I get around this issue?

Thanks in advance!

**Comment by Pomax** [comment]
this was a forgotten module update in login, a PR was filed and has been merged in to resolve the issue, and you should be able to install login.webmaker.org correctly now.

**Comment by asherdale** [comment]
Hi @Pomax , I still get the same error when running npm install. I even tried to delete the project and clone it again, and npm install still didn't work. Anything else that could help me?
Thanks!

**Comment by gideonthomas** [comment]
Hi @asherdale, if you re-cloned it from your own fork, it wouldn't have picked up @Pomax's changes. If you re-cloned it from the main fork, that's strange that you're still receiving the same error.
Either way, try the following in the login.webmaker.org folder using a terminal: `git pull https://github.com/mozilla/login.webmaker.org.git master` and then try `npm install`

Please also note that to run login.webmaker.org, you need to be running node v0.12. I suggest installing a version manager like `nvm` (instructions for which are at https://github.com/creationix/nvm#node-version-manager-) and using a node version of 0.12 for login.webmaker.org and > 4.x for all the other thimble dependencies. (I'll update the README to include this)
