### ISSUE TITLE
feature request: simplify "getting to a project"

### ISSUE THREAD

**Issue by Pomax** [mozilla/thimble.mozilla.org#1419]
Right now you need to click on your username, pick your projects, wait for a new page to load, then click through for there. Instead, might I request that clicking on "your projects" keeps doing what it does, but that it also automatically has an expansion for picking projects immediately?

Silly mockup:

![wefawefawefawe](https://cloud.githubusercontent.com/assets/177243/13205242/d3f0c068-d898-11e5-988c-18a94edd54ab.jpg)

**Comment by gideonthomas** [comment]
@flukeout what do you think about this?

@Pomax, I like it but I would remove the "Last edited" part from that list

**Comment by humphd** [comment]
You'd have to deal with scrolling, which might make that UI cumbersome.  What if it showed you the most recent ones, and had a link to "All..." at the bottom of the list?

But I defer to @flukeout.

**Comment by Pomax** [comment]
I imagine that most of our users don't have hundreds of projects. Ordering on "last edited" (which we can probably do without) and then offering a scroll bar if there are so many projects that they don't fit on the screen feels like an acceptable UX if the vast majority of the time the project users want to load are going to be in the top 10 of that list, so that even if there's a visible scrollbar, it's not necessary to actually scroll.

**Comment by flukeout** [comment]
I agree that it's cumbersome to get to your projects from the homepage when you're not yet signed in. Another way to solve this would be...
* When you sign in, redirect to...
  * "My Projects" page, when you have projects (so you can choose one)
  * Editor for when you don't
* Somehow inject a lit of your projects directly into the homepage

Anyway, with that dropdown, I feel like you'd have to click "My Projects" to access the list anyway (relying on hover always feels finicky), so you're not really saving a click - just the pageload.

**Comment by Pomax** [comment]
I don't mean for "when you're not signed in" though, even when the cookie's already set, having to navigate to a new page feels flow-breaking.

**Comment by cgsingh** [comment]
Hi. I'm interested in this issue. But do you guys have an idea on what you want to do for this?

**Comment by flukeout** [comment]
Hey @cgsingh - I think the redirect would work pretty well in this case, though I do like @Pomax's mockup too. Would you mind giving that a try first since it's the easier option?

**Comment by cgsingh** [comment]
Sorry, I'm going to have to withdraw from this issue. Hopefully someone takes this feature, it would be useful.

**Comment by humphd** [comment]
np, @cgsingh, we'll put it back in the general pool.

**Comment by flukeout** [comment]
I'm going to file a new issue with just the redirect to the Your Projects list for now. We can leave this as a follow up.

**Comment by Rajat-dhyani** [comment]
@Pomax @gideonthomas @humphd @flukeout  i have some quick questions...
1- Right now if i am signed in and i click on `your project` option i am redirected to `/projects` tab. So what i suppose you want right now is to have a hover over feature which just like the mockup shows list of recent project and a `view more` option. Right?
2- If no one is assigned to this i would love to work on this issue...

**Comment by flukeout** [comment]
Hi @Rajat-dhyani that is correct. And yeah, you can go ahead and get started. I think we can limit the menu items to the last 5 projects that you were working on and put a "Recently Edited" heading on the menu. Once you get some of the code running, I can assist with design.

**Comment by Rajat-dhyani** [comment]
great... @flukeout i am taking this over and will revert back to you. Thanks :)

**Comment by Rajat-dhyani** [comment]
@Pomax @flukeout @humphd @gideonthomas 
![ss](https://cloud.githubusercontent.com/assets/17648963/23829003/c6d81fac-0709-11e7-8038-e988ea2c3818.gif)

i was able to get the list of projects onto the  menu but i am tackling with two problems.
1- `hover over` is not working - when i am listing the event `onClick` it is working fine but when i change the event to `onhover` it is not doing anything.
2-  the projects are not loading in `homepage` but  are working fine in `/projects` page. I know they are being called at back end by `project-list.js` but i tried adding it too at the homepage still it is not working. Is there anything else that i am missing?
I have attached a short clip of how it is working now. 
P.S : Don't mind the style 🙈 i will work on it later i was just focusing on first getting the project onto menu bar and yea we can slice them down to 5 once fully developed.

**Comment by Pomax** [comment]
Looking pretty good so far!

**Comment by Rajat-dhyani** [comment]
@pomax the `hover over` is working fine now...  if you could help me with the second problem that i am facing that would be great help.
thanks

**Comment by Pomax** [comment]
Hm, this issue fell of a the map a little - @Rajat-dhyani did you have a PR up for this work already somewhere?

**Comment by Rajat-dhyani** [comment]
@Pomax  i am so sorry i was under the impression that i already filed a PR for this issue... my bad.. i am busy today with my college project.. please expect a PR by tomorrow... sorry again and thanks for informing me about this 👍

**Comment by humphd** [comment]
@flukeout this issue and the PR associated need to get moved along, or closed if we're not going to do it.  Can you make a call?

It doesn't seem to me like the approach here is right.

**Comment by flukeout** [comment]
Closing as we have decided not to pursue this - seems complex for what you get.
