### ISSUE TITLE
Document steps to localize strings

### ISSUE THREAD

**Issue by humphd** [mozilla/thimble.mozilla.org#1420]
We need a short guide to help devs and localizers work with strings in Thimble and Brackets.  This is connected to #1355.

**Comment by gideonthomas** [comment]
@humphd https://github.com/mozilla/thimble.mozilla.org/wiki/Localization

**Comment by humphd** [comment]
This is great, thank you.  I've made some fixes/corrections.  Can you add a link to this wiki page in the README, so that it's easier to find?  After that, r=me.

**Comment by gideonthomas** [comment]
https://github.com/mozilla/thimble.mozilla.org/commit/96cb77b74d8f93332a15c748bd9228f41b59d653
