### ISSUE TITLE
scrollTo for an update on a long document visually skips around content

### ISSUE THREAD

**Issue by Pomax** [mozilla/thimble.mozilla.org#1421]
If you remix https://d157rqmxrxj6ey.cloudfront.net/mopaxian/27916/, then scroll down in the preview to something like "So how do you "spiro"?", and then add some noop to script.js, like

```
var whatever = function() {};
```

then you first have to wait what feels like a very long time for the preview to catch up (a full second it feels like?) and then the preview will reload the content and then scroll to where were were, but there can be a significant pause in between the "reload" and "scrollTo", making it look like the preview is skipping around content. Paired with the reload delay, this is a rather unpleasant experience.

**Comment by gideonthomas** [comment]
Closing as this has been refiled as a good first bug under https://github.com/mozilla/thimble.mozilla.org/issues/1671
