### ISSUE TITLE
Database Documentation

### ISSUE THREAD

**Issue by adamlofting** [mozilla/thimble.mozilla.org#1422]
WRT to issue https://github.com/MozillaFoundation/plan/issues/725

We're currently scoping out possible Learning Analytics research that could be done using Thimble. In order to inform the research proposal and project plan, we need to understand what data is currently stored.

* What data do we store? (including user data in the connected login / id systems)
* What do we keep historic versions or logs of? (do we store past versions of projects or history of logins for example)
* What is structured data vs project files?
* What technology is used?

**Comment by gideonthomas** [comment]
Hi @adamlofting, sorry for getting back to you so late. Hope these points answer your questions:
* DB table data:
 * **publish.webmaker.org** - *PostgreSQL*
    * Users - username
    * Projects - who created the project (username), name, description, date/time created and last updated, created by X-Ray Goggles or Thimble, associated files, url for published version
    * Published Projects - name, description, date/time created and last updated, associated files, associated project
    * If a project was published, unpublished and then re-published again, a new data entry is created, so the previous published project version is in no way related to the re-published version
 * **id.webmaker.org**
   * cc @cadecairos or @jbuck
* GA events:
 * User clicks "sign in" or "create an account"
 * User creates a new project (separate labels for authenticated and unauthenticated)
 * User deletes a project
 * User changes the editor font size
 * User renames a project
 * Remixing someone else's project
* We do not store past versions of projects, at one given time there can only be a max of 2 versions - the current and the published(may exist)

Let me know if you need any more info :)

**Comment by cadecairos** [comment]
### id.webmaker.org (OAuth2 provider (Hapi JS), Postgresql backed ) 

- client
  - client_id (GUID)
  - client_secret (GUID)
  - allowed_grants
  - allowed_responses
  - redirect_uri
- auth_codes
  - auth_code
  - client_id
  - user_id
  - scopes
  - expires_at
  - created_at
- access_tokens
  - access_token
  - client_id
  - user_id
  - scopes
  - created_at

### login.webmaker.org (User Account data, Express server, MySQL backed)
- user
  - id (numerical GUID)
  - username
  - email
  - prefLocale
  - lastLoggedIn
  - usePasswordLogin (if false, uses email based one time tokens to log in)
  - isAdmin
  - sendNotifications
- loginToken (one time use login tokens)
  - token (randomly generated login token)
  - used (bool)
- resetCode
  - code (one time use code that enables password resets)
  - used (bool - has been used to reset a pw successfully)
  - invalid (bool - code was used unsuccessfully)
- password
  - saltedHash (bcrypted, individually salted password hash) 
  - userId (GUID of the user associated with this hash record

**Comment by adamlofting** [comment]
Perfect! :+1: 

Thanks @gideonthomas and @cadecairos
