### ISSUE TITLE
Figure out the relationship between locales for Thimble and Brackets

### ISSUE THREAD

**Issue by gideonthomas** [mozilla/thimble.mozilla.org#1423]
There will be situations when Thimble is localized in one language (for e.g. "es"), while Brackets will not be localized in that language but *may* be localized in a similar language (for e.g. "es-MX"). The question is should we select the "closest language" to the language picked in Thimble for Brackets, or should we default to "en-US"?

We discussed this a little bit in a call and the inclination was towards picking the "closest language". I think we should discuss this again and make sure that it makes sense.

@flukeout previously had a good suggestion for Thimble alone where we show some kind of UI based on the percentage translated for a language and ask the user if they still want to continue viewing that page in that language or switch to another one. Maybe we can make use of this concept for the Thimble-Brackets issue as well?

cc @alicoding, @simonwex, @humphd, @hannahkane

**Comment by humphd** [comment]
I would suggest that we always use a close locale, by trying to first match exactly, then using the language portion only.  So if you have "es-MX" and we only have "es" in Brackets, that's better than "en-US".

**Comment by alicoding** [comment]
Doing what @humphd said would work and I would agree that's better than showing English here.

**Comment by gideonthomas** [comment]
@alicoding what about the other way around? Thimble has "es" whereas Brackets has "es-MX"?

**Comment by alicoding** [comment]
I dont think it's a good idea to default a locale to another locale that specific to that country. There has been some incidents with our contributors in the past and the best thing to handle this would be either not enable that locale in production or just default to non region locale or fallback to English

**Comment by gideonthomas** [comment]
@alicoding just to clarify:
It should be ok for us if we switch Brackets to "es" if "es-MX" is not available and Thimble is in "es-MX"?
**but**
You suggest that we should not switch Brackets to "es-MX" if "es" is not available and Thimble is in "es"?

**Comment by alicoding** [comment]
Yep. I don't think it's wise to switch to region based language for example.

My default locale is `['ar-IQ', 'en', 'th']`
If `ar-IQ` and `ar` are available in Thimble, but in Bracket only `ar` it
is okay to switch me to `ar` for both, but ideally should switch to `en` or
`th` if `en` was not available then we go to the default.

Whereas, if `ar-IQ` and `ar` available in Thimble, but only `ar-TN`
available in Bracket then you should just switch to `en` or `th` if
available otherwise default language.

**Comment by gideonthomas** [comment]
@humphd does this sound like a good plan? ^

**Comment by humphd** [comment]
I think so.  Have Thimble vs. Brackets make the localization choice, and only switch to use lang vs. lang-Region in Brackets *if* we don't have exactly what is required.  But if the user asks for some lang or lang-Region in Thimble we don't have (but do have in Brackets), just use the default for both.

**Comment by gideonthomas** [comment]
Turns out, Brackets (requirejs really) already handles this exactly the way discussed above! Closing.
