### ISSUE TITLE
Acknowledgments for l10n contributors

### ISSUE THREAD

**Issue by gideonthomas** [mozilla/thimble.mozilla.org#1425]
Write a script to automatically grab new email addresses and github names from l10n contributors when they commit and add them to the README as well as a notification in mattermoz

**Comment by gideonthomas** [comment]
cc @jbuck and @Pomax for ideas

**Comment by Pomax** [comment]
It feels like a merge-hook would make sense here, to grab the "who filed the PR" information and then auto-generate an updated contributors list. (read in list, build name map, add name, write list back out).

**Comment by gideonthomas** [comment]
@Pomax but git-hooks belong to a local git repo right? How would we add that to something like Pontoon?

**Comment by Pomax** [comment]
we use a webhook: https://developer.github.com/v3/repos/hooks/

**Comment by gideonthomas** [comment]
Ooooh interesting! I'll take a look at that! Thanks @Pomax

**Comment by gideonthomas** [comment]
So instead of a complicated automated way to do this, we should just link to https://pontoon.mozilla.org/projects/thimble/contributors/ in our README so that users can see the contributors out there.

@simonwex does this sound like a good idea?

**Comment by simonwex** [comment]
Linking to the pontoon page totally makes sense to me.
