### ISSUE TITLE
UI overlaps with text in some languages

### ISSUE THREAD

**Issue by gideonthomas** [mozilla/thimble.mozilla.org#1427]
eg:
![screen shot 2016-02-26 at 12 41 21 pm](https://cloud.githubusercontent.com/assets/5816130/13360285/70bd7fd0-dc86-11e5-842b-4f396d2f03fc.png)

We should make it extensible regardless of locale.

@flukeout would you be able to take this on?

**Comment by flukeout** [comment]
You got it.
