### ISSUE TITLE
Speed issues in China

### ISSUE THREAD

**Issue by humphd** [mozilla/thimble.mozilla.org#1430]
From Twitter: https://twitter.com/nizibaba1/status/704320020336156673

Would be good to figure out what the problem is.

**Comment by nizibaba** [comment]
Hello, thimble, including goggles, etc. in China is very slow operating speeds, in most cases, we need to refresh several times before they can normally open, several recent events appear completely unable to open the phenomenon, 
We believe that this is school network problem，because will have 50-60 computers at the same time access https://thimble.mozilla.org/，, the school network can not support the cause, we will test this idea in the following activities.
My English is poor, please forgive me.

**Comment by humphd** [comment]
cc @jbuck, @Pomax

**Comment by gideonthomas** [comment]
we can work on trying to reduce the number of requests and making the response size smaller somehow

**Comment by humphd** [comment]
I wondered if there was also anything geographic to consider with regard to our CDNs physical locations, or where the apps are hosted (i.e., do we have servers in Asia?)

**Comment by jbuck** [comment]
We're using Cloudfront, but surprisingly enough, AWS doesn't have a [CDN endpoint in Beijing](https://aws.amazon.com/cloudfront/details/). 

We have fast internet here at the office, but it's still incredibly slow loading http://www.amazonaws.cn/en/ . AWS does have a China region, but it [requires a Chinese legal entity](http://www.amazonaws.cn/en/sign-up/) so I don't think we can actually deploy anything within China.

**Comment by gideonthomas** [comment]
Reducing the number of requests made should make the experience better though so that it won't matter as much where the endpoint is

**Comment by Pomax** [comment]
I see the homepage loading 4.7 MB in 48 requests, which is quite a lot more. Is there a reason the editor itself gets loaded on the main page, even though it's then not used? That'll cut down at least on the main page load (although doesn't really address this issue I think)

**Comment by humphd** [comment]
The reason we pre-fetch those files in the homepage is so that the editor loads more quickly (i.e., we hope to have them get cached).  We could easily experiment with not pre-loading them, but I think you just trade load times between homepage (which you load once) vs. editor (where you mainly live).

**Comment by Pomax** [comment]
Was that a metrics-based decision? It feels like a premature optimization that prevents people from loading the main page in a timely fashion.

**Comment by humphd** [comment]
If you take a look at the screenshots in that tweet, the issue is always the editor, not the homepage.

**Comment by humphd** [comment]
https://github.com/mozilla/brackets/pull/637 should help with this, but beyond that, I'm not sure what action to take without more data.  I'm going to close this until we have some real info we can use to make improvements.
