### ISSUE TITLE
Which part of the source is responsible for preview element outlining/highlighting?

### ISSUE THREAD

**Issue by tjfwalker** [mozilla/thimble.mozilla.org#1431]
In Thimble, when the cursor is positioned within an HTML element in the editor, a highlight is flashed on the corresponding element in the preview and an outline, that persists 'til the cursor is moved to a different element, is also placed on it.

I've browsed through the source code but failed to identify the module, package, function, whathaveyou responsible for this functionality.

I'd appreciate anyone pointing this bit of source out to me. Thanks

**Comment by gideonthomas** [comment]
This feature is a Brackets (the code-editor that Thimble uses) Live-Development feature. The code that tells the preview to highlight the element is [here](https://github.com/mozilla/brackets/blob/master/src/LiveDevelopment/MultiBrowserImpl/documents/LiveDocument.js#L319-L331) which is called from [here](https://github.com/mozilla/brackets/blob/master/src/LiveDevelopment/MultiBrowserImpl/documents/LiveHTMLDocument.js#L151-L172) when a click on an element in the editor occurs. This code sends a `postMessage` to the preview which accordingly highlights the element according to [this script](https://github.com/mozilla/brackets/blob/master/src/LiveDevelopment/Agents/RemoteFunctions.js#L469-L487)

**Comment by tjfwalker** [comment]
Thanks for such an actionable response to my inquiry, @gideonthomas.
