### ISSUE TITLE
Should we include the word "remix" in a project title

### ISSUE THREAD

**Issue by gideonthomas** [mozilla/thimble.mozilla.org#1433]
I am currently working on localizing the "(remix)" part that we usually append to a project title if it is being remixed.
There are a bunch of challenges here such as:
* Figuring out the order in which the translated part is incorporated into the title for different languages. For e.g. "My Title (remix)" vs. "(remix) My Title"
* Figuring out if the title already contains "(remix)" in it and not appending it twice (a remix of a remix). This is probably the biggest challenge since we need to figure out how to check the current project title for every possible translation of the "(remix)" string keeping in mind the constraint mentioned in the previous point.

The real question here though is if figuring this out is worth it or not. Let us question the need to even add the word "(remix)" to the title (which we don't think is being used a lot anyway). What does it add to the title and is it useful information to the user? Should we just leave it the way it is now and not localize it?

Personally I think that we should nix the suffix from the title since it doesn't really convey anything useful to the user. But, I would like to hear thoughts about this.

cc @hannahkane, @flukeout, @simonwex, @humphd, @alicoding, @ScottDowne, @Pomax

**Comment by hannahkane** [comment]
Few things:

1) Would like to hear from @chadsansing on this topic, too
2) I feel that it's a somewhat useful piece of feedback for users to know that they're not editing the original
3) Having said that, I don't think it's a *critical* piece of info to have. 
4) I think it *would* be useful to have a way to get back to the original item, but I know that's a whole 'nother ball of wax, and not relevant to the l10n question here.

**Comment by chadsansing** [comment]
I think the idea of "remix" is also not valued in some of the cultures with which we work (as per research). Perhaps we could localize more broadly with, "My copy of," which doesn't solve any of the problems of translation or recursion, but might play better globally.

I think this might be a problem for super-users who use certain projects as templates for others. If they forget to rename a project or two, then they would be stuck figuring out which "remix remix" or "remix remix remix" they updated last. Maybe there could just be a floating, pulsating circle "hint" on the title when Thimble opens with a mouse-over message like, "Be sure to change your title to something new!"

**Comment by gideonthomas** [comment]
@chadsansing brings up an interesting point - what if our solution to provide this feedback doesn't require modifying the title at all? What if we create a UI solution for this?

**Comment by alicoding** [comment]
I agree with @chadsansing here since my native language with the word `remix` it makes no sense when we put it together especially with this context. The use of `copy` is understandable and can be translated to make better sense here. Though, the UI solution could be something we can totally fix this problem here.

**Comment by jgmac1106** [comment]
I wish on the initial publishing you were forced to change or add title. It
is PITA as a teacher to see all these projects with the same file name or
then remixing a project to examine code and I end up with "untitled project
(remix) or My post.

In terms of l10n @chadsansig is correct "remix" does not work. "Copy of X"
would be better. or would a version number even be possible? which may hook
back to @hannahkane's point on getting back to the genesis project.

**Comment by ScottDowne** [comment]
To me it feels like remix is meta data about the project, but doesn't need to be part of the title itself.

It would be easier to localize it outside of the title, but I also think it's a low priority in general. I don't think people care too much about the title until they change the title, which at that point, I don't think they need much.

**Comment by Pomax** [comment]
Note that we don't strictly speaking want to translate the word "remix", we want to translate the concept of a fork, probably with modifications and personalisations, but not strictly speaking necessary.

**Comment by hannahkane** [comment]
I'm +1 on a UI solution. We discussed this here: https://github.com/mozilla/thimble.mozilla.org/issues/1284

**Comment by gideonthomas** [comment]
Sounds good, so until then (in favor of a UI solution), should we leave it as is?
viz. a title with "(remix)" at the end and it won't be localized?
