### ISSUE TITLE
Thimble currently seems to be unreachable for some users...

### ISSUE THREAD

**Issue by tperrigo** [mozilla/thimble.mozilla.org#1438]
Greetings,
I am not a Thimble user, but I am a software engineer working with a teacher using Thimble for a grad class.  Currently (7:45am Central Time (US), 6MAR2016, several members of her class are unable to log into Thimble.  I tried to create an account for myself, and am receiving the following error:
"An unknown error occurred on the server. Try your request again. If the problem persists, get help."

These students have a large project due at the beginning of the week, and are beginning to panic.  Is there a problem that Thimble Support is aware of?  Is there any ETA on a fix?

Any help would be very much appreciated.  I'm sorry I cannot provide more detail; I'm working with these students remotely, but they've all just reported being unable to access Thimble (although I know it was working correctly for them yesterday).

Thanks,
Timothy Perrigo

**Comment by chrislarry33** [comment]
Hello,

I just want to make sure they are using the correct link

https://thimble.mozilla.org/

**Comment by tperrigo** [comment]
That's the site where I tried to create an account this morning and received the "unknown error" message (I just tried again and received the same error); I will verify with the students that reported the problem to me this morning and get back to you.
Thanks,
Tim

**Comment by tperrigo** [comment]
Just verified with one of the students:  she enters her credentials at https://thimble.mozilla.org, but it never gets past the login screen.  This is the behavior I am now seeing as well (no error; just no action at all-- no way for me to create an account; no way for the students to log in to their existing accounts).

**Comment by tperrigo** [comment]
Some further information, if it is helpful:  I have tried creating a thimble account (using Firefox) on Ubuntu 14.04; the students I've been in contact with are also using Firefox, but are running on Windows.  If there's any further diagnostic information I can send or anything I can test on my end, please let me know.  The students are using Thimble for a project due at the beginning of the week and are beginning to panic.  If I can do anything to help reproduce the issue or provide any additional information, please contact me...I truly appreciate any assistance!

Tim

**Comment by tperrigo** [comment]
(I should note: the students already have existing Thimble accounts-- everything seemed to be working fine for them yesterday).

**Comment by preetidulloo** [comment]
Same is the case with me also. I am a teacher and I have given my students some project work that they need to subject by 8th March, and suddenly, Thimble stopped working for everyone. I would be great if team of Thimble can fix this as soon as possible.

**Comment by preetidulloo** [comment]
Same is the case with me also. I am a teacher and I have given students some project work that they need to submit by 8th March. From last 24 hours (appx), Thimble's 'login in' button's functionality stopped working. It validates all the checks on username and password at the client end but do nothing, once the client clicks on 'login in' button. 

It would be great if team of Thimble can fix this as soon as possible.

**Comment by davidascher** [comment]
I can confirm that I can't sign in to Thimble.  Escalating to our devops team to dig into it.

**Comment by davidascher** [comment]
We're looking into it, will update this bug as soon as we know more.  Apologies folks, I realize that's a real problem for your classes.  We'll get it working soon.

**Comment by preetidulloo** [comment]
Thanks a ton for prioritizing this issue!

**Comment by davidascher** [comment]
Should be fixed now, thanks to @jbuck. We'll figure out what happened, but do let us know if it is or isn't working for you now.

**Comment by preetidulloo** [comment]
Yeah, it's working. Your help is much appreciated!

**Comment by davidascher** [comment]
great!  Again, apologies for the outage.

**Comment by davidascher** [comment]
I'll close this bug as at this point all signs indicate it's been dealt with, but feel free to reopen it if it's still not working for you.
