### ISSUE TITLE
(Saving failed, retrying...)  unable to publish

### ISSUE THREAD

**Issue by mrivantan** [mozilla/thimble.mozilla.org#1441]
Cue says unable to save:
<img height="50" alt="screen shot 2016-03-08 at 5 58 37 pm" src="https://cloud.githubusercontent.com/assets/2179260/13598246/c73fc082-e557-11e5-80e9-a8c137f4817b.png">
However it saves perfectly fine. On the other hand, I am unable to publish:
<img width="200" alt="screen shot 2016-03-08 at 5 58 58 pm" src="https://cloud.githubusercontent.com/assets/2179260/13598249/c7480ddc-e557-11e5-9568-0f22b34b0ea6.png">
These are the files I am working with (no sub folders):
<img height="167" alt="screen shot 2016-03-08 at 5 58 46 pm" src="https://cloud.githubusercontent.com/assets/2179260/13598247/c74381ea-e557-11e5-8fa3-34ded974c0f3.png">
This is my console message:
<img width="700" alt="screen shot 2016-03-08 at 6 00 58 pm" src="https://cloud.githubusercontent.com/assets/2179260/13598248/c7478290-e557-11e5-9d2a-1aa7d0997af2.png">

Help will be much appreciated. Keep up the good work :)

**Comment by gideonthomas** [comment]
Hi @mrivantan! Thanks for reporting this! By any chance did you rename any folder in your project? If so, we are discussing the issue here: https://github.com/mozilla/thimble.mozilla.org/issues/1311. We are working on a fix for that. If not, can you provide any steps to reproduce?

**Comment by mrivantan** [comment]
yes I renamed a folder, thought it might have been the issue and removed
the folder.
thank you for your prompt reply!

**Comment by gideonthomas** [comment]
No problem at all! Feel free to follow the issue linked above! For now, I'll close this one.
