### ISSUE TITLE
Missing remix button

### ISSUE THREAD

**Issue by chadsansing** [mozilla/thimble.mozilla.org#1455]
The remix button is missing from published Thimble projects, e.g. https://d157rqmxrxj6ey.cloudfront.net/chadsansing/31632/. Webfonts/stylesheets may not be loading, as well. Reported by a user looking at our Letters to the Next president/#2NextPrez materials that have been submitted to be linked to on a partner site.

![screen shot 2016-03-22 at 6 51 10 am](https://cloud.githubusercontent.com/assets/4128600/13949288/8fc9076e-effa-11e5-89b5-600dc7086001.png)

cc @ldecoursy

**Comment by chadsansing** [comment]
If you republish a project and open it from the URL given to you by Thimble, the remix button appears. If you go to the link itself, the button does not appear. Refreshing the page after opening it from the link in Thimble loses the remix button. Older projects, such as https://thimbleprojects.org/chadsansing/33434/, do not seem to have the same issue.

**Comment by Pomax** [comment]
This would be a problem @gideonthomas @humphd 
```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://thimble.mozilla.org/projects/remix-bar?host=https%3A%2F%2Fthimble.mozilla.org&id=31632&title=Candidate+Meme+Project&author=chadsansing&updated=2016-03-07T11%3A45%3A02.435Z&_=1458653189862. (Reason: CORS header 'Access-Control-Allow-Origin' missing). <unknown>
```

**Comment by gideonthomas** [comment]
@chadsansing Fixed!
