### ISSUE TITLE
Get to published link from Your Projects list

### ISSUE THREAD

**Issue by techkim** [mozilla/thimble.mozilla.org#1457]
I'd like to be able to get to the published version of my project from the Your Projects page without having to go into remix mode. It would also be a way to tell whether a project has been published or not.

**Comment by gideonthomas** [comment]
Hi @techkim we're discussing the issue here: https://github.com/mozilla/thimble.mozilla.org/issues/1289
We would def be willing to accept a PR if you want to contribute. But realistically, this might take some time to implement.
