### ISSUE TITLE
Server sends HTTP 500 to the client during an attempted save

### ISSUE THREAD

**Issue by gideonthomas** [mozilla/thimble.mozilla.org#1460]
Context: https://github.com/mozilla/thimble.mozilla.org/issues/1458

The "Saving Failed...Retrying!" error in **this case** was not because of a rename. The folder structure for the project was:

```
|
|- index.html
|
|- file_1.html
|          :
|- <4 more html files>
|
|- style.css
|
|- /folder_1
|     |
|     |- file.pdf
|
|- /folder_2
|     |
|     |- <20 image files (png and .jpeg)>
|
|- /folder_3
      |
      |- <9 html files>
```

Noteworthy things about this project:
- Some of the folders had spaces in their names
- There were many files in the project but each of them were within the file size bounds

I was able to reproduce this error **once** on production with a different STR. I took the zipped project, extracting it locally and then individually dragging and dropping everything into Thimble (without the "Upload Files" dialog). Before I dnd'ed the files inside the folders, I had to create the folder in Thimble, dnd all the files I needed for that folder from my local machine into Thimble (it lands in the root) and then select each file and "Move To" the newly created folder.
I then inspected the logs on prod and saw that the server was sending an Internal Server Error back to the client (not sure if it was coming from publish.wm.org or not).

I tried to reproduce locally, but wasn't able to. Then I tried on prod again and it didn't happen this time.

My suspicions:
Something in the sync queue is screwing up - either the order of operations or something. I do find it weird that the error is a 500. I do think it might be coming from publish because I did not see any logs in thimble suggesting a JS error. Maybe there is an issue with the file streaming op? Maybe we're hitting a concurrency issue with publish? Or maybe this is a client-side issue where we are not sending a file id or something (unlikely).

Either way this needs to be investigated!

**Comment by humphd** [comment]
Re-reading #1458, I suspect that this is the `ENOENT` bug I fixed.  I'm going to close this, since we don't have enough info to go on for fixing.
