### ISSUE TITLE
Removing/Deleting old makes from a deleted account.

### ISSUE THREAD

**Issue by edriann** [mozilla/thimble.mozilla.org#1461]
A few years ago, I tried using the webmaker service and did a really poor and basic HTML page. It has somehow been published and I've deleted my account long since I discovered that when I Google search for my name, the make appears as a result. I have put some not-so sensitive but my school and student number on the said page and I would like it to be removed.

Is there a way that I could have this deleted?

**Comment by gideonthomas** [comment]
@cadecairos can we do this?

**Comment by cadecairos** [comment]
@gideonthomas yeah, it can be done. we can address this issue in MozillaFoundation/mofo-devops#296

**Comment by gideonthomas** [comment]
@edriann your content should be removed now. If you are still able to access your makes, let use know and we will take a look again.
