### ISSUE TITLE
thimbleprojects.org’s server DNS address could not be found.

### ISSUE THREAD

**Issue by thornet** [mozilla/thimble.mozilla.org#1463]
"DNS_PROBE_FINISHED_NXDOMAIN"

When publishing a Thimble project, I encountered this error (screenshot attached). 

![screen shot 2016-03-29 at 20 07 10](https://cloud.githubusercontent.com/assets/739174/14118491/01fbe4b0-f5ea-11e5-8c25-d97660aff3ec.png)
 
My project still works under this URL: https://d157rqmxrxj6ey.cloudfront.net/michelle/48075/

**Comment by thornet** [comment]
Update: if I load this using a different wifi connection, it works. Must've been something on the Mozilla Berlin network causing this...?

**Comment by gideonthomas** [comment]
Yeah @thornet sorry, I think their DNS needs to be refreshed and apparently it's happening really slowly. 

cc @cadecairos

**Comment by gideonthomas** [comment]
If you change your DNS configuration to use Google's DNS for e.g., it should work even in the Mozilla Berlin network.

**Comment by thornet** [comment]
Thanks! If this is a known issue, then we can close this ticket.

**Comment by cadecairos** [comment]
I'm really surprised that mozilla's internal DNS hasn't updated in over a week. I'll poke around the Moco Ops IRC about this.

**Comment by cadecairos** [comment]
FYI: https://bugzilla.mozilla.org/show_bug.cgi?id=1260602

**Comment by cadecairos** [comment]
I'm going to re-open this, and dump in any findings that come up in the BZ bug investigation, and close when the issue is resolved

**Comment by cadecairos** [comment]
@thornet @gideonthomas I'm told this should be resolved now

**Comment by thornet** [comment]
Confirmed that it's fixed for the Mozilla Berlin network.

On Wed, Mar 30, 2016 at 12:34 PM, Christopher De Cairos <
notifications@github.com> wrote:

> @thornet <https://github.com/thornet> @gideonthomas
> <https://github.com/gideonthomas> I'm told this should be resolved now
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/mozilla/thimble.mozilla.org/issues/1463#issuecomment-203371507>
>



-- 
*Michelle Thorne*
Mozilla Foundation

@thornet
michelle@mozillafoundation.org

**Comment by cadecairos** [comment]
Yay! marking this closed now
