### ISSUE TITLE
Creating a challenge

### ISSUE THREAD

**Issue by onel** [mozilla/thimble.mozilla.org#1464]
Hello, 

I really like this project and I'm happy it's focus is educational.
It's cool that the `tutorial.html` is implemented to create a lesson, but would it be helpful to also create a challenge?
I'm referring to the way codeacademy does it. A short description, a starting code and a result that the user should reach.
For example, in an html challenge, the page should contain two `<p>` tags.

If yes, where should this check be: 

- in the end result, the iframe (is this possible?)
- by checking the structure of the code (from the editor) at submit time

I am willing to work on this if I get some guidance.
Thanks.

**Comment by flukeout** [comment]
Hello @onel - that is an interesting idea. One way to accomplish this is to build the "test" right into the Thimble project itself, like I've done here...

https://thimbleprojects.org/flukeout/53164/

Remix this project and add two paragraphs to the document to see how it might work. I think this would be a simple, fast way to accomplish what you want. Let me know your thoughts - I can help you with some coding or feedback.

**Comment by onel** [comment]
Thanks for the quick response, that's a pretty clever hack. And it's very flexible.

I was thinking more of a Brackets extension that we can load optionally in Bramble.
I saw that the `load` method receives an `options` object, where we might send a `validation` method. 
Outside the editor we can have a **Submit** button, and when pressed, we can call a method on the Bramble instance (similar to `enableWordWrap` or `disableWordWrap`) which will call the extension which in turn will call the validation method.
Would that work?

I just think an extension would work best in this case, because we don't have to change the code of the editor too much and it's optional.
I have not experience with writing Brackets extensions, but I can start reading if the above sounds as a good idea. What do you think?
