### ISSUE TITLE
Projects mixing up

### ISSUE THREAD

**Issue by jgmac1106** [mozilla/thimble.mozilla.org#1465]
Take a look at this: https://thimbleprojects.org/jgmac1106/53210

What they heck did I do wrong? I published the project and the the published page looked like a different project, then I unpublished and republished and I am getting an amalgamation of two different projects, but it doesn't show in the source code.

**Comment by jgmac1106** [comment]
I also have this one: https://thimble.mozilla.org/en-US/user/jgmac1106/156810, same thing, same project. Different remix

**Comment by gideonthomas** [comment]
@jgmac1106 can you screenshot what is expected to be shown (maybe screenshot the preview window in your project) and screenshot the published version?

**Comment by jgmac1106** [comment]
![projectoverlap](https://cloud.githubusercontent.com/assets/10534566/14439099/70836d6a-fff7-11e5-9a89-e62e9b03398e.gif)

It is very strange as it is remixing another project I have published.

**Comment by gideonthomas** [comment]
hmm yeah this is very bizzare! I'll investigate

**Comment by jgmac1106** [comment]
As some context, a student was using my computer under his screen name or
under anonymous. I took the computer, did not close browser, signed in and
saw the weird mixed up content.

The markup is still all there. I have not yet tried to download and upload
to a new project to see if it happens.

**Comment by gideonthomas** [comment]
I tried investigating this earlier and couldn't track down what went wrong. But I haven't seen this reported again. If this happens again, feel free to reopen the issue and I'll try to recover the project for you (we have a better tool for this now) and investigate further.
