### ISSUE TITLE
Saving Failed

### ISSUE THREAD

**Issue by arvin1209** [mozilla/thimble.mozilla.org#1467]
![image](https://cloud.githubusercontent.com/assets/13255798/14480411/c24239e2-00f6-11e6-8a2d-ec06a7f8058d.png)

**Comment by gideonthomas** [comment]
Tracking the issue here: https://github.com/mozilla/thimble.mozilla.org/issues/1311

**Comment by gideonthomas** [comment]
We're working on a fix.
