### ISSUE TITLE
3 Things I <3

### ISSUE THREAD

**Issue by RStaceyMAT** [mozilla/thimble.mozilla.org#1468]
The links (Games, Music, Places) no longer work in the default pre-remix project. 
Error message below: 
404 Not Found

Code: NoSuchKey
Message: The specified key does not exist.
Key: bramble/production/dist/games.html
RequestId: 82B092190ED142F7
HostId: g0aRLNA6lJGWHm2qSJNxTV3BhPwOVPJINs9UVmO4+uZHodawnfeJHClo9wD5JMd15V/rim1aZSk=
An Error Occurred While Attempting to Retrieve a Custom Error Document

Code: NoSuchKey
Message: The specified key does not exist.
Key: error.html

**Comment by flukeout** [comment]
I'm seeing this as well - links in the preview don't work and produce the error above. When published, projects work though. 

cc @gideonthomas @humphd

**Comment by Pomax** [comment]
are their more detailed Steps To Reproduce, here? I just ran a quick test with index.html code:
```
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Made with Thimble</title>
  <link rel="stylesheet" href="style.css">
</head>
<body>

  <h1>Welcome to Thimble</h1>

  <p>Make something <strong>amazing</strong> with the web!</p>
  
  <a href="http://github.com">github</a>

</body>
</html>
```
and that link resolved fine when clicking it in the preview

**Comment by flukeout** [comment]
Try linking to another page within the same project, that's when it seem to break.

**Comment by flukeout** [comment]
**Steps to Reproduce**
* Create a brand new project
* Add another page to the project called test.html
* On the index.html page, create a link to the test.html page
  * ``<a href="text.html">Text</a>``
* Click the link in the preview
* The browser displays an error page (with text shown in the first comment)

**Comment by Pomax** [comment]
ah! yes, confirmed on my end too, it looks like the preview is trying to resolve off of the thimblelivepreview.net domain, which doesn't have knowledge of the full filesystem. @humphd any idea how we might be able to deal with that?

**Comment by humphd** [comment]
Confirmed, this is a regression in Bramble.  It was caused by this change @gideonthomas made: https://github.com/mozilla/brackets/commit/cf24dc8199b3fa0673dac87f578664694dae0305#diff-38673d24a652996ec87c67df33495e8bL7.  @gideonthomas if we use `anchor.href` vs. `getAttribute('href')`, it will give us a complete URL (i.e., `http://...`) vs. just the portion we want, which is the path name that the user entered.

Can we simply revert this one line, or is it critical to what you are doing for tutorial links?
