### ISSUE TITLE
List of owned projects should include remix button for each item

### ISSUE THREAD

**Issue by soapdog** [mozilla/thimble.mozilla.org#1472]
Hey Friends,

I do lots of remix of my own stuff. To remix my own projects I need to go to the list of projects I own, select one, wait for it to open, check the published url, open it and then click remix. It would be great if from the list of projects we could simply click remix.

**Comment by jgmac1106** [comment]
Hey @soapdog I feel your pain. I have even messed up my template projects in the past by forgetting to remix.

I know we have discussed this feature a bunch of issues and it is in the roadmap https://github.com/mozilla/thimble.mozilla.org/wiki/Roadmap (I think that is the current version).

Given that we never did get the old projects migrated I am guessing we are somewhere in 2.3 (not sure we still need to). The localization work, as you know, has been amazing.

Also seems like a design and engineering effort has been going into the the Calypso CMS project, the IA audit, and the web literacy 2.0 launch. 

Hopefully Thimble 2.4 comes right after. Based on the value prop the update to Thimble is dependent on curriculum and IA work going on.

**Comment by hannahkane** [comment]
Thanks for reporting @soapdog. I think this request is covered in #1289 where there's an extensive list of potential changes to the My Projects page, so I'm going to close this ticket as a dupe.

@jgmac1106 - thanks for the reminder that the roadmap probably needs some updating. I'll add that to my ToDo list. You are right to notice that we have directed a lot of resources to other projects right now, some of which are dependencies for the Thimble roadmap and some of which are just more aligned with our strategic plan.

I'll make updates to the roadmap shortly.
