### ISSUE TITLE
Disable Fullscreen Button is not working

### ISSUE THREAD

**Issue by GitJTO** [mozilla/thimble.mozilla.org#1474]
Hi, I'm not sure if this is my browser issue but I cannot return to the code after I have enabled the full screen.
![thimble workspace one](https://cloud.githubusercontent.com/assets/18408294/14826433/c9bb82cc-0bab-11e6-809b-76069955a2cc.png)
![thimble workspace two](https://cloud.githubusercontent.com/assets/18408294/14826438/cd88f1e6-0bab-11e6-9b4e-bf75b98081a1.png)

**Comment by humphd** [comment]
I wonder if this is increased font size, and us not expanding to allow it to show properly.  cc @flukeout

**Comment by humphd** [comment]
Actually, this looks like the default now, and it means we've regressed something.  Thanks for filing it.

@flukeout I also notice that the right-hand buttons on the toolbar (fullscreen for example) aren't right aligned at the start either, and you have to resize the editor to force it.  Maybe a few issues to clean up in the CSS.
