### ISSUE TITLE
Link anchors not works in preview

### ISSUE THREAD

**Issue by iBobik** [mozilla/thimble.mozilla.org#1478]
Demo project: https://thimbleprojects.org/bobik/61038

```html
<a href="#chapter1">Chapter 1</a>
<h2 id="chapter1">Chapter 1</h2>
```

After click to link with #chapter1 it should jump to place where is id="chapter1".
It works on published website, but not preview windows next to editor.

**Comment by humphd** [comment]
@gideonthomas I thought you fixed this.  Did it not get pushed to prod?

**Comment by gideonthomas** [comment]
hmm it should be on prod. Will investigate...
