### ISSUE TITLE
Space missing between button icon & label

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.mozilla.org#1480]
Not sure where it went to. Might be due to changes made when setting localization and a space might have gotten removed. Should control the spacing via a margin and not a space anyway...

![image](https://cloud.githubusercontent.com/assets/25212/15021637/ceac2110-11dc-11e6-99a0-e7f79547313e.png)

**Comment by Joe-Para** [comment]
Just noticed that the space between text and icon is only missing when anonymous(which i fixed in above commit), but when logged in the space exists but because of some spaces in the text. (see: http://puu.sh/s3F20/01b88f2b81.png)

Its not in localization .properties files...

**Comment by gideonthomas** [comment]
This has been merged in with ef12c7b680292e542acad8d5584cabc4e8ff97cf, thanks @Joe-Para
