### ISSUE TITLE
When opening result in full-screen, there is no button to exit the full page result

### ISSUE THREAD

**Issue by kostgames** [mozilla/thimble.mozilla.org#1482]
![thimble](https://cloud.githubusercontent.com/assets/14951831/15112004/d67522b4-15f3-11e6-9303-44933c531b51.png)
When I press the full-screen button in the editor, the full page result comes up but there is no button to exit full-screen. However, i can fix this temporarly with Inspect element and changing the width of .preview-pane-nav and setting it to 150 px.

**Comment by humphd** [comment]
This has been fixed, but apparently not shipped to production. Gideon?

**Comment by kostgames** [comment]
Sorry... what?

**Comment by humphd** [comment]
@kostgames I fixed this last week, and I'm waiting for @gideonthomas to actually ship the code to the servers.

**Comment by kostgames** [comment]
Oh, i thought you asked if I were Gideon and I got a bit confused :)

**Comment by gideonthomas** [comment]
haha, I'll do it today

**Comment by gideonthomas** [comment]
This should be working now @kostgames

**Comment by humphd** [comment]
Confirmed, it's good now.  Sorry about that @kostgames.
