### ISSUE TITLE
Please don't change URL for re-published content

### ISSUE THREAD

**Issue by emmairwin** [mozilla/thimble.mozilla.org#1488]
Created a resource, which was linked from several places:

https://thimbleprojects.org/sunnydeveloper/69609/

Needed to make some small tweaks, and unpublished/republished and the URL changed breaking all links.

https://thimbleprojects.org/sunnydeveloper/70912/

Would appreciate if URL remained the same between publish & unpublished states to avoid this in future.

**Comment by gideonthomas** [comment]
@emmairwin thanks for filing! We have gone back and forth on the complexity of implementing this vs. the need for this. Quick question, was there a reason you had to unpublish the project before re-publishing? Was it part of a specific workflow?

**Comment by gideonthomas** [comment]
I'm going to close this since we're tracking it in #1305. Feel free to add thoughts there.
