### ISSUE TITLE
Mozilla TogetherJS Support

### ISSUE THREAD

**Issue by Coder206** [mozilla/thimble.mozilla.org#1491]
I think there is some potential to add Mozilla TogetherJS to Timble to enable collaboration. Any reasons it is not being done now? It feels a little lonely without a friend...

**Comment by humphd** [comment]
This is being discussed in #485.  I'm going to close this one, and invite you to join the conversation there.

**Comment by Coder206** [comment]
@humphd Sorry, a search did not reflect this was a prevalent topic.
