### ISSUE TITLE
Complete folder structure cant be seen while moving files between folders.

### ISSUE THREAD

**Issue by Sekharz** [mozilla/thimble.mozilla.org#1492]
![thimble_issue](https://cloud.githubusercontent.com/assets/13449235/15704139/db3ed07c-2806-11e6-83dc-d4b09719c9b8.jpg)

After adding folders to the font-awesome folder and then trying to move some files into the folders under font-awesome is not possible since the folders can't be seen in the move dialog box. Nor there is a option to scroll down.

Only on zooming out using ctrl+- a single sub folder can be seen.

**Comment by humphd** [comment]
Sounds like we're missing proper overflow settings on that div.

**Comment by humphd** [comment]
@gideonthomas we should prod push when you have a chance to get this fix landed.
