### ISSUE TITLE
Moving file from a folder

### ISSUE THREAD

**Issue by preetidulloo** [mozilla/thimble.mozilla.org#1497]
The dialog box showing the name of the folders does not hold any scrollbars. So in case the user needs to move a file to a folder which is not visible on the screen, it is not possible. Please fix this asap as I am stuck with my students project work update because of this.

Thanks in advance,
Preeti

**Comment by Pomax** [comment]
Do you have a link to a project that we can load up to see this happen? This will let us figure out exactly how we can best implement a solution to this problem.

**Comment by preetidulloo** [comment]
Thank you for reverting back! Yesterday when I was working on my project, I can't see the scroll on the "Move To..." dialog box, but today it's there (and for the same project).

Not sure what could be the reason!

Thanks!
