### ISSUE TITLE
Thimble not working in FireFox 47 but does in Chrome 50 on Windows 10

### ISSUE THREAD

**Issue by Coder206** [mozilla/thimble.mozilla.org#1500]
Error message:

There was an error loading your Project.
Please refresh your browser.

NOTE: if you are using Private Browsing mode, please reload in normal mode.

**Comment by Coder206** [comment]
I also tried FireFox nightly, no success. However FireFox Developer Edition (most recent of the time of writing) works well!

**Comment by cadecairos** [comment]
I just tried running thimble in Firefox Nightly and stable (on Linux) and projects load well.

Are you continuing to experience the issue with those versions of Firefox? If so, would you be able to check the developer console (f12) for any errors, and paste them here?

**Comment by Coder206** [comment]
@cadecairos I am using Windows 10. Yes, I am. Here is a picture:
![capture](https://cloud.githubusercontent.com/assets/7758155/16543315/0062dfbc-409c-11e6-823b-17507f44382d.PNG)

**Comment by Coder206** [comment]
@cadecairos I tried on a Fedora 24 system, works fine! It's a Windows 10 issue.

**Comment by cadecairos** [comment]
And you're not using private browsing?

I'm not really familiar with the inner workings of bramble (the code editor thimble uses) but it looks like the storage mechanizm it depends on for working locally got corrupted somehow.

@gideonthomas is likely far more capable of identifying the problem here

**Comment by Coder206** [comment]
@cadecairos I am not actually. Wondering if one of my plugins is interfering.

**Comment by cadecairos** [comment]
That's possible. could you try using a fresh Firefox Profile?

**Comment by cadecairos** [comment]
try visiting `about:profiles` in firefox

**Comment by Coder206** [comment]
@cadecairos I tried Safe Mode for FireFox, no success...

**Comment by Coder206** [comment]
@cadecairos I visited `about:profiles` no sure what to do next...

**Comment by Coder206** [comment]
@cadecairos A refresh solved the issue :)

**Comment by Coder206** [comment]
@cadecairos Now enjoying my favorite code editor in my favorite browser (with the exception of Mozilla Servo ;) ) Thanks for your help!

**Comment by cadecairos** [comment]
🎉 It must have cleared out the issue in your indexedDB - glad to hear it's working again.

I'd love to know more about how it got in that state though :)

**Comment by cadecairos** [comment]
> @cadecairos A refresh solved the issue :)

@gideonthomas we should save this handy piece of debugging knowledge somewhere if other people have the same issue

**Comment by Coder206** [comment]
@cadecairos It's odd. I can provide a list of extensions (as I remember a few). I would be willing to reproduce the issue. Did you want me to keep this issue open?

**Comment by cadecairos** [comment]
We can leave it open if you think you'd like to try and reproduce the error. It might not even be platform specific, so knowing which addons were in use might help (only if you're willing to share, though!)

**Comment by gideonthomas** [comment]
We've had issues with IndexedDB getting corrupted on Firefox but we thought that we handled that by auto-formatting it when the error is encountered so not sure why that didn't happen here.

cc @humphd

**Comment by Coder206** [comment]
I received the same error as above using the same refreshed browser, this time without extensions/add-ons (plain simple browser)

**Comment by gideonthomas** [comment]
@humphd any idea why we decided not to pass in `autoRecoverFileSystem: true` here - https://github.com/mozilla/thimble.mozilla.org/blob/master/public/editor/scripts/editor/js/bramble-editor.js#L15-L18 ?
It looks like it's not attempting to format the fs because we're not passing that flag in.

**Comment by humphd** [comment]
@gideonthomas we stopped doing that because it wasn't fixing the corruption in Firefox, which is what we'd hoped when we added that option.  We found that there was nothing we could do on our side to fix the corruption, it had to be dealt with at the browser/profile level.

**Comment by gideonthomas** [comment]
Oh I see, noted! Thanks!

Two things to figure out:
* What can a user do to fix this problem (changes that need to be made in FF settings, etc.)
* What is a good UX solution to indicate this

**Comment by humphd** [comment]
@gideonthomas the real solution here is "Mozilla needs to fix Firefox," but in lieu of that, see what we know in #1136

**Comment by gideonthomas** [comment]
lol ok! Thanks for linking the other bug, I knew we had one somewhere

**Comment by Pomax** [comment]
@humph Given that the real solution is "Mozilla needs to fix Firefox", is there a bug open on Firefox's issue tracker that we can link to? If not, one should probably be filed.

**Comment by Coder206** [comment]
Do you want me to close this?

**Comment by cadecairos** [comment]
Yeah, we've identified the cause, and it appears to be out of our hands for now.

**Comment by Coder206** [comment]
Ok.
