### ISSUE TITLE
Server Side Support

### ISSUE THREAD

**Issue by Coder206** [mozilla/thimble.mozilla.org#1501]
Allow users to make server side apps in NodeJS among other ways.

**Comment by Pomax** [comment]
While certainly a cool idea, that is well beyond the current scope of Thimble, and would require a radically different UI to allow for the notion of spinning up a server, executing  code, and most importantly, debugging it while it runs. In addition to the large amounts of work that would have to go into the client, this would also require safe execution infrastructure (the programs wouldn't be able to run on the same domain as Thimble itself, much like the current preview, to prevent XSS/session theft/etc) and would either require having languages that can themselves run inside a VM in the browser, which aren't there yet to the best of my knowedge, or running with elevated privileges on the user's machine, which would be terribly insecure, or running on dynamically assigned VMs on our infrastructure, which would get very expensive very fast.

Taking all of this into account, we will not be focussing on this kind of activity, certainly short to medium term, but unless something changes in how Node.js etc. can be run, probably long to permanent term, too.
