### ISSUE TITLE
Hey! I've made a project! Your Mozilla Thimble is great!

### ISSUE THREAD

**Issue by khanh2003** [mozilla/thimble.mozilla.org#1502]
https://thimbleprojects.org/khanhcrazy/84280

**Comment by khanh2003** [comment]
I've hacked Thimble to remove the remix button.
=====

**Comment by Pomax** [comment]
Neat!

**Comment by Pomax** [comment]
Filed #1503 for fixing the bug that can (either accidentally or intentionally) cause this to happen. Thank you for reporting it to us!

**Comment by khanh2003** [comment]
I'll watch #1503

Vào 06-07-2016 23:08, "Mike Kamermans" <notifications@github.com> đã viết:
