### ISSUE TITLE
Design a generic error page

### ISSUE THREAD

**Issue by gideonthomas** [mozilla/thimble.mozilla.org#1506]
Honestly, this as a temporary solution is fine so that we can stop the template errors that are crashing the server like:
```
» 8 Jul 2016 18:12:36.543 124 <190>1 2016-07-08T22:12:36.238948+00:00 host app web.1 - Template render error: (/app/views/error.html) [Line 4, Column 19] /
» 8 Jul 2016 18:12:36.562 285 <158>1 2016-07-08T22:12:36.247322+00:00 host heroku router - at=info method=GET path="/favicon.ico" host=id-webmaker-org-production.herokuapp.com request_id=0ad6ac10-a940-47f6-afa7-4d128f0269c5 fwd="1.132.96.104,54.240.152.71" dyno=web.1 connect=1ms service=86ms status=200 bytes=1159 /
» 8 Jul 2016 18:12:36.626 121 <190>1 2016-07-08T22:12:36.239027+00:00 host app web.1 - Error: Unable to call `gettext`, which is undefined or falsey /
» 8 Jul 2016 18:12:36.626 139 <190>1 2016-07-08T22:12:36.239035+00:00 host app web.1 - at Object.exports.prettifyError (/app/node_modules/nunjucks/src/lib.js:34:15)
```

This happens when we try to serve the Webmaker 500 error which for some reason is erroring out because of node-webmaker-i18n. In reality, we shouldn't show the Webmaker page and show a custom "Something went wrong" page (I don't know the UI for this but it should probably include instructions to contact us).

I'm making this a P1 (feel free to change that) since I'm seeing a whole lot of these failures in the logs.

cc @hannahkane and @flukeout

**Comment by flukeout** [comment]
We currently have a 404-type page for missing projects...

![image](https://cloud.githubusercontent.com/assets/25212/16742506/c332f1e6-475c-11e6-8d5a-55f5a806b736.png)

We could use it as a base for making an error page. I can work on a design.

We also need a straight up 404 page on the thimble.mozilla.org domain, currently we server this...

![image](https://cloud.githubusercontent.com/assets/25212/16742546/f086ae12-475c-11e6-9384-2cc8408d9789.png)

**Comment by flukeout** [comment]
Looks like we already have an issue for a better 404 page here - #1130

**Comment by Pomax** [comment]
![deadlink](https://cloud.githubusercontent.com/assets/177243/16742975/03bd976e-475f-11e6-85ab-474e82d182ce.png)

**Comment by flukeout** [comment]
Here's my take on the error page...

![image](https://cloud.githubusercontent.com/assets/25212/16777073/03be23f0-481d-11e6-86bf-bf98a81c6460.png)

cc @gideonthomas 

Questions
* Will we have access to some kind of description of the error that occurred?
  * If so, what is the length and format of that error?

**Comment by gideonthomas** [comment]
Looks good to me! We will have access to the description of the error, but I don't think it's very useful at the moment. I can add that functionality to Thimble though when we add this error page. The error itself can be formatted. Here's what an error might usually contain:
* a status code - not user-friendly but useful for us (when filing a bug for e.g.)
* a readable message - Human-readable and something like the one you have in your design
* details - Usually an object with a stack maybe, or something that the db sends us (not human-readable at all but definitely useful for us)

Feel free to decide what needs to be here on this page, etc.

**Comment by flukeout** [comment]
Thanks @gideonthomas - Could you provide a sample message that contains those three pieces of info? Would like to get a sense of the length of each string / block.

**Comment by gideonthomas** [comment]
Hmm sure, I'll have to construct it, but what it probably will look like is something like this:
* status code - 500
* message - The project failed to save recent changes made to the files
* details - 
```js
{
  error: 'published_id is invalid', // or an object
  project_id: 13542,
  route: 'PUT /projects/132',
  stack: '......'
}
```
Not sure what from here you would like to show to the user

**Comment by flukeout** [comment]
Submitted a PR for the new error page here...
https://github.com/mozilla/thimble.mozilla.org/pull/1512

**Comment by gideonthomas** [comment]
This is done, the rest of the general error issue will be resolved in https://github.com/mozilla/thimble.mozilla.org/issues/1511

**Comment by flukeout** [comment]
👍
