### ISSUE TITLE
Investigate "Internal Server Error" on authentication

### ISSUE THREAD

**Issue by gideonthomas** [mozilla/thimble.mozilla.org#1507]
There are a lot of HTTP 500's  on the `/callback?logout=true` route and also a few on `/callback?client_id=...`(login) route.

Both seem to be occurring on a redirect from something like `/callback?logout=true` to `/en-US/callback?logout=true` so it's possible that l10n is screwing it up somehow. (This is true for logging in as well)

**Comment by humphd** [comment]
No updates for over a year, closing.
