### ISSUE TITLE
Issue with signing up

### ISSUE THREAD

**Issue by uday1201** [mozilla/thimble.mozilla.org#1509]
When I'm trying to sign up with my e-mail for the first time, it's saying there's already an account with this email. And when I'm trying to recover password by going into the **Forget Password** in Log In , it says there's no account associatedwith it.
![screenshot from 2016-07-11 12 24 27](https://cloud.githubusercontent.com/assets/13145905/16722187/980971c4-4762-11e6-96ef-44f558e27b17.png)
![screenshot from 2016-07-11 12 24 44](https://cloud.githubusercontent.com/assets/13145905/16722188/98813010-4762-11e6-8f1d-1197ea6c788f.png)

**Comment by cadecairos** [comment]
It looks like you've already created a webmaker account before. The username is "udapra".

The account will need to be migrated from our retired one-time password system into the new one. It will prompt you to do this when you enter in the username I've mentioned above, and you'll receive an email containing a link that will let you set up a password for your account.

**Comment by cadecairos** [comment]
@uday1201 Were you able to log in?
