### ISSUE TITLE
Blank language in language-picker

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.mozilla.org#1510]
In the screenshot below, one of the language options doesn't have any text in it.

![image](https://cloud.githubusercontent.com/assets/25212/16750133/42e2d880-4784-11e6-90c0-1c529a1911ca.png)

This is the markup, it's for the looks like the ``/az`` locale code.

![image](https://cloud.githubusercontent.com/assets/25212/16750148/6e56e7fe-4784-11e6-81cc-d890dbeffcf2.png)

**Comment by flukeout** [comment]
cc @alicoding

**Comment by alicoding** [comment]
This is actually missing from language mapping list library. I will have to add this and it should fix once you reinstall the module.

**Comment by alicoding** [comment]
This should now be fixed once you rebuild the app.
