### ISSUE TITLE
Analyzing how people learn web development on Thimble

### ISSUE THREAD

**Issue by liberaliscomputing** [mozilla/thimble.mozilla.org#1516]
Hello all,

As a contractor, I have been working on a research study temporarily titled **Scaling learning web development in the wild**. Since I am interested in computer science education especially within a context of **web literacy**, I have been investigating 1) **how people learn web development on Thimble** and 2) **how we could facilitate that understanding further**.

Whereas the latter objective will bring some practical implications for **developing and deploying additional features on Thimble** and then **expediting Mozilla’s web literacy mission** out of this present study, the first one consists of following sub-goals:
1. Building up ground truth of computational thinking in web development
   For other programming languages, there have been well-defined computational concepts and hierarchies between them. Given actual code, therefore, it is relatively easy to observe and measure how learning happens with those languages. In contrast, there has been **little research on computational thinking in web development**. Therefore, this present study aims to build up a **ground truth of computational thinking in web development** out of actual code where the ground truth will be highly user-driven. Given that learning involves the making of socially valuable objects, this approach will be highly impacting in understanding people’s learning behavior of web development.
2. Modeling mental models of users and learning trajectories
   Based on the ground truth that computational thinking in web development will call upon, I aim to measure **the sophistication of computational objects** and **the level of a learner’s mastery** at a specific moment of time. In so doing, I expect that we can also keep track of the individual’s **learning trajectories** and group users into some clusters that **share some homogeneous coding/learning characteristics**.
3. Understanding the effectiveness of remixing on Thimble
   Since users can initiate their projects from remixing, I aim to explore **how much the use of remixing projects influence learning web development**, compared to those who do not scratch from remixing. 

If you have any suggestions or feedback on this project, you are more than welcome to visit my Github repo named [thimble-analytics](https://github.com/liberaliscomputing/thimble-analytics) and open issues. You can also visit my [working document](https://docs.google.com/document/d/18SR0NVLi71eiZu1_EaDgRHm9JOML7wlyRUlr2Kwymgw/edit?usp=sharing) to comment anything.

Thanks!

**Comment by gideonthomas** [comment]
Closing as this is now out of scope.
