### ISSUE TITLE
Update server's security headers

### ISSUE THREAD

**Issue by marumari** [mozilla/thimble.mozilla.org#1517]
Hey there!  April here from the Mozilla infosec team.  Just wanted to help you out a little bit, getting your server's headers inline with our security guidelines.  :)

> X-Frame-Options: ALLOW-FROM https://pontoon.mozilla.org

ALLOW-FROM is only supported by Firefox, and has been deprecated in place of this:

> Content-Security-Policy: frame-ancestors https://pontoon.mozilla.org

This works in Firefox, Chrome, and Safari and hopefully Edge someday.  To protect users of older browser from possible clickjackings, I would set it like this:

Content-Security-Policy: frame-ancestors https://pontoon.mozilla.org
X-Frame-Options: DENY

> Strict-Transport-Security: max-age=86400

Please set this to a year:

> Strict-Transport-Security: max-age=31536000

I see you're well on your way to getting CSP implemented, with Content-Security-Policy-Report-Only, which is absolutely fantastic.  Thanks so much!

**Comment by marumari** [comment]
Note that you can set:

> Content-Security-Policy: frame-ancestors https://pontoon.mozilla.org

At the same time as you use Content-Security-Policy-Report-Only; they operate independently.  :)

**Comment by gideonthomas** [comment]
Awesome, thanks a lot @marumari!

Changes that need to be made:
* https://github.com/mozilla/thimble.mozilla.org/blob/master/server/security.js#L105 for the `X-Frame-Options` header
* https://github.com/mozilla/thimble.mozilla.org/blob/master/server/security.js#L69 to add `frame-ancestors` as a separate CSP header (`Content-Security-Policy`)
* https://github.com/mozilla/thimble.mozilla.org/blob/master/server/security.js#L87 for the `Strict-Transport-Security` header

cc @cadecairos

**Comment by cadecairos** [comment]
@gideonthomas is there a reason we're only using the report-only csp header?

**Comment by marumari** [comment]
Glad to help!  Please let me know if there's anything else I can do!  From what I can tell, the CSPRO header isn't returning any obvious CSP errors in the handful of pages I visited, which means you're all probably really close!  Nice work, and let me know if you have any questions at all!

**Comment by gideonthomas** [comment]
@cadecairos nope no reason at all. I think it was done earlier during the dev process, when we didn't have time to fix CSP errors.

**Comment by marumari** [comment]
Just checking in on this just to see how things are going with CSP and the like.  Carry on being awesome!  :)
