### ISSUE TITLE
better tutorials

### ISSUE THREAD

**Issue by khanh2003** [mozilla/thimble.mozilla.org#1523]
I saw your starter projects. They are nice. But when I show them to my friends, no one wanted to read the tutorials. They just kept asking me how to remix.

And now I tried to make a sample tutorial.
Let's discuss about it.
https://thimbleprojects.org/khanhcrazy/89200/

**Comment by flukeout** [comment]
Hi @khanh2003 - I saw you closed the issue but if you're still interested in sharing your thoughts, we'd appreciate it.

Some questions...

* Were your friends unable to remix a project when they tried?
  * Were you able to show them how to remix?
  * Was something about remixing the project difficult or unexpected?
* You said you tried to make a tutorial, were you successful or not? What issues did you run into?

Thanks, looking forward to your feedback.
