### ISSUE TITLE
Remove mozillathimblelivepreview script preloading in homepage

### ISSUE THREAD

**Issue by Pomax** [mozilla/thimble.mozilla.org#1524]
Despite the fact that neither of those things should hold up the app loading and starting up a UI.

**Comment by gideonthomas** [comment]
I'm not sure I understand. If you block mozilla.org, all subdomains are also blocked aren't they? So the app definitely won't load.

cc @cadecairos

**Comment by cadecairos** [comment]
Can you elaborate on this @Pomax? I'm not sure why the expectation is that it should load if the domains it depends on are blocked.

**Comment by khanh2003** [comment]
close this please

**Comment by Pomax** [comment]
it might be blocking the scripts from thimble.mozilla.org with base mozilla.org blocked, although mozillathimblelivepreview should not be required to load the bundle. Right now with mtlp blocked, the bundle load breaks with a black screen and warning text.

**Comment by gideonthomas** [comment]
@Pomax which browser and what JS blocking settings are being used here?

**Comment by Pomax** [comment]
firefox, with noscript set to block mozillalivepreview

**Comment by gideonthomas** [comment]
So you explicitly block mozillathimblelivepreview.net? I don't think that's something that users usually do though so I wouldn't prioritize this. However, I agree that we should make the UX for this case a bit smoother.

**Comment by Pomax** [comment]
consider that noscript blocks things by default, so people come to thimble with mozilla.org and preview blocked. Then they'll clear mozilla.org to see what we have to offer, the site loads, but then the bundle breaks despite there not being a good reason for that. Ideally, they would get the IDE and then go "oh I should clear the preview too, there is value in this"

**Comment by gideonthomas** [comment]
Oh I see so this extension blocks all thirdparty domains without having you to explicitly type it out? In that case, yeah it's probably worth investing some time soon in proper UX for this.

**Comment by Pomax** [comment]
the default noscipt behaviour is "block EVERYTHING until the user unblocks it", not just "third party domains", it even blocks primary until the user visits that domain, and tells noscript to either temporarily or permanently allow scrips from this domain to run.

**Comment by humphd** [comment]
The fix to this is two-fold:

* Switch over to Service Workers, which is #1459
* Undo this patch, so we don't load these files cross-origin: https://github.com/mozilla/thimble.mozilla.org/commit/c8fec1ed5627d507d16480e341e8c54f45d03b22

Let's make this bug be about the second part.  When we first shipped Brackets I was really worried about the download size.  Today, I'm less worried, and I don't think this preload bit is needed anymore.

**Comment by evantsyferov** [comment]
I would like to work on this issue.

**Comment by humphd** [comment]
I've fixed this, closing.
