### ISSUE TITLE
figure out if we can make the file nav bar light, when light theme is used

### ISSUE THREAD

**Issue by Pomax** [mozilla/thimble.mozilla.org#1525]
When using thimble on a laptop in some sun, the low contrast offered by the dark theme is too low, and light theme works a lot better. However, switching does not switch the navbar, so we might need to look at how bracket themes are applied, create a theme in line with our light theme, and tell brackets to switch when the Thimble theme gets switched, too.

**Comment by Pomax** [comment]
#sidebar background `#e0e0e0` looks fairly decent (darker than white to make it clear it's not "more editor")

<img width="1714" alt="screen shot 2016-07-28 at 9 51 54 am" src="https://cloud.githubusercontent.com/assets/177243/17221684/a3ab3fea-54a9-11e6-97d6-28ef3baf9cab.png">

**Comment by gideonthomas** [comment]
The upper dark nav bar looks a bit out of place though so maybe we should change the color of that as well. cc @flukeout

**Comment by flukeout** [comment]
Yeah it looks a bit weird, but I think @Pomax's idea still has merit in the short term. The dark bar contains a bunch icons and buttons, so we'll have to generate inverse versions of those, which will increase the scope of work.

We can schedule and prioritize

**Comment by cgsingh** [comment]
I'd like to make an attempt at tweaking this for credit for my school assignment: "when you switch to the light theme, the file navigation bar on the left takes the same similar white color scheme."

**Comment by flukeout** [comment]
@cgsingh - it actually looks like this is a duplicate of #1100 - any chance you could collaborate on that one with the other contributor? I'm going to close this issue, sorry about that.
