### ISSUE TITLE
https://thimbleprojects.org root should redirect to https://thimble.mozilla.org

### ISSUE THREAD

**Issue by Pomax** [mozilla/thimble.mozilla.org#1527]
Currently visiting https://thimbleprojects.org/ gives you the 404 page, and the "thimble by mozilla" links to thimbleprojects.org instead of thimble's real website.

It's probably far more useful to make the root on https://thimbleprojects.org outright redirect to https://thimble.mozilla.org, since that's what you were probably looking for instead anyway.

**Comment by gideonthomas** [comment]
@cadecairos, this might be a good bug for @patjouk to work on. Not labelling as a "Good First Bug" since this is beyond the scope for volunteers.

**Comment by patjouk** [comment]
We build this redirect rule with @cadecairos for staging this morning:

```
<RoutingRules>
  <RoutingRule>
    
    <Condition>
      <KeyPrefixEquals>index.html</KeyPrefixEquals>
    </Condition>
    
    <Redirect>
      <Protocol>https</Protocol>
        <HostName>bramble.mofostaging.net</HostName>
      <ReplaceKeyWith/>
      <HttpRedirectCode>307</HttpRedirectCode>
    </Redirect>

  </RoutingRule>
</RoutingRules>
```

We could use this one for production:

```
<RoutingRules>
  <RoutingRule>
    
    <Condition>
      <KeyPrefixEquals>index.html</KeyPrefixEquals>
    </Condition>
    
    <Redirect>
      <Protocol>https</Protocol>
        <HostName>thimble.mozilla.org</HostName>
      <ReplaceKeyWith/>
      <HttpRedirectCode>307</HttpRedirectCode>
    </Redirect>

  </RoutingRule>
</RoutingRules>
```

**Comment by cadecairos** [comment]
💯 

Looks great, let's add the production RoutingRules blob to the S3 bucket.

**Comment by patjouk** [comment]
Deployed in production and it's working :)

**Comment by gideonthomas** [comment]
Awesome! Thanks @patjouk :)
