### ISSUE TITLE
Quick edit is ⌘-e, not ⌥-e

### ISSUE THREAD

**Issue by samueller** [mozilla/thimble.mozilla.org#1528]
When you right-click an HTML tag, Thimble's context menu shows "Quick Edit ⌥E". But it's actually ⌘-e that brings up the quick edit. At least that's how it is on my MacBook.

**Comment by humphd** [comment]
See https://github.com/adobe/brackets/blob/f028b3ecdf2017498196f39ddbbe4a2364366c92/src/base-config/keyboard.json

**Comment by Shank09** [comment]
I'm interested on working on this bug

**Comment by humphd** [comment]
OK @Shank09, it's yours.

**Comment by gideonthomas** [comment]
Fixed with: 79162c10e3e68ebf0f561eba0c510aae1b19559a
