### ISSUE TITLE
Allow es6 linting with JSLint

### ISSUE THREAD

**Issue by samueller** [mozilla/thimble.mozilla.org#1529]
I saw in the Bramble GitHub repository that we can add JSLint support:

> You could enable JSLint and LESSSupport by loading Bramble with ?enableExtensions=JSLint,LESSSupport on the URL

I did that with JSLint and it does load:

```
[Brackets] Loading additional extension `JSLint` main.js:15
```

So how can we use JSLint?

**Comment by gideonthomas** [comment]
@samueller If you enable the extension, and then open up a new JS file and type something in, a JSLint bar should pop up at the bottom showing any problems in the code.

**Comment by humphd** [comment]
I think this extension works when the file is saved. Look at its main.js to confirm.

On Aug 1, 2016 12:00 PM, Gideon Thomas <notifications@github.com> wrote:

@samueller<https://github.com/samueller> If you enable the extension, and then open up a new JS file and type something in, a JSLint bar should pop up at the bottom showing any problems in the code.

-

**Comment by samueller** [comment]
I see, it doesn't show up for an HTML file with JavaScript in it, only a `.js` file. Is there a way to give JSLint the `es6` option?

**Comment by humphd** [comment]
You could change what gets specified here: https://github.com/mozilla/brackets/blob/master/src/extensions/default/JSLint/main.js#L101.  Any valid `options` value would get passed down to jslint.

**Comment by humphd** [comment]
There is work happening on this in https://github.com/mozilla/brackets/pull/623

**Comment by Pomax** [comment]
do we want to keep this specific issue open, or should we close it as the work is happening elsewhere?

**Comment by humphd** [comment]
I'll close, since this is tracked in that other bug.
