### ISSUE TITLE
Collaborative live coding in Thimble

### ISSUE THREAD

**Issue by liberaliscomputing** [mozilla/thimble.mozilla.org#1531]
Alongside [learning analytics in Thimble](https://github.com/mozilla/thimble.mozilla.org/issues/1516), I have been investigating people's learning behavior in web development in an open source toolkit called [Snowball](http://snowball.openhtml.org/). From this study, I found anecdotal evidence showing the sophistication of computational artifacts is greater when people **co-author** web articles.

This finding got me thinking that we can further facilitate learning web development in Thimble if it has a feature that enables **real-time collaboration** on HTML, CSS, and JavaScript code. The anticipated results include:
- It will enhance **the quality of learning** via collaborative coding 
- it will also increase **the effectiveness of teaching** web development since course facilitators can make **instant feedback** to their students

I found one great example of this idea called [CodeCircle](http://live.codecircle.com/) powered by [ShareJS](https://github.com/share/ShareJS). Mozilla already has TogetherJS, a great JS library that enables to add real-time collaboration features, and I believe some simple tweaks would be enough for making this happen.

FYI, as one of my side projects, I am planning to translate TogetherJS to a Brackets plugin.

Any feedback would be appreciated, @simonwex @Pomax @flukeout !

**Comment by Pomax** [comment]
adding @humphd, too - getting togetherjs, or any other collaborative state syncing tool, integrated into thimble for real time collaboration would be exciting.

**Comment by flukeout** [comment]
Sweet - keep us posted on the TogetherJS implementation. Once you have a better handle on how that could work, I can help out with some UX ideas / considerations.

**Comment by khanh2003** [comment]
I want it now! I'll teach code to my friends if you add that.

**Comment by gideonthomas** [comment]
Discussions - https://public.etherpad-mozilla.org/p/thimble-collaborative-editing

**Comment by liberaliscomputing** [comment]
There would be several ways to evidence the effectiveness of collaborative live coding as follows:

- Investigate data from the previous version of Thimble (data when TogetherJS was plugged in)
- Conduct field testing in classroom settings
- Examine previous literature

Regarding the third option, I have found two interesting articles. There both comes from a research lab at MIT dedicated to HCI and computing education:

- [Collabode: collaborative coding in the browser](http://dspace.mit.edu/openaccess-disseminate/1721.1/79662) 
- [Real-time collaborative coding in a web IDE](https://groups.csail.mit.edu/uid/collabode/UIST11-Collabode.pdf)

The first paper is about the development of a synchronous online IDE of Java, and the second paper shows that as sessions go on, **the rate of errors significantly decreases whereas the number of commit increases**.

**Comment by gideonthomas** [comment]
Related: https://github.com/mozilla/thimble.mozilla.org/issues/485
