### ISSUE TITLE
Improve the design and contrast of Thimble's code window for presenations

### ISSUE THREAD

**Issue by chadsansing** [mozilla/thimble.mozilla.org#1533]
Users can't read the Thimble FILES menu or code window in well-lit rooms because the display themes are too low-contrast. We should develop a presentation theme or improve current themes for readability during presentations, thinking past traditional fonts and colors used by coders.

cc @anmechung @hannahkane

**Comment by gideonthomas** [comment]
cc @flukeout

**Comment by humphd** [comment]
Dupe of #1251.
