### ISSUE TITLE
sign in won't work if you have youtube blocked.

### ISSUE THREAD

**Issue by Pomax** [mozilla/thimble.mozilla.org#1537]
This cannot possibly ever have been intentional, but it's still really frustrating - the sign in links will not work if "third party scripts and includes" are blocked (a pretty sensible noscript and ublock origins setting), so thimble is forcing me into letting youtube know that I'm using thimble before I'm allowed to log in.

Can we fix that?

**Comment by Pomax** [comment]
hm, it would appear that even with youtube unblocked, the thimble UI refuses to properly add hrefs to the sign in links. They stay `href='#'` instead (a test in chrome works fine).

Any idea what might be causing this?

**Comment by Pomax** [comment]
localStorage content:
```
{
  "bramble-property::previewMode": "desktop",
  "bramble-property::theme": "dark-theme",
  "bramble-property::fullPath": "/365/projects/462126/index.html",
  "bramble-property::sidebarWidth": "200",
  "bramble-property::sidebarVisible": "true",
  "bramble-property::filename": "index.html",
  "bramble-property::wordWrap": "true",
  "bramble-property::secondPaneWidth": "806",
  "bramble-property::fontSize": "15px",
  "intercom": "[{\"id\":null,\"name\":\"change\",\"origin\":\"AE9476C3-F31D-4232-B6C1-CA26B5CF45DD\",\"timestamp\":1470719376596,\"payload\":\"/365/projects/462126/index.html\"},{\"id\":null,\"name\":\"change\",\"origin\":\"AE9476C3-F31D-4232-B6C1-CA26B5CF45DD\",\"timestamp\":1470719395715,\"payload\":\"/365/projects/462126/index.html\"},{\"id\":null,\"name\":\"change\",\"origin\":\"AE9476C3-F31D-4232-B6C1-CA26B5CF45DD\",\"timestamp\":1470719423684,\"payload\":\"/365/projects/462126\"},{\"id\":null,\"name\":\"change\",\"origin\":\"AE9476C3-F31D-4232-B6C1-CA26B5CF45DD\",\"timestamp\":1470719424500,\"payload\":\"/365/projects/462126\"},{\"id\":null,\"name\":\"change\",\"origin\":\"AE9476C3-F31D-4232-B6C1-CA26B5CF45DD\",\"timestamp\":1470719424504,\"payload\":\"/365/projects/462126\"},{\"id\":null,\"name\":\"change\",\"origin\":\"AE9476C3-F31D-4232-B6C1-CA26B5CF45DD\",\"timestamp\":1470719425586,\"payload\":\"/365/projects/462126\"}]",
  "bramble-property::firstPaneWidth": "913"
}"
```

**Comment by Pomax** [comment]
four `ga` cookies, two moz cookies, `mozillaThimble` and `mozillaThimble.sig`, and four optimizely cookies.

**Comment by gideonthomas** [comment]
@Pomax what errors are you seeing in the console when you try to login? (also, can you copy/paste the domains that are blocked by uBlock on the homepage?)

**Comment by Pomax** [comment]
no errors.

**Comment by Pomax** [comment]
The only "errors" are:
```
Content Security Policy: Directive 'frame-src' has been deprecated. Please use directive 'child-src' instead. (unknown)
Content Security Policy: This site (https://thimble.mozilla.org) has a Report-Only policy without a report URI. CSP will not block and cannot report violations of this policy. (unknown)
```
Neither of which should have anything to do with this.

**Comment by gideonthomas** [comment]
@Pomax if you click on the little square-like thingy near "on this page" when you click on uBlock, it will open the logger after which if you click on the refresh icon, will show you blocked domains. Might help knowing which domain is being blocked?

Do those errors appear after you try to click on "Sign In"? Or do you see nothing being logged after clicking "Sign In"?

**Comment by Pomax** [comment]
Like I said, even with nothing blocked thimble is misbehaving for me. There are no errors, the sign in link simply does not get an href assigned into it. It stays `href='#'` and clicking it does what that's supposed to do: navigate you to the top of the page (which it's already on)

**Comment by Pomax** [comment]
turns out noscript somehow decided to block thimble.mozilla.org, but not show this in its UI... that'll do it.
