### ISSUE TITLE
Profile size larger than 10/12Go

### ISSUE THREAD

**Issue by Libaud** [mozilla/thimble.mozilla.org#1540]
Hi,
I'm manage many mail account and my profile size was reached than 10/12Go.
So I've saw that Thunderbird couldn't delete messages in different account or search folders then the profile have this size.
The solution is to archive messages, export them and delete archives after.
To be down the 10Go and able delete messages.

**Comment by Pomax** [comment]
It sounds like you filed this on the wrong repository, this is the repostory for https://thimble.mozilla.org, and online code editor specifically for making web content.
