### ISSUE TITLE
Thimble e-mail address doesn't work

### ISSUE THREAD

**Issue by my2iu** [mozilla/thimble.mozilla.org#1541]
I have a student who can't login to Thimble due to oath errors, but when she has tried to e-mail Thimble for help, the e-mail address on the webpage doesn't work.

The e-mail address at the bottom of the page is

thimble@mozillafoundation.org 

but it just goes to a google group that doesn't allow postings from non-members and is rejected, so no one ever receives it.

**Comment by gideonthomas** [comment]
Hi @my2iu thanks for filing this issue! I believe that the email address provided is incorrect (@cadecairos or @hannahkane can you confirm this). We will update it ASAP.

As for the issues regarding login, let's discuss in the other issue you have filed.

**Comment by hannahkane** [comment]
cc @KevZawacki to confirm, but I believe thimble@mozillafoundation.org emails are automatically sent to our Desk.com account, where Kevin routes them appropriately.

If this doesn't feel like the right solution, we can change to teachtheweb@mozillafoundation.org, which is a well-watched address.

**Comment by KevZawacki** [comment]
@hannahkane Yep, that's correct

**Comment by gideonthomas** [comment]
@hannahkane I think I would recommend the teachtheweb email considering the above mentioned issue. What do you think?

**Comment by hannahkane** [comment]
WFM because I think issues are likely to get more attention through the teachtheweb@ address, though I'm confused about this issue. The closed listserv address is thimble@mozilla.org, and I'm not sure we advertise that anywhere on the site. If we do, we should clarify its purpose.

**Comment by gideonthomas** [comment]
We don't, the link at the bottom is to thimble@mozillafoundation.org

**Comment by flukeout** [comment]
Closing as thimble@mozillafoundation.org emails now reach us just fine.
