### ISSUE TITLE
2017 Research opportunities for Thimble

### ISSUE THREAD

**Issue by gideonthomas** [mozilla/thimble.mozilla.org#1549]
http://etherpad.io/thimble-research contains our brainstorming session with @LauraReynal and
@liberaliscomputing. Next steps are to discuss and create a plan for this sometime in the first week of December.

**Comment by hannahkane** [comment]
@gideonthomas - I think we can close this. What do you think?

**Comment by gideonthomas** [comment]
Unless it's helpful to @flukeout, we can close this

**Comment by flukeout** [comment]
Closing - will review etherpad.
