### ISSUE TITLE
Overwriting of existing JavaScript when creating new file

### ISSUE THREAD

**Issue by cfmonk** [mozilla/thimble.mozilla.org#1550]
Was running a training session in Singapore yesterday and all my attendees had to add a second JS file to their projects. This resulted in about 50% of the group losing their first (default name script-1.js) file which was overwritten with the default content.

Was quite scary but fortunately nobody republished so we could grab the code back from the console.

**Comment by humphd** [comment]
That's no good, I'm sorry to hear that.  Can you help us understand what the process looked like?  Did you press the green '+' button and choose `JavaScript`?  Did you already have a file named script-1.js in the project?

**Comment by cfmonk** [comment]
That was the process they followed and yes they had been working in
script-1.js and I wanted them to create a script-2.js but it didn't create
a new file and just overwrite the contents of script-1.js.

Repeated the process and it worked perfectly.

 Chris Monk

Head of Region, Asia-Pacific

+61 2 8091 6100 <+61%C2%A028091+6100>   |   +61 437 888 604 <+61437+888+604>
| +44 7921 369 527 <+447921369527>

chris@decoded.com   |   @cfmonk <http://twitter.com/cfmonk>

decoded.com <https://www.decoded.com/>   |   @decodedco
<https://www.twitter.com/decodedco>

**Comment by humphd** [comment]
Do you have a link to a project you used as the basis for their work?  I'd like to try and reproduce this locally and debug.

**Comment by cfmonk** [comment]
https://thimbleprojects.org/cfmonk/100440/

 Chris Monk

Head of Region, Asia-Pacific

+61 2 8091 6100 <+61%C2%A028091+6100>   |   +61 437 888 604 <+61437+888+604>
| +44 7921 369 527 <+447921369527>

chris@decoded.com   |   @cfmonk <http://twitter.com/cfmonk>

decoded.com <https://www.decoded.com/>   |   @decodedco
<https://www.twitter.com/decodedco>

**Comment by cristinejohnson** [comment]
I want to report that the same problem occurred with a student at my center, but when creating a new HTML file. The student had been working on an HTML web page for several weeks and when he clicked the plus symbol and created a new HTML file, the old one completely disappeared. He was devastated. I hope the problem can be fixed.

**Comment by cfmonk** [comment]
@cristinejohnson If the student has not yet republished then you can copy
the source code from the published version. Hope that might help!

 Chris Monk

Head of Region, Asia-Pacific

+61 2 8091 6100 <+61%C2%A028091+6100>   |   +61 437 888 604 <+61437+888+604>
| +44 7921 369 527 <+447921369527>

chris@decoded.com   |   @cfmonk <http://twitter.com/cfmonk>

decoded.com <https://www.decoded.com/>   |   @decodedco
<https://www.twitter.com/decodedco>

**Comment by gideonthomas** [comment]
data loss seems to be a common theme here, I am going to spend some time this cycle trying to figure out what's going on

**Comment by gideonthomas** [comment]
@cfmonk or @cristinejohnson i'm trying to gather some more info about how this happens. By any chance do you know if there were any file/folder deletions or renames that happened before the new file was added (and before the content disappeared)?

**Comment by cfmonk** [comment]
Struggling to remember...  Might have renamed some stuff.

**Comment by humphd** [comment]
I can reproduce this, we'll debug and fix.

**Comment by Pomax** [comment]
STR:
- new project
- create a file called script-1.js manually
- publish the project
- visit published project, click remix
- create a new script file through the `[+]` button and picking "javascript".

this overwrites `script-1.js` with a new file. This looks like a sequence problem, where we assume sequence number `1` as start regardless of whether that file's already taken. A possible solution might be to spin the sequence number until we don't see a filename collision.

**Comment by gideonthomas** [comment]
Migrating this issue to https://github.com/mozilla/thimble.mozilla.org/issues/1564
