### ISSUE TITLE
Thimble Project Publishes, but the URL leads to "page not available"

### ISSUE THREAD

**Issue by rednax825** [mozilla/thimble.mozilla.org#1551]
I tried to publish with thimble, it gave me a link, but the link leads to a page that says 
"Oh no!
The page you're looking for
is not available!"

**Comment by humphd** [comment]
One reason users see this is if they publish a project that doesn't have an `index.html` file.  Do you have another `.html` file in your project?  Try adding that to the end of the URL you were given when you published.

**Comment by rednax825** [comment]
Thanks, that was the issue.
