### ISSUE TITLE
Could we use esnext syntax like import modules?

### ISSUE THREAD

**Issue by enguerran** [mozilla/thimble.mozilla.org#1553]
I try two or three things in Mozilla Thilmble.

First adding external script files: work like a charm.

Then using extended JavaScript syntax like arrow function or import/export modules. With or without the JIT babel transpiler. Here is the result:  https://thimbleprojects.org/enguerran/102733 .

Whereas the arrow function works like a charm, the [import/export module](https://babeljs.io/docs/learn-es2015/#modules) don't as `require is not defined`. No surprises but I ask myself a question: What JavaScript interpreter is integrated in Mozilla Thimble? Is there any chance to load ES2015 code without any transpiler?

**Comment by Pomax** [comment]
None: we let the browser load the files that you wrote, with the caveat that the filesystem is blob based, so XHRs might not work, and I suspect the same will be true for `import` statements.

**Comment by gideonthomas** [comment]
We special case xhrs but only those used through `window.XMLHttpRequest`. My suspicion is that if we special-case the import/export statements in JS as well (rewriting them in the blob that is sent to the preview), they would work (although rewriting JS can be quite challenging)

**Comment by enguerran** [comment]
Oh I see, thanks for your answers. As we can use Thimble to build projects, it could be very useful to let people create folders and to link files in some way. But I understand it is not a easy feature nor an high-priority-one.

I know understand it is due to the blob based "filesystem", makes a lot of sense.

I guess we can close this issue as there is nothing to add.
