### ISSUE TITLE
Incremental backoff for saving isn't working correctly

### ISSUE THREAD

**Issue by cadecairos** [mozilla/thimble.mozilla.org#1554]
on [line 31](https://github.com/mozilla/thimble.mozilla.org/blob/e6d8ba2162767b0de8aa48e8bad5cacf497bec1c/server/routes/files/delete.js#L31) we reference `status` which is undefined.

This slipped in with #1521 

cc/ @gideonthomas

**Comment by evantsyferov** [comment]
I would like to work on this issue.

**Comment by gideonthomas** [comment]
@evantsyferov all yours. The fix should be to simply refer to the correct variable that has the statusCode stored.

**Comment by humphd** [comment]
Looks like there's confusion here, since @gideonthomas seems to have fixed it in https://github.com/mozilla/thimble.mozilla.org/commit/75c4aea375005166e66ccb03ef58e40b3f5a42f6.  I'm going to close this.
