### ISSUE TITLE
Does not load

### ISSUE THREAD

**Issue by rugk** [mozilla/thimble.mozilla.org#1556]
Tested loading https://thimble.mozilla.org/de/anonymous/ba97034e-05f7-4f9b-ad2b-c9e1348290cc in Firefox **in safe mode** (means no add-ons are used) and it failed:
![thimbleloadingerror](https://cloud.githubusercontent.com/assets/11966684/18928176/54d1b22c-85bf-11e6-8ae7-317fef12268f.png)

FF 49.0.1

**Comment by gideonthomas** [comment]
Hi @rugk, might I ask what operating system you're running this on?

**Comment by rugk** [comment]
Firefox 39
Linux x64 (Debian)

**Comment by gideonthomas** [comment]
@rugk, just to confirm, you are not opening this in Private Browsing mode, correct?

@humphd any insights on this (maybe @modeswitch might also have some thoughts)? @ScottDowne also seems to have the same issue and he's running Fedora Firefox (not sure about the version but I think it was around the 39-49 range).

**Comment by rugk** [comment]
>  just to confirm, you are not opening this in Private Browsing mode, correct?

Yes, *but*
* I disabled third-party cookies
* and I use [the tracking protection](https://testpilot.firefox.com/experiments/tracking-protection) of Firefox, but as you can see on the screenshot it does not block anything in this case

**Comment by humphd** [comment]
It looks like it can't get at `indexeddb` for some reason.  It could be permissions, or it could be a corrupt DB, which is #1136.  Maybe try with a different profile (i.e., a clean db)?

**Comment by rugk** [comment]
Would checking the databases with `about:support` work too or is this a different database?

**Comment by ScottDowne** [comment]
When I had this issues, the data was completely corrupted, and getting rid of it fixed the issue. I could not even inspect it.

I was asking how it got corrupted, but I never could reproduce it. I wondered if it somehow got corrupted from saving during an older build of thimble.

**Comment by rugk** [comment]
So I now deleted all data from `thimble.mozilla.org` by just using Firefox history and right-clicking on `thimble.mozilla.org` -> "Forget this website".

By doing so I could indeed get a different result (at least this is what I think) as the phage just loads indefinitely.

BTW: Already when loading the main page I get an error from the embedded YouTube video:
![thimbleyterror](https://cloud.githubusercontent.com/assets/11966684/19096735/0f95bcb4-8a9f-11e6-93b6-82a87e6295d3.png)

So here is a video showing some errors in the JS debugger: https://github.com/rugk/otherfiles/blob/master/largeupload/ThimbleErrorJS.webm.zip?raw=true

**Comment by modeswitch** [comment]
Is this using Filer?

**Comment by rugk** [comment]
What??

**Comment by humphd** [comment]
@rugk sorry, he was asking me.  @modeswitch, yes, it's Filer.  I think it's the Firefox/idb bugs we already know about tbh.

**Comment by gideonthomas** [comment]
@humphd but if I remember correctly, in those cases IndexedDB never threw errors? Didn't it silently crash and return a null instance (I might be remembering incorrectly)? In this case IndexedDB is actually throwing an error which now that I notice, we don't log.

I don't remember why we didn't do this before but can we log `event.target.errorCode` [here](https://github.com/filerjs/filer/blob/develop/src/providers/indexeddb.js#L135)? Will that help debug the issue since we'll know what error is actually being thrown?

**Comment by Pomax** [comment]
as far as I'm aware, disabling cookies also disables indexdb and localstorage, as these are considered the same kind of "site-specific transient data storage", so I would not expect Thimble to work at all under these conditions.

It might be worth try/catching indexdb and localstorage access to determine whether Thimble will be able to successfully load as part of bootstrapping.

**Comment by gideonthomas** [comment]
But the user only disabled third party cookies so same origin indexeddb access should be permitted.

From what I understand from the API, those errors are passed to the callback when you request an instance of indexeddb. But in Filer, we don't actually log those errors anywhere and instead pass back a custom filer error.

**Comment by rugk** [comment]
> But the user only disabled third party cookies so same origin indexeddb access should be permitted.

Yes, but I also use [this cookie addon](https://addons.mozilla.org/de/firefox/addon/self-destructing-cookies/), but it only removes cookies after the tab has been closed.

**Comment by gideonthomas** [comment]
We have come up with a UX solution here: https://github.com/mozilla/thimble.mozilla.org/issues/1568, will be tracking the conversation there as well.
