### ISSUE TITLE
Sass or SCSS compiling

### ISSUE THREAD

**Issue by brob** [mozilla/thimble.mozilla.org#1557]
Compiling CSS would be amazing to work into a platform like this. I use CodePen regularly for teaching and would LOVE to move to something like this to teach more complex things, but having SCSS is a must

**Comment by humphd** [comment]
As an aside, we have limited support for LESS already (it will auto convert `*.less` to `*.css` on save, same for markdown).

**Comment by brob** [comment]
Interesting. I suppose one hurdle in this is a "if you give a mouse a cookie" scenario. If you can convert *.less to *.css someone will probably want to convert and concat into one file from many

**Comment by Pomax** [comment]
That's more something that a build system does not really something editors do. We only offer you the editor so autoconversion "on save" is something a plugin can achieve, but getting a full LESS compile with minification etc going on is generally reserved for when you have a terminal available.

**Comment by humphd** [comment]
Right.  We don't really publicize that this is doable, because doing it completely (with imports of secondary files) gets hard to do without problems (e.g., circular deps).  Without a user-initiated "compile" step of some sort, it's tricky.  Adding one was deemed to be a more advanced thing most of our users aren't doing.  But I get why you want it.

**Comment by brob** [comment]
I totally get that all that. Would still love SCSS as an option mirroring the LESS option, as that's my pre-processor of choice.

For the most part, I'll be using this around more basic teaching for the moment.

**Comment by flukeout** [comment]
Closing until we tackle other types of processors/platforms down the road.
