### ISSUE TITLE
make projects without an index.html save an index.html that is more helpful than "oh no" with a "virtual file" flag in the project metadata

### ISSUE THREAD

**Issue by Pomax** [mozilla/thimble.mozilla.org#1560]
slightly long title, but it would be very helpful for users if Thimble saved projects that do not have an `index.html` with an auto-generated index.html that gives users a hint on which URL they might want instead, such as a simple hyperlink list of `.html` files that do exist in the project (given that Thimble projects are remixable, exposing this information is in line with the fully open, remixable data concept Thimble is based around). 

A basic flow:
- user publishes project from _client_
- *server receives publish instruction
- _server_ checks file layout for the to-publish information
- if it does not see an `index.html`, it runs `generateVirtualIndex()` to generate an index.html file that is added to the "to-publish" set of files only (_not_ the user's project)
- _server_ sends files off to AWS/S3/wherever

This `generateVirtualIndex` would do something akin to:
- grep the project filesystem for all `.html` files, ordered by nesting (root first, then depth-first)
- template the result into a wrapper html snippet as `<a href=...>` elements so that users have a way to navigate to content
- also offer a link to remix the project itself entirely
- also offer text along the lines of "if this is your project and want people to see your main page rather than this disambiguation page, you will need to create an `index.html` for your project. You can do this by clicking ...blahblhablahblah" with some screenshots that illustrate how to add that index.html file.

Since this index.html file only exists at the time of publication in the absence of a user-defined index.html, the project files themselves are not affected, and loading up the project either for editing or remixing will not server up this file as suddenly having been generated into the project (rightly so. We should not be generating this file _into_ the project, only into the file set pushed to S3)

**Comment by humphd** [comment]
This is what I've always wanted, too.  I wrote it once upon a time (this is what my `nohost` dir listing does).  I think the issue we got stuck on was that this needed to happen on publish vs. thimble or in the browser--I can't remember why, and maybe we can get around it.  If we could, it would be fairly trivial to fix this.

**Comment by Pomax** [comment]
Agreed - it would make a lot of sense to implement this as functionality in the publish.webmaker.org codebase, invoked at the time of publication, rather than something that thimble itself does.

**Comment by Pomax** [comment]
Filed on publish.wmo as https://github.com/mozilla/publish.webmaker.org/issues/236

**Comment by humphd** [comment]
Related: #1261

**Comment by humphd** [comment]
#1563, #1566

**Comment by gideonthomas** [comment]
We have come up with a UX solution here: #1569, will be tracking the conversation there as well.
