### ISSUE TITLE
Some weirdness/unexpectedness in remix, not logged in, and cached changes

### ISSUE THREAD

**Issue by ScottDowne** [mozilla/thimble.mozilla.org#1562]
@gideonthomas 

Not sure yet what's happening, but I have clear STRs.
1. be not logged in.
2. got to a thimble project, I was initially doing it here: https://thimbleprojects.org/chadsansing/112205/
3. hit remix.
4. maker some changes.
5. go back to https://thimbleprojects.org/chadsansing/112205/
6. hit remix again

Expected: my changes should be gone.
Actual: my changes are there. Cached? Stored? dunno.

Some info from poking around and trying different angles.

The redirect url is the same every time I hit the remix button, but if I copy the remix button target, paste it in a new tab, and hit enter, I get a different url, without my changes. Something to do with the GUID generated from https://thimble.mozilla.org/en-US/projects/112205/remix

**Comment by ScottDowne** [comment]
New info, the click and right click + open in new tab always give the same project, and the copy target + paste and go in new tab always gives me the same project, but different than the first. So essentially I have two project remixes.

**Comment by humphd** [comment]
We haven't moved anywhere on this for over a year, closing.
