### ISSUE TITLE
Changing the filename of index.html results in an error page

### ISSUE THREAD

**Issue by hurryupmode** [mozilla/thimble.mozilla.org#1563]
I was having some trouble with a class assignment. 
Once of the requirements was that the filename be changed to cis89basic1.html. 
After publishing, I'd get an error page that said "Oh no! The page you're looking for is not available!"

The remix project I worked on last week didn't present any issues.
I unpublished and published a few times in multiple browsers, but still got the same issue with the resultant updated URLs.

Thanks to my professor, who suggested I copy and paste it into a new project, I stumbled onto one of the edges of the bug!

I think it has to do with renaming index.html to cis89basic1.html, and different behaviors between "updating the published version" and "unpublishing then publishing".

Here's what I found regarding the bug:

If you change index.html to something else, it'll break. 
If you change the filename back to index.html, using the green "update the published version" button will not fix it. 
If you "unpublish" and "publish" again with index.html, it'll work.
If you "unpublish", change the filename to something else, and "publish", it'll break again.

edit: Maybe the "update the published version" is technically a different bug. I just happened to catch it with it's interaction with the index.html one. 

I hope you found this helpful.

**Comment by humphd** [comment]
What happens if you change it to `cis89basic1.html` and then navigate to that URL vs. just the `/` (i.e., add your filename to the end of the slash so it points to your file vs. the implied `index.html` which won't exist)?

**Comment by gideonthomas** [comment]
We have come up with a UX solution here: #1569, will be tracking the conversation there as well.
