### ISSUE TITLE
Investigate and fix files reverting back to older versions

### ISSUE THREAD

**Issue by gideonthomas** [mozilla/thimble.mozilla.org#1564]
We're going to begin this by debugging this issue as a group (meeting scheduled for Wed, Oct 19). We have a lead into what is going wrong (most likely related to the way we generate the names for new files).
The project where we are able to reproduce this issue is: https://thimbleprojects.org/cfmonk/100440/ and the steps to reproduce can be found [here](https://github.com/mozilla/thimble.mozilla.org/issues/1550#issuecomment-253609237).

Issues that are related to this and that have been closed as a result of consolidating duplicates are:
- #1550
- #1471

**Comment by humphd** [comment]
The bug is most likely in here, or in what this calls: https://github.com/mozilla/brackets/blob/master/src/document/DocumentCommandHandlers.js#L680-L725
