### ISSUE TITLE
Bug de publication

### ISSUE THREAD

**Issue by damiennegri** [mozilla/thimble.mozilla.org#1566]
bonjour j'aimerai partagé mon projet mais à chaque fois le lien n'est pas valide :(
Pourriez-vous m'aider?

**Comment by humphd** [comment]
Que signifie exactement invalide? Avez-vous renommez votre page index.html à autre chose? (J'ai utilisé Google traduction, donc pardonner les pauvres français.)

**Comment by damiennegri** [comment]
Oui, j'ai renommé ma page index.html, je l'ai renommé "A-index.html". Le
lien de partage me redirige à une page thimble:"oh non the page you're
looking for is not available".

Le 16 oct. 2016 5:26 PM, "David Humphrey" <notifications@github.com> a
écrit :

**Comment by damiennegri** [comment]
Salut! Ça remarche j'ai renommé mon index.html et ça marche, merci!

Le 16 oct. 2016 5:26 PM, "David Humphrey" <notifications@github.com> a
écrit :

**Comment by humphd** [comment]
Si vous utilisez /A-index.html au lieu de juste un / il travaillera avec le fichier renommé. Glad cela a fonctionné!
