### ISSUE TITLE
getting 500 error remix and my projects unavailable message

### ISSUE THREAD

**Issue by jgmac1106** [mozilla/thimble.mozilla.org#1574]
I and my students are getting a 500 error when trying to remix projects or open "my projects"

I have tried Firefox and Chrome on our University network and got same result. 

I was able to load "my projects" on Firefox for mobile (not on network) and get my projects to load. I

If this is a local netowrk issue let me know and I can close the issue.

**Comment by jgmac1106** [comment]
Seems to be back to normal(ish). A little slow but functioning fine

**Comment by jgmac1106** [comment]
@gideonthomas reported disk space was full.

**Comment by cfmonk** [comment]
We're in Sydney and having a nightmare with this today! Lots of projects being lost, 500 Errors, unable to load project, failing to publish etc....

**Comment by cfmonk** [comment]
This one was particularly bad today:
https://thimbleprojects.org/mollusc6/125803/

**Comment by humphd** [comment]
@cfmonk brutal, sorry to hear this. @cadecairos, @gideonthomas can you check on what's happening server side?

**Comment by cadecairos** [comment]
I'm digging through all of our log data to see what happened. Good news, though, things seemt to recover at around 3AM Eastern time and have looked ok ever since.

**Comment by cadecairos** [comment]
I think what happened is that after we expanded the storage capacity of the projects database, the publish servers needed to be restarted to get new connections to the database. This never happened, so errors continued until the daily restart kicked in (which was actually around 12AM Eastern). Once that happened, everything went back to normal, and it continues to look that way.

**Comment by jgmac1106** [comment]
Okay closing this.

**Comment by humphd** [comment]
Thanks @cadecairos

**Comment by cfmonk** [comment]
Thanks all!
