### ISSUE TITLE
Back-to-school postcard mobile display

### ISSUE THREAD

**Issue by lkeneco** [mozilla/thimble.mozilla.org#1577]
The back-to-school post card does not display properly in mobile mode. It would be useful for learners if the tutorial added guidance on some basic steps (responsive design) to make the postcard look good for web or mobile.

Thanks

**Comment by gideonthomas** [comment]
@flukeout any insights into this?

**Comment by flukeout** [comment]
I'll check into it.

**Comment by flukeout** [comment]
In addition to the styling issue (the postcard format is too wide for a narrow viewport) the card only flips when you hover your mouse over it, which isn't possible on a mobile device. I'll see if there is an easy fix (like adding a flip button for narrower viewports).

**Comment by flukeout** [comment]
@lkeneco I created an updated version that handles mobile styling a little better, could you take it for a spin (ha ha)?

* https://thimbleprojects.org/flukeout/128667/

Tap it to flip, tap the yellow background to flip back. Let me know!

cc @chadsansing

**Comment by lkeneco** [comment]
Hi,

I did see your updated version, played with it briefly and it was looking good. Thanks! Now it seems to have reverted back to the previous version. What happened? This happened on the main thimble page and not in my own account because I'm also having login issues and waiting for a password reset email that hasn't shown up yet.

**Comment by gideonthomas** [comment]
Hi @Ikeneco we haven't updated it on the main Thimble page yet so you will still see the old version there.
If you like the version that @flukeout has provided with the link above, we can update it on the main page as well. @flukeout can you follow up with @chadsansing and @hannahkane about migrating it to the mozillalearning account?

@Ikeneco I'm going to loop in @cadecairos to see if he is able to help you out with your password reset email.

**Comment by lkeneco** [comment]
Hi Gideon:

Thanks for your help. I'll check back later.

**Comment by cadecairos** [comment]
@lkeneco I just fixed an issue that was holding up email delivery for password resets. You may recieve an email for your last reset request, but it might have expired by now. Please try asking for another reset email, and let me know if it comes through for you.

**Comment by flukeout** [comment]
@chadsansing are you in control / owner of the Postcard project linked from the Thimble homepage?

If so, could you please test out this version - https://thimbleprojects.org/flukeout/128667/ - and if you're happy with it, update the existing code to match this one? Cheers!

**Comment by chadsansing** [comment]
I am not - I believe @hannahkane or whoever has access to /projects/ might be?

**Comment by hannahkane** [comment]
@flukeout - is there a tutorial in your version? I'm getting an error when I click on the tutorial.html file. "An error occurred when trying to open the file. The file could not be found."

Should I use the existing tutorial, and just edit the index file?

**Comment by flukeout** [comment]
You don't see a tutorial file in the project after remixing?

**Comment by hannahkane** [comment]
Hmm...this time I do. Sorry about that. Will update the code on the MozillaLearning-authored project now.

**Comment by flukeout** [comment]
@hannahkane ok - it's ready to go. Please update both the ``index`` and ``tutorial`` files, as I've had to change update the line number references in the tutorial.

**Comment by hannahkane** [comment]
OK, done. Thanks for filing, @lkeneco!
