### ISSUE TITLE
"Back to School Postcard" tutorial line numbers need to be updated

### ISSUE THREAD

**Issue by gideonthomas** [mozilla/thimble.mozilla.org#1578]
There are a bunch of line number errors in the tutorial for the Back to School Postcard starter project that need to be fixed.

So far here's what I found:
- The first step says `Go to line 245`; it should be line 242
- The second step says `Go to line 139`; it should be 138
- The third step says `Go to line 261`; it should be 254
- The fourth step says `Go to line 54`; it should be 51

I don't know who manages the mozillalearning account (who manages the starter templates), maybe @chadsansing?

**Comment by chadsansing** [comment]
I think @hannahkane moved these over from my account to mozillalearning - is that correct? Can you update the tutorial, Hannah?

**Comment by gideonthomas** [comment]
@flukeout this has been fixed in your patch right? If so, we can close this.

**Comment by flukeout** [comment]
Yeah, closing
