### ISSUE TITLE
Shift command does unexpected file view change.

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.mozilla.org#1581]
Shift + RightCommand / LeftCommand navigates up and down the file tree. I also use it to select text in the editor (combined with arrow keys), so the change is very jarring and unwanted. Anyone else experience this?

**Comment by humphd** [comment]
You use Shift + Command to select text in the editor?  Why not shift + arrow keys?

**Comment by flukeout** [comment]
Shift + Arrow + Command selects the entire row after or before your cursor, and I use that a lot.

**Comment by humphd** [comment]
@gideonthomas same issue with this bug, can you comment on where the keybindings live for Brackets?  I can't find it.

**Comment by humphd** [comment]
I think it's https://github.com/adobe/brackets/blob/f028b3ecdf2017498196f39ddbbe4a2364366c92/src/base-config/keyboard.json

**Comment by humphd** [comment]
Closing in favour of #1646
