### ISSUE TITLE
Addition of PHP support

### ISSUE THREAD

**Issue by NetherDragons** [mozilla/thimble.mozilla.org#1583]
I think PHP should be implimented as alot of projects could be taught like login verification, etc.

**Comment by humphd** [comment]
We're focusing on client-side HTML, JS, CSS, etc vs. server side code.  There are other similar tools that do allow you to do server side scritpts, Cloud9 is one.  I'm going to close this, since it's not likely to happen.  It's a good idea, but beyond the scope of what we want to support.
