### ISSUE TITLE
Add Emmet to editor  that will help for faster typing

### ISSUE THREAD

**Issue by FERMAT1991** [mozilla/thimble.mozilla.org#1585]

**Comment by humphd** [comment]
@FERMAT1991 we have hacked Brackets, yes, and the code lives here: https://github.com/mozilla/brackets.  I've written about how we do everything here: http://blog.humphd.org/thimble-and-bramble/

**Comment by humphd** [comment]
https://github.com/emmetio/brackets-emmet

**Comment by humphd** [comment]
Copying this comment over from #1854:

One of our users, Roberto Matthews, left a feature request on our YouTube video...


> Hello there!  I've been a long time Brackets user, but since I am always updating clients' sites, I needed a way to text and fix things online when I'm on the road.  Thanks to Thimble, I can do this very well now.  One thing would make this program even more perfect...  is there a way to add Emmet editing?﻿


Links
* http://emmet.io/
* Bracket Extension - https://github.com/emmetio/brackets-emmet

**Comment by gideonthomas** [comment]
Closing since I think this has been superseded by snippets
