### ISSUE TITLE
Unable to export zip

### ISSUE THREAD

**Issue by gideonthomas** [mozilla/thimble.mozilla.org#1595]
We got an email about a user being unable to export the project as a zip on Firefox on Linux and Windows. They are able to export on Chrome though.

Will provide more details once they are available.

@humphd any first guesses as to why this might be happening?

**Comment by humphd** [comment]
It looks like a CSP issue:

```
Content Security Policy: The page’s settings blocked the loading of a resource at blob:https://mozillathimblelivepreview.net/2aafdf42-87af-cf4e-9b5f-4fbe2b284c83 (“frame-src https://thimble.mozilla.org https://docs.google.com https://mozillathimblelivepreview.net https://www.youtube.com/embed/JecFOjD9I3k”).
```

I'm not sure what we're doing that it doesn't like about this.  Maybe that the download Blob is coming from inside the iframe on a different domain?

**Comment by gideonthomas** [comment]
Wait, you're able to reproduce this?

**Comment by humphd** [comment]
Yes, I'm using FF (Developer Edition) on Mac and it fails with that CSP thing thrown to the console.

**Comment by humphd** [comment]
I wonder if we need to add `blob:` to the permitted `*-src` values for our CSP.  I see people doing this for images elsewhere.

**Comment by humphd** [comment]
For example:

```
Content-Security-Policy:
    default-src 'self';
    connect-src 'self' https://sentry.prod.mozaws.net;
    font-src 'self' https://addons.cdn.mozilla.net;
    frame-src 'self' https://ic.paypal.com https://paypal.com
        https://www.google.com/recaptcha/ https://www.paypal.com;
    img-src 'self' data: blob: https://www.paypal.com https://ssl.google-analytics.com
        https://addons.cdn.mozilla.net https://static.addons.mozilla.net
        https://ssl.gstatic.com/ https://sentry.prod.mozaws.net;
    media-src https://videos.cdn.mozilla.net;
    object-src 'none';
    script-src 'self' https://addons.mozilla.org
        https://www.paypalobjects.com https://apis.google.com
        https://www.google.com/recaptcha/ https://www.gstatic.com/recaptcha/
        https://ssl.google-analytics.com https://addons.cdn.mozilla.net;
    style-src 'self' 'unsafe-inline' https://addons.cdn.mozilla.net;
    report-uri /__cspreport__
```

from https://hacks.mozilla.org/2016/02/implementing-content-security-policy/

**Comment by gideonthomas** [comment]
Yeah I'm pretty sure that is the issue. The download is initiated by Brackets not Thimble and CSP doesn't allow blob protocolled domains

**Comment by gideonthomas** [comment]
I wonder if there are any security concerns for this since it will be user-generated content.

**Comment by humphd** [comment]
No, because it's not being executed.  I think we should just add `blob:`.

**Comment by cadecairos** [comment]
I think it's alright

**Comment by indranil-tiwary** [comment]
Can I try too solve this bug??

**Comment by humphd** [comment]
@indranil-tiwary sure, please do.  I think the change needs to happen in https://github.com/mozilla/thimble.mozilla.org/blob/fa3dde088dc016a562520e62a9df1f5558ba8f70/server/security.js.  Maybe @cadecairos can confirm.

**Comment by cadecairos** [comment]
thats the right spot

**Comment by humphd** [comment]
@indranil-tiwary how are you doing with this bug?

**Comment by shiri04** [comment]
can I work with this bug?

**Comment by humphd** [comment]
@shiri04 yes, please do.  It looks like @indranil-tiwary might have had to focus on other things.

**Comment by matthieu-foucault** [comment]
If this is not fixed soon, could it be possible in the meantime to disable this button, or show a help message to firefox users? 
I have students who were stuck with submitting an assignment because nothing happens when you click on the button, and it took them a while to figure out that they should try with Chrome.

**Comment by humphd** [comment]
@matthieu-foucault if @shiri04 doesn't fix this before Monday, I'll do it for you.  I'm curious how you're using Thimble.  How many students do you have, and what level are they at?  We're really appreciating the good bugs you are finding and filing.

**Comment by humphd** [comment]
As discussed, I have a PR up to fix this in https://github.com/mozilla/thimble.mozilla.org/pull/1818

**Comment by barrosgeraldo** [comment]
@humphd, the problem still occurs, this fix is in the current version of Thimble?

**Comment by humphd** [comment]
@barrosgeraldo it's on our staging box, but not on production yet.  We've got a bunch of fixes to ship to prod, hopefully this week.

Staging is at http://localhost:3000/validate/someone if you want to test.

**Comment by barrosgeraldo** [comment]
@humphd thanks, sorry for the rush, I'm working with Thimble these days and I need this functionality. 👍

**Comment by humphd** [comment]
No, it's us that should be saying 'sorry'! We need to deploy this fix to prod.  Soon...
