### ISSUE TITLE
Can't open any any saved projects or new projects in Chrome

### ISSUE THREAD

**Issue by kjstieda** [mozilla/thimble.mozilla.org#1597]
My students have chromebooks and some are starting to have an issue when signing in.  They can sign in, but when they choose New Project or Your Projects, the screen doesn't change.  I am having the same problem on my laptop, but can open projects and such in Mozilla.

**Comment by humphd** [comment]
@kjstieda I'm sorry to hear you're having issues.  Are you able to open Dev Tools on one of those machines and paste whatever it's logging?

**Comment by kjstieda** [comment]
I am trying on my computer as it won't work on Chrome for me either and the Dev Tools is grayed out.

**Comment by Friscopolice** [comment]
I am having a similar issue but it is for Mozilla Firefox. I can log in as well but cannot view any projects.

**Comment by gideonthomas** [comment]
Hi @kjstieda,

I have a suspicion, but would you help me try to confirm it? You can do so by:
- Signing into Thimble and then staying on the page which does not change when you click on "New Project" or "Your Projects"
- In a new tab, copy/paste the following into the url bar: [chrome://settings/clearBrowserData](chrome://settings/clearBrowserData) (hopefully you are able to access this)
- Only select the "Cached images and files" checkbox and make sure the "Obliterate the following items from" option is set to "the beginning of time" (I promise, it's not as scary as it sounds). Click the "Clear Browsing Data" button.
- Now go back to the Thimble tab and click on the button that did not do anything ("New Project" or "Your Projects"). Please let us know what happens.

As for you not being able to open Dev Tools, if you are using a work computer, they might have disabled dev tools for Chrome. You can confirm this by going to [chrome://policy/](chrome://policy/) in your URL bar and seeing if the "DeveloperToolsDisabled" value is set under Chrome Policies.

Let us know if you have any issues.

**Comment by kjstieda** [comment]
Now it is working.  The next time it doesn't work, I will do this.  Thanks!
