### ISSUE TITLE
Failing to publish after uploading images over 2mb

### ISSUE THREAD

**Issue by Jonnygwi** [mozilla/thimble.mozilla.org#1598]
We get stuck in a "Saving..." / "Failed to save..." / "Retrying..." loop after trying publish a project with a PNG that is 2.6MB in size. 

Even after deleting the file we are still unable to save the project from this point onwards. Resulting in you having to make a fresh project and copying the files across. 

We tried with some other images that were below 1MB and it successfully published.

**Comment by flukeout** [comment]
Thanks for filing @Jonnygwi - we've seen this with other image-heavy projects. I'll do some testing to see where the actual image size cutoff is.
