### ISSUE TITLE
Problems while running the project locally

### ISSUE THREAD

**Issue by nailaandleeb** [mozilla/thimble.mozilla.org#1601]
I want to run this locally and have setup everything according to the docs.but the project homepage is just showing loading status.
![image](https://cloud.githubusercontent.com/assets/8026795/21811868/fb386962-d772-11e6-9db4-44fc4e53f9b0.png)

Note:
1-One thing is its url which is "http://localhost:3500/en-GB/anonymous/ad107f13-0f87-4341-adb5-874d2365ed69" it shows anonymus despite of login.when i open "localhost:3000/account" it opens my account.

2-TypeError:initializeFile is null is ununderstandable.
3-Also getting this error in console..
![image](https://cloud.githubusercontent.com/assets/8026795/21812094/a23b5ae4-d773-11e6-84a8-64ed5d57665f.png)

Any Help please???i need it urgent...

**Comment by gideonthomas** [comment]
Hi @nailaandleeb, thanks for providing the errors, they will help us try to figure out what's wrong. But, would you be able to let us know how you logged in? On the main Thimble page, did you click on "Sign In" and follow the steps from there or did you login via other methods? localhost:3000/account is detached from Thimble so even if you are logged in there, you need not necessarily be logged in on Thimble.

Regarding the `initialFile is null` error, @humphd any idea what's going on there? I dug into the Brackets code for that but I can't point out what might be going wrong. I'm guessing a timing issue because either the active pane, current file, or current view is `null` and that is being passed down to RemoteEvents.

**Comment by nailaandleeb** [comment]
Thanxs for your response @gideonthomas I logged in through localhost:3000/account and the console of login.webmarker.org shoed my creadentials and also when i opened localhost:3000/account  it redirected me to my dashboard but yes i can see this problem that this login is detached from thimble.but i followed the docs as it is.

**Comment by nailaandleeb** [comment]
ok a little progress here.if i enter the url as "localhost:3500/en-GB" it redirects to login page and after successful login it redirects to "http://localhost:3500/%5Cen-US%5C%5Cen-US%5C%5Cen-US%5C%5Cen-US%5C%5Cen-US%5C%5Cen-US%5C%5Cen-US%5C%5Cen-US%5C%5Cen-US%5C%5Cen-US%5C%5Cen-US%5C%5Cen-US%5C%5Cen-US%5C%5Cen-US%5C%5Cen-US%5C%5Cen-US%5C%5Cen-US%5C%5Cen-US%5Ccallback?code=0ce6a917d9972241ba0e384d22e25f98043b113681ec6eae37ea265418a8d9fb&client_id=test&state=3da93f99-96e7-4efb-8a57-cd6ac7eb0044" 

![image](https://cloud.githubusercontent.com/assets/8026795/21837643/3a0f2186-d7ef-11e6-8520-430fccc776cd.png)

**Comment by nailaandleeb** [comment]
After some workaround and with the hep of <a href="https://github.com/mozilla/thimble.mozilla.org/pull/1605">this PR</a> i was able to get an error on
console.   

ERROR: { message: 'Request to http://localhost:1234/login/oauth/access_token returned a status of 403',
  context: '{"statusCode":403,"error":"Forbidden","message":"auth code expired"}',
  userMessage: 'Failed to login!',
  locale: 'en-US' } 

And i think this the reason behind the error initialFile is null...

**Comment by nailaandleeb** [comment]
With the help of <a href="https://github.com/mozilla/thimble.mozilla.org/pull/1605">this PR </a> i could be able to find the error on my console in case of signin.
 ERROR: { message: 'Request to http://localhost:1234/login/oauth/access_token returned a status of 403',
  context: '{"statusCode":403,"error":"Forbidden","message":"auth code expired"}',
  userMessage: 'Failed to login!',
  locale: 'en-US' }

But "start a project from scratch"  button still gives loading page.

**Comment by gideonthomas** [comment]
@nailaandleeb are you seeing different errors in your console this time?

**Comment by nailaandleeb** [comment]
@gideonthomas  same error for test project(without login).which i overcome by hardcoding the url in this file."brackets/src/extensions/default/bramble/lib/RemoteEvents.js;135

            var fullPath = initialFile.fullPath;

to

            var fullPath = "/7/projects/30/index.html";

So,this opened test project for me without login.

 I case of login after implementing what is suggested in <a href="https://github.com/mozilla/thimble.mozilla.org/pull/1605">PR</a> with a minor change.

  <h3>changing this:</h3> 
            "server/localize.js"
                +      localizedUrl = "/" + bestLanguage + "/" + (orgUrl === "/" ? "" : orgUrl);

 <h3>To this:</h3> 
            "server/localize.js"
                +      localizedUrl =  bestLanguage + (req.originalUrl === "/" ? "" : req.originalUrl);



I got an error in console as

            id.webmaker.org returning 403 instead of access token.and it made one thing clear that there is a problem in the redirections(routing) of this project or i have problem in understanding this.

**Comment by nailaandleeb** [comment]
I am closing this issue because of no lead on this even after so many days i can't use it successfully. 👎

**Comment by ryanwarsaw** [comment]
@nailaandleeb Hi nailaandleeb, I'm sorry to see you've been having issues setting up Thimble locally. We just recently landed a PR that simplifies the setup process by using a tool called Vagrant. You might be interested to try it out, you can find more information in the README.

Furthermore, I'm going to re-open this issue because it still needs to be investigated and resolved. I understand your frustration and am here to help, so is @gideonthomas!

**Comment by nailaandleeb** [comment]
thanks @ryanwarsaw  i'll  try vagrant now.kindly look into this issue.

**Comment by nailaandleeb** [comment]
vagrant is throwing an error as:
      
     ==> default: Err http://archive.ubuntu.com/ubuntu/ trusty-updates/main libc-ares2 amd64 1.10.0-2ubuntu0.1
      ==> default:   Cannot initiate the connection to archive.ubuntu.com:80 (2001:67c:1360:8001::17). - connect (101: Network is unreachable) [IP: 2001:67c:1360:8001::17 80]
      ==> default: Err http://archive.ubuntu.com/ubuntu/ trusty/universe libv8-3.14.5 amd64 3.14.5.8-5ubuntu2
      ==> default:   Cannot initiate the connection to archive.ubuntu.com:80 (2001:67c:1360:8001::17). - connect (101: Network is unreachable) [IP: 2001:67c:1360:8001::17 80]
      ==> default: Err http://archive.ubuntu.com/ubuntu/ trusty/universe nodejs amd64 0.10.25~dfsg2-2ubuntu1
      ==> default:   Cannot initiate the connection to archive.ubuntu.com:80 (2001:67c:1360:8001::17). - connect (101: Network is unreachable) [IP: 2001:67c:1360:8001::17 80]
      ==> default: Err http://security.ubuntu.com/ubuntu/ trusty-security/main libc-ares2 amd64 1.10.0-2ubuntu0.1
      ==> default:   Could not resolve 'security.ubuntu.com'
      ==> default: E
      ==> default: :
      ==> default: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/c/c-ares/libc-ares2_1.10.0-2ubuntu0.1_amd64.deb  Could not resolve 'security.ubuntu.com'
      ==> default: E
      ==> default: :
      ==> default: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/universe/libv/libv8-3.14/libv8-3.14.5_3.14.5.8-5ubuntu2_amd64.deb  Cannot initiate the connection to archive.ubuntu.com:80 (2001:67c:1360:8001::17). - connect (101: Network is unreachable) [IP: 2001:67c:1360:8001::17 80]
      ==> default:
      ==> default: E: Failed to fetch     http://archive.ubuntu.com/ubuntu/pool/universe/n/nodejs/nodejs_0.10.25~dfsg2-2ubuntu1_amd64.deb  Cannot initiate the connection to archive.ubuntu.com:80 (2001:67c:1360:8001::17). - connect (101: Network is unreachable) [IP: 2001:67c:1360:8001::17 80]
      ==> default:
      ==> default: E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
      The SSH command responded with a non-zero exit status. Vagrant
      assumes that this means the command failed. The output for this command
      should be in the log above. Please read the output to determine what
      went wrong.

Its my first time with vagrant and virtualbox.So do i need to open another issue.?

**Comment by humphd** [comment]
That looks like network trouble.  You can just retry it with `vagrant up --provision` as many times as you like until that command works.

**Comment by nailaandleeb** [comment]
Now the error is:

        GPG error: http://ppa.launchpad.net trusty InRelease: 

        The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 1E9377A2BA9EF27F

and it is consistences after over night tries.....what key it needs?

**Comment by humphd** [comment]
Something sounds corrupt in the VM, and I see others having similar issues: http://askubuntu.com/questions/566195/signatures-not-verified.

What I'd do is this:

```
vagrant destroy
vagrant up
```

This should force it to do things again and clean up whatever mess it got into with the downloads.  Sorry you're having issues.

**Comment by gideonthomas** [comment]
Hi @nailaandleeb, were you able to get this running again?

**Comment by nailaandleeb** [comment]
No  i  can't run neither locally nor with vagrant.tried with new updated docs too.I'll be grateful if u suggest something in windows context.

**Comment by nailaandleeb** [comment]
![capture](https://cloud.githubusercontent.com/assets/8026795/22688833/bc125ec6-ed4f-11e6-9e47-c85ed1f8e68f.PNG)


always ends up with this error

**Comment by ryanwarsaw** [comment]
@nailaandleeb Can you do me a favor and try and see if this resolves the problem for you? Run the command ```vagrant destroy``` then delete your Vagrantfile and replace it with this one: https://gist.github.com/ryanwarsaw/53555778e0629fa210efbae1e589eb98. 

I've basically added an extra configuration option that should resolve the issue: ```vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]```. Let me know if this resolves the issue for you.

**Comment by nailaandleeb** [comment]
![capture](https://cloud.githubusercontent.com/assets/8026795/22797846/a3b44884-ef21-11e6-8bd8-958011b59361.PNG)

now this problem on vagrant up

**Comment by nailaandleeb** [comment]
can we discuss it in detail at <a href="http://gitter.im/">gitter.im</a> ?

**Comment by ryanwarsaw** [comment]
@nailaandleeb We have a Mattermost! You can join here: http://chat.mozillafoundation.org, you can also connect using the native Mattermost apps (found here: https://about.mattermost.com/download/). I'd like to discuss this further with you and see if we can't figure out the rest of your problems, you can find me in the Thimble channel!

Also it looks like the new configuration problem solved your previous problem, that's good to hear. This looks like the result of a permissions issue, which gives us something to work with.

**Comment by Pomax** [comment]
Heyl @nailaandleeb @ryanwarsaw did anything come out of discussions on this? Are there issues we can file to address things that were discovered?

**Comment by humphd** [comment]
I'm going to close this, since the discussion seems to have ended.  @nailaandleeb if you still have issues and want to discuss, let's start a new bug.
