### ISSUE TITLE
Unable to access Your Projects list due to Cache issue.

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.mozilla.org#1603]
From an educator...

* Students sign in to Thimble on their Chromebooks
* They click on the Your Projects link in the dropdown
* Instead of showing the Your Project page, a new project is created
* When these students are signed in on a different computer (Surface Pro), things work as expected

This is apparently happening to 6 students out of about 40.

Any other details we need? I could ask for the usernames of those students so we can see if it's anything on our end?

**Update** - I changed the title of this issue since it's not a Chromebook specific issue.

**Comment by ryanwarsaw** [comment]
It wouldn't hurt to ask for the usernames, perhaps it will provide some helpful insight for debugging purposes. Also just to clarify, are all the effected students using Chromebooks? Are there any students using Chromebooks that aren't having this issue?

**Comment by jgmac1106** [comment]
I just checked on two different Chromebooks (which would be no different
than any Chrome browser) and did not have the issue.

**Comment by flukeout** [comment]
Thanks for checking @jgmac1106. Just now we received another complaint about this issue from a different educator, using a desktop PC - so it's not hardware related.

@gideonthomas believes clearing the browser's cache might resolve this so I created some instructions and the user to try them out.

https://github.com/mozilla/thimble.mozilla.org/wiki/Clearing-your-cache

I'll report back once they've tried it.

**Comment by flukeout** [comment]
Confirmed that clearing the cache resolved this for the user that tried it. I'll leave the bug open.

**Comment by flukeout** [comment]
Just to follow up, this seems like a widespread issue that seems to affect many people on different types of setups. I wonder if it's related to switching between accounts on the same computer, which would happen in a classroom setting. In any case, we've received emails about this as well as had issues file on the repo, so I'm going to slap a critical label on it, we can discuss in triage today.

**Comment by humphd** [comment]
cc @cadecairos

**Comment by flukeout** [comment]
In our last call we discussed doing the following:

* Apparently we can tell client-side if some kind of token is invalid
  * I think this token is something that is handled by the Login server
* If the token is invalid, let's log out the user
  * Do we do something else in addition here to handle these tokens?
* When the sign in again, things should be back to normal

Does this sound about right @humphd & @gideonthomas can you add some extra detail here?

**Comment by humphd** [comment]
I think invalidating the session and logging them out on failure would be good, yes.

**Comment by humphd** [comment]
This sounds like what we're fixing in #2055, closing.
