### ISSUE TITLE
Use Vagrant to host dependent services in dev env

### ISSUE THREAD

**Issue by humphd** [mozilla/thimble.mozilla.org#1604]
Thimble is really hard to setup right now because it depends on so many other services, including:
* publish
* id
* login
* bramble

Let's follow the advice [here](https://blog.moove-it.com/vagrant-multiple-projects/) and use Vagrant and `git subtree` to host all these services in a vagrant box.  Getting this done soon is a priority, since we want students to start working on this code very soon.

Also note: it needs to be tested on Windows, which a lot of the students are using.

**Comment by gideonthomas** [comment]
@humphd what do you think about installing Brackets separately? I'm having issues with subtreeing Brackets because it does not install the submodules that Brackets uses. I can't find docs on how to do that either.

**Comment by humphd** [comment]
Sure, we can file another bug to figure that bit out later.

On Jan 16, 2017 3:03 PM, Gideon Thomas <notifications@github.com> wrote:

@humphd<https://github.com/humphd> what do you think about installing Brackets separately? I'm having issues with subtreeing Brackets because it does not install the submodules that Brackets uses. I can't find docs on how to do that either.

-
