### ISSUE TITLE
Thimble and WebVR: Create A-Frame Starter Kit(s)

### ISSUE THREAD

**Issue by humphd** [mozilla/thimble.mozilla.org#1609]
WebVR is a cool new technology that people are eager to try.  We should provide some pre-made, easy to modify and remix starter kits in Thimble for working with it.  A good entry point for beginning is [https://aframe.io/](A-Frame).  There are full docs for it available at https://aframe.io/docs/0.4.0/introduction/.

Various VR starter projects are possible, for example: a panorama, an AR example via 'getUserMedia' camera view background, a picture gallery, a basic game-like navigation, example w/ the physics module, different user navigation examples, panoramas using different popular 3D camera output files (with processing instructions).

**Comment by humphd** [comment]
See other bugs filed in https://github.com/mozilla/thimble.mozilla.org/search?q=aframe&type=Issues&utf8=%E2%9C%93

**Comment by ZenanZha** [comment]
I already fixed a bug with Aframe VR in [#1068](https://github.com/mozilla/thimble.mozilla.org/issues/1608).
I think I'm ready to fix this problem as well.

**Comment by pranay414** [comment]
@ZenanZha Are you working on it?, if not then may take this one?

**Comment by ZenanZha** [comment]
@pranay414  Sorry, I already finished all the main part of this Kit. I'm editing Teaching Kit docquments at the moment. Can you pick another one?

**Comment by pranay414** [comment]
Yes sure thanks for informing me!

**Comment by ZenanZha** [comment]
@pranay414 Thank you. A frindly tip: A Start Kit need one page of Teaching Kit(See in the img). We have to pay a lot effort to make it on our own.
![startkit](https://cloud.githubusercontent.com/assets/22037167/23809539/08a7f0f2-059c-11e7-9606-eaadbda39a71.PNG)

**Comment by flukeout** [comment]
How's it coming along @ZenanZha?

**Comment by ZenanZha** [comment]
@flukeout I was back from other school work until last weekend. Sorry for push this work back. Please give me some time. I'll try to get the Teaching Kit done within this week.

**Comment by flukeout** [comment]
No problem @ZenanZha - just checking in. Cheers.

**Comment by ZenanZha** [comment]
@flukeout Ready to go in bramble: [Pull2030](https://github.com/mozilla/thimble.mozilla.org/pull/2030)

Sorry for the lateness.

**Comment by flukeout** [comment]
Closing this in favor of creating a new issue where we can keep track of lots of ideas at once.
