### ISSUE TITLE
Thimble and IoT: Johnny-Five Starter Kit

### ISSUE THREAD

**Issue by humphd** [mozilla/thimble.mozilla.org#1612]
Create a starter kit that would use [Web Sockets](https://developer.mozilla.org/en-US/docs/Web/API/WebSockets_API) to connect to a [Johnny-Five](http://johnny-five.io/) instance, e.g., displaying a [Fritzing](http://fritzing.org/home/) or an [Arduino](https://www.arduino.cc/) but hooked up to a live Arduino via J5 on the other end.

**Comment by Riyuzakii** [comment]
@humphd This is indeed my first time on github, and i would like to help fix this bug, if you would be kind enough to guide me through it.

**Comment by humphd** [comment]
@Riyuzakii can I suggest that this bug is not a great one for your first experience.  Partly I say this because it represents an area that we're moving away from (IoT) vs. toward.  Partly I say this because if you want mentoring, I'd like to get you working on a bug that I know I can mentor well.

With that said, what do you think about working on https://github.com/mozilla/thimble.mozilla.org/issues/889?  I can do a better job there, if you're open to it.

**Comment by Riyuzakii** [comment]
@humphd Surely enough, i'm open to it, just tell me what to do.

**Comment by humphd** [comment]
Closing this, since I think it's not well scoped.  @Riyuzakii if you want to continue this discussion, let's do it in #889.  You can ask questions there.
