### ISSUE TITLE
Thimble and Graphics: Create p5.js Starter Kits

### ISSUE THREAD

**Issue by humphd** [mozilla/thimble.mozilla.org#1613]
It would be nice to make it easy to create sketches in Thimble using http://processingjs.org/ and/or https://p5js.org/.  With the latter, there are a ton of tutorials and starter videos we could integrate, see https://p5js.org/tutorials/.

Here's an example made by @flukeout: https://thimbleprojects.org/flukeout/172572/

**Comment by flukeout** [comment]
Closing as we have got one already. Will open a meta-issue to track other ideas.
