### ISSUE TITLE
Thimble and JS: Starter Kits using data.GUI

### ISSUE THREAD

**Issue by humphd** [mozilla/thimble.mozilla.org#1615]
The [data.GUI](https://github.com/dataarts/dat.gui) controller library makes it easy for users to adjust variables in a running program.  See http://workshop.chromeexperiments.com/examples/gui/#1--Basic-Usage for examples.

It would be great if we had some starter kits that were highly data driven, and could benefit from exposing a visual controller.  Some examples might include:

* simple game (there are lots of existing JS games you could use vs. making a new one) where you can control things like speed, gravity, etc.
* visualizations of data, where you can control distances, density, colours, etc.
* using effects on images (e.g., video stream with different colour or filter affects applied)

It would also be interesting to consider how we might expose the data.GUI controls in a "native" way within Thimble, so that anyone who needs this in a project can expose it easily.

**Comment by pranay414** [comment]
@humphd I would like to work on this, please tell me how to proceed

**Comment by gideonthomas** [comment]
I have recommended that @pranay414 probably tackle another "good first bug" issue first before getting into the starter kits.
