### ISSUE TITLE
Thimble and CSS: "Design in 4 Minutes" style Starter Kit

### ISSUE THREAD

**Issue by humphd** [mozilla/thimble.mozilla.org#1616]
[Design in 4 minutes](http://jgthms.com/web-design-in-4-minutes/) is a fantastic example of how you can teach by doing show and tell on the web.  It would be nice if we had a way to expose this to people who want to also teach various types of CSS, such that a learner can progress through different stages of a design process, learning as she goes.

A simple approach would be to build a starter kit that does something very similar to this example.  A more ambitious goal might be to create a framework for building a new starter kit that can do things like this, i.e., create an API for managing the show-and-tell nature of this kit.

**Comment by DorelBarbu** [comment]
Hello. I like very much to teach people in general. This seems like a good bug to me. How do you suggest we proceed?

**Comment by sanariaz154** [comment]
@humphd I want to work on this . Can you explain it further ?

**Comment by humphd** [comment]
I feel like this isn't a well scoped bug, and is going to leave you feeling frustrated. Despite the fact that I filed it, I don't have any more to say about what it should be about than what I wrote earlier.  It was suggested by a community member, and I filed it on his behalf.

I think I'm going to close it, and suggest that we get you working on something else, @sanariaz154.  There are other ones at https://github.com/mozilla/thimble.mozilla.org/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20label%3A%22good%20first%20bug%22%20-label%3A%22Assigned%20to%20Contributor%22 for you to consider.
