### ISSUE TITLE
Thimble and Mentorship: Explore using Together.js

### ISSUE THREAD

**Issue by humphd** [mozilla/thimble.mozilla.org#1619]
Mozilla previously created [Together.js](https://togetherjs.com/), which provides remote chat and multiple cursor/mouse-pointers in a single application.  Thimble users could benefit from this, by supporting one another in the same project.

Doing this well requires a number of things, including:
* figuring out the state of together.js, which is not actively maintained any longer.  It may need things to be fixed, see https://github.com/mozilla/togetherjs
* working on ways to sync state between Thimble's editor and the remote Thimble editor(s).  The user's mouse position and cursor are also dependent on which file is currently being viewed, scroll position, etc.  What about syncing file system data across machines (this could be done with webrtc)
* We've talked in the past about doing an experiment that would allow users to work across languages using Google's Translate API, or similar.  Some work has been started on this, see http://downloads.simonwex.com/TogetherJS-Local.mp4
* Eventually we'd probably want to revamp and customize the together.js UI so it feels more "native" to Thimble instead of being a floating window/widget.

There's lots to do here, but many small steps along the way, and a lot of fun to be had!

**Comment by jgmac1106** [comment]
This would be an amazing feature. As a stop gap I have always wanted either
a native discourse instance for thimble or a category on Mozilla Learning
just asking for help.

**Comment by jgmac1106** [comment]
NVM there already is a Thimble category, while I am hijacking this thread
about together.js I wonder if we could link to
https://forum.learning.mozilla.org/c/thimble in the left side bar.

**Comment by humphd** [comment]
@jgmac1106 I wonder if we should split this off into another bug, it's a valid and self-contained request.

**Comment by humphd** [comment]
Filed in #1620, if you want to add anything there, @jgmac1106

**Comment by Rajat-dhyani** [comment]
wow this feature is really interesting.... should i work on this? @humphd 
and also it would be great if you can guide me also on this one... 
Thanks

**Comment by humphd** [comment]
@Rajat-dhyani we're going to be filing a bunch of tickets related to this work, and yes, you'd be welcome to help with it.  This bug is probably going to get closed, and replaced with more specific work, so I'll wait to assign it.

**Comment by Rajat-dhyani** [comment]
okay sir @humphd it does looks like a lot of work so breaking it down into smaller modules... would be great.. please let me know if i could be of any help 
Thank you

**Comment by flukeout** [comment]
We are not using together.js anymore.
