### ISSUE TITLE
Add option to hide the Remix button in a published project.

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.mozilla.org#1623]
It would be turned on by default, but we would give the author the ability to turn it off.

We could drop the following toggle into the **Publish** dialog...

![image](https://cloud.githubusercontent.com/assets/25212/16968101/a6a9ea32-4dc1-11e6-8262-7c16353fd260.png)

In addition, if this is toggled for a project that is already published, we should detect the change and show the **Update Published Project** button.

...or

We automatically update the published project to reflect this change.

**Comment by humphd** [comment]
We'd probably want to modify https://github.com/mozilla/thimble.mozilla.org/blob/master/public/resources/remix/index.js somehow to not show the remix button in the page.  One way to do this might be to add a DOM element (`meta` tag?) that flags for this script that we don't want to the button to be visible, and the injected script would need to look for that DOM element and adjust accordingly at runtime.

**Comment by peiying16** [comment]
This sounds interesting. I would like to do it.

**Comment by humphd** [comment]
Great @peiying16, go for it!

**Comment by peiying16** [comment]
We can add the toggle by modifying the file which is located on thimble.mozilla.org\views\editor\publish.html
Can anyone tell me what the toggle do if it is on/off?

**Comment by gideonthomas** [comment]
I would like to scope this issue down a bit because completely implementing this feature will require changes to `publish.webmaker.org`.

@peiying16 I apologize for the delay in communicating this, but frankly my first recommendation would be to possibly choose another "good first bug" to work on because I am trying to think of ways in which we can reduce the scope of this issue so that your changes would only need to touch the Thimble repository, but I haven't been able to come up with a solution for this issue that would qualify this as a "good first bug".
I will chat with @humphd tomorrow about this bug and try to brainstorm some ideas on how we could scope down this issue so that it is easier to fix so if you are able to wait until then (knowing that the answer maybe that fixing this issue might end up not being a good first bug), feel free to do so.

**Comment by peiying16** [comment]
@gideonthomas Thanks for you response. I can wait.

**Comment by flukeout** [comment]
@gideonthomas @humphd The published projects table has a 'tags' column that we don't use at all, we could use the UI in the publish dialog to add/remove a special 'no-remix' tag to the project. Then we could just look for that tag in the remix button javascript code to hide/show it.

**Comment by flukeout** [comment]
We could also just add a link in the publish dialog that leads the the Wiki page that explains how to remove it.

**Comment by gideonthomas** [comment]
@flukeout I don't think we should use 'tags' to hack in remix metadata (especially because it complicates actually remixing the project). I'd rather just link to the wiki for now.

@humphd based on that, any thoughts AND does this still qualify as a good first bug?

**Comment by humphd** [comment]
Let's split this bug into a few pieces:

1. Alter the Publish server route to allow us sending a "don't include remix button" option when we publish
2. Add UI to thimble as discussed above to let users enable/disable remix button inclusion
3. Connect 2) and 1) in Thimble

I agree with @gideonthomas that this is probably a good 2nd or 3rd bug, but maybe not a good first bug.  @peiying16, it might make sense to do this after you've done something smaller for your first contribution.  Meanwhile, @gideonthomas could you file a bug in publish describing how to accomplish 1)?

**Comment by gideonthomas** [comment]
Filed: https://github.com/mozilla/publish.webmaker.org/issues/237

**Comment by Pomax** [comment]
On a preexisting note, we do already have a `readonly` flag that we use for goggles - any project for which that flag is flipped will not inject the remix code in the S3-published files, flipping it back restores the remix option on publish.  (https://github.com/mozilla/publish.webmaker.org/blob/b12fa017ca768a421afba0889370d957dce957c5/api/classes/publisher.js#L204-L212)

**Comment by peiying16** [comment]
I think it's too hard for me now. I give up.

**Comment by gideonthomas** [comment]
@peiying16 as @humphd this might not be a good first bug for now. But don't be discouraged. We have a [lot of good first bugs](https://github.com/mozilla/thimble.mozilla.org/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20label%3A%22good%20first%20bug%22%20-label%3A%22assigned%20to%20contributor%22) out of which, you might find something that interests you and you feel comfortable fixing.

**Comment by flukeout** [comment]
@peiying16 If you're still looking for a bug to try #1397 might be worth a shot. I think it's an important change that would make life easier for contributors.

**Comment by peiying16** [comment]
Thanks. I'm working on another issue.

**Comment by gideonthomas** [comment]
The publish part of this has completed. I'll add instructions here on how to implement the thimble part.

**Comment by apoorvasingh17** [comment]
@humphd Hi, can I take this up?

**Comment by ryanwarsaw** [comment]
@apoorvasingh17 Since you're already assigned to an issue, lets leave this open for someone else to work on, once you complete your previous issue you're more than welcome to take this one.

**Comment by flukeout** [comment]
Closing as it's not super important - time better spent elsewhere.
