### ISSUE TITLE
Garbled styling in narrow preview header bar.

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.mozilla.org#1624]
Wow...

![image](https://cloud.githubusercontent.com/assets/25212/21994428/7c2ea90e-dbd4-11e6-95ae-07efd111dc11.png)

**Steps to Reproduce**
* Add a tutorial to your project
* Start making the preview pane narrower until eventually, the layout breaks
* This is likely caused by the PREVIEW link in there

**Comment by gideonthomas** [comment]
@flukeout can this be a good first bug?

**Comment by flukeout** [comment]
Yeah, I'll check into how to fix this and and update the label along with some instructions.

**Comment by flukeout** [comment]
I think adding a ``white-space: nowrap`` rule to the ``.nav-container`` that contains that UI should do the trick.

**Comment by mfainshtein4** [comment]
I'd like to fix this bug, but I am having a hard time replicating it

**Comment by humphd** [comment]
@flukeout I agree with @mfainshtein4, this doesn't seem to be happening any more.  Can you give some STR or close?

**Comment by flukeout** [comment]
@mfainshtein4 @humphd It might be because you don't have a Tutorial in the project. The TUTORIAL nav item is what's taking up the extra room and breaking the layout for me. Please confirm. To add a tutorial, use the file menu in the FILES bar.

**Comment by humphd** [comment]
OK, that did it.

![tutorial-in-header-resize](https://cloud.githubusercontent.com/assets/427398/22986819/b898c8ee-f37a-11e6-9908-bf9fabfed08f.gif)

@mfainshtein4 I've assigned this to you.  Ask further questions you have in this bug.

**Comment by gideonthomas** [comment]
FIxed with: 8a72f62f62511078208836aede438c43f1d61615
