### ISSUE TITLE
Enhance Thimble homepage with a bigger gallery of starter projects.

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.mozilla.org#1625]
We've featured the same 6 projects since launch, and it feels stale. 

We need something new, and it should...

* Look awesome
* Allow us to quickly change the feature projects
* Allow us to specify more than 6 projects
* Allow users to search for projects they want

**How will we handle the thumbnail image?**
Currently we use images to represent each project, but I think we should think about actually loading each project into a tiny iframe, and maybe disabling JS within those projects. This would reduce the amount of work drastically when wanting to show a project.

Alternatively, we could also make sure that each published project that ends up in the gallery has a ``thumbnail.jpg`` image in the root folder and we can show that.

**Github hosted JSON?**
In the past, we've built some front-end react UI that is powered by a JSON file hosted on github pages. This meshes nicely with our thinking around maybe hosting starter projects in github as well.

I'll give some thought to the design and post updates here.

**Curriculum database search UI**
Here's some React UI I built to search & filer curriculum. We could repurpose aspects of this.

* https://flukeout.github.io/curriculum-search-react/

It doesn't filter the results in the demo, but that would be easy enough.

**Comment by flukeout** [comment]
cc @gideonthomas @humphd thoughts?

**Comment by flukeout** [comment]
Mofo is also messing heavily with Django - is that something we can use as the back-end for this?

**Comment by flukeout** [comment]
Also, in doing this we should address https://github.com/mozilla/thimble.mozilla.org/issues/1171

Make sure we add GA events.

**Comment by flukeout** [comment]
Some related mockups I found from previous work...

![image](https://cloud.githubusercontent.com/assets/25212/22000151/7e8e1284-dbf2-11e6-9bbe-7381d1f0644a.png)

![image](https://cloud.githubusercontent.com/assets/25212/22000157/8c459730-dbf2-11e6-861f-608241c1eb3b.png)

**Comment by flukeout** [comment]
Currently, our static gallery doesn't let you preview the published version of each of the starter projects, and we should allow that. It would give people a better sense of what they're getting into by seeing the finished product. Will address this in the gallery UX.

**Comment by khanh2003** [comment]
@flukeout IMO, I want to see what others have made first.

**Comment by ryanwarsaw** [comment]
We're better off staying with our current setup of using images as thumbnails. It's low risk and doesn't pose any kind of security risk, where as embedding content (even with Javascript disabled) that we didn't create and don't directly control, is a pretty risky endeavor.

**Comment by flukeout** [comment]
@ryanwarsaw 

Initially, we'll be curating what ends up in the homepage gallery, so I guess both thumbnails and iframes would be okay..

* We can manually make nice thumbnails
* None of our content will be risky for iframes

...however, if we move beyond that and try to include dynamic or newly remixed content, we will no longer have thumbnails to show (unless we find a way to generate them). We could ask users to include a thumbnail.jpg in the root of the folder, but I doubt that will work out well.

Codepen gets away with using iframes to display projects on their homepage, but I also figure they have a staff, community & features to moderate that stuff if it's inappropriate. It also makes animated content way more enticing.

I'm not really sure if we'll ever just randomly show people's published content, especially if we don't have a way to measure quality with things like likes / favs. A lot of the time when looking at the dashboard I built, the most recently published projects are all clones of one another since they're part of some group effort or classroom exercise. It's fun to look through, but I don't think it's that useful to see. Also, we limit our exposure and worry about kids using our stuff and their privacy etc. etc.

@khanh2003 you can see some of the projects people are making in this dashboard: https://thimble-dashboard-staging.herokuapp.com/

**Comment by ryanwarsaw** [comment]
@flukeout My only concern with that is once the content is curated, is it still editable? What prevents someone from modifying the project in a malicious way after the curation process has taken place?

**Comment by flukeout** [comment]
@ryanwarsaw If we curate by featuring people's published projects, then we can't really safeguard against that. Even with the thumbnail solution, we still run the risk of them changing the content, people would see that a click later.

One option could be for us to remix the project and feature our remix (but still give attribution to the original author?). That seems kind of lame though. Maybe we could just start kickstart the effort by featuring stuff we've created.

**Comment by jgmac1106** [comment]
> however, if we move beyond that and try to include dynamic or newly remixed content, we will no longer have thumbnails to show (unless we find a way to generate them). We could ask users to include a thumbnail.jpg in the root of the folder, but I doubt that will work out well.

Could be a lesson on social media cards in the header. Have a, "Do you want to submit to the gallery?"

...and they get taught how to add a card that is  used for the gallery with a learn more link to an MDN article on using social media cards and/or microformats as a more advanced lesson.

This does provide pathways of learning across all the properties but does add a gatekeeper to making the gallery. Though maybe thats a good thing. A little risk/reward for everyone.

**Comment by flukeout** [comment]
In discussing this a bit more with @gideonthomas I think we're leaning towards using a thumbnail image for the gallery instead of a live preview. For each project we display, we'll look for a ``thumbnail.png`` file in the root folder of the project. This will be used as the cover image.

It just gives us more options for keeping the thumbnails interesting and consistent.

For example, a project that lets you draw something on a web canvas will look boring as a preview because it will blank and scaled way down. A screen cap of someone's project that is larger and cropped will be much more interesting and memorable.

**Comment by flukeout** [comment]
Additionally, we've settled on hosting a JSON file in github somewhere that will act as the "back end" for the project links and meta-data. We will hand-pick projects that end up in the gallery and for the most part, will probably also be the authors, at least initially.

I'll look into the extra page weight of using something like react and we'll make a call of what tech to build this thing in.

**Comment by ryanwarsaw** [comment]
@flukeout Keep in mind if we settle on hosting a JSON file on Github we're going to have to implement a fall back plan in-case someone tries to view the gallery while Github is experiencing a service outage.

**Comment by humphd** [comment]
Hosting on Github doesn't necessarily mean we need to rely on them as such: we can add a build step that **downloads** all the things from a github repo onto the server when we deploy.

**Comment by ryanwarsaw** [comment]
👍

**Comment by flukeout** [comment]
Okay, I put together a little prototype. It's not fully functional but you can check it out to get a feel of what I'm getting at.

* https://flukeout.github.io/thimble-gallery/index.html

![image](https://cloud.githubusercontent.com/assets/25212/22356322/4ef41d02-e3e5-11e6-8191-f8b28878d0f9.png)

**Notes**
* View will start with 6 featured projects
* Below the search bar we will include the most popular tags from among the visible projects
* Clicking one of these tags, or clicking a tag on one of the visible projects will set that tag text as the keyword search, and will filter the projects

**Comment by flukeout** [comment]
The JSON structure for each item looks like this...

```
  {
    title: "Keep Calm and Carry On",
    thumbnail_url : "https://thimble.mozilla.org/img/thumbnail-keep-calm.png",
    url: "https://thimble.mozilla.org/en-US/projects/72/",
    description: "This is activity one, the first activity!",
    tags: ["css","html","color"]
  },
```

**Comment by hannahkane** [comment]
Nice work, @flukeout! Some questions / thoughts:
 * Does this address #1171, as per comment above? Just want to make sure we don't lose that.
 * I think we might want to consider adding an "Authors" field, but not if all of the authors will just be Mozilla. Maybe @chadsansing can weigh in on how many featured projects are likely to have community members as contributors.
 * The filters feel like overkill if we're limited to six items. Is the idea that there will eventually be many projects, but only six featured at a time? If so, how will we handle search results with more than six results?
 * Are we losing the links to teaching kits altogether? Would like @chadsansing's thoughts on that.
 * Links to projects from the images are broken. Is that a known issue?
 * Seems like search field searches tags, title, and description. Is that right? If so, I think that's good. :)
 * Not a huge priority, but might want to consider a synonym dictionary. Users might type "js" rather than javascript. (Can't think of any other examples based on current projects, so, again, not a high priority.)

**Comment by flukeout** [comment]
Hey @hannahkane, thanks for the feedback

* Yeah, we can address #1171 with the changes we're making in the gallery, good catch.
* I'll add an authors field, we can always remove it after. One of the concerns is if we add something, and then the original author (who isn't us) modifies or unpublishes a project, we will be in a bad place.
* Not limited to 6 items, the plan is to have more more more. We can start a list of stuff we can include.
* Will add a way & treatment for keeping the Teaching Kit links.
* Will fix links to previews.
* Correct, searches title, description & tags.
* Good idea about "js" for example - will look into that, or maybe we'll just have to tag projects with both in that case.

**Comment by hannahkane** [comment]
Cool. Thanks, @flukeout. Will search results with more than six items be paginated?

**Comment by flukeout** [comment]
I guess it depends on how many we have total. I think for a start, we can just show any that match the search criteria.

**Comment by khanh2003** [comment]
@flukeout Currently I can't.
Console messages:

```
less.js:13 Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.
g.doXHR @ less.js:13
less.js:13 rendered https://thimble-dashboard-staging.herokuapp.com/css/style.less successfully.
less.js:13 css for https://thimble-dashboard-staging.herokuapp.com/css/style.less generated in 313ms
less.js:13 less has finished. css generated in 313ms
https://thimble-dashboard-staging.herokuapp.com/latest?date=2017+01+28 Failed to load resource: the server responded with a status of 503 (Service Unavailable)
https://thimble-dashboard-staging.herokuapp.com/count-created?date=2017+01+28 Failed to load resource: the server responded with a status of 503 (Service Unavailable)
```

**Comment by flukeout** [comment]
You're right, same for me - I have to update the database credentials in the dashboard, they were changed recently.

**Comment by flukeout** [comment]
I've updated the JSON structure to include
* Author and link to author
* Link to teaching kit

```
  {
    title: "Keep Calm and Carry On",
    thumbnail_url : "https://thimble.mozilla.org/img/thumbnail-keep-calm.png",
    url: "https://thimble.mozilla.org/en-US/projects/72/",
    teaching_kit_url: "https://thimble.mozilla.org/en-US/projects/72/",
    description: "This is activity one, the first activity!",
    tags: ["css","html","color"],
    author: "mozilla",
    author_url : "https://learning.mozilla.org"
  },
```

**Comment by chadsansing** [comment]
A clarification question: this is for thimble.mozilla.org rather than learning.mozilla.org/activities, correct?

I think it's okay to lose lesson plans (e.g. https://mozilla.github.io/curriculum-final/make-your-first-webpage/session04-common-tags.html#overview) if we have great content with embedded tutorials. We would not want to feature a beginning project from us or a community member without a tutorial, in my opinion. I think the Thimble lessons have lesson plans, but not teaching kits, which would be more like module pages (e.g. https://learning.mozilla.org/en-US/activities/make-your-first-webpage/)

I can put together a shortlist of beginner activities this week. I'll add them here.

I think @hannahkane put those activities on thimble.mozilla.org using a Mozilla-flavored account - they do not come from mine, so I don't have the project URLs. Apologies!

**Comment by flukeout** [comment]
Yes this is for ``thimble.mozilla.org``. As far as the lesson plan, for the activities that have one, it will be linked at the bottom of the activity card as a "Teaching Kit", like this...

![image](https://cloud.githubusercontent.com/assets/25212/22434541/584b93be-e6d1-11e6-8797-44a391e63862.png)

``Lesson Plan`` sounds better though, should I change the label?

**Comment by chadsansing** [comment]
I like the idea, but we do have a problem with vocab and holding over terms that aren't clear any more. Maybe "Module" or "Curriculum Module" would work better? The current taxonomy I use in materials and at trainings is Module (replaces training kit; also like a "unit" of study --> Activity (lesson plan; also replaces a different understanding of teaching kit) --> Project (a Thimble project to remix; includes a tutorial; replaces "make").

**Comment by flukeout** [comment]
I guess out of those "Activity" would be the term we'd want to roll with? Since the Thimble page doesn't necessarily benefit from the wider mozilla curriculum framing, maybe we could call it "Teaching Activity" so that it's more clear?

**Comment by chadsansing** [comment]
We're featuring Thimble projects, though - correct? Why not "Project?" Not everything we might suggest for curation will have a teaching activity.

**Comment by chadsansing** [comment]
We could tag them as "for educators."

**Comment by flukeout** [comment]
Hey @chadsansing just to make sure we're on the same page, I'm referring to the label used on the button that links to the Teaching Kit for an activity...

![image](https://cloud.githubusercontent.com/assets/25212/22474705/854b3020-e791-11e6-87ad-d021bb57c95e.png)

**Comment by chadsansing** [comment]
Totally - "For educators" would let us use that box to link to a module, lesson plan, teaching kit - whatever. Use it by audience, rather than type of thing.

**Comment by flukeout** [comment]
Closing as it has landed and is on staging - bramble.mofostaging.net

**Comment by khanh2003** [comment]
@flukeout Good enough. Now we need *more* contents!
