### ISSUE TITLE
Your Projects List > Add link to project if already published.

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.mozilla.org#1626]
On the Your Projects list, let's indicate if a project has been published, and if so, provide a link to the published project.

**Comment by indranil-tiwary** [comment]
Hey I can do this.. but I am new here.. just need to know how contributing works. Shall I start working on it right away?

**Comment by humphd** [comment]
Fixing this would involve working in this file:

**Comment by flukeout** [comment]
@indranil-tiwary are you good to get started on this?

**Comment by gideonthomas** [comment]
@indranil-tiwary how are you doing on this bug? Let us know if you need any help!

**Comment by flukeout** [comment]
Could also possibly do this one at the same time: https://github.com/mozilla/thimble.mozilla.org/issues/1766

**Comment by flukeout** [comment]
I'm going to unassign this and put it back in the pool of available tickets.

**Comment by flukeout** [comment]
@kramsamujh If you're looking for more issues, this one also deals with the Projects list.

**Comment by kramsamujh** [comment]
I'm interested in working on this bug. Should i look into fixing [#1766](https://github.com/mozilla/thimble.mozilla.org/issues/1766) as I'm working on this bug as well?

**Comment by flukeout** [comment]
Hey @kramsamujh - sorry I built this one into an existing PR https://github.com/mozilla/thimble.mozilla.org/pull/1775

**Comment by flukeout** [comment]
#1766 is still good to go. Hey @gideonthomas can you review the #1175 PR so that @kramsamujh can work on top of that to add the Remix Link?

**Comment by kramsamujh** [comment]
@flukeout No problem. I'd be glad to work on [#1766](https://github.com/mozilla/thimble.mozilla.org/issues/1766) instead.
