### ISSUE TITLE
Allow Javascript editor setting isn't remembered

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.mozilla.org#1631]
If you disable javascript in the gear menu and refresh the browser, it's enabled. It should keep the setting it last had.

![image](https://cloud.githubusercontent.com/assets/25212/22001014/5179a8b2-dbf7-11e6-9f91-bbf1261ccbc2.png)

**Comment by humphd** [comment]
Managing state in the Bramble API client library happens here:

* https://github.com/mozilla/brackets/blob/master/src/bramble/client/StateManager.js
* https://github.com/mozilla/brackets/blob/master/src/bramble/client/main.js#L254
* https://github.com/mozilla/brackets/blob/master/src/bramble/client/main.js#L407 which is where we pass it to the editor when it initializes

The actual Bramble editor then receives this state here:

* https://github.com/mozilla/brackets/blob/master/src/extensions/default/bramble/main.js#L181

And we'd need to call the code to allow/disallow JS, which is done like this:

* https://github.com/mozilla/brackets/blob/master/src/extensions/default/bramble/lib/RemoteCommandHandler.js#L92-L99

**Comment by peiying16** [comment]
I would like to try fixing this bug for my first bug. : )

**Comment by gideonthomas** [comment]
@peiying16 sure thing, it's all yours!

This bug needs to be fixed in the Brackets repository.
Let us know if you need any further help or instructions (beyond what @humphd has provided above).

**Comment by peiying16** [comment]
Thank you. I am working on it.

**Comment by peiying16** [comment]
Hello, I still have problem to fix it.
1. I add a property which names allowJavaScript to stateManage
![property](https://cloud.githubusercontent.com/assets/25106861/22620658/75cc8478-eade-11e6-96f7-8bd8e38f37a1.PNG)

2. I also add the get and set codes on file https://github.com/mozilla/brackets/blob/master/src/bramble/client/main.js
![main1](https://cloud.githubusercontent.com/assets/25106861/22620663/adffaf6e-eade-11e6-994e-d1fc19099503.PNG)
![main2](https://cloud.githubusercontent.com/assets/25106861/22620664/af431d7a-eade-11e6-8c95-b3374f52682d.PNG)

3. When I debug it. It shows the allowJavaScript is undefinded
![init](https://cloud.githubusercontent.com/assets/25106861/22620678/fa740eb2-eade-11e6-9595-c9302284f81c.PNG)

I guest, there should be any function that links to the UI toggle to set the allowJavaScript  property to true/false when the toggle is switched. And there should be any function to set the toggle on/off when the page is loaded.
Can any one locate the two functions for me?

**Comment by humphd** [comment]
It should be `true` by default (i.e., you probably want to initialize it to `true`).

These two functions here are how Thimble will trigger the change in Brackets:

https://github.com/mozilla/brackets/blob/master/src/bramble/client/main.js#L889-L895

Probably in the callback for those, we should be updating the value you have in storage to be `true` or `false`.

**Comment by humphd** [comment]
Also, this code block here is where events (callbacks) come back from Brackets, which is where you'd want to do this I think:

https://github.com/mozilla/brackets/blob/master/src/bramble/client/main.js#L275-L302

**Comment by peiying16** [comment]
Thanks. It takes time.

**Comment by peiying16** [comment]
I think we should separate this issue into 2 pieces.
1. Add back-end support like this issues 
https://github.com/mozilla/brackets/pull/378

2. Modify thimble to change the UI when initial.

The back-end part has been done. 
When I turn off the toggle and refresh the page, I can get the false value. It means the get and set functions should be done.
![false](https://cloud.githubusercontent.com/assets/25106861/22815135/41c466a8-ef27-11e6-961a-7d57dfe38030.PNG)

**Comment by peiying16** [comment]
Fixed
https://github.com/mozilla/thimble.mozilla.org/pull/1725
https://github.com/mozilla/brackets/pull/584
