### ISSUE TITLE
Limit minimum size of the font in the editor.

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.mozilla.org#1632]
Seems like there's no limit to how small you can make it. Let's pick a sane number as the minimum limit...

![image](https://cloud.githubusercontent.com/assets/25212/22001060/901dd78c-dbf7-11e6-95d7-fecdc13849b4.png)

**Comment by humphd** [comment]
Probably the best way to do this is to add an `if` check in https://github.com/mozilla/brackets/blob/master/src/bramble/client/main.js#L797-L799 to see if `_state.fontSize` is at a certain limit, and just `return`'ing if so.

**Comment by Abykin** [comment]
@flukeout @humphd, I'd like to work on this bug.

**Comment by flukeout** [comment]
Sounds good @Abykin - let me know if you need any help. Might as well also give it a maximum font-size. Let me know once you've got some values picked out for those.

**Comment by Abykin** [comment]
@flukeout I found where the values are being set : brackets/src/view/ViewCommandHandlers.js.
There is MIN_FONT_SIZE which is currently 1, and MAX_FONT_SIZE set to 72. I think setting MIN to 6 or 8 should be a good stopping point. Let me know which value you like more.

This is what a minimum font of 6 looks like
![min_font_6](https://cloud.githubusercontent.com/assets/10553879/22601885/ff004606-ea0e-11e6-8cca-0764a69fc99b.PNG)

This is what a minimum font of 8 looks like
![min_font_8](https://cloud.githubusercontent.com/assets/10553879/22601977/5b352b3a-ea0f-11e6-954a-ec8b37db5777.PNG)

**Comment by humphd** [comment]
@flukeout btw, those are in `px` units.  What do you think the two should be set to, so that @Abykin can continue.

**Comment by gideonthomas** [comment]
@flukeout is on PTO today. @Abykin since you are only waiting on the limit values, I suggest opening a PR on the brackets repo and we can get @flukeout to look at it there.

@humphd any thoughts about doing this in the Brackets core code vs. our client api?

**Comment by flukeout** [comment]
Hi @Abykin - yeah, please go ahead and start a PR and I'll have a look. Just from changing the font size via dev tools, a range of ``8px to 32px`` seems to work well.

**Comment by Abykin** [comment]
@flukeout PR created here [https://github.com/mozilla/brackets/pull/572] thanks

**Comment by flukeout** [comment]
Fixed in https://github.com/mozilla/brackets/pull/572
