### ISSUE TITLE
Make "menu appears" transition consistent.

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.mozilla.org#1634]
The publish menu and the gear menu have a different style of appearing. One fades in while the other appears suddenly. Let's make the Publish dialog appear instantly like the gear menu.

**Comment by humphd** [comment]
The fade-in on the Publish dialog happens here: https://github.com/mozilla/thimble.mozilla.org/blob/fa3dde088dc016a562520e62a9df1f5558ba8f70/public/editor/scripts/editor/js/fc/bramble-ui-bridge.js#L307

**Comment by humphd** [comment]
I'll work on this.  I'm going to fix it and write it up as an example.

**Comment by humphd** [comment]
Blog post is up at: http://blog.humphd.org/fixing-a-bug-in-mozilla-thimble/.  I'll do the actual fix later with my students in class, to show them.

**Comment by humphd** [comment]
I have the fix for this, but I want to show my students how to do a rebase/squash using it as an example.  I'll do that on Tues.

**Comment by Th30** [comment]
I'll push a fix for this tonight @humphd

**Comment by humphd** [comment]
Awesome, thanks!
