### ISSUE TITLE
Make items in user dropdown menu easier to click.

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.mozilla.org#1635]
The items in the dropdown menus only work if you click the text of the item, and not the entire length and height of the highlighted item when you hover.

This is because each item is a...

```
<li>
  <a>Item Label</a>
</li>
```

...and the padding around the item is applied to the ``<li>`` which isn't clickable.

![image](https://cloud.githubusercontent.com/assets/25212/22001231/76a7f2e6-dbf8-11e6-8bd3-173a18f23903.png)

To fix these we either...

* Add the click listener to the ``<li>`` item, or..
* Change the CSS styling so that the ``<a>`` item gets the padding and then makes up the entire clickable area.

**Comment by flukeout** [comment]
This is probably the same issue that is causing #1534

**Comment by raygervais** [comment]
@flukeout @humphd, I'd like to fix this bug. Can you point me to the coding conventions & contributions document?

**Comment by flukeout** [comment]
@raygervais I'm not sure we have a coding conventions doc. Do we @gideonthomas 

As far as contributing, the first step would be to get your dev environment up and running. Follow the steps in the readme here... https://github.com/mozilla/thimble.mozilla.org

Then, you're free to get rolling and ask us for help if you get stuck.

**Comment by gideonthomas** [comment]
No coding conventions document yet since we don't specifically follow a style guide. @raygervais, for now, I would try to follow the conventions that you see in the file you are working with. If there are any issues with coding conventions, we will point them out in your PR so I wouldn't worry about them at the moment.

**Comment by raygervais** [comment]
@gideonthomas thank you for the advice. @flukeout, I've attached an example of your second suggested option to fix this issue, and believe it is the most optimal way as well. You'll see that I used Firefox's highlight tool to ensure that it would not affect any other element on the page. In doing so, I also reduced surrounding `<li>` element's padding to 0. I also added `display:block` to retain the original styling of the element.
![css_thimble_fix_1635](https://cloud.githubusercontent.com/assets/14265337/22576215/493843c2-e988-11e6-9166-0e0739f47b7b.png)

If you are satisfied with this, I'd be happy to start a PR right away.

**Comment by flukeout** [comment]
Overall, this is great. Here are some thoughts.

You can remove the height from the <li> element if it has one, and just use the padding in the <a> element to give the menu item its height.

That way you can drop the ``height`` declaration from the <a>. Additionally, block elements always span 100% of the width of their parent. So you don't need to set a ``width`` on it either.

Give that a try and please go ahead with starting the PR. Looking forward.
