### ISSUE TITLE
Make the file-tray have a greater minimum width when the "expand" icon is clicked.

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.mozilla.org#1636]
You can close the file tray fully by resizing the editor. Then you can click the little arrow to expand it again. However, it's super small and not usable until you manually resize it again. See below..

![tray](https://cloud.githubusercontent.com/assets/25212/22001788/1c18f81c-dbfc-11e6-9348-94902debd688.gif)

Let's add a minimum file tray width when clicking the expand icon.

**Comment by humphd** [comment]
The code for this is in Bramble, see https://github.com/mozilla/brackets/blob/master/src/extensions/default/bramble/lib/RemoteCommandHandler.js#L113-L118.  There is code in https://github.com/mozilla/brackets/blob/master/src/project/SidebarView.js to do resizing, which we could call after we show it.

**Comment by sgupta7857** [comment]
hey, I would like to work on this bug. thanks

**Comment by flukeout** [comment]
Sounds good @sgupta7857 - let me know if you're not able to reproduce the behavior in the gif.

**Comment by aayushsanghavi** [comment]
@flukeout what is the status of this issue? If there hasn't been any progress I'd like to work on it.

**Comment by humphd** [comment]
@sgupta7857 can you let @aayushsanghavi know your status on this?  If you're not working on it still, let's hand it off.  Otherwise, please post a PR soon.  Thanks.

**Comment by flukeout** [comment]
@sgupta7857's PR is already filed in the Brackets repo: https://github.com/mozilla/brackets/pull/613

**Comment by sgupta7857** [comment]
@aayushsanghavi @humphd I already have a Pull Request open.
I am just waiting for review check by @flukeout

**Comment by Pomax** [comment]
@sgupta7857 can you crosslink your PR by putting a `fixes #1636` in that PR's  comment?

**Comment by sgupta7857** [comment]
fixes #1636

**Comment by humphd** [comment]
This landed, closing.
