### ISSUE TITLE
Always display a Tutorial in "Desktop" mode.

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.mozilla.org#1637]
Currently, if the preview is set to Mobile view and you click to view the tutorial, it remains in the mobile view. This makes it hard to use...

![image](https://cloud.githubusercontent.com/assets/25212/22002229/1a51df3c-dbff-11e6-88bf-ff6c426700ff.png)

Let's always show the Tutorial file in desktop view.

This means that if we're previewing the ``index.html`` page in the mobile view, we need to return the preview to mobile after showing the tutorial.

**Comment by humphd** [comment]
This will likely involve changes to https://github.com/mozilla/brackets/blob/master/src/extensions/default/bramble/lib/Tutorial.js and https://github.com/mozilla/brackets/blob/master/src/extensions/default/bramble/lib/UI.js#L207

**Comment by rkgupta21** [comment]
I am interested in working on the issue.

**Comment by humphd** [comment]
Great, @rkgupta21, it's yours.

**Comment by gideonthomas** [comment]
@rkgupta21 how are you doing with this bug? Let us know if you need any guidance.

**Comment by Rajat-dhyani** [comment]
hey @rkgupta21 if you are not working on this...can i try to fix this issue ?

**Comment by gideonthomas** [comment]
@humphd can we re-assign this issue?

**Comment by humphd** [comment]
@rkgupta21 can you let us know if you're working on this still?

**Comment by rkgupta21** [comment]
@humphd I was actually working on some other issue. You can reassign it.

**Comment by humphd** [comment]
Thanks @rkgupta21, that's helpful to know.  @Rajat-dhyani go for it if you want this one.

**Comment by Rajat-dhyani** [comment]
okay thanks for informing @rkgupta21 ... i am taking this over 👍

**Comment by Rajat-dhyani** [comment]
please review this PR : https://github.com/mozilla/thimble.mozilla.org/pull/1807

**Comment by Pomax** [comment]
@Rajat-dhyani can you update your PR so that the PR comment says `fixes #1637` somewhere? That makes github crosslink the two issues, flagging that your PR fixes this specific issue.

**Comment by Rajat-dhyani** [comment]
@Pomax Done :) 👍
