### ISSUE TITLE
Thimble and Aframe: Explore adding support for custom tag autocompletion

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.mozilla.org#1638]
If we integrate Aframe into Thimble, we'll want to add support for the various custom tags that it uses to create 3D scenes.

For example, here's the [list of primitives](https://github.com/aframevr/aframe/tree/master/docs/primitives)

Let's explore if this is possible and how.

**Comment by humphd** [comment]
This can be done with an extension, and there are a bunch of examples we can study, see https://brackets-registry.aboutweb.com/ and search for "autocomplete".  We can include extra extensions by following info here: https://github.com/mozilla/brackets#optional-extension-loading
