### ISSUE TITLE
Mobile - Thimble Remix Button On top of Google Cardboard Button

### ISSUE THREAD

**Issue by jordanbudi** [mozilla/thimble.mozilla.org#1639]
Made a project implementing A-Frame:
https://thimbleprojects.org/jbudisantoso/186422/

When visiting on my mobile device (iPhone 6S Plus), the Thimble Remix icon overlaps the Google Cardboard icon which prevents me from clicking it.

See bottom right of this image:
![img_7984](https://cloud.githubusercontent.com/assets/12487749/22075142/cd04c69c-dd78-11e6-9289-59ee68a14a17.PNG)

**Comment by flukeout** [comment]
Related to #1623 

@jordanbudi you can add some CSS to your project to hide the remix button, let me know if you want help with that.

**Comment by jordanbudi** [comment]
@flukeout yes that would be super helpful!

**Comment by flukeout** [comment]
@jordanbudi try out the instructions here:

https://github.com/mozilla/thimble.mozilla.org/wiki/CSS-for-Hiding-the-Remix-Button-on-Published-Projects

Let me know if that helps!

**Comment by jordanbudi** [comment]
@flukeout works like a charm. Thank you!

**Comment by flukeout** [comment]
Glad it helped. I'll close this issue since we're aware of the Remix button causing problems already.
