### ISSUE TITLE
Thimble + Aframe: Add entity property editor popup

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.mozilla.org#1640]
One way to make editing aframe projects would be to provide some custom UI for changing some common attributes (scale, size, rotation) of simple shapes. We already do something like this with the colorpicker.

Can we use the same expandable section to add UI specific to aframe components?

**Comment by flukeout** [comment]
For reference here's the special colorpicker UI you can access with Command + E when a hex value is being edited.

![image](https://cloud.githubusercontent.com/assets/25212/22081520/baa858ce-dd78-11e6-9ae4-6200b5cf3f33.png)

**Comment by humphd** [comment]
The `ColorEditor` is an extension that we can copy, and it lives here: https://github.com/mozilla/brackets/tree/master/src/extensions/default/InlineColorEditor

**Comment by hkirat** [comment]
Hey @flukeout 
I would like to work on this.
I would like to start with basic properties like rotation, translation and scaling. We can extend to other properties later.

**Comment by flukeout** [comment]
Great! Looking forward to it - are you OK juggling multiple issues at once or would you prefer to focus on one at a time?

What kind of interface would work well for these properties do you think? Could we expose all three properties at once in the QuickEdit UI? Or do you want to tackle them one at a time?

**Comment by humphd** [comment]
@hkirat I'm glad to see you grabbing a bigger piece of work to do with us, you're clearly capable.  A few thoughts about this.  First, there are a number of inline editor providers that exist, and you can likely study/steal code from, for example:

* https://github.com/mozilla/brackets/tree/master/src/extensions/default/InlineTimingFunctionEditor
* https://github.com/mozilla/brackets/blob/master/src/editor/CSSInlineEditor.js
* https://github.com/mozilla/brackets/blob/master/src/extensions/default/JavaScriptQuickEdit/main.js
* https://github.com/mozilla/brackets/tree/master/src/extensions/samples/InlineImageViewer
* etc, there are lots, do a search for `EditorManager.registerInlineEditProvider` in Brackets.

I'd also suggest looking at thirdparty extensions from https://brackets-registry.aboutweb.com/, since there are bound to be others that could help guide you here.  We may also want to extend Brackets to understand all the entities that a-frame adds, which could happen in another bug.

This will be exciting to see happen!

**Comment by hkirat** [comment]
@flukeout I'm totally fine with working on more than one issues.
Right now I was thinking of exposing all three properties at the same time. I'll build a prototype and we can see how it looks and decide accordingly.

@humphd Thank you for the resources.
Could you please elaborate why your last point. 
This line -> understanding the entities that a-frame adds? 
Do you mean the type of entities?

**Comment by humphd** [comment]
Consider the following:

```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Hello, World! • A-Frame</title>
    <meta name="description" content="Hello, World! • A-Frame">
    <script src="../../../dist/aframe-master.js"></script>
  </head>
  <body>
    <a-scene>

      <a-sphere position="0 1.25 -1" radius="1.25" color="#EF2D5E"></a-sphere>
      <a-box position="-1 0.5 1" rotation="0 45 0" width="1" height="1" depth="1"  color="#4CC3D9"></a-box>
      <a-cylinder position="1 0.75 1" radius="0.5" height="1.5" color="#FFC65D"></a-cylinder>
      <a-plane rotation="-90 0 0" width="4" height="4" color="#7BC8A4"></a-plane>

      <a-sky color="#ECECEC"></a-sky>
      <a-entity position="0 0 3.8">
        <a-camera></a-camera>
      </a-entity>
    </a-scene>
  </body>
</html>
```

I mean having Brackets be aware of things like `<a-entity>`, `<a-camera>`, etc.  Things like having syntax highlighting work properly, adding them to HTML autocomplete, etc.

**Comment by hkirat** [comment]
Right. Got it.
I'm starting with making the modifier for three primitives right now, cube, sphere and cylinder. This can be later extended to other primitives using regex.
I'm taking [this](https://github.com/mozilla/brackets/tree/master/src/extensions/default/InlineColorEditor) as a reference.

**Comment by flukeout** [comment]
👍

**Comment by hkirat** [comment]
A little help.
I am trying to work on this, however the changes I make in https://github.com/mozilla/brackets/tree/master/src/extensions/ don't seem to show in the browser.

I've tried running 
```
npm run build
```
and then restarting the server.
Is this the right file to make the change?
Have I messed up the installation process?

**Comment by hkirat** [comment]
Nevermind, Just had to disable cache in chrome

**Comment by humphd** [comment]
You only need to run `npm run build` when you touch `src/bramble/client/*`, so it shouldn't be necessary here.  I would suspect cache is your issue...and reading more closely above, I see you came to the same conclusion :)

**Comment by hkirat** [comment]
Hi
I have made the following in the last two days.
Right now you can edit all properties like position, scale etc (all that are of the form [number number number].
![vid](https://im3.ezgif.com/tmp/ezgif-3-b4f550af88.gif)

Is this approach right?

**Comment by humphd** [comment]
Very cool!  I think the preferred order here is: make it work, make it right, make it fast, make it pretty.  What it should look like in the end is one thing, but that you are doing it at all is the right first step.

This reminded me a bit of http://workshop.chromeexperiments.com/examples/gui/#1--Basic-Usage, have you ever played with it?

**Comment by hkirat** [comment]
Great. I'll finish it up and apply for a P.R with the first draft.
We can continue from there on.

Also the experiment above looks awesome. The right integration of aframe with thimble can give many more experiences like this one.

**Comment by flukeout** [comment]
Yeah, this is super cool - awesome progress and I'm happy we're exploring the Quick Edit feature in general too!

**Comment by humphd** [comment]
@hkirat what happened to your cool animated gif of this in action?  It was really cool.

**Comment by flukeout** [comment]
It's a few comments above - that one?

**Comment by hkirat** [comment]
Hey @humphd .. Sorry for that
Uploaded it on the wrong platform. The link died within a day. 

Edited it. Its back up.

I've optimised the code enough and should file for a P.R. in an hour or so.

**Comment by humphd** [comment]
Yeah, it wasn't showing for me, back now.  Must have been a glitch in the matrix.

**Comment by flukeout** [comment]
OK @hkirat - will test again!

**Comment by flukeout** [comment]
This is.. done! Woo
