### ISSUE TITLE
Create more Quick Edit UIs for different tags and properties.

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.mozilla.org#1642]
We have a Quick Edit UI for choosing a color...

![image](https://cloud.githubusercontent.com/assets/25212/22081603/084866e6-dd79-11e6-802c-588ab2c3a011.png)

...can we investigate and see how hard it would be to add other types of Quick Edit UIs? For example, we could add one to make gradients. Or, we could make one for changing box shadows, border-radius, or border properties.

**Comment by humphd** [comment]
The gradient one already exists: https://github.com/peterflynn/brackets-gradient-editor and https://github.com/mozilla/brackets/tree/master/src/extensions/default/InlineTimingFunctionEditor, so we could just include that if you like.  There's an ImageViewer too https://github.com/mozilla/brackets/tree/master/src/extensions/samples/InlineImageViewer

We could make ones for different tasks, yes.  It's a matter of following the same template as this, the ColorPicker, etc.

**Comment by flukeout** [comment]
Closing - will file detailed bugs describing what kind of editors we want.
