### ISSUE TITLE
Thimble + Aframe: Build a scene based on project markup.

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.mozilla.org#1644]
Zany idea - what if - when you are editing an html page, you could hit a button that generates some kind of 3D sculpture or visualization based on the contents of that page? We could interpret the HTML markup in any sort of way...

* We could build a 3d VR graph of the types and numbers of elements.
* Build a 3d representation of the page somehow
* Build a giant jenga tower where all of the elements are represented as shapes and are stacked together on top of one another

...etc.

The real trick would be to have a method to dynamically generate and display an aframe scene based on some simple parameters.

**Comment by Pomax** [comment]
Sounds like the old 3D view in developer tools, https://developer.mozilla.org/en/docs/Tools/3D_View, although that was removed from Firefox in v47

**Comment by flukeout** [comment]
Aaaand closing.
