### ISSUE TITLE
Thimble + Aframe: Comb through Aframe issues and find dev workflow painpoints

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.mozilla.org#1645]
Apparently the repo is full of good issues that could shed light on what we could do in Thimble to make authoring scenes easier:

* https://github.com/aframevr/aframe/issues

Would be a good task to dig through here and see if we can brainstorm some solutions to implement in Thimble.

**Comment by Blackweda** [comment]
how would this 'bug' be considered successfully complete?

**Comment by humphd** [comment]
To be honest, this bug needs to be closed.  It's not well scoped, which is exactly why you're asking this question.
