### ISSUE TITLE
When adding an HTML file to a project via the plus button to a project with no HTML files, call it "index.html" instead of "index-1.html"

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.mozilla.org#1651]
Currently, we have a convention that increments the name of the added HTML file, which is nice. Since projects start with "index.html", the next HTML file we add is called "index-2.html" which makes sense. However, if we delete all of the HTML files and then add a new one, it's called "index-1.html" - which makes sense given our convention.

However, this means a published project won't load unless that is changed to "index.html", so.. let's just call the first added HTML file (when none are present) "index.html" 

![index](https://cloud.githubusercontent.com/assets/25212/22216124/aae3729c-e152-11e6-9ae0-fc51d2677472.gif)

**Comment by Rajat-dhyani** [comment]
Hello sir @flukeout , 
I think i can fix this error could you please locate me the file for fixing it ?

**Comment by humphd** [comment]
Fixing this will involve similar code to https://github.com/mozilla/brackets/commit/64b7f12d5d8fa344c9be59ebcb28176d71e20466

**Comment by Rajat-dhyani** [comment]
Hello sir @humphd,
 i was able to navigate the code and reached to this file 
https://github.com/mozilla/thimble.mozilla.org/blob/master/public/editor/scripts/editor/js/fc/bramble-menus.js

but there is call to analytics.event("AddHTMLFile");

and here is code for calling the file at the top of the document

var analytics = require("analytics");

but i am could not locate this file. Please Help !

**Comment by humphd** [comment]
It comes from a node module, https://github.com/mozilla/thimble.mozilla.org/blob/master/Gruntfile.js#L49

**Comment by Rajat-dhyani** [comment]
please review this pull request : https://github.com/mozilla/brackets/pull/616

**Comment by gideonthomas** [comment]
Fixed with mozilla/brackets@6a92bc115240419092518de89f678beb0d6eb50f
