### ISSUE TITLE
update the README.md with mattermost information

### ISSUE THREAD

**Issue by Pomax** [mozilla/thimble.mozilla.org#1653]
We should add a section on how to do real-time collaboration with us on this project, since we don't use IRC for this anymore, but we're currently using mattermost.

**Comment by Pomax** [comment]
deadline: before Friday January 27

**Comment by Rajat-dhyani** [comment]
Hello sir @Pomax ,
Can you please share the link to mattermost account so that i can add that section to Readme.md ?

**Comment by ryanwarsaw** [comment]
@Rajat-dhyani Our Mattermost instance can be located at: http://chat.mozillafoundation.org, and people can download the official client / learn more here: https://about.mattermost.com.

**Comment by Rajat-dhyani** [comment]
@Pomax @ryanwarsaw  sir,
please check my PR and have it reviewed.

**Comment by ryanwarsaw** [comment]
Related #1324

**Comment by Pomax** [comment]
https://github.com/mozilla/thimble.mozilla.org/pull/1672 landed.
