### ISSUE TITLE
Thimble + IoT: Investigate Thimble + FlyWeb integration

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.mozilla.org#1656]
Mozilla has a project called Flyweb, described here https://wiki.mozilla.org/FlyWeb. I'm going to read more about it, but some of the implementations I've seen allow phones running firefox to easily connect to Flyweb enabled devices and control them. 

The demo I saw allows mobile devices running firefox to connect to another machine via the FlyWeb protocol and act as game controllers.

Maybe there are ways for a Thimble project to run in firefox and run as a controllable FlyWeb device, or some other arrangement. I'm going to talk to the FlyWeb folks in the next few days, but if anyone here has any info or thoughts, drop it in.

**Comment by flukeout** [comment]
Looked into this a little bit. One of the drawbacks is that it's an experimental spec and is only available on the Nightly version of the Android and Desktop version of firefox, behind a feature flag. 

I'm going to attempt to get this running between a phone and a desktop browser (or maybe two desktop browsers if possible) and see what happens.

**Comment by flukeout** [comment]
Okay, I played around with this a little bit, here's what I've found...

**Setup**
* To run Flyweb, you need to run Firefox Developer Edition on the desktop
* To connect to it using a mobile device, you need to run Firefox Aurora or Nightly for Android
* For each, you need to turn on the flyweb feature flag in ``about:config``

Once this is enabled, you get to use the Flyweb API directly in your JS, since it's a part of the browser. I was able to get a simple mobile device remote control up and running that let me change the background color of my published project.

**How it works**
* You basically get to write your own web server a client-side javascript file
* When the phone connects, you serve it whatever file you want (like remote.html) for example, and then it gets rendered in the mobile device
* Then, from the phone, you can use a ``fetch("something")`` method to talk to the server
* On the server, you have to figure out when a fetch comes in, and then fire a method in your javascript that does something
* The device and browser need to be on the same network

**Drawbacks**
* You can only do this with the specific browsers that are listed above
* When rapidly refreshing the Thimble preview (or a page running Flyweb in general) the browser crashes (might get resolved in future versions?)
* The path to the files in your project is different when you're editing and when the project is published, so it gets tricky writing something that will work both when in-progress and published
  * I ended up just trying to make it work for the published project only, not even sure if I can get access to the files before the project is live

**Thoughts**
* We could bake some of this into Thimble and then expose an abstraction layer overtop of it, that might make it easier to use, especially to resolve the difference between local and published projects.
* The device and browser limitations seem pretty heavy
* Both devices need to be on the same network for this to work

**Comment by flukeout** [comment]
@humphd @gideonthomas So in short, flyweb creates a little server via client-side javascript, then serves files to the devices that connect to it.

This works fine for published projects, as all the files are easily accessible. Is there any way to do this for an unpublished project. How are files referenced internally? 

There is this url structure ``https://mozillathimblelivepreview.net/bramble/production/dist/other.html`` - but it doesn't seem like I can use this URL to reference a project file from within some JS running on a page I'm editing. 

Is there a way to directly access files in a project while editing? Let me know if you have questions or want some clarification. Cheers.

**Comment by Pomax** [comment]
is FlyWeb still being actively worked on?

**Comment by flukeout** [comment]
It's being worked on, although right now they are focusing more on the device to browser use case as opposed to the browser to browser one I was playing around with.

**Comment by gideonthomas** [comment]
Not in scope anymore
