### ISSUE TITLE
Thimble + IoT: Investigate Thimble + Sensorweb collaboration

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.mozilla.org#1657]
The mozilla connected devices has been working on the SensorWeb project, and as part of that have created a prototype of their own [hardware board ](https://connected.mozilla.org/2016/12/22/project-sensorweb-dev-boards-arrive-today/). We should look into this more to see if there is a way to adapt Thimble to be an easy to use coding/ dev environment for this hardware. I think it will be available to a wider audience end of Q1.

**Comment by gideonthomas** [comment]
Not in scope anymore
