### ISSUE TITLE
Figure out setup on Windows with Hypervisor already in use

### ISSUE THREAD

**Issue by gideonthomas** [mozilla/thimble.mozilla.org#1659]
This is a follow-up from the Vagrant patch to make setup easier on Windows. Apparently, if you already have software that uses hypervisor on Windows (for e.g. VMWare, or Docker for Windows not Docker Toolbox) you cannot install another one (in this case, VirtualBox). This makes it impossible to follow our setup instructions. This is a problem only on Windows Professional and Enterprise versions since Hyper-V is not available on other versions of Windows.

@cadecairos can you confirm/correct the details specified here?

**Comment by cadecairos** [comment]
This is accurate. The virtualization programs all try to get exclusive access to your hypervisor, so having one enabled locks out the others. There's no simple workaround either - to enable VirtualBox with HyperV already installed you need to create a secondary boot profile that disables HyperV on boot. (no thank you)

Vagrant claims to be able to use HyperV as a provider, but there's a noticable lack of "boxes" in the atlas that support HyperV as a provider. There's also mention of poor networking support - somthing about needintg to manually create a network bridge for your box. (ouch)

Personally, Docker is the ideal solution for any platform that has first class docker support.

**Comment by cadecairos** [comment]
@gideonthomas Is there anything actionable we can get out of this issue, or should we close it out?

**Comment by gideonthomas** [comment]
I think we can close. Will reopen if we decide to stick to the vagrant setup.
