### ISSUE TITLE
Thimble + Mobile : Can we simulate touch events in the preview?

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.mozilla.org#1660]
It would be great to have a mode where we can simulate touch gestures in the preview. Browser dev tools allow this, but maybe it's harder to do from within a web page.

Hammer.js has some nice mouse-to-touch examples on their site: http://hammerjs.github.io/

This little game simulates it in a cool way too: http://codepen.io/Gthibaud/pen/zNwgmZ

**Comment by flukeout** [comment]
Could also be handled with a starter project maybe. We'd just need to find one that allows people to simulate those events with a mouse (and mouse + modifier key for two-finger touch). Hammer.js has that running on their homepage, but I've noticed that, at least for me, the pinch and rotate actions don't actually work.

**Comment by flukeout** [comment]
To elaborate a bit more on this, I was thinking about a mode that would let you use your mouse pointer in the preview as a 'touch' input. So if touch mode is on, when you used your mouse to click, it would instead fire a 'touch' event, and when you moved it, it would trigger 'touchmove', 'touchend' events etc.

Would this be possible?

**Comment by Rajat-dhyani** [comment]
so will there be a separate icon for touch sensitive layout that triggers​ the event or the existing mobile view mode will have this feature?
 i  personally think that the existing mobile view should have this feature. i will try my hands on this. if that is okay?  @flukeout

**Comment by humphd** [comment]
https://github.com/hammerjs/touchemulator has code for this.  We'd probably want to do something similar to how the Inspector works now (e.g., button in Thimble, you press it, it goes into that mode until you press again).  In this case we'd convert clicks to touch events.

**Comment by Rajat-dhyani** [comment]
@humphd @flukeout i have successfully added the `touchemulator.js` to brackets and was able to simulate touch responses. 
But as you can see i could not get the touch emulator to work on **only** in the `iframe-browser` it is taking window as an argument and is applying the touch to whole window i tried changing it to `iframe-browser` but could not really get this part.
If anyone of you could guide me in right direction that would be great.
Thanks
![ice_video_20170319-012539](https://cloud.githubusercontent.com/assets/17648963/24075634/473cb014-0c45-11e7-80e7-1de92cdeb8cd.gif)

**Comment by humphd** [comment]
The preview `iframe` gets a bunch of scripts injected into it when we load the user's page, see https://github.com/mozilla/brackets/blob/master/src/extensions/default/bramble/lib/PostMessageTransport.js#L191-L208.  We could inject some code for what you're doing there as well.

You could likely do something similar to how the `MouseManager` works.  There are two parts to it:

* https://github.com/mozilla/brackets/blob/master/src/extensions/default/bramble/lib/MouseManagerRemote.js which is what lives in the preview iframe
* https://github.com/mozilla/brackets/blob/master/src/extensions/default/bramble/lib/MouseManager.js the part at that lives in the editor and talks to the rest of Brackets

If you look at what we do with the inspector and the mouse, you'd see a similar pattern to what you want to do.

**Comment by flukeout** [comment]
We have decided not to pursue this feature.
