### ISSUE TITLE
Indicate when a project is saved.

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.mozilla.org#1668]
Our current saving UX shows a brief "Saving..." message near the title of the project in the header. This is a nice feature, but it's pretty subtle and hard to notice. I often find myself wondering if my files were truly saved, especially since sometimes the indicator doesn't show up at all as filed in #1667

I propose an update to this solution. Each project you're working on in the editor only really exists in two states...

* Saving after detecting changes
* Saved after the changes are pushed to the DB

So, let's always indicate the state. When the project in the editor matches what's in the DB, we show "Saved" next to the title, and when it's saving, we show "Saving..." as we do now.

**Comment by naperkovskiy** [comment]
I'd like to try and fix that issue

**Comment by flukeout** [comment]
Sounds good @naperkovskiy - let me know if you want any clarification or additional UX details.

**Comment by gideonthomas** [comment]
@flukeout are you missing a state?
Shouldn't it be:
- Saving (to IndexedDB) after detecting changes
- Saved (to IndexedDB) but not to the main database
- Save to the main database

**Comment by humphd** [comment]
Saving to indexeddb is so fast, and so frequent, I don't think it's useful to add it.  You'll find that the "Saving...Saved" stuff will flash constantly.

**Comment by flukeout** [comment]
Agreed, it's also not very interesting to know about since it pretty much always does it quickly & successfully. The key info is wether the changes are saved fully 'to the cloud'.

**Comment by gideonthomas** [comment]
Then I would be careful with the copy we use for the states if we **always** show a saving indicator since in that case, there are still three states, which are:
- Not saved to cloud (saving is happening locally but it does not match what's on the cloud and there is no network activity)
- Currently saving to cloud (network activity is there and it is pushing files locally to the cloud to update the cloud's state to match the local state)
- Saved to cloud (no network activity, what is on the cloud matches what is there locally)

**Comment by gideonthomas** [comment]
@naperkovskiy while we're discussing the copy here, I don't think it should block you from continuing with the issue. Were you able to find the code that handles this? If not, let us know and we can guide you in the right direction.

**Comment by naperkovskiy** [comment]
Thanks a lot, I'll definitely let you know if I need any help.

**Comment by Pomax** [comment]
@naperkovskiy are you still working on this? If so, it's a good idea to report in every 1~2 days to make sure people know you're still working on an issue rather than having shelved it. And of course, if you've shelved it, important to let people know that, too =)

**Comment by humphd** [comment]
This bug is filed various times, and there is an active PR for it.  I'm going to close.
