### ISSUE TITLE
Corrupted project won't open

### ISSUE THREAD

**Issue by jasonshafton** [mozilla/thimble.mozilla.org#1669]
I mistakenly pasted HTML into a filename (instead of plain text) and seem to have corrupted the project. Here's my project URL: https://thimble.mozilla.org/en-US/user/jasongoodworld/738697

STEPS TO REPRODUCE:
1. Create a new project
2. Rename an HTML file and paste in a block of HTML / CSS code into the filename
3. Observe that the filename disappears
4. Attempt to reload the project
5. Observe that it won't open

**Comment by flukeout** [comment]
@jasonshafton is it stuck on the green loading screen? Any chance you published the project before getting it stuck in this state?

**Comment by flukeout** [comment]
In the database I see that project 738697 doesn't exist..

![image](https://cloud.githubusercontent.com/assets/25212/22305003/ba99c6da-e2ee-11e6-9738-5d0453274bfb.png)

@jasonshafton did you delete it via Thimble after encountering the error?

**Comment by jasonshafton** [comment]
It was stuck in the loading state. The project is no working. Will close this one but super weird...
