### ISSUE TITLE
Preserve scroll position in preview when it auto-refreshes.

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.mozilla.org#1671]
Whenever the preview auto-refreshes the page you are editing, it scrolls it back to the top. This makes the preview hard to use because you have to keep scrolling down after you make a change to see how it looks.

Can we preserve the scroll position of the preview so that when we auto-refresh, the page stays at the same scroll position?

Every time we fire the auto-refresh, we could note the scroll position of the document, and then re-apply it after the refresh is finished.

@humphd if someone has trouble choosing a good first bug, I'd recommend this one, I think it's pretty high value.

**Comment by flukeout** [comment]
Note that this doesn't happen when you are just typing text into the HTML page. The preview will update but won't refresh. Once you add a tag, or edit a stylesheet connected to that page, the refresh is triggered.

**Comment by humphd** [comment]
Can you give me some steps to reproduce this?  I added code a long time ago to handle the scrolling position, so it's surprising to me that it's not working for you.  Doing things locally that would trigger this don't seem to cause it.

**Comment by flukeout** [comment]
So, investigating this more showed that it "almost" preserves the scroll position. It's just a bit off, maybe like 50-80px, which has the effect of making it seem like the page is going back to the top when a page is just barely longer than the viewport. Here's a screencap of what I'm seeing...

![scroll](https://cloud.githubusercontent.com/assets/25212/22315190/29b81f82-e31a-11e6-8459-78f75d62a4ef.gif)

**Comment by flukeout** [comment]
It also happens when you are scrolled to the bottom of the page and refresh, as seen here..

![scdroll2](https://cloud.githubusercontent.com/assets/25212/22315248/7ae4ccc0-e31a-11e6-92f7-a5aa04aca8eb.gif)

This doesn't happen every single time.

Here's my hypothesis. As soon as the page refreshes, we try to apply the new scroll position, but sometimes, all of the content hasn't loaded fully yet (in the case of my example, maybe the styles of the heading or something), and so we can't scroll far down as we want. 

Then, once the content fully appears there is extra scoll room at the bottom.

**Comment by Rajat-dhyani** [comment]
@flukeout @humphd i would like to handle this issue.... could u please guide where to start ?

**Comment by humphd** [comment]
The code doing this lives here:

* https://github.com/mozilla/brackets/blob/master/src/extensions/default/bramble/lib/MouseManagerRemote.js#L6
* https://github.com/mozilla/brackets/blob/master/src/extensions/default/bramble/lib/MouseManagerRemote.js#L67
* https://github.com/mozilla/brackets/blob/master/src/extensions/default/bramble/lib/MouseManagerRemote.js#L94-L97

Basically what we do is keep track of the last-known scroll position of the window in `localStorage`, using a key that is specific to this page/session.  Then, we we reload, we scroll back to that position.

There must be some case this misses by a small amount.  Likely we need to update that variable in response to some other event.

**Comment by bkim49** [comment]
@Rajat-dhyani Hey Rajat, I am thinking about working on this bug. If you are not working on it, mind if I take it? If you can respond back to me, that would be great. 

Thanks.

**Comment by Rajat-dhyani** [comment]
hey @bkim49  i m currently busy with my college work....so it would be great if you can fix this..... 👍

**Comment by bkim49** [comment]
@Rajat-dhyani Alright. I ll do my best. Thanks for letting me know.

**Comment by bkim49** [comment]
Like @humphd mentioned earlier in this issue, this bug does not occur locally. How would I fix an issue in this case?

**Comment by humphd** [comment]
"does not occur locally" <-- can you tell me what you mean by this?  I don't read that above.

**Comment by bkim49** [comment]
@humphd I mean, when I run thimble + bracket through vagrant locally on my computer, this bug does not occur. Refresh button, or auto refresh does not move the cursor to the very top of the preview page. Instead, it does what @flukeout wants it to do. It remains in the same position where the cursor starts. But when it auto refreshes, the scroll on the preview side does not change.

This bug only shows on the current Thimble webpage.

**Comment by flukeout** [comment]
@bkim49 I can't reproduce this in production OR locally right now! I guess that's a good thing - I'll close it for now, and if I notice it again, I'll open a new issue with very clear steps to reproduce the problem. Thank you for looking into it!

If it's happening for you in production, can you post a link to the published project where you are noticing it? I'll remix it and try to reproduce it.
