### ISSUE TITLE
Thimble + IoT: Look into Espruino

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.mozilla.org#1676]
There are bunch of IoT devices like puck.js that speak Javascript, and there's a web based IDE (that's open source) that you can use to program them - https://www.espruino.com/ide/

Puck.js is programmable over WiFi, so if we baked in the web based espruino IDE into Thimble, it seems like we could get someone up and running with IoT pretty quickly. Will keep researching, and might order some of this stuff into the office.

**Comment by flukeout** [comment]
I ordered a puck.js - https://www.adafruit.com/product/3372 - will update this issue once it arrives and I figure it out.

**Comment by gideonthomas** [comment]
Not in scope anymore
