### ISSUE TITLE
When auto-refresh is turned off in the preview, and I start editing a different HTML, the preview should reflect that.

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.mozilla.org#1677]
Let's say I'm editing ``index.html`` with auto-refresh off in the preview. Now, when I add a new HTML file and start editing it, the preview still displays on ``index.html``. To get it to show my new page, I have to click the Refresh icon, which is not really that intuitive.

I'd expect the preview to switch as I'm moving between HTML files, even with auto-refresh turned off.

![image](https://cloud.githubusercontent.com/assets/25212/22342697/1cfb001c-e3aa-11e6-8c0f-c9e7b7d30feb.png)

**Comment by flukeout** [comment]
When auto-refresh is disabled, it also prevents you from navigating between pages via links in the preview, which we should allow.

**Comment by tonypark0403** [comment]
Hi, I'd like to take a stab at fixing this bug.

**Comment by flukeout** [comment]
Greart, @tonypark0403 - let me know if you need any clarification and if you're able to reproduce the behaviour I'm describing.

**Comment by gideonthomas** [comment]
@tonypark0403, just to give you a bit of context:

- You will need to make the code change in the Brackets repository (check the readme for how to set that up) but the easiest way to test it is with Thimble (by using the UI to toggle the auto-reload feature)
- The change that probably needs to be made is in [this file](https://github.com/mozilla/brackets/blob/master/src/extensions/default/bramble/lib/PostMessageTransport.js) by modifying the function that sends transport messages and forcing a reload for a `Page.navigate` message

**Comment by tonypark0403** [comment]
Thank you.

I will look into the file.
But, I wonder why we got another repository, thimble?
Please explain it more.
Thank you again.

Sincerely,

Tony Park

**Comment by gideonthomas** [comment]
@tonypark0403, if you look at the setup instructions on the [repo homepage](https://github.com/mozilla/thimble.mozilla.org), it will explain how "Thimble" is divided across different services and apps.

The tldr; for your specific question is that we have taken Adobe Brackets (it's own github repo), forked it, and modified it to be usable in the browser and for Thimble (and we call it Bramble). We try to keep that repository up to date with Adobe Brackets and also allow other applications that only need an "editor in the browser" to use it on its own without the other features that Thimble offers. Therefore, we keep Thimble (containing these other features) as a separate repo from Brackets (containing just the editor).

**Comment by humphd** [comment]
@tonypark0403 I see that @gideonthomas has given you some info above.  Here are my thoughts, in addition.  There is a function that will reload the preview here:

https://github.com/mozilla/brackets/blob/master/src/extensions/default/bramble/lib/PostMessageTransport.js#L216-L246

You'll notice it takes a `force` argument, a `boolean` that if `true`, will automatically force the preview to reload.  However, currently when the user tries to navigate to a new page, we just call `reload()`, which is like calling `reload(false)`, so it won't force it:

https://github.com/mozilla/brackets/blob/master/src/extensions/default/bramble/lib/PostMessageTransport.js#L160-L166

I suspect that you could force a reload there, and it would work.  See if I'm right.

**Comment by gideonthomas** [comment]
Fixed in mozilla/brackets@7ab8bae96559ed9c4a13dae9ea961cda8f3baf75
