### ISSUE TITLE
Current version doesn't install on Win/MacOs

### ISSUE THREAD

**Issue by simon66** [mozilla/thimble.mozilla.org#1679]
Tried installing a fresh copy of Thimble on both Win 7 (x64) and MacOS (Sierra) and I get the following error:

![capture](https://cloud.githubusercontent.com/assets/1103528/22387732/1b936604-e4ab-11e6-95f2-6c6665397351.PNG)

I installed Brackets first then Thimble.

Looks like the .env file is missing
I see that there's a script that copies ["env.dist" to ".env"](https://github.com/mozilla/thimble.mozilla.org/blob/master/scripts/start-services.sh#L122) but it looks like the installation fails before that bash script is ran.

Both Windows and MacOS gives me the same error.
Can someone confirm that they are also experiencing the same issue?

**Comment by Pomax** [comment]
Is this with the `vagrant` solution outlined in the README.md, or is this running custom steps?

**Comment by simon66** [comment]
Ah I see... We let vagrant install thimble. The README wasn't clear enough to me. 
I was trying to install it via `npm install`

**Comment by humphd** [comment]
@simon66 maybe you should add a note to the `README.md` to help others not make this same mistake--it seems like something others might hit?

**Comment by simon66** [comment]
@humphd Funny you say that, I'm actually working on it (I noticed the actual README.md has a few mistakes) :)
