### ISSUE TITLE
Project stuck in "Saving failed, retrying..." state.

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.mozilla.org#1685]
I made some changes to an already-published project including dragging an image file into the file three and then moving it to the images folder. I tried to update the published project, and now it's stuck in this state...

![image](https://cloud.githubusercontent.com/assets/25212/22489236/3062dd6c-e7cb-11e6-95dc-2b28e3033d50.png)

The images aren't very big in this project, so it's not that.

Published project is here - https://thimbleprojects.org/flukeout/16745/

@gideonthomas

**Comment by flukeout** [comment]
I cleared my IndexedDB and was able to return to a 'normal' state. The image file in question ``thumbnail.gif`` is still visible in the images folder. I made a text change to the project and hit "Update Published". 

However, that file is not available in the published project:

* Old image, works https://thimbleprojects.org/flukeout/16745/images/dapper-fox.png
* New image, doesn't https://thimbleprojects.org/flukeout/16745/images/thumbnail.gif
  * Shows up int the file tree though

![image](https://cloud.githubusercontent.com/assets/25212/22489358/ebab7b42-e7cb-11e6-96a3-69fc55535b78.png = 150x)

**Comment by flukeout** [comment]
Update - seems to work now, the image is published...

* https://thimbleprojects.org/flukeout/16745/images/thumbnail.gif

**Comment by Pomax** [comment]
it feels like we might need an issue filed for an "emergency" menu button that clears indexdb (with maybe a "this operation clears your browser database which we use for blah blah, this is a last resort and we can't help debug any issues if you pick this before filing an issue over one blhablhab etc"?

**Comment by flukeout** [comment]
Yeah, we've got a wiki page for clearing your cache already (we should update it with IE instructions) and we should also have instructions for the IndexedDB stuff and link to it.

**Comment by gideonthomas** [comment]
+1 to @flukeout's solution for now. This isn't necessarily an issue with IndexedDB though. It could also be an issue with the filesystem sync logic (for which clearing IndexedDb won't usually resolve but sometimes refreshing your browser will resolve). We would probably need to figure out proper UX for your solution that will possibly include formatting the filesystem or somehow recreating the files and manually syncing them one by one to the db so that there is no data loss or some combination of the two.

**Comment by humphd** [comment]
NOTE: I have code in Bramble that we can trigger if you want to expose it via a fatal error UI: https://github.com/mozilla/brackets#brambleformatfilesystemcallback

**Comment by flukeout** [comment]
Closing as there isn't much action here and it hasn't been a problem (at least for me) recently.
