### ISSUE TITLE
Trouble with Dev enviornment

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.mozilla.org#1691]
I've got the brackets repo running on :8000 and the vagrant up version of Thimble running too.

I can load the homepage and the editor, but when I click Sign In or Create an Account, I get an Oops page...

![image](https://cloud.githubusercontent.com/assets/25212/22522711/87df22f2-e871-11e6-93a0-95992c5f044d.png)

There's a double slash in the URL when I click these links, might that be the issue?

``http://localhost:3500/en-US//callback?code=22ed3d7f600...``

Is there an alternate process for setting up an account locally so that I can test publishing, or is this supposed to work.

cc @gideonthomas

**Comment by humphd** [comment]
That looks like a missing `env` variable that tells Thimble where the login server is.  No idea why that would happen.

**Comment by simon66** [comment]
Like we spoke earlier @flukeout, I also have the same issue when trying to Import a Tutorial page.
After looking at what was change recently, I found this commit:

https://github.com/mozilla/thimble.mozilla.org/commit/f3c20672c905af758a95f34bfeb4b2e38cc49e76

Line 43 is whats causing the double slash.
For now, this is how I "patched" it.
![screen shot 2017-02-01 at 3 54 40 pm](https://cloud.githubusercontent.com/assets/1103528/22525815/d5ebdc0e-e896-11e6-8647-c82b9372ad28.png)

Another fix would be to remove the first instance of / in orgUrl (if exists) and leave the + "/".

**Comment by gideonthomas** [comment]
I'm pushing up a fix for this in a sec
