### ISSUE TITLE
Thimble Vision

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.mozilla.org#1693]
Team, I started a few vision documents related to WebVR and IoT. These summarize some of the ideas that we've had as a team and also reflect the input of the Web VR team at mozilla. I'd love to hear any feedback or new ideas these generate for you.

* [Thimble and A-frame](https://docs.google.com/document/d/1TsAf18x8jOXqmbPWgXk3Ea4h4TN-Um1Ia1gt6vtomFk/edit)
* [Thimble + Physical IoT](https://docs.google.com/document/d/1zqDWLHFyRQgYjtCivGwOqGkseoq-qc8X0YHb9yETL9M/edit)
* [Thimble + Virtual IoT](https://docs.google.com/document/d/1J_OwvI1TiCDHCDsM7r-m5KRP2o9KzTxfHvOMPmx6tlI/edit)
* Incoming - "Remote Mentoring"

They're just a starting point, and we should continue to flesh them out as we learn more. I also think we need a way to check in with our current audience about what they need and what they would be excited about.

Please also let me know if the format needs any updates. Any questions we should be asking as we evaluate these themes?

I think the we flesh these out (and any new ones as we come up with them) in the next few weeks and then work to build consensus around which one to move forward with.

**Comment by flukeout** [comment]
cc @gideonthomas @humphd @Pomax @hannahkane @simonwex

**Comment by flukeout** [comment]
As for my own two cents, the virtual IoT stuff would be a blast to work on. I'm getting a puck.js device in the next few days, so I'll have a better handle of that workflow pretty soon.

The VR stuff is neat too - we'd get some interest from the existing A-frame community and it would also give us reasons to collaborate with moco.

**Comment by flukeout** [comment]
@hannahkane suggested we do a bit of competitive analysis within each of the vision docs. I'll add that section. To do that, I think we'll also need a pretty specific audience definition, how about

* Educators in classrooms or after-school programs working with beginner coders between 13 and 18 years old. Students have access to their own computers.

**Comment by hkirat** [comment]
Hey @flukeout 
I like the idea of integrating VR to Thimble. I have a few ideas that I've summarized below.

1. Integrating the visual inspector into the editor.
Right now the editor interface is divided into two parts, one that contains the code, and the other one containing the output. Aframe-inspector (https://github.com/aframevr/aframe-inspector) is a tool to inspect your scene visually and modifies code according to the changes done in the visual inspector. This is a great tool to both inspect your scene and it also helps people with a non-coding background create virtual reality experiences.

Most of the work on the visual inspector is being done in the aframe-inspector repository. 

Here are a few mock ups of integrating it to thimble: 
![1](https://cloud.githubusercontent.com/assets/8079861/23618271/d8dbdca0-02b5-11e7-8876-6d0187db5552.png)

![2](https://cloud.githubusercontent.com/assets/8079861/23618256/ce2a2c26-02b5-11e7-80ea-058d3f857a3b.png)

These mock ups includes orthographic views of the scene which is yet to be implemented in aframe-inspector [Issue Here](https://github.com/aframevr/aframe-inspector/issues/302)

2. Adding aframe.js examples to the Thimble homepage.
Some of the best examples on WebVR can be found on the awesome-aframe [repo](github.com/aframevr/awesome-aframe). These can be used as a to help people start with VR.

**Comment by flukeout** [comment]
Hey @hkirat - this looks interesting, thanks for looking into it!

I wonder a little bit if the Inspector is the best starting point. Thimble mostly focuses on beginner coders who are learning markup, so I think we should aim our features at promoting that kind of learning. The inspector kind of takes away from that experience and makes Thimble into a more fully featured 3D tool, which I don't think is the right intention.

Have you tried using A-frame within Thimble yourself? What have been your experiences and problems? Maybe we can focus on some smaller, simpler features. I think one interesting feature would be to create a QuickEdit view (like the colorpicker) for when you're editing an object.

Here's the issue: https://github.com/mozilla/thimble.mozilla.org/issues/1640

Would you be interested in working on that? I think if we can figure out how to make QuickEdit views for other types of tags / properties that would be really good for the tool overall.

I'm goign to close this "Vision" issue, but feel free to file new issues related to this work.
