### ISSUE TITLE
Tag our project for the new Topics feature in Github.

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.mozilla.org#1695]
https://github.com/blog/2309-introducing-topics

We can use this to make our project easier to discover for new contributors.

Thanks to @ryanwarsaw for the heads up.

Let's get the ball rolling...

* CSS
* HTML
* Javascript
* Editor
* Educational
* Learning
* Brackets
* ...

From Ryan

* community
* curriculum 
* education 
* learn-to-code
* nonprofits
* programming
* teachers
* brackets 
* javascript 
* nodejs
* code-editor, etc?
* mozilla

**Comment by humphd** [comment]
I added some, based on some other similar projects.  Feel free to edit/change.
