### ISSUE TITLE
Experiment: embed Piskel Sprite Editor into Thimble

### ISSUE THREAD

**Issue by humphd** [mozilla/thimble.mozilla.org#1696]
I saw a new open source web app today called [Piskel](http://www.piskelapp.com/) for editing sprites:

![](http://www.piskelapp.com/static/resources/home/piskel_screenshot.jpg)

It could be something you include (via extension) into Brackets and use for building games.  We'd have to hack it a bit to sit on our filesystem vs. using their publishing service, but it wouldn't be a ton of work.  Something to consider if we want to do a game programming kit.

**Comment by chadsansing** [comment]
Would love it; we feature Piskel in a web lit lesson or two.

**Comment by humphd** [comment]
We did some experiments with this in class.  It's interesting, but not high priority, going to close.
