### ISSUE TITLE
Cursor property is not changed when hovering on a folder

### ISSUE THREAD

**Issue by simon66** [mozilla/thimble.mozilla.org#1703]
When hovering the mouse over a folder in the file tree, the mouse cursor is set to `default` instead of `pointer`.
![ezgif com-video-to-gif 1](https://cloud.githubusercontent.com/assets/1103528/22621635/1924ddc0-eaf6-11e6-800f-4f8decbbfd0e.gif)

I fell like the cursor property should be set to `pointer` since folders are clickable items just like the other item in the file tree.

@flukeout, what do you think?

**Comment by flukeout** [comment]
Thank you for filing - at a minimum we should change it so the cursor turns to a pointer.

Generally, I wish we styling that is more distinct from just a regular file, but we can leave that for another issue.

**Comment by rkgupta21** [comment]
I'm interested on working on this bug.

**Comment by humphd** [comment]
@rkgupta21 excellent, it's yours.  You probably need to make your CSS changes in `src/extensions/default/bramble/stylesheets/sidebarTheme.css` in the Bracket's repo.  You can do your PR against it vs. Thimble, and just reference this bug by URL in your commit message.

**Comment by gideonthomas** [comment]
Fixed with mozilla/brackets@1454b667bb02c2343675e054b550fc32b0fd47be
