### ISSUE TITLE
Issues with new Vagrant set up

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.mozilla.org#1705]
Gideon and I found some issues with the current setup when trying out code from some of the branches in the currently opened PRs.

**LESS files aren't being compiled do CSS**
We couldn't get this to work no matter what we tried.

**JS file changes aren't being reflected**
When you load up a new branch, even if a JS file is changed, that change won't be reflected in your local environment until you manually edit the file (with something trivial like adding a space). Then that triggers a re-build.

cc @humphd

**Comment by humphd** [comment]
I'll see if I can fix things.

**Comment by humphd** [comment]
@gideonthomas, @flukeout: question: where are we (re)building LESS for Thimble now?

**Comment by humphd** [comment]
It looks like switching branches *does* cause files in `public/**/*.js` to get rebuilt.  So I'm not sure what you're seeing in your first bullet.  Can you give me some STR?

**Comment by flukeout** [comment]
@humphd Will try again now, one sec.

**Comment by humphd** [comment]
Reading https://github.com/mozilla/thimble.mozilla.org/blob/master/server/request.js#L97-L105 it seems like we have code that *should* recompile LESS if you don't specify that we're optimizing.  We call it here, maybe we have a bug: https://github.com/mozilla/thimble.mozilla.org/blob/20fa70c77fb6a9dbdad29492989715178954fada/server/index.js#L55

**Comment by flukeout** [comment]
Wow this might be me just not hard-refreshing the editor. Seems like all of this has resolved as soon I started doing that. Damn. I'll keep this open just for a little longer and chime in if I'm experiencing this again, but disregard for now @humphd

**Comment by humphd** [comment]
One thing to note: restarting the server isn't instant, it takes a few seconds, depending on the speed of your host machine, and therefore the speed of the guest VM.  Maybe it's just lag?

Running `npm run logs` will at least show you what's happening (everything but the LESS stuff, which we could log too if it helps).

**Comment by flukeout** [comment]
Okay, closing this - apologies for the hassle.
