### ISSUE TITLE
Feature Request: Split HTML / CSS view instead of one-at-a-time.

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.mozilla.org#1706]
Via email...

> It will be very good if we can have split view of html and css files in the same window. 

Let's review at some point later when going through feature requests.

**Comment by humphd** [comment]
That's kind of the point of Bracket's inline CSS editing mode, where you go to any element in the HTML, and do `CMD+E` to open the CSS right there in the file.  The problem with it is that it's not discoverable.  But that's part of a solution to what you're describing.

**Comment by humphd** [comment]
I don't think we're going to do major surgery on Brackets to allow for this, closing.
