### ISSUE TITLE
Align images on starter page when br tags are used in the description

### ISSUE THREAD

**Issue by gideonthomas** [mozilla/thimble.mozilla.org#1708]
Localizers would like to use `<br>` tags in strings so that they don't end up with situations like this: https://bramble.mofostaging.net/dsb/ (take a look at the Homework Excuse generator project - second row, middle image). 

When they try to add `<br>` tags though, the image moves down, but the other images (left and right) don't move to align themselves with the image that moved down.

I don't know if this bug needs to be fixed in the current code or if you'll be accounting for it in the gallery code @flukeout. If this can be fixed in the current code, let's mark this as a "good first bug".

**Comment by Pomax** [comment]
I'm not sure I understand what I'm looking for in the link you gave... ?

**Comment by flukeout** [comment]
The way the long title of one of the starter projects blows up the layout...

<img width="890" alt="image" src="https://cloud.githubusercontent.com/assets/25212/23042404/7a0821c8-f44d-11e6-9dcd-fd7bc6faa4fd.png">

**Comment by Pomax** [comment]
Ahh... this feels like a `<br>` might be the wrong way to go. We could auto inject `<wbr>` between words of a title, which makes them break-only-when-necessary (if you've never see `<wbr>`: it is super useful), but then this would push images out of vertical alignment...

**Comment by bkim49** [comment]
@gideonthomas  I would like to work on this bug. Can I be assigned to this bug? Thank you

**Comment by Th30** [comment]
I don't think this bug is relevant anymore, the new UI design seems to fix this. @gideonthomas

**Comment by humphd** [comment]
Thanks, closing.  @flukeout if you think we need this, or something similar, please re-file.
