### ISSUE TITLE
Make it harder to accidentally Unpublish a project.

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.mozilla.org#1718]
In the Publish dialog, the Unpublish link is really close to the link the published project, which can lead to misclicks and unintended consequences.

<img width="250" src="https://cloud.githubusercontent.com/assets/25212/22798522/3e128d02-eeb7-11e6-85cc-131b6c3d68de.png"/>

It's especially bad because once you do this, you can't get the original URL back.

**Ideas**
* Move the Button further away from the project link
* Add an extra step to confirm an Unpublish action
  * Maybe even a boring old Confirm
  * Some kind of custom "Are you sure?"
* Change icon to Trash icon.
* Make the button red scary.
* Change label to "Delete" instead of "Unpublish"
  * Unpublish / republish kind of makes it seem like you might get the same URL

Also somewhere within that UX we should indicate that Unpublishing causes you to lose the original URL you had.

**Comment by gideonthomas** [comment]
+1 to adding an extra step

**Comment by O-kasso** [comment]
hey! can I take a crack at this?

**Comment by humphd** [comment]
@flukeout can you let @O-kasso know your thoughts on this plan?

**Comment by O-kasso** [comment]
I was thinking the confirmation dialog could say something like "Are you sure you want to unpublish this project? Links that have already been shared will no longer work."  

Also, does localization need to be taken into account? is there any material available describing how locale text is handled?

**Comment by gideonthomas** [comment]
@O-kasso go for it! I would say go with those changes for now and open up a PR and we can comment on any changes there. As for localization: https://github.com/mozilla/thimble.mozilla.org/wiki/Localization might be helpful.

**Comment by O-kasso** [comment]
Basic fix here: https://github.com/mozilla/thimble.mozilla.org/pull/1739
Will address localization separately.

**Comment by TheAlbinoPanda** [comment]
Afternoon,

Is this issue solved? Can I take a stab at it ? I'm new to all of this, so If i'm doing something wrong, just let me know !

**Comment by O-kasso** [comment]
@TheAlbinoPanda workin' on it :)

**Comment by gideonthomas** [comment]
@TheAlbinoPanda if you look at the list in https://github.com/mozilla/thimble.mozilla.org/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20label%3A%22good%20first%20bug%22%20-label%3A%22assigned%20to%20contributor%22 you might have a better chance finding issues that haven't been taken by someone yet.

**Comment by flukeout** [comment]
Sorry team, was just alerted to this issue by @Pomax (thanks!).

@O-kasso this looks great, I'll provide a white garbage can Icon momentarily. I think that will work better. Then, please create a PR and we'll go from there!

**Comment by flukeout** [comment]
Here's a white garbage can - https://drive.google.com/open?id=0B_CPRh4f3yyqOGYwVkJ2c0xmOUE

**Comment by O-kasso** [comment]
![image](https://cloud.githubusercontent.com/assets/7986733/23038104/cc30cac8-f456-11e6-92f8-6657f047f6ee.png)

**Comment by flukeout** [comment]
Fixed via #1739
