### ISSUE TITLE
Gear menu icon should keep "hover" state always when the menu is open.

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.mozilla.org#1719]
This is a small cosmetic bug.

Currently, when you hover and click on a gear icon, it turns white and opens the menu. When you mouse off and use the menu, the gear fades out again. 

It should stay white the whole time the menu is open. See below for what I mean...

![menu](https://cloud.githubusercontent.com/assets/25212/22807568/89d46966-eedc-11e6-9e7f-9bfc13e9f96e.gif)

We might want to add a "menu-open" class whenever this menu (and others like it) are open.

**Comment by bbhagwandeen** [comment]
I'd like to try to fix this small cosmetic bug.

**Comment by gideonthomas** [comment]
@bbhagwandeen awesome! Feel free to let us know if you need any help.

**Comment by Pomax** [comment]
@bbhagwandeen are you still working on this?

**Comment by bbhagwandeen** [comment]
Yes, sir. Working on it at this moment. Should be completed today.

Brandon Bhagwandeen

On Feb 16, 2017, 3:53 PM -0500, Mike Kamermans <notifications@github.com>, wrote:

@bbhagwandeen<https://github.com/bbhagwandeen> are you still working on this?

**Comment by bbhagwandeen** [comment]
I've found a way for the gear icon to stay highlighted when active/clicked but it doesn't seem like a proper way of applying it.

**Comment by humphd** [comment]
@bbhagwandeen afaict, this never happened.  You have a PR that you closed, and then it's gone silent.  What's the story?  If you plan on using this as your release as per https://bbhags.tumblr.com/post/159855343044/continuing-the-fix-of-1719, you need to actually finish it.  Let me know ASAP.

**Comment by bbhagwandeen** [comment]
@humphd Sorry about that, the link was wrong. I updated the wiki to direct to the final PR

**Comment by humphd** [comment]
Fixed with https://github.com/mozilla/thimble.mozilla.org/pull/1951, closing.  @bbhagwandeen you need to make sure that issues associated with a PR get closed.  If you use the `Fix #...` style message on your PR, it will automatically happen.  In this case it didn't.
