### ISSUE TITLE
Make hover effect transitions consistent

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.mozilla.org#1722]
Take a look at this GIF of me hovering over various UI elements.

![hover](https://cloud.githubusercontent.com/assets/25212/22807856/0326680e-eede-11e6-96e3-99df346cdb06.gif)

You'll notice the buttons in the toolbar change color immediately, while the menu color fades.

Let's make this consistent. I'd be curious what all of these look like with a fast transition time. Let's try ``.15s`` with an ``ease-out`` on the css transitions for these elements.

**Comment by bkim49** [comment]
Hello, I worked on this bug. I used the existing transition class in userbar.less and editor.less files. I have added transition class into all the appropriate CSS elements that allows hover animation. Using the transitionTime, you can adjust all the hover time with ease. 

```
/* Transition time for hover effects */
@transitionTime: 0.15s;

.transition {
  -webkit-transition: @transitionTime;
  -moz-transition: @transitionTime;
  -ms-transition: @transitionTime;
  -o-transition: @transitionTime;
  transition: @transitionTime;
}

.transition-only-opacity {
  -webkit-transition: opacity @transitionTime ease-in-out;
  -moz-transition: opacity @transitionTime ease-in-out;
  -ms-transition: opacity @transitionTime ease-in-out;
  -o-transition: opacity @transitionTime ease-in-out;
  transition: opacity @transitionTime ease-in-out;
}
```

I have created 2 GIF: 

0.5s Transition time
![0 5 transition](https://cloud.githubusercontent.com/assets/17182037/22851950/77c7776c-efff-11e6-90e7-ab05b1a1867c.gif)


0.15 Transition time
![0 15 transition](https://cloud.githubusercontent.com/assets/17182037/22851951/7a4eb8ba-efff-11e6-9d3f-860e3709c88a.gif)

My GIF is little faster than usual, hopefully you can tell the different between 0.5s and 0.15s.

**Comment by bkim49** [comment]
@flukeout Could you give me a feedback for the transition time? Whether to go with 0.5s or 0.15s.

**Comment by gideonthomas** [comment]
@bkim49 I would recommend that you open up a pr (you can add [WIP] to the title) with whatever you feel is right and we can comment there. I believe @flukeout won't be available until tuesday but it will help for us to see your work in progress.

**Comment by flukeout** [comment]
Hi @bkim49 - please go with .15s and please also use ``ease-out`` timing, I find it's makes things feel more responsive and snappy.

**Comment by Pomax** [comment]
are all these vendor prefixes still necessary? `transition` has been a normal CSS property for a while now, I'd be surprised if any modern browser (e.g. still supported by the vendor who makes that browser) doesn't just work without the -vendor- prefix

**Comment by flukeout** [comment]
Good call @Pomax - let's roll with just ``transition``
