### ISSUE TITLE
Add hover effect to the AUTO refresh UI in the preview.

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.mozilla.org#1723]
Currently, it's one of the few UI elements that doesn't have a :hover treatment...

![checkbox-hover](https://cloud.githubusercontent.com/assets/25212/22808581/929b2c74-eee1-11e6-9c3b-1e7868af7ce0.gif)

...maybe just making the text slightly darker would work.

**Comment by O-kasso** [comment]
Oops, I submitted my attempt at this fix, didn't realize it had been assigned to someone else! For posterity, https://github.com/mozilla/thimble.mozilla.org/pull/1733 is my fix, but feel free to chuck it ¯\\_(ツ)_/¯

**Comment by gideonthomas** [comment]
@O-kasso that's ok, we'll try to figure out which fix makes sense and go with that.

@O-kasso and @hritwik567, as a best practice (possibly for next time), it is often helpful for us as project maintainers (as well as other contributors) to know who is working on what, so I would recommend commenting in the issue first saying that you would like to fix the bug before attempting the fix. This way, the likelihood of duplication of work is reduced.

Either way, thank you for digging into this and contributing. We'll take a look at your PRs asap.

**Comment by gideonthomas** [comment]
Fixed with e91fad76864c92e6b604d92f37e1307dd4c447ae
