### ISSUE TITLE
Locales not present when installing via vagrant

### ISSUE THREAD

**Issue by LCartwright** [mozilla/thimble.mozilla.org#1729]
I'm attempting to start up thimble for the first time from a fresh clone of master, after running `vagrant up`, requesting http://localhost:3500/ returns a connection reset error from the browser. 

So looking at the pm2 app summary in the `vagrant up` output, I see that `localize-client` is stopped
```bash
==> default: ┌─────────────────┬────┬──────┬──────┬─────────┬─────────┬────────┬─────┬───────────┬──────────┐
==> default: │ App name        │ id │ mode │ pid  │ status  │ restart │ uptime │ cpu │ mem       │ watching │
==> default: ├─────────────────┼────┼──────┼──────┼─────────┼─────────┼────────┼─────┼───────────┼──────────┤
==> default: │ id              │ 1  │ fork │ 2215 │ online  │ 0       │ 12s    │ 23% │ 27.3 MB   │ disabled │
==> default: │ localize-client │ 3  │ fork │ 2227 │ stopped │ 1       │ 0      │ 0%  │ 0 B       │ disabled │
==> default: │ login           │ 0  │ fork │ 2209 │ online  │ 0       │ 12s    │ 42% │ 21.0 MB   │ disabled │
==> default: │ publish         │ 2  │ fork │ 2221 │ online  │ 0       │ 12s    │ 23% │ 39.9 MB   │ disabled │
==> default: │ thimble         │ 4  │ fork │ 2235 │ online  │ 0       │ 12s    │ 20% │ 47.5 MB   │ enabled  │
==> default: └─────────────────┴────┴──────┴──────┴─────────┴─────────┴────────┴─────┴───────────┴──────────┘
```
Digging into the log file `/home/vagrant/.pm2/logs/localize-client-out.log` shows the following error
```
Error: Cannot find module '/vagrant/dist/locales/en_US/messages.json'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/vagrant/scripts/localize-client.js:17:12)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
```
Likewise there's a similar error in `/home/vagrant/.pm2/logs/thimble-error.log`
```bash
Error: ENOENT: no such file or directory, scandir '/vagrant/dist/locales'
    at Error (native)
    at Object.fs.readdirSync (fs.js:808:18)
    at Object.exports.middleware (/vagrant/node_modules/webmaker-i18n/i18n.js:408:28)
    at localize (/vagrant/server/localize.js:13:27)
    at Object.<anonymous> (/vagrant/server/index.js:113:1)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
```
So it's looking like theres a missing localisation directory, digging around in the repos `package.json` revealed a promising looking script `"prestart": "npm run localize"`.

 After running this script, success! Thimble has started. 

So my question is this. Have I missed something from the `README.md`? From what I understood, `vagrant up` should have brought up a working thimble vm, accesible via `http://localhost:3500` however that dosn't seem to be the case.

**Comment by gideonthomas** [comment]
@LCartwright hmm that is weird. I wonder if something went wrong in the `npm install` part for thimble. For `vagrant up`, in the startup script, we run `npm install` as one of the last commands here: https://github.com/mozilla/thimble.mozilla.org/blob/master/scripts/setup-services.sh#L113 which automatically should run the `postinstall` script (https://github.com/mozilla/thimble.mozilla.org/blob/master/package.json#L79). As you can see, it runs `npm run localize` as well so this shouldn't have happened.

Would you be able to delete the `dist` and `node_modules` folder from your thimble directory and then run `vagrant destroy` and then `vagrant up` again and see if you get the same error?

**Comment by humphd** [comment]
I got a similar email from @twigz20 tonight, who couldn't get `vagrant up` to start the localization script on startup.  He sent this screenshot:

![screenshot_6](https://cloud.githubusercontent.com/assets/427398/22850473/bf28935c-efd7-11e6-9f92-de532ff6f6e5.png)

Odd that you're both hitting this.

**Comment by gideonthomas** [comment]
maybe we should just add `npm run localize` to the startup script.

**Comment by twigz20** [comment]
After manually running `npm run localize` I get another issue. It seems to be stuck here "Loading Project"

![screenshot_8](https://cloud.githubusercontent.com/assets/10361408/22851517/51ec45ac-eff2-11e6-8ee4-645fa9ef3bf6.png)

Been like that for about 20 minutes now.

**Comment by humphd** [comment]
I wonder if it's a startup order issue between localize-client and thimble?

**Comment by LCartwright** [comment]
@gideonthomas running `vagrant destroy` and `vagrant up` from a fresh copy of `master` produced the same results. You can the full output here: https://gist.github.com/LCartwright/4b14e764f90ca033e258a31018701934 This is being run with node `v6.9.5`, vagrant `1.9.1` and VirtualBox `5.1.14` on Windows 8.1

@twigz20 I had the same issue, I needed to run `npm run postinstall` instead. I'm able to use thimble and open projects after step. So it looks like this command isn't automatically running as part of `npm install --no-bin-links --loglevel=error` as @gideonthomas suggested. 

I removed the logging switch from the command here: https://github.com/mozilla/thimble.mozilla.org/blob/master/scripts/setup-services.sh#L113 so this command now reads `npm install --no-bin-links`. Now running `vagrant-up` this snippet which looks interesting:
```
==> default: WARN
==> default:
==> default: cannot run in wd
==> default:  thimble.mozilla.org@2.0.0 grunt requirejs:dist && npm run localize && npm run localize-client (wd=/vagrant)
==> default: grunt-npm@0.0.2 node_modules/grunt-npm
```
you can see the full output here: https://gist.github.com/LCartwright/a3533e13e3f3620a6f856d5ac80501e7#file-output-2-log-L1902-L1906

**Comment by twigz20** [comment]
@LCartwright It works after using `npm run postinstall`. 
Be sure to have grunt installed on the machine, though. If not, run `npm install -g grunt-cli` before `npm run postinstall` and it should work without any issues.

**Comment by LCartwright** [comment]
There are a couple of issues with the script https://github.com/mozilla/thimble.mozilla.org/blob/master/scripts/setup-services.sh which prevents thimble from starting from `vagrant up`. 

1. thumble is installed with the command `npm install... --loglevel=error` which swallows an npm warning regarding the `postinstall` npm script
2. the `postinstall` npm script needs to run with root privileges, meaning the triggering `npm install` requires the flag `--unsafe-perm`
3. grunt-cli isn't installed on the vm, this is required for the command `grunt requirejs:dist` of the `postinstall` npm script

Adding `npm install -g grunt-cli` and ammending the line https://github.com/mozilla/thimble.mozilla.org/blob/master/scripts/setup-services.sh#L113 with `--unsafe-perm` results in a working thumble instance from `vagrant up`

Does this sounds like a reasonable fix?

**Comment by gideonthomas** [comment]
@LCartwright thank you for debugging this and really nice work figuring out the issue. 

I think the root cause is the missing global dependency of `grunt-cli` (it is bizarre that no one else has run into this issue yet). Feel free to open up a PR with that change (as well as the `--unsafe-perm` change).

Let's keep the `--loglevel=error` for now until we have updated our dependencies so that we don't get spammed by WARN messages. (TBH I think the `cannot run in working directory` message should be an error, not a warning).

**Comment by LCartwright** [comment]
@gideonthomas Thanks! I agree the severity of an install step failing should produce some `ERR` output, I'd liken it to a build step failing. 

PR #1734 submitted, thanks @gideonthomas @humphd @twigz20 👍

**Comment by humphd** [comment]
@LCartwright this is great, thank you so much for dealing with this.  Really appreciated.
