### ISSUE TITLE
Update remix metadata when published projects are renamed

### ISSUE THREAD

**Issue by gideonthomas** [mozilla/thimble.mozilla.org#1737]
Continuation of https://github.com/mozilla/thimble.mozilla.org/issues/719

and cross-filed here: https://github.com/mozilla/publish.webmaker.org/issues/240

STR:
- Publish a project
- Rename the project (no need to make any other changes)
- Open publish dialog to see the "Update published project" button and click on it
- Reload your published project (via the published url) and you will see that the old project name is still used in the remix bar.

**Comment by mkavidas** [comment]
@gideonthomas @humphd I would like to fix this.

**Comment by humphd** [comment]
I think @lkisac is already working on it.  Can you take a look at the other Thimble/Brackets bugs, and if you need help speak to me in class?

**Comment by humphd** [comment]
Fixed by https://github.com/mozilla/publish.webmaker.org/issues/240, closing.
