### ISSUE TITLE
Make FILES, EDITOR, and PREVIEW headers more responsive

### ISSUE THREAD

**Issue by humphd** [mozilla/thimble.mozilla.org#1740]
In apps like Google Docs, if I make my screen narrow, the toolbar shrinks, and a "More" button appears on the right, indicating there are things I'm missing:

![screen shot 2017-02-15 at 9 57 04 am](https://cloud.githubusercontent.com/assets/427398/22979686/36232db0-f365-11e6-8a6e-47bdac8503e9.png)

However, in Thimble, if you narrow one of the FILES, EDITOR, or PREVIEW headers, the buttons just vanish.  We should deal with the case of narrow headers somehow:

![responsive-headers](https://cloud.githubusercontent.com/assets/427398/22979785/8d268c60-f365-11e6-9ff3-515e26257b2f.gif)

I defer to @flukeout for ideas on how this should look.

**Comment by flukeout** [comment]
Oh, I've got some ideas alright. So, I think since we are already firing a 'resize' method all the time, we might as well attach some cool logic to it.

Instead of moving them to a menu, I'd rather we condense the size of the existing UI when things get narrow. For example, ditching the "Undo" label from that icon when we run out of room.

I'll experiment with this a little bit.

**Comment by Pomax** [comment]
the typical way to make this responsive is to have a timeout-for-new-event so you have something like
```
function handleResize() {
  if (resizing) {
    setTimeout(handleResize, 100);
  }
  resizing = true;
  setTimeout(actuallyResize, 0);
}

function actuallyResize() {
  // ......
  resize = false;
}

slide.addEventListener("mousedrag", handleResize);
```

So even thoug the drag event kicks in constantly, you only handle it every 100ms or whatever looks acceptable, so you don't try to handle the resize at 60fps.

**Comment by flukeout** [comment]
Yeah great idea @Pomax - maybe I'll just finish this feature then, with the timeout. Here's how it works with a few items, each of which have a ``display-priority`` attribute set in order of their importance, ie ``1,2,3`` etc.

![narrow-mode](https://cloud.githubusercontent.com/assets/25212/23040633/e9eac114-f446-11e6-8a4c-1fdcb893997c.gif)

**Comment by Pomax** [comment]
I like it. We can probably do some priority checks, feels like collapsing undo to just the icon, then "EDITOR", then the filename, might work best in terms of having people identify what they're using (given that the file tree can be collapsed)

**Comment by flukeout** [comment]
Yeah, easy enough to tweak the priority.

**Comment by flukeout** [comment]
Here's an update with some tweaked priority for the Editor and Preview panes.

![narrowing](https://cloud.githubusercontent.com/assets/25212/23048176/0f6052d4-f469-11e6-9242-ce452f2f7411.gif)

**Comment by Pomax** [comment]
whoa, what's happening with that gray-transition?

**Comment by flukeout** [comment]
It's just crappy color encoding of the GIF tool I'm using. It doesn't do that IRL.

**Comment by Pomax** [comment]
This looks pretty sweet. Should the "undo" button restore its label though? With the width decreasing it seems counter-intuitive that some elements re-expand despite the view getting smaller and smaller.

**Comment by humphd** [comment]
@flukeout this can get closed now I think?  If I'm wrong, please re-open.
