### ISSUE TITLE
Long Term: Improve homepage to showcase features.

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.mozilla.org#1741]
Thimble does a lot of awesome things, but our description of it on the homepage is kind of bland. I'll benchmark some similar tools and see how they present their offering.

We can call out
* Lots of the cool brackets features
  * Quick edit menus
  * Inline CSS editing
  * ...
* That you can publish to the web instantly
* That you can upload assets / files
* Mobile preview
* Inspector tool
* ...lots more!

Also
* Showcase / invite contribution

**Comment by humphd** [comment]
We've done this, closing.
