### ISSUE TITLE
Update node deps

### ISSUE THREAD

**Issue by humphd** [mozilla/thimble.mozilla.org#1743]
We should look at all our dependencies in `package.json` and update them.

See also https://github.com/mozilla/brackets/issues/589

**Comment by gideonthomas** [comment]
@ryanwarsaw I know you were doing some of this work for one of the dependencies. Are you interested in this one too?

**Comment by ryanwarsaw** [comment]
@gideonthomas Yeah I'm currently working on doing some work on login & id, if this is still available afterwards then I'll take it, but I'm not going to assign myself to it (in-case someone wants to take it).

**Comment by humphd** [comment]
Whoever takes this, you can use a tool like https://www.npmjs.com/package/npm-check to make this easier.

**Comment by omytryniuk** [comment]
I would like to update node deps

**Comment by Pomax** [comment]
Awesome, go for it @omytryniuk - Try to update one dependency at a time: when uplifting one dependency works, create a commit, then move on to the next, so that you don't end up with a single diff with 20 updates of which *one* breaks but you can't tell which one =)

**Comment by Pomax** [comment]
this specific issue can be closed with @omytryniuk's PR landing - there are more issues outstanding for individual major-version bumps.
