### ISSUE TITLE
Show the project description (if available) on the Your Projects page.

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.mozilla.org#1755]
If we're going to keep it in the Publish dialog, let's at least make it somewhat useful.
I think we should include the project description as a line of text below the title. If it's longer than one line, we can cut it off with an ``...``

**Comment by cgsingh** [comment]
Can I please have this issue. This seems like something I can actually handle, heh.

**Comment by humphd** [comment]
Yup, go for it.

**Comment by cgsingh** [comment]
@flukeout In order for `text-overflow: ellipsis;` to work, I need a `width: XXXpx`. What value do you want in there, or is there another way I'm supposed to be truncating a description into one line?

**Comment by flukeout** [comment]
Closed via https://github.com/mozilla/thimble.mozilla.org/pull/1759 - thanks @cgsingh
