### ISSUE TITLE
Provide useful error when bramble.js can't be loaded in Thimble

### ISSUE THREAD

**Issue by humphd** [mozilla/thimble.mozilla.org#1758]
If you setup Thimble but forget (or don't know you have to) run Brackets as well, you get our default black error page saying that the project couldn't be loaded.  In reality, it has failed to load `bramble.js` from Brackets, which it needs to load the editor.

We should provide some kind of error for developers/devops running Thimble so they know how to fix it.  I've seen quite a few people get stuck on this.

**Comment by Pomax** [comment]
as I recall we ajax every file for Bramble, correct? If so it should be possible to set up a mapping for "when file with name X fails": "String to present the user when that fails" and present that in the Black Screen(tm) instead.

**Comment by edyedy123** [comment]
id like to work on this

**Comment by humphd** [comment]
OK @edyedy123 it's yours.  Let us know if you have questions.

**Comment by edyedy123** [comment]
hey here's my pull request:
https://github.com/mozilla/thimble.mozilla.org/pull/1820

**Comment by Pomax** [comment]
@edyedy123 rather than putting the issue number in the PR title, remove it from there, and edit to the PR comment to say `fixes #1758`, and then github will automatically link up this issue to your PR
