### ISSUE TITLE
Redirect Sign In on homepage to Your Projects list

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.mozilla.org#1760]
It's a little annoying getting back to a project you were working on after signing in with Thimble. Once you sign in, you pretty much always end up navigating to the **Your Projects** view from the user dropdown.

**So..**

* When someone Signs In from the homepage, let's redirect them there right away.
* If they're already in the Editor though, let's keep them there.

**Comment by gideonthomas** [comment]
I'd question this workflow because that seems to suggest that all the starter projects on the homepage are not clicked enough when people sign in. Since the starter projects are ctas on the homepage, do you imagine some other user workflow that will draw their attention to these projects after signing in and being directed to the your projects page?

**Comment by flukeout** [comment]
I just can't think of a reason why someone would sign in unless they wanted to get at one of their old projects. Signing in currently on the homepage doesn't give you any benefit except to let you then access your projects list after.

**Comment by gideonthomas** [comment]
I think you have a separate issue that's dealing with the starter projects UX and the gallery (that you're working on as well) so if you think that this workflow will also allow them to access those projects easily and calls it to their attention, then this makes sense.

**Comment by sgupta7857** [comment]
Okay, i would like to work on this feature. As per my understanding
1st case: When the user signs in if the user has "more than one" existing project then the user would be redirected to your project page
2nd case: if the user only has one project. the user will be redirected to that particular project page
3rd case: no existing project, the user will be redirected to new project page
Agreed?

**Comment by Pomax** [comment]
That sounds like a reasonable summary of the use cases to me. @flukeout?

**Comment by humphd** [comment]
@sgupta7857 Yes, let's go with what you've described, it sounds right.  If we need to adjust, we'll do it in review.

**Comment by flukeout** [comment]
Hey @sgupta7857 - sorry for the late response. Let's go with the three use cases you've described.

However, could you write it in such a way that makes it easy to disable or turn off case 2 & 3? I'm worried that it might be unexpected behaviour, so I'd like the option to test out how it feels when it's actually running with a few users.

**Comment by flukeout** [comment]
Fixed by @hkirat in https://github.com/mozilla/thimble.mozilla.org/pull/1809
