### ISSUE TITLE
Funky Console Errors on Staging

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.mozilla.org#1762]
Seeing lots of JS errors when I duplicate the link tag in the head of a brand new project on staging.

* Go to https://bramble.mofostaging.net/
* Start a new project
* Copy and paste the existing style tag
* Check the console and see...

![image](https://cloud.githubusercontent.com/assets/25212/23144620/b13850a4-f77d-11e6-83a8-b9c71d1df80f.png)

What is this stuff? @gideonthomas @humphd

**Comment by humphd** [comment]
There's at least one, maybe more bugs here.  The first issue, with the exception in `DocumentRelated` is apparently not a new bug--I can reproduce this on production.  My best guess is that somehow we're throwing away (or regenerating) the `style.css` file's blob URL and one of the two that gets included is failing.  It's dying like so:

```
GET blob:http://localhost:8000/e08b6995-6250-47ec-8972-235d6cd6844a 
EventDispatcher.js:231 Exception in 'DocumentRelated' listener on Object {_EventDispatcher: true, _eventHandlers: Object} Error: Paths must be absolute: 'blob:http://localhost:8000/e08b6995-6250-47ec-8972-235d6cd6844a' Error: Paths must be absolute: 'blob:http://localhost:8000/e08b6995-6250-47ec-8972-235d6cd6844a'
    at FileSystem._normalizePath (http://localhost:8000/src/filesystem/FileSystem.js:489:19)
    at FileSystem._getEntryForPath (http://localhost:8000/src/filesystem/FileSystem.js:556:21)
    at FileSystem.getFileForPath (http://localhost:8000/src/filesystem/FileSystem.js:575:21)
    at Object.getFileForPath (http://localhost:8000/src/filesystem/FileSystem.js:988:25)
    at Object.getDocumentForPath (http://localhost:8000/src/document/DocumentManager.js:342:46)
    at _styleSheetAdded (http://localhost:8000/src/LiveDevelopment/LiveDevMultiBrowser.js:309:42)
    at http://localhost:8000/src/LiveDevelopment/LiveDevMultiBrowser.js:574:29
    at Array.forEach (native)
    at http://localhost:8000/src/LiveDevelopment/LiveDevMultiBrowser.js:573:30
    at Object.trigger (http://localhost:8000/src/utils/EventDispatcher.js:229:40)
```

Basically, we've deleted the URL for the `style.css` file and generated a new one.  Here's what the preview HTML looks like when rewritten:

```html
    <link data-brackets-id="6" data-bramble-start-line="6" data-bramble-start-ch="4" data-bramble-end-line="6" data-bramble-end-ch="44" rel="stylesheet" href="blob:http://localhost:8000/a586393d-1b4f-46b6-b75b-d2d5d982d696">
    <link data-brackets-id="11" data-bramble-start-line="7" data-bramble-start-ch="4" data-bramble-end-line="7" data-bramble-end-ch="44" rel="stylesheet" href="blob:http://localhost:8000/bfde9a05-90ba-44e3-9bd9-80298f234d9e">
```

As you can see we've got 2 `blob:` URLs here, and they don't match.  Our CSS Rewriter, or the BlobUtils, needs to not throw the other one away so quickly.

**Comment by humphd** [comment]
I have a fix up for the first exception above, but the second one is interesting.  It's somehow crashing in here:

https://github.com/mozilla/thimble.mozilla.org/blob/392fb9dccc4a228b21dfe88cfe415cb56a6acded/public/editor/scripts/editor/js/fc/publisher.js#L87-L114

@gideonthomas any ideas?  I'm not sure how to hit this one locally.

**Comment by humphd** [comment]
Oh, I bet this is a symptom of #1738.

**Comment by gideonthomas** [comment]
@humphd yeah it def is that issue.
