### ISSUE TITLE
Add UI toggle for whitespace indicators in the editor.

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.mozilla.org#1763]
It would be cool if we could show whitespace within the editor. It makes it easier to indent the code correctly and gets new coders thinking about this important, but easy miss, aspect of coding.

Here's an extension we could try:
https://github.com/DennisKehrig/brackets-show-whitespace

Or maybe there's another way?

For reference, I'm talking about these little dots that appear where a space is...

<img width="272" alt="image" src="https://cloud.githubusercontent.com/assets/25212/23146457/ca2af50e-f78b-11e6-9ee2-8ee1132abe25.png">

**Comment by humphd** [comment]
Yes, we can do that.  Do you want it to be on by default?  Would it confuse people?

**Comment by Taguiar** [comment]
I would like to do this one.

**Comment by tonypark0403** [comment]
I would like to take this one.

**Comment by flukeout** [comment]
Give it a shot @tonypark0403 - let's try it on by default. If it feels weird, we can add it as another editor option.

**Comment by humphd** [comment]
Here's how I'd tackle this:
* Add the extension linked above to a new folder in this dir: https://github.com/mozilla/brackets/tree/master/src/extensions/default
* Add a new entry to the list here for the new folder name you added above: https://github.com/mozilla/brackets/blob/master/src/utils/BrambleExtensionLoader.js#L16-L40
* Test it, and fix bugs!

We may find that this negatively affects performance and don't want it by default, see https://github.com/DennisKehrig/brackets-show-whitespace/issues/16

**Comment by humphd** [comment]
I'm morphing this bug to be about adding the UI necessary for toggling whitespace on/off.  By default in https://github.com/mozilla/brackets/pull/630 we're adding this extension to be not loaded.  We should add a pref that allows the user to enable/disable it (it's actually already available in the extension's `main.js` file, we just have to use it).

![image](https://cloud.githubusercontent.com/assets/427398/24016015/da052412-0a60-11e7-88a3-c5a2b257f56f.png)

**Comment by humphd** [comment]
@tonypark0403 the work in https://github.com/mozilla/thimble.mozilla.org/issues/1896 is very similar to what you're going to do, so you might want to collaborate.

**Comment by humphd** [comment]
I'm just reviewing the Brackets side of this now, and a note for implementing this toggle on the Brackets side.  In https://github.com/mozilla/brackets/blob/master/src/extensions/default/bramble/lib/RemoteCommandHandler.js#L68 when you add your remote command for enabling/disabling this, you need to do code like this:

```js
whitespacePrefs = PreferencesManager.getExtensionPrefs("denniskehrig.ShowWhitespace");
whitespacePrefs.set("enabled", true); // or false, depending on what you want to do
```

That should toggle the enabled pref on/off.

**Comment by humphd** [comment]
I've merged the [Brackets portion](https://github.com/mozilla/brackets/pull/630) of this (or at least the first part of the Brackets bit).  The API side and the Thimble UI portion can happen now.

**Comment by flukeout** [comment]
Awesome, happy about this! Nice work so far on this @tonypark0403

**Comment by humphd** [comment]
@tonypark0403 take a look at https://github.com/mozilla/brackets/commit/b524178098f17ccf129268daf4664493916835cb for ideas on how to add the Brackets portion of the API you need.

**Comment by humphd** [comment]
@tonypark0403 you might want to look at @cgsingh's work in https://github.com/mozilla/thimble.mozilla.org/pull/1787, since he got the value to stick between refreshes for his preference.

**Comment by humphd** [comment]
This shipped, closing.
