### ISSUE TITLE
Give me option to remix project on My Project Page

### ISSUE THREAD

**Issue by jgmac1106** [mozilla/thimble.mozilla.org#1766]
It currently takes me four clicks to remix my own project. It should be less
* Either put a remix button on the my projects page
* Count renaming project as saving a new project kind of like hitting "Save As"

I know this issue exists but I couldn't find it so feel free to delete this as duplicate.

I have to use a lot of templates I make for students and I often start editing the original project and forget I need to open project, hit publish project, click on the link, and then hit remix.

**Comment by flukeout** [comment]
#1626 deals with adding the link to the published project on that page too which would be helpful, these issues can definitely be tackled together.

**Comment by rajivjhaimin** [comment]
@flukeout  I would like to start contributing in thimble, with this being my first.

**Comment by humphd** [comment]
@rajivjhaimin It looks like @flukeout did some of the work for this in https://github.com/mozilla/thimble.mozilla.org/pull/1775.  @flukeout can you update this bug with what needs to happen?

**Comment by flukeout** [comment]
Hey @jgmac1106 - we've made some changes that will be landing shortly that show you the Published Project link on the projects list. Now, if something is published, you can click on that and remix it. It will be way simpler than before. Does this solve your need, or are you looking to be able to duplicate projects that aren't published yet, for example.

<img width="679" alt="image" src="https://cloud.githubusercontent.com/assets/25212/23561313/9bd9fc4e-fff2-11e6-999b-0c382ff177d7.png">

Let us know. Cloning projects on the projects list makes a lot of sense too.

**Comment by jgmac1106** [comment]
two clicks is better than four but one is better than two

also there is an icon for delete but not one for published and remix. If you can fit in all three why not go with live (possible earth icon) remix (arrows or something) delete (already has can)

What you suggests will work and fit my use case.

**Comment by jgmac1106** [comment]
Way out of left field here but what if we started using vocab of the discipline. Remix has never localised well.

Published Version=Production
Saved but published=Staging
Remix=Fork

**Comment by flukeout** [comment]
Closing as this has been addressed in #1900 - woo!
