### ISSUE TITLE
Modernize codebase

### ISSUE THREAD

**Issue by gideonthomas** [mozilla/thimble.mozilla.org#1767]
We have no need for requirejs/Grunt in this repository and it is slowly showing its limitations (as can be seen in https://github.com/mozilla/thimble.mozilla.org/issues/1630#issuecomment-281147850). 

We should slowly move towards using CommonJS + Babel + Webpack so that our build becomes a little less involved and we can use CommonJS features that requirejs does not provide a built-in solution for (like requiring in json files) without worrying about size of built output. 

This will be a slow process as it is a big lift for the codebase.

**Comment by humphd** [comment]
Closing until this becomes necessary.
