### ISSUE TITLE
Strange 404 page behaviour & appearance

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.mozilla.org#1768]
Check out the following links...
* https://thimbleprojects.org/mozillalearning/213466/blah.blah
  * Funky background image
* https://thimbleprojects.org/mozillalearning/213489/zing
  * Pink background

In both of these projects, styles from that projects ``style.css`` are being applied to the 404 page.

**Comment by gideonthomas** [comment]
This was a bug in the error page we show. It had a link tag to `style.css` which was causing this issue.

I've updated the error page. Should be fixed now.

**Comment by flukeout** [comment]
👍
