### ISSUE TITLE
Help text in HTML quick edit shows <br> tag instead of new line

### ISSUE THREAD

**Issue by matthieu-foucault** [mozilla/thimble.mozilla.org#1772]
See screenshot:
![screenshot from 2017-02-21 15-59-04](https://cloud.githubusercontent.com/assets/2684022/23190822/0d77ae74-f84f-11e6-8789-739695111f91.png)

The french version also shows the HTML escape codes (`&lt;` `&gt;`) instead of the brackets: 
![screenshot from 2017-02-21 16-01-13](https://cloud.githubusercontent.com/assets/2684022/23190833/2e63f62e-f84f-11e6-85be-f5e9a9f0b4ae.png)

**Comment by humphd** [comment]
I wonder if this is just our bug, or if Adobe has this same issue upstream in http://brackets.io/?  Thanks for filing.

**Comment by humphd** [comment]
@gideonthomas is this our double-localization scripts escaping things in Adobe's nls strings?

**Comment by matthieu-foucault** [comment]
I checked on brackets (v 1.8), and this bug is not present there.

**Comment by humphd** [comment]
Excellent, thank you @matthieu-foucault.  @gideonthomas so this means our localization code is escaping these when it runs over the strings.  Can you put some info in this bug to guide a contributor to fix things, please?

**Comment by gideonthomas** [comment]
Sure, I'll need to take a look at what's causing this first.

**Comment by humphd** [comment]
I'm pretty sure this is fixed with the escaping patch we did in Brackets for generating the locales.  @gideonthomas can you close if you agree?

**Comment by gideonthomas** [comment]
This is def fixed
