### ISSUE TITLE
Add a way to preview markdown files

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.mozilla.org#1773]
It would be nice to be able to preview markdown files in the right-side pane. Currently it's not possible.

**Comment by flukeout** [comment]
Whoa, did Thimble just generate an HTML file based on my markdown file??

**Comment by humphd** [comment]
Yep :) I wrote this *for* you long ago.  It's the same thing we do with LESS to CSS files.  I love when you (re)discover things I've added at your request.

**Comment by flukeout** [comment]
I'm so spoiled.
