### ISSUE TITLE
Choosing "Upload" twice and canceling them causes Brackets to hang/unusable 

### ISSUE THREAD

**Issue by Shank09** [mozilla/thimble.mozilla.org#1779]
When Upload is chosen twice or more, Brackets hangs and doesn't respond to click/key-strokes.

![thimble](https://cloud.githubusercontent.com/assets/11877279/23276508/8eb3af3a-f9d8-11e6-9953-c10c4c8f73fc.gif)

It seems to be waiting to close the Upload window, and reloading the page resolves this issue.

Steps to reproduce:
1. Click Upload
2. Click Upload again while the 1st Upload window is still open. 
3. Click Cancel
4. Try to use Brackets. 

Maybe we can disable the toolbar while in the Upload window.

**Comment by humphd** [comment]
Nice catch!  To fix this, we probably should start by not having Brackets double-open this dialog.  We have 2 spots we could do this:

* https://github.com/mozilla/brackets/blob/master/src/extensions/default/bramble/lib/RemoteCommandHandler.js#L142
* https://github.com/mozilla/brackets/blob/master/src/extensions/default/UploadFiles/main.js#L13

I'd probably do the latter, and hold a reference to the current dialog, checking if it exists before we call that code to `.show()`.

**Comment by mfainshtein4** [comment]
I'd like to give this bug a shot.

**Comment by Shank09** [comment]
@mfainshtein4 Sorry, I already worked on this and creating a pull request soon.

**Comment by mfainshtein4** [comment]
Okay. In the future comment on the issue to say you are working on it please.

**Comment by humphd** [comment]
@Shank09 where is this at?  Are you indeed still working on it?  If not, please let us know so someone else can fix it.

**Comment by Shank09** [comment]
Yes I'm still working on it. I lost my local branch, when i tried to reclone the brackets repo.
Everything is fine now. 
I am trying to see why it doesn't reopen when the cancel button is pressed. It doesnt seem to set `_uploadDialog` back to `null`

https://github.com/mozilla/brackets/pull/621

**Comment by Shank09** [comment]
This issue can be closed. Merged with [#621](https://github.com/mozilla/brackets/pull/621)
