### ISSUE TITLE
Drop down menus on Your Projects page overflow past the edge of the page.

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.mozilla.org#1780]
See here...

![horiz](https://cloud.githubusercontent.com/assets/25212/23284012/f4779d5e-f9dd-11e6-99c0-c35b7c3f9917.gif)

**Comment by flukeout** [comment]
On the homepage they're positioned correctly, so we need to use the same code here.

![image](https://cloud.githubusercontent.com/assets/25212/23284035/1b2abc42-f9de-11e6-83ad-392a7cc58193.png)

**Comment by humphd** [comment]
Whoever works on this, you can compare:

* https://github.com/mozilla/thimble.mozilla.org/blob/master/views/homepage/userbar.html
* https://github.com/mozilla/thimble.mozilla.org/blob/master/views/editor/userbar.html

and

* https://github.com/mozilla/thimble.mozilla.org/blob/master/views/homepage/index.html#L25-L26
* https://github.com/mozilla/thimble.mozilla.org/blob/master/views/editor/index.html#L4-L5

**Comment by rkgupta21** [comment]
I would like to work on this bug

**Comment by flukeout** [comment]
Go for it @rkgupta21
