### ISSUE TITLE
add a CONTIBUTING.md file

### ISSUE THREAD

**Issue by Pomax** [mozilla/thimble.mozilla.org#1784]
Right now there is no explanation of what contributions should concretely look like, and what procedures we'd like to see people follow in order to work on the code and submit PRs.

We've already seen some of the issues this leads to with CDOT contributions: accidental pulls from master, mixed spaces and tabs, empty PR commit messages, and questions about process in the channel that we should have already answered with a contribution document =)

Let's get some guidelines written @gideonthomas @humphd @flukeout

**Comment by gideonthomas** [comment]
adding to this, as you suggested in chat, let's add linting/style-guide checks with eslint as well.

**Comment by gideonthomas** [comment]
This work is done
