### ISSUE TITLE
Hover effect missing for Upload dialog and color consistency  

### ISSUE THREAD

**Issue by Shank09** [mozilla/thimble.mozilla.org#1790]
I was working on Bug #1779 and wanted to add hover effects to the buttons and change the color of "From your computer" for dark to match thimble's color scheme.
 
![bug 2](https://cloud.githubusercontent.com/assets/11877279/23342169/8c8ceb8e-fc23-11e6-8f2a-78ea455cd586.gif)

I'll do a pull request for both bugs soon, if its okay.

**Comment by gideonthomas** [comment]
cc @flukeout

**Comment by Shank09** [comment]
@gideonthomas 
Quick question.

Should I create a new ui variable or change the color values of the default button?
Current variables:
[brackets_core_ui_variables.less#L108 ](https://github.com/mozilla/brackets/blob/master/src/styles/brackets_core_ui_variables.less#L108)


It is being used in the following:
[brackets_patterns_override.less#L1509](https://github.com/mozilla/brackets/blob/master/src/styles/brackets_patterns_override.less#L1509-L1513)
[brackets_patterns_override.less#L1610](https://github.com/mozilla/brackets/blob/master/src/styles/brackets_patterns_override.less#L1509-L1513)


If creating new variables, it will require changes these also
![screen shot 2017-04-16 at 8 37 03 pm](https://cloud.githubusercontent.com/assets/11877279/25075568/6221cb9c-22e5-11e7-8781-9050dde74876.png)

**Comment by flukeout** [comment]
Hey @Shank09 - sorry for taking a while to get back to you.

I think it's OK to change the variable values in ``brackets_core_ui_variables.less``

Another option would be to change / overwrite them in ``bramble_overrides.less`` - maybe see if that works first?

What are your plans for the actual colors for the buttons? I guess we should go with green on both themes huh? Not sure about secondary button, just a gray that works well on both themes?
