### ISSUE TITLE
Trying to write closing square bracket on French keyboard folds code

### ISSUE THREAD

**Issue by matthieu-foucault** [mozilla/thimble.mozilla.org#1791]
In all editors (HTML, CSS or Javascript), typing a closing square bracket (`]`) with a [french keyboard](https://upload.wikimedia.org/wikipedia/commons/c/ca/Azerty_fr.svg) (`Alt Gr + )`) triggers a shortcut that folds the code.

This behavior is not present in brackets v1.8

**Comment by humphd** [comment]
Not good.  Possibly related https://github.com/mozilla/thimble.mozilla.org/issues/1646#issuecomment-281541204.

These get defined in Brackets here: https://github.com/mozilla/brackets/blob/master/src/extensions/default/CodeFolding/main.js#L51-L56

It's odd that we're doing something different from 1.8 on desktop.

**Comment by matthieu-foucault** [comment]
These keys seem to be disabled with a French layout on desktop:
Here is the menu when brackets is started with a French layout:
![menufrlayout](https://cloud.githubusercontent.com/assets/2684022/23345212/2b3a27c2-fc3f-11e6-9f3a-a4a863be2ba3.png)
And here is the same menu with an English keyboard layout:
![menuenlayout](https://cloud.githubusercontent.com/assets/2684022/23345216/417cdda4-fc3f-11e6-9e50-59992b883ef9.png)

Is it possible that Thimble fails to pass some keyboard layout information to the editor?

**Comment by humphd** [comment]
Possibly related:

* https://github.com/adobe/brackets/issues/6209
* https://github.com/adobe/brackets/issues/6132

and some others.  They make it sound like it was dealt with, but clearly that's not the case.

I looked for code that does layout specific checks, and at one point they were thinking about it: https://github.com/adobe/brackets/pull/9652

But I can't (yet) see why they are doing different things in the menus you showed.  It would be interesting to see if anything is calling this, which is where I'd expect that binding gets stripped:

https://github.com/adobe/brackets/blob/f028b3ecdf2017498196f39ddbbe4a2364366c92/src/command/Menus.js#L843

This is an interesting bug.

**Comment by Pomax** [comment]
Do browsers have alt-gr detection at all? (http://stackoverflow.com/questions/10657346/detect-alt-gr-alt-graph-modifier-on-key-press is not encouraging, but also an older post)

**Comment by matthieu-foucault** [comment]
Pressing Alt-Gr emits two keydown events, one for the left control key and one for the right alt key: 

```
KeyboardEvent {key: "Control", code: "ControlLeft", location: 1, ctrlKey: true, altKey: false ...}
KeyboardEvent {key: "Alt", code: "AltRight", location: 2, ctrlKey: true, altKey: false ...}
```

The codes combination is `ControlLeft` and `AltRight`, so I guess you could add listeners on keydown/keyup events to disable shortcuts when this combination of keys is pressed.

**Comment by matthieu-foucault** [comment]
In Brackets there is a function that is supposed to detect the altGr key: https://github.com/adobe/brackets/blob/f028b3ecdf2017498196f39ddbbe4a2364366c92/src/command/KeyBindingManager.js#L242

**Comment by matthieu-foucault** [comment]
.... which does nothing if the platform is not windows. What is the value of `brackets.platform` in Bramble? Same as the client's OS?

**Comment by humphd** [comment]
Should be same as client OS, as per browser https://github.com/mozilla/brackets/blob/master/src/utils/Global.js#L71

**Comment by humphd** [comment]
I'm interested if this is still happening now that we've landed https://github.com/mozilla/brackets/pull/644.  @matthieu-foucault when you have some time, can you please test again at https://bramble.mofostaging.net?

**Comment by matthieu-foucault** [comment]
The issue is now fixed on the staging server. Closing this bug.

**Comment by humphd** [comment]
Excellent, thanks for testing!  We're hoping to deploy to prod soon, so should get fixed for real.
