### ISSUE TITLE
Fix CSP warning in Firefox

### ISSUE THREAD

**Issue by humphd** [mozilla/thimble.mozilla.org#1792]
```
Content Security Policy: Directive ‘frame-src’ has been deprecated. Please use directive ‘child-src’ instead.  (unknown)
```

We should update our CSP definitions:

https://github.com/mozilla/thimble.mozilla.org/blob/master/server/security.js#L8-L53

See also #1595

**Comment by gideonthomas** [comment]
Actually we have both `frame-src` and `child-src`. `frame-src` might be deprecated but we use it because Edge only supports that directive and not `child-src`.

**Comment by Pomax** [comment]
@gideonthomas  are you sure about that? Microsoft advocates ditching frame-src in https://docs.microsoft.com/en-us/microsoft-edge/dev-guide/security/content-security-policy

**Comment by gideonthomas** [comment]
Hmm interesting. [MDN](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/child-src) and https://content-security-policy.com/ say that Edge does not support it. Maybe they're out of date?

**Comment by Pomax** [comment]
If there's a simple test page somewhere I can point Edge at it and see what it does.

**Comment by shubham0794x** [comment]
I would like to work on this issue.

**Comment by humphd** [comment]
@shubham0794x if you want to, sure.  However, can I ask that you please take only 1 bug at a time, so that we don't block other contributors who also want to fix things?  We have many, many new contributors (like yourself) who are eager to get involved, and we want to try and include as many people as possible.

A related bug that I'd like to see fixed, either at the same time as this, or in addition, is https://github.com/mozilla/thimble.mozilla.org/issues/1595

**Comment by shubham0794x** [comment]
Okay Sir I would like to work on this issue only .

**Comment by shubham0794x** [comment]
@humphd @gideonthomas  Sir can we come back to solving this issue?

**Comment by humphd** [comment]
@shubham0794x I'm not sure what you're asking.  Are you saying you'd like to do it, or that you want to give it up to someone else?  Either is fine.  Thanks for clarifying.

**Comment by shubham0794x** [comment]
Sir , I would like to fix it . Sorry for confusion .  Would you provide more background information about the bug .

**Comment by shubham0794x** [comment]
@humphd  Sir , I am not getting what problem we are facing when Directive ‘frame-src’ has been deprecated  instead of  directive ‘child-src’ . ?

**Comment by humphd** [comment]
@shubham0794x I think we need to delete https://github.com/mozilla/thimble.mozilla.org/blob/master/server/security.js#L15-L19, but first, we need to make sure that the browsers we support don't need it, in particular Edge.

**Comment by shubham0794x** [comment]
Sir , I think I found your concern : https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP
"Browsers that don't support it still work with servers that implement it, and vice-versa: browsers that don't support CSP simply ignore it, functioning as usual, defaulting to the standard same-origin policy for web content. If the site doesn't offer the CSP header, browsers likewise use the standard same-origin policy."

**Comment by humphd** [comment]
Gonna close, since we don't want to break IE.
