### ISSUE TITLE
Clarify README about localhost:3000/account

### ISSUE THREAD

**Issue by humphd** [mozilla/thimble.mozilla.org#1793]
In our README we say [to go to localhost:3000/account](https://github.com/mozilla/thimble.mozilla.org/#sign-in).  When you do, you get this:

![image pasted at 2017-2-27 23-01](https://cloud.githubusercontent.com/assets/427398/23372933/acd103bc-fceb-11e6-8b56-c1570731bc0e.png)

This all seems odd to me.  Can someone clarify what we are saying in the README or fix the login stuff to do what you'd expect?

cc @cadecairos

**Comment by gideonthomas** [comment]
Hmm, damn, forgot to remove that. Those instructions should be removed entirely. You create an account by simply going to Thimble and clicking "Create an account" in the top-right corner and following the instructions there.

**Comment by cadecairos** [comment]
It looks like a front-end build step might not be completing like it should. Anything in the build log indicating that?

Also, yes - using the signup on thimble is way easier

**Comment by JohnEJames** [comment]
I would like to fix this issue @gideonthomas

**Comment by Pomax** [comment]
@JohnEJames it's yours, have at it!
