### ISSUE TITLE
Update our Google Analytics event tracking approach

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.mozilla.org#1794]
Currently, we have methods in our code that send events to Google Analytics. All of them have an Event Category of ``thimble.mozilla.org`` and only use the **Event Action** to convey information. 

GA Events can have the following properties...

* Category
* Action
* Label (optional, but recommended)
* Value (optional)

...and we can make better use of this structure.

Our current analytics setup enables us to send an event and specify the label and value fields, like this...

```analytics.event("NormalPreview", {label: "User switched to normal preview mode vs. tutorial"});```

However, they're all stuck under the ``thimble.webmaker.org`` Category. We should refactor our code to give us control over the category, then we could divide events into logical groups...

* Home page actions 
  * Search, filter, which projects are remixed
* Editor UI
  * Font size, mobile preview, etc.
* Publishing & Project actions
  * Renaming, publishing, updating publishing etc

**Comment by flukeout** [comment]
Any thoughts on this @gideonthomas and @humphd?

The ``webmaker-analytics`` module automatically assigns the ``category`` based on the hostname, which we more fine-grained control over. Should we just take what's in the module and adapt it to our own needs? I'm happy to do that.

**Comment by humphd** [comment]
I wrote much of that code originally :) it's in https://github.com/mozilla/webmaker-analytics.  I think you should fork it and do whatever you want, or just take the https://github.com/mozilla/webmaker-analytics/blob/master/analytics.js file and fix the way it does category stuff (it defaults to hostname).

**Comment by flukeout** [comment]
Okay, I'm working on this now and restructuring all of our event calls. Here's an example of a new style of call...

``analytics.event({ category : "Editor UI", action : "Toggle JavaScript", label : "Enabled" });```

**Differences**
* Each call will set its own Category, which will include:
  * **Editor UI** - everything related to the editor
  * **Project Actions** - deleting, creating & renaming projects
  * **Homepage** - related to searching and remixing from the new homepage gallery

In addition, I'll have calls work as pairs so instead of separate events with actions like ``Javascript Enabled`` and ``Javascript Disabled`` we will have the following...

* ``analytics.event({ category : "Editor UI", action : "Toggle JavaScript", label : "Enabled" });``
* ``analytics.event({ category : "Editor UI", action : "Toggle JavaScript", label : "Disabled" });``
