### ISSUE TITLE
Fix incorrect use of "login" to "log in".

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.mozilla.org#1795]
A contributor found this string somewhere within Pontoon...

![image](https://cloud.githubusercontent.com/assets/25212/23413704/6044751c-fd8e-11e6-90fe-b2e50b79afa1.png)

Must be some kind of system error, but let's get it updated anyway.

**Comment by gideonthomas** [comment]
Fixed with 77d48ed0ff440bc1830fb5cb38a0cf263efc2a86
