### ISSUE TITLE
Unable to access the service through my account

### ISSUE THREAD

**Issue by kariya22** [mozilla/thimble.mozilla.org#1798]
When i want to start a new project and view my project it shows: 
Service Unavailable (503): Failed to get the list of your projects!
Service Unavailable (503): Failed to create the project!

**Comment by SidneyNemzer** [comment]
See #1797

**Comment by kariya22** [comment]
but how can i get access to the projects, i even tried create another account it shows the same error message....i have an assignment due today and now i am clueless.

**Comment by humphd** [comment]
@kariya22 I'm really sorry you're having this issue.  We use Amazon's S3 service for file storage and publishing, and it is currently down, which is affecting a huge part of the Internet.  We can't access the projects as a result.

In terms of your assignment being due today, please let them know that it's an outage, and not your fault.  Feel free to point them at this, and I can provide any details they need.
