### ISSUE TITLE
Several strings changed without updating the string ID

### ISSUE THREAD

**Issue by TheoChevalier** [mozilla/thimble.mozilla.org#1801]
Several strings have been updated over the past months, but the string ID has not been updated. If IDs are not updated, translations are not invalidated, and localizers are not warned that the source string has changed. Doing so results in updating en-US only, and not the other locales.

See also this page to understand when IDs need to be updated and when they don’t: https://developer.mozilla.org/en-US/docs/Mozilla/Localization/Localization_content_best_practices#Changing_existing_strings
Happy to answer questions, too

Tonnes and I identified the following commits with string updates without an ID change:

https://github.com/mozilla/thimble.mozilla.org/commit/1f4b98799227fd80d6cf8345a9998ef00ced636f
https://github.com/mozilla/thimble.mozilla.org/commit/bc500a8550e0b3d82e7cff4eae365300c16b4b44
https://github.com/mozilla/thimble.mozilla.org/commit/adf9a5f79f7828e2b025cc673c412dff823d2928
https://github.com/mozilla/thimble.mozilla.org/commit/612e0eedff6a5dadf8c30fefb2697123fd5912b4
https://github.com/mozilla/thimble.mozilla.org/commit/59bb2d8696be5963dccef75d967f888c17b9c887

Side note, please don’t commit changes in other locales, even if in this case en-GB is really close to en-US: https://github.com/mozilla/thimble.mozilla.org/commit/bc500a8550e0b3d82e7cff4eae365300c16b4b44#diff-1b35da63addb17b2751083c61013aac6

**Comment by TheoChevalier** [comment]
CC @gideonthomas @flukeout

**Comment by gideonthomas** [comment]
Oh wow, yeah we definitely weren't aware of that. I'll make those changes soon. Thanks for pointing these out @TheoChevalier and also for linking to that document about best practices as well.

**Comment by gideonthomas** [comment]
@TheoChevalier I'm a bit hesitant to change the ids in this commit: 612e0ee. All the changes made there reflect back in mozilla/brackets which is a fork of adobe/brackets. They have their ids set to specific names they use in their codebase. I would rather not go deep into their core code and change these keys (it'll make it hard for us to keep up-to-date with upstream changes). Any suggestions on how I could approach this? Maybe I could send an email to dev-l10n about those changes or something? Any advice is appreciated.

**Comment by TheoChevalier** [comment]
Hey @gideonthomas, yes, there are indeed cases where IDs can’t be updated (it’s sometimes the case in products too), and your approach is the right one, sending a message to the mailing list communicating the change and linking to the diff. I would suggest however to send this to mozilla.dev.l10n.**web** [1], mozilla.dev.l10n [2] is for products only.

[1] https://groups.google.com/forum/#!forum/mozilla.dev.l10n.web
[2] https://groups.google.com/forum/#!forum/mozilla.dev.l10n

**Comment by gideonthomas** [comment]
Awesome! Thanks for the input @TheoChevalier. Will do that.
