### ISSUE TITLE
Remix resources not loading

### ISSUE THREAD

**Issue by humphd** [mozilla/thimble.mozilla.org#1804]
Given https://thimbleprojects.org/jgmac1106/223453/, I'm seeing 404s for all our remix resources:

```

https://thimbleprojects.org/jgmac1106/223453/undefined/resources/remix/clean-slate.min.css Failed to load resource: the server responded with a status of 404 (Not Found)
https://thimbleprojects.org/jgmac1106/223453/undefined/resources/remix/style.css Failed to load resource: the server responded with a status of 404 (Not Found)
https://thimbleprojects.org/jgmac1106/223453/undefined/projects/remix-bar?_=1488564992284 Failed to load resource: the server responded with a status of 404 (Not Found)
index.js:1 [Thimble Error] Unable to inject Remix UI. Error was: `error`
https://thimbleprojects.org/jgmac1106/223453/undefined/resources/remix/style.css Failed to load resource: the server responded with a status of 404 (Not Found)
https://thimbleprojects.org/jgmac1106/223453/undefined/resources/remix/clean-slate.min.css Failed to load resource: the server responded with a status of 404 (Not Found)
```

NOTE the `undefined` in all those URLs. cc @cadecairos, @gideonthomas, @jgmac1106

**Comment by gideonthomas** [comment]
None of the remix metadata was injected into the code because we can't find the `<head>` element which is what we look for here: https://github.com/mozilla/publish.webmaker.org/blob/master/lib/remix.js#L24-L29

**Comment by humphd** [comment]
@Pomax what should we do when there's no `head`?  We should morph this bug into fixing that.

Having said that, why all the `undefined`s in the URLs?

**Comment by gideonthomas** [comment]
I don't think we run `undefined` checks in the "get remix bar" script so it still makes the requests.

**Comment by lkisac** [comment]
I would like to work on this bug

**Comment by humphd** [comment]
All yours, @lkisac!

**Comment by Pomax** [comment]
Actually this is an interesting case: when I load up view-source:https://thimbleprojects.org/jgmac1106/223453/ it looks like @jgmac1106 used `<header>` instead of `<head>` and thimble should have absolutely warned him about the fact that there is body content outside the `<body>` tag.

**Comment by lkisac** [comment]
@Pomax  I checked the project for any kind of html validation - is there already some type of handler for validating html, or would this be an entirely new feature?

**Comment by lkisac** [comment]
The files I am working on for this bug are [HTMLParser.js](https://github.com/mozilla/slowparse/blob/8a5f9e1045714c216acfe65f73ac5862648ed962/src/HTMLParser.js) and [ParseErrorBuilders.js](https://github.com/mozilla/slowparse/blob/8a5f9e1045714c216acfe65f73ac5862648ed962/src/ParseErrorBuilders.js).  When loading Brackets from localhost:8000, the `src/thirdparty/slowparse` folder does not appear to be on the server.  How is Brackets using slowparse, or if it no longer is, how is the HTML being parsed for validation?

**Comment by humphd** [comment]
There are a few ways to go here


Brackets has a DOM

* We could use the browser's built-in HTML parser via [`DOMParser`](https://developer.mozilla.org/en-US/docs/Web/API/DOMParser).  The advantages of this are that it's fast, and that it's the most complete and accurate parser you can get.  The downside is that it isn't designed to produce good error messages that are actionable by a beginner.  We could use it as a guide, though, and see if it passes here, then use the result of that to make a suggestion or pass the file to another layer of testing.

* Brackets has its own parser here, which we could also use: https://github.com/mozilla/brackets/blob/master/src/LiveDevelopment/MultiBrowserImpl/language/HTMLSimpleDOM.js#L502-L513 could be used to parse the contents of `index.html` and see if you get back `null` or a valid `DOM` representation.

* We can use Slowparse.  Look at `src/extensions/extra/HTMLHinter/parser.js` which uses it now.  We don't actually load this extension at the moment, but it works, so you can use it as a guide.

Once you `requre()` the `slowparse.js` file (like `HTMLHinter` does), you'll be able to use it--it's there as a submodule.

NOTE: if you don't see that file in your `src/thirdarty` dir, you need to run `git submodule update --init`.

**Comment by lkisac** [comment]
I filed two #2241 & #2242 to address script injecting and remix metadata injecting.

**Comment by Pomax** [comment]
closing this issue in favour of the two issues @lkisac filed, plus #2243, which addresses the possible need to inform users that their HTML may be technically fine, but practically "really weird".
