### ISSUE TITLE
Remix projects redirect to dead URL on local Thimble setup

### ISSUE THREAD

**Issue by aayushsanghavi** [mozilla/thimble.mozilla.org#1811]
After setting up the project locally, trying to remix any of the first 3 projects on the homepage (ones boxed in the image below), 
![screenshot from 2017-03-06 20-02-31](https://cloud.githubusercontent.com/assets/19590302/23614396/ab5c301c-027a-11e7-91a5-45816110d7d2.png)
gives the error,
![screenshot from 2017-03-06 20-02-42](https://cloud.githubusercontent.com/assets/19590302/23614401/b2052ba8-027a-11e7-9314-50374a371429.png)

**Comment by ryanwarsaw** [comment]
This issue is caused by invalid URL references for front-page resources in the ```env.dist``` file, all references of ```thimble-beta.webmaker.org``` have to be updated to ```thimble.mozilla.org```. 

See: https://github.com/mozilla/thimble.mozilla.org/blob/master/env.dist#L81

**Comment by aayushsanghavi** [comment]
@ryanwarsaw I'll take it up
