### ISSUE TITLE
Uncaught TypeError: bramble.getAutoUpdate is not a function

### ISSUE THREAD

**Issue by lkisac** [mozilla/thimble.mozilla.org#1814]
After pulling the latest upstream for brackets and thimble,

brackets:
<ul>
<li>git checkout master</li>
<li>git pull upstream master</li>
<li>npm install</li>
</ul>

thimble:
<ul>
<li>git checkout master</li>
<li>git pull upstream master</li>
<li>vagrant destroy</li>
<li>vagrant up</li>
</ul>

I'm getting "_Uncaught TypeError: bramble.getAutoUpdate is not a function_" in [bramble-ui-bridge.js](https://github.com/mozilla/thimble.mozilla.org/blob/master/public/editor/scripts/editor/js/fc/bramble-ui-bridge.js#L218).

**Comment by lkisac** [comment]
I ended the brackets session (Ctrl + C) and did `vagrant halt` in thimble repo, then ran `npm run build` in brackets and it looks to have built successfully.  After running `npm start` again, then `vagrant up` I still see the error.

After the brackets build, do I maybe have to do a `vagrant destroy` before running `vagrant up` in thimble?

**Comment by humphd** [comment]
Do you have your cache disabled in Dev Tools (Network tab on Chrome Dev Tools) and are you running with them open?  For sure the fix to this is to do what I said.

**Comment by lkisac** [comment]
Yes, cache was disabled.   I gave it some time and ran `vagrant up` again and it works now...   thanks @humphd

**Comment by humphd** [comment]
cc'ing @cgsingh so he's aware, and can help other people if they have issues.  Closing since this isn't really a bug, just a process people need to follow for updating.
