### ISSUE TITLE
audit the thimble CSP

### ISSUE THREAD

**Issue by Pomax** [mozilla/thimble.mozilla.org#1817]
https://observatory.mozilla.org/analyze.html?host=thimble.mozilla.org is dinging us 20 points for having a CSP that explicitly allows http resources on https...

It's been a while since we audited our CSP, let's do so now.

**Comment by humphd** [comment]
See also:
* https://github.com/mozilla/thimble.mozilla.org/issues/1792
* https://github.com/mozilla/thimble.mozilla.org/issues/1595

I also wonder why we have things like google docs in our CSP list, see https://github.com/mozilla/thimble.mozilla.org/blob/fa3dde088dc016a562520e62a9df1f5558ba8f70/server/security.js

**Comment by humphd** [comment]
I think we're good for now on this, closing.
