### ISSUE TITLE
After merging local repo with upstream brackets

### ISSUE THREAD

**Issue by Shank09** [mozilla/thimble.mozilla.org#1819]
I was working on the Upload Dialog, and noticed that the text for the Upload file dialog box was missing after merging from the upstream.

At first i thought it was my repo only, I spent a lot of time trying to reinstall everything and tried in different computer. Also tried to only clone Mozilla's repos to test it, and the result was the same. 

<img width="612" alt="screen shot 2017-03-06 at 5 10 19 pm" src="https://cloud.githubusercontent.com/assets/11877279/23632426/cf249c18-028f-11e7-8200-78cb15b5f675.png">

I don't think these lines are getting loaded.
[https://github.com/mozilla/brackets/blob/master/locales/en-US/editor.properties#L170-L176](https://github.com/mozilla/brackets/blob/master/locales/en-US/editor.properties#L170-L176)

In the live version I can see that the [Strings variable ](https://github.com/mozilla/brackets/blob/master/src/extensions/default/UploadFiles/UploadFilesDialog.js#L14)is being loaded with the Upload dialog box contents.
<img width="849" alt="screen shot 2017-03-06 at 5 06 54 pm" src="https://cloud.githubusercontent.com/assets/11877279/23633141/920aed66-0292-11e7-9e32-d96bf339272b.png">

However in the dev environment it is not.
<img width="848" alt="screen shot 2017-03-06 at 5 08 24 pm" src="https://cloud.githubusercontent.com/assets/11877279/23633148/9361fe70-0292-11e7-8945-905efc5a038c.png">

I'm also getting this error:
<img width="794" alt="screen shot 2017-03-06 at 5 35 10 pm" src="https://cloud.githubusercontent.com/assets/11877279/23633330/570dea1e-0293-11e7-8401-c9e43f60451e.png">

**Comment by humphd** [comment]
The last error is ignorable, and is due to running in `src/` vs. `dist/`  The other one sounds like the localization stuff needs to run.  @gideonthomas ?

**Comment by flukeout** [comment]
I think this is a problem with the localization stuff @Shank09 

Try running these commands in your terminal from the root of the the Project folder:

* vagrant ssh
* cd /vagrant
* npm run localize
* npm run localize-client

**Comment by Shank09** [comment]
@flukeout 
Unfortunately it did not work. I still cannot see the text.

**Comment by flukeout** [comment]
Did the ``npm run localize`` command build a set of locale files and display which files it created in the terminal?

**Comment by Shank09** [comment]
Yes, i think so. I didn't see any errors while running those commands. 
```
vagrant@vagrant-ubuntu-trusty-64:/vagrant$ npm run localize

> thimble.mozilla.org@2.0.0 localize /vagrant
> node scripts/properties2json.js

Skipping  bg  due to missing strings
Skipping  sk  due to missing strings
Done writing: /vagrant/dist/locales/en_US/messages.json
Done writing: /vagrant/dist/locales/bn_BD/messages.json
Done writing: /vagrant/dist/locales/az/messages.json
Done writing: /vagrant/dist/locales/es/messages.json
...
vagrant@vagrant-ubuntu-trusty-64:/vagrant$ npm run localize-client

> thimble.mozilla.org@2.0.0 localize-client /vagrant
> node scripts/localize-client.js

Successfully localized the client at:  /vagrant/client
```

**Comment by Shank09** [comment]
I'm still having this issue.
Here is a fast video of installing thimble and brackets.
https://youtu.be/upkfMYJLOxs

Did I forget anything?

**Comment by flukeout** [comment]
No you didn't - it's happening for me as well, even after running the localization steps that usually fix problems like these.

cc @gideonthomas @humphd

**Comment by humphd** [comment]
What happens when you run brackets from `http://localhost:8000/src/hosted.html`, does that work with strings?

**Comment by humphd** [comment]
@MargarytaChepiga is reporting a similar issue with the dialog box that should indicate when a dnd of a .zip file finishes--we usually show a message saying "it worked" but nothing is happening at the moment.

I also think #1862 is likely related.  I'd advise @Shank09, @MargarytaChepiga, and @dangkhue27 all co-ordinate their knowledge/efforts on this.  I'm not 100% sure what the right fix is, and I think I need @gideonthomas to help.

**Comment by humphd** [comment]
We've got process fixes for this now, closing.
