### ISSUE TITLE
Watch for l10n changes

### ISSUE THREAD

**Issue by gideonthomas** [mozilla/thimble.mozilla.org#1823]
Let's automate builds for client code when changes to the l10n files (inside the `locales/en-US`) are made. I think it's as simple as watching the `en-US` directory for changes and then running `npm run localize`, `npm run localize-client` and `npm run restart-server`.

We can probably try to figure out optimizations (for e.g. running only one of `localize-client` or `restart-server` depending on whether the change was made in the client or the server) but should probably start with just implementing the above.

**Comment by pranay414** [comment]
@gideonthomas I would like to work on this?

**Comment by gideonthomas** [comment]
Yeah go for it

**Comment by pranay414** [comment]
how to begin?

**Comment by Pomax** [comment]
A simple place to start would be to define an `npm` script that starts up [chokidar](https://www.npmjs.com/package/chokidar) for watching changes to the `locales/en-US` directory, and have that trigger the localization scripts that are already in our package.json file for updating the other locales.

**Comment by humphd** [comment]
NOTE: we have a few scripts in https://github.com/mozilla/thimble.mozilla.org/tree/master/scripts that do things like this, and could be copied/added to.  I think @gideonthomas should let us know the right path here, since he's written most of this code.

**Comment by gideonthomas** [comment]
You need to write another watch script in the folder that @humphd links to above. Let's call it `watch-strings.js`

Use [this file](https://github.com/mozilla/thimble.mozilla.org/blob/master/scripts/watch-client.js) as a reference as the watch logic is similar. You basically just need the following pieces of logic:
- https://github.com/mozilla/thimble.mozilla.org/blob/master/scripts/watch-client.js#L56-L60 to set up the watcher. You will watch the `locales/en-US/messages.properties` file instead and only listen for the `change` event instead of the `all` event. It should be as simple as writing:
```js
watcher.on("change", (event, filePath) => {
  if(event !== "change") {
    return;
  }

  // logic for what happens when the en-US/messages.properties file changes
});
```
- For the piece of code that deals with what happens when the file changes, you need to run two npm commands in series - `localize`, `localize-client` and then `pm2 restart thimble ; true`. You can do that by:
   1. Requiring in the `npm-run-all` module
   2. Use it to run `localize` and `localize-client`. To make it easy for the last command (`pm2 restart thimble ; true`) you can add an npm script here: https://github.com/mozilla/thimble.mozilla.org/blob/master/package.json#L78-L90, let's call it `restart-thimble` that runs `pm2 restart thimble ; true`. Now, tack on `restart-thimble` to your list of `npm-run-all` tasks as the final task. You can refer to https://github.com/mozilla/thimble.mozilla.org/blob/master/scripts/start.js to see how you can use `npm-run-all` in your script.

Finally, add an entry to https://github.com/mozilla/thimble.mozilla.org/blob/master/ecosystem.json at the end similar to https://github.com/mozilla/thimble.mozilla.org/blob/master/ecosystem.json#L40-L48 called `watch-strings` that calls your `watch-strings.js` script.

Let me know if you need any more info.

**Comment by Pomax** [comment]
this is, honestly, way more work than necessary, a single chokidar npm script can do this without needing to touch lots of files.

```
   "watch:locales": "chokidar 'locale/en-US/**' -c 'npm run localize'
```

done.

**Comment by gideonthomas** [comment]
Not sure I understand what you're saying - we don't use grunt/gulp anywhere for this. It is a plain node script. 

We can't do what you suggest above because pm2 does not allow you to run npm scripts. Each process can only point to a node script like so: https://github.com/mozilla/thimble.mozilla.org/blob/master/ecosystem.json#L51 so we'd need to use chokidar's API vs. the cli command (we can probably try invoking the cli command with `shx` or something within the node script but really the above code solution is not that much work since most of the code is already written).

**Comment by Pomax** [comment]
I did not realise pm2 was a jerk that way. Does it allow env passing so that the server can check `process.env.WATCH` for toggling the chokidar API?

**Comment by humphd** [comment]
Sure, all it's doing is running a node script.  The docs for pm2 are amazing, if you need to figure out how to do something.

**Comment by humphd** [comment]
We really need this, it trips up devs all the time, including me.

**Comment by flukeout** [comment]
Closing as in two weeks.. TWO WEEKS @gideonthomas this will be fixed.
