### ISSUE TITLE
"Add a file to your project" popup window overflows to the left side 

### ISSUE THREAD

**Issue by hkirat** [mozilla/thimble.mozilla.org#1824]
Hey

I came across this bug while working on thimble recently.
If we resize the left pane to make its width small enough on the editor page, the "add a file to your project popup window" popup window overflows to the left.

![screenshot from 2017-03-07 11-26-22](https://cloud.githubusercontent.com/assets/8079861/23643745/99270264-0329-11e7-880d-2a7d8a0f84de.png)

I would like to work on fixing this.

**Comment by flukeout** [comment]
All yours @hkirat - thank you for filing. Sounds good, go ahead - what's your general plan?

**Comment by hkirat** [comment]
I can think of two possible methods of solving this issue

1. First one involves shifting the arrow of the popup to the left most corner. This would make the popup right oriented and hence it will begin where the "add a file to your project" button starts. 
Something like this
![screenshot from 2017-03-08 15-51-08](https://cloud.githubusercontent.com/assets/8079861/23700118/e9029174-0417-11e7-8d14-7ac47b28abad.png)
Though I think some rounding up of corners might be required for it to look more apealing. 
Adding a simple check of 
```js
        if (leftOffset<0) {
          leftOffset = 0;
        }
```
over [here](
https://github.com/mozilla/thimble.mozilla.org/blob/master/public/editor/scripts/editor/js/fc/bramble-popupmenu.js#L17) does the job.

2. Making the div's position dynamic.
This would keep the position of the arrow in the middle like it is right now till the time there is no overflow. 
As the div starts to recede to the left side, the position of the div fixes to the left side, the arrow still moves. This is a bit tricky as making the arrow responsive can be a bit difficult. 
The arrow's css is written over [here](https://github.com/mozilla/thimble.mozilla.org/blob/master/public/editor/stylesheets/editor.less#L191)
The property left is to be manipulated accordingly. Write now it is hardcoded to 86 to keep it in the center of the popup.

I like the second approach better. 
Which approach do you like more?

**Comment by humphd** [comment]
I like the idea of the menu moving over, while the arrow stays put.  I'll let @flukeout give the final say, though.

Also, @hkirat thank you for getting so involved and taking on these bugs!  It's great to have you working on Thimble.

**Comment by hkirat** [comment]
Hey @humphd 
Even I like the second idea more. 
And thank you for the appreciation. It feels great to get involved with thimble.

**Comment by flukeout** [comment]
Hi @hkirat cool, yeah let's go with option 2 - move the menu over only as far as is necessary. Cheers!

**Comment by flukeout** [comment]
Hey, while you're at it, what do you think of changing the label from "Add" to "New" for each of the items. "New HTML file" sounds better than "Add HTML file"

**Comment by hkirat** [comment]
Sure will do @flukeout . 
Right now I'm a bit stuck in making the arrow responsive. There is an interesting problem that comes with the second method that we agreed to implement.

We need to modify [this](https://github.com/mozilla/thimble.mozilla.org/blob/master/public/editor/stylesheets/editor.less#L191) css property dynamically. However, since it is not a part of the DOM (:after), it is slightly tricky to do this. You cant access it directly using something like : 
$(#filetree-pane-nav-add-menu:after)
Have you seen something like this before?

**Comment by humphd** [comment]
cc @Pomax, who also might know.

**Comment by flukeout** [comment]
Let's just add the ``:after`` element into the markup as a new ``div`` with something like ``class='arrow-tip'`` - how's that sound?

**Comment by hkirat** [comment]
Sounds good. Will do that
