### ISSUE TITLE
npm test for new deps failed because of "A constructor name should start with an uppercase letter"

### ISSUE THREAD

**Issue by omytryniuk** [mozilla/thimble.mozilla.org#1829]
I was trying to update node deps for the project and CI Travis shows me an [error](https://travis-ci.org/mozilla/thimble.mozilla.org/builds/208818821)

![screenshot 2017-03-07 17 55 13](https://cloud.githubusercontent.com/assets/13225708/23687422/63ef2862-037c-11e7-94f1-d74e08f00b93.jpg)

According to it, the next [function](https://github.com/mozilla/thimble.mozilla.org/blob/master/server/lib/environment.js)
```js
var habitat = require('habitat');
habitat.load(require('path').resolve(__dirname, '../../.env'));
var env = new habitat();
``` 
is wrong, because jshint expects that an identifier following the new operator(when the newcap option is set to true)  should start with an upperCase.

**Comment by humphd** [comment]
According to http://jshint.com/docs/options/#newcap this was removed in JSHint, and your update has probably hit that.  In our `.jsintrc` we specify it, https://github.com/mozilla/thimble.mozilla.org/blob/master/.jshintrc#L11.  It looks like the combo of `use strict` is also affecting us.  Basically, this code *should* have a capital, but we didn't write it so we are at the mercy of the authors.

I bet we need to do what's done here:

https://github.com/jshint/jshint/blob/6aee2fd434cbd1fc9c449336162cec7b229ea99e/tests/unit/fixtures/strict_newcap.js#L15

**Comment by humphd** [comment]
Also, you might want to fix this at the same time you fix the node deps (same PR), since you'll need it to pass travis.

**Comment by omytryniuk** [comment]
Yes, I would like to work on it!
You are absolutely right. I have added a warning suppressor, and  successfully run "npm install" 

```js
/*jshint newcap:false */

var habitat = require('habitat');
habitat.load(require('path').resolve(__dirname, '../../.env'));
var env = new habitat();

module.exports = env;
```
