### ISSUE TITLE
Duplicate definition of indent in .jshintrc

### ISSUE THREAD

**Issue by humphd** [mozilla/thimble.mozilla.org#1830]
We are redefining `indent` in our .jshintrc file.  It should only happen once, and Thimble uses 2-spaces.  Let's remove the second one.

**Comment by hkirat** [comment]
I think this issue can be closed via #1831

**Comment by Pomax** [comment]
you're right, thanks for catching that!

**Comment by humphd** [comment]
@hkirat use `Fixes #1830: ...`  in your commit or PR message and it will do it automatically in github.
