### ISSUE TITLE
Benchmark other collaborative editing & coding environments.

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.mozilla.org#1834]
* Codepen - Broadcast / tutor mode
* Google docs
* Google presentations
* For when people are in other slides, similar to how we do files
* Komodo IDE
  * https://www.youtube.com/watch?v=Mouxx6Wlg1k
* Etherpad
* http://liveweave.com/ - using Together.JS right now for code editing.
* ...others?

**Comment by flukeout** [comment]
**Komodo Collaboration Tool**
* You create a collaboration session 
* You invite/add contacts to it (contacts are managed separately)
* This creates a blank collaboration session, and then you can..
  * Import an existing file / project
  * Create a new file / project

When collaborating, you can see..
* Other people's text cursors (not mouse pointers)
  * Different color per user and username indicated
* Live changes to files
* Other people's selections

**Other features**
* Line by line attribution
  * Seems to highlight each line (along gutter) to match the author who last edited it
* Author can remove users from a collab session

**Comment by Pomax** [comment]
jsfiddle I believe has together.js for collaborative working.

**Comment by gideonthomas** [comment]
glitch.com
