### ISSUE TITLE
Explore Google Drive API for collaboration.

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.mozilla.org#1835]
@humphd mentioned the Google Drive API as a possible approach to doing collaborative editing.

**Comment by humphd** [comment]
See https://developers.google.com/google-apps/realtime/overview.  The down side of this is that it requires you to use a Google account.  I'd argue that this isn't a huge barrier, but it's something to ponder.

**Comment by gideonthomas** [comment]
Closing since we're implementing the fs syncing using webrtc
