### ISSUE TITLE
Dev: Create basic prototype of Thimble integrated with Together.js 

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.mozilla.org#1841]
Since we're thinking of using Together.js as the mechanism to enable our real-time collaboration experience, let's try to create a basic prototype that allows two or more people to edit a Thimble project together. I think it will teach us a lot.

* Can we set up a public accessible-by-anyone thimble project to try this on?

**Comment by humphd** [comment]
One of the problems we're going to need to solve when we do this (and this bug is probably not the right place to solve this) is how to deal with state changes in the editor between the two ends.  For example, I'm looking at `index.html` and you switch to `style.css` and start typing.  We don't want that text to get put in the wrong file.

cc @simonwex, who might have 10,000 foot ideas on this.

**Comment by sudwebd** [comment]
To tackle a case like your @humphd , we can add a new functionality of multiple scrollable windows on the left side coding window ,if one user is editing the `index.html` file and another switches to `styles.css` file, then two divisions will come up on the coding region respectively for the html and css files and the users can code there in parallel. 
To manage the problem for the coding space I would suggest even a more better alternative , we can partition the windows similar to http://codepen.io where the coding region and the final preview are placed vertically , the coding window is then partitioned horizontally in css ,html and js regions.

**Comment by AnshulMalik** [comment]
I think we can work with single opened window, we can just indicate that other user is editing that file in files tree, and send only the changes made in a file across.

If you have seen [c9.io](https://c9.io), it has got a really nice collaborative editor, may be we can learn something from there.

**Comment by gideonthomas** [comment]
Closing as we're no longer using TogetherJS
