### ISSUE TITLE
Investigate technical requirements of 'shared ownership' of a Thimble Project

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.mozilla.org#1843]
Assuming we adopt a model of an explicit owner and additional (optional) collaborators per Thimble project, what are the technical implications and requirements. What will we have to re-architect about our current setup?

* We'll need a new database table to store this extra layer of data
* ...

**Comment by Pomax** [comment]
we may also need to start tracking changes as made "by someone", with rollback and back-out for unwanted contributions.

**Comment by flukeout** [comment]
I'm going to close this issue as it's related more to the 'multiple owners' use case that we're not going to be tackling right away. To your point about reverting changes, I think we can make that an option at the end of a collaboration session like [ discard changes? ] etc.
