### ISSUE TITLE
Investigate work involved in turning Together.js into a module / API that can be integrated into other projects

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.mozilla.org#1844]
Currenlty, together.js works by injecting its own UI into the host page. This might not be the best solution for Thimble (or other projects). What work would need to happen in together.js to expose its functionality via a plugin or API that can be included in other projects.

Not sure I'm using the right terminology here. But if we build our own collaboration UI, how would we wire it into together.js.

**Comment by humphd** [comment]
I think we need to re-engineer together.js to be a service and an optional UI, but that you can swap out for ours.  It would be good if we could integrate this tightly into our app vs. having to use what it provides.  It's the broadcast and discovery aspects that we need (service) vs. UI.

**Comment by Pomax** [comment]
I'd echo that - having toghether.js take care of the "under the bonnet" work without any specific UI attached, but giving hooks for listeners and signals so we can tie our own UI into it would be amazing.
