### ISSUE TITLE
Remove "navigate to previous doc" key binding

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.mozilla.org#1846]
Previous discussion is here https://github.com/mozilla/thimble.mozilla.org/issues/1646

In short, hitting Shift + Command (in that order) on a Mac causes Thimble to switch the currently edited file to a different one. We don't want this feature enabled it can be removed probably by getting rid of these lines here:

https://github.com/mozilla/brackets/blob/master/src/command/Commands.js#L119-L120

**Comment by sgupta7857** [comment]
I will like to work on this bug @flukeout

**Comment by flukeout** [comment]
Please do! I hate this keybinding!

**Comment by sgupta7857** [comment]
@flukeout I wasn't able to generate the behaviour every single time on chrome. So, I really can't fully test the edits that I have made. I have created a new branch and made the changes please see if the changes fix the issue. 

[https://github.com/sgupta7857/brackets/tree/issue-1846](url)

**Comment by flukeout** [comment]
Can you please create a Pull Request - then I'll test it out - cheers!

**Comment by sgupta7857** [comment]
@flukeout I created a pull request here 
please test the changes 
https://github.com/mozilla/brackets/pull/644

**Comment by humphd** [comment]
Best to ask for reviews in the PR vs. here in the bug.  I looked at the new code, and left a comment.

**Comment by humphd** [comment]
Fixed in https://github.com/mozilla/brackets/pull/644, closing.
