### ISSUE TITLE
Test embedding live streaming vides

### ISSUE THREAD

**Issue by humphd** [mozilla/thimble.mozilla.org#1853]
Spin-off from #1593, @kyletower writes:

> One quick thought about Cloud 9: it allows me to embed live streaming videos from connectcast.tv whereas I couldn't get the feature to work in Thimble. I was informed that the feature is blocked or not implemented in Thimble.

Let's figure out what, if anything, we can do about this.

**Comment by Pomax** [comment]
Do we have any information what aspect of the embed didn't work? (x-frame-embed forbidden, etc?)

**Comment by humphd** [comment]
No, and ideally @kyletower can give us come clues for testing.

**Comment by kyletower** [comment]
I just checked on this feature a few days ago and it does in fact work. I had to click an icon toward the top right of the Chrome browser and select "Run Unsafe Scripts".

**Comment by humphd** [comment]
It sounds like maybe they are injecting and `eval()`ing a script in order to do the embed?  If so should we close this, since it's not really something we can allow/disallow (e.g., browser sec).  @kyletower?
