### ISSUE TITLE
Add Emmet Support

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.mozilla.org#1854]
One of our users, Roberto Matthews, left a feature request on our YouTube video...

> Hello there!  I've been a long time Brackets user, but since I am always updating clients' sites, I needed a way to text and fix things online when I'm on the road.  Thanks to Thimble, I can do this very well now.  One thing would make this program even more perfect...  is there a way to add Emmet editing?﻿

Links
* http://emmet.io/
* Bracket Extension - https://github.com/emmetio/brackets-emmet

**Comment by Pomax** [comment]
It feels like this ties in with the idea of having a list of extensions (power)users can toggle through "a menu", however we end up implementing that. @humphd this feels like a good candidate for an initial extension set.

**Comment by flukeout** [comment]
I agree, and I'd wager @humphd and @gideonthomas do to. We can include some kind of advanced settings panel. Might be a cool contributor task too - port your favorite extension.

**Comment by gideonthomas** [comment]
https://github.com/mozilla/thimble.mozilla.org/issues/1585 dupe

**Comment by bkim49** [comment]
Hello, I would like to work on adding this feature. Could you assign this to me? @flukeout
