### ISSUE TITLE
Design: Insert Snippet Menu

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.mozilla.org#1855]
@twigz20 is working on adding a snippet menu in PR #1826 - it's coming along really nicely, but we need to figure out some design. 

**Needed**
* Icon & placement
* Menu design & placement

**Considerations**
* Right now in the PR, the snippet options change depending on what file is selected
  * While this is handy, I think we should have a way to access all the snippets independent of the file type
  * Many HTML pages include a ``<script>`` tag in the ``<head>`` - so the user should be able to access JS snippets while editing an HTML page.
* I think we should provide some extra context to the snippet you're adding
  * Showing the actual code is probably a good idea

..I'll drop some designs into this issue.

**A) Full-featured snippet menu**
This has a left-side menu to help you sort through the different types of snippets. It could default to the category that matches the current file you're editing (if possible).

![image](https://cloud.githubusercontent.com/assets/25212/23765179/3262deda-04b5-11e7-8023-cabf9ec422bd.png)

**B) Simplified full-featured**

Same as above, but with a condensed menu for selecting the snippet type.

![image](https://cloud.githubusercontent.com/assets/25212/23766011/179af8d2-04b8-11e7-8546-5f089ae753f5.png)

**C) Simplified**
This version lets you choose the snippet type, but doesn't show you any context.

![image](https://cloud.githubusercontent.com/assets/25212/23766489/dbca5c38-04b9-11e7-9dbc-6f61766a5773.png)

cc @twigz20 @humphd @Pomax @gideonthomas - curious about your thoughts on these.

**Comment by flukeout** [comment]
The middle version is getting the best feedback from the folks that I've asked. In this mockup I also centered it below the icon so that we can reveal more of the code in the editor.

![image](https://cloud.githubusercontent.com/assets/25212/23815125/6d29f224-059b-11e7-9a2e-3e6aab3329cd.png)

Another option for this could be the 'inlineWidget' that brackets offers. We could expand something below the line of code you're working with.

**Comment by Pomax** [comment]
Really liking the first and second - although rather than let the user decide on the content, would it make sense to determine what the user can insert based on the file they're in? With a "more..." text that then reveals more snippets, which might be out of context? 

Or perhaps that's more clicks than necessary and the menu can select the correct snippet context on its own, with the user able to click another one if they need to.

**Comment by flukeout** [comment]
When you say out of context, do you mean the file type (HTML vs CSS) or something more specific within a file type like showing HTML snippets useful in the ``<head>`` when you've got your cursor there? 

If it's just filetype, I think we can select the right file type by default when we open the menu.

**Comment by Pomax** [comment]
yeah like you have index.html open, the snippets suggested are HTML snippets. You're looking at "script-1.js", the snippets suggested are javascript snippets.

**Comment by flukeout** [comment]
Yeah, def - @twigz20 already has that ability built into the code. Makes a lot of sense.

**Comment by flukeout** [comment]
Here's a mockup of a treatment for the hover effect that another mozillian put together...

<img src="https://d3uepj124s5rcx.cloudfront.net/items/0E0w2k2Y2k051y2X0P02/thimble-code-snippet-menu-hover.gif" width="350"/>

**Comment by Pomax** [comment]
How're we doing on this one? Is this still in discussion or do we have enough to move forward marking as good first bug? @flukeout

**Comment by flukeout** [comment]
This issue is supporting the work in a PR by @twigz20 (#1826). Looks like there is some recent activity there, so I'll check in. Ideally the design option B from this issue would be implemented as part of that PR. If we decide to implement this as a separate effort then I'll create a new implementation issue with Good First Bug on it then.

**Comment by twigz20** [comment]
@flukeout I've made the necessary changes so you're able to easily pull and test out my branch. Is it possible to link me to where or who made the hover effect?

**Comment by flukeout** [comment]
Closing this as it has been designed and we are working on finalizing the implementation now.
