### ISSUE TITLE
Create list of insertable HTML, JS & CSS snippets

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.mozilla.org#1857]
Related to the work snippet work in #1856 

Let's start a list of useful snippets for beginners...

**HTML**
* table markup with a few with a table header, and some rows and columns
* definition list
* ordered and unordered list with a few blank items
* form with a few inputs / labels and submit button
* script tag to link to a JS file in the head
* style tag to link to a CSS file in the head
* video tag
* audio tag
* mobile meta tags
* empty comment
* ...

**CSS**
* link styles
  * With :hover, :active, :visited
* more pseudo selectors?
  * :after / :before?
* keyframe animation
* maybe some empty selectors? 
  * class selector
  * ID selector
* font-face declaration
* some media queries
  * greater than a certain width
  * less than a certain width
  
...

**JS**
* for loop
  * loop over array
* while loop
* if / else statement
* case statement
* blank function
* ...

cc @twigz20

**Comment by flukeout** [comment]
We can figure out the code/markup for these later, but let's build a list of at least 5-10 per code.

**Comment by Pomax** [comment]
for CSS it would be cool to have an automatic @import for webfonts.

**Comment by flukeout** [comment]
Going to close, since the feature is merged and working already.
