### ISSUE TITLE
Editor doesn't let you copy and paste white space

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.mozilla.org#1864]
In the desktop Brackets, and other desktop editors, you can highlight two spaces, copy them, then paste them over and over, adding to the whitespace on a line. 

This doesn't work in the Thimble editor. Is it a setting?

**Comment by Pomax** [comment]
does it not work in all files, or just HTML files?

**Comment by flukeout** [comment]
Looks like HTML/JS/CSS files. Those are all I tested.

**Comment by humphd** [comment]
This works fine for me.  What kind of keyboard and mouse are you using with all these haunted keyboard and mouse shortcut issues!?

**Comment by flukeout** [comment]
Does it work for you @Pomax ?

**Comment by Pomax** [comment]
only in places where spaces are "allowed"... if I do it here:
```
<h1>title</h1>
←
<p>test</p>
```
then pasting spaces from clipboard does nothing. If I do it here:
```
<h1>here works<h1>

<p>here works too</p>
```
the it works fine. Looks like Brackets "knows" about the whitespace rules in an HTML document and prevents putting whitespace that is going to get ignored anyway in the document?

**Comment by flukeout** [comment]
Okay - let's close it! Thanks for checking
