### ISSUE TITLE
Trouble in  signing in for Mozilla Chat

### ISSUE THREAD

**Issue by GingerDragon7** [mozilla/thimble.mozilla.org#1871]
When we try to join Mozilla Chat,every time it is showing we couldn't find an account matching your login credentials,irrespective of the fact that we have entered all the details correct every time.It would be great if anyone could  see this screen shot and tell me what exactly is going wrong.

![screenshot 6](https://cloud.githubusercontent.com/assets/17198965/23836933/f6970068-07a5-11e7-8a6f-bf9035f3b271.png)

**Comment by ryanwarsaw** [comment]
You need to enter your email address, not your username. Refer to the field description.

**Comment by humphd** [comment]
@GingerDragon7 if this doesn't fox your issue, please re-open this and let us know.

@ryanwarsaw, I asked Sunny to file this, so we could get the answer documented in Github vs. emailing me directly.

**Comment by GingerDragon7** [comment]
@ryanwarsaw thank you,my issue has been solved.
@humphd thank you,if i will face any issue i will open it.
