### ISSUE TITLE
Add extra padding before the start of each line in the editor

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.mozilla.org#1875]
Currently, code starts immediately after the white line that separates it from the line numbers (and gutter arrows)...

<img src="https://cloud.githubusercontent.com/assets/25212/23877522/ebbd2ec4-07ff-11e7-9898-ea653b962812.png" width="250"/>

Let's add about 10 pixels of left padding the code so that it looks like this...

<img src="https://cloud.githubusercontent.com/assets/25212/23877543/00b66c46-0800-11e7-9409-7f8d6ff1ffa1.png" width="250"/>

**Comment by flukeout** [comment]
Temporarily held for @sanariaz154

**Comment by sanariaz154** [comment]
I am working on this . Thanks @flukeout

**Comment by sanariaz154** [comment]
@flukeout can you please tell me which files from [](https://github.com/mozilla/brackets/blob/master/src/extensions/default) are referencing this issue?

**Comment by flukeout** [comment]
Hi @sanariaz154, since this is mostly a styling issue, I'd recommend adding some new styles to ``bramble_overrides.css`` - you can find the right element to modify by using the developer tools to inspect the elements on the page in your browser.

Let me know if you need help.

**Comment by sanariaz154** [comment]
Hi @flukeout,  styles related to the code block element class `.CodeMirror` are in `brackets_codemirror_override.less` - adding new styles to `bramble_overrides.css` weren't fixing the issue. 
I've sent a pull request for this issue:
(Thimble issue1875 #648)
Kindly let me know what can I do to make it better.
