### ISSUE TITLE
Discussion: Ditch Code-folding feature? 

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.mozilla.org#1877]
So i was doing some small styling tweaks to our sorta-ugly code folding arrows and was thinking, do we even need these? It doesn't seem like they're a useful feature for beginners. 

We could always just enable them later when we get around to an advanced panel. But for now I feel like they take up space and clutter things up without adding a lot of utility.

Thoughts?

**Comment by humphd** [comment]
It's an extension that's easy to turn off/on by just not loading it.  We could try removing it and see if people notice.

**Comment by flukeout** [comment]
Cool, I'll file that.

**Comment by negativefix** [comment]
I am writing a small module using thimble and having an hard time tracking blocks of code without folding. Dotted indent guides do not much. Do you have any plans of providing some sort of settings to toggle this feature via settings? Thanks.

**Comment by jgmac1106** [comment]
We all miss our collapsing code chevron.
