### ISSUE TITLE
Research: Collaboration via Together.js

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.mozilla.org#1878]
Let's try to build a light-weight prototype that uses Together.js to keep the content in an edited files in brackets in sync...

Goals
* Allow two or more people to access the same file with the same URL using brackets
* Reflect the changes made to the file in real-time to all participants

**Comment by Pomax** [comment]
do we want to do an intial test with a single file setup, so that "changing files" doesn't get in the way? Or do we want to try to go for multiple files?

**Comment by humphd** [comment]
My advice, based on what I'm seeing in various bits of code is that we do something that targets `http://localhost:8000/src/hosted.html` which means we'll have a pseudo-shared fs (same initial state) and then we do something with OT and CodeMirror deep inside Brackets.  That could be Together.js or any number of other OT js libs.

One thing we're going to have to solve is routing.  We're going to have N-CodeMirror instances in Brackets, and each one will need its own way to send/receive updates with the associated instances in the remote editor.  I suspect that Together.js and other libs I've seen don't do this yet. We'll have to somehow name instances so we can route them to the right instance off the wire.

However, as I told Luke, this should all "Just Work."  Brackets wraps an abstraction around a CodeMirror instance called an `Editor`, see https://github.com/mozilla/brackets/blob/master/src/editor/Editor.js#L403.  We'll just hack this up a bit to wrap it in an OT-aware version, with a websocket somewhere to marshal data.
