### ISSUE TITLE
Research: How does Cloud9 do its thing?

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.mozilla.org#1879]
What technologies does https://c9.io/ use to handle collaboration? Can we apply a similar stack to our real-time collaboration work in Thimble?

**Comment by humphd** [comment]
This is how they do it: https://github.com/c9/c9.ide.collab

However, their license is not compatible with ours, so we can't really study or use their code.  Basically they use an OT approach like we're considering anyway.

I think the most useful aspect of what they do would be to try it out in the app and see what it's like.

**Comment by humphd** [comment]
See also https://docs.c9.io/docs/share-a-workspace
