### ISSUE TITLE
Research: Google Drive API for real-time collaboration

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.mozilla.org#1880]
This has come up quite a few times in our discussions. Let's investigate what this API does and if it would be useful for real-time collaboration in Thimble.

**Questions**

* What are the upsides?
* What are the drawbacks?
* Can it handle keeping brackets files in sync?
* Can it handle chat?
* ...

**Comment by alalonde** [comment]
There are several options for realtime collaboration frameworks.  Apparently you're not afraid of proprietary solutions, so I'll plug ours :)  We built something similar from scratch in about a week: https://demo.convergence.io/code-editor/  Check it out in multiple browser windows to see the collaboration in action.  

Also, see my answer to a Quora question for a more thorough round-up: https://www.quora.com/What-are-good-frameworks-for-real-time-collaboration-in-a-web-application/answer/Alec-LaLonde?srid=uOx3K

**Comment by humphd** [comment]
cc @babhishek21, @hkirat who are also thinking about this stuff.

**Comment by alalonde** [comment]
We're intimately familiar with the landscape for these tools and how they can fit different projects' needs.  I'd be happy to jump on a call to discuss -- no selling, I promise! :)  Ping me at the email in my profile.
