### ISSUE TITLE
Feature Discussion - Call for Help

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.mozilla.org#1885]
Since we are focusing on short-term real-time collaboration, it seems like it might be useful to use it to get help with a project. If you don't know of someone to send the link to, could we advertise somewhere that you want help so we can get a community member or random helpful stranger to help you out?

* Maybe you could set a "make this public" flag when you turn on a collaboration
* You could add a description of what you want help with
* We could show your call for help somewhere
  * Thimble homepage?
  * Somewhere within the editor so other users could see it?

Potential dangers?
* Trolls?

**Comment by khanh2003** [comment]
Do we need a ban system for this?

**Comment by Pomax** [comment]
this is pretty much an entire project on its own if you want to do this right - so we might have to pick between a small exchange service that works, but with the pitfalls of "some jerk can be a jerk" (and set that us as "this is apparently the kind of service we offer") or a large exchange effort that we probably can't pull off but makes people go "oh this is really nicely done" from day one.

Other than non-brokered connection, where people already know someone for help, dropping a link in &lt;insert your favourite group-chat technology here&gt;, this feels like it'll be a deep rabbit hole.

**Comment by gideonthomas** [comment]
Let's revisit once we have a prototype set up.
