### ISSUE TITLE
can't drop files "into" a dir

### ISSUE THREAD

**Issue by Pomax** [mozilla/thimble.mozilla.org#1886]
If I have a dir "open" and selected in the file browser, and I drag-and-drop a file into thimble, it'll drop it in the root, rather than the dir I have open. This has high potential for losing work by overwriting a file with the same name.

**Comment by humphd** [comment]
Whoever works on this, the DnD code lives in https://github.com/mozilla/brackets/blob/master/src/utils/DragAndDrop.js.  We'd have to somehow add code to figure out which filetree node (if any) was under the mouse when we dropped the file(s), and then use that as part of the path vs. just the project root.  I'm not 100% clear if it's possible, but I suspect with work it is.

**Comment by bkim49** [comment]
Hello, I would like to work on this bug. Can you assign it to me? @Pomax Thank you.

**Comment by humphd** [comment]
@bkim49 this probably won't be a trivial fix, but a very cool one nevertheless.  Please ask questions and chat with us on https://chat.mozillafoundation.org/mozilla/channels/thimble about it.  I can probably give you some tips as you get started.

**Comment by humphd** [comment]
From Mattermost:

>    bkim49: Hello, I am looking for some help regarding one of the issue I am working on. My issue is that we want the files to be able to drag and dropped into a folder. Currently that is not possible. If you drag and drop, it will only go to the root tree. Even if you drop it on top of a folder, it does not recognize it, and files are placed into the root. What are some possibilities I can try to allow the dragged cursor to recognize the folder or repository?
>
> humphd @bkim49 hey, I was just working on this code today https://github.com/mozilla/brackets/pull/659
> so to do what you want, we'd have to change it so when we do the drop event, we figure out what is under us in the file tree. if I were you, I'd have a conversation with @pomax about how to do this in React.js.  I think you need to work in this file https://github.com/mozilla/brackets/blob/master/src/project/FileTreeView.js and you'd have to somehow figure out which, if any, nodes in the filetree are currently under the mouse.  Likely that would mean watching for mouse enter and mouse leave events in the nodes, and keeping track of this state (react probably has a good way to do this).  Then, you need to make this something you can get with code from the drag-and-drop code such that you can ask the filetree view: "Which node is under the mouse right now?" and it tells you, and you then get the path for it, and use that vs. the project root. this is not a quick bug to fix, fyi, it's going to require you to learn some react, learn about mouse and drag/drop events, and work in a bunch of places in our code.  I can guide you with some, but not all of it, since I don't know a ton about react.

@Pomax I'd value spending a few minutes with you to just examine how likely this is to be fixed (based on your knowledge of React and how Brackets uses it), so we can either tell @bkim49 to go for it, or to abandon this.

**Comment by bkim49** [comment]
@humphd I feel like this might be little too difficult for me. Maybe it could be better if I choose a different bug to work on.

**Comment by humphd** [comment]
@bkim49 no problem, thanks for letting me know.  I think it would be difficult for me too!

**Comment by humphd** [comment]
After writing about what needed to happen, I ended up just fixing this as part of my dnd refactor in https://github.com/mozilla/brackets/pull/659.  The relevant commit is https://github.com/humphd/brackets/commit/c238c04afb107946ecabf8347c4b1e14e709fb3c.

**Comment by Pomax** [comment]
tested and barring some bugs that this surface, this works really well now

**Comment by humphd** [comment]
I've landed #659, closing.
