### ISSUE TITLE
Vagrant - DEBUG ssh, Sending SSH keep-alive

### ISSUE THREAD

**Issue by lkisac** [mozilla/thimble.mozilla.org#1893]
After running `vagrant halt` or `vagrant suspend`, then `vagrant up` it hangs on `default: [PM2] [thimble](4)`

So I run with `vagrant up --debug` to see the debug logs:

```bash
==> default: [PM2] Applying action restartProcessId on app [thimble](ids: 4)
DEBUG ssh: Sending SSH keep-alive...
DEBUG ssh: Sending SSH keep-alive...
DEBUG ssh: Sending SSH keep-alive...
DEBUG ssh: Sending SSH keep-alive...
 INFO interface: info: [PM2] [thimble](4) ✓
 INFO interface: info: ==> default: [PM2] [thimble](4) ✓
==> default: [PM2] [thimble](4) ✓
DEBUG ssh: Sending SSH keep-alive...
DEBUG ssh: Sending SSH keep-alive...
DEBUG ssh: Sending SSH keep-alive...
DEBUG ssh: Sending SSH keep-alive...
DEBUG ssh: Sending SSH keep-alive...
DEBUG ssh: Sending SSH keep-alive...
DEBUG ssh: Sending SSH keep-alive...
DEBUG ssh: Sending SSH keep-alive...
```
The last line repeats for some time (approx. 5-10 mins), until it finally gets here:

```bash
 INFO interface: info: ┌─────────────────┬────┬──────┬──────┬────────┬─────────┬────────┬─────┬────
───────┬──────────┐
│ App name        │ id │ mode │ pid  │ status │ restart │ uptime │ cpu │ mem       │ watching │
├─────────────────┼────┼──────┼──────┼────────┼─────────┼────────┼─────┼───────────┼──────────┤
│ id              │ 1  │ fork │ 2178 │ online │ 1       │ 16m    │ 0%  │ 42.8 MB   │ disabled │
│ localize-client │ 3  │ fork │ 2322 │ online │ 1       │ 10m    │ 40% │ 31.9 MB   │ disabled │
│ login           │ 0  │ fork │ 2172 │ online │ 1       │ 16m    │ 1%  │ 50.4 MB   │ disabled │
│ publish         │ 2  │ fork │ 2224 │ online │ 1       │ 11m    │ 0%  │ 60.0 MB   │ disabled │
│ thimble         │ 4  │ fork │ 2475 │ online │ 1       │ 6m     │ 6%  │ 44.0 MB   │ enabled  │
└─────────────────┴────┴──────┴──────┴────────┴─────────┴────────┴─────┴───────────┴──────────┘
 INFO interface: info: ==> default: ┌─────────────────┬────┬──────┬──────┬────────┬─────────┬──────
──┬─────┬───────────┬──────────┐
==> default: │ App name        │ id │ mode │ pid  │ status │ restart │ uptime │ cpu │ mem       │ watching │
==> default: ├─────────────────┼────┼──────┼──────┼────────┼─────────┼────────┼─────┼───────────┼──
────────┤
==> default: │ id              │ 1  │ fork │ 2178 │ online │ 1       │ 16m    │ 0%  │ 42.8 MB   │ disabled │
==> default: │ localize-client │ 3  │ fork │ 2322 │ online │ 1       │ 10m    │ 40% │ 31.9 MB   │ disabled │
==> default: │ login           │ 0  │ fork │ 2172 │ online │ 1       │ 16m    │ 1%  │ 50.4 MB   │ disabled │
==> default: │ publish         │ 2  │ fork │ 2224 │ online │ 1       │ 11m    │ 0%  │ 60.0 MB   │ disabled │
==> default: │ thimble         │ 4  │ fork │ 2475 │ online │ 1       │ 6m     │ 6%  │ 44.0 MB   │ enabled  │
==> default: └─────────────────┴────┴──────┴──────┴────────┴─────────┴────────┴─────┴───────────┴─
 INFO interface: info:  Use `pm2 show <id|name>` to get more details about an app
 INFO interface: info: ==> default:  Use `pm2 show <id|name>` to get more details about an app
==> default:  Use `pm2 show <id|name>` to get more details about an app
 INFO interface: info: Starting Thimble server on http://localhost:3500/ (this may take a minute...)
 INFO interface: info: ==> default: Starting Thimble server on http://localhost:3500/ (this may take a minute...)
==> default: Starting Thimble server on http://localhost:3500/ (this may take a minute...)
 INFO interface: info: Use 'npm run restart-server' to force a reload of the server
 INFO interface: info: ==> default: Use 'npm run restart-server' to force a reload of the server
==> default: Use 'npm run restart-server' to force a reload of the server
 INFO interface: info: Use 'npm run logs' to see server logs for the node apps in the VM
 INFO interface: info: ==> default: Use 'npm run logs' to see server logs for the node apps in the VM
==> default: Use 'npm run logs' to see server logs for the node apps in the VM
```

_id_, _localize-client_, _login_ and _publish_ processes start up very quickly, but the _thimble_ process is stalling.

A similar issue [here](https://github.com/mitchellh/vagrant/issues/8118) suggests disabling config.ssh.pty helps, although Thimble's Vagrantfile does not enable it anyway, I tried explicitly disabling it, but it doesn't fix it.

I also tried [this](https://coderwall.com/p/uaohzg/use-nfs-to-speed-up-your-vagrant) suggestion to enable [NFS](https://www.vagrantup.com/docs/synced-folders/nfs.html) but this also did not solve the issue.

I'm running vagrant on Windows 10, using git bash terminal (git version 2.12.0.windows.1) from my Thimble project folder.

@gideonthomas @humphd any ideas?  

Please let me know if you want me to provide any more details.

**Comment by humphd** [comment]
When you get the VM up, try opening 2 terminals and doing this:

```
// in first terminal
vagrant ssh
pm2 logs

// In second terminal, do this
vagrant ssh
cd /vagrant
pm2 restart thimble
```

See how long that takes, and if it logs anything in the first terminal.  It's possible that the Thimble node app is having a hard time starting, or is restarting itself a lot, or something else.  I wouldn't guess that this is an ssh keep-alive issue, but I could be wrong

cc'ing @Pomax, who is also running on Windows.

**Comment by lkisac** [comment]
Here are the [logs](https://gist.github.com/lkisac/c576e5c2fc131b532b3874cbaee49cfd) for both terminals.  Took approx. 7 mins.

Some error logs from lines 19-37.  Maybe issue is here?

**Comment by humphd** [comment]
@cadecairos @gideonthomas do these two crashes mean anything to you?

```
/home/vagrant/.pm2/logs/id-error.log last 15 lines:
1|id       |     at Object.exports.internal (/vagrant/services/id.webmaker.org/node_modules/boom/lib/index.js:252:92)
1|id       |     at Object.exports.badImplementation (/vagrant/services/id.webmaker.org/node_modules/boom/lib/index.js:288:23)
1|id       |     at /vagrant/services/id.webmaker.org/web/server.js:610:37
1|id       |     at /vagrant/services/id.webmaker.org/node_modules/hapi/node_modules/hoek/lib/index.js:848:22
1|id       |     at nextTickCallbackWith0Args (node.js:489:9)
1|id       |     at process._tickDomainCallback (node.js:459:13)
1|id       | Debug: internal, implementation, error
1|id       |     Error: Error: Service Unavailable
1|id       |     at Object.exports.create (/vagrant/services/id.webmaker.org/node_modules/boom/lib/index.js:21:17)
1|id       |     at Object.exports.internal (/vagrant/services/id.webmaker.org/node_modules/boom/lib/index.js:252:92)
1|id       |     at Object.exports.badImplementation (/vagrant/services/id.webmaker.org/node_modules/boom/lib/index.js:288:23)
1|id       |     at /vagrant/services/id.webmaker.org/web/server.js:610:37
1|id       |     at /vagrant/services/id.webmaker.org/node_modules/hapi/node_modules/hoek/lib/index.js:848:22
1|id       |     at nextTickCallbackWith0Args (node.js:489:9)
1|id       |     at process._tickDomainCallback (node.js:459:13)

/home/vagrant/.pm2/logs/publish-error.log last 15 lines:
2|publish  |     at Immediate.Async.drainQueues [as _onImmediate] (/vagrant/services/publish.webmaker.org/node_modules/bluebird/js/main/async.js:15:14)
2|publish  |     at processImmediate [as _immediateCallback] (timers.js:396:17)
2|publish  | Debug: internal, implementation, error
2|publish  |     Error: Internal Server Error
2|publish  |     at generateErrorResponse (/vagrant/services/publish.webmaker.org/api/classes/errors.js:44:17)
2|publish  |     at bound (domain.js:287:14)
2|publish  |     at runBound (domain.js:300:12)
2|publish  |     at tryCatcher (/vagrant/services/publish.webmaker.org/node_modules/bluebird/js/main/util.js:26:23)
2|publish  |     at Promise._settlePromiseFromHandler (/vagrant/services/publish.webmaker.org/node_modules/bluebird/js/main/promise.js:510:31)
2|publish  |     at Promise._settlePromiseAt (/vagrant/services/publish.webmaker.org/node_modules/bluebird/js/main/promise.js:584:18)
2|publish  |     at Promise._settlePromises (/vagrant/services/publish.webmaker.org/node_modules/bluebird/js/main/promise.js:700:14)
2|publish  |     at Async._drainQueue (/vagrant/services/publish.webmaker.org/node_modules/bluebird/js/main/async.js:123:16)
2|publish  |     at Async._drainQueues (/vagrant/services/publish.webmaker.org/node_modules/bluebird/js/main/async.js:133:10)
2|publish  |     at Immediate.Async.drainQueues [as _onImmediate] (/vagrant/services/publish.webmaker.org/node_modules/bluebird/js/main/async.js:15:14)
2|publish | at processImmediate [as _immediateCallback] (timers.js:396:17)
```

**Comment by Pomax** [comment]
I ran into this when I didn't have `VT-x` enabled in my UEFI (what some call the "BIOS" except it's a completely different thing from BIOS). Once I had that enabled, rebuilding the vagrant image (`vagrant destroy` + `vagrant up`) ended up working.

**Comment by humphd** [comment]
@lkisac I wonder if https://github.com/mozilla/thimble.mozilla.org/pull/1913 is going to fix your issue.

**Comment by lkisac** [comment]
@Pomax  I'm able to get vagrant up and running, just that it takes quite some time (approx. 10 mins) to vagrant up after a vagrant suspend/halt (I need to do this while working on any server-side code), stalling on the `DEBUG ssh: Sending SSH keep-alive...` for each process.  I have vt-x enabled on my Vagrant VM as well as on my Windows OS.

@humphd  Thanks, I will keep an eye on it.  Hopefully it does address this issue.

**Comment by Pomax** [comment]
@lkisac humph's PR got merged in, can you see if your issue was resolved with it?

**Comment by lkisac** [comment]
I pulled most recent changes and getting ``==> default: /tmp/vagrant-shell: line 3: pm2: command not found" error in my --debug log on `vagrant up`.  

```bash
    default: Running: C:/Users/LENISA~1/AppData/Local/Temp/vagrant-shell20170328-8860-10dli5b.sh
DEBUG ssh: Re-using SSH connection.
 INFO ssh: Execute: chmod +x '/tmp/vagrant-shell' && /tmp/vagrant-shell (sudo=false)
DEBUG ssh: stderr: /tmp/vagrant-shell: line 3: pm2: command not found

 INFO interface: info: /tmp/vagrant-shell: line 3: pm2: command not found
 INFO interface: info: ==> default: /tmp/vagrant-shell: line 3: pm2: command not found
==> default: /tmp/vagrant-shell: line 3: pm2: command not found
```

pm2 is also not recognized within the vagrant shell either:

```bash
No command 'pm2' found, did you mean:
 Command 'wm2' from package 'wm2' (universe)
 Command 'pmw' from package 'pmw' (universe)
 Command 'pms' from package 'pms' (universe)
 Command 'pmk' from package 'pmk' (universe)
 Command 'pom2' from package 'libpod-pom-perl' (universe)
 Command 'pmi' from package 'powermanagement-interface' (universe)
 Command 'fpm2' from package 'fpm2' (universe)
 Command 'pm' from package 'powerman' (universe)
pm2: command not found
```

I tried re-installing pm2 `npm install pm2 -g`, but still getting error.  Should I open a separate ticket for this issue?

**Comment by Pomax** [comment]
hm, let's keep this one open for now - @gideonthomas @humphd have you seen this before by any chance?

**Comment by humphd** [comment]
@lkisac what does `git show` tell you about which commit you are on when you run `vagrant up`?

**Comment by lkisac** [comment]
I did a `git log --max-count=3` to show a couple changes before my latest pull request (1868).

```git
commit 5888caed0c22a69e3dab4100111aba69e8e06956
Author: Jim Spentzos <jamesspentzos@hotmail.com>
Date:   Tue Mar 28 20:31:17 2017 +0000

    Pontoon: Update Greek (el) localization of Thimble

    Localization authors:
    - Jim Spentzos <jamesspentzos@hotmail.com>

commit 11836197929186f9293cb28510d5b8f6c5be7ba7
Author: kramsamujh <kevin_ramsamujh@yahoo.ca>
Date:   Tue Mar 28 13:31:09 2017 -0400

    Issue #1766- Remix from projects list (#1900)

    Added Remix link to the Your Projects page for published projects.
```

**Comment by humphd** [comment]
@lkisac I truly think that the VM and your laptop hardware and/or OS just hate each other.  You've had so many problems :(

**Comment by lkisac** [comment]
@humphd  One thing I fixed earlier on when setting up vagrant was my vagrant home path (a directory with no spaces, unfortunately my Windows user dir has a space in it when I installed Windows I put my first and last name which automatically created a user home directory with the full name...  Vagrant/Ruby has issues with directories containing [spaces](http://stackoverflow.com/a/26217200/2434565)).

I found that the VM snapshots were also being stored in this home directory so I changed the default machine folder from the Oracle Virtualbox GUI:
![oracle-defaultmachinefolder](https://cloud.githubusercontent.com/assets/5377677/24480623/6ab4978e-14b3-11e7-82f7-6b46362d58e8.png)

After doing `vagrant destroy`, `vagrant up`, "missing pm2 command" issue was fixed.

Regarding initial issue:  I ran `vagrant up` (after vagrant halt) and it took approx. 4 mins which is an improvement from before.  Here are new [logs](https://gist.github.com/lkisac/2ba7d34998f6e965c660034cde8aaea7).   

Earlier crashes are gone now with latest changes, Only thing I see that may be making the startup slow: `pid=1637 msg=failed to kill - retrying in 100ms` from lines 75-86.  I suppose this ticket could be closed now since initial errors are gone now, unless someone can advise on the last one mentioned?

**Comment by humphd** [comment]
Looks to me like it's working now--those logs look like it was just having trouble killing an old process, which may not actually have existed (e.g., `pid` was old and deleted).  Let's close this and file again if you hit new issues.

**Comment by lkisac** [comment]
Ok, will do.  Thanks for the help @Pomax and @humphd!

**Comment by Pomax** [comment]
This sounds like a thing we may want to add to the readme for windows users. Path verification is a tricky thing, and worth calling out in the README.md
