### ISSUE TITLE
Problem with website response in case of small window size.

### ISSUE THREAD

**Issue by sudwebd** [mozilla/thimble.mozilla.org#1894]
![ezgif com-video-to-gif](https://cloud.githubusercontent.com/assets/17878270/23993620/5027e638-0a67-11e7-9636-6d00cefd875a.gif)

The editor bar comes down in case of small window size.I am running the website on google chrome.
I'll do a pull request for the bug asap, if its okay.

**Comment by humphd** [comment]
@flukeout I think we have a bug on this responsive header issue already, am I right?

**Comment by flukeout** [comment]
I think this has been fixed already and should be working correctly in staging - https://bramble.mofostaging.net/en-US/

@sudwebd if you are able, could you double-check that at the URL above, this behavior is not happening?

**Comment by sudwebd** [comment]
@flukeout the above problem is not happening in the url you specified.Its working correctly.

**Comment by flukeout** [comment]
Thank you for confirming @sudwebd - we've fixed lots of things and those changes are only reflected on that URL.
