### ISSUE TITLE
401 authentication error when logging in

### ISSUE THREAD

**Issue by Mavromatika** [mozilla/thimble.mozilla.org#1895]
Hi, 
I tried to get my brother to log in to Thimble remotely (giving him instructions via skype). 
He managed to create an account (userid : petitpoulet), but he can't log in. He gets a 401 error.
He tried in both Firefox and Edge and both give the same error. He also gets the same error from another computer in the same local network.

When I try to log in with his credentials from my computer (in another country) everything works fine.

Any idea what could cause this ?

**Comment by humphd** [comment]
cc @cadecairos who might have ideas.

**Comment by cadecairos** [comment]
@Mavromatika  Based on the info you've provided, it sounds like an issue with your brother's network. Is there any chance that the network operator is running a firewall or perhaps running an MITM (man in the middle) proxy that's modifying or blocking his requests to/from Thimble?

**Comment by Mavromatika** [comment]
Thank you both for your quick replies. I'm also suspecting something along these lines. Do you think I could check that at the level of their router ?

**Comment by cadecairos** [comment]
Presuming you've got access to the router administration interface, you can certainly check to see if there's something going on. There's also the chance it's the ISP doing something with network traffic.

If they've got the time to figure it out, they might want to try using a VPN to see if it's indeed the network they're on.

**Comment by Mavromatika** [comment]
Well, my brother just told me that it's working fine now. No idea why it wasn't before. I guess I can close this issue. Thanks a lot for answering so quickly.

**Comment by cadecairos** [comment]
Glad to hear it works!

**Comment by humphd** [comment]
Glad it's working for you @Mavromatika, and I hope you enjoy using Thimble.

**Comment by Mavromatika** [comment]
My brother is enjoying it a lot. Nice work !
