### ISSUE TITLE
Facebook blocking urls from thimbleprojects.org

### ISSUE THREAD

**Issue by jgmac1106** [mozilla/thimble.mozilla.org#1898]
Getting some feedback from club captains that facebook is marking any Thimble project as safe and dangerous. 
<img width="913" alt="screenshot 2017-03-18 15 07 48" src="https://cloud.githubusercontent.com/assets/10534566/24075156/b31572c0-0bec-11e7-9ad2-1a3732209118.png">
Here is the message I get when trying to share.

This must be a recent change as I was sharing posts as of last week.

cc'ing @KevZawacki since this may be a media/comms issue and not so much a technical one.

**Comment by humphd** [comment]
Did you, or they, click the "let us know" link and file something with them?  We have friends at Facebook I could reach out to, but if it can be handled through normal channels that might be good.

cc'ing @chrislarry33 too.

**Comment by jgmac1106** [comment]
Yeah. I tried to reproduce the bug and got the warning message. I filled
out the form as well, but figured friends may move it along quicker. Many
clubs in other parts of the world organize most of their events on facebook.

**Comment by humphd** [comment]
OK, thanks.  Keep us update on what happens with that request you filed, and if necessary, I'll reach out to people I know.

**Comment by ryanwarsaw** [comment]
https://developers.facebook.com/tools/debug/sharing/?q=thimbleprojects.org

**Comment by humphd** [comment]
@ryanwarsaw I don't have a facebook account, what does it say?

**Comment by gideonthomas** [comment]
> We can't review this website because the content doesn't meet our <a href="https://www.facebook.com/communitystandards" target="_blank">Community Standards</a>. If you think this is a mistake, please <a href="https://www.facebook.com/help/contact/571927962827151?additional_content=AejryWYIykuBL37oLWMDrYLgjVpcrLq4rTntldGjjwgLTklCcSAQjqrvthJ5Lr3A6hFVf4jvZhl1oFVZmJFqz3f3fcNH_DtTJ7EfOXaZpNC3eqlwl5tuU9LPV2yh5ZaiXL1BUmgg7v0bL_LTfTseI66LLdSz-xTV2C9ORH8LaB9zcam1vbgPEWL9fzB11e1wUhCJhJuO2paU8k66sqjdqw608CS5Klrxx8NANEPqy6DHtiNOMq-MVcQsSY2zKJeiUQAc3igVpbH1uC1IKpt32dIkl6UHLiRumyu7R-aRv0vpqRXQWhicekvFgTBPHDHxc30" target="_blank">let us know</a>.

**Comment by humphd** [comment]
It's entirely possible that some of our users have breached their standards with things they've published (e.g., images, text, and the like that we also wouldn't agree with).  Given that we can't really police all this, I'm not sure what the right answer is.

**Comment by ryanwarsaw** [comment]
While that's entirely possible, other sites known to have dealt with similar issues in the past (JSBin, JSFiddle, etc) are not currently being blocked by Facebook, so I wouldn't be worried by this. It's likely all done by automation, so it could just be a matter of incorrect classification.

**Comment by jgmac1106** [comment]
Goog point. @ryanwarsaw Could be as simple as their content recognition flagging Goggles remixes more than Thimble as well. JSBin and JSFiddle probably don't bump into as many copyright claims as a tool that allows you to remix somebody else's website.

**Comment by ryanwarsaw** [comment]
@jgmac1106 Any update on this?

**Comment by jgmac1106** [comment]
No I never got a response. Let me try posting a project and seeing if I get
the same error.....Just checked. URL still blocked. Gonna take someone
above my pay grade to resolve I think.

**Comment by gideonthomas** [comment]
cc @simonwex to help figure out how to get Facebook to resolve this (I can't find a link to contact them directly)

**Comment by philtrem** [comment]
How is this still a problem in November 2018 ??

**Comment by jgmac1106** [comment]
Because we haven't convinced everybody to leave facebook by November 2018....but we can keep trying.

**Comment by zubairamin** [comment]
2019 is about to come. It is still blocked. Strange? how facebook recheck the block websites? My client's website also blocked. Their review form is useless.
