### ISSUE TITLE
Update "New Project" style.css to include a nicer font

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.mozilla.org#1903]
Honestly, I'm tired of looking at....

![image](https://cloud.githubusercontent.com/assets/25212/24121044/fdf18fa8-0d73-11e7-97b0-bf95ceb03ae9.png)

Since we're already packaging a ``style.css`` file with new projects, we may as well add a few styles to it to make it more attractive and appealing.

As a start, let's add 

```css
body {
  font-family: sans-serif;
}
```

**We could also..**

* Add extra padding around the body
* Change the default background color
  * Would it be possible to generate a dynamic / randomized stylesheet every time a new project is created? That would be cool.
* Include a cool Google Font?

**Comment by nadia39** [comment]
Hi, I can work on this issue
I need to contribute to open source projects for a class.

**Comment by humphd** [comment]
Great, welcome @nadia39!  I've assigned it to you

**Comment by humphd** [comment]
The files that need to get updated are here:

https://github.com/mozilla/thimble.mozilla.org/tree/master/default/empty-project

**Comment by khanh2003** [comment]
@humphd What font should we change it to? Or can we set the default project background to be a linear-gradient background?
```css
background: #f06;
background: linear-gradient(45deg, #f06, yellow);
min-height: 100%;
```
(from Dabblet)

**Comment by humphd** [comment]
@nadia39, @khanh2003 can I confirm that one of you is actually working on this?  If you're not able to do it, no problem, just let me know so I can give it to someone else.

**Comment by flukeout** [comment]
Okay, so for whoever takes it, here is a list of what should happen:

**Update index.html markup**
The new project ``index.html`` file should match the blank ``index.html`` file that you add from the **Add File** dropdown.

Files are...
* https://github.com/mozilla/thimble.mozilla.org/blob/master/default/empty-project/index.html
* https://github.com/mozilla/thimble.mozilla.org/blob/master/public/resources/default-files/html.txt

Markup should be...

```
<!DOCTYPE html>
<html>
  <head>
    <title>Made with Thimble</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="style.css">
  </head>
  <body>
    <h1>Welcome to Thimble!</h1>
    <p>Make something <strong>amazing</strong> with the web!</p>
  </body>
</html>
```

We removed the stylesheet link tag before, but I think we should add it back. It's a handy reference for how to add a stylesheet, and will work most of the time anyway since projects start with a ``style.css`` file.

Also, let's change the default CSS file...

* https://github.com/mozilla/thimble.mozilla.org/blob/master/default/empty-project/style.css

```
body {
  font-family: "Open Sans", "Helvetica Neue", "Helvetica", sans-serif;
  padding: 5px 25px;
  margin: 0;
  background: plum;
}
```

Thanks!

**Comment by nadia39** [comment]
yes I am working on it


I should be done in a few days

Nadia

________________________________

**Comment by flukeout** [comment]
Thanks @nadia39!

**Comment by flukeout** [comment]
How's it coming along @nadia39 ?

**Comment by nadia39** [comment]
I am almost done! Today I will be done.
It was a great first pull request by the way

**Comment by nadia39** [comment]
I sent it, over a week ago. 
Hopefully it was published, this is my first pull requests.
However it was not updated on the GitHub page..

**Comment by flukeout** [comment]
Hi @nadia39 - did you create a Pull Request? Did you make the changes in your own repo? Let me know, we can track it down. Thanks!

**Comment by nadia39** [comment]
I hope you check the **pull request** now. It seems like I did not complete the process.

**Comment by humphd** [comment]
This was merged, closing.
