### ISSUE TITLE
QuickEdit menu styling problems

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.mozilla.org#1906]
When we indented the code in the editor, we inadvertently moved the Quick Edit menu...

![](https://cloud.githubusercontent.com/assets/25212/24159627/cef629b2-0e1c-11e7-8671-9fe729c8ba6c.png)

In addition, there is a strange white bar visible near the line numbers, I think this is also related.

(@humphd brings back memories?)

**Comment by humphd** [comment]
@flukeout "I told you so" comes to mind! :(

**Comment by flukeout** [comment]
Fixed in #667 - awaiting next told you so moment.
