### ISSUE TITLE
QuickEdit menus don't have a dark theme anymore.

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.mozilla.org#1907]
Dang it! Something changed when we updated the themes probably.

This is the color picker in dev on a dark theme...

<img src="https://cloud.githubusercontent.com/assets/25212/24159744/27abe72c-0e1d-11e7-9226-66300b2a694d.png" width="450" />

**Comment by humphd** [comment]
I did a `git bisect` and it was https://github.com/mozilla/thimble.mozilla.org/issues/1100 and the PR in https://github.com/mozilla/brackets/pull/646:

```
41dfa3a82d2bce6ee29ccc534d3d8066b25a2555 is the first bad commit
commit 41dfa3a82d2bce6ee29ccc534d3d8066b25a2555
Author: Dorel Barbu <dorelbarbu96@gmail.com>
Date:   Wed Mar 15 21:11:43 2017 +0200

    Issue 1100: Modified the approach used. Instead of toggling classes we change the value of an attribute now
```

cc @DorelBarbu 

By the way, in case whoever works on this wants to play with git bisect, here is how you do it.  I checkout the code on master and confirm that it's broken, then I start `git bisect start` and go back to an old commit that I know works (it used to work in January).  I've blogged about how to use `git bisect` before, see http://blog.humphd.org/learning-to-git-bisect/.  Here is what my session in Brackets looked like:

```bash
git bisect start
git checkout cf24dc8199b3fa0673dac87f578664694dae0305
git submodule update --init && npm start
git bisect good
git submodule update --init && npm start
git bisect good
git submodule update --init && npm start
git bisect good
git submodule update --init && npm start
git bisect good
git submodule update --init && npm start
git bisect good
git submodule update --init && npm start
git bisect bad
git submodule update --init && npm start
git bisect bad
git submodule update --init && npm start
git bisect bad
git submodule update --init && npm start
git bisect good
git bisect reset
```
Every time I update my submodules (sometimes a commit changes them, so this makes sure they are all correct) and start the server.  Then, depending on what I see (broken vs. correct), I tell `git bisect` that it's `good` or `bad` and it keeps narrowing down the search.  Eventually it finds the exact commit that introduced the error.  It's a handy thing to know how to do for looking at regressions.

**Comment by abhayptp** [comment]
Hi! I want to work on this issue!

**Comment by hkirat** [comment]
I think the problem is that we have omitted [this](https://github.com/mozilla/brackets/commit/59242ea376082abeeb4cfaf94b9f561575199276#diff-82c3690745f7c8a1b46c19bba1804f0aL240) line.

```js
$("body").toggleClass("dark", theme.dark);
```

**Comment by Abykin** [comment]
Hey @flukeout @humphd I'd like to work on this.

**Comment by humphd** [comment]
@Abykin it's yours, go for it.  See notes above.

**Comment by hkirat** [comment]
Hi @Abykin 
Are you still working on this?
If not I would like to work on it since one of my [other](https://github.com/mozilla/brackets/pull/651) PRs is pending because of this issue.

**Comment by Abykin** [comment]
@hkirat Sorry for the delay I had weird problems with my vagrant recently. I pushed a PR with the change at [https://github.com/mozilla/brackets/pull/670](url). @humphd

**Comment by flukeout** [comment]
Fixed via https://github.com/mozilla/brackets/pull/670 - thank you @hkirat
