### ISSUE TITLE
Get rid of Stay Calm project from the codebase

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.mozilla.org#1917]
For some reason the ``stay-calm`` project is hard-coded into our codebase. I don't think we need it there...

![image](https://cloud.githubusercontent.com/assets/25212/24374961/89177972-12eb-11e7-9393-6e9119790c06.png)

Is that correct @humphd? If we don't - mind labeling this Good Bug, ty.

**Comment by humphd** [comment]
I don't honestly remember why we did this, it might have been just for testing purposes.  See https://github.com/mozilla/thimble.mozilla.org/pull/638 where I added it, and https://github.com/mozilla/thimble.mozilla.org/pull/733 where @gideonthomas worked on it too.  @gideonthomas do you know if we need this?

**Comment by ZenanZha** [comment]
@humphd This one related to the issue I worked on. I would like to contribute for this one.

**Comment by humphd** [comment]
@ZenanZha sounds good.  @gideonthomas can you confirm that deleting this code is correct?

**Comment by gideonthomas** [comment]
yeah pretty sure we don't use it anywhere

**Comment by flukeout** [comment]
@ZenanZha any progress on this? Please open a PR if you've made some changes or let us know if you're no longer able to work on it - thank you!

**Comment by ZenanZha** [comment]
@flukeout It takes some time to test it becuse the bramble didn't work that well.(see [Issue2012](https://github.com/mozilla/thimble.mozilla.org/issues/2012)
Sorry for the lateness.
