### ISSUE TITLE
Change Publish popup title when project is Live

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.mozilla.org#1918]
Currently, the popup title always says "Publish your Project", even if it is already published...

![image](https://cloud.githubusercontent.com/assets/25212/24376855/3cd4c860-12f2-11e7-9ba7-85da8a484922.png)

Let's change it to "Your Project is Online" when the project is published.

**Comment by rkgupta21** [comment]
I would like to work on this bug.

**Comment by flukeout** [comment]
👍 Great, go ahead!

**Comment by rkgupta21** [comment]
I found the file where header value is used. Its in publish.html
```
<h1>{{ gettext("publishHeader") }}</h1>
```
As per my understanding i need to check whether the project is published or not and if it is published then change the publish header value to the required text "Your Project is Online". Where do i need to implement the code to make this change? Is it gonna be in publish.html file ?

**Comment by humphd** [comment]
@flukeout or @gideonthomas, can you give some guidance to @rkgupta21 on how to get started with this please?

**Comment by gideonthomas** [comment]
sure! 

Your change needs to happen in the file that you mentioned. You're gonna need to write a check something like this: https://github.com/mozilla/thimble.mozilla.org/blob/master/views/editor/projects.html#L39-L42 to determine what needs to be shown in the `h1` tag. As far as localization is concerned, refer to https://github.com/mozilla/thimble.mozilla.org/wiki/Localization#strings and https://github.com/mozilla/thimble.mozilla.org/wiki/Localization#server-side-localization to add your new string.

Let us know if you have any questions @rkgupta21

**Comment by rkgupta21** [comment]
@gideonthomas 

I've added `{% if project.publish_url %}` in `publish.html`.
<img width="525" alt="screen shot 2017-04-16 at 9 28 39 pm" src="https://cloud.githubusercontent.com/assets/14276579/25076078/c739cef2-22eb-11e7-936b-9eb58257988f.png">

But i noticed that it is always going in the else condition, and always displaying `Your Project is Online` 
<img width="553" alt="screen shot 2017-04-16 at 9 26 46 pm" src="https://cloud.githubusercontent.com/assets/14276579/25076079/c73a807c-22eb-11e7-8a6c-2c675b063a40.png">

I think that `publish.html` doesnt have access to `project.publish_url`

Do I need to import anything?

**Comment by flukeout** [comment]
@rkgupta21 can you open a pull request with your changes so we can look & work on it there? It will be easier if we have access to your code changes - thank you!

**Comment by MarcoBeltempo** [comment]
Hi @flukeout , I'm currently a student at Seneca college learning open source, and I was hoping to work on this bug for my course.  If no one else is currently working on it, I'd like to give it a try.

**Comment by flukeout** [comment]
Hi @MarcoBeltempo - I think it's fair if you start work on this. @rkgupta21 has submitted a pull request here (https://github.com/mozilla/thimble.mozilla.org/pull/2022) but it looks like has has stopped working on it. Please review the notes and comments there as they might be helpful to you.

Cheers!
