### ISSUE TITLE
Make auto-complete an "on-by-default" editor setting that can be turned off.

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.mozilla.org#1920]
Let's make autocomplete (as seen below) an editor setting, and put it in the gear dropdown menu.

<img src="https://cloud.githubusercontent.com/assets/25212/24428268/ba8867e6-13c2-11e7-9fa1-3a9c3d453431.png" width="300"/>

It should be on by default, but if a user turns it off, it should stay off until the next time that it is turned off. This can be stored in localStorage along with the other editor options found in that menu.

For reference, this is autocomplete in action...

<img src="https://cloud.githubusercontent.com/assets/25212/24428286/c6f520b4-13c2-11e7-96fa-383ec269caae.png" width="300"/>

**Comment by Pomax** [comment]
It would be great if autocomplete did *not* kick on a key that is already used for normal typing, like space or enter, but instead required a different key. Or, alternatively, to have autocomplete show suggestions, *but not select the top one* until the user presses their down key or something. That way even with autocomplete, you can just keep typing your code if you want, treating autocomplete as "hints that you *can* autocomplete, but can also ignore".

I would imagine that with that change alone, the autocomplete feature would become far less of a nuisance, and much more of a powerful suggestion system, conditioning you into knowing html tag names, css properties, etc. simply by virtue of seeing them a lot, without getting in the way of writing code.

**Comment by hkirat** [comment]
Hi @flukeout 
I would like to work on this.

**Comment by flukeout** [comment]
Hey that would be great @hkirat

**Comment by humphd** [comment]
I left some technical notes about this in https://github.com/mozilla/thimble.mozilla.org/issues/1919#issuecomment-289867438, fwiw.
