### ISSUE TITLE
extend the grunfile so that `npm test` also runs eslint

### ISSUE THREAD

**Issue by Pomax** [mozilla/thimble.mozilla.org#1921]
Right now the `grunt` task that runs when you run `npm test` in thimble only runs jshint, which doesn't really do enough style profiling to work contributors that their code is not style-conformant. Let's extend that task a little so that it catches style errors, and allows TravisCI to fail when commits are push that do not follow the eslint styles we tell it to use.

**Comment by badrmodoukh** [comment]
@Pomax I would like to work on this issue :)

To do this I was thinking I would:
- install eslint
- modify the Gruntfile.js file to enable the eslint styles we want to use and the src of the files we want to check

Am I on the right track?

**Comment by Pomax** [comment]
yep that sounds about right. We'll want to probably start with very loose rules so the current code passes, and then as we tighten up the eslint rules the code will have to be updated in follow-up issues accordingly.

**Comment by badrmodoukh** [comment]
@Pomax I created the PR for this issue :)

**Comment by gideonthomas** [comment]
This is done, closing!
