### ISSUE TITLE
My thimblin' throws a "Couldn't find the dom for /365/projects/882127/index.html" error

### ISSUE THREAD

**Issue by Pomax** [mozilla/thimble.mozilla.org#1924]
I've been working on https://thimble.mozilla.org/en-US/user/mopaxian/882127, which uses the following HTML:
```
<body>
    <svg width="300" height="300" viewBox"0,0,300,300">
      <g transform="translate(10,10) scale(3,3)">
        <path d="M 68.8 49 V 21.9 c 0 -8.3 -2.8 -11.5 -8.2 -11.5 c -6.6 0 -9.3 4.7 -9.3 11.4 v 16.8 h 6.4 V 49 H 37.6 V 21.9 c 0 -8.3 -2.8 -11.5 -8.2 -11.5 c -6.6 0 -9.3 4.7 -9.3 11.4 v 16.8 h 9.2 V 49 H 0 V 38.7 h 6.4 V 11.4 H 0.1 V 1 h 20 v 7.2 C 23 3.1 28 0 34.7 0 C 41.6 0 48 3.3 50.4 10.3 C 53 3.9 58.5 0 66 0 c 8.6 0 16.5 5.2 16.5 16.6 v 22 h 6.4 V 49 H 68.8 Z"/>
      </g>
    </svg>

    <svg width="300" height="300" viewBox"0,0,300,300">
      <g transform="translate(10,10) scale(3,3)">
        <path d="" />
      </g>
    </svg>
  </body>
```
and the following script:
```
    const path1 = find("svg path")[0];
    const path2 = find("svg path")[1];

    const d = path1.get("d");

    var outline = new Receiver();
    const parser = new SVGParser(outline);
    parser.parse(d);
    
    function jitter() {
      return (Math.random() - 0.5) * 0.;
    }
    
    function next() {
      outline.getShapes().forEach(shape => {
        shape.points.forEach(p => {
          let m = p.main;
          let l = p.left;
          let r = p.right;
          [m,l,r].forEach(pt => {
            if (!pt) return;
            pt.x += jitter();
            pt.y += jitter();
          });
        });
      });
      let code = outline.toSVG();
      find("svg g path")[1].set("d", code);
      requestAnimationFrame(next);
    }
    
    next();
```
Opening this in Chrome or Firefox (probably others, didn't test) shows:

![screenshot 190](https://cloud.githubusercontent.com/assets/177243/24515289/05d273c6-152c-11e7-9035-06a5c21fb18b.png)

**Comment by humphd** [comment]
Based on my debugging, this is happening in the HTML tokenizer Brackets has, and it's not liking your attribute `viewBox"0,0,300,300"`.  Are you sure that shouldn't be `viewBox="0,0,300,300"`?

**Comment by Pomax** [comment]
Turns out there were in fact two errors. The one you flagged, which should be `viewBox="0 0 300 300"` (missing equal sign, no commas), the other being that the `jitter` function return something "times 0." rather than "times 0.5", so the jitter was zero and vertices don't look to be moving even when the animation loop is running.

Thanks for looking it over!

**Comment by humphd** [comment]
OK, glad it wasn't the tokenizer, because I'd hate to have to start fixing crap in there at this point.
