### ISSUE TITLE
Consider using yarn rather than npm for this project

### ISSUE THREAD

**Issue by Pomax** [mozilla/thimble.mozilla.org#1925]
This might also solve the binlink NPM run issue https://github.com/mozilla/thimble.mozilla.org/pull/1714

**Comment by humphd** [comment]
Even if we only do this inside Vagrant, I think it's likely a big win for the npm bugs we're hitting.  See https://yarnpkg.com/lang/en/docs/migrating-from-npm/ on how to do this.

@ryanwarsaw do you have any interest in doing this for us?

**Comment by ryanwarsaw** [comment]
Yeah I can tackle this one, just an FYI I'm currently in the midst of a long distance move to a new house so that's why my response time is so delayed and it's taking me a while to get through these tickets. Cellular data is expensive ☠️  !

**Comment by JohnEJames** [comment]
Hey I would like to work on this bug!

**Comment by humphd** [comment]
@ryanwarsaw I'm going to give this to @JohnEJames, who needs a bug for his release.  Sorry to steal it from you, but I hope you're happy to work on other stuff.  You might be interested in reviewing this.

**Comment by ryanwarsaw** [comment]
@humphd No problems at all, I apologize for the ridiculously long delays and my recent absence, I'm hoping things will return to normal in the next 4-6 weeks. Cheers.

**Comment by JohnEJames** [comment]
@humphd  I'm starting to work on this bug, would you prefer for me to only replace npm with yarn in the vagrant file? such as this [File](https://github.com/mozilla/thimble.mozilla.org/blob/master/scripts/setup-services.sh)

**Comment by humphd** [comment]
@JohnEJames correct.  Start there.

**Comment by humphd** [comment]
npm 5 is a lot better, I haven't noticed issues.  Closing.
