### ISSUE TITLE
Brackets URL Hints doesn't list folders

### ISSUE THREAD

**Issue by humphd** [mozilla/thimble.mozilla.org#1927]
![screen shot 2017-03-30 at 8 59 38 pm](https://cloud.githubusercontent.com/assets/427398/24532114/e3eb2fd6-158b-11e7-9774-a4513e103610.png)

When you type `<img src=` Brackets will give you a list of possible completions for files in the filesystem, as well as "Take a Selfie...".  It doesn't list any folders that you have, though.

We should really show the folders too.  The code for this lives in https://github.com/mozilla/brackets/blob/master/src/extensions/default/BrambleUrlCodeHints/main.js#L59-L231 I think.

**Comment by Taguiar** [comment]
@humphd 
 I would like to fix this bug!

**Comment by humphd** [comment]
@Taguiar OK, it's all yours.

**Comment by Taguiar** [comment]
Hi professor @humphd how do I issue a command to go inside the file from here?
![1](https://cloud.githubusercontent.com/assets/17263593/25032133/ba0f7478-209f-11e7-86d6-85062456f38b.PNG)

"source" is a directory with 2 .jpg images. If I manage to open the file here I will be able to display it on the popup box using something similar to what is been doing here.

![2](https://cloud.githubusercontent.com/assets/17263593/25032165/06ba0a40-20a0-11e7-9fd9-73f05a8260ba.PNG)

**Comment by humphd** [comment]
What does "go inside the file" mean?  With the filesystem you can do https://github.com/filerjs/filer#fsreaddirpath-callback or https://github.com/filerjs/filer#ls to find files.

**Comment by Taguiar** [comment]
Hi @humphd I have created this pull request on brackets https://github.com/mozilla/brackets/pull/726 please have a look as you see fit!

**Comment by humphd** [comment]
Finishing this in https://github.com/mozilla/brackets/pull/787

**Comment by flukeout** [comment]
Looks like @humphd has fixed this in the PR above, so we'll be closing this issue.
