### ISSUE TITLE
Brackets URL Hints doesn't do the right thing with spaces in path names

### ISSUE THREAD

**Issue by humphd** [mozilla/thimble.mozilla.org#1928]
![screen shot 2017-03-30 at 9 05 05 pm](https://cloud.githubusercontent.com/assets/427398/24532207/a3b8bebe-158c-11e7-9364-204fc00b1a73.png)

If a path has a space in it, Brackets URL encodes it and gives `%20` instead.  It's probably this, or something else in this file: https://github.com/mozilla/brackets/blob/master/src/extensions/default/BrambleUrlCodeHints/main.js#L562-L563

**Comment by bkim49** [comment]
Hello, could I attempt to fix this bug? @humphd

**Comment by humphd** [comment]
Sure thing, @bkim49, it's yours.  I'm just guessing above above about where the fix needs to happen, but that should get you started.  You might also want to fix #1927, which is going to need to be done in the same code.

**Comment by bkim49** [comment]
I am wondering how this bug needs to be fixed. If the space is present in the file name, should the thimble make it so that it adds a hyphen (-), underscore ( _ ), or allow spacing? @humphd

**Comment by humphd** [comment]
Try not doing any encoding and see what happens.  We might be fine with that, or we might need to just replace `%20` with `' '`.

For sure you can't add or use a hyphen or underscrore--the filename would be wrong.  The issue here is that it's looking for whatever path you give it, so if you encode to %20, it looks for that.

**Comment by bkim49** [comment]
So, the problem with this issue is that when a user selects the URL hint with spaces in between, it adds "%20" between spaces. I tried removing the encodeURI() like you suggested @humphd  and it works perfectly. I used other characters to test, and it seems like it is working without a flaw. 

![image](https://cloud.githubusercontent.com/assets/17182037/24892217/dc2b5238-1e48-11e7-9b3c-f85b2a55a66c.png)

Is there any other test I  should attempt before committing the fix? 

Another thing I noticed was the file names on the left file panel. I had bunch of images with multiple spaces between letters and characters. But the number of spaces between letters and characters were reduced to one. Not sure if this is another bug? or if bracket is supposed to have this feature.

**Comment by humphd** [comment]
@bkim49 what happens in the live preview with these filenames?  What about if you publish?  Do they all still work?

This is looking great, hopefully it will all work.  Let me know when you've tested this, and you should open a PR with your changes.

**Comment by bkim49** [comment]
Everything works well. When it is published and in live preview. @humphd 
Creating a PR now!

**Comment by humphd** [comment]
@bkim49 I think we should close this, and leave it how it is.  I'm actually rethinking what I filed originally, and it's probably correct to encode those paths.  Can you do one last test: try doing what you have above with the regular code (e.g., without your fix) and have paths with spaces; then publish and see if they all work with the encoded form of the path.

**Comment by bkim49** [comment]
@humphd I have just tested the regular code but paths with spaces. When I publish, it does not work with encoded form of the path. 
Editor:
![image](https://cloud.githubusercontent.com/assets/17182037/25209827/5f4bf240-254b-11e7-9d2e-562f9c041b1b.png)

Preview: 
![image](https://cloud.githubusercontent.com/assets/17182037/25209847/6b2260cc-254b-11e7-814c-e98c4f773c8b.png)

Published:
![image](https://cloud.githubusercontent.com/assets/17182037/25209870/7cc51b26-254b-11e7-9e76-40a73297cd3e.png)

I tried with encoded, and without, both do not work when the codes are published. But it does work in the preview.

**Comment by humphd** [comment]
I don't understand what you're seeing.  See https://thimbleprojects.org/humphd/255451/.

@Pomax can you help me decide what to do here?  Should we just allow Brackets to escape the paths (technically correct).  I'm tempted to close this and leave it as is.

**Comment by bkim49** [comment]
@humphd I tried publishing the images but it just does not show up for me. I tried it with encodeURI(), and the images are broken up. My thimble repository is up-to-date as well. Is it because I am trying this on localhost?

**Comment by humphd** [comment]
It's possible that the local server we are using for showing published projects in dev isn't aware of how to deal with this properly.

**Comment by bkim49** [comment]
Ah okay. So do you want me to close the pull request I made for this issue? @humphd

**Comment by humphd** [comment]
I'm not sure, need to consider more.  Regardless, I'll count this for your release, so please submit it.

**Comment by humphd** [comment]
I think this behaviour is actually correct, I'm going to close this.
