### ISSUE TITLE
Add "Updates Available" UX for new service worker cached content

### ISSUE THREAD

**Issue by humphd** [mozilla/thimble.mozilla.org#1930]
In Brackets, and eventually in Thimble (#1459), we cache and serve static resources so that offline use cases work.  When a service worker has new content, we really should provide the user with some kind of UI that indicates they need to refresh the browser in order to load the new code.  It's a lot like having a "Updates Installed, Restart Required..." UX for a native app.

Depending on what the change is that's been updated in the cache, the update may or may not be critical for the code to continue to work.  An example is when we make changes to `dist/bramble.js` and Thimble needs to call some API function in Bramble that isn't available in the old version.  Running Brackets and Thimble separately means that they can drift out of compatibility until you refresh and force the cached code to get loaded.

Right now we don't do anything, and it worries me.  I'd like to add some kind of UI for the user to tell them that they need to refresh before they continue to use the app.  Once we have this, I can wire up the various bits of Brackets and Thimble to use it.

@flukeout this is probably worth doing before we update prod with all our new changes.

**Comment by flukeout** [comment]
Hey @humphd, some questions:

* Don't most common actions (opening a project, starting a new one) already refresh the browser?
  * Or is refreshing different somehow than re-loading? Would they need to hard-refresh?
* If we can detect this case, can we refresh for them when they are on say, the green loading screen?

**Comment by humphd** [comment]
@flukeout there are a lot of edge cases with this.  I'll try to summarize what I understand:

* First time user opens thimble.mozilla.org and starts a new project.  The service worker will install, and all resources will get downloaded and cached in the service worker's cache (SWC).  When they are done, they close the tab.
* Same user, next day, opens a new tab and loads Thimble to start a new project.  The entire site will load from SWC immediately, and the user starts working.  In the background, the service worker will also go to the network and download the resources again, refreshing what's in the SWC.
* If the files in the SWC are newer than what's currently being run in the page, we'll get an event from the service worker telling us that there are updates.  This is the moment where we should give a hint to the user that there are updates they could use if they refresh.
* Could we refresh for them?  I don't think that's a great strategy, since there is no way to know when those updates will finish arriving and be available.  Almost always it will be after the green loading screens.

The refresh they do will load really fast, since it won't need to touch the network (i.e., everything will come from the SWC).

**Comment by flukeout** [comment]
Okay, here's a concept for some UI to get people to refresh. Wording TBD.

![image](https://cloud.githubusercontent.com/assets/25212/24631596/c22c392a-1875-11e7-8b12-2c1b09c678d0.png)

**Options**
* **Thimble needs a Reload** - We've updated some code, reload this page in your browser. **[Reload]**

**Comment by humphd** [comment]
So this would push things down at the top?

I'm working on a PR to do the event to trigger this.  If you're willing to do the UI, or a student is, I'll hook it all together.

**Comment by humphd** [comment]
See also https://github.com/mozilla/thimble.mozilla.org/issues/1931

**Comment by humphd** [comment]
@simon66 is going to take this.

**Comment by amitsin6h** [comment]
can i work in this bug

**Comment by humphd** [comment]
@amitsin6h the comment above yours already says it's being worked on by @simon66.  Take a look at the bugs that don't have Assigned to Contributor already in their labels.

**Comment by simon66** [comment]
Hey @flukeout, can we chat about this :)

**Comment by humphd** [comment]
FYI, I've just landed the Brackets backend portion of this in https://github.com/mozilla/brackets/pull/691, which adds the events we'll need from Brackets.  I'm working on doing the same thing in Thimble in another PR I'll put up soon.

**Comment by humphd** [comment]
@flukeout and @simon66: here are some thoughts for you about what I think this needs.

Both Brackets and Thimble are each going to have offline capabilities.  In both apps, we are going to know 2 things:

* when the code becomes available to run offline (i.e., it's been cached)
* when there are updates to the code in the offline cache, and the user should (possibly) refresh

There is no telling when the second event will happen, and it might be required, or just a nice to have update (e.g., breaking change vs. css colour change)--there's no way to tell.

We should give some thought to the case that the app is loading (green Loading screen) vs. the app is running the editor.  In the first case, you probably want to encourage a refresh?  In the second case, you're already running, so it's probably safe to wait and you might just want to provide a hint.

This is going to take some iteration and testing on staging to get right.

**Comment by humphd** [comment]
I'm starting the offline work for Thimble in https://github.com/mozilla/thimble.mozilla.org/pull/1984

**Comment by humphd** [comment]
As part of this bug, let's also fix this page:

![screen shot 2017-04-13 at 11 52 50 am](https://cloud.githubusercontent.com/assets/427398/25012928/edbee746-203f-11e7-8ff1-9b0eed287610.png)

When we hit an error loading the project, or can't load Bramble, we show this error page.  Let's make some modifications:

* "There was an error loading your Project" should probably say "There was an error loading Thimble"
* We should make the "Please refresh your browser" more obvious, and perhaps have it be a button you can click which will actually do something.  Let's make it easy to *do* something when you hit this page.
* The copy for private browsing mode and dev tools should be made smaller.

The focus of this should be: something went wrong, click here to **try again**.

**Comment by humphd** [comment]
Escalating this for Launch, and assigning to @flukeout and me.

@flukeout, you can use the events in Thimble like this:

```js
        // We may not care about this one yet, but later we can use it to indicate offline-ready
        Bramble.on("offlineReady", function() {
            console.log("Bramble available for offline use.");
        });

        // This is the one we care about, and should show a UI hint to allow you to refresh.
        Bramble.on("updatesAvailable", function() {
            console.log("Bramble offline content updated, please refresh to use.");
});
```
