### ISSUE TITLE
Remove filename from Image Viewer + Small tweaks

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.mozilla.org#1934]
When you click on a file, Thimble shows it to you in this handy Image Viewer....

![image](https://cloud.githubusercontent.com/assets/25212/24572585/ab484d1e-162e-11e7-9183-a4bc9047f920.png)

This viewer also includes the filename, ``selfie2.png`` in the image above. Let's ditch it, the editor bar above already shows the filename.

**Additional Improvements**
* Include width and height labels in the image size
  * ``320 (width) x 240 (height) pixels``
  * People might not know the width first, height second convention for the current notation
* Change font inside viewer to Open Sans
* **New** - For the ``dark`` theme, make the background of the Image Viewer ``#222`` instead of black so that it matches the color of the code editor.

**Comment by flukeout** [comment]
```
Blam
```

**Comment by omytryniuk** [comment]
@flukeout, I would like to improve it

**Comment by flukeout** [comment]
Sounds good @omytryniuk - all yours

**Comment by humphd** [comment]
See https://github.com/mozilla/brackets/blob/master/src/editor/ImageViewer.js for where most of this code happens, and the HTML/CSS it loads.

**Comment by omytryniuk** [comment]
@humphd, thank you! Yes, i have already fixed this. I am just going to change css and it will be ready to push

**Comment by flukeout** [comment]
Looking forward to it @omytryniuk

**Comment by flukeout** [comment]
Hey @omytryniuk - in case you're tackling the other **Additional Improvements** in the issue description, I've added one more.

**Comment by omytryniuk** [comment]
Hello @flukeout. I have removed filename from ImageViewer, as well as added the tweaks (including the one with darkTheme background colour). Feel free to contact me if you need some changes. Thank you!

**Comment by flukeout** [comment]
Thanks @omytryniuk - testing it out now.

**Comment by flukeout** [comment]
Closing as it's been addressed in https://github.com/mozilla/brackets/pull/689 - thanks @omytryniuk
