### ISSUE TITLE
Switch to webpack from requirejs

### ISSUE THREAD

**Issue by humphd** [mozilla/thimble.mozilla.org#1947]
I closed #1767 earlier, but after talking to @gideonthomas I think we should start moving toward some of this.  The first thing I think we should do is switch to webpack for building our website.  We currently use AMD-style modules with requirejs.  We can either stick with that for now, and just have webpack use these as they are; or we can also switch to CommonJS at the same time.

Let's have one of our goals be to streamline the Thimble build so that all resources are as small, as as few as possible (e.g., one CSS file, one or only a few JS, small images, etc), add live reloading or hot swapping, etc.  Let's also do this in small, incremental steps (i.e., file more bugs as we go), so we don't disrupt our current devs.

**Comment by Pomax** [comment]
I'd love to move away from require.js in favour of a commonjs, but in that case it might be even better to skip over commonjs entirely and switch from require.js to ES6 modules and have webpack with babel take care of the "converting it when bundling".

I don't know if there is a way to do this in parts - I know webpack can generate UMD libraries just fine so we could start converting isolated bits of code and see if we can still run require.js but *after* a webpack/babel step converts all no-longer-require.js to a umd library with the `define`s that require.js code expects?

This will be tricky....!

**Comment by humphd** [comment]
Personally, I wouldn't choose to migrate to ES6 yet.  I think it puts a burden on our dev community, which is currently comprised of a lot of beginners, and in my experience, ES6 isn't as easy to learn/teach.  That won't always be the case, because it will come to be the standard we all use.  But that's not where we are yet.

**Comment by humphd** [comment]
This is done.
