### ISSUE TITLE
Change "Create new Project" button styling after it is clicked.

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.mozilla.org#1949]
On the **Your Projects** page, after you click the "Create New Project" button. We change the button label, but otherwise keep the button styling the same as it was before, including the ``:hover`` and ``:active`` styling. 

![button-disable](https://cloud.githubusercontent.com/assets/25212/24620176/81238b32-1851-11e7-828e-4281cd5e9b56.gif)

Let's change it so that once a user clicks this button, we grey it out (or fade it with something like ``opacity: .5`` and remove the ``:hover`` and ``:active`` styling.

**Comment by Abykin** [comment]
Hey @flukeout I'd like to give this one a go

**Comment by flukeout** [comment]
Great, let me know if you have any questions @Abykin

**Comment by Rajat-dhyani** [comment]
@Abykin  hey still working on this ?

**Comment by Abykin** [comment]
@Rajat-dhyani Hey, yeah I will try to get my PR up today

**Comment by Rajat-dhyani** [comment]
hey @Abykin do [these](https://github.com/Rajat-dhyani/thimble.mozilla.org/commit/0b96c233c1842ab6dbb88d25af677a1ba354c43d) changes and it will work

**Comment by Abykin** [comment]
@Rajat-dhyani Thanks that worked! Had some issues running my thimble locally took a while.

**Comment by Abykin** [comment]
@flukeout PR here https://github.com/mozilla/thimble.mozilla.org/pull/2000

**Comment by Rajat-dhyani** [comment]
glad to help @Abykin 😊👍
