### ISSUE TITLE
Enable tg (Tajik) locale on production

### ISSUE THREAD

**Issue by TheoChevalier** [mozilla/thimble.mozilla.org#1950]
As a follow up of #1866, Tajik is now 100% complete!
https://pontoon.mozilla.org/tg/thimble/ (congrats to our new volunteers! 🎉)
Tajik can now be added to the list of supported languages enabled on production

**Comment by humphd** [comment]
Fantastic!  Assigning to @gideonthomas.

**Comment by bkim49** [comment]
#1963 is related to this bug. Please take a look! Thanks!

**Comment by gideonthomas** [comment]
@TheoChevalier, I think I need your help here. We need the native name and english name of the language and if possible, would https://product-details.mozilla.org/1.0/languages.json also be able to include that?

**Comment by gideonthomas** [comment]
Blocked on https://github.com/mozilla/node-webmaker-i18n/pull/57

**Comment by TheoChevalier** [comment]
@us-mahina could you confirm that `забо́ни тоҷикӣ́` is the correct way to translate `Tajik` in Tajik? Having hard time finding it in CLDR data :/

@gideonthomas Will check, but we should be able to add it to product-details, yeah

**Comment by gideonthomas** [comment]
@us-mahina any updates on this?

@TheoChevalier, since we're re-launching next week, is it ok to assume what you have commented here as the native name for Tajik is correct and use that (and fix later if needed)?

**Comment by TheoChevalier** [comment]
@gideonthomas Yeah, we can use it for the launch and fix it as needed, but I would wait to have a confirmation from a native speaker before adding it to product-details

**Comment by gideonthomas** [comment]
Alright sounds good! Thanks!

**Comment by gideonthomas** [comment]
It should show up on staging now. Will keep it open so that I'll remember to enable it on production

**Comment by humphd** [comment]
@gideonthomas can we close this now?  Is it on prod?

**Comment by gideonthomas** [comment]
Yeah
