### ISSUE TITLE
Publishing projects without index.html fails to locate it.

### ISSUE THREAD

**Issue by dsych** [mozilla/thimble.mozilla.org#1952]
When publishing project without index.html file, the resulting link leads to a broken project. 

![no_index](https://cloud.githubusercontent.com/assets/16144679/24671349/39ae0432-193f-11e7-948d-3c850add8572.png)

While the resulting page has a suggestion on potential cause of the problem, however the existence of index.html should be checked at the publish time, and feedback should provided. Maybe block the publish button and provide feedback here:

![no_index_2](https://cloud.githubusercontent.com/assets/16144679/24671534/c70bb626-193f-11e7-8cf0-696fc3e7813b.png)

**Comment by dsych** [comment]
This is related https://github.com/mozilla/brackets/pull/620

**Comment by flukeout** [comment]
Hey @dsych - we've been down this road before and ended up with the solution to add the help text on that page. Before that change, we got quite a few support emails about "Projects not working" & the change seems to have helped a lot.

Your suggestion is one of the few we discussed, and I think it would still be a good idea. You can see some background discussion about it in this issue.

https://github.com/mozilla/thimble.mozilla.org/issues/1569#issuecomment-259006400

I'm not sure if totally blocking publishing is the right idea, there could be some valid cases where you wouldn't need an index page. We could just add a warning or something like that.

**Comment by dsych** [comment]
@flukeout in https://github.com/mozilla/thimble.mozilla.org/issues/1569#issuecomment-259006400 , your first idea with the pop-up could solve the problem before the publishing occurs. Moreover, now that I am working on the API that will allow us to check project for the index.html file, implementing the pop-up message should not be an issue.

**Comment by dsych** [comment]
Maybe we can just reuse the same publishing window, however when a project is lacking the index.html file, the "Publish" button will be of different colour, say orange. There will also be a highlighted reasoning to the left of the cancel.

**Comment by MargarytaChepiga** [comment]
Can I work on this bug? @humphd

**Comment by dsych** [comment]
@MargarytaChepiga @humphd this is part of my previous release.

**Comment by humphd** [comment]
@MargarytaChepiga I think @dsych is tackling this, based on his earlier work.

**Comment by dsych** [comment]
@flukeout did you have a chance to decide what is the better way to warn user about the absence of index.html?

**Comment by flukeout** [comment]
Hey @dsych - not yet, BUT - please go ahead and start on this. We'll assume that we need two things:

* A class on the publish dialog, something like ".no-index"
* A div with an error message in the publish dialog

If you can start and get those things into a PR, then I can finalize the styling (and assist later by making a PR against your branch).

I guess optionally, we can think about disabling the publish button when there is no index, but we can achieve that with CSS maybe anyway (by disabling pointer events) or hiding the real publish button and showing a 'disabled' faked one.

Thanks!
