### ISSUE TITLE
XML Parsing Error in Firefox

### ISSUE THREAD

**Issue by humphd** [mozilla/thimble.mozilla.org#1954]
Loading staging in Firefox, I see this:

```
XML Parsing Error: not well-formed
Location: https://mozillathimblelivepreview.net/bramble/staging/dist/extensions/default/brackets-show-whitespace/styles/whitespace-colors-css.tmpl
Line Number 1, Column 1:
```

If memory serves, I think this is probably a mime type issue with what we put in S3 on build that only Firefox seems to care about.  We might actually have this filed somewhere already, but I can't find it.

Another fix for this would be to alter how that code works, and not bother with this made-up `.tmpl` type, and just make it some kind of text file or css file.

**Comment by simon66** [comment]
Hi @humphd,

You're right, I saw an issue similar to this somewhere (I'll link it here if I can find it).
Mind if I tackle this 👍

**Comment by humphd** [comment]
@simon66 and I confirmed that this was fixed when I landed the requirejs extension bundling stuff.  Closing.
