### ISSUE TITLE
Add hover state to Homepage Gallery Remix button.

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.mozilla.org#1956]
Doesn't have one currently...

![image](https://cloud.githubusercontent.com/assets/25212/24729264/3901e50c-1a12-11e7-9cbb-22b8da47d45b.png)

**Comment by omytryniuk** [comment]
@flukeout  I will fix that.

**Comment by omytryniuk** [comment]
Here is the [fix](https://github.com/mozilla/thimble.mozilla.org/pull/1958). I forgot to include Fix # in a commit message and as a result, the commit does not link to the issue.

**Comment by flukeout** [comment]
Thanks, and you can just add the ``Fixes #blah`` to the PR description when submitting the PR (or anytime after really).

**Comment by omytryniuk** [comment]
Thank you for the advice! I have renamed the PR title and it did not work, but I tried and it works if I update description for example.
