### ISSUE TITLE
Typo in autocomplete button label

### ISSUE THREAD

**Issue by TheoChevalier** [mozilla/thimble.mozilla.org#1960]
As noticed by a localizer, this landed with a typo: https://github.com/mozilla/thimble.mozilla.org/commit/274f5526a33c52d17d6d95a9dd9d1249591c42d6#diff-aef074d5302a863440aa549e7a2fd981R63

Autcomplete code > Autocomplete code

In this case we can keep the same string ID and just fix the typo, since the meaning remains the same

CC @humphd

**Comment by humphd** [comment]
@hkirat can you fix this please?

**Comment by humphd** [comment]
Fixed!  Thanks for filing @TheoChevalier, and thanks for fixing @hkirat.
