### ISSUE TITLE
Language menu is too tall, runs off page.

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.mozilla.org#1962]
The language dropdown has a ton of languages in it now, and it's getting too long for my screen.

**We could either**

* Give it a max-heigh or something and have it scroll
* Rearrange into 3 columns
* Something else...

<img src="https://cloud.githubusercontent.com/assets/25212/24776462/beb33d18-1ad5-11e7-9dc8-8a2eb09c7e4a.png" width="350" />

**Comment by cgsingh** [comment]
I'd like to take this on.

**Comment by humphd** [comment]
Go for it @cgsingh.
