### ISSUE TITLE
Improve UX of clicking small icons in the preview & editor bars.

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.mozilla.org#1966]
Check out the screengrab below. I click the icon, then move the mouse only a few pixels, which causes the ``<img />`` used in the icon to star dragging, and also stops my click from registering. 

![icon-drag](https://cloud.githubusercontent.com/assets/25212/24811212/e7c29768-1b79-11e7-94de-1fefa3cd637d.gif)

This leads the UI to sometimes not doing what you wanted, which is annoying. We should fix this. 

* Maybe instead of click events, we fire the UI on ``mousedown``
* Maybe we shouldn't use ``<img/>`` tags in there, and just rely on background images
  * This will prevent the dragging behaviour
* Maybe something else...

**Comment by cgsingh** [comment]
Well, I'm not committing to this issue just yet, but I do have have an idea I'll implement if you think it's acceptable (otherwise I'll stay on the outskirts for now and let someone else take a jab at it, but I'll come back if I have another idea if no one else takes this by then). Anyway, my first idea involves the least amount of coding. Pretty much, make the click events `mousedown` and set the `draggable` attribute on these elements as `false`. What do you think?

**Comment by amitsin6h** [comment]
Hey i want to work on this bug

**Comment by flukeout** [comment]
Hey @amitsin6h go ahead - I think @cgsingh's solution might be a good starting point.

**Comment by flukeout** [comment]
Any progress on this @amitsin6h? Let us know if you're unable to work on this - thanks!

**Comment by amitsin6h** [comment]
So sorry I have been bit busy .. just started to work @flukeout

**Comment by dfperry5** [comment]
Hey guys,

Is anyone working on this? 

It'd be my first time contributing and i'd love to use @cgsingh's solution as a jumping off point!

Thanks!

**Comment by amitsin6h** [comment]
you can work on this @dfperry5

**Comment by flukeout** [comment]
Cool, go ahead @dfperry5 - let us know if you run into trouble or have questions.

**Comment by dfperry5** [comment]
Awesome guys! I'll be playing around it today (I'm traveling) but ill try to have the starts of a PR opened pretty soon! 

Thanks!

**Comment by flukeout** [comment]
@dfperry5 - have you given this a try? Let us know. Thanks.

**Comment by dfperry5** [comment]
@flukeout  I started grad school and got caught up in all of that - I'd love to still give it a shot. Do i just fork the repo? or is cutting a branch off better?

**Comment by gideonthomas** [comment]
@dfperry5 you would need to create a fork so that when you open up a PR, you can push to a branch on your fork.

**Comment by dfperry5** [comment]
Hey @flukeout  @gideonthomas  Sorry to be such a noob here - but when I was trying to build brambles on my local, I was getting an error about missing text.js in src/thirdparty/text directory.

Also, when i copy those files (following links from the repo to here: https://github.com/requirejs/text/tree/35c3ead097a9ede09469172666cc96349d2ce3e4. I am getting similar errors for l18n directory, and then for the filter directory as well. 

Any idea what I am doing wrong in setup?

Thanks!

**Comment by ryanwarsaw** [comment]
@dfperry5 You have to add the ```--recursive`` flag to your ```git clone``` command as it'll initialize all the sub-modules, and that should make that error go away.

**Comment by flukeout** [comment]
Let us know if that helped @dfperry5

**Comment by dfperry5** [comment]
@flukeout @ryanwarsaw  Thanks :) Worked like a charm!

**Comment by dfperry5** [comment]
@flukeout @ryanwarsaw 

Noob question #2: I am making changes in this file: /public/editor/scripts/editor/js/fc/bramble-ui-bridge.js.  Trying to make the .click events for the preview-pane-nav-desktop && #preview-pane-nav-phone into .mousedown events. When i make these changes, I see them reflected in the dist folder, but those changes dont seem to be making it to the UI. Any quick thoughts on what I'm missing. 

I made a quick change in the /views/editor/nav-options.html as well to make the draggable attribute false. 

Does it seem like I am on the right track?

**Comment by gideonthomas** [comment]
@dfperry5, sorry for the late reply. One possibility is that the browser is aggressively caching your pages. If you keep your devtools/console open, you can circumvent this. Here's an article on how you might do that: http://nicholasbering.ca/tools/2016/10/09/devtools-disable-caching/. Let us know if you have any other issues.

**Comment by pradeepgangwar** [comment]
@gideonthomas is anybody still working in this? I am looking for my first issue on thimble. This may be a good point to start .

**Comment by humphd** [comment]
@pradeepgangwar if you'd like to work on this, I think it's safe to say that no one else is doing it currently (if I'm wrong, I apologize, and please correct me).

I think the best thing to do is to follow the advice given above:

> make the click events mousedown and set the draggable attribute on these elements as false.

Why don't you start with this bug (I see you've commented on some others) and see how things go.
