### ISSUE TITLE
Light theme in Brackets doesn't highlight all the way across the filetree

### ISSUE THREAD

**Issue by humphd** [mozilla/thimble.mozilla.org#1974]
![screen shot 2017-04-10 at 1 55 47 pm](https://cloud.githubusercontent.com/assets/427398/24875288/a01ce714-1df5-11e7-8f72-0b881a4762ee.png)

This actually happens in both themes, but it's most noticeable in the light theme.  We have an area where the scrollbar goes that doesn't get covered, and it looks odd.

**Comment by rkgupta21** [comment]
I would like to work on this issue.

**Comment by humphd** [comment]
Go for it.  I took that screenshot on Chrome on macOS, in case it matters.

**Comment by flukeout** [comment]
Interesting - it's not happening for me, nor have I noticed it while working on the themes. I wonder what's causing it. Anything special about your setup. Was the gap there right away @humphd ?

![image](https://cloud.githubusercontent.com/assets/25212/24885031/245ad134-1e01-11e7-9e5d-0aaa6d493dfc.png)

**Comment by humphd** [comment]
![highlight-bug](https://cloud.githubusercontent.com/assets/427398/24885208/3324f11c-1e1b-11e7-92f5-e24c5c9538a3.gif)

It's related to the scrollbar, and if you don't have enough files to need it, it doesn't happen.  Shrink your window.

**Comment by rkgupta21** [comment]
Hey David,

I was just confused while fixing this issue. I managed to increase the padding size but then the scrollbar would extend to editor area. I am assuming that i might have to modify sidebar.css. I could use some guidance here.

**Comment by humphd** [comment]
It's caused by `overflow: auto` on the tree container:

![overflow-bug](https://cloud.githubusercontent.com/assets/427398/25093492/850610c0-2360-11e7-9c9e-e18fc86d55cf.gif)

@flukeout might have ideas on how best to fix this, and where.

**Comment by flukeout** [comment]
I'll look into it now.

**Comment by flukeout** [comment]
Okay @rkgupta21 - I think I found it. Looks like brackets is using something called ``quiet-scrollbars`` which have a webkit specific style override in ``brackets_scrollbar.less``...

```
    ::-webkit-scrollbar {
        width: 9px;
        height: 9px;
        background-color: orange;
    }
```

If you find this, setting the width to ``0`` seems to do the trick. The gap we're seeing is the ``9px`` reserved for the scrollbar.
