### ISSUE TITLE
Image Viewer: Transparent background images look bad when using Dark Theme

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.mozilla.org#1976]
The dark background in the image viewer makes it hard to see transparent images.

![image](https://cloud.githubusercontent.com/assets/25212/24883363/6e3c4dda-1df9-11e7-9829-bce7562302b8.png)

There is a checkered pattern underneath the image that is probably transparent and is letting the black color through. We should give the area underneath the image a white background always, despite what theme is currently used.

Also, we could probably stand to make that checker pattern a little bigger.

**Comment by flukeout** [comment]
Actually, it looks like there are different background images set behind the preview image that change depending on the theme.

**Comment by bbhagwandeen** [comment]
I'd like to try this

**Comment by flukeout** [comment]
Right on, please go ahead @bbhagwandeen

**Comment by amitsin6h** [comment]
Hey i want to work on this bug

**Comment by humphd** [comment]
@amitsin6h same story here, already claimed right above you.

**Comment by flukeout** [comment]
Any progress on this @bbhagwandeen? Let us know in case you've stopped working on it.

**Comment by bbhagwandeen** [comment]
Hey, @flukeout still working on it. It's top priority right now. Just heading to work now and then I'll be back at it around 10:30pm.

**Comment by flukeout** [comment]
Thanks for the update, no hurry - just wanted to check that you were still on it!

**Comment by flukeout** [comment]
Fixed via https://github.com/mozilla/brackets/pull/744#pullrequestreview-41367189
