### ISSUE TITLE
CommandManager.js & Menus.js errors in console

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.mozilla.org#1978]
I'm seeing these every time I load a project, and I'll tell ya, I don't like it and it's making me worried:

![image](https://cloud.githubusercontent.com/assets/25212/24920025/83f5739e-1e9a-11e7-86e2-5ed6858b0758.png)

I'm the latest master branch of both Thimble & Brackets.

**Comment by humphd** [comment]
Dupe of https://github.com/mozilla/thimble.mozilla.org/issues/1862, also being fixed in https://github.com/mozilla/brackets/pull/680.  cc @dangkhue27
