### ISSUE TITLE
Image viewer doesn't show image details unless "npm run localize" is run first.

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.mozilla.org#1981]
This seems weird, the Image Viewer needs ``npm run localize`` to be run every time, which then creates all the localization files that you have to ``unlocalize`` later. We're not supposed to commit these files right, shouldn't they be built automatically somehow at this point?

cc @gideonthomas

**Comment by humphd** [comment]
The work that @dangkhue27 is doing in https://github.com/mozilla/brackets/pull/680 will make this better.  Our localization stuff depends on a build step, there's no way around it.  Automating it is the only way I can see.

**Comment by gideonthomas** [comment]
@humphd does the imageviewer depend on any l10n strings that we generate (i.e. did we land code in the imageviewer that uses a new string)? If not, it shouldn't break.

**Comment by humphd** [comment]
Yeah, @flukeout had him add `(width)` and `(height)`.

**Comment by gideonthomas** [comment]
ah I see
