### ISSUE TITLE
Line height is too small

### ISSUE THREAD

**Issue by gideonthomas** [mozilla/thimble.mozilla.org#1988]
![screen shot 2017-04-12 at 2 03 53 pm](https://cloud.githubusercontent.com/assets/5816130/24972338/21bd8000-1f89-11e7-863b-e2dd09c4f3dd.png)

In the publish dialog, the bottom of the `g` in the url is cut off because the line height is set to the same value as the font-size we're using. I think we probably just need to either remove the line-height or set it to something bigger. If we want to maintain the same space in the blue box, we can reduce the padding.

cc @flukeout

**Comment by flukeout** [comment]
"Good-eye" Gideon they call him. Of course he only finds the problems related to the character "g".

**Comment by morrme** [comment]
@gideonthomas @flukeout  

This seems to be the line in question: 

https://github.com/mozilla/thimble.mozilla.org/blob/master/public/editor/stylesheets/publish.less#L71

which setting would you prefer to try first--removing the line-height or setting it to a larger value?

**Comment by rkgupta21** [comment]
Hey i would like to work on this bug.

**Comment by humphd** [comment]
@rkgupta21 it looks to me like @morrme is already attempting it, is that correct @morrme?

**Comment by morrme** [comment]
@humphd yes, :) thanks!

**Comment by humphd** [comment]
OK, thanks for confirming @morrme.  Go for it.

**Comment by morrme** [comment]
@humphd I appreciate it. I was just waiting for @gideonthomas ' preference on the first option to try, but I've located the setting (I believe) and can make the change quickly.

**Comment by gideonthomas** [comment]
@morrme let's just remove the line-height for now. I would suggest reducing the padding of the container slightly as well so that it doesn't look to tall. Open up a PR and @flukeout can suggest changes based on how it looks.
