### ISSUE TITLE
Add some DNS, Resource prefetch and preload meta info to Thimble

### ISSUE THREAD

**Issue by humphd** [mozilla/thimble.mozilla.org#1991]
Some great speedups discussed in https://csswizardry.com/2013/01/front-end-performance-for-web-designers-and-front-end-developers/#section:dns-prefetching and https://css-tricks.com/prefetching-preloading-prebrowsing/.

In https://github.com/mozilla/thimble.mozilla.org/issues/1524 we're undoing my hacky way of preloading these big Bramble resources.  We can use this proper way instead.

**Comment by Mordax** [comment]
I'm interested in working on this if it's alright.

For clarification's sake: My understanding on the issue (if I'm correct) is to speed up the [c8fec1e](https://github.com/mozilla/thimble.mozilla.org/commit/c8fec1ed5627d507d16480e341e8c54f45d03b22) resources that you talk about in #1524. 

Is it important to have the resources already cached in the browser or do we just want the editor to be able to quickly resolve the location?

**Comment by humphd** [comment]
The files that are currently being precached using JS should be cached using these more modern, standard ways.  It's the big files in Brackets that I want to pre-fetch/cache while the user is on the homepage doing other things; the idea being that when they finally load the editor, it will load faster.
