### ISSUE TITLE
Translating Thimble into Vietnamese

### ISSUE THREAD

**Issue by dangkhue27** [mozilla/thimble.mozilla.org#1993]
Hi @TheoChevalier,
I would like to translate Thimble into Vietnamese and I was told that you could assist me on how to this. I hope you don't mind pointing me to where I can start doing the translation. So far, I know that I will need to work with Pontoon.
Thanks.

**Comment by humphd** [comment]
@dangkhue27 while we wait for @TheoChevalier's reply, see his advice in a similar bug:

https://github.com/mozilla/thimble.mozilla.org/issues/1866#issuecomment-286168202

**Comment by dangkhue27** [comment]
It seems all I can do at the moment is creating an account for Pontoon. Here's the email address that I've used: 
trandangkhue27@gmail.com

**Comment by TheoChevalier** [comment]
Hi @dangkhue27,

Thanks for proposing your help :) Just sent an email to the Vietnamese team (CCed you), to check how we should proceed

**Comment by TheoChevalier** [comment]
Project enabled, will be available here in ~20 minutes https://pontoon.mozilla.org/vi/thimble
Happy localizing!
