### ISSUE TITLE
[IE11] File Tree has no files in Thimble, works with Brackets alone

### ISSUE THREAD

**Issue by humphd** [mozilla/thimble.mozilla.org#1995]
I was debugging https://github.com/mozilla/brackets/issues/598 today, and noticed that if I run Brackets on its own, I get a filesystem.  However, with Thimble, I have no files:

![](https://cloud.githubusercontent.com/assets/427398/25016792/5b51574e-204f-11e7-81e6-2d3fe2ca893e.png)

If I add a file manually, it works.  Something is breaking when it tries to write the initial filesystem, maybe in the `tar` worker thread?  Just guessing.

Someone with access to Windows/IE11 should help us figure out what this is.

**Comment by Rajat-dhyani** [comment]
@humphd sir just tried this on IE11 it works fine for me.... both on thimble and on brackets.... 
![image](https://cloud.githubusercontent.com/assets/17648963/25072150/47e60dce-22e5-11e7-9034-41a1764e9d27.png)
![image](https://cloud.githubusercontent.com/assets/17648963/25072154/7531695e-22e5-11e7-9006-0f49681b59fd.png)

could you please tell me the steps to reproduce ?

**Comment by humphd** [comment]
It looks to me like you're using IE11 vs. Edge (for rendering engine in dev tools), I wonder if that's the difference?  For me, I just loaded it and it it did what I showed, no steps per se.

**Comment by Rajat-dhyani** [comment]
@humphd  sir everything seems good with both edge and IE11. which version of windows you are using may be it is specific to version? I am on window 10

**Comment by humphd** [comment]
I'm also on Windows 10.  It sounds like this can't be reproduced, so let's close this.  Thanks for testing @Rajat-dhyani.

**Comment by Rajat-dhyani** [comment]
Anytime sir 👍 @humphd
