### ISSUE TITLE
Look into adding Thimble logo / restyling id.webmaker.org

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.mozilla.org#1996]
By recent count:

* 93% of people who hit the /sign-in page come from Thimble
* 76% of people who hit the /sign-up page come from Thimble

Yet neither of these pages references Thimble & in addition, the welcome email for new accounts doesn't reference Thimble either.

**In the least we could**

* Change the styling & content of these pages to include a Thimble Reference
* Add some Thimble-specific content to the welcome email

**Comment by edyedy123** [comment]
I'll try this

**Comment by flukeout** [comment]
Hey @edyedy123 - I've got this assigned to myself. I have to check in about what changes we can make and come up with the design first. I can ping you here later depending on the scope of the changes, but right now there's no to be done until I can follow up. Thanks!

**Comment by flukeout** [comment]
I've made these changes and they are reflected in https://id.mofostaging.net/signup
