### ISSUE TITLE
Brackets editor not able to edit files when running in localhost from /dist folder

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.mozilla.org#2004]
See screenshot below, the editor is always blank no matter what file I try to edit...

![image](https://cloud.githubusercontent.com/assets/25212/25194986/14565a78-24f1-11e7-9197-91bf692f483a.png)

Works fine from ``http://localhost:8000/src/hosted.html`` but not ``http://localhost:8000/dist/hosted.html``

**Comment by humphd** [comment]
It looks like we also broke the CSS for the image viewer to show swatches of colours:

![screen shot 2017-04-19 at 2 20 22 pm](https://cloud.githubusercontent.com/assets/427398/25195370/66be3ee2-250b-11e7-9a4e-65daa46e213a.png)

Which is defined in:

```
src/styles/bramble_overrides.less:.swatch-wrapper {
```
