### ISSUE TITLE
bramble_overrides.less file is being applied before the styles it is meant to override.

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.mozilla.org#2005]
cc @humphd - looks like the new order is messing us up a bit, for example, the horz-resizer styles that are being cancelled out here...

![image](https://cloud.githubusercontent.com/assets/25212/25200241/7362afba-2502-11e7-967b-e60b40e4feaa.png)

Are the ones that are supposed to be applied second. We *could* add ``!important`` to all of the overrides. Or maybe could we ``@import`` ALL of the CSS into one main file instead of adding ``@imports`` above the existing styles? Then we could control the order better.

**Comment by humphd** [comment]
This is due to us doing the `import`.  I think we are going to have to accept loading 2 separate stylesheets.

The other solution would be to `import` the `brackets.less` file *into* `bramble_overrides.less` and maybe change it to `bramble.less`.  What do you think?

**Comment by flukeout** [comment]
Can we have a ``main.less`` file that doesn't have any styles that we import everything into? Is that possible? Otherwise two is fine.

**Comment by humphd** [comment]
Tell me more about what you want wrt `main.less`.  That's kind of what I'm suggesting with us importing everything first into `bramble_overrides.less`, and then we'd literally override things.

If you do the layout of what you want, I'll do the patch.  My only ask is that we aim to do it with 1 `.css` file when done to streamline loading.

**Comment by flukeout** [comment]
Yeah so there's a blank (ie. no rules) ``main.less`` file that only has a bunch of ``@import`` calls, where we import things one by one, importing the ``bramble_overrides.less`` file last after all of the other files.

That's similar that what you described above, except we use one scaffold file sort of.
