### ISSUE TITLE
Remix buttom broken on bramble.mofostaging.net

### ISSUE THREAD

**Issue by ZenanZha** [mozilla/thimble.mozilla.org#2012]
I tried to remix the project on bramble but it failed:
![step1](https://cloud.githubusercontent.com/assets/22037167/25257029/181002be-2603-11e7-9ead-ff98029e3e8d.gif)
Then I type the project's url, and the project is there:
![step2](https://cloud.githubusercontent.com/assets/22037167/25257058/56f587d8-2603-11e7-957a-94fff902c3ec.gif)
When I click on remix button, it works:
![step3](https://cloud.githubusercontent.com/assets/22037167/25257067/6a5462ae-2603-11e7-8bd4-d05a8698340b.gif)

Should we change the url from:
https://thimbleprojects.org/mozillalearning/???/remix
back to:
https://thimble.mozilla.org/en-US/projects/???/remix

**Comment by ZenanZha** [comment]
@humphd

**Comment by ZenanZha** [comment]
I just found out that the remix button under the 404 page will work:
![step4](https://cloud.githubusercontent.com/assets/22037167/25257221/75f0b5d0-2604-11e7-96a0-559f34e928e6.gif)

This interesting issue works for every project.

**Comment by gideonthomas** [comment]
Nice catch @ZenanZha!

The issue is here:
 https://github.com/mozilla/thimble.mozilla.org/blob/master/public/homepage/scripts/gallery.js#L191-L196. The activity url uses `thimbleprojects.org/<username>/<id>`. The remix url is actually `thimble.mozilla.org/projects/<id>/remix` and it uses the same id from the activity url.

**Comment by ZenanZha** [comment]
@gideonthomas Which one is the right one we need to use?
I remember the thimbleprojects' link was working well two weeks ago.

**Comment by ZenanZha** [comment]
@gideonthomas 
I saw the file: [activities.json](https://mozilla.github.io/thimble-homepage-gallery/activities.json) in https://github.com/mozilla/thimble.mozilla.org/blob/master/public/homepage/scripts/gallery.js#L19.
Should we hard code in that file to make this working? Or we could do [this](https://github.com/mozilla/thimble.mozilla.org/pull/2027).

**Comment by ZenanZha** [comment]
This is another issue that we have in [activities.json](https://mozilla.github.io/thimble-homepage-gallery/activities.json). @flukeout 
Any suggestion?
