### ISSUE TITLE
publish dialog is missing a protocol for local dev

### ISSUE THREAD

**Issue by Pomax** [mozilla/thimble.mozilla.org#2014]
![image](https://cloud.githubusercontent.com/assets/177243/25258715/1b28cb00-25f6-11e7-990b-a3ced419131e.png)

MS Edge does not like that `localhost` without an `http://` in front of it: instead it goes "you need a different app to open this URI"

**Comment by bkim49** [comment]
Hello @Pomax, I am looking into this right now. What I found is that the link to localhost is generated into href="test" [here](https://github.com/mozilla/thimble.mozilla.org/blob/21545ddd9fb513dbf61a327c7a35bb6de7247e5c/views/editor/publish.html#L21). I was searching through thimble repository for the keyword "test" and I am having difficult time finding the right location. I am assuming that it is generated by the server. Could you point me to right direction for this issue? Thank you.

**Comment by gideonthomas** [comment]
@bkim49 it's in the client. Here's where you need to make the change: https://github.com/mozilla/thimble.mozilla.org/blob/master/public/editor/scripts/editor/js/fc/publisher.js#L275-L277

**Comment by bkim49** [comment]
Okay, So I just looked at the code. The link generated shows up as this right now: 
![image](https://cloud.githubusercontent.com/assets/17182037/25301885/8c0b51c6-26ff-11e7-8492-10b5cc81d35b.png)

But once I update it, the link generated is like this: 
![image](https://cloud.githubusercontent.com/assets/17182037/25301900/d436ce76-26ff-11e7-8e46-64f301cca764.png)

This is what is generated now: 
![image](https://cloud.githubusercontent.com/assets/17182037/25301920/2a8789f0-2700-11e7-9a30-499367409036.png)

Is this what you wanted? Also, I added "https://" to the href as well. But when the project is published as https://localhost:3500~, the page does not load. 
![image](https://cloud.githubusercontent.com/assets/17182037/25301957/e4d610b0-2700-11e7-9fef-43def503b354.png)

When I remove the https:// from the link, the published page still does not load. 

@Pomax @gideonthomas

**Comment by Rajat-dhyani** [comment]
hey @bkim49  you probably need to replace `https://` with `http://` and it will work.

**Comment by flukeout** [comment]
For me it depends on the browser...

* In Chrome ``http://localhost:8001/flukeout/36`` doesn't work, but if I add a ``/`` at the end it does
* In Firefox ``http://localhost:8001/flukeout/36`` works fine.

@bkim49 Maybe we just need to add a ``/`` - doesn't seem the ``http`` matters.

**Comment by gideonthomas** [comment]
The PR is here: https://github.com/mozilla/thimble.mozilla.org/pull/2029
