### ISSUE TITLE
Update welcome Email when creating a new account.

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.mozilla.org#2021]
I've restyled our sing up / create account page in ``id.webmaker.org`` here:
https://github.com/mozilla/id.webmaker.org/pull/432

In addition, we'll want to update the welcome email that is currently being served from...
https://github.com/mozilla/webmaker-mailroom/blob/master/templates/user_created/index.html

However, since this email is a generic email for accounts created from a few different potential spots, we'll need to account for that fact by either:

* Making the copy very generic "welcome to a mozilla tool" etc., or...
* Calling out some specific services that the user may have started the process from with content for each of those things...
  * We could maybe do a generic welcome and then have a small Thimble section below
  * **Here for Thimble** - here's some content & links to get you started.

I like that second approach, myself.

**Comment by flukeout** [comment]
Working on copy for the email here:
https://docs.google.com/document/d/1OSe6cJwZWGDd04jx6ndTZk_VhC03-WnaqMW5w6YJTbg/edit

Also, for later reference, I can preview the welcome email locally...
https://github.com/mozilla/webmaker-mailroom#development

**Comment by flukeout** [comment]
Filed a PR here: https://github.com/mozilla/webmaker-mailroom/pull/57

**Comment by gideonthomas** [comment]
@flukeout are you sure we want to include "Webmaker App" in the copy? Aren't we shutting it down soon?

**Comment by flukeout** [comment]
Closing as all of the changes for this are in staging in their respective repos. We're going to push the changes live on Monday.
