### ISSUE TITLE
Teaching Kit pages have wrong titles, one of them has the wrong link

### ISSUE THREAD

**Issue by ZenanZha** [mozilla/thimble.mozilla.org#2028]
One of the teaching kit has the wrong link on bramble. (It was right on thimble.)
The last three teaching kit pages of starting kits have wrong titles:
![step1](https://cloud.githubusercontent.com/assets/22037167/25300093/d3c3428c-26d5-11e7-9f44-e9c695ae7f61.gif)

**Comment by ZenanZha** [comment]
The problem of the wrong link is in this file:
https://mozilla.github.io/thimble-homepage-gallery/activities.json

In line 30:
  "teaching_kit_url" : "https://thimbleprojects.org/mozillalearning/171/",
It should be:
  "teaching_kit_url" : "https://thimbleprojects.org/mozillalearning/32/",

I don't have the authorization to make any changes on this issue.
@flukeout @humphd @gideonthomas

**Comment by ZenanZha** [comment]
I double checked the "wrong title kits".
I found out that it is just confusing, becuase they are really loooooong.
Like: "Back-to-School Write the Web Kit | My Six-Word Summer"

**Comment by flukeout** [comment]
Thanks for catching this @ZenanZha - I've invited you as a Collaborator on that repository in case you're able to make a fix. Thanks!

**Comment by ZenanZha** [comment]
Thank you. @flukeout 
Here is my fix for this issue: [Pull1](https://github.com/mozilla/thimble-homepage-gallery/pull/1)

**Comment by ZenanZha** [comment]
Should I merge my own pull request? 
I saw that I might be able to merge a pull request on my account. @flukeout

**Comment by ZenanZha** [comment]
@humphd 
Is this a good practice for me to merge my own pull request?

**Comment by flukeout** [comment]
Hi @ZenanZha - sorry for getting back to you slowly on this one. Generally the maintainer / owner of the project will merge the Pull Request (in this case me). I'll get to it within the next day or so - I've been away traveling.

Thanks!

**Comment by humphd** [comment]
This was fixed upstream, closing.
