### ISSUE TITLE
"new projects" are made too soon - show up even if cancelled

### ISSUE THREAD

**Issue by Pomax** [mozilla/thimble.mozilla.org#2035]
If I click "new project", then hit esc because I realise that's not what I intended to do and instead go to my projects, then that new project shows up as top entry in my project list despite the fact that it was never opened in Thimble.

It might be good to make sure that new projects aren't committed to the database until after they've been loaded at least once in Thimble, since that's the point at which database storage actually starts making sense. (although even then, only after the user has made any sort of modification to the code. If they opened it and then closed Thimble again, that project should not be saved to the db)

**Comment by flukeout** [comment]
Hey this is sort of related to https://github.com/mozilla/thimble.mozilla.org/issues/1284 so I'll just close your issue and update that one.
