### ISSUE TITLE
Previewing images from js... fails?

### ISSUE THREAD

**Issue by kfrajer** [mozilla/thimble.mozilla.org#2036]
Hi 
I have the following  project:  https://thimbleprojects.org/migashi/258183/

I am new to js. I am using p5.js library on a project. I have a preload function where I load an image. Then I have a setup function that is run once followed by a draw function which runs forever.

I was loading some images using p5.js call. The images were uploaded into the project. When the project runs on preview mode, it shows "Loading..." but it never shows the image.   This only happens when working on the project and trying to load iamges using p5.js calls. However, if I load the images from the html body using the img tag, I have no problems. Notice that  if I publish the project and I copy the link into a new window, it works fine and any image loaded in js is shown with no problem. To clarify, the problem is only in the preview mode.

Something I would like to mention. In preview mode, when I check the console output, I find the following error: cnh1.jpg:1 GET https://mozillathimblelivepreview.net/bramble/production/dist/assets/cnh1.jpg 404 (Not Found)

Is this a bug?

kfrajer

**Comment by humphd** [comment]
You're encountering a current limitation in the way we do our live development server, and dynamic loading of resources via JS calls.  As luck would have it, I'm currently rewriting it in https://github.com/mozilla/brackets/pull/725, but it's going to take me a month or two to get this changed shipped.

I'll use your project as a test case for what I'm doing in that PR, and make sure that your use case works with the new code.

Sorry you're hitting this, it's our fault, not yours.  Thanks for taking the time to file this bug.

**Comment by kfrajer** [comment]
@humphd Great, thank you for your message. I look forward to the changes.

For the record, this seems to be related: https://github.com/mozilla/thimble.mozilla.org/issues/1535

kfrajer

**Comment by humphd** [comment]
This is landing today, and it fixes the case discussed here.  I'm going to close this.  It should hit production in a week or two.
