### ISSUE TITLE
Editor stuck on infinite loop.

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.mozilla.org#2039]
We have a support email from user ``ghaladronog`` and they have a project with an infinite for loop. Because there's no way to reliably disable JavaScript (the "Allow JavaScript" toggle doesn't remember it's setting) there doesn't seem to be a way to recover or work on the project.

Any suggestions @humphd @Pomax @gideonthomas ?

I think that fix for that JavaScript setting is coming in our next push, but in the meantime I can't think of anything to try.

**Comment by gideonthomas** [comment]
Hmm, I keep trying to get into a state where the project actually saves with the infinite loop and I'm not able to.

I thought that maybe they could open another project and disable javascript there and then open the project with the infinite loop. However, it seems that the allow javascript toggle is not remembered between projects on production (it works on staging).

I think the only thing we might be able to do is for us to manually download the project and pass it on to him to create a new project after removing the infinite loop in a text editor.

**Comment by flukeout** [comment]
Yeah, that's interesting that it gets saved while looping infinitely and yeah, the Allow Javascript doesn't persist but is already fixed in staging I'm pretty sure.

**Comment by flukeout** [comment]
Will close this until we run into it again.
