### ISSUE TITLE
Page Crashes When Project is Loading

### ISSUE THREAD

**Issue by dipakparmar** [mozilla/thimble.mozilla.org#2040]
The Link Of Error Page is  https://thimble.mozilla.org/en-US/anonymous/e2d30351-f43d-41ba-bf3e-73523cc8e879/33977
![2017-05-02_201350](https://cloud.githubusercontent.com/assets/24366206/25623080/f265d280-2f73-11e7-884a-1e77f0b66c35.png)

**Comment by gideonthomas** [comment]
Hi @dipakparmar can you open the developer console (here's [how you do that](https://developer.mozilla.org/en-US/docs/Tools/Web_Console/Opening_the_Web_Console)) and paste everything you see there.

**Comment by dipakparmar** [comment]
Filer error:  Object { name: "EINVAL", code: "EINVAL", errno: 18, message: "IndexedDB cannot be accessed. If pr…", stack: "e@https://mozillathimblelivepreview…" }  bramble.js:3:4004
[Bramble] Failed to load Project state, with Object { name: "EFILESYSTEMERROR", code: "EFILESYSTEMERROR", errno: 1001, message: "unknown error", stack: "e@https://mozillathimblelivepreview…" }  main.js:5:12570
[Thimble Error] Object { name: "EFILESYSTEMERROR", code: "EFILESYSTEMERROR", errno: 1001, message: "unknown error", stack: "e@https://mozillathimblelivepreview…" }  main.js:5:1754
[Bramble] Error during service worker registration: TypeError: ServiceWorker script at https://mozillathimblelivepreview.net/bramble/production/dist/bramble-sw.js for scope https://mozillathimblelivepreview.net/bramble/production/dist/ encountered an error during installation.  main.js:1:1135
[Bramble] browser filesystem inaccessible (needs to be re-formatted, or permission denied due to private browsing mode.  bramble.js:4:3478
[Bramble Error] Object { name: "EFILESYSTEMERROR", code: "EFILESYSTEMERROR", errno: 1001, message: "unknown error", stack: "e@https://mozillathimblelivepreview…" }  main.js:5:12245
[Bramble] browser filesystem inaccessible (needs to be re-formatted, or permission denied due to private browsing mode.  bramble.js:4:3478
[Bramble] browser filesystem inaccessible (needs to be re-formatted, or permission denied due to private browsing mode.  bramble.js:4:3478
[Bramble] browser filesystem inaccessible (needs to be re-formatted, or permission denied due to private browsing mode.  bramble.js:4:3478

**Comment by dipakparmar** [comment]
It is working on Chrome but not in Firefox

**Comment by gideonthomas** [comment]
@dipakparmar and you are not in private browsing mode, correct?

**Comment by dipakparmar** [comment]
I am not in private browsing mode.
Version : 53.0 Firefox Release
Platform/Os : Windows 10

**Comment by gideonthomas** [comment]
@dipakparmar, did you work on any project when that happened? i.e., if we reset it, will there be data you need that will be lost?

**Comment by dipakparmar** [comment]
@gideonthomas it is not my project , i am just remixing this project for my use.
