### ISSUE TITLE
Change "XML/SVG" option label in the editor dropdown menu.

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.mozilla.org#2042]
This setting lets you edit SVG files...

<img src="https://cloud.githubusercontent.com/assets/25212/25766985/cc68651e-31aa-11e7-8983-c92f0351c6de.png" width="350" />

The label is totally cryptic and doesn't give any indication of what it actually does. Let's change it to something like...

* ``Edit SVG images as Code``
* ``SVG Image Editing``
* ...any other ideas?

**Comment by amitsin6h** [comment]
Want to work on this bug please assign it to me

**Comment by gideonthomas** [comment]
@amitsin6h go for it!

I would vote for @flukeout's first suggestion (because it is the most descriptive), but go for what you feel makes the most sense.

**Comment by amitsin6h** [comment]
While trying to setup Postgres for development. I get error even tried to solve my self no luck.
postgres -D /usr/local/var/postgres
FATAL:  could not create lock file "/var/run/postgresql/.s.PGSQL.5432.lock": Permission denied
@gideonthomas @flukeout

**Comment by humphd** [comment]
@amitsin6h are you using Vagrant?  You should only need to `vagrant up` and it should work.  If you're doing this manually, you're asking for pain.

**Comment by amitsin6h** [comment]
running below command for publish.webmaker.org gives Error
npm run knex

Error: Knex:Error Pool2 - error: role "amitsin6h" does not exist

@flukeout @humphd

**Comment by humphd** [comment]
@amitsin6h you didn't answer my question above: are you using `vagrant up`?  If you're not, please switch to using Vagrant.

**Comment by mk779** [comment]
Hello, I'm a newbie. I'm interested in working on this bug. Can anybody help me with the process. and  
I've setup the thimble and its up and running. but when i hit the remix button on the projects ,i'm getting a "page not found error". Do i have to setup the bramble also to fix this bug ? Thanks

**Comment by humphd** [comment]
Hey @mk779, welcome to Thimble dev!  I've written a blog post on this, which might help you get stated: http://blog.humphd.org/fixing-a-bug-in-mozilla-thimble/.  Anything that differs in the README files for Thimble and Brackets should be ignored in my post (it's possible things have changed).

**Comment by mk779** [comment]
Hey @humphd Thanks for the info. I've setup my environment its up and running but when i navigate through the Remix button on the projects i'm getting an error. 
![image](https://user-images.githubusercontent.com/25910848/29468929-36d0a360-8414-11e7-94af-a7a4c805af6f.png)

Is it normal or did i do something wrong? Can you help me with this and navigate me through the pages that i've to edit. Thanks

**Comment by humphd** [comment]
@gideonthomas or @Pomax might have ideas.  I wonder if the mocked s3 stuff isn't working properly--in development we use a fake Amazon S3 API, which might not be working full there.

**Comment by mk779** [comment]
how can i fix this ? or are there any articles which can me fix this ? thanks

**Comment by gideonthomas** [comment]
Hi @mk779, just a quick clarification - are you trying to remix one of the projects on the homepage? If so, unfortunately they cannot be remixed in a local environment and hence that is the error you are seeing. If you would like to try remixing, you would need to create a project from scratch, publish it and then remix it.

**Comment by mk779** [comment]
@gideonthomas I'm trying to fix the error above , which is XML/SVG . Could you suggest me how can i get it done? thanks.

**Comment by gideonthomas** [comment]
You need to update the string for this option. To do that, remove this line: https://github.com/mozilla/thimble.mozilla.org/blob/master/locales/en-US/server.properties#L81, and replace it with another key/value pair (use a different key name) with the value being one of the choices that @flukeout provides in his comment above. Then, change https://github.com/mozilla/thimble.mozilla.org/blob/master/views/editor/nav-options.html#L172 to use the new key that you created. Restart Thimble and start a new project and then verify that the text has successfully been changed to the new value.

Since this involves a localization change, it might be useful for you to read through https://github.com/mozilla/thimble.mozilla.org/wiki/Localization#server-side-localization to understand how to make the change you need to make.

**Comment by apoorvasingh17** [comment]
Hi, can I take this up?

**Comment by ayush9398** [comment]
Can I take this issue...? I have already set up Thimble on my local machine and have successfully changed the key value pair in the editor on my localhost.
![change_success](https://user-images.githubusercontent.com/21312552/30127640-9f8d2858-935d-11e7-9dd4-76e8d2e1dece.png)
