### ISSUE TITLE
[dev] Unable to upload image files to project.

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.mozilla.org#2043]
@humphd @gideonthomas can you guys try to see if it works locally for you?

I can't drag files in, nor upload them via the "Upload file" dialog. Getting this error...

![image](https://cloud.githubusercontent.com/assets/25212/25827440/1e655a5a-3400-11e7-8ef7-802f0b9fde13.png)

**Comment by humphd** [comment]
Which browser?

**Comment by humphd** [comment]
Also, can you send me the file you're using that it's rejecting?  I'll test locally.

**Comment by flukeout** [comment]
Chrome and it seems like literally any image file.

**Comment by flukeout** [comment]
![cat-1](https://cloud.githubusercontent.com/assets/25212/25827504/643f201a-3400-11e7-91b8-28e6710920bc.jpg)

This one doesn't work, and is pretty cute so there's that ^

**Comment by humphd** [comment]
I have no issue getting this to work on latest `master`.  What else could be happening here?  Which commit are you on?

**Comment by humphd** [comment]
I'm on e0747c612fc062932f849d998888119ad5a8d025 and every way I try to do this (drag-and-drop to file tree, Upload dialog drag-and-drop, Upload dialog From Computer...) all work.

**Comment by flukeout** [comment]
Okay, thanks for checking. I'll see if I can provide any additional detail.

**Comment by flukeout** [comment]
@humphd I'm running latest master on brackets, just hitting it directly via ``http://localhost:8000/src/hosted``. I get this error in both Firefox and Chrome when I try to drag something in. Can you try latest master?

**Comment by flukeout** [comment]
I get no console errors when it fails, although the console has this after the editor loads

![image](https://cloud.githubusercontent.com/assets/25212/25828306/5a081832-3404-11e7-8496-c2390996ad1f.png)

**Comment by gideonthomas** [comment]
@flukeout `npm run build && npm start` try that

**Comment by flukeout** [comment]
@gideonthomas COME ON MAN what do you take me for over here

**Comment by flukeout** [comment]
That is to say, I tried that and it didn't work. Can you try it locally and let me know? I think I noticed this a few days ago, but it's only become urgent now.

**Comment by humphd** [comment]
I'm able to reproduce this on staging, so maybe it's something that's happening with the built code vs. what's in src:

![screen shot 2017-05-08 at 9 12 21 pm](https://cloud.githubusercontent.com/assets/427398/25831571/1dd563fe-3433-11e7-8d39-588f6ccb9462.png)

I'll debug.  Thanks for filing.

**Comment by humphd** [comment]
Refreshing on staging (with dev tools open) fixed it for me.  I wonder if it's a service worker cache issue?

**Comment by humphd** [comment]
I think this is somehow a Thimble-uses-the-wrong-Brackets-version-due-to-Service-Worker-Cache bug.  We haven't solved this yet, and I think it's going to continue to bite us.

The easiest thing we could do for Launch is to finish the "Updates are available, click refresh" UI to let users know that a refresh might fix things.

**Comment by humphd** [comment]
The update UI bit is in https://github.com/mozilla/thimble.mozilla.org/issues/1930.

**Comment by flukeout** [comment]
@humphd What's the method for resolving this locally?

**Comment by gideonthomas** [comment]
I too think this is an SW issue because I was only able to trigger this on staging BUT after I repeatedly dragged and dropped the image into the editor, it eventually worked.

@flukeout locally, open your dev tools on Chrome, click on the "application" tab, select "Clear Storage" and make sure everything is checked and then click "Clear site data"
