### ISSUE TITLE
Do the right thing when users access Project List without proper tokens

### ISSUE THREAD

**Issue by humphd** [mozilla/thimble.mozilla.org#2049]
@flukeout is reporting that many users are hitting an issue while trying to access their Project List page, and then being redirected to the homepage.  We think this is cache related, and perhaps most affecting people on shared machines/accounts.

@gideonthomas suggests that we could make sure that we don't cache the project-list page when we send it, or perhaps we should be clearing the expired tokens/cookies when this happens?

Assigning to @gideonthomas for further work.  I'll put this in Launch, but we can move it out if it's not doable, since this isn't a regression.

**Comment by ThatGirl2015** [comment]
If I could chime in -- I teach high school computer science and have been using Thimble for the past two weeks or so and we have been experiencing this exact issue. Additionally, sometimes the project they have been working on does not show up at all in the project list. Or a project they worked on at home does not show up in the project list on the school's PCs. My students are all on shared PCs at school with individual login accounts.

**Comment by humphd** [comment]
@ThatGirl2015 sorry to hear your students are hitting this.  Glad to have you engaged in this bug so we can ask questions as we try to sort this out.  It's hard to reproduce (for us), so valuable to have insights from someone experiencing it.  I'll raise this on our team call today, and hopefully we can get a fix shipped soon.

**Comment by ThatGirl2015** [comment]
I'm happy to help.

**Comment by gideonthomas** [comment]
Hi @ThatGirl2015, does this happen on Firefox or Chrome?

**Comment by ThatGirl2015** [comment]
Chrome

**Comment by humphd** [comment]
After discussion and debugging we think the following is needed:

* Let's not do a `301` [here](https://github.com/mozilla/thimble.mozilla.org/blob/fa3dde088dc016a562520e62a9df1f5558ba8f70/server/lib/middleware.js#L61), let's render an error page instead.  The error page should indicate that an affected user should sign-out and sign-in again.
* Let's set a `no-cache` header on what we return here.

@gideonthomas will do the server code changes, @flukeout will do the error page.
