### ISSUE TITLE
Console icons not loading on staging

### ISSUE THREAD

**Issue by humphd** [mozilla/thimble.mozilla.org#2057]
Fall out from https://github.com/mozilla/brackets/pull/753:

![screen shot 2017-05-10 at 7 48 06 pm](https://cloud.githubusercontent.com/assets/427398/25925955/f3fceae2-35b9-11e7-97b4-f26581718b57.png)

We must not be copying them, or including in SW cache somehow. cc @raygervais

**Comment by humphd** [comment]
This works locally, so I'd say our problem is that it's hard-coding `src/` in the path here:

```
src/extensions/default/bramble/stylesheets/consoleTheme.less:    background-image: url(/src/styles/images/icons/console-icon-dark.svg);
src/extensions/default/bramble/stylesheets/consoleTheme.less:    background-image: url(/src/styles/images/icons/console-icon-light.svg);
src/extensions/default/bramble/stylesheets/consoleTheme.less:    background-image: url(/src/styles/images/icons/console-icon-light.svg);
```

**Comment by flukeout** [comment]
Ok, I'll get on this.

**Comment by humphd** [comment]
I've also noticed we have string issues, which I've fixed in https://github.com/mozilla/thimble.mozilla.org/pull/2058

**Comment by humphd** [comment]
NOTE: https://github.com/mozilla/brackets/pull/759 fixes this bug.

**Comment by flukeout** [comment]
Oh okay, I'll test that.

**Comment by humphd** [comment]
This was merged.
