### ISSUE TITLE
Trying to open a Remix on Staging gives a 500

### ISSUE THREAD

**Issue by humphd** [mozilla/thimble.mozilla.org#2065]
![screen shot 2017-05-11 at 3 28 53 pm](https://cloud.githubusercontent.com/assets/427398/25968186/9a671f2a-365e-11e7-9713-10f1ee416f14.png)

I made a new account to get around #2064, and was able to click Publish.  My project got published to https://thimbleprojects.mofostaging.net/david-humphrey/140/.  When I click Remix, it gives a 500.

cc @cadecairos, @gideonthomas

**Comment by gideonthomas** [comment]
Is this from the homepage? If so, that is expected @humphd. You cannot remix any of the projects on the homepage because they only live on production.

**Comment by humphd** [comment]
No, see my note above: this is a project I made myself and published on staging.

**Comment by cadecairos** [comment]
Clicking the remix button on that project seems to work okay - maybe it was a blip in the system?

**Comment by humphd** [comment]
Closing, will re-file if I keep seeing it.
