### ISSUE TITLE
Raise the minimum dyno count in Adept Scale (For launch week)

### ISSUE THREAD

**Issue by cadecairos** [mozilla/thimble.mozilla.org#2069]
In anticipation of high traffic, we're going to raise the minimum dyno count.

I propose setting it to 10 for the launch day, and allow scaling out to 40

What's our target launch day?

**Comment by humphd** [comment]
Be generous with what you do here, and turn it down after.  It's basically "Marketing" vs. "DevOps" cost for the short period we want it to be scaled up.

**Comment by cadecairos** [comment]
So, in the interest of being absolutely sure we'll handle load, I'll scale us all the way up to a minimum 30 Dynos for the first couple days after launch, and even allow for more dynos if required.

**Comment by cadecairos** [comment]
I've applied the following scale settings to our Thimble-related Heroku applications:

### bramble-production
Min dynos: 30
Max dynos: 75

### publish-webmaker-org-production
Min dynos: 30
Max dynos: 75

### id-webmaker-org-production
Min dynos: 30
Max dynos: 75

### wmlogin-production
Min dynos: 30
Max dynos: 75

**Comment by flukeout** [comment]
Hey an update @cadecairos - we've pushed back the launch to this coming Tuesday after the long weekend.

**Comment by cadecairos** [comment]
How early? Should I scale us up on Friday?

**Comment by humphd** [comment]
Probably we can scale back to normal now and close this?  @cadecairos

**Comment by cadecairos** [comment]
OK, I'll check the traffic levels once more and scale down

**Comment by flukeout** [comment]
Yeah, throw a graph in here if you can, curious how some of our social media exposure affected our traffic. Looking at analytics yesterday, it didn't really look out of the ordinary.

**Comment by cadecairos** [comment]
I'm seeing only minor or negligible impacts to traffic based on the last seven days. I'll lower the minimums to two dynos and leave room for plenty of scaling still.

wmlogin-production: 
![image](https://cloud.githubusercontent.com/assets/438003/26419502/f4d50bc8-408d-11e7-8c8d-279c1af37621.png)

bramble-production:
![image](https://cloud.githubusercontent.com/assets/438003/26419600/3aba8b86-408e-11e7-9674-952f5901daec.png)

publish-webmaker-org-production:
![image](https://cloud.githubusercontent.com/assets/438003/26419694/86b419da-408e-11e7-9f3d-5a4864683f01.png)

id-webmaker-org-production:
![image](https://cloud.githubusercontent.com/assets/438003/26419844/f3a63ca8-408e-11e7-8b66-5a8477a6339f.png)

**Comment by cadecairos** [comment]
autoscaling settings are now set back to normal values.
