### ISSUE TITLE
Make it possible to add a new Folder from the File Tree page icon 

### ISSUE THREAD

**Issue by humphd** [mozilla/thimble.mozilla.org#2072]
Via Twitter, a request to add the ability to create new Folders in addition to files from the File Tree page icon.  I'll add a patch to Brackets to make this possible, then do the UI here.

**Comment by flukeout** [comment]
+1 to this

**Comment by humphd** [comment]
It turns out we already have the API in place for this, we just need a new menu item and it will work.  Pretty easy fix.

**Comment by humphd** [comment]
We need to prod push both Brackets (first) and Thimble (second) to get this feature shipped.
