### ISSUE TITLE
[Microsoft Edge] Hovering the Inspector shows no icon

### ISSUE THREAD

**Issue by humphd** [mozilla/thimble.mozilla.org#2074]
![img_20170512_105656](https://cloud.githubusercontent.com/assets/427398/26003907/06fb6256-3702-11e7-8e43-a8cddfe3cf6e.jpg)

Noticing that when I hover the Inspector icon in MS Edge, it goes pure white.  It looks like this in Chrome:

![screen shot 2017-05-12 at 10 59 34 am](https://cloud.githubusercontent.com/assets/427398/26003937/1f623dce-3702-11e7-8ad8-c4fdc4316a5a.png)

**Comment by flukeout** [comment]
Are you able to inspect it at all in edge to see what might be wrong?

**Comment by humphd** [comment]
I can't reproduce this now, in IE11 or Edge.  No idea what happened, but I'll re-file if I see it again.
