### ISSUE TITLE
Console icon disappears when switching from Mobile to Desktop preview mode

### ISSUE THREAD

**Issue by humphd** [mozilla/thimble.mozilla.org#2077]
![missing-console-icon](https://cloud.githubusercontent.com/assets/427398/26004436/e17f5b66-3703-11e7-8717-5a3729222a57.gif)

We're not doing something right when we switch back to Desktop mode from Mobile.  Probably we need to alter where we are putting the console icon, so it doesn't get hidden/destroyed/overwritten.

cc @raygervais

**Comment by raygervais** [comment]
Perhaps put the icon in the toolbar above the preview? Just a thought.

**Comment by humphd** [comment]
I think it's good where it is, but just not where it is in the DOM order.  I'll fix it today when I get a min.

**Comment by humphd** [comment]
I've got a fix in https://github.com/mozilla/brackets/pull/761 waiting on review.
