### ISSUE TITLE
New default HTML doesn't match HTML file we add from Files icon

### ISSUE THREAD

**Issue by humphd** [mozilla/thimble.mozilla.org#2078]
![different-html](https://cloud.githubusercontent.com/assets/427398/26004808/0b027d00-3705-11e7-8b78-b6de649e5fe7.gif)

We changed the default HTML and CSS in https://github.com/mozilla/thimble.mozilla.org/commit/4b241cdbc69ca69e73fbe8700433d632a9c02520 but didn't update the ones we inject when you click `Add HTML file` and `Add CSS file`.  Probably they should match.

**Comment by flukeout** [comment]
👍
