### ISSUE TITLE
Mobile Preview "Home" button no longer centered

### ISSUE THREAD

**Issue by humphd** [mozilla/thimble.mozilla.org#2081]
![screen shot 2017-05-12 at 12 51 19 pm](https://cloud.githubusercontent.com/assets/427398/26008215/d2fa3af8-3711-11e7-9720-6ee6615b8516.png)

Somehow we've messed up the position of the "home" button on the mobile preview wrapper, it's not in the centre any more.

**Comment by flukeout** [comment]
I got it...
