### ISSUE TITLE
Missing icons in new homepage

### ISSUE THREAD

**Issue by humphd** [mozilla/thimble.mozilla.org#2082]
![screen shot 2017-05-12 at 1 43 42 pm](https://cloud.githubusercontent.com/assets/427398/26010020/420427d6-3719-11e7-8dd3-e8e77102665b.png)

Seem to be missing some images:

![screen shot 2017-05-12 at 1 44 31 pm](https://cloud.githubusercontent.com/assets/427398/26010029/49bb15de-3719-11e7-866e-50bebd43baf6.png)

**Comment by flukeout** [comment]
Fixed in a merged PR.
