### ISSUE TITLE
[MS Edge, IE11] Odd sizing issue with mozilla logo in homepage footer

### ISSUE THREAD

**Issue by humphd** [mozilla/thimble.mozilla.org#2083]
![img_20170512_134908](https://cloud.githubusercontent.com/assets/427398/26010205/0762340a-371a-11e7-98fd-1012602dc001.jpg)

cc @flukeout

**Comment by humphd** [comment]
Looks the same in IE11

**Comment by humphd** [comment]
This one looks like in IE the `img` element has a height of `28px` in Chrome (looks right) and `50px` in IE.  I think we need an explicit height for the CSS on this element so Edge/IE don't inherit it (no idea where it's coming from).

**Comment by humphd** [comment]
@flukeout I'm moving this into Launch, since it affects branding, and seems pretty bad on that front.  Can you do some CSS on this image?

**Comment by flukeout** [comment]
No, closed by accident.
