### ISSUE TITLE
Play/Pause videos in Features page on scroll for better performance

### ISSUE THREAD

**Issue by humphd** [mozilla/thimble.mozilla.org#2084]
The new Cool Features page (see https://bramble.mofostaging.net/en-US/features) is awesome, and does a good job showing how things work, while still keeping download sizes small.  I've tested it on a bunch of machines/browsers/OSes, and especially on Edge, I notice lag in the framerates.  We have a lot of videos (and therefore media threads) running on this page, even when the `video` elements are visible in the viewport.

Let's see if we can add code to call `play()` and `pause()` when the videos scroll into/out-of view, so they don't run all the time.

**Comment by flukeout** [comment]
Another option would be to play them on hover.

**Comment by Rajat-dhyani** [comment]
can i take this over ? @humphd @flukeout 
and i do like like the idea of playing them on hover instead of making a play and pause button.

**Comment by humphd** [comment]
I think we should play on hover, yes.  @Rajat-dhyani if you want to do this, go for it.

**Comment by Rajat-dhyani** [comment]
Okay thanks @humphd ,
i just added the controls for play and pause.
Filled a PR for the same. We can add both the features if you want. Can you tell me where to add the script for the hover over feature cause when i add the script in same page it throws bunch of errors that: "i can't put my script in the same page". Should i create a new `feature.js` file like we have `getInvoled.js `

`var feature = $(".feature");`

`feature.addEventListener("mouse-enter", function(){
   this.firstchild.play();
});`
`feature.addEventListener("mouse-leave", function(){
      		this.firstchild.pause();
});`

**Comment by yaroslavromanyuk** [comment]
I think that we could solve this problem differently.
You can use JS to make play only those videos that are visible on the screen . We can dynamically catch the window scrolling event and call the play() on those videos that are currently visible and the corresponding pauses() on those videos that are not visible. Thus, the CPU will only be loaded with those videos that are visible for user. What do you think about it?

**Comment by yaroslavromanyuk** [comment]
If you are willing to wait a few days, I can make an implementation of this approach.

**Comment by flukeout** [comment]
Hey @yaroslavromanyuk - that sounds pretty good, but we've already gone down the other road pretty far. We are just finishing up a PR here - https://github.com/mozilla/thimble.mozilla.org/pull/2197

This one plays and pauses the videos based on hovering over them (or touch for touch-enabled de ices)
