### ISSUE TITLE
Provide hint in empty Console on how to use it

### ISSUE THREAD

**Issue by humphd** [mozilla/thimble.mozilla.org#2091]
![screen shot 2017-05-12 at 4 36 53 pm](https://cloud.githubusercontent.com/assets/427398/26016002/47848fc6-3731-11e7-91bd-a9a170cfa612.png)

If you don't know what the new console is, or how to use it, it might seem odd.  We should consider adding a line of text by default when it opens and has no ideas that says something like:

```
TIP: You can use console.log("message"); in your JavaScript to print log messages here.
```

**Comment by flukeout** [comment]
Great idea, I'll add something.
