### ISSUE TITLE
Localized feature page layout issue

### ISSUE THREAD

**Issue by TheoChevalier** [mozilla/thimble.mozilla.org#2098]
The issue can be seen here, the “Built-in JavaScript Console” block is going on a new line: https://bramble.mofostaging.net/fr/features

![screenshot-2017-5-15 thimble par mozilla un editeur de code en ligne pour apprendre et enseigner](https://cloud.githubusercontent.com/assets/1294206/26042143/a9a6d0b0-392a-11e7-8435-21d88e9415fb.png)

**Comment by humphd** [comment]
cc @flukeout

**Comment by flukeout** [comment]
Thanks for catching that @TheoChevalier, will work on it now.
