### ISSUE TITLE
QA > Create account button becomes unusable after failed password validation

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.mozilla.org#2108]
On Firefox on Mac, I'm stuck on this page...

![image](https://cloud.githubusercontent.com/assets/25212/26071968/c7ac250e-395e-11e7-9018-0827e38617f3.png)

This happens after you try a non-valid password (one without an uppercase character or number). After that, even if you provide a good password, the button does not re-enable.

cc @Pomax could you take a look at this one as we were both involved in these changes?

**Comment by humphd** [comment]
Do you get a `404` on your console?  This is similar to what I had on my local machine before.

**Comment by flukeout** [comment]
The disabled button issue seems linked with the password not having a number:

![image](https://cloud.githubusercontent.com/assets/25212/26072195/93a5bb84-395f-11e7-807d-d129d99d5d63.png)

**Comment by flukeout** [comment]
@humphd that might be a different issue. I get a 404 if I just try a username and nothing else. Will file separately.

**Comment by gideonthomas** [comment]
cc @cadecairos

**Comment by flukeout** [comment]
This is related to a change @Pomax and I made, I think we just have to listen to some additional events to re-enable the button.

**Comment by Pomax** [comment]
hmm, is that not triggering from a `FORM_WARN` maybe?

**Comment by Pomax** [comment]
I'm seeing this go wrong as:
```
Uncaught Error: Invariant Violation: Dispatch.dispatch(...): Cannot dispatch in the middle of a dispatch.
    at invariant (invariant.js?7626:42)
    at Dispatcher.dispatch (Dispatcher.js?03ea:185)
    at Object.displayError (webmaker-actions.jsx?9344:12)
    at Constructor.validatePassword (api.jsx?4b31:102)
    at Constructor.handleFormData (signup.jsx?0581:133)
    at Object.EventEmitter.emit (events.js?7c71:81)
    at Object.emitEvent (webmaker-actions.jsx?9344:42)
    at Object.ID_1 (webmaker-actions.jsx?9344:53)
    at Dispatcher.$Dispatcher_invokeCallback (Dispatcher.js?03ea:220)
    at Dispatcher.dispatch (Dispatcher.js?03ea:195)
```

**Comment by Pomax** [comment]
this triggers when `FORM_ERROR` is being generated

**Comment by Pomax** [comment]
https://github.com/mozilla/id.webmaker.org/pull/437 filed to add dispatch protection in case the dispatcher is still working through an existing action.

**Comment by flukeout** [comment]
This is addressed in https://github.com/mozilla/id.webmaker.org/pull/437
