### ISSUE TITLE
QA > Text in input field when renaming a file is clipped.

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.mozilla.org#2111]
In Firefox on Mac, rename a file, it will appear like this...

![image](https://cloud.githubusercontent.com/assets/25212/26073735/82fba5fa-3964-11e7-8f5f-b25b04f0d0c1.png)

**Comment by gideonthomas** [comment]
This only happens in Firefox (possibly only on Mac).

**Comment by amehic** [comment]
Hi @flukeout, I'm a student learning open source and I was wondering if I could try this one.

**Comment by flukeout** [comment]
Hey @amehic - sounds good. Please check first if you can reproduce it, as it might not be happening on all OS / browser combinations. Thanks!

**Comment by amehic** [comment]
@flukeout Thanks, I was able to reproduce it in Firefox on Windows as well.

**Comment by flukeout** [comment]
Great, let me know if you have questions about where to get started with this. A good first step is getting your local environment up and running. I believe that with this bug you'll only need to run Brackets itself.
