### ISSUE TITLE
[MS Edge] Selfie preview image skewed

### ISSUE THREAD

**Issue by humphd** [mozilla/thimble.mozilla.org#2113]
Similar to the issue with the height not being correct on the Mozilla logo in https://github.com/mozilla/thimble.mozilla.org/pull/2105, I'm noticing image skew in the preview image in the selfie uploader:

![img_20170515_144916](https://cloud.githubusercontent.com/assets/427398/26074030/725cf25c-397e-11e7-9e57-55138abb4346.jpg)

**Comment by Vasusena** [comment]
Greetings, I'm a student at Seneca college learning open source, and I was hoping to work on this bug for my course.  If no one else is currently working on it, I'd like to give it a try.

**Comment by humphd** [comment]
@Vasusena it's yours.  Take a look at how a similar bug was fixed here https://github.com/mozilla/thimble.mozilla.org/pull/2105/files.

**Comment by humphd** [comment]
Some more tips on this.  The code you need to fix is located in the Brackets repo, and specifically, in this extension: https://github.com/mozilla/brackets/tree/master/src/extensions/default/BrambleUrlCodeHints.  Take a look at https://github.com/mozilla/brackets/blob/master/src/extensions/default/BrambleUrlCodeHints/style.less.

**Comment by Vasusena** [comment]
Thank you, i will look at the documentation and setup the build environment accordingly.

**Comment by bansalnitish** [comment]
@humphd it seems no one is working on this issue now. May I work on this !

**Comment by Vasusena** [comment]
Hey bansalnitish, I am sorry I haven't been active for a while but I am about to finish this issue, I just need to finish up and send a pulll request
