### ISSUE TITLE
Feature request > After inserting a snippet, focus the Editor again.

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.mozilla.org#2114]
Right now if you add a code snippet via the menu, the editor becomes blurred so you need to click it again to start typing. Can we focus it and put the cursor after the inserted snippet?

**Comment by humphd** [comment]
This would need to happen in Brackets, here: https://github.com/mozilla/brackets/blob/master/src/extensions/default/bramble/lib/BrambleCodeSnippets.js

**Comment by pranay414** [comment]
Can I work on this @flukeout @humphd ?

**Comment by humphd** [comment]
Sure @pranay414, go for it.  Here's an example of how you focus an editor in Brackets:

https://github.com/mozilla/brackets/blob/master/src/extensions/default/bramble/lib/RemoteCommandHandler.js#L50-L54

**Comment by pranay414** [comment]
@humphd where is the menu to add code snippet. I was not able to find it on thimble?

**Comment by humphd** [comment]
Here's an easier way to test this, @pranay414, which doesn't involve Thimble at all.

* Run Brackets on its own, and load `http://localhost:8000/src/hosted.html
* Open your Dev Tools Web Console
* Type `bramble.addCodeSnippet("test snippet");`

![snippet-console](https://cloud.githubusercontent.com/assets/427398/26111531/598e3650-3a23-11e7-992d-d1ba078a267d.gif)

Using this method, you can ignore Thimble completely.  The fix you need to make won't involve it at all.

**Comment by pranay414** [comment]
Got it, thanks @humphd

**Comment by flukeout** [comment]
Hi @pranay414 - I've unassigned this issue because it looks like you have stopped working on it. If you're still going to work on it, please let us know. Thanks!

**Comment by pranay414** [comment]
@flukeout I have stopped working on this issue. Sorry for informing you late.

**Comment by Cryzek** [comment]
Hi, I wanted to work on this as my first issue in thimble.
But, when I tried this out in thimble , I noticed that the cursor was automatically inserted after the code snippet. So, I'm just wondering if this is still/should be an open issue.

**Comment by gideonthomas** [comment]
Yeah I'm not able to reproduce this anymore (Chrome 60). @flukeout which browser is this happening in?

**Comment by flukeout** [comment]
Checking now.

**Comment by flukeout** [comment]
Yeah, I'm not seeing this anymore. The editor retains focus after adding a snippet so the user can keep typing. Closing!
