### ISSUE TITLE
QA > File menu doesn't close after clicking "Download Files"

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.mozilla.org#2115]
On Mac Firefox, this here menu stays open after clicking download project.

![image](https://cloud.githubusercontent.com/assets/25212/26074223/d3ad8e4a-3965-11e7-8f72-9ac3da3ca792.png)

**Comment by humphd** [comment]
Same on all browsers.

This code [here](https://github.com/mozilla/thimble.mozilla.org/blob/aa63cc848be71a4f442f3d74324ce7a7e128760f/public/editor/scripts/editor/js/fc/bramble-ui-bridge.js#L163-L167) should get moved into [this function](https://github.com/mozilla/thimble.mozilla.org/blob/f71e848f83205ec8d98cd88293f224308dfde42e/public/editor/scripts/editor/js/fc/bramble-menus.js#L312) and call `menu.close()` in the callback to `bramble.export()`.
