### ISSUE TITLE
Feature Request > Indicate font size next to font size UI

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.mozilla.org#2118]
For this option...

![image](https://cloud.githubusercontent.com/assets/25212/26074588/30848a14-3967-11e7-9c0e-4f2dd6d02eee.png)

Would be nice to indicate the actual font size you're setting (or percentage), so that you can set it to something you like (and remember) more easily.

**Comment by flukeout** [comment]
We could simply add the font size next to the text label like this...

* ``Text size (12px)``

**Comment by humphd** [comment]
I've got a student, Azusa Shimazaki @azusaaz, who wants to work on this.  I'm assigning it to her now.

**Comment by azusaaz** [comment]
Hello, I am that student Azusa Shimazaki @azusaaz!
Thank you for assigning!
I am excited to try this!

**Comment by humphd** [comment]
A few tips on how to do this:

The HTML for this lives here: https://github.com/mozilla/thimble.mozilla.org/blob/9e6289cb54f60fe770f4744885d8ae5673b1e9fd/views/editor/nav-options.html#L117-L120.  You'll need to add a `<span id="editor-pane-nav-font-size"></span>` to create the UI.

Next, we'll need some code to get the current font size on startup, and put it in that UI.  That code can go here: https://github.com/mozilla/thimble.mozilla.org/blob/ea243750e1a09e850ddc07a31fcafc9660780b1c/public/editor/scripts/ui/menus.js#L129-L150.  You can get the current font size with `bramble.getFontSize();`, see https://github.com/mozilla/brackets#bramble-instance-getters.

Finally, we'll need an event handler to deal with the case of the font size changing at runtime (e.g., the user adjusting the font size), and then update the UI with the new size.  You'll have to deal with the `bramble` event `fontSizeChange`, see https://github.com/mozilla/brackets#bramble-instance-events.

I'm not sure if we need to localize `px` or if that's fine in all languages.  @TheoChevalier what does one usually do with `12px` in non-English?

**Comment by azusaaz** [comment]
@humphd Ok. Thank you so much for the tips!

**Comment by TheoChevalier** [comment]
> I'm not sure if we need to localize px or if that's fine in all languages. @TheoChevalier what does one usually do with 12px in non-English?

Generally speaking, all units should be localized. For instance, some locales will order the unit and value differently, add spaces or non-breaking spaces between the two, change capitalization, or even translate the unit, etc.

To give you an idea for the `px` unit: https://transvision.mozfr.org/string/?entity=browser/chrome/browser/pageInfo.properties:mediaDimensions&repo=central

In your case, the string could be similar to this: `Text size ({{fontSize}}px)`

**Comment by TheoChevalier** [comment]
> we can just use the value passed back from the function calls themselves.

Not sure to understand, what would the string look like?

**Comment by humphd** [comment]
`12px`

**Comment by TheoChevalier** [comment]
I will leave the decision to you, but since you’re asking me, leaving `12px` unlocalized won’t work for several languages.

Taking another example from Thimble, look at the `LOCALES` tab: https://pontoon.mozilla.org/en-GB/thimble/all-resources/?search=px&string=165701
There’s a bunch of languages using something different than `number+px`.

**Comment by azusaaz** [comment]
@TheoChevalier  Thank you for the info!

**Comment by gideonthomas** [comment]
@humphd yeah let's not add the l10n  part for this specific contribution. @azusaaz, you can just use the values as is as @humphd mentions. @humphd, can you file a follow-up to localize it and assign to me please?

**Comment by Pomax** [comment]
@flukeout pixel sizes don't really mean anything across devices, could I suggest we use percentage instead? (similar to how browsers themselves indicate zoom level?)

**Comment by azusaaz** [comment]
@gideonthomas thank you for your comment! I overlooked somehow.

**Comment by azusaaz** [comment]
Now it is like this.
<img width="502" alt="snapcrab_noname_2017-10-16_17-45-18_no-00" src="https://user-images.githubusercontent.com/22462471/31636963-9f9b431e-b29a-11e7-823d-08dfcfdd16dc.png">

**Comment by azusaaz** [comment]
@TheoChevalier @Pomax
The text size is for the editor, and the most of the codes are written in English.
So, I think it is not necessary to care about language and device in this case.

ex. Japanese ver ...
<img width="591" alt="snapcrab_noname_2017-10-16_17-40-44_no-00" src="https://user-images.githubusercontent.com/22462471/31637006-c8ac65da-b29a-11e7-9eb6-f9ee584d68cb.png">

**Comment by humphd** [comment]
@azusaaz this is looking great.  Did you want to open a pull request with your changes, and we can discuss this further there.  One suggestion I have would be to get rid of the extra spaces between the font size and parenthesis:

```
// Yes
Text size (12px)
// No
Text size ( 12px )
```

Great job getting this started!

**Comment by flukeout** [comment]
Yeah, I agree with @humphd suggestion about removing the extra spaces, looking forward to a PR.

**Comment by azusaaz** [comment]
@humphd  @flukeout Thank you for the comment!  When I cleaned up the code, space has gone!
Now looks like this
<img width="169" alt="snapcrab_noname_2017-10-17_22-59-48_no-00" src="https://user-images.githubusercontent.com/22462471/31701282-4e425224-b39d-11e7-86fa-a742e7067935.png">

**Comment by azusaaz** [comment]
I tried to pull request, but I got check errors. Means there is the problem in my repo??

<img width="431" alt="snapcrab_noname_2017-10-17_23-35-10_no-00" src="https://user-images.githubusercontent.com/22462471/31701342-cc231b1a-b39d-11e7-910b-5c4ac4068a4a.png">

<img width="502" alt="snapcrab_noname_2017-10-17_23-36-13_no-00" src="https://user-images.githubusercontent.com/22462471/31701362-e1e1486e-b39d-11e7-9354-367429b34869.png">

**Comment by humphd** [comment]
I'll comment in your PR and help you out.

**Comment by azusaaz** [comment]
@humphd  Thank you!
