### ISSUE TITLE
QA > pretty console hint missing on staging

### ISSUE THREAD

**Issue by humphd** [mozilla/thimble.mozilla.org#2121]
In https://github.com/mozilla/brackets/pull/763 we landed some text to give a hint for the console, but it seems to be missing on staging for me:

![screen shot 2017-05-15 at 3 32 17 pm](https://cloud.githubusercontent.com/assets/427398/26075627/f3bd8f64-3983-11e7-8c31-e2feb3cff093.png)

cc @flukeout

**Comment by flukeout** [comment]
Yeah, it looks like the element is there and visible, but he localized string it not coming through.

**Comment by humphd** [comment]
Fix in https://github.com/mozilla/thimble.mozilla.org/pull/2176

**Comment by humphd** [comment]
Merged.
