### ISSUE TITLE
QA > Top nav links in Your Projects page shouldn't spawn a new tab.

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.mozilla.org#2123]
![image](https://cloud.githubusercontent.com/assets/25212/26078219/a303b5a4-3973-11e7-92b7-07438ce8edd2.png)

We should just open them in the same tab.

**Comment by Pomax** [comment]
This is caused by a `<base target="_blank">` in the head, coming from https://github.com/mozilla/thimble.mozilla.org/blob/aa63cc848be71a4f442f3d74324ce7a7e128760f/views/editor/layout.html#L13
