### ISSUE TITLE
Disallow backslash in filenames

### ISSUE THREAD

**Issue by cadecairos** [mozilla/thimble.mozilla.org#2127]
it seems that while some special characters are not allowed in filenames, you can use a backslash ('\') which doesn't initially seem to break anything, but does make the file or folder disappear when a project is exported to a zip. The resources inside are also not available to autocomplete prompts in the code editor for things like src attributes.

STR:
1. Rename a file or folder to '\\\\\\' or something
2. try to export or use the resource in the editor.

**Comment by flukeout** [comment]
Also, related https://github.com/mozilla/thimble.mozilla.org/issues/2066

**Comment by humphd** [comment]
I'm going to close this, because we have it filed in a few other places.  Thanks for reporting it, though, @cadecairos.
