### ISSUE TITLE
QA > Firefox not using 100% of screen height when in the editor.

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.mozilla.org#2128]
You can tell by looking at where the console tab starts, a few pixels above the bottom of the screen...

![image](https://cloud.githubusercontent.com/assets/25212/26082116/fa98b72e-3982-11e7-9d15-3095a30d4aef.png)

**Comment by humphd** [comment]
This is a really interesting bug.  At first I couldn't reproduce it.  I had to do a lot of messing around with my window to make it happen, but eventually it did.  Here is what I see:

![screen shot 2017-05-16 at 11 21 04 am](https://cloud.githubusercontent.com/assets/427398/26113954/02282540-3a2a-11e7-83c9-aca92d8cbeb8.png)

There is a very small margin at the bottom, but I can't figure out what is causing it exactly.

**Comment by flukeout** [comment]
Me neither, and I can't readily reproduce it so let's close it for now.
