### ISSUE TITLE
Getting a "page not found" when I try to remix my project

### ISSUE THREAD

**Issue by hannahkane** [mozilla/thimble.mozilla.org#2129]
![screen shot 2017-05-15 at 3 43 08 pm](https://cloud.githubusercontent.com/assets/8389648/26082512/43b1f180-3985-11e7-9860-486272cf2dd0.png)

**Comment by gideonthomas** [comment]
Hmm, thanks for pointing this out @hannahkane. Going to escalate to critical since @humphd noticed this error too.
