### ISSUE TITLE
get involved -> good first bug count is wrong?

### ISSUE THREAD

**Issue by Pomax** [mozilla/thimble.mozilla.org#2135]
I don't know if this value is hardcoded atm, but it's showing me 30 good first bugs, when in actuality there are 49 (as I write this issue)

**Comment by humphd** [comment]
I bet this is the GitHub API paging and sending only the first 30 results.

The code is here: https://github.com/mozilla/thimble.mozilla.org/blob/df3c76074b8cea8ef710a45f3257d88caa14911a/public/homepage/scripts/getinvolved.js#L11

See https://developer.github.com/guides/traversing-with-pagination/ which seems to confirm this.  Probably we should re-consider how we want to show that number.
