### ISSUE TITLE
tutorials look the same when previewed vs "as tutorial"

### ISSUE THREAD

**Issue by Pomax** [mozilla/thimble.mozilla.org#2141]
when editing a tutorial, the "previw" and "tutorial" sections look identical, making it easy to go "what am I even looking at?". It feels like it's important to make the tutorial tab differently styled by default, in a way that is not affected by what the user's put in the tutorial.html file

**Comment by humphd** [comment]
Going to close this as dupe of https://github.com/mozilla/thimble.mozilla.org/issues/2003.
