### ISSUE TITLE
QA > I'm able to create an account despite my password not having a number

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.mozilla.org#2144]
Even though I get a warning. @Pomax - is this related to the latest changes? That brief flash at the end of the gif is the editor firing up with a blank project...

![_password](https://cloud.githubusercontent.com/assets/25212/26090928/cbaec496-39bc-11e7-9291-8f951b088b0d.gif)

Seems like as long the password is long enough and has one capital, it gets accepted.

**Comment by cadecairos** [comment]
That's odd, since password strength is also validated on the server, before getting bcrypted

**Comment by Pomax** [comment]
this could be two different policies between client and server

**Comment by gideonthomas** [comment]
Migrated to https://github.com/mozilla/id.webmaker.org/issues/445
