### ISSUE TITLE
Explore using HTTP2 via Cloudfront for Brackets content

### ISSUE THREAD

**Issue by humphd** [mozilla/thimble.mozilla.org#2146]
There are some nice loading speedups with HTTP2, and I notice that you can do this on AWS today:

https://aws.amazon.com/blogs/aws/new-http2-support-for-cloudfront/

Since we serve Brackets statically from Cloudfront/AWS, maybe we should do this?  I'm not sure what the downsides are, or what we'd need to tweak in the code to make it really use everything HTTP2 has to offer.

@cadecairos, @gideonthomas

**Comment by gideonthomas** [comment]
Hmm, I thought we already did this for brackets when I filed https://github.com/MozillaFoundation/mofo-devops/issues/410

**Comment by cadecairos** [comment]
> Hmm, I thought we already did this for brackets when I filed MozillaFoundation/mofo-devops#410

we've got dozens of distributions, so it's not surprising some were missed.

I've gone ahead and enabled HTTP2 for thimble.mozilla.org and thimbleprojects.org (it's literally just a radio input that can be enabled)

**Comment by humphd** [comment]
NOTE: it's Brackets I really want it for.  It's currently HTTP/1.1:

![screen shot 2017-05-16 at 12 52 28 pm](https://cloud.githubusercontent.com/assets/427398/26118104/a80becf6-3a36-11e7-8cbc-5dc63f319e44.png)

**Comment by cadecairos** [comment]
I'll find that CDN and enable it there as well

**Comment by cadecairos** [comment]
(done, it'll roll out change over the next half hour)

**Comment by gideonthomas** [comment]
This should be done...closing

**Comment by humphd** [comment]
mozillathimblepreview.net is still serving 1.1, according to Firefox and Chrome.

**Comment by cadecairos** [comment]
And so it was! I think I must've enabled it on the staging domain -.-

It's definitely enabled for the mozillathimblelivepreview.net domain now.

**Comment by humphd** [comment]
```
curl -I https://mozillathimblelivepreview.net/bramble/production/dist/index.html
HTTP/1.1 200 OK
Content-Type: text/html
Content-Length: 2034
Connection: keep-alive
Date: Tue, 16 May 2017 17:35:26 GMT
Content-Encoding: gzip
Last-Modified: Tue, 16 May 2017 16:48:05 GMT
x-amz-version-id: ACxGOWIrpU9CxG3hFUFUZg2UCvKtALow
ETag: "f0e735ba84d6d13e0b4c44c4efb8d80d"
Server: AmazonS3
X-Cache: RefreshHit from cloudfront
Via: 1.1 f564d0c1e4568b2b822f986a309f4114.cloudfront.net (CloudFront)
X-Amz-Cf-Id: BV48n4MggPMPJlrPn-8VvN4JD2uMXnFr9wSuKYaIpqUc_lWkxUSIBg==
```

I still see 1.1.

**Comment by cadecairos** [comment]
does curl support http2?

**Comment by cadecairos** [comment]
this tool reports that the domain supports http2: https://tools.keycdn.com/http2-test

**Comment by humphd** [comment]
OK, thanks for confirming.  It's odd that it won't uses HTTP2 in browsers, but I guess if it's enabled on the server side, we're good.

**Comment by gideonthomas** [comment]
We're still getting HTTP1.1. @cadecairos so the apex domain itself is serving HTTP 2.0 but the paths are still being served with HTTP 1.1

**Comment by gideonthomas** [comment]
I'm an idiot, and so is cache!
