### ISSUE TITLE
For some reason I can't create or see my previous projects. 

### ISSUE THREAD

**Issue by Spaceface13** [mozilla/thimble.mozilla.org#2147]
I have been working on a website but now I can't access it? Is it just a matter of time?

**Comment by humphd** [comment]
@Spaceface13 we pushed some new code today, which seems to have caused some authentication issues for users.  We're currently fixing some things to try and mitigate, but you could try and either a) logout of Thimble and login again; b) clear your cache for Thimble, which will effectively do the same as a) and clear your cookies.

Apologies that you're hitting this.  cc @cadecairos.

**Comment by Spaceface13** [comment]
It now is working. The new look is amazing and all the new features are incredible. One of the features answers something that I have been working on forever. Thank you so much.

**Comment by humphd** [comment]
@Spaceface13 that's great to hear!  If you have other ideas for features, or see bugs, please feel free to file more issues.
