### ISSUE TITLE
Allow pontoon.mozilla.org in X-Frame-Options header

### ISSUE THREAD

**Issue by mathjazz** [mozilla/thimble.mozilla.org#2160]
In-context l10n in Pontoon doesn't work currently for Thimble.

That's because your site uses the X-Frame-Options header.

Please [make sure](https://developer.mozilla.org/en-US/docs/Mozilla/Implementing_Pontoon_in_a_Mozilla_website#B._(optional)_Enable_in-page_localization_of_your_web_project) loading inside iframe is permitted for domain pontoon.mozilla.org.

**Comment by TheoChevalier** [comment]
Note: I’ve disabled in-context localization for now since some people reported having issues opening the Thimble project in Pontoon

**Comment by TheoChevalier** [comment]
Hey @cadecairos, is this something you can flip, or is it on the Thimble team?

**Comment by cadecairos** [comment]
This needs to be done in code

Change needs to happen [here](https://github.com/mozilla/thimble.mozilla.org/blob/add5b5baffc4860de25ee028cb6c0e5b829ba13c/server/security.js#L101-L104)

which should stop browsers from overriding [this](https://github.com/mozilla/thimble.mozilla.org/blob/add5b5baffc4860de25ee028cb6c0e5b829ba13c/server/security.js#L26-L28)

**Comment by gideonthomas** [comment]
Sorry for the delay @TheoChevalier, got a PR up now.

**Comment by TheoChevalier** [comment]
Thanks, guys! Will look into enabling in-context localization again :)
