### ISSUE TITLE
500 creating new project: TypeError: The header content contains invalid characters 

### ISSUE THREAD

**Issue by humphd** [mozilla/thimble.mozilla.org#2161]
```js
ERROR: {
  message: 'Failed to send request to https://publish-webmaker-org-prod.herokuapp.com/projects/962793',
  context: [TypeError: The header content contains invalid characters],
  userMessage: 'Failed to create new file!',
  locale: 'en-US'
}
```

We're seeing a lot of these on production.

I think it originates here: https://github.com/mozilla/thimble.mozilla.org/blob/fa3dde088dc016a562520e62a9df1f5558ba8f70/server/routes/files/index.js#L17 for the `/projects/:projectId/files/:fileId?` route.

I think it's originating in request, https://github.com/request/request/issues/2120.

We need to uriencode the auth tokens we pass with requests.

**Comment by humphd** [comment]
https://github.com/mozilla/thimble.mozilla.org/pull/2167 added some logging for this error case, so we can get better data to fix this.  https://github.com/mozilla/thimble.mozilla.org/issues/2169 is about removing it once we have more data.

**Comment by humphd** [comment]
![image](https://cloud.githubusercontent.com/assets/427398/26173063/7cefc096-3b18-11e7-8c2f-1ea0736c4394.png)

is what this is exposing on prod.

**Comment by humphd** [comment]
I notice that those invalid tokens are about the right length, but they are binary vs. in the printable range.  Next question: what is causing us to have binary tokens all of a sudden?

**Comment by humphd** [comment]
cc @cadecairos, @Pomax, @gideonthomas

**Comment by humphd** [comment]
So a user is logged in (or was logged in before we updated prod), and has a token in his/her session.  Now we try to decrypt it and we get a binary string that has no correlation to what we originally put in.  @cadecairos asks on Mattermost if we altered our crypto, and I think we did update some deps related to this.

We need to figure out what we should do in the case that this is happening, since a user won't see any of these errors, their project will just be in a "Saving..." and "Failed to save.." loop forever.  I bet this is what is often the cause of such complaints.  cc @flukeout.

We need to somehow alert the user to logout and login again, but I'm not sure where we should do it exactly.

**Comment by cadecairos** [comment]
I think this is happening because a switch in the default algorithm in cryptr: https://github.com/MauriceButler/cryptr/compare/fabae97a61119d69f03fc189f7c95dda826c96b7...master#diff-168726dbe96b3ce427e7fedce31bb0bcR9

**Comment by cadecairos** [comment]
We can potentially recover user sessions automatically with a new middleware that checks if the decrypted token is invalid, and decrypts it again using the old algorithm, and updates the session with the new algorithm

**Comment by humphd** [comment]
I'm not sure who wants to drive this fix, but I don't feel like I understand it all well enough to be that person.  I do, however, think this is pretty critical to get fixed soon.  We should figure out our approach.  Right now this will manifest itself in some people, and especially existing users, being in a broken state until they log out/log in again.

Another fix would be to surface this error in new UI that prompts you on an action to take, since the saves will never work.

**Comment by cadecairos** [comment]
```JS
  let sessionSecret = env.get("SESSION_SECRET");
  let cryptr = new Cryptr(sessionSecret);
  let cryptrAES256 = new Cryptr(sessionSecret, 'aes256');

// Later...
    setUserIfTokenExists(req, res, next) {
      if (!req.session || !req.session.token) {
        return next();
      }
      // Decrypt oauth token
      req.user = req.session.user;
      let token = req.user.token = cryptr.decrypt(req.session.token);

      if (!/^[a-z0-9]{64}$/.test(token)) {
        token = cryptrAES256.decrypt(req.session.token);
        req.session.token = cryptr.encrypt(body.access_token);
      }
      next()
}
```

**Comment by cadecairos** [comment]
That's a rough draft of what automatically recovering would look like.

**Comment by humphd** [comment]
@cadecairos can you please close this when https://github.com/mozilla/thimble.mozilla.org/pull/2170 hits prod and you're able to confirm that we're not still seeing these?  We should now see log messages about trying the fallback encryption algorithm instead, and it should work.

**Comment by humphd** [comment]
@cadecairos reports a dramatic improvement in the error rates:

![](https://i.imgur.com/eMsC44h.png)

**Comment by cadecairos** [comment]
We appear to have recovered many of the broken sessions.

![](https://i.imgur.com/8mcGePp.png)

calling this resolved!
