### ISSUE TITLE
update fallback cryptr to change the session expiry

### ISSUE THREAD

**Issue by Pomax** [mozilla/thimble.mozilla.org#2172]
If people are on an old cryptr session, we should set their session to expire at the same rate as the new cryptr sessions, so that their old session expires in a week as well.

**Comment by humphd** [comment]
Will the change we made [here](https://github.com/mozilla/thimble.mozilla.org/blob/master/server/index.js#L56-L64) to use 1 week not also affect current sessions?

**Comment by Pomax** [comment]
sessions that are successfully decoded with the fallback don't hit the error handler, though

**Comment by humphd** [comment]
What if we add `overwrite: true` to our [`cookieSession` options](https://github.com/expressjs/cookie-session#cookie-options) in https://github.com/mozilla/thimble.mozilla.org/blob/master/server/request.js#L86?
