### ISSUE TITLE
"find html elements" feature is missing its video

### ISSUE THREAD

**Issue by Pomax** [mozilla/thimble.mozilla.org#2173]
https://thimble.mozilla.org/en-US/features => "find html elements fast" is a big ol' grey box

**Comment by humphd** [comment]
![screen shot 2017-05-18 at 11 17 51 am](https://cloud.githubusercontent.com/assets/427398/26209758/ac17d392-3bbb-11e7-8894-8920bb222189.png)

WFM in Firefox on Mac.  Do you see the movie file 404'ing?

**Comment by Pomax** [comment]
This was in Chrome on OSX:

![image](https://cloud.githubusercontent.com/assets/177243/26210090/79aeb956-3ba3-11e7-9740-d4590d0b6cd3.png)

reloading with dev tools open did a refetch so probably just a caching issue.
