### ISSUE TITLE
Standardize "X" to close icon.

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.mozilla.org#2177]
In the inline editor...

![image](https://cloud.githubusercontent.com/assets/25212/26217473/5dab3cc0-3bbc-11e7-8c29-a6e4127be084.png)

In the console...

![image](https://cloud.githubusercontent.com/assets/25212/26217478/63068990-3bbc-11e7-81de-1902ed8d21a3.png)

I think we should go with the larger style for both.

**Comment by serendicoder** [comment]
Hi, 
I have found out the following-
The close icon in inline editor uses &times and styling as present in these files-
[JS](https://github.com/mozilla/brackets/blob/master/src/editor/InlineWidget.js#L44)
[Style](https://github.com/mozilla/brackets/blob/master/src/styles/bootstrap/close.less)

The close icon in console is an svg image and uses styling for dimensions, the code for which is here-
[HTML](https://github.com/mozilla/brackets/blob/master/src/extensions/default/bramble/htmlContent/console.html#L5)
[Style](https://github.com/mozilla/brackets/blob/master/src/extensions/default/bramble/stylesheets/consoleTheme.less#L255)

May I know what would be the preferred standard representation of the close icon and whether there are any specs to be followed?

**Comment by serendicoder** [comment]
@gideonthomas May I have an update on the above query?

**Comment by gideonthomas** [comment]
@flukeout would you be able to provide some input here?

**Comment by evolic** [comment]
@serendicoder I have found another problem with this icon.

It is not showing after all in Mozilla Firefox.
Do you use Mozilla Firefox or Google Chrome only?

**Comment by gideonthomas** [comment]
@flukeout re-pinging in this issue

**Comment by flukeout** [comment]
I'm sorry for losing track of this issue. @serendicoder - are you still interested in continuing this work? Let me know and I'll answer all of your questions.

**Comment by serendicoder** [comment]
Yes, I'd work on it.

**Comment by flukeout** [comment]
Hi @serendicoder - we should use the following icons...

* [Dark version](https://mozillathimblelivepreview.net/bramble/production/dist/extensions/default/bramble/images/close-icon-dark.svg) for light theme
* [Light version](https://mozillathimblelivepreview.net/bramble/production/dist/extensions/default/bramble/images/close-icon-dark.svg) for dark theme

**Comment by ericschv** [comment]
Hi @flukeout, if this issue hasn't been taken up I would like to tackle it.

**Comment by flukeout** [comment]
Hey @ericschv - go ahead. We haven't heard from @serendicoder for a while so I think you're good to go!

**Comment by humphd** [comment]
This has been fixed and merged, closing!
