### ISSUE TITLE
update /healthcheck to note the build commit rather than version

### ISSUE THREAD

**Issue by Pomax** [mozilla/thimble.mozilla.org#2181]
we're not versioning thimble in a meaningful way: we should update healthcheck so that it lists its current commit instead, so that we actually know which version of Thimble we're looking at on staging or production.

**Comment by humphd** [comment]
Assigning this to @ericsuhn, who is a student of mine looking for a good-first-bug.

So to do this, we need to adjust the code here:

https://github.com/mozilla/thimble.mozilla.org/blob/d641ee3dc7e9d42b4638d4a19da2c29a787043ab/services/login.webmaker.org/app/http/controllers/site.js#L45-L58

We need to add a `commit: ...` property, and indicate what the current git commit is.  We can probably use something like https://www.npmjs.com/package/git-rev to do it.

Take a look at this and let me know if you have questions.

**Comment by gideonthomas** [comment]
@humphd doesn't look like the right file is linked above? ^

The change needs to be made here: https://github.com/mozilla/thimble.mozilla.org/blob/master/server/request.js#L106

I'm gonna suggest using [git-rev-sync](https://github.com/kurttheviking/git-rev-sync-js) instead which does the same thing as git-rev except synchronously.
