### ISSUE TITLE
Missing remix button when publishing page without HTML, HEAD, BODY, etc

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.mozilla.org#2183]
https://thimbleprojects.org/bandreasv/227682/

To remix - https://thimble.mozilla.org/projects/227682/remix

Reported by @omnignorant

**Comment by flukeout** [comment]
I wonder if we removed the Remix button from a-frame projects.

**Comment by humphd** [comment]
Page is missing `<head>` etc. and only has `<script>`.  I bet it's just that we aren't doing our injection stuff right on publish when DOM looks like this.

**Comment by humphd** [comment]
Yup, added and https://thimbleprojects.org/humphd/274432/ has it.

**Comment by flukeout** [comment]
Okay year crazy, it doesn't even have an HTML or BODY tag.

**Comment by humphd** [comment]
Possible dupe of https://github.com/mozilla/thimble.mozilla.org/issues/1804

**Comment by flukeout** [comment]
Closing! This is more of a lack of linting / hints to the user that the page is invalid.
I think it's OK that this happens in these instances - small percentage I think.
