### ISSUE TITLE
provide some means for people to debug the black screen without dev tools

### ISSUE THREAD

**Issue by Pomax** [mozilla/thimble.mozilla.org#2187]
Some institutional computers do not allow dev tools to be opened in any way, which makes it really hard to determine what's actually going wrong when users get the black screen that indicates Brackets was unable to properly run.

Perhaps we can add information to the page source as HTML comments when the blacks screen triggers so that "view source" can give some insight into what went wrong without needing dev tools.

**Comment by humphd** [comment]
#2193 and #2195 will cover this I think.
