### ISSUE TITLE
Deleting indexedDB "local" db via console causes projects not to load.

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.mozilla.org#2188]
Signed out on Mac Firefox. I ran ``indexedDB.deleteDatabase('local')`` in my console.

Now, when I try to create a new project, I'm stuck on the green loading screen with the following in my console...

![image](https://cloud.githubusercontent.com/assets/25212/26268258/617a5e20-3ca3-11e7-9b30-4f80342027ee.png)

**Comment by humphd** [comment]
This is an odd thing to do, can I ask why you did it?  It looks like you're in Chrome, right?  So you did this on which domain?

**Comment by flukeout** [comment]
To test if we are able to recover from stuff like this. I did this when using thimble.mozilla.org. I was trying to mess up my db to see if I could get myself into some sort of corrupted db state.

**Comment by humphd** [comment]
I'm going to close this, as I'm not sure we can do a lot about this case.
