### ISSUE TITLE
"Less is not defined error" causing project not to load.

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.mozilla.org#2189]
![image](https://cloud.githubusercontent.com/assets/25212/26281576/017ab44e-3db0-11e7-9315-9eaaea2ebe6f.png)

It's stuck on the green screen for a user, who has tried to reload via the button a few times. I'll suggest signing in and out again and then failing that, trying another browser. I'll see if I can find out what browser this is.

**Comment by flukeout** [comment]
Looks like it's only happening when editing one certain project. This is the published version here:

* https://thimbleprojects.org/kuanca/270073/

Remixing it causes the same error for me.

**Comment by humphd** [comment]
OK, I know what this is.  I disabled LESS in production, but forgot that I had that transform code that turns LESS files into CSS.  This project has some less files in it, so it's trying to do that, and failing to find LESS, so crashing.

I'll disable the LESS transforms.

**Comment by flukeout** [comment]
Okay, I'll let the user know a fix is on the way. You've got a launch label on this, will you be working on it in the near future?

**Comment by humphd** [comment]
Yes, I'll do it next.

**Comment by humphd** [comment]
Fix for this in https://github.com/mozilla/brackets/pull/766

**Comment by humphd** [comment]
We'll need to update Brackets on prod soon to get this, and some other fixes, landed.
