### ISSUE TITLE
Project not loading console error dump from user...

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.mozilla.org#2191]
This was in Firefox I believe, and was resolved by creating a new profile and using that.

![image](https://cloud.githubusercontent.com/assets/25212/26287329/0f7e2ebc-3e2e-11e7-8ac5-70ee7b7f04aa.png)

![image](https://cloud.githubusercontent.com/assets/25212/26287332/15cc29fe-3e2e-11e7-981b-1a34287b5c1f.png)

**Comment by flukeout** [comment]
I haven't seen this particular error, ``NS_ERROR_FILE_CORRUPTED`` but might be related to our recent woes.

cc @humphd

**Comment by humphd** [comment]
Sounds like https://bugzilla.mozilla.org/show_bug.cgi?id=1341070, which could mean that `localStorage` or `indexedDB` databases have become corrupted somehow.  Not a bug we can fix from Thimble, but we might be able to provide some docs on what to try (e.g., new profile).

**Comment by humphd** [comment]
I think it's `localStorage` db corruption causing [this code](https://github.com/adobe/brackets/blob/5562adcbd8974e968a453bfc9f1cb7386f114ff8/src/utils/Global.js#L92-L95) to fail with that `NS_ERROR_FILE_CORRUPTED` message.

**Comment by humphd** [comment]
@flukeout there's nothing we can do about this, it's a browser bug.

**Comment by flukeout** [comment]
Okay, I'll file an issue to report as much to the user. The Try Again button won't help for cases like these.
