### ISSUE TITLE
Turn barking-dog GIF into a project you can make on Thimble

### ISSUE THREAD

**Issue by humphd** [mozilla/thimble.mozilla.org#2192]
I love @flukeout's new [animated GIF](https://twitter.com/mozilla/status/866995618954084353) for the launch.  Can we turn that into a very simple starter kit that goes on the home page?

![image](https://cloud.githubusercontent.com/assets/427398/26369256/1f47273c-3fc2-11e7-87f7-61c6e274af51.png)

Here are some thoughts:

* Lego bricks are either HTML `<div>`s or images
* CSS for layout of bricks
* include a single JS function that happens when you click the dog to make the "bark" animation happen.

Things people could remix:

* What the dog says
* aspects of the animation (timing variables)
* colours of the bricks
* maybe add a tail or some other brick
* include a sound file that plays when the bark happens using `<audio>`
* etc

I don't think it needs to be super complicated or become a game or something; but it's a fun way to showcase all of HTML, CSS, and JS.

**Comment by flukeout** [comment]
Published a basic version to the Thimble homepage gallery: https://thimbleprojects.org/mozillalearning/279519/

This version is just about placing and positioning different colored blocks. I think I'll make two more versions...

* One that showcases some CSS some animations
* One that adds a click handler with some basic functionality
  * Maybe swapping brick colors?
  * Maybe changing the text within a brick?
  * Maybe placing random bricks?

**Comment by flukeout** [comment]
I've created this and published it to the gallery so closing.
