### ISSUE TITLE
Update style-src CSP header for inline style

### ISSUE THREAD

**Issue by gideonthomas** [mozilla/thimble.mozilla.org#2196]
We added the `unsafe-inline` directive for stylesheet CSP here: https://github.com/mozilla/thimble.mozilla.org/blob/master/server/security.js#L54-L56 to allow changes in the loading spinner. Let's revert that by hashing https://github.com/mozilla/thimble.mozilla.org/blob/master/views/editor/bramble.html#L2-L145 again and using that as the CSP rule.

**Comment by auracle** [comment]
Can I have this one?
