### ISSUE TITLE
Hover tooltip string missing from "Add a Tutorial" item in the file menu

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.mozilla.org#2203]
<img width="250" src="https://cloud.githubusercontent.com/assets/25212/26423158/57fe7778-4081-11e7-8015-bb23e2e8478d.png">

When I hover over this, I see ``navTutorial`` in the tooltip. Seems like there's gotta be a missing string. Let's add it and make it say ``Add a Tutorial``.

**Comment by morrme** [comment]
I think it is just a mistake in a label. I'd like to try to fix this.

**Comment by flukeout** [comment]
Go for it, @morrme - awesome.

**Comment by morrme** [comment]
@flukeout I've submitted a PR, #2214
