### ISSUE TITLE
Deleting an image from a project and adding it causes it to not work.

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.mozilla.org#2205]
I've got a project with some ``.svg`` files that are being used as background images. When I delete one of those files, and upload the same file again to the project, the background image no longer works. 

I'm pretty sure we have this, or something equivalent to it, filed already but I wanted to get it down again while it was happening. Reloading the editor solves this, as I guess the "blob" reference that CSS uses is rebuilt. Anyway, just chucking it in.

**Comment by flukeout** [comment]
@humphd This would be a good one to tackle - it makes Thimble seem broken without giving any indication to the user that something could be wrong.

Seems related to @gideonthomas' issue here https://github.com/mozilla/brackets/issues/751

**Comment by humphd** [comment]
I put a fix up for that CSS refresh issue here https://github.com/mozilla/brackets/pull/771.  Let's test with that fix in, and see if this is related/fixed by it.

**Comment by humphd** [comment]
@flukeout can you re-test this with my new fix in?  It's on staging.

**Comment by flukeout** [comment]
Testing now.

**Comment by flukeout** [comment]
@humphd - tested and works great. One thing we could consider is auto-refreshing the preview whenever we upload new files. In the case of uploading an image that is already being referenced in the CSS, it doesn't show up until I manually reload the preview.
