### ISSUE TITLE
404 Page Styling Busted on thimbleprojects.org

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.mozilla.org#2207]
Gah...

![image](https://cloud.githubusercontent.com/assets/25212/26431057/c80f4748-40a6-11e7-9b65-675a7bff3a33.png)

**Comment by gideonthomas** [comment]
I don't see anything 404'ing. Do you know if a stylesheet is missing?

**Comment by flukeout** [comment]
What do you mean by that @gideonthomas - this is the 404 page on the thimbleprojects.org domain...

* https://thimbleprojects.org/blam

It has instructions about adding an ``index.html`` page as that's a common source of the errors.

**Comment by flukeout** [comment]
Okay, I've updated the page that we are serving for this, it's available in the ZIP archive below along with an image that goes with it...

* [error-page.zip](https://github.com/mozilla/thimble.mozilla.org/files/1042612/error-page.zip)

Should appear like this...

![image](https://cloud.githubusercontent.com/assets/25212/26649281/44ac0f7c-45fa-11e7-9033-86bfd7ba83db.png)

@cadecairos Will you be able to do this? Do you need anything else?

**Comment by cadecairos** [comment]
@flukeout updated: https://s3.amazonaws.com/publish-webmaker-org-staging-s3bucket-bqo25c3iqx2o/error.html

**Comment by flukeout** [comment]
@cadecairos The image isn't showing up in production...

![image](https://cloud.githubusercontent.com/assets/25212/26650112/447b63a6-45fd-11e7-8c77-71b10f1d1a9b.png)

It's meant to be in the same level of folder as the error page. Is that possible to set up? Let me know if I need to change anything.

**Comment by cadecairos** [comment]
oh, I didn't realize there was a gif in the archive. it's in place now.

**Comment by flukeout** [comment]
Thanks @cadecairos - tested & works great!
