### ISSUE TITLE
[Collaboration] Prototype 0 - Editor syncing for one file

### ISSUE THREAD

**Issue by gideonthomas** [mozilla/thimble.mozilla.org#2210]
### Prototype 0
A simple editor that syncs between two codemirror instances for a single file
  - It will not run on Thimble, everything happens within the Brackets repo
  - No sync of mouse pointer
  - Bramble with a single index.html file (e.g., default HTML file), 2 people can work on it with syncing in editor
  - The startup state of the editor will always be the same, i.e., always write a single static file index.html and overwrite whatever is there

**Comment by hkirat** [comment]
Other than the startup sync, everything else has been implemented [here](https://github.com/mozilla/brackets/pull/801). 
Working on the fourth point now.
Most probably we will be using an event which is fired when a new client joins.
