### ISSUE TITLE
Project Loading Slowly GA event fires even though a project loaded quickly.

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.mozilla.org#2212]
Oh boy. I was reviewing @humphd's analytics PR and logging all the GA calls and lo and behold I saw this thing pop up in the console even though my project loaded just fine (in less than 5 seconds). 

![image](https://cloud.githubusercontent.com/assets/25212/26474230/b5aca730-4164-11e7-834c-dc02818b2a75.png)

Tested this in Chrome and FF. Happens on both signed out and signed in projects.

**Comment by humphd** [comment]
I bet we need to `clearTimeout` that 15s timeout when we successfully load.  It's just finishing, showing the warning (but the div is already hidden).  So glad you found this!

**Comment by flukeout** [comment]
Yeah we're def not clearing it haha.
