### ISSUE TITLE
Publish server - Update knexjs

### ISSUE THREAD

**Issue by gideonthomas** [mozilla/thimble.mozilla.org#2219]
We should update knex.js to the latest version as their changelog indicates some perf fixes as well as a switch from `pool2` to `generic-pool` as their connection pooling interface (I don't know if there will be significant implications for this but I assume better connection management). It is a bit of a random fix but is still probably worth doing.

cc @cadecairos

**Comment by humphd** [comment]
I think login needs it too (e.g., new versions of the db related modules).

**Comment by gideonthomas** [comment]
This is done
