### ISSUE TITLE
Japanese localization - tracking issue

### ISSUE THREAD

**Issue by TheoChevalier** [mozilla/thimble.mozilla.org#2220]
I’ve just enabled Japanese and they have started translating Thimble, let’s use this issue to track this and add ja locale to the language switcher.

Language name: `日本語`

**Comment by gideonthomas** [comment]
This already exists on staging - https://bramble.mofostaging.net. Once the translations are greater than 50% and we're ready to push to production, I can enable it on production as well.

**Comment by TheoChevalier** [comment]
Heads up that the team is almost done :) A bunch of strings are still pending review, though https://pontoon.mozilla.org/ja/thimble/

**Comment by gideonthomas** [comment]
I've already enabled ja on prod since it's over 64% done, so feel free to close.

**Comment by TheoChevalier** [comment]
Thanks!
