### ISSUE TITLE
Applying a filter to an SVG images breaks the image.

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.mozilla.org#2222]
While you can click through the different filters to see their effect, applying causes the image to stop working...

![_svg_filter](https://cloud.githubusercontent.com/assets/25212/26561099/654685ea-4470-11e7-80db-08ba108c57f3.gif)

We should disable the image filter feature for ``.svg`` images. I guess caman knows how to render the svg to the canvas, but can't convert it back into an svg with the effect applied.

**Comment by humphd** [comment]
Fix for this in https://github.com/mozilla/brackets/pull/776
