### ISSUE TITLE
Consider reloading the preview when files are uploaded to project.

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.mozilla.org#2223]
This is a bit of a fringe scenario, but let's say I'm uploading an image file that is already referenced in the markup via an ``img`` tag or maybe as a ``background-image`` in CSS. When the upload completes my preview doesn't refresh to show me the image. I have to manually refresh it, or make other changes that cause it to refresh.

This may make the editor feel broken because most other changes happen instantly.

**Comment by humphd** [comment]
Fixing this would involve adding a call in the success case of this function https://github.com/mozilla/brackets/blob/master/src/utils/DragAndDrop.js#L320-L341, probably at line 338, which calls this https://github.com/mozilla/brackets/blob/master/src/LiveDevelopment/LiveDevMultiBrowser.js#L909-L916 and reloads the live dev preview via the protocol.

**Comment by vikramnr** [comment]
@humphd @flukeout Can I take this issue?

**Comment by gideonthomas** [comment]
@vikramnr yeah go ahead. Do you have your development environment setup? If not, you can find the instructions here: https://github.com/mozilla/brackets/blob/master/README.md

**Comment by flukeout** [comment]
@vikramnr - are you still working on this? Please let us know, otherwise we will release it to other contributors. Thanks!

**Comment by vikramnr** [comment]
Please assign to other contributers.

**Comment by Cryzek** [comment]
Hi, I was trying to reproduce this issue. So, I added a img tag in the index.html and then dropped an image file(with the same name),and the preview reloaded automatically showing the image in the html preview. I had the "Auto" refresh button checked. Should the issue be tried when it is unchecked?

**Comment by feihaozi77** [comment]
@humphd @flukeout Hi, I'm a student at Seneca college learning open source, and I was hoping to work on this bug for my course.  If no one else is currently working on it, I'd like to give it a try.

**Comment by feihaozi77** [comment]
@Cryzek I tried the same thing, When Auto is checked the auto reload works good, maybe this issue needs to be reproduced.

**Comment by feihaozi77** [comment]
![auto_reload](https://user-images.githubusercontent.com/13205171/30966918-960b3118-a428-11e7-8fc3-c8ed1d538e88.gif)
the above gif is a short screen cast showing when auto-refresh check box is checked, if i drag and drop the image to the project to replace an existing one, the preview will get updated.
However, if you leave the auto-box unchecked, the drag and drop won't trigger the updating of the preview. 
I wonder If you want to make this issue as "Consider reloading the preview when files are uploaded to project when auto-checkbox is unchecked". If that is what you need, i would like to work on that

**Comment by humphd** [comment]
@flukeout can you confirm that this is still an issue?  Looks like it might be fixed to me, based on what @feihaozi77 is showing above.

**Comment by flukeout** [comment]
Hey @feihaozi77 - thanks for looking into this. That does looks like it's working correctly. Can you test another case for me? Can you add a background image via a linked CSS file to an element on the page and then upload an updated image to see if that works as well? Thanks!

If it does, I think it's fair to close this issue. Cheers!

**Comment by feihaozi77** [comment]
@flukeout , just tried the background-image and it works, with auto-box checked everything worked  fine.

**Comment by flukeout** [comment]
Thanks for looking into this. I bet it was filed before we'd updated how the live preview handles files. Closing!
