### ISSUE TITLE
Indicator for selected file when opening right-click menu has wrong color.

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.mozilla.org#2232]
It looks like it has a faint white background, which is correct for the dark theme, the highlight should be darker...

![image](https://cloud.githubusercontent.com/assets/25212/26610058/12c2aed0-455a-11e7-88d4-e63fd30b2f7f.png)

The correct highlight can be the same as the hover state, seen here:

![image](https://cloud.githubusercontent.com/assets/25212/26610075/30e38ad8-455a-11e7-9f60-ce12737b785c.png)

**Comment by humphd** [comment]
For whoever wants to work on this, you'd make the changes in Brackets here https://github.com/mozilla/brackets/blob/master/src/extensions/default/bramble/stylesheets/sidebarTheme.less.

**Comment by auracle** [comment]
I'll fix this!

**Comment by auracle** [comment]
Fix for this in mozilla/brackets#783
