### ISSUE TITLE
Fix localization of file delete dialog

### ISSUE THREAD

**Issue by humphd** [mozilla/thimble.mozilla.org#2233]
In Brackets we show a confirmation dialog when the user tries to delete a file:

https://github.com/mozilla/brackets/blob/master/src/document/DocumentCommandHandlers.js#L1610

That string is hard coded, and should be properly localized.  We need to create a new string key/value in https://github.com/mozilla/thimble.mozilla.org/blob/master/locales/en-US/editor.properties and then use it in Brackets.

**Comment by Rajat-dhyani** [comment]
@humphd i would like to work on this if that's okay ?

**Comment by humphd** [comment]
Sure, sounds good.  The string will need to go in Thimble, but get used in Brackets.
