### ISSUE TITLE
After deleting a file, it's name is still indicated in the Editor header bar

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.mozilla.org#2237]
See here, this is after deleting ``thumbnail.png``. Even though the file is gone, the name is still in the Editor bar.

![image](https://cloud.githubusercontent.com/assets/25212/26656393/b48dc0b0-4613-11e7-9742-fa81c9f8637e.png)

This happens with any file that you delete while it is open. It should clear the filename.

**Comment by humphd** [comment]
When this happens, does your editor actually switch to another file?  It looks like it didn't in the case above, which would explain why it doesn't fire the `editorChange` event, which should be what triggers all this.
