### ISSUE TITLE
Image not showing up on thimbleprojects.org 404 page.

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.mozilla.org#2247]
We updated the 404 page in https://github.com/mozilla/thimble.mozilla.org/issues/2207 

When we load the page directly, things work fine...

* https://s3.amazonaws.com/publish-webmaker-org-staging-s3bucket-bqo25c3iqx2o/error.html

But when the page is served within the context of a bad project URL like this...

* https://thimbleprojects.org/flukeout/9999999

![image](https://cloud.githubusercontent.com/assets/25212/26701407/d6c7acc8-46d5-11e7-99eb-8c07086c37e9.png)

The helper image no longer shows up. I guess that's because the ``<img>`` tag expect the image to live in in the same folder as the ``error.html`` page, which it no longer does at that point.

The absolute path to the image is https://s3.amazonaws.com/publish-webmaker-org-staging-s3bucket-bqo25c3iqx2o/index-html.gif

@cadecairos Should I update the markup of the ``error.html`` page to have an absolutely referenced image src? Let me know and I can provide it.

**Comment by cadecairos** [comment]
Would `/index-html.gif` work?

Otherwise let's use the CDN hostname https://thimbleprojects.org/index-html.gif

**Comment by flukeout** [comment]
Hi @cadecairos - here's the updated error page with the correct path to the image.

[error-updated.zip](https://github.com/mozilla/thimble.mozilla.org/files/1049100/error-updated.zip)

Cheers!

**Comment by flukeout** [comment]
Fixed by @cadecairos - closin'
