### ISSUE TITLE
Update Console instructions for IE on Wiki

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.mozilla.org#2249]
We need instructions on how to open the browser console for IE on the Wiki. Would be cool if someone could update that with a few steps...

https://github.com/mozilla/thimble.mozilla.org/wiki/Project-not-Loading-Help

**Comment by flukeout** [comment]
@Pomax if you have a spare few mins?

**Comment by Pomax** [comment]
added for Edge.
