### ISSUE TITLE
Change "Oops, something went wrong" page title.

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.mozilla.org#2250]
Currently when the editor doesn't start we show this...

![image](https://cloud.githubusercontent.com/assets/25212/26704641/624ced26-46e5-11e7-991a-50d8e4cc141b.png)

However, I think we should just say something like **Thimble could not start** so that it makes it more obvious to the user what's going on when they are reaching out to us via email.

**Comment by serendicoder** [comment]
Hi,
I am suggesting few error messages which could be displayed in this scenario. Please let me know if any of these is suitable or something else is required.
Unable to launch Thimble...
We couldn't start it for you!
Aw, could not start!
App did not load properly!
It failed to launch this time...
Failed to start Thimble!
Oops, something failed the launch!

Also, I would like to know what are the possible causes to keep the app from starting? Thanks.

**Comment by abhiyad** [comment]
hi @flukeout Please guide me to the part of code being referred to .
I Want to fix this.

**Comment by DanielBrown3108** [comment]
Hi @flukeout 
I want to add up on some suggestions that @serendicoder was making for the error messages
    Something went wrong...
    Somethings not right here...
    Hmm, that's not right...
    Darn, somethings wrong on our end...
    Hold up!
    
That's all for now.

**Comment by MhdTlb** [comment]
Can I work on this?

**Comment by serendicoder** [comment]
Hi @flukeout,
May I have an update on this issue ? Thanks.

**Comment by flukeout** [comment]
Hey @MhdTlb - if you want to take it, please go ahead - let me know.

@serendicoder - let's work on the QR code issue together instead? Cheers!

**Comment by MhdTlb** [comment]
@flukeout  It took me a while to set up my dev environment.
Will we display this message **Thimble could not start**?
