### ISSUE TITLE
Change position of "Download" action in the right-click menu.

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.mozilla.org#2252]
I can't tell you how many times I've accidentally downloaded a file instead of deleting it. They both start with D and Delete used to be the right option (and will probably get used more often)...

<img src="https://cloud.githubusercontent.com/assets/25212/26739828/2f5f0770-4788-11e7-95f5-08aa4a5c56e9.png" width="250"/>

Let's move ``Download`` above ``Delete``

**Comment by humphd** [comment]
haha, I just landed the `Download` stuff yesterday, so it can't be *that* many times!  Yeah, this is a good idea.

Code for this is in https://github.com/mozilla/brackets/blob/master/src/command/DefaultMenus.js#L240-L244 in Brackets.

**Comment by MhdTlb** [comment]
Still open?

**Comment by gideonthomas** [comment]
@serendicoder, you seem to have a commit referring to this issue. Are you still interested in opening up a PR for this issue or can @MhdTlb work on it?

**Comment by serendicoder** [comment]
@gideonthomas Thanks for the response. I will submit the PR.

**Comment by serendicoder** [comment]
@gideonthomas Submitted a PR [here.](https://github.com/mozilla/brackets/pull/841)
