### ISSUE TITLE
Publish & Cancel buttons showing when project is already published.

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.mozilla.org#2253]
This is happening right now on latest master. We've introduced a UX bug, I'll work on it now so that we can roll it out for monday...

![image](https://cloud.githubusercontent.com/assets/25212/26739931/86f0d25c-4788-11e7-8129-4220369d3202.png)

**Comment by flukeout** [comment]
There's a PR in for this ready to go, let's review + push on Monday when we go to prod.

**Comment by zmf0507** [comment]
can naybody tell me how can i access the code for the above section to fix it? i am new

**Comment by flukeout** [comment]
Hi @zmf0507 I've already made a Pull Request to fix this issue so there is no more work required here. We will close the issue as soon as the Pull Request has landed.
