### ISSUE TITLE
Don't block on S3 deletes when running the deleting a project on publish

### ISSUE THREAD

**Issue by humphd** [mozilla/thimble.mozilla.org#2255]
![screen shot 2017-06-02 at 4 46 49 pm](https://cloud.githubusercontent.com/assets/427398/26744333/746a2522-47b3-11e7-9904-2505674dec83.png)

We shouldn't block a call to `DELETE /projects/{id}` on S3 cleaning out all the files.  We should delete the metadata from the DB, and then let the user "we're deleting your project" and have it happen in the background.

**Comment by flukeout** [comment]
Yeah, I don't think we should even bother showing anything. The item gets removed from the UI, and as far as the user is concerned, it's just gone.

**Comment by humphd** [comment]
Closing this in favour of #2273
