### ISSUE TITLE
Incomplete string on Get Involved page

### ISSUE THREAD

**Issue by MekliCZ** [mozilla/thimble.mozilla.org#2259]
On Get Involved page, one of Brian Yang's contributions (Added support for file icons in) is incomplete. I guess there should be one more word (Thimble; Editor; something else?).

**Comment by gideonthomas** [comment]
Nice catch @MekliCZ! @flukeout what should the string be?

**Comment by flukeout** [comment]
Hey good catch @MekliCZ - it should say...

``Added support for icons in the file list``

**Comment by flukeout** [comment]
Assigned to @kritisingh1

**Comment by apoorvasingh17** [comment]
@flukeout When I saw the bug it wasn't assigned to anyone so I worked on it: #2472 
Really sorry didn't pay attention that it was referenced earlier. 
Will my PR be considered?
