### ISSUE TITLE
Reuse Image View "editor" in Brackets for other media types

### ISSUE THREAD

**Issue by humphd** [mozilla/thimble.mozilla.org#2269]
Here's what happens if you try to load an `.mp3` file:

![screen shot 2017-06-06 at 7 00 25 pm](https://user-images.githubusercontent.com/427398/26855683-6f718a76-4aea-11e7-8c56-3e02d84294e5.png)

Brackets has an Image Viewer, which we use to show images and SVG (as images).  I'd like to extend it so that we can also show `<video>` and `<audio>`.

We'd need to adjust things a bit for non-images:

![screen shot 2017-06-06 at 7 01 59 pm](https://user-images.githubusercontent.com/427398/26855726-aac5bd4a-4aea-11e7-9085-731ba8af443a.png)

For example, audio has a duration but not a width/height (video has both!).  And there's no way to extract colours, or apply filters.  But otherwise, the basics are the same.

**Comment by flukeout** [comment]
Should we write different viewers, or add different modes to this one?

**Comment by humphd** [comment]
Probably we should write separate ones, but refactor out a bunch of the `ImageViewer` because so much of it will be the same across types.
