### ISSUE TITLE
Show something useful when we can't/won't load a file type

### ISSUE THREAD

**Issue by humphd** [mozilla/thimble.mozilla.org#2270]
Here's what happens when you load a `.pdf`:

![screen shot 2017-06-06 at 7 04 47 pm](https://user-images.githubusercontent.com/427398/26855792-0e55c396-4aeb-11e7-8ad1-dc590c1f10cb.png)

It's not really useful.  It might be better if we had a default view that we showed that gave some info, for example: filename, file size, and maybe some info about why we aren't showing it to you because it's a binary file type, etc.

@flukeout you might have ideas about how the above should look.  It wouldn't be hard to implement this.

#2269 is related, and deals with things we *can* show in a more meaningful way.

**Comment by flukeout** [comment]
In addition to the above, it might be nice to have a **Download** action.

**Comment by humphd** [comment]
I also think we should add a `I know what I'm doing, let me edit this` button, for cases like what I hit in https://github.com/mozilla/thimble.mozilla.org/issues/1955#issuecomment-306662729 with `phaser.map`.

**Comment by flukeout** [comment]
Yeah good call - **Edit as Text** or something.

**Comment by humphd** [comment]
Adding support for PDFs here https://github.com/mozilla/brackets/pull/815
