### ISSUE TITLE
CSS for <li> in dialog with dark theme using white text in File Import error message

### ISSUE THREAD

**Issue by humphd** [mozilla/thimble.mozilla.org#2271]
Spin-off from https://github.com/mozilla/thimble.mozilla.org/issues/1955#issuecomment-306662729--the import error dialog in Brackets doesn't show what went wrong.

STR:
* Create a new project
* Make a file on your desktop named `phaser.map`
* Drag the file into the file tree
* You should get an error indicating that the file type is not supported
* What I get is a dialog without the message

![screen shot 2017-06-06 at 9 44 03 pm](https://user-images.githubusercontent.com/427398/26858844-c06a6c7e-4b01-11e7-930b-f0708bbdb1d3.png)

**Comment by humphd** [comment]
![error-string-colour](https://user-images.githubusercontent.com/427398/27303179-e3fca39a-5507-11e7-9633-0aad81c41928.gif)

Spent some time on this today, and it's a CSS issue, where the text for the `<li>` is white.  I think this is fallout from the default styling changes we made to dialogs.  @flukeout?

**Comment by flukeout** [comment]
Thanks for catching that @humphd - I screwed this up when I removed the "dark" theme from the modals. Will fix.

**Comment by demajkel** [comment]
if the background is dark, the font should be light :) at Your place I would change the background color of the modal to dark not remove or change color of the fonts :) This issue can come back later in another place ;)
