### ISSUE TITLE
[Firefox] Fix CSP blocking precaching of editor

### ISSUE THREAD

**Issue by humphd** [mozilla/thimble.mozilla.org#2275]
Firefox is reporting that our precaching isn't working due to CSP:

![screen shot 2017-06-07 at 12 15 14 pm](https://user-images.githubusercontent.com/427398/26889138-15670d4e-4b7b-11e7-9ff3-bf3303d3755e.png)

We probably need to add the domain for the editor.

**Comment by gideonthomas** [comment]
ah beat me to it
