### ISSUE TITLE
[Firefox] Snippets button has incorrect colouring

### ISSUE THREAD

**Issue by humphd** [mozilla/thimble.mozilla.org#2277]
![screen shot 2017-06-07 at 1 35 12 pm](https://user-images.githubusercontent.com/427398/26892433-3ed197fc-4b86-11e7-825a-3b144b03b33e.png)

Maybe similar to the logo issue we had with Firefox?

**Comment by flukeout** [comment]
Ooof, yeah must be. What the heck. The last Firefox release was on May 19th - so I'm not sure why this stuff is suddenly breaking.

**Comment by ahsanbarkati** [comment]
I am new to thimble. Please help me start my contribution to it. Please tell me the suggested colour.

**Comment by ahsanbarkati** [comment]
Do i need me make its color similar to the other buttons?

**Comment by flukeout** [comment]
Hello @ahsanbarkati - yeah that is correct. Do you have your development environment up and running?

**Comment by ahsanbarkati** [comment]
NO. Can I get some help on it so that I can start contributing.

**Comment by flukeout** [comment]
Have you tried following the steps outlined in the Readme?

* https://github.com/mozilla/thimble.mozilla.org/blob/master/README.md
