### ISSUE TITLE
Unneeded blue outline on File Tree elements

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.mozilla.org#2279]
![image](https://user-images.githubusercontent.com/25212/26897778-88e3ccd2-4b7e-11e7-8dd9-b9c4afe065cc.png)

Let's get rid of this. For me, on Mac Chrome, the blue lines show up when I hold the mouse click down on top of an item. And also, they stick around when the file I have open is an image.

**Comment by humphd** [comment]
I thought we fixed this before I landed https://github.com/mozilla/brackets/pull/704#issuecomment-299971160, but I guess not.  I'm not sure how to deal with this, so assigning to you, @flukeout

**Comment by flukeout** [comment]
Yep, I'll take it - I thought we nuked it too.

**Comment by flukeout** [comment]
Addressed in Brackets PR - https://github.com/mozilla/brackets/pull/790
