### ISSUE TITLE
Arrange File view so folders are shown above files.

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.mozilla.org#2281]
My own editor does this, and I appreciate it. I think files and folders are different enough that it makes sense to group them together instead of enforcing alphabetical order like we currently do...

**My Current Editor** (Nice and organized, great)

<img src="https://user-images.githubusercontent.com/25212/26939536-73d9df4e-4c2c-11e7-8fff-b3b23c971608.png" width="200" />

**Thimble** (Not good, messy & chaotic)
This project in particular made me think about how disorganized and chaotic this looks...

<img src="https://user-images.githubusercontent.com/25212/26939558-874bdb22-4c2c-11e7-99f7-3e23c0a4a1e8.png" width="200" />

**Comment by humphd** [comment]
@flukeout did this land?  Can we close this?

**Comment by flukeout** [comment]
Yep landed in brackets, closing.
