### ISSUE TITLE
Tracking Frisian localization

### ISSUE THREAD

**Issue by TheoChevalier** [mozilla/thimble.mozilla.org#2283]
Just enabled Frisian (fy-NL) on Pontoon, let’s use this ticket to track progress and enable the locale on staging/prod.

Native language name `Frysk`

**Comment by Pomax** [comment]
There's a language I would not have expected. Do we have any Frisian users?

**Comment by TheoChevalier** [comment]
Frisian is a small locale, but that’s the beauty of our community, we don’t only support languages with hundreds of millions of speakers.

**Comment by Pomax** [comment]
As a Dutchman, I am quite aware of this. I am, however, literally surprised we have _any_ Frisian users.

**Comment by TheoChevalier** [comment]
Translation is complete, can someone enable it on staging/prod please?

Thanks!

**Comment by gideonthomas** [comment]
Will do this today
