### ISSUE TITLE
When Remixing a project, the project description does not carry over to the Remix.

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.mozilla.org#2288]
**Steps to reproduce**
* Create a project
* In the publish dialog, add a description
* Publish the project
* From the published version, Remix it
* In the editor, open the publish dialog
* The project description is empty

**Comment by gideonthomas** [comment]
The issue is here: https://github.com/mozilla/publish.webmaker.org/blob/master/api/modules/publishedProjects/controller.js#L36

it should use the `get` api vs. directly accessing it via dot notation.

**Comment by atiqueahmedziad** [comment]
@gideonthomas can you please check the pr if it is alright?
