### ISSUE TITLE
<a> tag with href="#" throws JS error in Thimble console.

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.mozilla.org#2290]
**To reproduce...**

* Create a new blank project
* Add an ``<a href="#">Test</a>`` to your index.html page
* Click the Test link in the preview
* The preview wigs out and the console opens with the following erorr...

**Screenshot of error on Staging**
![image](https://user-images.githubusercontent.com/25212/27089355-fd7a1026-500e-11e7-81be-a9ce20f0bd44.png)

**Screenshot of error with the Service Worker branch**
![image](https://user-images.githubusercontent.com/25212/27089668-ee8f01d8-500f-11e7-9346-129828d6f1c3.png)

This happens locally when running Thimble along with brackets. When running just the hosted brackets, this doesn't happen to me.

cc @humphd

**Comment by gideonthomas** [comment]
It's interesting that it throws.

I think the fix is just that https://github.com/mozilla/brackets/blob/master/src/extensions/default/bramble/lib/LinkManagerRemote.js#L24-L28 needs to be wrapped in a try/catch/finally block so that it doesn't throw.

**Comment by humphd** [comment]
Merged, fixed.

**Comment by Pomax** [comment]
Although on an HTML note this is really bad markup and should really be giving people warnings along the lines of "this used to be how we did things in HTML4.1, a version of HTML from 1998, but is no longer how we do things. If you want a clickable thing in HTML5 that is **not** a navigating link, use a `<button>` and use CSS to turn off borders and coloring"
