### ISSUE TITLE
[Windows] Leading backslash in filenames for new Thimble project

### ISSUE THREAD

**Issue by cadecairos** [mozilla/thimble.mozilla.org#2293]
When I create a new project in Thimble, I see trailing forward slashes on the files (`\style.css` and `\index.html`) There is also a second `index.html`, without a leading slash.

OS: Windows 10 Pro (creators update)
Node version: 6.11.0
npm version: 5.0.3

STR: 
1. Run all dependent thimble services natively on windows (no vagrant/docker)
2. Create a new Thimble project
3. check the project file names in the filebrowser

expected: Two files - `index.html` and `style.css`
actual: Three files - `\index.html`, `index.html`, and `\style.css`

**Comment by Pomax** [comment]
tagging myself so I remember to try this - /cc @pomax

**Comment by humphd** [comment]
I'm pretty sure that the duplicate `index.html` is not actually a bug: if we're writing a file named `\index.html` then when it searches for an `index.html` on startup, it won't find one, and it will automatically create one for the user.

Let's focus on the leading backslash instead.  NOTE: in filer we hard-code the separator https://github.com/filerjs/filer/blob/develop/src/path.js#L229.  It might be something in node though?

**Comment by humphd** [comment]
I am going to close this, as we've never heard anyone else hit this since it was filed.
