### ISSUE TITLE
Can't scroll list of folders in Move To dialog

### ISSUE THREAD

**Issue by humphd** [mozilla/thimble.mozilla.org#2294]
![screen shot 2017-06-13 at 3 53 12 pm](https://user-images.githubusercontent.com/427398/27101626-8c61ae98-5050-11e7-9a66-2918eaec2d89.png)

We're not doing the right thing with `overflow-y` on the div that holds the directories in the Move To dialog box in Brackets.  This shouldn't be `hidden`.

**Comment by demajkel** [comment]
Try overflow-y: scroll;

**Comment by jschwanebeck** [comment]
I'd like to work on this

**Comment by flukeout** [comment]
Hey everyone, it's scrolling just fine for me on staging in Firefox and Chrome...

![image](https://user-images.githubusercontent.com/25212/27205697-27da3948-51e7-11e7-9bad-42e648fd473b.png)

@jschwanebeck Staging server is on https://bramble.mofostaging.net/ in case you want to check it out too.

**Comment by flukeout** [comment]
I'm guessing that the real issue is that the scrollbar isn't showing when you're using a macbook without a mouse.
