### ISSUE TITLE
Many projects in our DB have multiple files with the same path.

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.mozilla.org#2295]
![image](https://user-images.githubusercontent.com/25212/27102599-a66c9836-503a-11e7-8a0c-b7bd8ea699b5.png)

**Comment by flukeout** [comment]
Seeing this again in another project, this time prompted by a support email

![image](https://user-images.githubusercontent.com/25212/27193716-cc945046-51b4-11e7-99a1-ec244ab45975.png)

![image](https://user-images.githubusercontent.com/25212/27193727-d5ad3684-51b4-11e7-9e30-08e3659a668b.png)

According to the user, the progress they make on the style.css file they are editing is not saved.

**Comment by humphd** [comment]
Is it possible that they have this project open more than once, and both are sending files up, which get added with different ids?

**Comment by flukeout** [comment]
So, check this out, it's a query showing projects that have duplicate files...

![image](https://user-images.githubusercontent.com/25212/27195147-72d933ae-51ba-11e7-905a-a41e607065c1.png)

Pretty staggering!

* More than 19 thousand projects are in this state
* The top offenders have hundreds of the same file
  * For these projects, it's pretty clear that this is some kind of bug in the editor and not a user action

Here's the project with hundreds of index-2.html files. Just posting it to verify that the SQL query above is correct...

![image](https://user-images.githubusercontent.com/25212/27195232-d2750c66-51ba-11e7-80ad-ea4bd7c15680.png)

**Comment by flukeout** [comment]
cc @cadecairos also for his insight.

**Comment by flukeout** [comment]
Can we run a sweet database maintenance task that blows away all extra copies of items with the same path? 

We could pick the one that is "larger" since we don't have ``date_updated`` or ``date_created`` in the ``files`` table. We should!

**Comment by grigoryk** [comment]
@flukeout at the very least consider first adding date_updated, letting that run for a bit, and deleting duplicates based on that. I think you'll end up screwing up less projects that way.

Making sure this won't repeat itself would be a nice thing to plan out - given that the client bug is located and fixed, you'll probably want to alter `path` to be unique right after you run your clean up query... This will also surface other client/backend bugs! (via sql insertion violations).

**Comment by cadecairos** [comment]
> We could pick the one that is "larger" since we don't have date_updated or date_created in the files table. We should!

this feels dangerous, lol. what if code was removed?

**Comment by cadecairos** [comment]
> at the very least consider first adding date_updated, letting that run for a bit, and deleting duplicates based on that. I think you'll end up screwing up less projects that way.

this is a good step.

**Comment by flukeout** [comment]
It's possible that the projects that have multiple files are _already_ screwed up, so removing duplicates might actually help.

**Comment by gideonthomas** [comment]
Plan:
1. On publish, on creation of a file, if the path already exists, execute the update file code path instead and return the updated id. The client will handle it correctly in its existing state.
2. For existing projects, we will handle it when we switch to serverless implementation of storage. Somehow we will decide on which file should be uploaded to the storage provider.
3. No point in adding the date_modified field (I'm surprised we don't have it already) because of our switch to serverless implementation where date_modified will be stored implicitly.
