### ISSUE TITLE
Restrict total project size.

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.mozilla.org#2296]
We've agreed to restrict the size of Thimble projects. So, if the user tries anything that causes the project to go over the maximum file size, we have to block that action. These actions include...

* Upload a file by dragging it in to the file view
* Upload a file via the file upload dialog
* Using the Selfie feature
* Copy & Pasting large amounts of content into an editable file?

We also need a way to indicate that a desired action would cause the project to exceed the maximum file size. We could show some kind of modal with an explanation as well as a link to some other services (dropbox, google drive) people could use to host files.

**Questions**
* What is a good size to restrict to?
  * 3mb?
* What if someone uploads multiple files at once?
  * Do we just import as many as we can and show an error message for the rest?

I'll file a related issue that deals with showing the user how much of the total project size they are using.

**Comment by humphd** [comment]
I've already started a PR for this.

**Comment by RandyIA** [comment]
I've just started working on remixing some of the Web Literacy lesson plans like this one: [Web Literacy Basics II | Fair Use Free-for-All](https://thimbleprojects.org/chadsansing/125881/web-lit-basics-two/session05-fair-use-free-for-all.html#overview). After may attempts to load, it finally does so, but then give this "Project Size Limit Reached"  Any recommendations on how to deal with this issue in Thimble.  Many of the lesson plans will exceed the 5MB limit.

**Comment by flukeout** [comment]
Hey @RandyIA - yeah that's a strange case. It looks like that Thimble project contains all of the lessons, which then exceed the limit. This is unfortunate, and we didn't foresee it. My recommendation would be to split out each lesson into a separate, smaller, project. As it stands, the editing experience when loading this thing up will be quite poor due to the overall size.

Would creating smaller, lesson-specific projects be an option for you?

**Comment by RandyIA** [comment]
@flukeout - thanks for following up so quickly. 👍 Yes I can try create smaller lesson modules.  Unfortunately, since most of the Web Lit lessons were designed before this project size limitation, it's likely I (and others) will have to deal with this issue anytime we need to remix them.  I will post a message to some of the Mozilla people I know, who were involved in creating these lessons and see if they have any recommendations as well.

**Comment by juruhn** [comment]
Awesome tool, clean interface and works like a charm. 
Any plans of extending the maximum size for assets?
I am using it for learning aFrame (it's page suggests Timble) and with some 3D models and textures it quickly adds up.

Cheers,
Juruhn
