### ISSUE TITLE
Add UI to indicate total project size and room left.

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.mozilla.org#2297]
Since we'll be capping total project size, we should also indicate how much someone has used up. We'll want something like...

``1.2 of 3mb used [######_________]``

Probably near or within the FILES column on the left hand side.

**Comment by humphd** [comment]
I'm working on the backend for this in #2296, and I wonder two things:

1) do we want to show this in Brackets or Thimble?
2) depending on the answer to 1), I need to figure out which events matter, and what data we need.

**Comment by flukeout** [comment]
I think we should show it in Brackets, in the file tree specifically. This will reduce the complexity involved in terms of passing the data back and forth. Here's one take on this...

![image](https://user-images.githubusercontent.com/25212/27306882-3e00e844-54fc-11e7-8acb-c3227f23968d.png)

**Comment by humphd** [comment]
I've got the [backend for this all ready](https://github.com/mozilla/brackets/pull/800).  If you want to plug into the places I've marked off with `// TODO` in `UI.js`, this should all work now:

https://github.com/mozilla/brackets/pull/800/files#diff-21109d7bb135d8b29240c262a954659eR374

I give you the formatted size, total, and percentage, as well as hooks for when we've gone over capacity, and when it's been restored.

I think when we go over capacity, we should show a link to a doc that explains the problem.  It could discuss things like:
* ideal file sizes, web page size
* bandwidth limitations and affects on performance of loading content
* sizes of images, etc.
* use of non-web file types

**Comment by flukeout** [comment]
@humphd I'm having an issue where this code only runs after ``npm run build`` in brackets. I'm running just bracktes via ``src/hosted.html``. Changes I make to ``ProjectStats.js`` don't have an effect until I do another build. Is that how this is supposed to work or am I missing a piece of the puzzle?

**Comment by flukeout** [comment]
Okay, as far as I can tell, this is reporting things correctly and firing the "showExceeded" and "hideExceeded" events appropriately. R+ from me. Once this hits, I'll start building the indicator UI on top of it.

**Comment by gideonthomas** [comment]
@flukeout I think that's right, `ProjectStats.js` is in `src/bramble/client`. Any changes made in that folder requires a re-build.

**Comment by humphd** [comment]
This is done in https://github.com/mozilla/brackets/pull/800.
