### ISSUE TITLE
Since Dave hates PDFs with a passion, should we do something special with them?

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.mozilla.org#2298]
For some reason @humphd loves to hate PDFs and wanted an issue filed specifically to address them. I think we should just treat them as any other file in our projects - hold them accountable to whatever maximum file size we decide on.

**The question is...**

* Do we want to just enforce a project size limit
* Or do we also want to enforce a file size limit?
  * We sort of do this for images by resizing them down.

I think it's OK to host some PDFs, as long as they are under ``250kb`` or something like that.

**Comment by ryanwarsaw** [comment]
I agree completely, so allow me to introduce a BRAND NEW file format all together! I'm calling it the **TPDF** (short for Thimble Proprietary Document Format), it's a PDF without the name! We're taking best file format to ever be created, and giving it a new modern flashy name!

With **TPDF** let all your file storage needs be bygones and when you call today and today only, you can get a 50% off life time discount (50% off FREE) and let all your file format needs be bygones. Do you support PNG, JPEG, SVG or any other of those small potato file formats? Well with **TPDF** you can drop them completely, after all who needs a PNG when you've got **TPDF** _the best file format ever._ Ever.

But WAIT! There's more, call today and get our special petabyte format for all of your intensive **TPDF** needs, that's millions of photos in a single PDF for the low low price of _FREE_!

![](https://media.giphy.com/media/5xtDarmwsuR9sDRObyU/giphy.gif)

**Comment by flukeout** [comment]
Hahaha what 👍 👍 :1st_place_medal:

**Comment by humphd** [comment]
I think we can close this, and deal with PDFs via two other fixes: 1) limit total project size; 2) show special UI for non-text types

**Comment by humphd** [comment]
https://github.com/mozilla/brackets/pull/815 fixes this.
