### ISSUE TITLE
Process for Social Sign-In Development

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.mozilla.org#2299]
I'm writing this to clarify some thoughts after a chat that @ryanwarsaw and I had just now and would appreciate input and thoughts from @Pomax @humphd @gideonthomas to make sure that this is on the right track.

**Ryan will...**

* Add a new "Sign In / Create Account" page on Thimble.
* This page will have a form with username / password inputs etc
* This page will talk to the ID server via that Passport technology that we've been talking about
* This page will also have a "Sign in with Google" button
  * Clicking this button will move people off of the Thimble page and onto Google's where they will sign in 
* When this is done, people will no longer go to id.webmaker.org to sign in, but it will all happen on Thimble

Does this sound like the right approach?

The alternative is to add the Social Sign-In stuff to the current page on id.webmaker.org, which seems like a bad idea since we'll be shutting all that down at some point.

Please weigh in on this approach!

**Comment by ryanwarsaw** [comment]
The angle I was coming from while looking at ID stuff was your typical login scheme, where you've got basic authentication then maybe some optional oauth strategies via Passport for 3rd parties.

ID also has some oauth stuff I think, I wasn't sure if you wanted me to make ID a 3rd party or integrate it into Thimble via basic authentication, then continue with the strategy outlined above.

Since ID is only used for Thimble (I think?) it wouldn't make a lot of sense doing it 3rd party, and it might make things a little confusing to the end user vs. doing it somewhat normally.

**Comment by flukeout** [comment]
@humphd @gideonthomas can you weigh in on this stuff?

**Comment by humphd** [comment]
+ @cadecairos.

@ryanwarsaw I agree with the idea of making a `passport-webmaker`, yes.  I'd suggest we hold off on also adding Google for now, though we'll want to do that later.  Until we have a migration strategy, and a way to link people's accounts, I don't think this is a wise idea.

Ideally we should be able to convert Thimble to only use "3rd party" providers, by making our own stuff 3rd party as you suggest, and then we can add others without a lot of trouble.

**Comment by cadecairos** [comment]
+1 passport-webmaker 

@humphd is right, until we have a data migration to associate user rows in publish (username) to email addresses in login.webmaker.org, we won't be able to use a true third party login provider. 

For now we can continue relying on a 1:1 username relation between publish and webmaker for authentication.

**Comment by ryanwarsaw** [comment]
**Update**

The completed version of `passport-webmaker` is currently under review: #2358.

Next step would be wiring it up to fit in the current authentication flow, then if we want we can eventually add other 3rd party login support with relative ease.

**Comment by ryanwarsaw** [comment]
Respective PRs have been filed, there is some migration considerations to factor into in the future, but as it stands we've met the first objective (clean port to passport). Good to close @flukeout ?

**Comment by gideonthomas** [comment]
Thanks @ryanwarsaw!
