### ISSUE TITLE
Can write code PHP.

### ISSUE THREAD

**Issue by xXySniperyXx** [mozilla/thimble.mozilla.org#2300]
Thimble is really a great tool and very useful but it would be really great if you could make sure that one could code in PHP.
Thank you.

**Comment by humphd** [comment]
It's a good suggestions, and has been discussed a few times before (https://github.com/mozilla/thimble.mozilla.org/issues/1583 is one).  We're focused on static web sites with no server-side processing--our goal is to let people write code that can run in their browser with no server, and when we publish, we put project files on Amazon S3 and serve them statically (i.e., there's no server to run the PHP scripts).

Other tools (cloud9, glitch, etc) do offer server-side support, and we're not trying to compete with them.

I'm going to close this, but thank you for filing.  It's a good idea, just not something we are able to do.
