### ISSUE TITLE
Don't add empty color swatches in Image Viewer

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.mozilla.org#2304]
Check out this image below. Our code was only able to extract three unique colors for it, but we're still injecting 5 total DOM elements for the swatches. Two of them are unused and they add a gap below the image. We should only inject as many as we need.

![image](https://user-images.githubusercontent.com/25212/27146940-e49f5f5c-50ef-11e7-8315-48e7bd5413e3.png)

**Comment by humphd** [comment]
That happens here: https://github.com/mozilla/brackets/blob/master/src/editor/ImageViewer.js#L54-L86

**Comment by flukeout** [comment]
Here's the image in the test, the now famous "mouse.png"...

![mouse](https://user-images.githubusercontent.com/25212/27147284-0e92f926-50f1-11e7-99b4-9224abaf1477.png)

**Comment by gideonthomas** [comment]
We hardcode 5 elements here: https://github.com/mozilla/brackets/blob/master/src/htmlContent/image-view.html#L7-L28

**Comment by flukeout** [comment]
Addressed in PR https://github.com/mozilla/thimble.mozilla.org/issues/2304

**Comment by gideonthomas** [comment]
@flukeout you linked to this issue lol

Fix in mozilla/brackets#806
