### ISSUE TITLE
Project creation in Thimble

### ISSUE THREAD

**Issue by pakTech786** [mozilla/thimble.mozilla.org#2306]
I want to  trace the flow where project is created or updated.I explored browser's localstorage but cannot clearly figure out that project where i am changing the code. I can see <a href="https://github.com/mozilla/thimble.mozilla.org/tree/master/default">Default folder</a>.I tried changing it and then restarted server but still the anonymous project is as it was in previous state.i kept only style.css in default but my editor has index.html,style.css and tutorial.css too.i am running only thimble and brackets.other services and postgres db isnt running.

**Comment by humphd** [comment]
Try running `npm run restart-server` after you make your changes.

**Comment by nailaandleeb** [comment]
i am not using vagrant.deployed manually

**Comment by gideonthomas** [comment]
where are you making the changes in the default folder? And did you create a new project when you restarted the server?

**Comment by nailaandleeb** [comment]
i deleted index.html file and there is only style.css.and create new project from scratch is clicked every time.but it is persisting previously made changes instead of loading project from default folder.

**Comment by gideonthomas** [comment]
@nailaandleeb we automatically create an index.html file if it doesn't exist because the editor needs an html file to preview (right @humphd?). Now, if you delete the css file and then create a new project after restarting the server and you see that the css file still pops up in the new project, that would be interesting.

**Comment by nailaandleeb** [comment]
Yes it is interesting that empty folder of default/empty-project and default/stay-calm still showing index.html and style.css files in editor.And also creation of new tutorial.html persists after restart.

**Comment by humphd** [comment]
I'm going to close this for now, and if you want to follow-up on it, please file a new bug.
