### ISSUE TITLE
Add support for auto downsizing non-animated GIFs with ImageResizer

### ISSUE THREAD

**Issue by humphd** [mozilla/thimble.mozilla.org#2307]
In https://github.com/mozilla/brackets/pull/794 we're adding auto-resize code, but it currently only works for PNG and JPG files.  For the case of a GIF, we need to know if it's animated or not.

We could possibly adapt this code to check the buffer when it's a `.gif` and see if it's animated:
 https://github.com/mailcharts/animated-gif-detector/blob/master/index.js

**Comment by flukeout** [comment]
@humphd Here is a count vs filesize (in kb) of .gif images from our files DB

![image](https://user-images.githubusercontent.com/25212/28385933-c49cb2b8-6c7e-11e7-9971-4717431949fb.png)

Looking at some random .gif filenames over 1mb in the publishedFiles table, it seems like a lot of them are animated (judging by the titles) - but we could do a more thorough investigation.

**Comment by humphd** [comment]
I've got a student, Azusa Shimazaki @azusaaz, who wants to work on this.  I'm assigning it to her now.

**Comment by azusaaz** [comment]
Hello, I am that student Azusa Shimazaki @azusaaz!
Thank you for letting me join the project!
I am glad to try this Issue!

**Comment by humphd** [comment]
@azusaaz I'd start with the other bug first, and come back to this one.  When you're ready to do it, let me know and I'll give you some ideas here.

**Comment by azusaaz** [comment]
@humphd I see. Thank you!

**Comment by azusaaz** [comment]
@humphd I'm ready! The cord I should touch would be in "bracket" side?

**Comment by humphd** [comment]
@azusaaz awesome!  Yes, you are going to want to do this change in the Brackets code only (nothing will need to happen in Thimble).  Here's how I'd approach this work:

1. Start by finding two large `.gif` files (i.e., more than 250K): one that is animated, and one that is not
1. Confirm that you can drag-and-drop both files into the filetree.
1. Alter the `isResizableImage()` function to also work for `.gif` extensions, see https://github.com/mozilla/brackets/blob/master/src/filesystem/impls/filer/lib/content.js#L141
1. Next, alter the code for [ImageResizer.js](https://github.com/mozilla/brackets/blob/master/src/filesystem/impls/filer/lib/ImageResizer.js).  We need to inspect the `path` argument, see if it's a `.gif` and then figure out whether this is an animated GIF or not.  To do that, you are going to need to either use or adapt the code in https://github.com/mailcharts/animated-gif-detector/blob/master/index.js to inspect the first few bytes of the `data` for this image file, and see if it contains the animation markers. 
1. If the `.gif` is animated, we should just return it unchanged.  Otherwise, we can safely try and resize it.
1. Once it's resized, we'll need to re-encode it as a GIF.  I'm not 100% sure the best way to do this, we might need to use a JS library that does it like https://github.com/deanm/omggif if we can't do it natively via `canvas` and the browser.

See if what I say above makes sense, and ask any questions you have.

**Comment by azusaaz** [comment]
@humphd  Thank you for the detail! I'll try the steps!

**Comment by azusaaz** [comment]
@humphd I've forgotten to make a branch! so I have a question for the start point.

This issue page is on "thimble", but I need to edit "bracket".
In this case, Could I use the issue number "2307"? and push to "bracket" repo at last,?

for example, inside of my local "bracket",
> git checkout -b issue-2307 and pull    // for the start
> git push origin issue-2307  //for the end
is that a correct way?

**Comment by humphd** [comment]
@azusaaz you will do everything against the Brackets repo, even though it's filed here:

```
// In Brackets
git checkout master
git pull upstream master
git checkout -b thimble-issue-2307
// do your fixes
git push origin thimble-issue-2307
```

**Comment by azusaaz** [comment]
@humphd oh, I see. Thank you!

**Comment by azusaaz** [comment]
@humphd Is that not necessary to resize "animated" gif in this issue?

**Comment by humphd** [comment]
@azusaaz correct, we do not need to resize animated GIFs.

**Comment by azusaaz** [comment]
@humphd omg! great! Thank you!

**Comment by azusaaz** [comment]
@humphd 
Hi, my pull request went to bracket side.
https://github.com/mozilla/brackets/pull/913

I guess there is a problem. I appreciate if you could review this.
