### ISSUE TITLE
Decide how to deal with package-lock.json files in Thimble, Brackets, etc

### ISSUE THREAD

**Issue by humphd** [mozilla/thimble.mozilla.org#2311]
Especially in Brackets, there are now about a dozen of these (extensions can have their own `package.json`).  Should we be committing these files?  I'd like to figure out a project-wide strategy.

**Comment by ryanwarsaw** [comment]
It's intended to be committed into repositories, it's basically like Yarn's lock file just for NPM.

**Comment by humphd** [comment]
Data point: https://github.com/mozilla/publish.webmaker.org/pull/258

**Comment by flukeout** [comment]
@humphd will add these to the .gitignore in both repos.

**Comment by humphd** [comment]
Fix happening in https://github.com/mozilla/brackets/pull/845, closing here.
