### ISSUE TITLE
Move Thimble server out of Vagrant

### ISSUE THREAD

**Issue by humphd** [mozilla/thimble.mozilla.org#2312]
We wanted to move [Thimble to use node LTS](https://github.com/mozilla/thimble.mozilla.org/pull/1714), but doing it in Vagrant is hard because some other services can't migrate up yet.  What we're going to do instead is update our docs and workflow to move Thimble outside Vagrant, and only run the dependent apps (publish, id, login, ...) inside Vagrant.  This will hopefully make it a bit easier to understand what's happening with Thimble for new devs (similar to how we run Brackets).

**Comment by humphd** [comment]
Let's do this with Webpack work.

**Comment by humphd** [comment]
@gideonthomas am I right that this is actually done now?  Can we close this?  If so, please do.

**Comment by gideonthomas** [comment]
Yep
