### ISSUE TITLE
[Staging] Renaming a file keeps a copy of the original after reload.

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.mozilla.org#2315]
Steps to reproduce
* Create a new project
* Rename the index.html file to blam.html (or whatever)
* Reload the editor
* In the file column, you'll see the original and the renamed html file

<img src="https://user-images.githubusercontent.com/25212/27351755-3c98cae6-55b3-11e7-8810-c5f5a069277a.png" width="300" />

**Comment by flukeout** [comment]
This also happens with deleted files by the way. Try to delete a file, and then reload the editor. It's back!

**Comment by humphd** [comment]
I'm pretty sure this is us automatically creating an `index.html` file when the project doesn't have one.

**Comment by flukeout** [comment]
@humphd Yeah sorry, maybe index.html wasn't the best test scenario, but this happens to ALL files that are renamed, as well as files that are deleted, so it's not isolated to our ``index.html`` logic.

**Comment by humphd** [comment]
I tried with the `style.css` file, and I'm not able to reproduce this, whether logged in or anonymous.
