### ISSUE TITLE
[Staging] Number of files streamed in network tab in dev tools doesn't match project

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.mozilla.org#2317]
See below, I have an 8 file project, but the network tab only shows 5 unique files being streamed in.
Some of these files are the ones that have been renamed (and magically came back) #2315 - so maybe that's part of the issue?

![image](https://user-images.githubusercontent.com/25212/27352365-532696ba-55b5-11e7-889a-d3f412d784c5.png)

**Comment by humphd** [comment]
I think this is related to #2315, and should potentially get fixed by https://github.com/mozilla/thimble.mozilla.org/pull/2319.

**Comment by gideonthomas** [comment]
@flukeout is this still an issue?

**Comment by flukeout** [comment]
Oh, it's an issue alright @gideonthomas
