### ISSUE TITLE
[Staging] Super fast refresh after rename or delete still causes duplicate file.

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.mozilla.org#2321]
STR
* Rename a file or delete a file
* Immediately refresh after you do it
* Deleted/renamed file is still there

So I guess there is some timing issue where we remove the file from the file-tree, but don't have enough time to send the event to the server or update it in the indexedDB? Can we delay updating the UI until we've done so?

![duplicates](https://user-images.githubusercontent.com/25212/27358337-fd0eea8c-55ca-11e7-964b-ad8914ab8db0.gif)

**Comment by humphd** [comment]
Between you doing a file operation, and it actually completing, a whole bunch of asynchronous calls have to complete, including:
* process the file change in brackets
* update the URL cache
* send the file operation over the iframe via `postMessage`
* actually do the indexeddb change
* return the result over the iframe via `postMessage`
* update `localStorage` with sync info

Any of these can fail to complete if you immediately hit refresh.  I'm not sure how you'd code around this: if you kill the power while a word processor or photoshop are working, it will also do bad things to your files.

**Comment by flukeout** [comment]
No, I get that - I guess that's a lot of moving parts so maybe we can just ignore this. It's an edge case that I guess it was nice if we could recover from. Maybe we could delay making the update in the UI until we hear back that yes, the file has been deleted? Happy to close it too, it's fairly fringe

**Comment by flukeout** [comment]
@humphd - the other thing I wanted to mention is that I feel like making this happens throws the project into a weird state, because the number of files streamed (in the network tab, filtering for ``/files``) no longer matches the stuff in the project. Is that an issue?

After renaming and quick-refreshing, I'm left with 3 files in the filetree...

<img src="https://user-images.githubusercontent.com/25212/27359211-6a1a1cce-55cf-11e7-8cb4-ce47f5210eb3.png" width="200"/>


and only 2 files visible in teh network tab...

![image](https://user-images.githubusercontent.com/25212/27359208-65976efe-55cf-11e7-8aa8-938b67fda968.png)

Is this something we should be worried about?

**Comment by humphd** [comment]
My guess, in the case above, is that you have 2 files streaming in (`style.css` and `zingo.html`) and it automatically creates `index.html` because there isn't one, which means you end up with 3 files, where only 2 get loaded.

You can check the `Response` tab in your Dev Tools > Network to see what's in the `meta` (should list all the paths and IDs), and what each file was:

![file-contents](https://user-images.githubusercontent.com/427398/27359385-8054ecc0-55e9-11e7-9609-df8f6c7fb996.gif)

**Comment by flukeout** [comment]
In addition, check this out...

https://thimbleprojects.mofostaging.net/flukeout/163/

A published project with 3 files. But only two streamed in...

![image](https://user-images.githubusercontent.com/25212/27359773-741e693e-55d2-11e7-94eb-4975e99ca5fd.png)

The published version doesn't have the index.html file. 

![image](https://user-images.githubusercontent.com/25212/27359798-924772fc-55d2-11e7-9958-677c7b534bc5.png)
