### ISSUE TITLE
[Staging] Images dragged in to project within a .ZIP archive are not resized.

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.mozilla.org#2322]
I've got a .zip with a few images that are larger than 250kb. When I drag the folder in, none of the images get resized when they are imported. Like this one...

![image](https://user-images.githubusercontent.com/25212/27359367-3b7da0d8-55d0-11e7-921d-50858ac741c5.png)

**Comment by gideonthomas** [comment]
@humphd is this still an issue or did we patch this?

**Comment by flukeout** [comment]
I'll test this now in prod.

**Comment by flukeout** [comment]
This works now in Prod, so assumed we've fixed it and didn't close the issue...

![image](https://user-images.githubusercontent.com/25212/28385811-4847f6d2-6c7e-11e7-830a-52f71e352432.png)
