### ISSUE TITLE
[Staging] Failed saving error... 

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.mozilla.org#2326]
Was just making random edits to the index.html page in this project and suddenly started seeing the failed saving error...

![image](https://user-images.githubusercontent.com/25212/27361289-2a7ab0d6-55db-11e7-8b5e-ac26a18b2c3f.png)

Will investigate more.

**Comment by flukeout** [comment]
After reloading, looks like something is down in the back end?

![image](https://user-images.githubusercontent.com/25212/27361303-412b7c66-55db-11e7-9a65-bb34ffd355d3.png)

Getting the Black screen in the editor.

**Comment by flukeout** [comment]
cc @gideonthomas - this started happening about 5:10 PM PST for reference.

**Comment by humphd** [comment]
Error comes from https://github.com/mozilla/thimble.mozilla.org/blob/master/public/editor/scripts/project/metadata.js#L266, and means we didn't really have error info, so yeah, probably pretty bad.

**Comment by gideonthomas** [comment]
Are we still seeing this?

One of the dynos might have gone down.

**Comment by flukeout** [comment]
Not seeing it anymore. Closing.
