### ISSUE TITLE
[Latest Master Brackets] Uploaded image 404s after refresh.

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.mozilla.org#2328]
Running brackets from ``localhost:8000`` - I upload a file (less than 250kb). It shows up fine, but when I refresh the browser, the image 404s...

![image](https://user-images.githubusercontent.com/25212/27397128-31e83c14-566a-11e7-8af4-d9603246a635.png)

Log...

<img src="https://user-images.githubusercontent.com/25212/27397155-4096f782-566a-11e7-9965-eb9105e36773.png" width="300" />

File I used (but seems to be an issue with all images)

![cat_mic](https://user-images.githubusercontent.com/25212/27397161-45691cea-566a-11e7-97b3-43c45b56385d.jpg)

This doesn't happen when running full Thimble via ``localhost:3500``.

cc @humphd

**Comment by flukeout** [comment]
This seems to happen to at least one of the images in a project. I've got another setup now with 3 images, and one of them is often 404-ing. It's not always the same one, and sometimes all of them work.

**Comment by humphd** [comment]
This is fixed on my service worker PR for Brackets, closing.
