### ISSUE TITLE
OK and Cancel actions not in the same spot within modals.

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.mozilla.org#2332]
Move to dialog...

![image](https://user-images.githubusercontent.com/25212/27409903-ced1aa82-5698-11e7-990b-cd862a5ae795.png)

Delete file dialog...

![image](https://user-images.githubusercontent.com/25212/27409910-dab77a7a-5698-11e7-8b26-80b8111ec56a.png)

Let's go with a [Cancel] [Confirm] pattern.

**Comment by pranavkumar2015** [comment]
The thing that you intend to do can be done directly through the UI (frontend), with the functionalities editing in the backend.
