### ISSUE TITLE
Image Viewer: "LightMuted" swatch always comes back as undefined.

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.mozilla.org#2333]
Pretty much any image I try, this swatch is always undefined. It's supposed to try to give us 6 swatches, but never seems to give more than 5.

![image](https://user-images.githubusercontent.com/25212/27410445-7804ce24-569c-11e7-8f4f-3758e59a6d4e.png)

**Comment by humphd** [comment]
Now that you've added code to only show swatches that have values, do we care about this anymore?  When it exist, we'll show it; when it doesn't, we won't.  Seems fixed to me.
