### ISSUE TITLE
Remove double-click to rename file feature?

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.mozilla.org#2334]
While seemingly handy, I'm having two issues on my end...

* I can't get it to work reliably
* Sometimes I trigger it accidentally

It's a hard to find feature that sometimes comes up by accident. And since we will also be adding an affordance for the right click menu (in progress) then I think we can nuke this.

Thoughts @Pomax @humphd - can you reliably double-click to edit the filename?

**Comment by humphd** [comment]
I often end-up renaming when I just want to select, so I'm fine to remove this.  They have a bunch of hacks in https://github.com/mozilla/brackets/blob/master/src/project/FileTreeView.js to deal with it based on timers, and I suspect it's just buggy.

**Comment by flukeout** [comment]
Sounds good to me!

**Comment by hkirat** [comment]
I think there is a functionality to rename on a single click as well.
Which is what might be causing confusion.
Reference: https://github.com/mozilla/brackets/blob/master/src/project/FileTreeView.js#L441 and https://github.com/mozilla/brackets/blob/master/src/project/FileTreeView.js#L417

If we remove this, rename would take place only on a double click. Would that be a better option than removing it completely?

**Comment by flukeout** [comment]
Addressed in referenced PR
