### ISSUE TITLE
[Collaboration] Prototype 1 - Multi-file infrastructure

### ISSUE THREAD

**Issue by gideonthomas** [mozilla/thimble.mozilla.org#2335]
## Overview
The bare-bones infrastructure for having multiple files synced across collaboration sessions at the file system level.

## Goals
1. Deal with unique rooms - Having unique sessions based on url
2. Investigate WebRTC server requirements
   - What kind of servers do we need?
   - Do we need to modify the server logic? If so, should we fork the repo and publish to npm.
   - How do we hook it up to simplewebrtc?
   - Add the server as a module in brackets
3. Add code to pass file events
   - Allow identifying files by path
   - Allow identifying what type of event it is + payload (create, update, delete, rename, folder rename)

## Deliverable
A collaborative environment enabled on Brackets where you can join a unique session via url and we receive all file events logged to the console.

**Comment by hkirat** [comment]
Unique rooms implemented in #820.
However, #801 must be merged before this.

**Comment by hkirat** [comment]
Shifting WebRTC server development going on in [#824](https://github.com/mozilla/brackets/pull/824)
