### ISSUE TITLE
Create a FontViewer editor, so people can "open" font files

### ISSUE THREAD

**Issue by humphd** [mozilla/thimble.mozilla.org#2339]
People [put font files in projects](https://github.com/mozilla/thimble.mozilla.org/issues/1326#issuecomment-307450487), but we offer no way to look at them in the editor.  We could probably follow the lead of https://github.com/TomMalbran/brackets-fonts-viewer and build a `FontViewer`, similar to the `ImageViewer` we have now, and the [`VideoViewer`](https://github.com/mozilla/brackets/pull/807) @flukeout is building.

Part of https://github.com/mozilla/thimble.mozilla.org/issues/2270

**Comment by humphd** [comment]
@pomax, this seems like something you might have ideas on.  If you have any tips for what we might include/do here, please add them.

**Comment by humphd** [comment]
Fix for this happening in https://github.com/mozilla/brackets/pull/819.

**Comment by Pomax** [comment]
what kind of UI are you thinking here? A kind of fontbook style "scroll through all the supported characters"? Given that webfont support is baked into browsers, it feels like the brackets extension is super overkill. We could simply make an html file template that uses a css font-family matched to the font file itself, which then makes the browser rendering all that text with the font applied.

**Comment by flukeout** [comment]
That sounds like a good idea @Pomax - an extra benefit of having a view like that is the ability to find, and then copy and paste special characters and stuff like that.

**Comment by humphd** [comment]
Let's continue this discussion in https://github.com/mozilla/brackets/pull/819 please.

**Comment by humphd** [comment]
This was merged, any new discussion should happen in new bugs (I think some already got filed).  Closing.
