### ISSUE TITLE
".ogv" and ".webm" video file types not supported, but should be. 

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.mozilla.org#2349]
Try to drag in an ``.ogv`` video file. It's the OGG video format and one of the ones supported by HTML5 natively. 

Test files below...

* [small.ogv.zip](https://github.com/mozilla/thimble.mozilla.org/files/1126269/small.ogv.zip)
* [small.webm.zip](https://github.com/mozilla/thimble.mozilla.org/files/1126280/small.webm.zip)

When I drag either into the sidebar I see...

![image](https://user-images.githubusercontent.com/25212/27888581-a89a8b96-619b-11e7-9f48-3adf2cd6bdfd.png)

**Comment by humphd** [comment]
I fixed this by removing type checks in favour of file size checks in Brackets.
