### ISSUE TITLE
Emit events other than codemirror events while collaborating

### ISSUE THREAD

**Issue by hkirat** [mozilla/thimble.mozilla.org#2353]
Along with the codemirror events that are sent while collaborating, there are a few others that we need to tackle: 

 - [x] Create an empty text file
 - [x] Delete a file
 - [x]  Rename a file

**Comment by humphd** [comment]
Checkout `filesystem/FileSystem.js` and https://github.com/mozilla/brackets/blob/master/src/filesystem/impls/filer/FilerFileSystem.js#L423, which allow you to setup watches on dirs/files.

**Comment by hkirat** [comment]
Found these events that are fired on adding and deleting files: https://github.com/mozilla/brackets/pull/835/files#diff-172c2aa71bb7326386a85125ccd13603R47

Tried looking into watchers. Could you elaborate a little what purpose they serve @humphd ?

**Comment by hkirat** [comment]
Something similar here : 
https://github.com/mozilla/brackets/pull/836/files#diff-172c2aa71bb7326386a85125ccd13603R47

**Comment by hkirat** [comment]
Closed via [#858](https://github.com/mozilla/brackets/pull/858)
