### ISSUE TITLE
Review webmaker passport

### ISSUE THREAD

**Issue by gideonthomas** [mozilla/thimble.mozilla.org#2358]
Let's make sure https://github.com/ryanwarsaw/passport-webmaker has everything we need for integration into Thimble.

**Comment by ryanwarsaw** [comment]
Documentation is going to make this an easier task to do, been slowly chipping away at it for a little while, should be done soon.

**Comment by gideonthomas** [comment]
Ok, no worries!

**Comment by ryanwarsaw** [comment]
Documentation has been completed, if someone wants to go ahead with this task you've got the green light. I'm currently buried with school work so I can't do any login work for the next 7-10 days so feel free to take your time on this.

**Comment by gideonthomas** [comment]
Thanks for the work @ryanwarsaw. @cadecairos would you be able to take a look at that in the next two weeks?

**Comment by cadecairos** [comment]
yup

**Comment by ryanwarsaw** [comment]
Code is located here: https://github.com/mozilla/passport-webmaker, the original link is dead.

**Comment by ryanwarsaw** [comment]
Hey @cadecairos I know you were working on this a while back, I wasn't sure if you completed it though. There's no rush, I'd like to finish a review on it before landing the SSO work though.

**Comment by cadecairos** [comment]
@ryanwarsaw sorry for the silence on this for a while. I'll add it to my list and make sure I complete what I started.

**Comment by ryanwarsaw** [comment]
@cadecairos DW about it, I'm held up with MozFest stuff and there is some other stuff to review so you've got at least a month before I need to come to a conclusion on this.

**Comment by cadecairos** [comment]
With the winding down of thimble on the horizon, I don't think we'll have the bandwidth to integrate passport login. Going to close this out, but if someone wants to do the passport integration, please submit a PR.

**Comment by ryanwarsaw** [comment]
hey @cadecairos i actually already wrote the passport integration for it, it syncs right into the `id.webmaker.org` component. Needed some review but this is basically a drop-in replacement.

see: https://github.com/mozilla/passport-webmaker
