### ISSUE TITLE
Standardize File Viewer UI & Content

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.mozilla.org#2361]
Placeholder issue for once the Video Viewer and upcoming Audio Viewer lands, we'll want to make sure that the following elements are cohesive

**Viewers**
  * PDF
  * Audio
  * Video
  * Image
  * Font
  * ...

**Common elements**
* Viewer header, to include
  * File type, "Video File", "Audio File", etc...
  * File details
    * media size, file size, other details
* Code samples that can be used in HTML and/or CSS where applicable
* Unified order of elements & styling for dark and light themes
* ...?

This might also be a good time to pull out common *-viewer styles and put them all in one place somewhere so we have just one stylesheet to maintain.

**Comment by flukeout** [comment]
**Notes while working on this**

* Round File sizes to whole KB
* Replace (width) and (height) with width and height icons

**Comment by humphd** [comment]
This is closable now, right @flukeout?

**Comment by flukeout** [comment]
Correct.
