### ISSUE TITLE
PDF Viewer in dark theme has an unneeded border

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.mozilla.org#2362]
See below, the border divides the viewer from the selected file indicator. Let's get rid of it.

![image](https://user-images.githubusercontent.com/25212/28139335-bf24362e-6708-11e7-8a8a-f9b1e5b48b7f.png)

**Comment by humphd** [comment]
Fix for this in https://github.com/mozilla/brackets/pull/854
