### ISSUE TITLE
Keeping Track of the History of a project

### ISSUE THREAD

**Issue by whitecat** [mozilla/thimble.mozilla.org#2367]
Keeping track of changes for a project or file is helpful. For example if a student makes lots of changes and then the next day wants to undo them all there is no simple way.

I would like to see some way to look at history of a file and see the changes that happened.

**Comment by gideonthomas** [comment]
This is currently outside the scope of work we can do. However, as we are in the process of implementing collaborative features in Brackets, the logic used in it could serve as a foundation to add versioning features. Thanks for the suggestion!
