### ISSUE TITLE
Debugger

### ISSUE THREAD

**Issue by nadeemramsing** [mozilla/thimble.mozilla.org#2368]
Right now, the debugger keyword cannot be used as breakpoints.

**Comment by humphd** [comment]
This works for me, can you give me some more info on what you're trying and what's happening/not-happening?

**Comment by humphd** [comment]
I'm going to close this, but if you find you're hitting it a lot/again, please let us know.

**Comment by nadeemramsing** [comment]
Sure.

Debugger is working, but it does resume automatically sometimes.
When it does happen, I write it twice and it stops at the second one.

E.g:
```
import { Component, NgModule, VERSION } from '@angular/core'
import { trigger, state, style, transition, animate } from '@angular/animations'

@Component({
selector: 'app-body',
template: `
<h2>Hello <span [@brand]="'red'">{{name}}</span> {{version}}</h2>
<h5>Developer: {{developer}}</h5>
`,
animations: [
trigger('brand', [ state('red', style({ color: '#DD0031' })), transition('void <=> *', animate('500ms')) ])
]
})
export class AppComponent {  
private version: string;
private name: string;
constructor() {
this.name = 'Angular'
this.version = VERSION.full
this.developer = 'Nadeem Ramsing'
debugger //resumes automatically
debugger //stops
}
}
```

Not a major issue though; just need to write it twice if it happens.

**Comment by humphd** [comment]
Is this in Chrome?  I've noticed the same in the Chrome dev tools in general recently, and not related to Thimble.  It's odd that it would resume like that.
