### ISSUE TITLE
HTML & CSS files in downloaded ZIP archive are blank.

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.mozilla.org#2369]
Got this via email and just confirmed it myself. It looks like HTML & CSS files are blank when downloaded via the Download ZIP feature. Will test other file types. Images seem to download fine.

cc @humphd

**Comment by humphd** [comment]
Fixed in Brackets.  We should probably get this rolled out to prod soon.  CC @gideonthomas.
