### ISSUE TITLE
The mozilla logo in the footer is black in Firefox

### ISSUE THREAD

**Issue by TheoChevalier** [mozilla/thimble.mozilla.org#2371]
The moz://a logo in the footer is black in Firefox (tested on Nightly), and white in Chrome. I assume it should be white in all browsers

**Comment by gideonthomas** [comment]
bleh, thought we fixed this! Thanks for catching it!

**Comment by TheoChevalier** [comment]
In the same fashion, the recently added MozFest SVG is also busted on Firefox

**Comment by flukeout** [comment]
Thanks for catching these @TheoChevalier - I've addressed them in PR #2376
