### ISSUE TITLE
Fix margins around project size panel

### ISSUE THREAD

**Issue by humphd** [mozilla/thimble.mozilla.org#2372]
In Chrome especially, it's really easy to cover the new project size panel with the status bar:

![screen shot 2017-07-17 at 2 11 56 pm](https://user-images.githubusercontent.com/427398/28282899-124d56ce-6afa-11e7-9a3a-8200fb6c53ad.png)

**Comment by ArtanisAce** [comment]
Hi! I'd like to start working on this as my first bug (hope is good one) ;)

**Comment by ryanwarsaw** [comment]
@ArtanisAce It's all yours, if you have any questions just let us know. Also if you haven't already, check out the README and CONTRIBUTING files, it's got a bunch of helpful information for new contributors, and feel free to join us in Mattermost (#Thimble channel).
