### ISSUE TITLE
Add "Binary Viewer" for files that can't be displayed / edited.

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.mozilla.org#2374]
What do we want here...

* File Type
* File size
* Some sort of message "We can edit this file type"
* Possible actions
  * Open in editor as text
  * Download
  * Open in a tab??
* Possibly, we can ask if the user wants to edit the file every time they open it. So that way they don't get stuck in a 'weird' state.

**Comment by humphd** [comment]
I'll start this rolling, and get @flukeout to help me finish.

**Comment by humphd** [comment]
I'm doing this in https://github.com/mozilla/brackets/pull/851.
