### ISSUE TITLE
Webpage doesn't process or render in preview

### ISSUE THREAD

**Issue by AllanFox** [mozilla/thimble.mozilla.org#2381]
Webpage isn't getting rendered or processed in the preview section. The preview section shows a URL to https://mozillathimblelivepreview.net/bramble/production/dist/vfs/31986/projects/1069428/index.html
link where the page is actually getting displayed. This problem started few days ago
![thimble_screenshot](https://user-images.githubusercontent.com/5771865/28325047-84c69a2a-6bfa-11e7-9eb4-d938236ef339.png)

**Comment by humphd** [comment]
Hey @AllanFox, sorry you're running into this issue.  This is not something I've run into before, and I'd like to try and understand/fix it.  Can you tell me:

* which OS and browser (also version) you're using?
* Is this project published somewhere, and can I remix it to test locally?

**Comment by AllanFox** [comment]
* The OS I am using is Ubuntu 16.04 LTS (32 bit)
* I use 2 browsers 
   * Firefox 54.0
   * Chromium 59.0


This project isn't published somewhere else, so please remix it and test it locally if needed.

**Comment by gideonthomas** [comment]
@humphd looks like the project id is: 1069428. Let me know if you need the files for it...I can send it to you over chat.

**Comment by humphd** [comment]
@AllanFox we've had another user tell us about a similar thing, and it turned out to be a cache issue, and multiple refreshes fixed the issue.  I'd suggest you close all but 1 tab containing Thimble, and refresh it a few times.  It likely needs to re-download updated code for the editor, and we cache that in a Service Worker, which can get "stuck" sometimes.  Let us know what happens.

**Comment by AllanFox** [comment]
Thanks for helping. After refreshing 7 times it finally started working in Firefox browser. Not working in chromium even after 12 refreshes. I shall continue using Thimble on Firefox for now :)

**Comment by humphd** [comment]
@AllanFox so weird.  Here's something you can try in Chromium:

![screen shot 2017-07-22 at 11 10 56 am](https://user-images.githubusercontent.com/427398/28492298-8e196c7a-6ece-11e7-96e4-be7219ea644d.png)

In Dev Tools, go to the Application tab, and then Clear Storage on the left.  If you **uncheck** the IndexedDB option, then click Clear Site Data, it will make sure you don't delete your files.  After this, a refresh should re-install the service worker.

**Comment by AllanFox** [comment]
Thanks for the help again. Now the Thimble preview works in Firefox as well as Chromium.

**Comment by surfscoter** [comment]
This is happening on Windows 10 and Chrome.  Trying to clear cache and refresh but it is not working.

**Comment by flukeout** [comment]
We've got a PR in progress that tries to address this by showing a special page so I'll close this issue for now. @surfscoter - are you still experiencing this?
