### ISSUE TITLE
Image files won't load in a published project.

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.mozilla.org#2385]
Project in question...

* https://thimbleprojects.org/dgregory10561/199996/

Has a file called ``neptune.png`` in the ``publishedFiles`` table...

![image](https://user-images.githubusercontent.com/25212/28336768-103db4c8-6bb8-11e7-81cd-7eea4fe09bcd.png)

But it won't load...

![image](https://user-images.githubusercontent.com/25212/28336756-07b84714-6bb8-11e7-96e0-4a8185d9e13f.png)

When remixing the project, the image files appear in the file tree.

![image](https://user-images.githubusercontent.com/25212/28336742-f6212b2e-6bb7-11e7-8ea3-8853e7b276a8.png)

**Comment by gideonthomas** [comment]
hmm none of those files are on s3. That's weird!

**Comment by flukeout** [comment]
Weird i wonder if it has something to do with auto-resized images not making it.

**Comment by flukeout** [comment]
I'll do some testing.

**Comment by flukeout** [comment]
However, when you remix it, those files make it into the project.

**Comment by humphd** [comment]
It looks like the upload from the publish server to S3 didn't work, and we got a 500, resulting in the records existing in the db, but not in the published bucket.

**Comment by flukeout** [comment]
Should we close this then @humphd @gideonthomas - or is there something we can do to keep this from happening in the future?

**Comment by humphd** [comment]
Yeah, let's close this and monitor.
