### ISSUE TITLE
Audio Viewer - Changing Audio Settings of one viewer affects a different one.

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.mozilla.org#2392]
Steps to reproduce
* Add two different sound files to your project
* Open one of the viewers and change the 'autoplay setting' a few times
* Open the other viewer and do the same
* You'll notice that one of the viewers is affecting the other sound file, and not the one you are currently looking at

![image](https://user-images.githubusercontent.com/25212/28439371-7717aa9c-6d56-11e7-85df-dd6922dfd3fb.png)

Might be an issue with some selectors that I'm using, maybe they're not being scoped properly.

**Comment by hkirat** [comment]
I'm not sure if they are effecting each other. 
I think everytime you shift away from one sound file, its checkboxes are refreshed (the loop, autoplay and muted checkboxes).

**Comment by humphd** [comment]
I'm not able to reproduce this using two audio files.  There must be some other step required that I'm missing.

**Comment by flukeout** [comment]
Will try to reproduce.

**Comment by flukeout** [comment]
Closing as I'm not noticing any issues like what I've described in the original description.
