### ISSUE TITLE
Add logic to send files via WebRTC

### ISSUE THREAD

**Issue by hkirat** [mozilla/thimble.mozilla.org#2395]
WebRTC allows sending binary files. 
However, It expects FileList object as an input.
Is this stored somewhere in the File object? Or can we create it somehow?

**Comment by humphd** [comment]
I don't know WebRTC, so I'm not sure the answer.  A [`FileList` is read-only](https://dxr.mozilla.org/mozilla-beta/source/dom/webidl/FileList.webidl), so we can't really make one programmatically.

Is there a way to work with `File` objects or `Blobs` or something?

**Comment by gideonthomas** [comment]
Doesn't webrtc allow you to send ArrayBuffers using its binary data channel?

**Comment by hkirat** [comment]
I think blobs might be the way to go. WebRTC is failing at this point:

**Comment by hkirat** [comment]
`  _webrtc.getPeers()[0].sendFile(new Blob ([addedFile._contents]));` works.

Does the convertToBlob function exist somewhere. Also this ^ doesn't allow sending any metadata along to identify the file to the peer receiving it.


Any way to do that?

**Comment by hkirat** [comment]
This is where I reached on this issue: 

Here is a simple example how filetransfer should work using WebRTC: 
https://simplewebrtc.com/filetransfer

The function following function can be used to send files: 
peer.sendFile(parameter)

The parameter expected is a file/blob object. However, trying various implementations, I wasn't able to get the the contents of the file object right.
I've tried: 
```js
FilerUtils.readFileAsBinary(addedFile._path, function(err, fileInBinary) {
  var file = new File(fileInBinary, Path.relative(StartupState.project("root"), addedFile._path));
  peer.sendFile(file);
});
```

**Comment by humphd** [comment]
You just need to put that binary data into a Blob:

```js
FilerUtils.readFileAsBinary(addedFile._path, function(err, buffer) {
  // NOTE: if you care about the content type, use https://github.com/mozilla/brackets/blob/master/src/filesystem/impls/filer/lib/content.js#L185
  var blob = new Blob([buffer], {type: "application/octet-stream"})
  var file = new File(blob, Path.relative(StartupState.project("root"), addedFile._path));
  peer.sendFile(file);
});
```

**Comment by hkirat** [comment]
Thanks for the reference @humphd. It works.
Although I see that for some reason if the path is of the form "a/b/c", the connected client receives it as "a:b:c". Will have to look more into the docs of webrtc as to why that happens

**Comment by hkirat** [comment]
Another issue came up with this approach.
The file received on the other side is corrupted.

Here is the original and the received file: 
![original](https://user-images.githubusercontent.com/8079861/29115033-a4f4d2fc-7ce5-11e7-9556-66ba6e6d8564.png)
![received](https://user-images.githubusercontent.com/8079861/29115036-a6a10fee-A7ce5-11e7-8c97-096bdbb9377e.png)

Also I'm using 
```js
  var file = new File([blob], Path.relative(StartupState.project("root"), addedFile._path));
```
instead of 
```js
  var file = new File(blob, Path.relative(StartupState.project("root"), addedFile._path));
```

**Comment by humphd** [comment]
How are you writing the file on the receiving end?  Can you please show me all the code involved here vs. snippets?

**Comment by hkirat** [comment]
This is the logic for saving the file to the filesystem.
https://github.com/mozilla/brackets/pull/855/files#diff-172c2aa71bb7326386a85125ccd13603R145

**Comment by hkirat** [comment]
The code for this can be found in this pr : https://github.com/mozilla/brackets/pull/855

**Comment by humphd** [comment]
I have some similar code here: https://github.com/mozilla/brackets/blob/master/src/filesystem/impls/filer/lib/WebKitFileImport.js#L181-L228.

I think your corruption is due to you not using `new` when constructing your new `Buffer` object.

**Comment by hkirat** [comment]
Thanks for the resource @humphd 
I think I will be reusing the handleZipFile, handleTarFile and handleRegularFile functions as it is. Would it be a good idea to shift these into an abstraction and reuse them in both the places?

**Comment by humphd** [comment]
I don't think you'll need anything other than what `handleRegularFile` does, since any file in the remote filesystem will already be expanded (i.e., we auto-inflate archives).  If you want to generalize that code into its own utility module (or put it in an existing one).

**Comment by hkirat** [comment]
Oh yes that makes sense.

**Comment by hkirat** [comment]
With https://github.com/mozilla/brackets/pull/855 merged, we have a basic architecture for sending files via webrtc. 

However, after discussing with @gideonthomas, we're thinking of shifting back to simple webrtc send events for text files, and rely on the sendFile function only for sending binary data. 

Things we need to figure out: 
Does there exist a function that can classify a file as a text/non-text file?
