### ISSUE TITLE
Add logic to rename, add/delete a file on receiving corresponding event from connected clients

### ISSUE THREAD

**Issue by hkirat** [mozilla/thimble.mozilla.org#2402]
Right now, on receiving a rename/add/delete event, the event is logged on the client.
See : https://github.com/mozilla/brackets/blob/collaboration/src/editor/Collaboration.js#L76

The next step would be to add logic to actually to this.

For `rename`, I do see a [rename](https://github.com/mozilla/brackets/blob/master/src/filesystem/FileSystemEntry.js#L336) function in FileSystemEntry.js. 
This renames the file on the filesystem, however, the file name remains same on the UI.
I couldn't find a function that inherently does this. 

For `delete`, I think [this](https://github.com/mozilla/brackets/blob/master/src/filesystem/FileSystemEntry.js#L376) function should do the job.

Looking for how to implement the `add` logic.

**Comment by hkirat** [comment]
The logic for interpreting delete events has been merged in Collaboration branch.

add-file events are interpreted by using the following : 
```js 
CommandManager.execute("bramble.addFile", {filename: payload.path, contents: ""});  
```

However, something similar doesn't exist for adding folders.

**Comment by hkirat** [comment]
For adding a folder: 

There doesn't exist a command to create a new folder with a file name. 
calling FILE_NEW_FOLDER command creates a new folder with the title UNTITLED-x.
https://github.com/mozilla/brackets/blob/master/src/document/DocumentCommandHandlers.js#L705 is called after executing this command.

Would it be a good idea to make this function accept parameters, or create a new command like -> https://github.com/mozilla/brackets/blob/master/src/extensions/default/bramble/lib/RemoteCommandHandler.js#L192  
which accepts a parameters like folder name

**Comment by gideonthomas** [comment]
If you think it's easier to make it accept an optional parameter (name or path of the folder), then yeah, that would be preferable.

**Comment by hkirat** [comment]
Added a new command in https://github.com/mozilla/brackets/pull/868

**Comment by hkirat** [comment]
Closed via https://github.com/mozilla/brackets/pull/869
