### ISSUE TITLE
Add a custom domain.

### ISSUE THREAD

**Issue by TemTemmie** [mozilla/thimble.mozilla.org#2403]

**Comment by gideonthomas** [comment]
Hi @TemTemmie, could you describe your proposal for this bug?

**Comment by TemTemmie** [comment]
not a bug. just a suggestion.

**Comment by gideonthomas** [comment]
Can you describe what you are suggesting though? Do you want to have your published projects hosted on a custom domain? And do you want the feature built into Thimble?

**Comment by TemTemmie** [comment]
probably

**Comment by gideonthomas** [comment]
Hi @TemTemmie, unfortunately custom domain provisioning is currently beyond the scope of what Thimble can provide as it is not a hosting service and as such, I'm going to close this issue for now. Feel free to suggest other simple ways that we can add this feature and contribute to its implementation as well.
