### ISSUE TITLE
Tracking Malay (ms) localization

### ISSUE THREAD

**Issue by TheoChevalier** [mozilla/thimble.mozilla.org#2412]
We are getting Malay localization for Thimble (yay!), let’s track progress here to enable it on dev/prod.

Locale code: `ms`
Language name: `Melayu`

**Comment by TheoChevalier** [comment]
Ready to be enabled! 90% complete as we speak and counting 📈

**Comment by gideonthomas** [comment]
awesome! Thanks for the update @TheoChevalier, will keep this open till we push to production next Tuesday; I'll enable it then.
