### ISSUE TITLE
Allow subtitling on the Thimble demo video 

### ISSUE THREAD

**Issue by TheoChevalier** [mozilla/thimble.mozilla.org#2413]
Looks like people can’t contribute subtitles on the video featured on the home page: https://www.youtube.com/watch?v=JecFOjD9I3k
Is there a reason we’re not turning that on from YouTube settings? I assume subtitles could even be enforced in the embed code. That would be really awesome :) I could also suggest contributing to those subtitles from the project description in Pontoon.

What do you think @flukeout ?

**Comment by flukeout** [comment]
Hey @TheoChevalier - no special reason! I hadn't realized it's something I need to enable. I think before we ask for help we need to decide if the video is up-to-date enough to bother translating. We've added a lot of new features recently so maybe it's worth updating the video.

**Comment by TheoChevalier** [comment]
Awesome! Yeah that probably makes sense at this point to wait for a new video if it needs to be updated :)

**Comment by flukeout** [comment]
Closing until we make an updated video, which we will then enable subtitles on.
