### ISSUE TITLE
Typescript support

### ISSUE THREAD

**Issue by nadeemramsing** [mozilla/thimble.mozilla.org#2418]
Right now, thimble does not support .ts files (no formatting, auto-completing, keyword coloring, etc available).

**Comment by humphd** [comment]
Hi @nadeemramsing.  Our policy around adding language support is that it needs to work without any build steps.  Can you help me understand the requirements of TypeScript support as you imagine it working in Thimble?  If it's just that you want syntax highlighting to work, that's cool.  What else?

**Comment by gideonthomas** [comment]
Closing due to incomplete information
