### ISSUE TITLE
Right click hides new file and new folder option alternatively

### ISSUE THREAD

**Issue by hkirat** [mozilla/thimble.mozilla.org#2419]
Irrespective of where you are right clicking, the drop down tends to alternate between two formats, one in which it contains the new folder and new file option and one in which it does not.

![](https://media.giphy.com/media/3oEhmOyJUzptz7MGRO/giphy.gif)

**Comment by flukeout** [comment]
Yeah, good catch @hkirat - I have noticed this too.
