### ISSUE TITLE
Consider removing inline CSS/JS editors

### ISSUE THREAD

**Issue by humphd** [mozilla/thimble.mozilla.org#2426]
Connected to the discussion in https://github.com/mozilla/thimble.mozilla.org/issues/2425, I think we should consider dumping the inline editors for CSS and JS.  They are a neat idea, you really need to know about them, and buy into the editing model.

Disabling these might take a bit more work, since they aren't extensions.  In the meantime, I'm going to try and disable it from popping-up in the inline editor work happening in https://github.com/mozilla/brackets/pull/826.

**Comment by flukeout** [comment]
Is there any benefit to disabling them?
