### ISSUE TITLE
Thimble takes forever to load projects and crashes

### ISSUE THREAD

**Issue by Lugasamom** [mozilla/thimble.mozilla.org#2429]
I am teaching a Black Rocket class and most of my students cannot open their projects. The system takes too long to load and then crashes.

**Comment by humphd** [comment]
@Lugasamom really sorry to hear this, and thanks for letting us know.  Would you be able to provide some more info so we can try and fix things?

Which OS and browser are you working with in the class?  Also, what does "crashes" mean?  Are you able to look at the dev tools console and see if there are any relevant error messages?

**Comment by Lugasamom** [comment]
Loading Project
Your project seems to be taking a long time to load.
If it doesn't load, please reload the page to try again.

Try Again
If that doesn't help, let us know.

**Comment by Lugasamom** [comment]
Oops, something went wrong!
Please reload your browser to try loading Thimble again. Reload Now
For error details open your browser's Developer Tools console.

NOTE: if you are using Private Browsing mode, please reload in normal mode.

**Comment by Lugasamom** [comment]
We are using Win10 and Dell desktops. They worked fine all week.

**Comment by Lugasamom** [comment]
I have them using Chrome because Edge (the default) kept crashing with another program (scratch)

**Comment by Lugasamom** [comment]
I just had them try Firefox and it is still taking forever....

**Comment by humphd** [comment]
OK, this is good.  Can you also take a look at the console when it crashes like that?  Use [Ctrl + Shift + J](https://developers.google.com/web/tools/chrome-devtools/console/) to open and see what it shows, specifically any errors:

![screen shot 2017-08-10 at 10 10 32 am](https://user-images.githubusercontent.com/427398/29174427-4aabb070-7db4-11e7-89b2-cff4da5636a0.png)

**Comment by Lugasamom** [comment]
Content Security Policy: Directive ‘frame-src’ has been deprecated. Please use directive ‘child-src’ instead.  (unknown)
1502374435608	addons.update-checker	WARN	Update manifest for aushelper@mozilla.org did not contain an updates property
1502374435619	addons.update-checker	WARN	Update manifest for e10srollout@mozilla.org did not contain an updates property
1502374435629	addons.update-checker	WARN	Update manifest for deployment-checker@mozilla.org did not contain an updates property
1502374435640	addons.update-checker	WARN	Update manifest for webcompat@mozilla.org did not contain an updates property
1502374435652	addons.update-checker	WARN	Update manifest for firefox@getpocket.com did not contain an updates property
1502374435661	addons.update-checker	WARN	Update manifest for {972ce4c6-7e08-4474-a285-3208198ce6fd} did not contain an updates property
XML Parsing Error: no root element found
Location: https://push.services.mozilla.com/
Line Number 1, Column 1:  push.services.mozilla.com:1:1
deployment-checker results:
incoming.telemetry.mozilla.org sends expected certificate chain
telemetry.mozilla.org sends expected certificate chain
addons.mozilla.org sends expected certificate chain
services.addons.mozilla.org sends expected certificate chain
versioncheck.addons.mozilla.org sends expected certificate chain
ftp.mozilla.org sends expected certificate chain
mozilla.org sends expected certificate chain
bugzilla.mozilla.org sends expected certificate chain
crash-reports.mozilla.com sends expected certificate chain
releases.mozilla.com sends expected certificate chain
download-installer.cdn.mozilla.net sends expected certificate chain
firefox.settings.services.mozilla.com sends expected certificate chain
push.services.mozilla.com sends expected certificate chain
token.services.mozilla.com sends expected certificate chain
shavar.services.mozilla.com sends expected certificate chain
search.services.mozilla.com sends expected certificate chain

**Comment by Lugasamom** [comment]
The parsing line is highlighted

**Comment by humphd** [comment]
@Lugasamom excellent, that looks like Firefox's log, correct?  How about chrome's?

**Comment by hkirat** [comment]
@Lugasamom Could you post a screenshot of the `console` tab right next to the `Elements` tab in chrome?

**Comment by joycelee11** [comment]
I have the same issue quite often - checked console and it shows a `timeout` error

**Comment by gideonthomas** [comment]
Hi @joycelee11, I'm sorry you're experiencing these issues. If you encountered this over the past 3 days, we were unfortunately experiencing a partial service outage that may have been what you were seeing. It should be resolved now and we intend to release a few fixes today that will hopefully make the service less prone to such outages. We also intend to communicate such outages better in the future. Let us know if you're still experiencing problems and we'd be happy to help out.

**Comment by joycelee11** [comment]
@gideonthomas thanks for the clarification! My templates worked fine today, so that's most likely the reason why 😄

**Comment by flukeout** [comment]
We have made lots of strides in stability and performance lately and likely a majority of these types of issues have been resolved - as such, I'll be closing. Thanks for filing @joycelee11 - please reach out again here of to ``thimble@mozillafoundation.org`` if you encounter this again (or other problems). Cheers!
