### ISSUE TITLE
Mozilla Thimble not loading and stuck.

### ISSUE THREAD

**Issue by TemTemmie** [mozilla/thimble.mozilla.org#2430]
I tried making a new project and this happened.

ERROR
The request could not be satisfied.
CloudFront attempted to establish a connection with the origin, but either the attempt failed or the origin closed the connection.

Generated by cloudfront (CloudFront)
Request ID: RRhBiVAB0OujG_1Fj3oNj6_iNNtug4TObjWcJOV5ZWKvxap5k9iEag==
.

Screenshot : https://gyazo.com/0c79a423baff5677c03e899e65092951

**Comment by humphd** [comment]
cc @cadecairos @gideonthomas.  We've had a few reports of issues today with things not loading.  The earlier one I saw led me to believe it might be some kind of SSL issue.  Any thoughts?

**Comment by humphd** [comment]
@TemTemmie @Lugasamom can you try again now?  We've been seeing some database performance issues, which look to be resolved.

**Comment by cadecairos** [comment]
We've recovered for now, but based on the last twelve hours, we're not out of the woods yet:

![](https://i.imgur.com/BRulp17.png)

**Comment by TemTemmie** [comment]
@humphd It's now working.

**Comment by Lugasamom** [comment]
@humphd It's working but slow for me. Could be my laptop but it finally loaded.

Thanks!

**Comment by humphd** [comment]
Glad it's working again, and sorry that you weren't able to get things working today.  Let us know if you hit more issues.
