### ISSUE TITLE
Architectural decisions towards implementation of Social Sign-In

### ISSUE THREAD

**Issue by ryanwarsaw** [mozilla/thimble.mozilla.org#2431]
Relevant Issues: #2358, #2299, #1752 

Tagged: @humphd, @cadecairos, @gideonthomas, @flukeout 

We're now entering the implementation stage for integrating Passport authentication technology within Thimble, and as a result we need to make some design decisions before moving forward. I would like to gather opinions, ideas and ultimately consensus on my proposal below.

Currently, the way we're doing authentication is modular but yet slightly messy, I'd like to consolidate all the initialization code into a singular location, and include "Strategy" specific code at a lower level, preferably closer to the actual definition of the routes.

As it stands now, we have two generic endpoints: `/login` and `/callback` which are references throughout the code and in HTML templates. I want to keep `/login` but remove `/callback`, and ultimately have `/login` be an interactive web page where you can _select_ a login strategy. 

It could also be built-in with an additional URL parameter to specify a specific strategy in the interim, which would skip the web page and go directly to the login process. This would serve as an intermediary as we transition closer to the final vision of system. 

Specific strategies would be assigned routes such as `/auth/webmaker` and `/auth/webmaker/callback` which would make it easier in the future to add **multiple** strategies.

**Comment by gideonthomas** [comment]
@ryanwarsaw, all of this sounds great! Two questions though:

1. Why do the callback urls need to be different per strategy? The route logic for all of them are effectively going to be the same so there might be a lot of code duplication if we split them.

2. @flukeout can advise on whether the login endpoint to render the choices for authentication should be its own page or just a pop-up overlay on all the pages (homepage, editor, project list). Different websites implement it differently.

**Comment by ryanwarsaw** [comment]
@gideonthomas I'm sure it'd be possible to have just one callback URL, from which you could run logic when hit to determine what provider is being used and send the appropriate callback, but I opted to go with a more readable and less complex option of having just a simple separate route.

It's really just one line of code to declare the route, and tell it to let Passport handle callbacks to that route, see below for an example of how that'd look.

```js
app.get("/auth/webmaker/callback",
    passport.authenticate("webmaker", { failureRedirect: "/", successRedirect: "/yay", session: true }));
```

**Comment by gideonthomas** [comment]
Oh I see what you mean. Question about this approach - where would be add the logic that would need to happen before the redirect (for e.g. setting locale info, cache control headers, storing the user information in the db, etc.)?

**Comment by ryanwarsaw** [comment]
@gideonthomas We have control of the entire flow down to the libraries that send the request(s), so adding the logic to handle these various functions is fairly trivial. We're doing the same thing, just abstracting the login stuff out to a library and a "strategy".

The sequence of events and how that data is distributed may change slightly however, and I speak specifically to how handling user information would work in that regard.

**Comment by flukeout** [comment]
@ryanwarsaw - do you foresee any significant differences in terms of difficulty of implementation in the two approaches (popup vs separate page)? My gut says just to stick with the separate page, especially if that makes it a bit simpler.

**Comment by ryanwarsaw** [comment]
@flukeout A separate page might make for a more clean implementation, but it's honestly up to you.

**Comment by flukeout** [comment]
@ryanwarsaw - sounds good, let's move to a separate page.

**Comment by ranjithrajvasam** [comment]
Social Sign-on is not a good idea, indeed a very dangerous idea. Being Mozillians we shouldn't encourage harmful methods like social sign-on which helps the large corporations and trackers to grab the social data of users, it would make users to have concerns over personal information being transferred or used inappropriately were among their top concerns.

We have to make our privacy practices clearer.

**Comment by Pomax** [comment]
@ranjithrajvasam social sign-on is not in and of itself a dangerous idea, but perhaps the term makes you think of only facebook and google. When we say social sign in, we're being sloppy and what we really mean is "third party brokered signin", which includes (of course) things like facebook and google, but also includes things like firefox accounts and the auth0 login that mozilla is currently working on as replacement for the Persona solution that was discontinued a while back.

**Comment by ryanwarsaw** [comment]
@ranjithrajvasam Social Sign-On isn't an inherently dangerous thing at all, in fact it's just a construct. It is the process of using existing login information from an external source as a means of authenticating yourself with the target site without having to create an entirely new account. 

The privacy concerns only come into play when choosing what **providers** to support, and as of right now we only support one and that is id.webmaker.org which is a Mozilla controlled OAuth 2.0 server that's been serving Thimble logins for years. 

In the future we also have plans to support Google as an **optional** provider, and I'd also like to support Github login as well. We're not the first or last project to have these considerations, and it plays into a larger plan of cleaning up and consolidating the Thimble stack.

**Comment by hmitsch** [comment]
@Pomax @ryanwarsaw @gideonthomas is there any plan or desire to bring Thimble onto Mozilla's Auth0 (see our IAM Project)? If yes, now would be an important time to discuss potential licensing impact.

-Henrik

**Comment by ryanwarsaw** [comment]
@hmitsch I'm not knowledgable on the topic, I'll leave that to @Pomax & @gideonthomas to determine, but also going to loop in @cadecairos.

**Comment by gideonthomas** [comment]
@hmitsch at the moment, no. We're still not sure about what our Auth plans are but I doubt that we would be pursuing it under the existing agreement that MoCo has with Auth0. I think when we have some more clarity on the direction of Auth w.r.t. Thimble's future, we might revist the Auth0 discussion but will still most likely be independent of our existing Auth0 contract.

**Comment by ryanwarsaw** [comment]
**Status Update:** The webmaker passport module (Stage #1) is awaiting review, so is the first of two PRs on the implementation side for Thimble (Stage #2, #3 respectively). As per discussion with @gideonthomas, going to punt this until December or early next year.

**Comment by ryanwarsaw** [comment]
Closing this as all decisions from an engineering perspective have been made, respective PRs have been filed and I don't expect this to move anywhere until well into next year.
