### ISSUE TITLE
Getitng error in Preview

### ISSUE THREAD

**Issue by jgmac1106** [mozilla/thimble.mozilla.org#2432]
On this project: https://thimble.mozilla.org/en-US/user/jgmac1106/1107177/

I am getting this error in the preview window when I click on a link: 

```
404 Not Found

Code: NoSuchKey
Message: The specified key does not exist.
Key: bramble/production/dist/vfs/9/projects/1107177/index.html
RequestId: FDF088AA6B589100
HostId: KA7PiJhUFGsyVw8i7XyM5wFwuBQY/8TtdZnO2WWclX4W252grCa7d6RKCiJVjTMGng2/JcbI8RU=
An Error Occurred While Attempting to Retrieve a Custom Error Document

Code: NoSuchKey
Message: The specified key does not exist.
Key: error.html
```

Yet the projedt works fine live,. Not sure if it is the JS or the CSS animation causing this. I know CSS animation doesn't work in Preview.

**Comment by humphd** [comment]
This is what I'm fixing in https://github.com/mozilla/brackets/pull/866.  @jgmac1106 solution is to refresh until it works.  Let me know.

**Comment by jgmac1106** [comment]
Okay will move discussion there. Just some interesting patterns. Happens most for me with projects that use CSS Animation.
