### ISSUE TITLE
Thimble platform not working. Help ASAP!

### ISSUE THREAD

**Issue by arianadziedzic** [mozilla/thimble.mozilla.org#2436]
Currently we have a classroom of 35 people in Sao Paulo, Brazil using Thimble and all functionality has stopped for 90% of the attendees. Can someone please help or give us an update on the technical issues going on ASAP?

**Comment by flukeout** [comment]
@arianadziedzic we made some improvements yesterday that we think will solve these outages in the future. Please let us know if you experience any issues again.
