### ISSUE TITLE
Losing content in "saved" project.

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.mozilla.org#2441]
**Updated STR**

* Create a new project from scratch
* Name it something
* Modify the ``index.html`` file in some way
* Click the **Publish** button just to force a save
  * Or, you just wait like 10 seconds for the editor to save things locally
* Refresh the editor
* The changes you made to the ``index.html`` page are lost, we see the _previous_ version of that page
  * I've noticed that the _previous_ version is just the version that initially opened in the editor.
* Go to **Your Projects** via the dropdown
* Click on the project you just made
* When it opens in the editor, the ``index.html`` file has the previously unsaved changes in it.

**However**
* If you make a change to the ``index.html``
* Then, open ``style.css``
* Then, go back to ``index.html``
* Now, if you refresh, the changes you made to ``index.html`` persist.

It seems like the "Save" we trigger when hitting the Publish button is not working.

SPOOKY 👻 

**Notes**
* I can reproduce this in both Chrome and Firefox, so I don't think its something specific to the browser and its state.
* I cannot reproduce this locally when running thimble & brackets (AKA works as expected locally)
* When testing on https://mozillathimblelivepreview.net/bramble/production/dist/hosted.html - the local file saves correctly if I give it enough time before refreshing.
* Also able to reproduce this behavior on another machine with a brand new account in Chrome.

cc @gideonthomas @humphd

**Comment by flukeout** [comment]
OK - confirmed that this is also happening when I just edit an ``index.html`` file without any of the special steps above.

**Comment by flukeout** [comment]
@gideonthomas is confirming that he sees this on his end as well.

**Comment by flukeout** [comment]
This is happening in both Chrome & Firefox Nightly for me.

**Comment by gideonthomas** [comment]
Actual fix for this was to set a custom behavior on cloudfront to force it not to cache for the `/files/*` routes
