### ISSUE TITLE
Projects deleted from the Projects List persist until I sign out and back in.

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.mozilla.org#2442]
After deleting and refreshing, when I try to delete it again, I see the following:

![image](https://user-images.githubusercontent.com/25212/29476209-b5342e2c-8417-11e7-9116-b19c56ebd850.png)

It persists even after clearing cached images and files in Chrome.

**Comment by hkirat** [comment]
Might be due to the projects being stored in local storage.
Runnning `window.localStorage.clear()` makes it work.

**Comment by hkirat** [comment]
Nope sorry my bad. Looks like clearing localStorage doesn't do the job.

**Comment by hkirat** [comment]
Opening the projects page in a new tab also doesn't show the delete projects.

**Comment by flukeout** [comment]
I'll re-test this since the new updates we pushed might have helped with overall performance.

**Comment by gideonthomas** [comment]
This is definitely some weird cache issue. If you open that link in a new tab, it shows up fine.

**Comment by gideonthomas** [comment]
Fixed by adding a cloudfront header to not cache the `projects` route
