### ISSUE TITLE
Description of remixed project

### ISSUE THREAD

**Issue by nadeemramsing** [mozilla/thimble.mozilla.org#2443]
Remixed project gets the description of its predecessor and it cannot be changed unless I publish it. 
Can the description be initialized to null after remixing? 
Or is there a way to edit the description that I might have missed?

Kind regards

**Comment by gideonthomas** [comment]
Hi @nadeemramsing, would you be able to explain your use case of changing the description for an unpublished project? We initially intended the description to be something that is shown on a published project to describe the project to others viewing it (although we don't currently do it yet). It was also meant as a place to provide descriptive text for published projects that can be searched in a "gallery of Thimble projects" - something we hope to work on in the future. These assertions might be incorrect so I'm curious to hear your scenario.

**Comment by nadeemramsing** [comment]
My use case would be to simply use the description to describe the unpublished remixed project (so that we can have a differentiating element with its predecessor). This inheritance did not occur previously (i.e. before I tested it more than 15 days ago).

![1](https://user-images.githubusercontent.com/20681851/30112597-ffce72fc-9322-11e7-870f-e8af28701503.PNG)

Sorry for the late reply by the way. Did not notice the mail (notifying a reply).

**Comment by humphd** [comment]
I think "zeroing" the description to the empty string when we create a remix is a good idea in general.  @gideonthomas is this something that needs to happen on publish or thimble?

**Comment by gideonthomas** [comment]
this would need to happen in publish.

**Comment by flukeout** [comment]
Hey @nadeemramsing - one way to change the description for your projects is to edit it, then publish, then you can delete the published version. That should do it. Will close this and file a new issue about changing the description without having to re-publish.
