### ISSUE TITLE
Change <title> tag for the default index.html page

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.mozilla.org#2447]
Currently both the ``<title>`` and ``<h1>`` have very similar content. I've seen many people start to edit the title expecting to change what they see in the preview because the text matches. It's a small thing but I think we should change it so that the first change people try to make works more reliably.

<img src="https://user-images.githubusercontent.com/25212/29628518-94ac4ae6-87ea-11e7-8be4-70c03794804b.png" width="300" />

**Comment by hkirat** [comment]
+1 to that

**Comment by ayush9398** [comment]
Hey everyone, I would like to work on this...

**Comment by gideonthomas** [comment]
@ayush9398, go for it. You would need to setup Thimble locally first, instructions for which are in the main README: https://github.com/mozilla/thimble.mozilla.org#setupinstallation. Once you do that, I think the change that needs to be made is in this file: https://github.com/mozilla/thimble.mozilla.org/blob/master/default/empty-project/index.html.

**Comment by ayush9398** [comment]
What would be a more appropriate title for this...

how about THIMBLE_SAMPLE or maybe THIMBLECIOUS....

**Comment by ayush9398** [comment]
@flukeout @gideonthomas , 
may I know the changes to be made so as to close this issue as soon as possible...

**Comment by gideonthomas** [comment]
@flukeout ping re: this ^ what would a good title be?

**Comment by flukeout** [comment]
It looks like @FinleyCorrigan is tackling this issue and has already opened a PR - so we'll just continue the work there: https://github.com/mozilla/thimble.mozilla.org/pull/2467

**Comment by ayush9398** [comment]
@flukeout any contribution I can make to this issue or should I be switching to any another issue to contribute to?

**Comment by gideonthomas** [comment]
@ayush9398, I'm sorry that a PR for this was already opened while you were still assigned to this issue. As per our contribution guidelines, we ask that contributors request to work on an issue before they try to fix it and it seems like it fell through in this case. Alternatively, are you still interested in working on https://github.com/mozilla/thimble.mozilla.org/issues/1251? I'm happy to assign it to you. Otherwise, feel free to pick a bug from https://github.com/mozilla/thimble.mozilla.org/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20label%3A%22Good%20First%20Bug%22%20-label%3A%22Assigned%20to%20Contributor%22%20 and let us know in the issue you would like to work on.

**Comment by ayush9398** [comment]
Yes! I would like to work on #1251 , please assign it to me..... @gideonthomas

**Comment by ppatel221** [comment]
Is it possible for me to work on this? Im currently a student in an open-source looking to contribute in this space. It would be nice if i can be assigned this

**Comment by flukeout** [comment]
Hey @ppatel221 - I've assigned another issue that you requested to work on.

@FinleyCorrigan - are you still working on this issue? You've got an open PR. Let us know, thanks!

**Comment by flukeout** [comment]
Okay, I'm going to consider this unassigned now and suggest it to another contributor.

**Comment by mkavidas** [comment]
@flukeout Can I work on this bug? Currently in an open-source course and am thinking this would be a good first bug for me to tackle.

Tagging my professor in case he would like to chime in: @humphd

**Comment by humphd** [comment]
@mkavidas go for it.  Feel free to ask questions here, and in https://chat.mozillafoundation.org/mozilla/channels/thimble.

**Comment by rheupler** [comment]
If this gets unassigned again, I'd like to work on it!

**Comment by shikhar-scs** [comment]
Is this issue still up ?

**Comment by gideonthomas** [comment]
looks like there's a queue for this issue :P
@rheupler are you still interested in fixing this issue? If not, @shikhar-scs you can take it on.

**Comment by rheupler** [comment]
Yeah, I can do this today. Thanks!

**Comment by rheupler** [comment]
Opened PR - [#2582](https://github.com/mozilla/thimble.mozilla.org/pull/2582)
