### ISSUE TITLE
Don't crash when a project has no files

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.mozilla.org#2449]
Project URL - https://thimble.mozilla.org/en-US/user/flukeout/1125538/

It's an untitled project in my projects list. When I try to open it, I always see the black error screen (Firefox and Chrome)...

![image](https://user-images.githubusercontent.com/25212/29678192-7f4241a6-88b2-11e7-8a24-835de235d834.png)

Console reports...

![image](https://user-images.githubusercontent.com/25212/29678226-9b8ae4da-88b2-11e7-880d-95838d3638ed.png)

Other projects open fine, it seems to be this project only. In the DB the project exists, but has no files in the ``files`` table.

**Comment by gideonthomas** [comment]
Interesting. Yeah we definitely don't handle the case in which a project has no files attached to it. We might want to handle that on the front-end instead of crashing.

**Comment by humphd** [comment]
Morphing this bug to be about not crashing when we have not files.  We probably need to send back something other than a 404 here, and then deal with that case in the front-end.

**Comment by Cryzek** [comment]
@flukeout Could you please provide the steps to reproduce this issue. The above given project url is not available. Plus, when I tried deleting all files in a project, on the next reload an index.html file was added by default.

**Comment by flukeout** [comment]
Hey @Cryzek - I'll double-check now.

**Comment by flukeout** [comment]
@Cryzek - OK - I got this to happen once out of about 10 tries or so. Usually it adds an ``index.html`` page as you noticed. But sometimes it exhibits the behaviour I described above. I don't know what causes it to break when it does, and it doesn't seem to happen very often, so I'm going to close this issue for now. Thanks for checking into it though!
