### ISSUE TITLE
Autocomplete text is hard to read in dark theme.

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.mozilla.org#2452]
See below...

![image](https://user-images.githubusercontent.com/25212/29730587-8ee32524-8995-11e7-9cf6-c5bba2e8057f.png)

**Comment by kritisingh1** [comment]
Hi @flukeout I would like to take up this issue. Can I ?

**Comment by gideonthomas** [comment]
@kritisingh1, thanks for volunteering! I've assigned it to you. You can start by setting up brackets (I think that's all you need for this) and testing it there. Here are our [contributor guidelines](https://github.com/mozilla/thimble.mozilla.org/blob/master/CONTRIBUTING.md) that might help you with your process. You can find instructions on how to set up Brackets in our README [here](https://github.com/mozilla/thimble.mozilla.org#installing-brackets-bramble). Let us know if you need any help.

**Comment by flukeout** [comment]
Shoot sorry @kritisingh1 - I'm in the middle of working on this right now.

**Comment by flukeout** [comment]
@kritisingh1 - would you like to work on this issue here...

* https://github.com/mozilla/thimble.mozilla.org/issues/2259

It's a good first bug. Please leave a comment there if you would like to and it's yours. Thanks and sorry about the confusion with this issue.

**Comment by flukeout** [comment]
Adressed in https://github.com/mozilla/brackets/pull/874

**Comment by kritisingh1** [comment]
Cool @flukeout I would like to work on #2259. Thanks.
