### ISSUE TITLE
Link to view published project in publish dialog should open in new tab.

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.mozilla.org#2453]
Referring to the link here:

![image](https://user-images.githubusercontent.com/25212/29730988-7cf8d136-8997-11e7-9dd1-57c2e7e88a42.png)

I think it used to open in a new tab. Now it opens in the same tab as the editor, which is annoying. This will also reduce load on our services as people won't have to re-open the editor to continue working.

**Comment by complexSandwich** [comment]
I submitted a pull request for a fix.

**Comment by ryanwarsaw** [comment]
@complexSandwich Glad to see you've filed a PR, for future reference make sure you leave a comment letting us know that you're working on a bug, before starting on a fix. That way we can make sure we're not having two people work on the same bug at the same time.
