### ISSUE TITLE
Tracking Kaqchikel locale

### ISSUE THREAD

**Issue by TheoChevalier** [mozilla/thimble.mozilla.org#2457]
I’ve enabled Thimble for Kaqchikel, a small locale in Guatemala.

Code: `cak`
Name: `Maya Kaqchikel`

Progress can be tracked here https://pontoon.mozilla.org/cak/thimble/

**Comment by belkacem77** [comment]
Welcome Kaqchikel!!

**Comment by TheoChevalier** [comment]
The localization is complete 💯

**Comment by gideonthomas** [comment]
just waiting on adding it to our language mapping list and then this should be enabled on production

**Comment by gideonthomas** [comment]
Should be on production now!
