### ISSUE TITLE
Styling issue with project size UI in Firefox

### ISSUE THREAD

**Issue by humphd** [mozilla/thimble.mozilla.org#2459]
Testing #2446 in Firefox, after importing @flukeout's [Archive.zip](https://github.com/mozilla/thimble.mozilla.org/files/1267968/Archive.zip) file, I noticed that the project size UI is showing when it shouldn't (e.g., we only show it when we get over a certain size):

![screen shot 2017-08-31 at 1 50 34 pm](https://user-images.githubusercontent.com/427398/29937551-f25bc0d0-8e53-11e7-89ae-043f563e9a5f.png)

**Comment by flukeout** [comment]
I will try to reproduce.

**Comment by flukeout** [comment]
@humphd I'm unable to reproduce. The indicator only shows up for me when it is supposed to. Will close but if you see it again, let's hop on a call?
