### ISSUE TITLE
Add AngularJS

### ISSUE THREAD

**Issue by Popescul2222GeorgeTeodor** [mozilla/thimble.mozilla.org#2461]
I would like to have AngularJS compatibility in thibmle.

**Comment by emctague** [comment]
Hey @Popescul2222GeorgeTeodor, it doesn't look like Thimble has preset options for *any* frameworks at the moment - seems to be mostly aimed at developing small, vanilla-JS sites, for the purpose of learning about web development. Now, I'm not a thimble contributor, but in the meantime while you wait for a response from a contributor, there are a few other similar sites that *do* support adding frameworks that you could use - namely JSBin and CodePen.

**Comment by flukeout** [comment]
@Popescul2222GeorgeTeodor @emctague Yeah, the idea was to limit the complexity of the editor and focus on just the basics (this applies also to things like LESS vs CSS). Ideally, we would create starter projects for the Thimble Homepage Gallery that would include some popular frameworks, including Angular. If you are interested in creating something like that, we could add it to the homepage.

I'll close this issue and start an issue with Starter Project suggestions / ideas where we can keep track of this.
