### ISSUE TITLE
Quick docs link takes to WebPlatform

### ISSUE THREAD

**Issue by abdulhannanali** [mozilla/thimble.mozilla.org#2464]
As shown in the Image Below the Quick Docs external links to WebMaker which is a non existent resource now. I would love if it instead took us to the great MDN. 

![image](https://user-images.githubusercontent.com/8170969/30003460-a609b3ba-90d6-11e7-95a2-3da58ea5b7d0.png)

If this is a problem that needs to be fixed. I can start working on this.

**Comment by humphd** [comment]
Hi @abdulhannanali, we've actually talked about ripping this documentation extension out, see #2425.  I wonder if you should start by doing that?  We could explore MDN instead after that.

I'm going to close this in favour of #2425.
