### ISSUE TITLE
Add scroll in Editor dropdown menu 

### ISSUE THREAD

**Issue by ayush9398** [mozilla/thimble.mozilla.org#2469]
The last options in the editor dropdown menu hide when the browser window is not maximized and therefore, these options can't be accessed.

![editor_dropdown](https://user-images.githubusercontent.com/21312552/30130288-4f9dada0-9366-11e7-8e81-97436095a6e4.png)

![editor_dropdown2](https://user-images.githubusercontent.com/21312552/30130527-1bd3706c-9367-11e7-89e1-090ce110f929.png)

This is seen in Firefox and Chrome as well.
Maybe, adding a scroll to menu will work...

**Comment by gideonthomas** [comment]
cc @flukeout for suggestions

**Comment by flukeout** [comment]
Having it scroll might work! We can try adding an ``overflow-y: scroll`` property to it and see what happens. I wouldn't call this a high-priority item however, as a browser window that short isn't very common.

**Comment by RakshithNM** [comment]
I will try this, will be my first bug fix.

**Comment by flukeout** [comment]
@ayush9398 - do you want to take this one to work on?

**Comment by ayush9398** [comment]
Yeah @flukeout

**Comment by ayush9398** [comment]
@flukeout I have opened PR #2473 to fix this issue.... review it please...
