### ISSUE TITLE
Change PDF viewer highlighted text color

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.mozilla.org#2480]
When you highlight text within the PDF Viewer, the highlight color is a kind of bluish purple that is non-standard and doesn't match our color scheme...

![image](https://user-images.githubusercontent.com/25212/30301721-51cdfee6-9711-11e7-8efd-561a1797e125.png)

Let's remove this treatment so it gets the default highlight color of the browser.

**Comment by arsalanh3** [comment]
Would it be something like this?

`#pdf-meta.viewer-header ::selection{
  color: /*color*/;
  background: /*color*/;
}`

**Comment by Anshika-G** [comment]
I would like to fix this.
I'm a beginner, can u pls guide?

**Comment by flukeout** [comment]
Hello @arsalanh3 - it could be! Are you able to run brackets locally to test those changes? Let me know.

@Anshika-G - hey let's see if @arsalanh3 wants to work on this issue first. Thanks.

**Comment by ppatel221** [comment]
@flukeout Hey looks like no ones really working on this bug. Is it okay if i take over?

**Comment by flukeout** [comment]
@ppatel221 - please go ahead, it's yours. Let me know if you have any questions.

**Comment by flukeout** [comment]
Any updates on this @ppatel221 ?

**Comment by ppatel221** [comment]
I have a slight hiccup on this.. I can't seem to get over this problem. Can you take a look and see if you can help me out? (ive installed the most recent version of node.js)

![error](https://user-images.githubusercontent.com/31732426/31325678-c6e3204e-ac8d-11e7-90cd-b4d056c0feb2.png)

**Comment by humphd** [comment]
Do `npm install` and it will add the missing module `is-reachable` that it's complaining about...`Error: Cannot find module 'is-reachable'`

**Comment by gideonthomas** [comment]
@ppatel221 also try pulling from master again and then trying `npm install`

**Comment by ppatel221** [comment]
@humphd I tried this and it didn't work. when i read the error log it said "This is probably not a problem with npm".  But it works now after i removed and pulled the master again.

@gideonthomas surprisingly i did this the first time and it didn't work. Tried it again and it seemed to be working fine. Thanks! I can get started on making the change now.

@flukeout do tips for me as i approach this bug?

**Comment by humphd** [comment]
@ppatel221 glad you got it working.  Here's some info on how to approach this--I'll let @flukeout weigh in on the exact CSS he thinks this needs.

The code you want to work with is in https://github.com/mozilla/brackets/tree/master/src/extensions/extra/PDFView.  Specifically, you probably want to work with the HTML in https://github.com/mozilla/brackets/blob/master/src/extensions/extra/PDFView/htmlContent/viewer.html and CSS in https://github.com/mozilla/brackets/blob/master/src/extensions/extra/PDFView/styles/viewer-overrides.css.  I note that there's a suggestion above in https://github.com/mozilla/thimble.mozilla.org/issues/2480#issuecomment-328748494.

To see a PDF file in the editor, you'll need to drag-and-drop a PDF file into the file tree.  Then you can click it and you'll get the viewer.

**Comment by ppatel221** [comment]
I've got the selection to override the CSS from viewer.css. I've attached the image to show you what it looks like. What are the exact CSS properties(the color) do you want when this pdf metadata is selected?  
![selection](https://user-images.githubusercontent.com/31732426/31701085-ce880b06-b39b-11e7-9fa8-1cacc5b07dbd.png)

**Comment by humphd** [comment]
@flukeout can say for sure, but a good strategy with a situation like this is to look around at what other code already does.  For example, here's what I see when I add an Image to my project and select the text in the editor's header:

<img width="696" alt="screen shot 2017-10-18 at 10 04 27 am" src="https://user-images.githubusercontent.com/427398/31723070-d84fc3fe-b3eb-11e7-83bc-c0ad78bea4a9.png">

> When in Rome, do as the Romans.

**Comment by flukeout** [comment]
Agreed, I think one approach would be just to remove whatever custom styling that PDF viewer is adding. I bet the default matches what's visible in the screenshot above.

**Comment by ashish1500616** [comment]
Hi @flukeout  its seems that this issue has not been resolved and no one is working on it, can I work on this issue?

**Comment by humphd** [comment]
This is actually fixed, I landed it yesterday and forgot to close this.
