### ISSUE TITLE
中文乱码

### ISSUE THREAD

**Issue by sanmaodo** [mozilla/thimble.mozilla.org#2486]
我上传的网页，中文变成了乱码，期望能够改善，谢谢！

**Comment by ryanwarsaw** [comment]
> I uploaded the page, the Chinese became garbled, hoping to improve, thank you!

I used Google Translate, so that might actually be a terrible translation but it seemed to work.

**Comment by feihaozi77** [comment]
@sanmaodo 能否提供重现步骤（截图）

**Comment by feihaozi77** [comment]
@sanmaodo would you please provide some STR?

**Comment by Pomax** [comment]
这似乎工作: https://thimbleprojects.org/mopaxian/326223/

**Comment by Pomax** [comment]
![screenshot 366](https://user-images.githubusercontent.com/177243/31138974-0794680e-a825-11e7-8cc5-6c8b188eddd6.png)

![screenshot 367](https://user-images.githubusercontent.com/177243/31138978-09a726e0-a825-11e7-824a-dfc2fffce09c.png)

**Comment by Pomax** [comment]
closing as resolved. Please comment if this should be reopened.
