### ISSUE TITLE
Figure out how to disable Codemirror's native error highlighting.

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.mozilla.org#2489]
When you have an error in your markup, Codemirror highlights a bunch of stuff in pink:

![image](https://user-images.githubusercontent.com/25212/30502758-6cfd1d7e-9a1c-11e7-8fb9-95c24da75142.png)

Because there's no other information presented, it kind of makes it hard to tell where and why an error is happening. Since we're trying to integrate slowparse again, I think we should figure out how to turn this behaviour off so once slowparse is ready, we can let it take over fully.

**Comment by humphd** [comment]
I had a chance to look into this.  Here's what I found.

CSS for this error highlighting gets defined here:

https://github.com/mozilla/brackets/blob/master/src/LiveDevelopment/MultiBrowserImpl/documents/LiveDocument.js#L32-L37

This then gets applied here:

https://github.com/mozilla/brackets/blob/master/src/LiveDevelopment/MultiBrowserImpl/documents/LiveDocument.js#L200-L235

It's being called for HTML Live Documents here (see like 235 specifically), when the underlying doc changes, and before updates are sent to the preview:

https://github.com/mozilla/brackets/blob/master/src/LiveDevelopment/MultiBrowserImpl/documents/LiveHTMLDocument.js#L188-L235

So one option is for you to hook your SlowParse calls into `https://github.com/mozilla/brackets/blob/master/src/LiveDevelopment/MultiBrowserImpl/documents/LiveDocument.js`, and use the error reporting it has vs. what's coming from the instrumentation code in Brackets.  Another (easier) option would be to just get rid of the code that's adding the CSS to CodeMirror in `LiveDocument.prototype._updateErrorDisplay`.

**Comment by flukeout** [comment]
Thanks @humphd - will look into it more.

**Comment by ayush9398** [comment]
The slowparse returns a JSON file when an error is encountered in the html, which gives a key value pair of error, key being 'type' and the value states the error encountered.

I think this json can be used in adding more info to tell the user what error is made at the specific line. 
@flukeout @humphd

**Comment by flukeout** [comment]
Definitely @ayush9398 - we are working on integrating Slowparse here -> https://github.com/mozilla/brackets/pull/876

**Comment by flukeout** [comment]
Oh and also, we've been able to disable the native error highlighting within that PR using CSS, so we can close this issue.
