### ISSUE TITLE
Slowparse Discussion

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.mozilla.org#2491]
This is a tracking bug for discussions & deliberations related to Slowparse. I had a call today with @Pomax to get him up to speed with my current adaptation [here](https://github.com/mozilla/brackets/pull/876).

**Issues & Quesitons** 
* **Main thing:** We'd like to adapt Slowparse to work with CSS files in addition to inline CSS within HTML files
* ~~Can we delay the parsing to 2 seconds after the user has stopped typing?~~
* Currently it seems like Slowparse only reports the line number of the error initially, can we pass all of the data in right away so we can do a highlight before expanding the error message?
  * Would be nice to get a Line and Character range (or series of ranges)
* Can we report the ranges in the following format ``start: { line: 2, char: 9}`` & ``end : { line: 2, char: 15}`` 
  * This is the data structure that is used by Codemirror's ``markSelection`` method.
  * Currently we report the start and end index like this ``59,62`` and we have to figure out the above based on that information
 

cc @Pomax

**Comment by humphd** [comment]
> * Can we delay the parsing to 2 seconds after the user has stopped typing?

Doing this would likely require us to invent an "idle" callback for the editor in Brackets, which currently doesn't exist.  The closest we can get to it would be to listen for `change` events on the editor, then use something like [`_.debounce()`](http://underscorejs.org/#debounce) to set a timeout that will fire in the future.  We'd need to deal with another `change` event coming in during that timeout, and restart the countdown, only firing our `idle` event when we've *really* seen no change in Nms.

Out of interest, I looked at how the interactive linters extension works, and it basically waits 500ms after a `change` and then calls the `lint()` function like I mention above, but without dealing with a true `idle` case--maybe we don't actually care?

**Comment by Pomax** [comment]
Just to make sure, it needs to fire "in the future" but on "the current text" rather than "the text as it was when the future-scheduling happened"?

**Comment by flukeout** [comment]
@Pomax Yeah I think we should always lint on the current text. We shouldn't do the linting and then report the result in the future, just schedule a lint pass for the future.

**Comment by Pomax** [comment]
We could give slowparse its own "debounce" functionality, like:

```js
parseTheCSSdata = function(getCurrentDataFunctionReference, sendUpdateFunctionReference, timeout, ) {
  this.lock.setDataRequestFunction(getCurrentDataFunctionReference);
  this.lock.setParseResultCallback(sendUpdateFunctionReference);
  this.lock.setTimeout(timeout);
}
```
where the lock object has a timeout like
```js
lock.setTimeout = function(ms) {
  // invalidate previously scheduled timeout
  clearTimeout(this.timeout);
  // schedule a new timeout
  this.timeout = setTimeout( () => this.parse(this.getCurrentData()), ms);
}
```
where `parse` runs the actual CSS validation and then calls `this.parseResultCallback(result)` after the timeout expires.

**Comment by flukeout** [comment]
Closing this as we've been making headway and have additional issues open now.
