### ISSUE TITLE
Can't easily edit Slowparse, as there is no watch-task to recompile it

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.mozilla.org#2493]
So, we'll be wanting to make changes to the Slowparse submodule. Currently, when we make changes, we'd need to ``npm run build`` within the ``thirdparty/slowparse/`` folder to see the changes. Is it possible to have the changes we make to the code in that folder work without this step?

cc @Pomax - this sound about right?

**Comment by flukeout** [comment]
Looks like ``build`` depends on ``browserify`` which isn't listed in the dependencies.

**Comment by humphd** [comment]
When I merged upstream with Adobe, they added ways for secondary `npm` scripts to run for each extension.  We can try to use that, or we can just hack it in directly into our `Gruntfile`.  Do what's easier, I think.

**Comment by humphd** [comment]
Thinking about this a bit more today, and I think we shouldn't put build steps for Slowparse in our code, since it won't happen often enough to warrant this extra machinary.  Instead, can we change Slowparse to build the release + minified versions and then check those into git?  That way a submodule update will pull in the latest code.

**Comment by flukeout** [comment]
OK - I'm just anticipating a time when we'll need to modify / update it's inner workings to rephrase the rule descriptions that it spits out which will require a lot of refreshing / testing.

**Comment by humphd** [comment]
If we're going to significantly change Slowparse to work in Brackets, I'd suggest you consider just pulling the code into the repo.

**Comment by flukeout** [comment]
I don't think the changes will be brackets-specific, anyway, let's discuss on a call.

**Comment by flukeout** [comment]
It's not really bothering me anymore. ``npm run build`` within the slowparse dir is fast enough.
