### ISSUE TITLE
Localization Bugs

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.mozilla.org#2499]
A user emailed and let us know that if you choose English (UK) some strange things happen...

Top nav is in greek...

![image](https://user-images.githubusercontent.com/25212/30704092-38fa950c-9eb7-11e7-8004-eee2d20efbbd.png)

Text below gallery is definitely not in English...

![image](https://user-images.githubusercontent.com/25212/30704104-4494f25e-9eb7-11e7-97ef-c97dd4498ee0.png)

The [features page](https://thimble.mozilla.org/en-GB/features) is messed up too.

cc @gideonthomas @TheoChevalier any ideas?

**Comment by TheoChevalier** [comment]
Looks like when a translation is missing, the fallback is broken. So instead of falling back to English, the script seem to randomly pick an existing translation.
