### ISSUE TITLE
Adapt Slowparse to work with CSS files

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.mozilla.org#2500]
To build on the work in https://github.com/mozilla/brackets/pull/876, we want to make it so that slowparse will work on ``.css`` files as well as within ``.html`` files. Currently it can parse CSS within an HTML file, so it looks like a lot of the brains of that are already in place.

Flagging @Pomax for any additional comments, thoughts & questions.

**Comment by flukeout** [comment]
Current deliberations include:

* How to set it up?
  * node module (current favorite)
  * submodule (boo)
  * subtree (boo)

**Comment by Pomax** [comment]
let's do a node_module, it's already hosted on https://www.npmjs.com/package/slowparse and publishing an update to expose the CSS parser will be ez

**Comment by flukeout** [comment]
Okay cool, how does that affect the work I've currently been doing? I think I only made a super minor change to add a ``token`` thing to one of the messages.

**Comment by Pomax** [comment]
shouldn't be

**Comment by Pomax** [comment]
slowparse itself has been updated to v1.3.0 with a `Slowparse.CSS(css, options)` function that we can add to parse.js/main.js specifically for CSS files now.

**Comment by flukeout** [comment]
Well, then let's consider this closed. I tested with the latest branch and it works...

<img width="637" alt="image" src="https://user-images.githubusercontent.com/25212/30718594-fb0cd4b0-9ee5-11e7-986d-2f1005108d78.png">
