### ISSUE TITLE
English (UK) shows greek in Navigation

### ISSUE THREAD

**Issue by abdulhannanali** [mozilla/thimble.mozilla.org#2503]
English UK is showing Greek in the Nav menu, while English (US) is showing okay english

![image](https://user-images.githubusercontent.com/8170969/30781621-0b9a19ca-a13c-11e7-8b46-93b5dd94fae6.png)

**Comment by humphd** [comment]
I think @gideonthomas recently fixed this, but it might not have made it to production yet.  Gideon, can you please confirm and close this if so?

Thank you for filing this, @abdulhannanali.

**Comment by abdulhannanali** [comment]
@humphd it also shows some of the text on other pages in Greek. It looks like Greek to me but it might be some other language.

**Comment by abdulhannanali** [comment]
There are no service workers or cache enabled on my side, so the bug is there, here's another page 
![image](https://user-images.githubusercontent.com/8170969/30815118-a84a83d2-a22b-11e7-991a-ba9d0e27c935.png)

**Comment by gideonthomas** [comment]
Yeah, it didn't make its way to production, but it should be there now. Feel free to reopen if you still see this @abdulhannanali

**Comment by abdulhannanali** [comment]
Yes it did Thanks a lot! I love people at Mozilla :heart: :heart: :heart:
