### ISSUE TITLE
Create Account errors?

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.mozilla.org#2504]
Hey team, got word from a user that there were some problems resetting a password (no email received) and creating a new account. This is the error they saw when attempting to create an account...

![image](https://user-images.githubusercontent.com/25212/30863558-f406e110-a296-11e7-8438-1c2dbc6fef96.png)

Based on that screenshot, do we know what might have happened? Was the login server having any issues within the last 48 hours?

cc @cadecairos @gideonthomas @humphd

**Comment by cadecairos** [comment]
Based on the URL, they visited `id.webmaker.org` directly, and not via Thimble. The query params `client_id`, `response_type`, `state`, and `scopes` are filled automatically by Thimble, and are required for this to function.

For a reset to work, they need to use the login button on Thimble, then find the reset password function on the login form.

**Comment by cadecairos** [comment]
Also, There was an issue with sawmill over the weekend that caused emails to not get sent. I fixed this issue yesterday and processed the backlog (12,000 messages/events) - reset emails should work now.

**Comment by flukeout** [comment]
Cool, thanks @cadecairos - got a bunch of emails about password resets not working, so that explains it. Thanks for resolving.
