### ISSUE TITLE
Unneeded gap where the Project Size is displayed.

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.mozilla.org#2505]
When a project isn't large enough to warrant displaying the Project Size UI at the bottom of the File View, we still take up some room for it, as seen here where the ``index.html`` file is being overlapped by an empty container with a black background...

![image](https://user-images.githubusercontent.com/25212/30869260-4d0c44f8-a2a6-11e7-9cae-12d6b714922f.png)

We should only take up this space if we are displaying the project size. The styles for this are in the ``sidebarTheme.less`` file. Solving this would require changing the styles for the ``.hidden`` class that this UI receives when it is not in use. Happy to assist further if someone wants to take it.

**Comment by michaelic** [comment]
Hi @flukeout, I'd like to work on this.

**Comment by flukeout** [comment]
All yours @michaelic - let us know if you need help or have questions.

**Comment by flukeout** [comment]
All yours @michaelic - let us know if you need help or have questions.

**Comment by michaelic** [comment]
Thanks! I got the brackets project and built it, and I do have a question about approach.
How important is maintaining the fade in / fade out effect here?

The most straightforward fix I can think of would be to `display: none;` since it seems like what we really want to do here is take the element out of the flow completely rather than making it invisible, but that would interrupt the opacity transition since the display change happens immediately and can't be transitioned.

**Comment by michaelic** [comment]
Another option could be to slide/pull it out of view by transitioning the bottom margin when `.hide` is applied, but it seems like the height of that project size area can vary, so I'm not sure there's a reliable way to know how far to move it.

**Comment by flukeout** [comment]
Hello, @michaelic - I think just straight up hiding it with ``display: none`` would be fine. Give that a try and we'll see how it looks.

**Comment by ppatel221** [comment]
Hey can i be assigned this bug. Im a student in an open-source class looking to contribute to this project. Thanks!

**Comment by flukeout** [comment]
Hello @ppatel221 - if you check the recent comment history you'll notice that @michaelic is working on this issue. Cheers.

**Comment by michaelic** [comment]
@flukeout Thanks, PR incoming shortly :)

**Comment by flukeout** [comment]
Closing as we've merged the PR related to this. Thanks again to @michaelic 👍
