### ISSUE TITLE
QuickEdit UI for 'border-radius'

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.mozilla.org#2506]
It would be great to have a QuickEdit UI (similar to how we handle the colorpicker) for the CSS property ``border-radius``. The goal would be to create an expandable UI that would allow people to set the border...

Here's a very rough mockup of the UI controls it could have...

```
(*) Set individual radiuses
( ) Use same radius for all corners 

Units: 
(*) px
( ) em
( ) %

Top-left corner:     -----O------ 5px
Top-right corner:    ---------O-- 7px
Bottom-right corner: O----------- 8px
Bottom-left corner:  --O--------- 2px
```

The UI would be a combination of toggles and sliders and it would update the code in the editor to match what the user selected.

If we can get these basic controls working, then we can move to a secondary phase of improving the look and feel of the UI.

**Comment by feihaozi77** [comment]
This sounds interesting, can I work on this one?

**Comment by gideonthomas** [comment]
@flukeout are quick-edit ui's good for contributors to work on?

**Comment by humphd** [comment]
@gideonthomas Yeah, I think these are good "projects" for contributors, as long as they know it's not going to be a few lines of code to fix it.

@feihaozi77 if you're OK with this, then yes go ahead.  If you want help, let me know and I can guide you through what has to happen.

**Comment by feihaozi77** [comment]
@humphd @flukeout  @gideonthomas Yes I would like to work on this one, please give me a brief instruction on which part of existing code I can refer to, i was looking at the codes in src/extension/inlinecoloreditor.js

**Comment by humphd** [comment]
OK @feihaozi77, here's an overview of what you need to do.

1. Create a new directory in `src/extensions/default/` named `InlineBorderRadiusEditor`

2. Create a skeleton for a new inline editor following the patterns in these existing ones: [Color Editor](https://github.com/mozilla/brackets/tree/master/src/extensions/default/InlineColorEditor), [3D Params](https://github.com/mozilla/brackets/tree/master/src/extensions/default/Inline3DParametersEditor), [Timing Function](https://github.com/mozilla/brackets/tree/master/src/extensions/default/InlineTimingFunctionEditor).  Of the three, the Color Editor is probably the easiest to understand.

3. Your first version of this can be very much a prototype, so don't get caught up in all the details at first.  You'll need create some HTML to look like what @flukeout outlined above, and then put into a template file, like this https://github.com/mozilla/brackets/blob/master/src/extensions/default/InlineColorEditor/ColorEditorTemplate.html.

4. You'll need some CSS for that (we use LESS), like this https://github.com/mozilla/brackets/blob/master/src/extensions/default/InlineColorEditor/css/main.less.

5. You'll need to load your template, and CSS at runtime, and register your editor in a `main.js` file, like https://github.com/mozilla/brackets/blob/master/src/extensions/default/InlineColorEditor/main.js.

6. You'll need to write a regex to figure out when to show this thing.  I suggest you study the spec on `border-radius` and figure out all the ways it can be entered.

7. You'll need to tell Brackets to load your extension by modifying this file https://github.com/mozilla/brackets/blob/master/src/extensions/bramble-extensions.json and following the docs here https://github.com/mozilla/brackets/tree/master/src/extensions#bramble-extension-loading.

Get started at this, and then feel free to ask questions in here or online.  We'll help you as you go.

**Comment by feihaozi77** [comment]
@humphd thank you for the instruction, I'll try figure out those one by one

**Comment by feihaozi77** [comment]
@humphd @flukeout I need help for getting the RegExp for the border-radius property, could not find any proper expressions

**Comment by feihaozi77** [comment]
@flukeout @humphd 
right now I'm using a very simple regexp like this 
var BORDER_RADIUS_REGEX = new RegExp('^.*border-radius:.*');
so far that works fine for finding the match of border-radius property and it triggers the purple thunder badge to show. And that's what I've done so far. I don't know if I should leave the RegExp as it is for now and move on to the next step, or should I just make a perfect regexp first. 
Please give some advice.

**Comment by flukeout** [comment]
Yeah, go ahead and move on to some of the other parts of this project - I don't think we need to get every aspect perfect, we can refine a working version and improve it as we go in the Pull Request. For reference @Cryzek has done some good work here on another of the editors, maybe it will help you to see what he has done so far...

* https://github.com/mozilla/brackets/pull/888

**Comment by humphd** [comment]
https://stackoverflow.com/questions/12432345/javascript-jquery-regex-for-border-radius-value has one attempt at this.  I think don't worry about being perfect yet, just get the basics working, and we can improve from there.

**Comment by feihaozi77** [comment]
@flukeout @humphd 
finally i made some progress on this issue. please take a look and let me know if I should make a PR at this point so that you can review the code a little bit and give me some feedback.
[
![bracket_border_radius](https://user-images.githubusercontent.com/13205171/32087664-66875d60-baab-11e7-95b9-aaf3b6f139e3.gif)
](url)

**Comment by feihaozi77** [comment]
@flukeout @humphd I have made a PR in the brackets repo 
https://github.com/mozilla/brackets/pull/890

**Comment by flukeout** [comment]
Thanks @feihaozi77 - I'll check it out tomorrow!

**Comment by feihaozi77** [comment]
@humphd https://github.com/mozilla/brackets/pull/890 this the pr i made, please review
