### ISSUE TITLE
Test for Brackets when starting Thimble

### ISSUE THREAD

**Issue by humphd** [mozilla/thimble.mozilla.org#2509]
Follow-up from https://github.com/mozilla/thimble.mozilla.org/issues/2355#issuecomment-333153037: let's have Thimble test to see if Brackets is running when the server starts, since it's a runtime dep that we assume is there.  This tends to trip-up new devs who forget (or don't know) to run them both.

Let's use https://github.com/sindresorhus/is-reachable.  The general idea here would be:

* install and save the `is-reachable` module: `npm install --save is-reachable`
* Alter the [server code](https://github.com/mozilla/thimble.mozilla.org/tree/master/server) to do a check to see if the [`BRAMBLE_URI` URL defined in the `env`](https://github.com/mozilla/thimble.mozilla.org/blob/7a6c2f8d492b5ade8c5a28e5bb93f37c20be2c3e/server/routes/config.js#L19).  @gideonthomas can tell you where he'd want that code to live specifically
* If the Brackets host isn't reachable, log a message indicating that the server should be running.

Assigning this to @MPierre9.  Ask questions here and we can help you through this.

**Comment by gideonthomas** [comment]
you can add it somewhere at the bottom of this file: https://github.com/mozilla/thimble.mozilla.org/blob/master/server/index.js. And use `config.editorHOST` instead of testing the `env` for `BRAMBLE_URI`. You also don't need to check if it exists because it will throw an error earlier in the code if it is missing.

**Comment by MPierre9** [comment]
I'll get started working on it, thanks @humphd and @gideonthomas.

**Comment by MPierre9** [comment]
So I implemented what @humphd and @gideonthomas  suggested and have a working "prototype". 
![bramble bug fix](https://user-images.githubusercontent.com/27080760/31050337-6e4fe27e-a615-11e7-9854-f140abb02f6c.JPG)

The only odd thing I encountered is that when you run npm start and the build process bar is displayed the console.log() text will be repeated. 

![bramble bug 2](https://user-images.githubusercontent.com/27080760/31050347-be13014c-a615-11e7-8a25-15efbb0d6f80.JPG)


What do you guys think?

**Comment by gideonthomas** [comment]
Huh, that is interesting...I'm not sure why that happens. Now that I think about it, it might make more sense to have this be a separate module. Here's my suggestion:
1. Take your code and move it to a new file inside the `scripts` folder called `verify-brackets.js`. Use `process.env.BRAMBLE_URI` instead this time.
2. In `package.json`, before [this line](https://github.com/mozilla/thimble.mozilla.org/blob/master/package.json#L108) add a `prestart` script that runs `node scripts/verify-brackets`.

Make sure that when you run `npm start`, you see the log (hopefully only once).

**Comment by MPierre9** [comment]
Hi @gideonthomas, I implemented what you suggested and get "undefined" as the output when I use process.env.BRAMBLE_URI. Is there something I missed? Thanks.
![undefined](https://user-images.githubusercontent.com/27080760/31088176-b2c50dae-a76d-11e7-9b72-b6585e5e00fc.JPG)

**Comment by gideonthomas** [comment]
@MPierre9, did you run `npm run env` before that?

If you have done that and you still see `undefined`, we can instead rely on config by doing the following:
1. require in `server/routes/config` as a const `config`.
2. You can then access `config.editorHOST` to get the url for brackets and check if it's reachable.

Btw, thanks for the screenshots, they're really helpful!

**Comment by humphd** [comment]
That likely means the environment hasn't been loaded into the process yet.  Can you open a PR with your changes, and we can discuss them there.

**Comment by MPierre9** [comment]
Using require `server/routes/config` as @gideonthomas suggested I got an error that it couldn't find the module. 
![require bug](https://user-images.githubusercontent.com/27080760/31096424-fc76c052-a789-11e7-82b9-9db1a7e3226b.JPG)

Should I still open a PR if there is an error in the code or should I use a different version of the code @humphd 

Thanks for the help, I've enjoyed working on this so far!

**Comment by humphd** [comment]
@MPierre9 yeah, open a PR with what you have, and I can read the code.  Let's continue this conversation in the PR, and we'll get it figured out together.  Thanks for working on this.
