### ISSUE TITLE
QuickEdit Lightning indicator doesn't go away when switching to Font Viewer

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.mozilla.org#2515]
**Steps to reproduce:**

* Start a new project
* Add a font file to it
* Switch to the style.css file and start to edit or add a color rule
* When the purple Lightning icon appears ⚡️, click the font file
* When the view switches, the lightning icon persists on the screen

See below...

![image](https://user-images.githubusercontent.com/25212/31148657-38c9da40-a842-11e7-8ad9-568ff38bb40a.png)

**Comment by humphd** [comment]
We probably need to add a listener for `activeEditorChange` to turn this off.  I'll mentor someone if they want to work on this.  It would be pretty easy to fix.

**Comment by ddinis-alves** [comment]
Hi, I'd like to try working on this.
Thanks.

**Comment by humphd** [comment]
@ddinis-alves great, it's yours!

It looks like the code for this got written already, but is never used:

https://github.com/mozilla/brackets/blob/master/src/editor/PopoverWidget.js#L150-L161

Try adding `EditorManager.on("activeEditorChange", onActiveEditorChange);` in the `appReady` function, and see if this fixes things.

**Comment by scarecrow21** [comment]
Hi. I'm a newbie here. I'd like to work on this bug. Can someone guide me through it?

**Comment by humphd** [comment]
Hi @scarecrow21, welcome to Thimble.  This bug is already being worked on by @ddinis-alves, but if you'd like another bug, we can certainly look for one for you.  Let me know.

**Comment by scarecrow21** [comment]
Yes, I'd like to solve another bug.

**Comment by humphd** [comment]
@scarecrow21 I'm going to assign you https://github.com/mozilla/thimble.mozilla.org/issues/2152 instead.
