### ISSUE TITLE
Add is-reachable to package.json

### ISSUE THREAD

**Issue by gideonthomas** [mozilla/thimble.mozilla.org#2520]
cc @MPierre9 

the module you added should be in `package.json` as a `devDependency`. Would you be able to add that @MPierre9?

**Comment by humphd** [comment]
@MPierre9 see https://docs.npmjs.com/files/package.json#devdependencies for info.

**Comment by MPierre9** [comment]
@gideonthomas For sure I'll get started on it. Thanks for the extra info @humphd
