### ISSUE TITLE
Thimble not showing my project

### ISSUE THREAD

**Issue by milanm8** [mozilla/thimble.mozilla.org#2527]
Thimble is not showing my project. Instead it is saying "https://mozillathimblelivepreview.net/bramble/production/dist/vfs/546606/projects/1203521/index.html".

**Comment by humphd** [comment]
@milanm8 we've been trying to track this bug down.  Are you able to give me more info?  Which OS, browser, version, etc.  Did it ever work before, or is this your first time?  Anything on the web console (e.g., errors)?  What if you refresh a few times?

**Comment by humphd** [comment]
This was fixed by https://github.com/mozilla/brackets/pull/894.  See http://blog.humphd.org/promise-to-catch/ for more details.
