### ISSUE TITLE
What is -> "Cannot set property `token` of undefined" error.

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.mozilla.org#2531]
A user from Twitter brings us this error, do we know what it might be related to?

![image](https://user-images.githubusercontent.com/25212/31747363-5b458278-b421-11e7-8ebb-b1a22440779e.png)

cc @gideonthomas @humphd

**Comment by humphd** [comment]
I wonder if this is related to our patch to try and remove the user's cookies if we hit a route that would require the user to logout/login again.  What do you think, @gideonthomas?  Also, what happened when they clicked Try Again?

**Comment by gideonthomas** [comment]
it sounds like we're calling a piece of middleware for a route where we shouldn't be. What was the STR for this?

**Comment by flukeout** [comment]
I've requested more info over Twitter, but so far no extra information:
https://twitter.com/invisionvisuals/status/920704041457455104

Let's close in a few days if we don't get more detail.
