### ISSUE TITLE
Github icon on Get Involved page is black in Firefox. Should be white.

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.mozilla.org#2536]
On https://thimble.mozilla.org/en-US/get-involved/ the Github icon on the button is black, but should be white...

<img src="https://user-images.githubusercontent.com/25212/31834963-aa11684a-b584-11e7-8512-95caacd3220e.png" width="400" />

This is happening in Firefox only, and has happened to other SVGs on the site in the past. I'm pretty sure if we run the SVG through https://jakearchibald.github.io/svgomg/ it starts to work correctly after, so that's what I'd recommend trying here.

**Comment by marcobeltempo** [comment]
Hi @flukeout I would like to take this one on

**Comment by gideonthomas** [comment]
Assigning to you @marcobeltempo

**Comment by sandeeproy99** [comment]
We can use font awesome for white icon.

<i class="fa fa-github" aria-hidden="true"></i>
