### ISSUE TITLE
Inconsistent "mouse-style" in the settings menu.

### ISSUE THREAD

**Issue by scarecrow21** [mozilla/thimble.mozilla.org#2543]
Browser: Firefox
OS: Ubuntu 16
Click on the settings menu and mouse over between the "text-size" and the "Color-theme" option. The mouse pointer style is different for both of them.
![thimble-issue](https://user-images.githubusercontent.com/24637176/32035413-a308b912-ba08-11e7-81bd-64d57a9eec56.gif)

**Comment by scarecrow21** [comment]
I'll fix this.

**Comment by gideonthomas** [comment]
Thanks for taking this on @scarecrow21

**Comment by scarecrow21** [comment]
I've made a PR for this. Please let me know if some other changes have to be made.

**Comment by bansalnitish** [comment]
@gideonthomas This issue should be closed since the mouse styling was intentionally set in this way as mentioned [here](https://github.com/mozilla/thimble.mozilla.org/pull/2544#issuecomment-342000554).
