### ISSUE TITLE
Preview side bar will not work 

### ISSUE THREAD

**Issue by DehydratedGrape** [mozilla/thimble.mozilla.org#2546]
It says this (i attend highschool myabe it is wifi blocking it plz help)

404 Not Found

Code: NoSuchKey
Message: The specified key does not exist.
Key: bramble/production/dist/vfs/677355/projects/1251203/index.html
RequestId: 71B0EB56787E5117
HostId: ESmBaeuVWQaHQRyi3XaQE61tlAb1EB7ZqEMPAur1URPU+eD8IhjFBpGrqEupFc8M
An Error Occurred While Attempting to Retrieve a Custom Error Document

Code: NoSuchKey
Message: The specified key does not exist.
Key: error.html

**Comment by gideonthomas** [comment]
Hi @DehydratedGrape, would you be able to refresh your browser a few times? That might clear it up.

**Comment by humphd** [comment]
This was fixed by https://github.com/mozilla/brackets/pull/894.  See http://blog.humphd.org/promise-to-catch/ for more details.
