### ISSUE TITLE
Error during service worker registration

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.mozilla.org#2547]
From a user over email, they are seeing this error message when attempting to load a project in Firefox. Chrome seems to work fine...

<img width="1120" alt="image" src="https://user-images.githubusercontent.com/25212/32381402-df082a96-c0b2-11e7-9bbe-c636d89f889d.png">

Do we know what might be causing this @gideonthomas @humphd

**Comment by humphd** [comment]
It looks like a CORS issue with CSS loading from `https://mozillathimblelivepreview.net`.  Did we somehow change the known hosts? cc @cadecairos

**Comment by cadecairos** [comment]
This is a Content Security Policy violation - was this CSS file loaded from somewhere else before, or was the policy modified recently?

Easy fix is adding `https://mozillathimblelivepreview.net/bramble/production/dist/styles/` into the `style-src` directive.

**Comment by flukeout** [comment]
We've been getting a lot of "Stuck Loading Error" type of emails recently, is this something that might have changed recently?

**Comment by humphd** [comment]
The `style-src` should only care about domain, right?  Not path.  I'm confused why it's not listed in that error above.

**Comment by cadecairos** [comment]
CSP directives can include paths in the source strings. I'd include the path to the CSS dist directory, unless we're loading CSS from another place on that domain.

**Comment by gideonthomas** [comment]
@cadecairos do CSP policies from the parent frame apply to the embedded iframe? If so, it's weird that we are running into this now because we never had the bramble domain in the `style-src` CSP rule and we were still able to load `brackets.min.css` fine.

**Comment by gideonthomas** [comment]
ok so I chatted with jbuck and vlad from MoCo. This might be an interesting bug and may be a bug in firefox. @flukeout do we know what version of firefox the user was on?

@humphd to clarify, the service worker is registered from the bramble domain (https://mozillathimblelivepreview.net) correct? And bramble is trying to load the `brackets.min.css` file from the service worker? If so, CSP rules from Thimble should not be leaking into the iframe. We do not enforce any CSP rules on bramble at all.

**Comment by humphd** [comment]
This was fixed by https://github.com/mozilla/brackets/pull/894.  See http://blog.humphd.org/promise-to-catch/ for more details.  The CSS CSP stuff is a red herring, I think.
