### ISSUE TITLE
<center> is not in the Tag library!

### ISSUE THREAD

**Issue by weaselboy2004** [mozilla/thimble.mozilla.org#2551]
<center> is not in the Tag library!

**Comment by gideonthomas** [comment]
Hi @weaselboy2004, thanks for filing this request. The tag library contains HTML tags that are HTML5 standard compliant. The `<center>` tag was deprecated a while ago and is not a part of the HTML5 specification.

Instead, if you would like to center content, what is now recommended is to use CSS rules like so:
- centering text: `text-align: center`
- centering non-text elements: `margin: 0 auto`

**Comment by Pomax** [comment]
On a modern web standards note, using `margin` to center non-text elements is an older solution, most modern browsers allow you to center elements (rather than text) through "flexbox" styling instead - see https://css-tricks.com/snippets/css/a-guide-to-flexbox/ for that topic.

**Comment by weaselboy2004** [comment]
Thank you for this info!!

Jack Magson
________________________________
