### ISSUE TITLE
Disable the right-click menu when editing HTML pages.

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.mozilla.org#2558]
Currently, if you right-click inside of the editor when editing an HTML page, you get the following menu...

<img src="https://user-images.githubusercontent.com/25212/32971909-64523ace-cba4-11e7-965c-6f1a2a1262a6.png" width="300" />

I don't think it's very useful. The Quick Edit & Quick Docs options show up even if they are not usable. When the Quick Docs work and expand within the editor, the link to _Read More_ takes the user to a 404. 

Since you still have to use the keyboard for pasting, having the cut/copy/paste actions doen't seem very handy.

Lasty, _Select All_ is rarely useful and can be accomplished in other ways.

**Comment by humphd** [comment]
Whoever works on this, that menu is defined here: https://github.com/mozilla/brackets/blob/master/src/command/DefaultMenus.js#L253-L269

**Comment by svitlana-galianova** [comment]
Hello, I would like to try to help out here

**Comment by flukeout** [comment]
Yes, please go ahead @svitlana-galianova ! Get rid of that menu!

**Comment by humphd** [comment]
@svitlana-galianova also note: you can probably "undo" a bunch of what was done in this PR when you do this, since we won't need that dialog anymore:

https://github.com/mozilla/brackets/pull/666

**Comment by gideonthomas** [comment]
@svitlana-galianova, I just noticed that someone else just submitted a PR for this issue. Have you started working on this?

**Comment by svitlana-galianova** [comment]
@gideonthomas unfortunately I haven't had a chance to look at it yet

**Comment by humphd** [comment]
@svitlana-galianova looks like you'll need another bug.  Sorry about that.  This sometimes happens, and it's unfortunate, but also the way with open projects.  Having said that, you did the right thing by making it clear you were working on this, and signalling to others that they should find another bug.  Not everyone pays attention, though.
