### ISSUE TITLE
Add info to "Black Screen of Death" error page about Third-Party Cookie issues

### ISSUE THREAD

**Issue by humphd** [mozilla/thimble.mozilla.org#2562]
In cases where users have enabled third-party or other tracking protections (notably in Firefox), we sometimes crash on startup because IndexedDB can't be loaded.  We currently [have a message about Private Browsing](https://github.com/mozilla/thimble.mozilla.org/blob/ea243750e1a09e850ddc07a31fcafc9660780b1c/views/editor/bramble.html#L201) mode (which also breaks in Firefox, though there is a fix that should land in Firefox 58 or 59).

It would be good to also add info about the effects of having third-party cookies disabled, see https://support.mozilla.org/en-US/kb/disable-third-party-cookies for example.  Obviously we can't force users to change this setting.  But it would be good to inform them so they understand what their choices are doing.

@flukeout could you help with potential wording/UI here?

I'm also going to try and do a memory-backed workaround for not having indexeddb.

**Comment by humphd** [comment]
See #2564, #2563 for the memory-backed filesystem workaround bugs.

**Comment by HansvandenPol** [comment]
Hello David, I'm interested helping with this bug.

**Comment by humphd** [comment]
OK, great, it's yours @HansvandenPol.  You may want to tackle all three of these bugs as a set, since they are related.

Start by [getting Thimble set up locally](https://github.com/mozilla/thimble.mozilla.org#setupinstallation), and then you can trigger this screen by running Firefox and opening Thimble in a Private Window.  Let me know if you have other questions I can help with.

**Comment by HansvandenPol** [comment]
Hello David,

I would like to work on the other bugs as well. I am only worried if I have
enough time for all of them, since the due date is next week.

Best regards,

Hans van den Pol


<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

2017-11-22 16:19 GMT-05:00 David Humphrey <notifications@github.com>:

**Comment by humphd** [comment]
@HansvandenPol if this is for your 0.1 release, I think just focus on this one bug, and do the others as your 0.2

**Comment by HansvandenPol** [comment]
Hi David, A question about the first bug: Do I need to check if the black screen was caused by having tracking protection enabled before printing the info?

**Comment by humphd** [comment]
@HansvandenPol good question.  No, I think you should probably just adjust the messaging about Private Browsing mode to include this extra info.  Doing so would mean a string change in the `en-US` locale file, and you'd need to change the string key to add a new version (e.g., `_2` on the end or something).

@flukeout can you weigh in here soon, since @HansvandenPol needs to get this in by Tues.

**Comment by HansvandenPol** [comment]
Thanks, also sometimes when I run Thimble in a private session the black screen won't appear (even though my tracking protection is enabled). The editor opens instead without content. Is there a way to force the black screen to appear to test the info message?

**Comment by humphd** [comment]
Which browser?  Also, what's in your console?  Can you include some screenshots here?

**Comment by HansvandenPol** [comment]
I'm using the latest Firefox browser. I also tried the cloned Firefox project, but I haven't pulled the most recent version. Unfortunately, my laptop is at home so I can sent you the screenshots after classes this afternoon.

**Comment by humphd** [comment]
We landed a fix recently to make Firefox work in a fallback mode when Private Browsing is enabled.  If you want to trigger this black screen, you'll probably need to roll-back Brackets.  In your Brackets repo, do this:

```
git checkout -b old-code c617cd985d0dc943d542c0ac8149fca3c5a1f8bf
```

Then you can start Brackets and it should break in Firefox.  You can switch back to the new code with:

```
git checkout master
# or flip back to the broken with
git checkout old-code
# etc
```

**Comment by HansvandenPol** [comment]
I rolled back Brackets to that commit, but the black screen still won't appear. It's weird, because yesterday I was able to see the black screen just fine. I will include the screenshots of the editor page and of both consoles.
![thimble editor](https://user-images.githubusercontent.com/14921415/33221424-78faebf0-d11d-11e7-9b77-93ab8bb75734.png)
![thimble console](https://user-images.githubusercontent.com/14921415/33221431-82f671b0-d11d-11e7-8d09-bfea0a9f1fbd.png)
![brackets console](https://user-images.githubusercontent.com/14921415/33221434-84b56ea2-d11d-11e7-82f1-3cbf296848a8.png)

**Comment by flukeout** [comment]
@humphd @HansvandenPol hey sorry, reading over the issue now and will chime in shortly!

**Comment by humphd** [comment]
@HansvandenPol in Firefox, open that page with the Web Console (dev tools) showing.  I want to see what's showing there.  This might be a CSP error.

**Comment by flukeout** [comment]
@HansvandenPol @humphd - locally I can't get the black screen to show up anymore. I'm only running thimble (localhost:3500) and not brackets, and that used to trigger the black screen. Is there a more reliable method?

**Comment by humphd** [comment]
@flukeout that's odd.  We should be showing that.

**Comment by flukeout** [comment]
@humphd can you get it to show up from latest master?

**Comment by HansvandenPol** [comment]
@humphd Is it an idea that I start on bug #2563? I don't want to request my current version, which adds the text explaining effect of having third-party cookies disabled, because I haven't tested it yet.

**Comment by humphd** [comment]
@HansvandenPol, yes, let's switch you over to #2563 and I'll close this.  I don't think this is turning out to be as necessary as I thought.
