### ISSUE TITLE
Allow memory-backed filesystem vs. indexeddb via URL param

### ISSUE THREAD

**Issue by humphd** [mozilla/thimble.mozilla.org#2563]
I'd like to experiment with a memory-backed filesystem in addition to the current IndexedDB one that we use.  Here's how I imagine it working:

* User hits https://thimble.mozilla.org, we default to the standard IndexedDB provider.
* User hits https://thimble.mozilla.org?brambleMemoryFileSystem we override to use `Filer.FileSystem.providers.Memory` when we create the filesystem in Brackets.  Thimble adds some kind of UI badge to alert the user to the fact that they are using a temporary filesystem (not sure of the right language here, needs thought) and that they will lose their work when they close the tab.  They can, however, still export a `.zip` file before they leave.

In Brackets, we create the filesystem here https://github.com/mozilla/brackets/blob/master/src/bramble/client/main.js#L123-L144.  The code would need to be changed to look for the presence of the `brambleMemoryFileSystem` query param on the URL, and if present, override the provider.  In Filer, you can do that like so:

```js
// Memory backed fs
fs = new Filer.FileSystem({
  flags: [ 'FORMAT' ],
  provider: new Filer.FileSystem.providers.Memory()
});

// Default IndexedDB backed fs
fs = new Filer.FileSystem({
  flags: [ 'FORMAT' ],
  provider: new Filer.FileSystem.providers.IndexedDB()
});
```

I'll file another bug on doing the UI in Thimble to warn when this mode is enabled, and also to add a button to the "Black Screen of Death" error page to enter it.

**Comment by humphd** [comment]
@HansvandenPol is going to tackle this.

**Comment by HansvandenPol** [comment]
@humphd I am not sure if you've seen my pull request yet. When the user hits the 'BrambleMemoryFileSystem' parameter the memory-backed filesystem is used instead of indexedDB fs.

Further, I'd like to work on the next bug (I think it was #2564) if it's still open
