### ISSUE TITLE
 cors error when accessing the domain from its sub-domain ( no error in chrome and safari only in firefox)

### ISSUE THREAD

**Issue by pawansaket** [mozilla/thimble.mozilla.org#2565]
I have a problem with firefox for its CORS policy. As, I have a domain and created a sub-domain for it. Now want to access domain from sub-domain I got cors errors ( app is on nodejs+expressjs+angularjs) ( only in firefox). Here is the code for CORS setting in nodejs:

var allowHeaders = ['Accept', 'Accept-Version', 'Content-Type', 'Api-Version', 'Origin', 'X-Requested-With', 'api-token'];

      res.header('Access-Control-Allow-Credentials', true);
       res.header('Access-Control-Allow-Headers', allowHeaders.join(', '));
       res.header('Access-Control-Allow-Methods', res.methods.join(', ')); // method is PUT,GET,OPTIONS
       res.header('Access-Control-Allow-Origin', origin);
       res.header("X-Frame-Options", "SAMEORIGIN");
       res.header('X-XSS-Protection', '1; mode=block');
       res.header('x-content-type-options', 'nosniff');
       return res.send(204);

![firefox-cors](https://user-images.githubusercontent.com/26107608/33165672-b16e131a-d05d-11e7-8477-fa54a6bbdb00.png)

**Comment by gideonthomas** [comment]
@pawansaket I don't follow, is this on Thimble? Or this your own website hosted somewhere and you're having issues on Firefox? If it's the latter, unfortunately this is beyond our expertise in this project. I do recommend filing a support ticket in https://support.mozilla.org/questions/firefox and someone who works on that project will be able to assist you better.
