### ISSUE TITLE
Remove iFrameBrowser.getDetachedPreview

### ISSUE THREAD

**Issue by humphd** [mozilla/thimble.mozilla.org#2573]
We have some remnants of code from when we supported detaching the preview to a separate window.  Once https://github.com/mozilla/brackets/pull/897 lands, which is removing some more, let's get rid of the rest.  Specifically, we can probably dump `getDetachedPreview` and any code that interacts with it.

**Comment by Avedis777** [comment]
Can I work on this bug?

**Comment by humphd** [comment]
@Avedis777 all yours.

**Comment by Avedis777** [comment]
Would I be making any changes to the Thimble repository? It seems like the only place getDetachedPreview is written is in Bramble main.js

**Comment by humphd** [comment]
The only place that should need to get touched here is in Brackets.

**Comment by Avedis777** [comment]
So how would I go about submitting my work? The issue is on Thimble but Bracket is the project being modified

**Comment by humphd** [comment]
Just do all your work in Brackets (i.e., pull request there vs. here).  We file bugs in Thimble because users' can't know whether a bug is part of Thimble or Brackets (or publish, or id, or login, or ...).  It makes it easier to file/find bugs for users, and slightly more complex for us as developers :)

**Comment by Avedis777** [comment]
I made a pull request [here](https://github.com/mozilla/brackets/pull/910)
