### ISSUE TITLE
Consider adding CSSAtRuleCodeHints, CSSPseudoSelectorHints from upstream

### ISSUE THREAD

**Issue by humphd** [mozilla/thimble.mozilla.org#2581]
https://github.com/adobe/brackets/tree/deeb74e694e64f5a78656286dcffd7e6b37857f2/src/extensions/default/CSSAtRuleCodeHints

Not sure if we care about this or not.  @flukeout do you want it?

**Comment by gideonthomas** [comment]
I vote for adding it! Seems useful especially since media queries are used a lot in responsive design curriculum

**Comment by humphd** [comment]
https://github.com/adobe/brackets/tree/deeb74e694e64f5a78656286dcffd7e6b37857f2/src/extensions/default/CSSPseudoSelectorHints is another one that does similar things.

Both of these could be basically dropped into Bramble and "just work" without modification.

**Comment by flukeout** [comment]
What is it? Have you tested it out? Post a screenshot?

**Comment by humphd** [comment]
They add CSS hinting for `@...` media queries and various pseudo selectors.

**Comment by flukeout** [comment]
Yeah let's slam it in there!

**Comment by humphd** [comment]
To whoever wants to do this, here's the process:

* From Adobe's repo, copy these two directories into our repo, making sure we keep license info in tact.
* Remove the `unittest.js` files
* Add 2 new entries to src/extensions/bramble-extensions.json for these extensions so these get loaded by Bramble, similar to https://github.com/mozilla/brackets/blob/master/src/extensions/bramble-extensions.json#L10-L12 should be enough.

**Comment by ericsuhn** [comment]
I'd like to do this!
