### ISSUE TITLE
Preview box only displays the URL of preview file

### ISSUE THREAD

**Issue by TakumaKawashiro** [mozilla/thimble.mozilla.org#2588]
The preview box in the editor displays the URL like "https://mozillathimblelivepreview.net/bramble/production/dist/vfs/[6NUMBERS]/projects/[7Numbers]/index.html" in IFRAME.

**Comment by TakumaKawashiro** [comment]
2018/1/4 15:21 (JST), this issue was cleared.

**Comment by humphd** [comment]
I think this should have been fixed with our recent work to deal with failed service worker installations and falling back to Blob URLs.  If you still see this happening, let us know.  Thanks for filing.
