### ISSUE TITLE
Selfie preview is inverted

### ISSUE THREAD

**Issue by bansalnitish** [mozilla/thimble.mozilla.org#2593]
The selfie image as well as the preview is flipped. In most of the apps and cell phones the selfie image is flipped but the preview is not. This seems better to me to have such (flipped of what we have) preview keeping the selfie image as it is.

Steps to reproduce:
1. Click on get started.
2. In the editor write `<img src = "">`
3. You will see a Take a selfie option, click on that.

**Comment by humphd** [comment]
The fix for this is likely two-fold.  We should probably use the JS and CSS methods described at https://stackoverflow.com/questions/3129099/how-to-flip-images-horizontally-with-html5 and fix 
https://github.com/mozilla/brackets/blob/master/src/extensions/default/BrambleUrlCodeHints/camera/interface.js#L78-L106 and https://github.com/mozilla/brackets/blob/master/src/extensions/default/BrambleUrlCodeHints/camera/selfieWidget.html#L4 so they display as you'd expect.

**Comment by bansalnitish** [comment]
@humphd I would like to work on this. I feel this can be fixed with css only. Adding the following css would flip the preview:
`-webkit-transform:` rotate(180deg);     /* Chrome and other webkit browsers */
  -moz-transform: rotate(180deg);        /* FF */
  -o-transform: rotate(180deg);          /* Opera */
  -ms-transform: rotate(180deg);         /* IE9 */
  transform: rotate(180deg);             /* W3C compliant browsers */`

**Comment by humphd** [comment]
Thanks @bansalnitish, it's all yours.  Flipping the preview is good, but what about the final image?  Maybe it's already the way you want?  If not, you'll need to translate that canvas too, before we save the image to disk.

**Comment by bansalnitish** [comment]
Yes, I feel the final image should remain flipped. In various other selfie apps as well as on cell phones, the preview is not flipped but the final image is flipped. What do you think?

**Comment by humphd** [comment]
Personally, I've always hated that the final image is different from the preview.  However, I'd say "do what won't surprise users," and if this is what phones do now, let's just do what they do.

**Comment by gideonthomas** [comment]
@xmatthewx, would you be able to provide some input here?

**Comment by xmatthewx** [comment]
I agree, do what won't surprise users. Follow the most common pattern in the wild, diverge only if there's an _overwhelmingly_ compelling reason.

**Comment by bansalnitish** [comment]
@humphd this issue should be closed !
