### ISSUE TITLE
Deleting projects: just published version.

### ISSUE THREAD

**Issue by trishla08** [mozilla/thimble.mozilla.org#2600]
If I just published a project, closed it and the next day, I want to remove the published version only, how do I go about doing that? I do know that when we publish it, we get the option immediately but I couldn't find the option once I closed that window. On going to my project page: (https://thimble.mozilla.org/en-US/projects/), deleting it gives me the message that both versions will be deleted.  

I think there should be an option to delete both published and actual version or just published once we click on 'delete'.

**Comment by gideonthomas** [comment]
@trishla08, if you open your project and click on the "publish" button, you should see a "Delete Published Version" button that should do what you want.
<img width="545" alt="screen shot 2018-01-18 at 12 47 00 pm" src="https://user-images.githubusercontent.com/5816130/35112965-d7ee1118-fc4d-11e7-84a6-5b3c22bb827f.png">
If you don't see this button, feel free to comment back in this issue.

**Comment by trishla08** [comment]
@gideonthomas I can't view that option once my project is already published, I have closed it and reopened it. To be clear, when I visit my projects and open a published project from there, and click on publish, the following appears:
![image](https://user-images.githubusercontent.com/27439626/35197304-45570d42-ff03-11e7-8171-0d66b6cb573d.png)
A 'delete published version' would be great to have next to the 'cancel' button or somewhere in the 'my projects' window.

**Comment by gideonthomas** [comment]
@trishla08, I think having that button might clutter the my projects page a bit but maybe we can come up with some form of acceptable UI.

Until then, your specific issue seems like a bug. Would you be able to share your published project url?

**Comment by trishla08** [comment]
@gideonthomas somehow I can now see the delete published version only when I click on publish. I am positive it didn't show up when I tried it yesterday but it does now, I guess it was some other glitch yesterday. It's working as it should now, this can be closed! Thank you!
