### ISSUE TITLE
Extend Quick Edit UI for border-radius

### ISSUE THREAD

**Issue by bansalnitish** [mozilla/thimble.mozilla.org#2602]
Quick edit UI works perfect for `border-radius` but not for `border-top-left-radius` , in general not for `border-top/ bottom-left/right-radius`.

![Imgur](https://i.imgur.com/NebFjFd.png)

I would like to extend this !

**Comment by gideonthomas** [comment]
@bansalnitish go for it! You'll need to modify a few things in the inline editor - for e.g. the regex, the html template, the InlineBorderRadiusEditor function to only enable a single value in this case. Let us know if you need any help in figuring this out.

**Comment by gideonthomas** [comment]
Fixed with mozilla/brackets#920
