### ISSUE TITLE
Website Problems

### ISSUE THREAD

**Issue by cheesemanq** [mozilla/thimble.mozilla.org#2603]
Can you please help me fix my project here is the link:
https://thimble.mozilla.org/en-US/user/demond/1419551/

**Comment by gideonthomas** [comment]
@cheesemanq what problem are you experiencing?

**Comment by cheesemanq** [comment]
I cannot get into my project even when I type into the search bar ?cacheType=blob

**Comment by cheesemanq** [comment]
![screen shot 2018-01-26 at 11 42 03 am](https://user-images.githubusercontent.com/35706422/35450514-454eeae8-028e-11e8-8869-0dbbf3237fed.png)

**Comment by cheesemanq** [comment]
That's the error message I get. If I reload it, it says the same thing. This happens on multiple devices. Thanks for the help!

**Comment by gideonthomas** [comment]
@cheesemanq sorry, you are experiencing this. Would you be able to check your cookie settings? Do you block all cookies, or thirdparty cookies, or do you allow all cookies? Also, which browser are you using?

**Comment by Eqilux** [comment]
I know I shouldn't be bumping this issue, but it's really urgent. I'm having the same issue too, and the project I'm making in thimble is for work, and I need it restored ASAP.

**Comment by humphd** [comment]
@Eqilux are you able to open your browser's console and see any errors?

**Comment by humphd** [comment]
Closing due to lack of info.  If this persists, please re-open.
