### ISSUE TITLE
Possible to embed flash games?

### ISSUE THREAD

**Issue by LLuLukLuke** [mozilla/thimble.mozilla.org#2605]
I'm new to HTML and webpage design, but am familiar with programming in general. I'm wondering if it is possible to embed flash programs into mozilla thimble webpages, such as a flash game. I have tried a few methods with no luck, any way I can go about doing this?

**Comment by humphd** [comment]
You'll find that most browsers will block Flash in a web page, due to security.  Thimble will allow it, but it won't work in practice.  You'd be better off using HTML5 for gaming, which has replaced Flash.

**Comment by LLuLukLuke** [comment]
Okay, so how do I do embed it then?

**Comment by humphd** [comment]
See https://stackoverflow.com/questions/7538286/how-to-embed-a-flash-object-on-my-website
