### ISSUE TITLE
Console error with 3rd party cookie blocking enabled on chrome stable

### ISSUE THREAD

**Issue by User486375** [mozilla/thimble.mozilla.org#2607]
I get this console error when I enable `Block third-party cookies` on the latest stable chrome 64 build, but I get no such error on the latest stable Firefox build with the same setting enabled.

![chrome_2018-01-27_17-56-48](https://user-images.githubusercontent.com/30012923/35474867-37ce5a3a-038c-11e8-85ed-0ce6748550eb.png)

**Comment by humphd** [comment]
There's a fix for this in review now, see https://github.com/mozilla/brackets/pull/919.  I'm going to close this, since we have it in hand.  However, I appreciate you filing it.
