### ISSUE TITLE
Fix regression for Browser.setListener in iframe-browser.js

### ISSUE THREAD

**Issue by humphd** [mozilla/thimble.mozilla.org#2608]
From https://github.com/mozilla/brackets/pull/913#discussion_r165143030 we have a regression in Brackets where we've removed a function on `iframe-browser`, but not dealt with all callers.  We should either add it back, or remove the caller.

Thanks to @azusaaz for tracking this down.

**Comment by ayush9398** [comment]
I would like to take this up

**Comment by ayush9398** [comment]
is this still available? @humphd @gideonthomas

**Comment by ryanwarsaw** [comment]
@ayush9398 I've assigned you to this ticket, and am working on getting you access to the contributor Slack in-case you have questions along the way (will update later today).

**Comment by ayush9398** [comment]
oh, okay! Thanks @ryanwarsaw !!

**Comment by ryanwarsaw** [comment]
@ayush9398 You should have access to the contributor slack now (sent to email listed on your GitHub), you will need to join the MoFo contributors channel. That would be the place to go if you have any questions or need help, cheers.

**Comment by ayush9398** [comment]
@ryanwarsaw do you mean channel contribute-code, actually I had a query, do I have to remove the caller from all the scripts in thimble and brackets as well, if there are any?
@humphd

**Comment by ryanwarsaw** [comment]
@ayush9398 Yep, that's the correct channel! I don't have an answer to your question, definitely @humphd or @gideonthomas would be able to better assist you in that area.

**Comment by humphd** [comment]
I think we should add the function back, since other sites are still calling it.  I'd have to dig into whether or not they are still necessary, but at least we shouldn't crash on them not being there.

**Comment by humphd** [comment]
Reading the code again, I'd suggest you remove this caller instead: https://github.com/mozilla/brackets/blob/master/src/extensions/default/bramble/lib/PostMessageTransport.js#L114

**Comment by ayush9398** [comment]
@humphd I have opened the [PR](https://github.com/mozilla/brackets/pull/922)

**Comment by gideonthomas** [comment]
Fixed with mozilla/brackets#922
