### ISSUE TITLE
ngRoute = 100% RAM and freeze in thimble

### ISSUE THREAD

**Issue by Mlocik97-issues** [mozilla/thimble.mozilla.org#2609]
Write this code:

https://www.w3schools.com/angular/angular_routing.asp

Thimble will freeze and after few minutes browser is using a lot of ram (8GB +)

**Comment by gideonthomas** [comment]
@Mlocik97-issues, which browser are you using?

**Comment by Mlocik97-issues** [comment]
Chrome 63 & 64

**Comment by Mlocik97-issues** [comment]
It happend also in firefox 55

**Comment by gideonthomas** [comment]
hmm, which example from that page are you using? I can't seem to reproduce this issue. Do you have any extensions installed that might do this (for e.g. anything javascript related)

**Comment by humphd** [comment]
Closing due to lack of info.  If this problem happens again, please re-file.
