### ISSUE TITLE
Images not uploading into Thimble.

### ISSUE THREAD

**Issue by ichibangaijin** [mozilla/thimble.mozilla.org#2615]
Issue suddenly appeared yesterday.  Unable to drag-n-drop image files or upload image files.

**Comment by gideonthomas** [comment]
Hi @ichibangaijin sorry that you're encountering this issue. Looks like we are currently having problems with image uploads. We hope to resolve this within the next hour.

**Comment by gideonthomas** [comment]
This should be working now, let us know if you're still having issues with it.
