### ISSUE TITLE
unable to upload images.

### ISSUE THREAD

**Issue by jmortizruiz** [mozilla/thimble.mozilla.org#2616]
Hello,

I'm trying to upload a small image (25kB png format) and I'm having a lot of problems to do so. I've tried in different computers with different operating systems and different wifi networks. Is there any trouble right now with the servers?. Is it just me?

thanks

**Comment by gideonthomas** [comment]
Hi @ichibangaijin sorry that you're encountering this issue. Looks like we are currently having problems with image uploads. We hope to resolve this within the next hour.

**Comment by jmortizruiz** [comment]
I just saw another issue report as soon as I sent mine so I figured that out.
Thanks for your promt answer.

**Comment by gideonthomas** [comment]
No  worries! Let us know if you're still having any issues
