### ISSUE TITLE
[Bracket Module] I cannot run Bramble in Production.

### ISSUE THREAD

**Issue by paiboonpa** [mozilla/thimble.mozilla.org#2626]
If I run "npm start" and access "src/hosted", It's working fine. If I run "npm run production", when I access index.html or hosted.html in dist directory, result of the page would be something like this:

"��X[S�H~�W�855@Y�d'�:�0A;Ʀl3O[����Z�nީ������[2UL%O[k.���K�>�ޫXEfQJL�����^9�ѹ*��'���:9:>!��Rh��b �,��&?�TY�20"�d7j���#�G��e&��*'�)�4/��4+� 5�(	ʹh�Q�*D��A�&����)w��$�jf��R`yL��*�� A�*��a�3� M�&Ԛ,w���X)�x��{�&Q�a1L)#FicQ�V1��L�2�5 ��Rz�Vr0�m�T,g�-�pE�R'm�%����J̓�ȱP��U%i�C�{+�ö�t�#�T�f���13�Y�Uͪ2Y(��VP���YD�G���JS��F*�%K�����b>գ�B��+�kN�4,/�!/�t@L�;�9˷!ĬBm`	[�dw�m�hzէ��rz���O�f<�տ�_P˛�զ;z5��V�����F�� ��xѦ�o7��dB�1��o~���|p{�?�vGS�����1�%����K��ϯ���z�'v�O��{9�G7�x���1�܎oF�>X���^�A��N;��1����\y��w��%��n�����)]�}����w6��� �����t�]{���1����G���� ���{>�GC�|4���چ���j�?������G ���Pv�5+�*ju6X����\���pTí�=�aĎ�t��=|l͂T��)fD���^&L`]��c�23�=V�)#M*N{n��W«��d�����]��K�3����G:�_���S���碤Hk���a�wM�*�? S=4˭�2(j�܊����c "

Is it in binary form? How can I run it in dist dir?

**Comment by ryanwarsaw** [comment]
I really don't have enough information to be able to give you an informed answer, it sounds more like an issue with your encoding than with brackets, so I'm going to close this but if you have any more questions or this continues to happen, feel free to reach out again (please give us as much information as possible!). 😅
