### ISSUE TITLE
[Bracket Module] What's the license of Bramble?

### ISSUE THREAD

**Issue by paiboonpa** [mozilla/thimble.mozilla.org#2627]
If I look at this repository of thimble, it said MPL. If I look at https://github.com/mozilla/brackets, it's MIT. However, while I using Bramble, there's a lot of Thimble word showing around in the source code. What's the license of Bramble if I use only Bramble not Thimble? Is it MIT or not?

**Comment by gideonthomas** [comment]
Thimble is an independent module that makes use of Bramble and therefore has its own license (MPL). This does not apply to any modules that Thimble depends on. 
Bramble on its own is under the MIT license.
