### ISSUE TITLE
Add Polish 'pl' translation

### ISSUE THREAD

**Issue by evolic** [mozilla/thimble.mozilla.org#2631]
The goal is to add Polish language to Thimble.

**Comment by ryanwarsaw** [comment]
We can't add translations directly, you need to use Mozilla's tool for translating called `Pontoon` it's a pretty awesome tool, you can check it out here: https://pontoon.mozilla.org/ 

If the language you want to translate doesn't exist yet, then @TheoChevalier I believe is able to add it, and let me know if you have any other questions 🕺
