### ISSUE TITLE
Don't have option to clone the project.

### ISSUE THREAD

**Issue by mohitepm1998** [mozilla/thimble.mozilla.org#2647]
Add option to create dublicate project.
If I need to create the clone of any project then I required to copy all the files from old 

![openedwithimage](https://user-images.githubusercontent.com/32018912/43539416-75e8b200-95e2-11e8-9d89-f307c561c9cc.png)

**Comment by ryanwarsaw** [comment]
@mohitepm1998 that's pretty much what the remix feature does, unless I'm mistaken. Try that out, and let me know what you think / if you have any other questions.

**Comment by mohitepm1998** [comment]
but we required to publish the project first.

**Comment by Pomax** [comment]
you can download the project as a .zip file, which you can unpack, and then you can create a new project and drag all the files back into the file tree

**Comment by mohitepm1998** [comment]
If my file contains 2GB  videos then it takes double time to download and again upload the file.

**Comment by ryanwarsaw** [comment]
You can either `Publish -> Remix -> Unpublish` to copy without downloading, or as @Pomax suggested you can download your project files, then upload them again to create a duplicate project. Those are currently the only two methods of doing this.

Those two methods seem to suit most of our users needs, it would be neat to have a feature like this, but I'm afraid it's not warranted for the resources necessary to implement it. I'm going to close this issue, but feel free to reach out if you have any other questions!

**Comment by Pomax** [comment]
You really shouldn't be using Thimble with large files, though. If your project has 2GB of videos, upload those to a video service and link to them from your html files. Putting 2GB in Thimble is basically abusing it as a file host instead of a simple website builder.
