### ISSUE TITLE
scroll-behavior property does available for auto suggestions in css.

### ISSUE THREAD

**Issue by mohitepm1998** [mozilla/thimble.mozilla.org#2648]
scroll-behavior:auto;
scroll-behavior: smooth;
scroll-behavior: inherit;
scroll-behavior: initial;
scroll-behavior: unset;

![annotation 3](https://user-images.githubusercontent.com/32018912/43602054-7861b41c-96ac-11e8-88f2-861df60e5216.png)

**Comment by Pomax** [comment]
This is not an adopted CSS property yet. It only has support from two browsers at the moment, and the specification for it has not moved past draft status yet.

See https://caniuse.com/#search=scroll-behavior
