### ISSUE TITLE
I can't log in...

### ISSUE THREAD

**Issue by angelab1030** [mozilla/thimble.mozilla.org#2649]
I was resetting my password but it wasn't responding so I PRESS a couple more times. But then I couldn't log in, it bought me to the error page. I try to rest my password a couple more times, but this time pressing only once... Still bought me to the error page... Can't log in now.

**Comment by ryanwarsaw** [comment]
Hi @angelab1030, apologies for late response, can you verify that this is still an ongoing issue? cheers!
