### ISSUE TITLE
Export CTA dialog on homepage

### ISSUE THREAD

**Issue by gideonthomas** [mozilla/thimble.mozilla.org#2656]
**Behind feature flag - GLITCH_EXPORT_ENABLED**

Layout: https://projects.invisionapp.com/share/6YN7CXIKHQN#/screens/312632667_Homepage_Colour_Option_2
Comp reference: https://drive.google.com/file/d/1LRqVEFARgJ3o7J7RNm6sVlYplB4_jLnx/view?usp=sharing

A dialog should show up only for authenticated users when they land on the homepage that shows the CTA for migrating their projects. It should show up after a 2s delay (play around with it to see what looks smooth). 

Notes:
1. The date/month/year string in the text should be an environment variable (GLITCH_MIGRATION_DATE) so that we don't need any more code changes.
2. The button should take you to the project list page.
3. On dismissing the dialog, the dialog and overlay vanish and instead a banner (that cannot be closed) shows up (comps/implementation in a subsequent ticket).
4. Link at the bottom should be an environment variable (GLITCH_HOMEPAGE_DIALOG_BLOG_POST).
5. Strings should be localized.

**Comment by Pomax** [comment]
closed by PR.
