### ISSUE TITLE
QA: Export banner on homepage

### ISSUE THREAD

**Issue by gideonthomas** [mozilla/thimble.mozilla.org#2661]
1. `.export-button`
  a. Border radius - 5px
  b. padding - top/bottom 9px, left/right 10px
  c. :hover/:active - background - #70e8b8
2. `.glitch-logo`
  a. width/height - 40px
  b. vertical-align - middle

**Comment by Pomax** [comment]
blocked by https://github.com/mozilla/thimble.mozilla.org/pull/2663, which moves and modifies the glitch styling, so working in these QA notes before that lands will be a bad idea.

**Comment by Pomax** [comment]
this got done as far as I know.
