### ISSUE TITLE
Export dialog in project list

### ISSUE THREAD

**Issue by gideonthomas** [mozilla/thimble.mozilla.org#2664]
**Behind feature flag - GLITCH_EXPORT_ENABLED**

**Layouts:** 
1. https://projects.invisionapp.com/share/6YN7CXIKHQN#/screens/312645378
2. https://invis.io/6YN7CXIKHQN#/312645377_Project_List_Copy_2
3. https://projects.invisionapp.com/share/6YN7CXIKHQN#/screens/312645379

**Comp reference:** https://drive.google.com/file/d/1LRqVEFARgJ3o7J7RNm6sVlYplB4_jLnx/view?usp=sharing

When the Export button is clicked in the project list, a dialog should pop up as per the layout above letting the user know about the export process for Glitch, and show buttons to continue with the export.

**Notes:**
1. Based on whether the export button was clicked for a project that has a published version or not, either layout 1 or 2 will be shown. If the project has a published version, layout 1 will be shown, otherwise layout 2 will be shown.
2. In layout 1, once one of the buttons is clicked, the other button will be greyed out as seen in layout 3 and the clicked button will say "Exporting..." (this text is also the same for layout 2).
3. On clicking the button a bunch of XHR requests happen as detailed below.
4. Strings should be localized.

**XHR Requests and Redirects**
1. An XHR POST request is made to the Thimble server to `/projects/<project id>/export/start/ ` (implementation pending) if the "Export project" button was clicked or to `/publishedprojects/<published project id>/export/start/` if the "Export published project" button was clicked.
   - The response from this route will be in the format: `{ "token": "<random hash>" }`. 
2. Once the token is received, the page will redirect to `<GLITCH_IMPORT_PROJECT_APP_URL>` (this should be an env var) with the following query params - 
   - `token` - The token received in the previous request
   - `id` - The project (or published project) id of the project that needs to be exported
   - `published` - A boolean indicating whether we're exporting the published project or the unpublished project.

**Comment by Pomax** [comment]
It would be good if we also had some messaging around how to let the user know that our `.../start` route(s) failed:

- calling the URL works, but the result does not have a `{token:...}`
- calling the URL fails (e.g. the user's router has a melt-down after loading the projects page)

**Comment by gideonthomas** [comment]
Hey @jgmac1106 this is something that Glitch might be able to do on their end when importing each project - you can probably [email them](mailto:support@glitch.com) and ask if they're able to support this.
