### ISSUE TITLE
Export FAQ

### ISSUE THREAD

**Issue by gideonthomas** [mozilla/thimble.mozilla.org#2665]
**Behind feature flag - GLITCH_EXPORT_ENABLED**

**Layout:** https://invis.io/6YN7CXIKHQN#/312632663_Moving_To_Glitch_Copy

**Comp reference:** https://drive.google.com/file/d/1LRqVEFARgJ3o7J7RNm6sVlYplB4_jLnx/view?usp=sharing

This is an FAQ page that will answer questions that users might have about the migration and why we're doing it.

**Notes:**
1. Add a nav item called "Moving to Glitch".
2. For the styling, follow the same rules as the "Get Involved" page that already exists (as opposed to being strict to the layout above). So that means:
   - font-size for top paragraph and questions: 1.125em
   - font-size for rest of the text: 1em
   - line-height: 150%
   - color: rgba(0,0,0,.65)
   - font: Open Sans
   - regular font-weight: 400
   - link color: #268cb9
   - horizontal line color: #cacaca
   - top/bottom padding between questions - 20px
The rest can be approximations.
3. The email should be an env var - `GLITCH_SUPPORT_EMAIL`.
4. Strings should be localized.

For now use the following gif: 
![glitch-assets](https://user-images.githubusercontent.com/5816130/45183091-19082900-b1f1-11e8-9093-eeda5c4314eb.gif)

**Comment by gideonthomas** [comment]
# Copy

Mozilla has made a strategic decision to sunset Thimble within the course of 2018-2019. To continue supporting our Thimble community, we have partnered with Glitch (created by [Fog Creek Software](https://www.fogcreek.com/)). [Read our blog post](https://about:blank) to learn more about this partnership.

To make this process simple for you, we have answered some common questions you might have. If you don’t find your question here, shoot us an email at [email@mozillafoundation.org](https://about:blank) and we’d be happy to chat with you.

### FAQ

**What do I need to do?**
We encourage you to export your projects over to Glitch. In the project list, you can transfer each project individually. Don’t forget to do this by December 1, 1989.

---

**What is Glitch?**
Glitch is a creative community that gives you the tools to create any app or website that you can imagine — and it's **free**! Like Thimble, it allows you to remix and tweak web projects to learn and build new content and put your own spin on it. [Click here](https://glitch.com/about/) to learn more about Glitch and what it can do.

---

**Is Glitch available in my language?**
Currently Glitch is translated in English. However, the Glitch team is committed to supporting more languages soon.

---

**Will my Glitch project work the same way as it does on Thimble?**
Once you export your project to Glitch, you should expect a few differences from Thimble:
1. Glitch advocates for openness on the web. This means that when you export your project, both the project and the code will be live and public by default. Before you export your project, you will be asked if you want to export the published or the work-in-progress version. If you need to, you can [make your project’s code private](https://glitch.com/help/privateproject/).
2. Tutorial files are regular files on Glitch. You will need to open the tutorial file in your live project to see the tutorial.

---

**Help! My images (and other linked files) don’t show up in my live project.**
Glitch groups all your non-textual files like images, videos, audio, etc. under the assets folder. When you export your project to Glitch, all of these files will be moved into the assets folder. 

You can get your links working again by simply updating them with the URLs provided for each file in the assets folder.

---

**What happens to my project on Thimble after I export it over to Glitch?**
Your project will still remain in Thimble, and if published, the live link will still be active. However, all projects and user accounts will be deleted by December 1, 1989.

---

**Can I continue using Thimble until I export over my projects?**
Absolutely! But, we will be turning off features in Thimble over the course of the year. Here’s our timeline for shutting down services:
    **January 10, 1989** - Turn off Publishing and Remixing
	**May 10, 1989** - Turn off creating new accounts
	**September 10, 1989** - No new accounts can be created
	**December 1, 1989** - All projects, user accounts, and published projects will be deleted

---

**Comment by Pomax** [comment]
Where are all these dates coming from? New environment variables?
