### ISSUE TITLE
Uable to log in

### ISSUE THREAD

**Issue by Kelprim** [mozilla/thimble.mozilla.org#2680]
Hello!

Yesterday I have been using Thimble and it was working perfectly. However, when I tried to use it  today, I was unable to log in. I have tested in several computers and the problem still persists. I also changed from network but the problem it's still there.

**Comment by StevePaget** [comment]
The developer console is telling me there's a 500 server timeout error.

**Comment by ryanwarsaw** [comment]
Hey folks, should be fixed now, let us know if it's still not working. Thank you for reporting!
