### ISSUE TITLE
Wiki changes

### ISSUE THREAD

**Issue by moz-hwine** [mozilla/thimble.mozilla.org#2710]
FYI: The following changes were made to this repository's wiki:

- Restricting write access to contributors is strongly encouraged.  Please [make that change](https://github.com/mozilla/thimble.mozilla.org/settings)  ([documentation](https://help.github.com/articles/changing-access-permissions-for-wikis/)).

These were made as the result of a recent automated defacement of publically writeable wikis.

**Comment by ryanwarsaw** [comment]
@moz-hwine Thanks for following up, I've alerted DevOps team for Foundation projects and will share this with them as well.

**Comment by moz-hwine** [comment]
settings are good
