### ISSUE TITLE
The function requestFullscreen() not working in javascript.

### ISSUE THREAD

**Issue by PratikMMohite** [mozilla/thimble.mozilla.org#2712]
`https://developer.mozilla.org/en-US/docs/Web/API/Element/requestFullScreen`
`https://www.w3schools.com/jsref/tryit.asp?filename=tryjsref_element_requestfullscreen_exit`

**Comment by Pomax** [comment]
Hi @PratikMMohite, Thimble is no longer being worked on, and people are encouraged to switch to Glitch instead, and any projects you have can be automatically migrated from within Thimble. Please see https://medium.com/read-write-participate/a-note-about-thimble-b8ba0a51b8fd for more information.
