### ISSUE TITLE
Better message when there's a space before DOCTYPE

### ISSUE THREAD

**Issue by pamelafox** [mozilla/thimble.mozilla.org#471]
If you put a space before the doctype, you get a confusing message about HTML tags:
https://pamela-from-khan.makes.org/thimble/LTEzNDgwNzI5Ng==/challenge-avatar-attributes

I'd expect instead to see a message about no space before the DOCTYPE.

**Comment by humphd** [comment]
@Pomax, this sounds like it belongs in slowparse, can you confirm?

**Comment by flukeout** [comment]
Closing, as there is no error message shown in thimble anymore when there is a space in front of the doctype. Maybe this was an Old Thimble bug.

![image](https://cloud.githubusercontent.com/assets/25212/21998608/c016a782-dbea-11e6-8daf-8ecba8cac043.png)
