### ISSUE TITLE
Support for Collaborative Editing

### ISSUE THREAD

**Issue by humphd** [mozilla/thimble.mozilla.org#485]
From email today:

<blockquote>Allow multiple people to work on the same code at the same time, like Google Docs, Etherpad or JSFiddle. That will make it a lot easier to teach, as we can have teams and mentors all in the same project.</blockquote>

**Comment by Pomax** [comment]
this would be super nice.

**Comment by humphd** [comment]
cc @AndyForest

**Comment by davidascher** [comment]
Cc @simonwex re togetherjs and related tech.

**Comment by simonwex** [comment]
TogetherJS would make the most sense. It'd be nice to spend some design cycles here, too. There are some simple changes we could implement in togetherjs that would be a win for everyone.

**Comment by humphd** [comment]
So you think TogetherJS could be taught about UI state?  What about initial filesystem sync?  Seems like there are some hard problems to cope with; but maybe those problems are part and parcel of doing this at all, and TogetherJS gets us there faster?

**Comment by sedge** [comment]
I moved this into our overflow milestone because this was the first feature a user requested.

**Comment by simonwex** [comment]
You can send custom events over the TogetherJS pipe and could use that for sync quite easily. Part of that is done automatically, in fact.

**Comment by humphd** [comment]
Talking about this with @flukeout today, and another idea would be to use Slack per-project (i.e., everyone who remixes project X might be in same room): https://api.slack.com/  Not in scope for now, but dropping a link for someone in the future.

**Comment by humphd** [comment]
It's not looking like this is going to happen any time soon.  Let's re-file if we decide to prioritize later.

**Comment by hannahkane** [comment]
Another request via email: "Is it in the plans to make live collaboration possible through Thimble? It would be nice to have that feature (just like how Google Docs allows multiple live collaborators on a single document)."

**Comment by chadsansing** [comment]
Would also be handy for the Mozilla Curriculum Workshop.

**Comment by jasonjurotich** [comment]
I would also love to see some real time collaboration (similar to what togethersj had) in Thimble. It would make it a game-changer for the classroom.

**Comment by Coder206** [comment]
Is anyone implementing this?

**Comment by humphd** [comment]
I'm not aware of anyone working on this, no.  One of the concerns I have about using TogetherJS is that it isn't maintained any more.  If we decide that collaborative features are important to do in Thimble, we should probably evaluate the possible options, and especially look for things that still have devs engaged.

**Comment by humphd** [comment]
As an example, Google provides an API for this, https://developers.google.com/google-apps/realtime/overview.  It's basically all the features of collaboration in Google Docs for an arbitrary app.  Lots of upside to this, with the obvious downside being that it ties you to Google's system.  One might argue that this isn't all that bad, especially if you want to make an app like Thimble work really well on things like Chromebooks.

**Comment by gideonthomas** [comment]
Moving this discussion to #1531
