### ISSUE TITLE
Develop a migration strategy for single-file to multi-file projects when old-thimble is deprecated

### ISSUE THREAD

**Issue by simonwex** [mozilla/thimble.mozilla.org#509]
Made with Code is a significant source of traffic for thimble. We'll need to continue to support or transition these projects to Bramble. We could alternatively have these project pages link to old-thimble, which would invalidate my opinion here: https://github.com/mozilla/thimble.webmaker.org/issues/505#issuecomment-101761608

Here's an example:
https://webmaker.org/en-US/madewithcode-meme

**Comment by sedge** [comment]
There was [some](https://github.com/MozillaFoundation/mofo-devops/issues/66#issuecomment-101725886) [discussion](https://github.com/MozillaFoundation/mofo-devops/issues/66#issuecomment-101739393) about making all thimble projects the same under the hood. We lacked a compelling reason to do the extra schema work to make this possible though. 

The simplest solution is as you say, keep old-thimble.

**Comment by sedge** [comment]
I'm going to morph this bug into finding a migration strategy for single-file to multi-file projects

**Comment by humphd** [comment]
@hannahkane was discussing this with me today, wondering if it's doable.  @sedge, can you estimate the work involved in this, now that we know more about how all the systems work?

**Comment by jgmac1106** [comment]
After beta testing new thimble with a few power users they all went to old Thimble and cut and pasted a project from old to new when I asked them to test "new project" feature.

This got me thinking about this issue. Could we do any of these:
* Send emails encouraging people to copy projects they make and then set a date that old Thimble projects are read only.
* Somehow make the single html files downloadable and then set a sate that old Thimble projects are read only.

I figure the majority of users have one-off projects. They attended an event or had to use webmaker for class and then never returned.

The user base who wants access to older projects is probably smaller and more skilled. Like I said the one's I worked with migrated their pages without being asked.

**Comment by humphd** [comment]
We had a meeting today to discuss this.  Deprecating Old Thimble will depend on a number of factors, and we'd like to move forward with this part of it independently.  Instead of a bulk import from old- to new-Thimble, we're going to try and do the following:
* continue to host old Thimble Makes on their current URLs
* allow a user to see their old-Thimble makes in the new-Thimble project list and open or delete them.
* remixing an old Thimble make would cause it to open in the new Thimble and follow the new flow

Questions:
* Does opening an old Thimble make allow someone to update the old content (i.e, changes saved back to old URL) or does it create a new one?  I would recommend the latter, since not all changes you do in the new editor can be show in the old system (e.g., multiple files).

Making this work will require changing a number of things, so this bug is about creating a work plan, and we'll do the work in new tickets.

cc @Pomax, @jbuck, @ldecoursy, @xmatthewx, @hannahkane

**Comment by jbuck** [comment]
Can you explain why you wouldn't want to do a bulk import of classic thimble data? Is the idea that you don't want make classic thimble read-only?

**Comment by jbuck** [comment]
Oops, didn't even answer your question!

> Does opening an old Thimble make allow someone to update the old content (i.e, changes saved back to old URL) or does it create a new one?

It allows someone to update the old content

**Comment by humphd** [comment]
The reason they said they didn't want it (I'm recording what Lanie, Hannah, Simon, Matthew said), is that they need/want to support the old URLs, and moving things into the new Thimble would (currently) break those.  Maybe there is a desire to migrate and not break old URLs, but that wasn't discussed.

RE: my question, it wasn't me not knowing the answer, but that there could be two right answers, and we need agreement; a discussion point still to be fleshed out.

**Comment by jbuck** [comment]
I think we should consider doing a mass migration from old Thimble to new Thimble instead of doing some sort of API integration between the two. It'll be a one-time cost to pay and then we can move forward with new Thimble. My proposal:

1. Turn old Thimble read-only
2. Run a database migration that converts old thimble makes into publish.wm.o projects
3. Redirect makes.org urls to new thimble project urls
4. Redirect thimble.webmaker.org to thimble.mozilla.org

@hannahkane @humphd Thoughts?

**Comment by humphd** [comment]
I think this sounds like the most reasonable approach, agreed.  It's implied in what you wrote, but this would mean turning off edits/changes to anything on makes.org, so it remains stable.

**Comment by jbuck** [comment]
@humphd Ah yes, good point. Updated my comment with that

**Comment by hannahkane** [comment]
Want to make sure I understand this from the user perspective. Is this correct?

 * Time between step 1 and step 2: if I go to a make on Old Thimble, it will be read-only, and I have no work-around
 * Once step 2 happens: when I go to any url for an old make, it will open on the new Thimble prod server, where I can hit Remix
 * If I go to thimble.webmaker.org, I'll be redirected to new thimble

Questions:
 * Can I access my old makes from the My Projects list in new Thimble, or is that outside the scope of this ticket?

**Comment by jbuck** [comment]
@hannahkane You are correct on all counts! And you'll be able to access your old makes in the my projects list in new Thimble

**Comment by hannahkane** [comment]
Cool. Thanks, @jbuck. This plan works for me.

/cc @ldecoursy and @KevZawacki so they know what's up

**Comment by hannahkane** [comment]
@jbuck - how long is the gap between step 1 and step 2 likely to be? Wondering for how long people will be unable to edit/remix their old makes.

**Comment by hannahkane** [comment]
disregard above question. I understand my error - people will continue to be able to access their own makes in old Thimble, we're just turning off the Remix capability. (Correct me if that's wrong.)

**Comment by jbuck** [comment]
@hannahkane probably an hour or two

**Comment by hannahkane** [comment]
sweet. thanks.

**Comment by hannahkane** [comment]
Can we decide when we're going to do this exactly, so that we can give people a heads up that old Thimble makes will be read-only for a few hours. Possible to do this over a weekend?

**Comment by hannahkane** [comment]
To check my understanding again, @jbuck, could you please fact-check these user-facing questions/answers we could in theory add to SUMO:

**How do I access projects made with the pre-September 2015 version of Thimble?**
Sign in to thimble.mozilla.org and mouse over the menu in the top right, where your name appears. Click "Your Projects." You'll see a list of any projects you've created with the latest version of Thimble, as well as a list of projects you made with the older version.

**How do I access projects made with Popcorn Maker and Appmaker (now retired)?**
Sign in to teach.mozilla.org, and click on your name in the top left to expand the account menu. Click on "Your Projects." You'll see all of the projects you created with Popcorn Maker and Appmaker (along with projects you made with older versions of Thimble and X-Ray Goggles). Please note: these projects are no longer editable, but you can still view them and share them with others.

**Comment by ldecoursy** [comment]
Should we add a note under the second Q that you can also bookmark teach.mozilla.org/me?

**Comment by jbuck** [comment]
@hannahkane I don't want to set a date until @cadecairos or I have written the code to do the migration. We'll update this thread when we've done that! I'd personally prefer to do it during the weekday because if something goes wrong then we can easily work with people to fix it and/or roll it back.

As for the SUMO FAQs, those answers look good to me!

**Comment by hannahkane** [comment]
ok, thanks @jbuck!

**Comment by mickfuzz** [comment]
This would be good to have sorted before Moz Fest otherwise a lot of activities linked to from Teach DOT won't work. Also a heads up would have been nice as I had a session teaching teacher trainers to use Thimble yesterday and well the old activities didn't work. 
Maybe if there isn't a clear migration plan in place yet it's worth turning write back on until it is.

**Comment by jgmac1106** [comment]
I just wonder if a manual migration is quicker all around if the migration will be extensive work.

As of now  if it is a project that is linked to through things like Teach DOT or Made with Code does it make more sense to transfer these manually and let the bigger ticket issues get sorted out?

Honestly if the transition is going to take up a huge effort across multiple heartbeats would it be better to just drop and leave the old makes in a read only state like popcorn and appmaker?

How many projects are linked to and receive heavy traffic? We can get that data. Move projects manually.

How many really active monthly users in the community did old Thimble have? We can reach out to them and encourage them to move their projects manually. Out of all mine, I probably want 6-7. Might be the same for others.

Things are just so different between the two versions (such as the multiple files, image hosting, and tutorial structure) I just worry the migration effort might take too many people far too long.

But I also no nothing of your magical whizz-bang technofuture machines. So maybe it isn't an issue.

**Comment by jbuck** [comment]
I spoke to @cadecairos and we're pretty confident we'll have this done by the end of the week. We'll update this bug with a specific time when we've written some code!

**Comment by humphd** [comment]
Wow! @jbuck++, @cadecairos++

**Comment by hannahkane** [comment]
Thanks, @jbuck and @cadecairos !!!

**Comment by hannahkane** [comment]
Has there been progress on this ticket?

**Comment by cadecairos** [comment]
@hannahkane Yup, I'm in the midst of testing and debugging the migration strategy on my local machine. @jbuck and I are hoping to get it finished tomorrow.

**Comment by hannahkane** [comment]
Rad, thanks! cc @KevZawacki so he can follow along, since we're getting questions about this from users.

**Comment by hannahkane** [comment]
@cadecairos @jbuck - is there an update on this one?

**Comment by simonwex** [comment]
Hey @hannahkane we ran into a problem with this export and EOY activities have taken the attention of @jbuck and @cadecairos.

Is there a timeline that has been communicated externally? I suggest we move this to post-orlando.

**Comment by hannahkane** [comment]
Thanks for the update. I think we can probably wait until post-Orlando, but pinging @KevZawacki and @ldecoursy to share what we've communicated externally. (Summary since this ticket is long: this is the final step in migrating user's old Thimble makes to the new Thimble.)

**Comment by ldecoursy** [comment]
We haven't communicated a date, but as mentioned above, we have been getting questions from users. Was hoping we'd have it sorted before Hour of Code, which is next week. Based on the EOY activities, is it still feasible to get done after Orlando but before Dec. 31?

**Comment by gideonthomas** [comment]
This still involves some work on the publish-side and based on a conversation during the Thimble standups, moving out of Dizzneyland and into Final Stride.

**Comment by cadecairos** [comment]
@jbuck I'm pretty sure I've figured out how to safely get the control characters out without stripping newlines and tabs and other save (but non-printable characters)

`tr -cd '\11\12\15\40-\176'`

we've already migrated staging with the other command we used for sanitizing (`tr -cd '[:print:]\n'`)

But I migrated the staging data successfully on local databases, so yay.

**Comment by gideonthomas** [comment]
Moving out of Jan 29th milestone since this is on hold until we finish localization.

**Comment by cadecairos** [comment]
I'm going to track this in a devops ticket: MozillaFoundation/mofo-devops#302
