### ISSUE TITLE
When I load a project, the file tray doesn't show any file as 'selected'

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.mozilla.org#634]
At first, even though index.html is selected and being edited, that is not reflected in the file tray...
![image](https://cloud.githubusercontent.com/assets/25212/8436882/5b63d6a4-1f10-11e5-8219-f66d13aab461.png)

Later, as I switch between files, the currently opened file has a different treatment...
![image](https://cloud.githubusercontent.com/assets/25212/8436902/78605c8c-1f10-11e5-9006-d80ae843c17d.png)

**Comment by humphd** [comment]
At the top of your screenshot, beside "EDITOR" it says "index.html" which is another kind of selection.  See discussion in #637.

**Comment by flukeout** [comment]
@humphd I read over the comment in #637 and agree that if the technical effort is significant, then it's not worth pursuing. However, the desired behaviour (opened file is highlighted in file tray) already seems to work as designed **except** when the editor first loads. Would it just be a matter of firing an extra event to highlight the file on initial load?

**Comment by flukeout** [comment]
One thing I noticed is that it only becomes deselected the first time you start editing it. If you switch files and go back to it, it stays selected when you edit.

I bet this has something to do with how the file is added to the working set. I bet we first display the file as selected in the non-working set, then as soon as we edit it, we display the file in the working set, and it loses the selection. Then, since it stays in the working set, the selected file highlight works as expected.

**Comment by flukeout** [comment]
Closing as it's in the brackets repo already: https://github.com/mozilla/thimble.mozilla.org/issues/634
