### ISSUE TITLE
Published project URLs

### ISSUE THREAD

**Issue by gideonthomas** [mozilla/thimble.mozilla.org#693]
A published project URL atm follows a template similar to `host/projectName/path/to/File`. This however complicates renaming a project significantly since we'd have to rename each and every key in S3 for that project (which involves several steps).

We need to determine how important it is that the URLs are readable i.e. `/host/projectName/path/to/file` vs. `/host/randomString/path/to/file` since the second case would make the renaming logic a lot more straightforward.

cc @flukeout

**Comment by flukeout** [comment]
For reference...

* Webmaker - ```https://beta.webmaker.org/#/project?user=443854&project=3872```
* Current Thimble - ```https://mofoluke.makes.org/thimble/NDkzNjE3NjY0/my-project-name```

**Comment by humphd** [comment]
@jbuck suggests that we should do `makes.org/<user>/<project-name>`.  I think that's right, and will eliminate a bunch of problems with user sub-domains.  So I suggest we do:

`makes.org/flukeout/b1/my-project-name` or, if it were totally up to me: makes.org/flukeout/b1 (no project name at all, just some "random" string).

**Comment by gideonthomas** [comment]
Right now we do `/<username>/<project-id>` we can iterate on this

**Comment by gideonthomas** [comment]
Also, refer to https://github.com/mozilla/thimble.webmaker.org/issues/707

**Comment by humphd** [comment]
We stalled on this, but @jbuck says that we can register a domain and use that vs. the current random cloudfront one.

@hannahkane, can you figure out what this should be, and let's just do it.  I think we should do it sooner rather than later, for indexing purposes.

**Comment by hannahkane** [comment]
Are we making a thimble-specific decision here, or will this apply to all projects including Webmaker?

cc @simonwex @xmatthewx

**Comment by jbuck** [comment]
It'd apply to thimble and goggles

**Comment by hannahkane** [comment]
this feels like a branding decision. I'm not the right person to make it. @HPaulJohnson @cassiemc - any thoughts on this?

**Comment by jbuck** [comment]
Also, don't list preferred domain names here in this thread; please discuss somewhere private so we don't have someone grab the domain before we can :)

**Comment by cassiemc** [comment]
If we can't talk about domains here let's book a meeting time and hash it out

**Comment by jbuck** [comment]
A private github repo issue would also work

**Comment by hannahkane** [comment]
Can we put published projects on thimble.mozilla.org/[user]/...?

(per discussion with @HPaulJohnson and @cassiemc)

**Comment by jbuck** [comment]
@hannahkane Unfortunately not, it has to be a completely separate domain. Because users can write whatever javascript they want in their projects, if we put published projects on thimble.mozilla.org they'd be able to write malicious projects that do wonderful things like delete all your projects simply by visiting a site.

**Comment by jbuck** [comment]
We've got the domain thimbleprojects.org [registered and ready for use](https://github.com/MozillaFoundation/mofo-devops/issues/209). We need to do some migration in the database and credential rotation though

**Comment by davidascher** [comment]
I'm out of the loop: what's wrong w/ makes.org?

**Comment by hannahkane** [comment]
I think we wanted better branding, plus we've been evolving to using "projects" rather than "makes" as the terminology.

**Comment by gideonthomas** [comment]
Closing this issue since we have not had any negative feedback from users concerning what the url looks like indicating that our current system works fine and it seems like most of the time they simply copy/paste the urls to share.
