### ISSUE TITLE
Measuring Learning Impact by analysing Thimble Data

### ISSUE THREAD

**Issue by adamlofting** [mozilla/thimble.mozilla.org#730]
Following on from the conversation started in #653 I promised to setup a document where we could continue the Learning Analytics conversation asynchronously.

Here is that EtherPad:
- https://etherpad.mozilla.org/indicators-of-learning-in-thimble-data

After making some notes in the pad, I suggest pinging people via this ticket to create notifications.
@flukeout @hannahkane @humphd

**Comment by hannahkane** [comment]
Thanks, @adamlofting. I added a few things to the pad.

**Comment by hannahkane** [comment]
Wondering if we can choose an initial set of data to track by the end of this heartbeat? Let's start simple. @adamlofting - what do you think?

**Comment by jgmac1106** [comment]
If you need an initial data set to test feel free to see if anything is
easily surfaceable in my makes.

I am totally self taught through Thimble so looking at my data for patterns
of growth could test basic code counts and complexity growth.

**Comment by KevZawacki** [comment]
@hannahkane Yep, this would be a great angle!

**Comment by adamlofting** [comment]
For inspiration: http://www.drscratch.org 

cc @davidascher

**Comment by hannahkane** [comment]
And this via @amirad: http://dl.acm.org/citation.cfm?id=2787709

**Comment by flukeout** [comment]
Some notes from chats at Mozfest: 
https://docs.google.com/document/d/1iaE-Wy2WXpuo9RTgdhSbg4NVQPZKH9L9B_D2StPNdsk/edit?ts=5649f143&actionButton=1

**Comment by gideonthomas** [comment]
@hannahkane are we moving forward with this in anyway?

**Comment by hannahkane** [comment]
I think we should keep this open because the answer is....I'm not sure. :) cc @davidascher to weigh in on possible partnership opportunities

**Comment by davidascher** [comment]
My opinion is that while getting thimble data published is a good idea, it
does not currently seem a critical consequence of the strategy as written.
It could totally show up though, but it doesn't feel like a P1.

**Comment by gideonthomas** [comment]
Discussion moved to https://github.com/mozilla/thimble.mozilla.org/issues/1516
