### ISSUE TITLE
Brief flash of unstyled content on the Details Bar when a published project is viewed.

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.mozilla.org#752]
**What's going on**
When you first open a published Thimble project, the title of the project briefly appears in large text above the project details. Once the Javascript & CSS for the Remix button loads, this content then disappears. It is later visible, as expected, when you hover over the remix Button, like this...

![image](https://cloud.githubusercontent.com/assets/25212/12368055/80848f4a-bb9c-11e5-9c5e-64d7f422e3b3.png)

**Note** - By "Details Bar", I'm referring to the white box (visible above) when a user hovers over the Remix button.

**Steps to reproduce**
- Load up a published project like http://bramble-staging.s3-website-us-east-1.amazonaws.com/flukeout/77/
- Refresh it over and over and keep an eye on the top part of the page
- Sometimes you see the unstyled markup (like the project title) of the details bar for a bit before it turns into the styled header

**Solutions**
I think what we can do is just apply an inline style like `display: none` to markup that wraps the details bar. Once the JS and CSS loads, we can remove this inline style.

Alternatively, we can inline all of the styles in a `<style>` tag so we don't have to wait for any external resources to load.

I'm not sure if these approaches will work, but they're worth trying out.

**Comment by gideonthomas** [comment]
Hmm I think hiding it with `display: none` until the stylesheet is loaded is probably the best solution.

**Comment by flukeout** [comment]
This looks pretty bad, and takes about 2 seconds to go away every time a project loads...

![image](https://cloud.githubusercontent.com/assets/25212/9257772/486b1fa8-41ac-11e5-9355-5217707fd679.png)

**Comment by humphd** [comment]
@flukeout Is this still an issue?

**Comment by flukeout** [comment]
Closing because it will be addressed #1107

**Comment by flukeout** [comment]
Opening becuase hasn't been addressed. It's not as noticeable locally, but definitely a problem on staging and production. Taking it on now.

**Comment by flukeout** [comment]
This is still happening, especially when loading a project for the first time.

**Comment by flukeout** [comment]
I'll update this to include a real project example which demonstrates the problem.

**Comment by flukeout** [comment]
Closing this as I can't reproduce this - even when simulating a 3G connection in the browser.
