### ISSUE TITLE
Remove duplicate encryption of oauth token

### ISSUE THREAD

**Issue by sedge** [mozilla/thimble.mozilla.org#785]
We [already encrypt the cookie session](https://github.com/mozilla/thimble.webmaker.org/blob/bramble/app.js#L62), but also [encrypt](https://github.com/mozilla/thimble.webmaker.org/blob/052833ae5f9e150c930420f1ea9ebe202e9240fc/routes/index.js#L135) and [decrypt](https://github.com/mozilla/thimble.webmaker.org/blob/bramble/lib/middleware.js#L506) the oauth token. This was an oversight in the implementation, and there isn't really added security since both encryptions use the same secret.

Not decrypting twice will also speed up requests.

Shoutout to @cadecairos for identifying this!

**Comment by cadecairos** [comment]
:+1:

**Comment by gideonthomas** [comment]
Closing this as we see no perf consequences of doing this
