### ISSUE TITLE
Determine whether to add a project/ root dir to export zip

### ISSUE THREAD

**Issue by humphd** [mozilla/thimble.mozilla.org#889]
This is something @Pomax raised, and I've been pondering it ever since.  When you export your project as a `.zip` file, we currently take everything in your project, and add it to a `project.zip` file, with things rooted in `project/*`.  This means that `index.html` in your project becomes `project/index.html` in the zip file.  It's generally seen as bad form to have archive files expand directly into the current directory, since you end up littering your current working dir with a bunch of files: most people root their archive with some folder to avoid this mess.

But consider the case of someone exporting a project, emailing it to a friend, and then that friend dragging it into Thimble.  It will work, but they will end up with a `project/` subdir with all the files in that.  Should we try and preempt this, and add a special case for `project/*` and strip it?  Or should I go against good practice and throw away `project/` altogether, and just archive exactly what's in your project?

cc @simonwex, @flukeout

**Comment by humphd** [comment]
@flukeout suggests using `thimble-project/*` and then watch for this and nuke it when we import.

**Comment by flukeout** [comment]
@humphd I think exporting / importing zip files is pretty fringe so I'm happy to close this unless we run into it again or hear about it from users.

**Comment by Pomax** [comment]
Hello I am a user =)

Being able to drag my code into Thimble for immediate editing and then getting it back out with an export is actually really nice. Rather than close, I'd say "let's go with `thimble-project` and if an imported zip only contains that dir at the top level, move everything up one level".

It's a nice feature to have, an interesting feature to work on for contributors, and opens up thimble as a roundtripping workflow tool that it currently simple cannot be used for.

**Comment by humphd** [comment]
The code for this is in here https://github.com/mozilla/brackets/blob/master/src/filesystem/impls/filer/ArchiveUtils.js.  It would be pretty easy to change.

**Comment by humphd** [comment]
I've suggested that @Riyuzakii work on this, and I'll mentor.

**Comment by Riyuzakii** [comment]
@humphd What are the things that i need to know to fix this bug , because i saw the code and i am quite confused.

**Comment by humphd** [comment]
@Riyuzakii we have code that allows a user to a) download a `project.zip` archive file; and b) drag-and-drop a `*.zip` file into the file tree, see:

* Import a zip: https://github.com/mozilla/thimble.mozilla.org/wiki/Using-Thimble#upload-archives
* Export a zip: https://github.com/mozilla/thimble.mozilla.org/wiki/Using-Thimble#export-a-project

The code that does this automatically takes your files, and prepends a `project/*` parent directory to  everything:

https://github.com/mozilla/brackets/blob/master/src/filesystem/impls/filer/ArchiveUtils.js#L153-L156

We do this because it's considered good form to always have a zip file expand into a directory vs. into the current directory (it makes it easier to delete or move the files afterward).

In the case that you export a `project.zip` from Thimble on one computer, then on another computer want to drag-and-drop that `project.zip` back into Thimble, it would be nice if we **ignored** the `project/*` parent folder and just extracted the files directly into the current directory--otherwise you have to do everything inside a `project/` dir now, and if you exported/imported again, you'd have `project/project/*` etc.

When we do the extraction, we first begin by scanning all the files/folders in the `zip` archive and build a list of filenames:

https://github.com/mozilla/brackets/blob/master/src/filesystem/impls/filer/ArchiveUtils.js#L82-L93

Right here, we could do a bit more work to look for files that begin with `project/` and then strip that so that a file `project/index.html` becomes just `index.html`.

Let me know if this makes sense or not, and if you have more questions.  You can also chat with the developers by using Mozilla's Thimble channel on their Mattermost server, see https://github.com/mozilla/thimble.mozilla.org#contact-us.

**Comment by Riyuzakii** [comment]
@humphd no it didn't make much sense but i think that's because i know only basic level javascript.

**Comment by humphd** [comment]
@Riyuzakii OK, got it.  Maybe this isn't a good first project then?  We use a lot of JS, and in some complex ways.  If you decide you want to try things, we'll try to help you here.  If it's too much, no problem.

**Comment by Riyuzakii** [comment]
@humphd I definitely want to do this and i have even started learning JS further.

**Comment by humphd** [comment]
@Riyuzakii how is this going?  Do you need some help?

**Comment by Riyuzakii** [comment]
@humphd I have been a bit busy with my mid-semester exams for the past week and they end on sunday so i'll restart then.

**Comment by humphd** [comment]
@Riyuzakii I'm going to put this bug back into the general pool of available bugs.  If you decide you want to work on something, let me know and I'll try to find you another one.

**Comment by humphd** [comment]
NOTE: I'm refactoring the code this will need to change, so be aware of https://github.com/mozilla/brackets/pull/659

**Comment by simon66** [comment]
Any luck I can tackle on this bug? I worked on this file while fixing issue mozilla/brackets#596 so I'm familiar with the code. Or should I wait for your PR?

**Comment by humphd** [comment]
@simon66 go for it.  NOTE: I'm changing this code a lot in https://github.com/mozilla/brackets/pull/659 which should hopefully land soon.  I'm just waiting on https://github.com/mozilla/brackets/pull/635 to merge first.

**Comment by humphd** [comment]
I've landed #659 so, feel free to rebase and finish this.
